jhotdraw: org.jhotdraw.draw.event.BezierNodeEdit Class Reference
org.jhotdraw.draw.event.BezierNodeEdit Class Reference
Public Member Functions
BezierNodeEdit (BezierFigure owner, int index, BezierPath.Node oldValue, BezierPath.Node newValue)
String getPresentationName ()
void redo () throws CannotRedoException
void undo () throws CannotUndoException
boolean addEdit (UndoableEdit anEdit)
Detailed Description
An
UndoableEdit
event which can undo a change of a node in a BezierFigure.
Version
Id
BezierNodeEdit.java -1
Author
Werner Randelshofer
Constructor & Destructor Documentation
BezierNodeEdit()
org.jhotdraw.draw.event.BezierNodeEdit.BezierNodeEdit (BezierFigure owner, int index, BezierPath.Node oldValue, BezierPath.Node newValue)
Creates a new instance.
Referenced by org.jhotdraw.draw.event.BezierNodeEdit.addEdit().
Member Function Documentation
addEdit()
boolean org.jhotdraw.draw.event.BezierNodeEdit.addEdit (UndoableEdit anEdit)
References org.jhotdraw.draw.event.BezierNodeEdit.BezierNodeEdit().
getPresentationName()
String org.jhotdraw.draw.event.BezierNodeEdit.getPresentationName ()
redo()
void org.jhotdraw.draw.event.BezierNodeEdit.redo () throws CannotRedoException
References org.jhotdraw.draw.figure.AbstractFigure.changed(), org.jhotdraw.draw.figure.BezierFigure.setNode(), and org.jhotdraw.draw.figure.AbstractFigure.willChange().
Referenced by org.jhotdraw.draw.handle.BezierControlPointHandle.trackEnd(), and org.jhotdraw.draw.handle.BezierNodeHandle.trackEnd().
undo()
void org.jhotdraw.draw.event.BezierNodeEdit.undo () throws CannotUndoException
References org.jhotdraw.draw.figure.AbstractFigure.changed(), org.jhotdraw.draw.figure.BezierFigure.setNode(), and org.jhotdraw.draw.figure.AbstractFigure.willChange().
The documentation for this class was generated from the following file:
jhotdraw-core/src/main/java/org/jhotdraw/draw/event/BezierNodeEdit.java