jhotdraw: org.jhotdraw.draw.locator.FontSizeLocator Class Reference
org.jhotdraw.draw.locator.FontSizeLocator Class Reference
Public Member Functions
FontSizeLocator ()
Point2D.Double locate (Figure owner)
Point2D.Double locate (Figure owner, Figure dependent)
Detailed Description
FontSizeLocator
is used by org.jhotdraw.draw.handle.FontSizeHandle to locate its position on the drawing.
Author
Werner Randelshofer
Version
$Id$
Constructor & Destructor Documentation
FontSizeLocator()
org.jhotdraw.draw.locator.FontSizeLocator.FontSizeLocator ()
Creates a new instance.
Member Function Documentation
locate() [1/2]
Point2D.Double org.jhotdraw.draw.locator.FontSizeLocator.locate (Figure owner)
Locates a position on the provided figure.
Returns
a Point2D.Double on the figure.
Implements org.jhotdraw.draw.locator.Locator.
References org.jhotdraw.draw.figure.Figure.get(), and org.jhotdraw.draw.figure.Figure.getStartPoint().
Referenced by org.jhotdraw.draw.locator.FontSizeLocator.locate().
locate() [2/2]
Point2D.Double org.jhotdraw.draw.locator.FontSizeLocator.locate (Figure owner, Figure dependent)
Locates a position on the provided figure relative to the dependent figure.
Returns
a point on the figure.
Implements org.jhotdraw.draw.locator.Locator.
References org.jhotdraw.draw.locator.FontSizeLocator.locate().
The documentation for this class was generated from the following file:
jhotdraw-core/src/main/java/org/jhotdraw/draw/locator/FontSizeLocator.java