jhotdraw: org.jhotdraw.draw.figure.TriangleFigure Class Reference
org.jhotdraw.draw.figure.TriangleFigure Class Reference
Public Member Functions
TriangleFigure ()
TriangleFigure (Orientation direction)
TriangleFigure (double x, double y, double width, double height)
TriangleFigure (double x, double y, double width, double height, Orientation direction)
Connector findConnector (Point2D.Double p, ConnectionFigure prototype)
Connector findCompatibleConnector (Connector c, boolean isStartConnector)
Rectangle2D.Double getBounds ()
Collection< Handle > createHandles (int detailLevel)
BezierPath getBezierPath ()
boolean contains (Point2D.Double p)
void setBounds (Point2D.Double anchor, Point2D.Double lead)
Rectangle2D.Double getDrawingArea ()
Point2D.Double chop (Point2D.Double p)
void transform (AffineTransform tx)
TriangleFigure clone ()
void restoreTransformTo (Object geometry)
Object getTransformRestoreData ()
Public Member Functions inherited from org.jhotdraw.draw.figure.AbstractAttributedFigure
AbstractAttributedFigure ()
void setAttributeEnabled (AttributeKey<?> key, boolean b)
boolean isAttributeEnabled (AttributeKey<?> key)
void setAttributes (Map< AttributeKey<?>, Object > map)
Map< AttributeKey<?>, Object > getAttributes ()
Object getAttributesRestoreData ()
void restoreAttributesTo (Object restoreData)
void draw (Graphics2D g)
double getStrokeMiterLimitFactor ()
Rectangle2D.Double getDrawingArea (double factor)
void write (DOMOutput out) throws IOException
void read (DOMInput in) throws IOException
boolean hasAttribute (AttributeKey<?> key)
Public Member Functions inherited from org.jhotdraw.draw.figure.AbstractFigure
AbstractFigure ()
void addFigureListener (FigureListener l)
void removeFigureListener (FigureListener l)
void addNotify (Drawing d)
void removeNotify (Drawing d)
void fireAreaInvalidated ()
void fireFigureChanged ()
void remap (Map< Figure, Figure > oldToNew, boolean disconnectIfNotInMap)
Cursor getCursor (Point2D.Double p)
final void setBounds (Rectangle2D.Double bounds)
void willChange ()
void changed ()
boolean includes (Figure figure)
Figure findFigureInside (Point2D.Double p)
Collection< Action > getActions (Point2D.Double p)
Tool getTool (Point2D.Double p)
boolean handleMouseClick (Point2D.Double p, MouseEvent evt, DrawingView view)
boolean handleDrop (Point2D.Double p, Collection< Figure > droppedFigures, DrawingView view)
Point2D.Double getEndPoint ()
Point2D.Double getStartPoint ()
Dimension2DDouble getPreferredSize ()
boolean isConnectable ()
void setConnectable (boolean newValue)
boolean isSelectable ()
void setSelectable (boolean newValue)
boolean isRemovable ()
void setRemovable (boolean newValue)
boolean isTransformable ()
void setTransformable (boolean newValue)
boolean isVisible ()
void setVisible (boolean newValue)
Collection< Figure > getDecomposition ()
void requestRemove ()
int getLayer ()
String getToolTipText (Point2D.Double p)
String toString ()
Collection< Connector > getConnectors (ConnectionFigure prototype)
Public Member Functions inherited from org.jhotdraw.draw.figure.Figure
void addPropertyChangeListener (PropertyChangeListener listener)
void removePropertyChangeListener (PropertyChangeListener listener)
Protected Member Functions
void drawFill (Graphics2D g)
void drawStroke (Graphics2D g)
Protected Member Functions inherited from org.jhotdraw.draw.figure.AbstractAttributedFigure
abstract void drawFill (java.awt.Graphics2D g)
abstract void drawStroke (java.awt.Graphics2D g)
void drawText (java.awt.Graphics2D g)
void writeAttributes (DOMOutput out) throws IOException
void readAttributes (DOMInput in) throws IOException
AttributeKey<?> getAttributeKey (String name)
void applyAttributesTo (Figure that)
Protected Member Functions inherited from org.jhotdraw.draw.figure.AbstractFigure
Drawing getDrawing ()
Object getLock ()
void fireAreaInvalidated (Rectangle2D.Double invalidatedArea)
void fireAreaInvalidated (FigureEvent event)
void fireFigureRequestRemove ()
void fireFigureAdded ()
void fireFigureRemoved ()
void fireFigureChanged (Rectangle2D.Double changedArea)
void fireFigureChanged (FigureEvent event)
void fireFigureHandlesChanged ()
void fireUndoableEditHappened (UndoableEdit edit)
void invalidate ()
boolean isChanging ()
int getChangingDepth ()
void validate ()
FontRenderContext getFontRenderContext ()
Additional Inherited Members
Static Public Attributes inherited from org.jhotdraw.draw.figure.Figure
static final String CONNECTABLE_PROPERTY = "connectable"
static final String REMOVABLE_PROPERTY = "removable"
static final String SELECTABLE_PROPERTY = "selectable"
static final String TRANSFORMABLE_PROPERTY = "transformable"
Protected Attributes inherited from org.jhotdraw.draw.figure.AbstractFigure
EventListenerList listenerList = new EventListenerList()
int changingDepth = 0
Detailed Description
Implements a Figure with a triangular shape.
The tip of the triangle points in the direction specified by the attribute org.jhotdraw.draw.AttributeKeys#ORIENTATION.
This figure creates a OrientationHandle which allows to interactively change the orientation of the triangle.
Author
Werner Randelshofer
Version
$Id$
Constructor & Destructor Documentation
TriangleFigure() [1/4]
org.jhotdraw.draw.figure.TriangleFigure.TriangleFigure ()
Creates a new instance.
Referenced by org.jhotdraw.draw.figure.TriangleFigure.clone().
TriangleFigure() [2/4]
org.jhotdraw.draw.figure.TriangleFigure.TriangleFigure (Orientation direction)
TriangleFigure() [3/4]
org.jhotdraw.draw.figure.TriangleFigure.TriangleFigure (double x, double y, double width, double height)
TriangleFigure() [4/4]
org.jhotdraw.draw.figure.TriangleFigure.TriangleFigure (double x, double y, double width, double height, Orientation direction)
Member Function Documentation
chop()
Point2D.Double org.jhotdraw.draw.figure.TriangleFigure.chop (Point2D.Double p)
References org.jhotdraw.draw.figure.TriangleFigure.getBezierPath(), org.jhotdraw.draw.AttributeKeys.getPerpendicularHitGrowth(), and org.jhotdraw.draw.AttributeKeys.getStrokeTotalWidth().
Referenced by org.jhotdraw.draw.connector.ChopTriangleConnector.chop().
clone()
TriangleFigure org.jhotdraw.draw.figure.TriangleFigure.clone ()
Returns a clone of the figure, with clones of all aggregated figures, such as children and decorators. The cloned figure does not clone the list of FigureListeners from its original.
Reimplemented from org.jhotdraw.draw.figure.AbstractAttributedFigure.
References org.jhotdraw.draw.figure.TriangleFigure.clone(), and org.jhotdraw.draw.figure.TriangleFigure.TriangleFigure().
Referenced by org.jhotdraw.draw.figure.TriangleFigure.clone().
contains()
boolean org.jhotdraw.draw.figure.TriangleFigure.contains (Point2D.Double p)
Checks if a Point2D.Double is inside the figure.
Implements org.jhotdraw.draw.figure.Figure.
References org.jhotdraw.draw.figure.TriangleFigure.getBezierPath(), org.jhotdraw.draw.AttributeKeys.getPerpendicularHitGrowth(), and org.jhotdraw.draw.AttributeKeys.getStrokeTotalWidth().
createHandles()
Collection<Handle> org.jhotdraw.draw.figure.TriangleFigure.createHandles (int detailLevel)
Creates handles used to manipulate the figure.
Parameters
detailLevel The detail level of the handles. Usually this is 0 for bounding box handles and 1 for point handles. The value -1 is used by the SelectAreaTracker and the HandleTracker to highlight figures, over which the mouse pointer is hovering.
Returns
a Collection of handles
See also
Handle
Reimplemented from org.jhotdraw.draw.figure.AbstractFigure.
drawFill()
void org.jhotdraw.draw.figure.TriangleFigure.drawFill (Graphics2D g) protected
References org.jhotdraw.draw.figure.TriangleFigure.getBezierPath(), org.jhotdraw.draw.AttributeKeys.getPerpendicularFillGrowth(), org.jhotdraw.draw.AttributeKeys.getScaleFactorFromGraphics(), and org.jhotdraw.draw.AttributeKeys.getStrokeTotalWidth().
drawStroke()
void org.jhotdraw.draw.figure.TriangleFigure.drawStroke (Graphics2D g) protected
References org.jhotdraw.draw.figure.TriangleFigure.getBezierPath(), org.jhotdraw.draw.AttributeKeys.getPerpendicularDrawGrowth(), org.jhotdraw.draw.AttributeKeys.getScaleFactorFromGraphics(), and org.jhotdraw.draw.AttributeKeys.getStrokeTotalWidth().
findCompatibleConnector()
Connector org.jhotdraw.draw.figure.TriangleFigure.findCompatibleConnector (Connector c, boolean isStartConnector)
Returns a compatible connector. By default a org.jhotdraw.draw.connector.ChopTriangleConnector is returned.
Reimplemented from org.jhotdraw.draw.figure.AbstractFigure.
findConnector()
Connector org.jhotdraw.draw.figure.TriangleFigure.findConnector (Point2D.Double p, ConnectionFigure prototype)
Returns the Figures connector for the specified location. By default a org.jhotdraw.draw.connector.ChopTriangleConnector is returned.
Reimplemented from org.jhotdraw.draw.figure.AbstractFigure.
getBezierPath()
BezierPath org.jhotdraw.draw.figure.TriangleFigure.getBezierPath ()
Referenced by org.jhotdraw.draw.figure.TriangleFigure.chop(), org.jhotdraw.draw.figure.TriangleFigure.contains(), org.jhotdraw.draw.figure.TriangleFigure.drawFill(), and org.jhotdraw.draw.figure.TriangleFigure.drawStroke().
getBounds()
Rectangle2D.Double org.jhotdraw.draw.figure.TriangleFigure.getBounds ()
Returns the untransformed logical bounds of the figure as a Rectangle.
The bounds are used by Handle objects for adjusting the figure and for aligning the figure on a grid.
Implements org.jhotdraw.draw.figure.Figure.
Referenced by org.jhotdraw.draw.figure.TriangleFigure.getDrawingArea().
getDrawingArea()
Rectangle2D.Double org.jhotdraw.draw.figure.TriangleFigure.getDrawingArea ()
Returns the drawing area of the figure as a Rectangle.
The drawing area is used to inform DrawingView about the area that is needed to draw this figure.
The drawing area needs to be large enough, to take line width, line caps and other decorations into account that exceed the bounds of the Figure.
Reimplemented from org.jhotdraw.draw.figure.AbstractAttributedFigure.
References org.jhotdraw.draw.figure.TriangleFigure.getBounds(), and org.jhotdraw.draw.AttributeKeys.getStrokeTotalWidth().
getTransformRestoreData()
Object org.jhotdraw.draw.figure.TriangleFigure.getTransformRestoreData ()
Gets data which can be used to restore the transformation of the figure without loss of precision, after a transform has been applied to it.
See also
transform(AffineTransform)
Implements org.jhotdraw.draw.figure.Figure.
restoreTransformTo()
void org.jhotdraw.draw.figure.TriangleFigure.restoreTransformTo (Object restoreData)
Restores the transform of the figure to a previously stored state.
Implements org.jhotdraw.draw.figure.Figure.
setBounds()
void org.jhotdraw.draw.figure.TriangleFigure.setBounds (Point2D.Double start, Point2D.Double end)
Sets the logical and untransformed bounds of the figure.
This is used by Tool's which create a new Figure and by Tool's which connect a Figure to another Figure.
This is a basic operation which does not fire events. Use the following code sequence, if you need event firing:
figure.willChange();
figure.setBounds(...);
figure.changed();
Parameters
start the start point of the bounds
end the end point of the bounds
See also
getBounds
Reimplemented from org.jhotdraw.draw.figure.AbstractFigure.
Referenced by org.jhotdraw.draw.figure.TriangleFigure.transform().
transform()
void org.jhotdraw.draw.figure.TriangleFigure.transform (AffineTransform tx)
Moves the Figure to a new location.
Parameters
tx the transformation matrix.
Implements org.jhotdraw.draw.figure.Figure.
References org.jhotdraw.draw.figure.AbstractFigure.getEndPoint(), org.jhotdraw.draw.figure.AbstractFigure.getStartPoint(), and org.jhotdraw.draw.figure.TriangleFigure.setBounds().
The documentation for this class was generated from the following file:
jhotdraw-core/src/main/java/org/jhotdraw/draw/figure/TriangleFigure.java