jhotdraw: org.jhotdraw.draw.event.AbstractAttributeEditorHandler< T >.EventHandler Class Reference
org.jhotdraw.draw.event.AbstractAttributeEditorHandler< T >.EventHandler Class Reference
Public Member Functions
void selectionChanged (FigureSelectionEvent evt)
void propertyChange (PropertyChangeEvent evt)
void attributeChanged (FigureEvent e)
Public Member Functions inherited from org.jhotdraw.draw.event.FigureAdapter
void areaInvalidated (FigureEvent e)
void figureAdded (FigureEvent e)
void figureChanged (FigureEvent e)
void figureRemoved (FigureEvent e)
void figureRequestRemove (FigureEvent e)
void figureHandlesChanged (FigureEvent e)
Member Function Documentation
attributeChanged()
void org.jhotdraw.draw.event.AbstractAttributeEditorHandler< T >.EventHandler.attributeChanged (FigureEvent e)
Sent when an attribute of the figure has changed.
Reimplemented from org.jhotdraw.draw.event.FigureAdapter.
References org.jhotdraw.draw.event.AbstractAttributeEditorHandler< T >.attributeKey, org.jhotdraw.draw.event.FigureEvent.getAttribute(), and org.jhotdraw.draw.event.AbstractAttributeEditorHandler< T >.updateAttributeEditor().
propertyChange()
void org.jhotdraw.draw.event.AbstractAttributeEditorHandler< T >.EventHandler.propertyChange (PropertyChangeEvent evt)
References org.jhotdraw.draw.DrawingEditor.ACTIVE_VIEW_PROPERTY, org.jhotdraw.draw.event.AbstractAttributeEditorHandler< T >.activeView, org.jhotdraw.draw.event.AbstractAttributeEditorHandler< T >.attributeEditor, org.jhotdraw.draw.event.AbstractAttributeEditorHandler< T >.attributeKey, org.jhotdraw.draw.DrawingEditor.DEFAULT_ATTRIBUTE_PROPERTY_PREFIX, org.jhotdraw.draw.DrawingView.DRAWING_PROPERTY, org.jhotdraw.draw.event.AbstractAttributeEditorHandler< T >.editor, org.jhotdraw.draw.event.AbstractAttributeEditorHandler< T >.updateActiveView(), org.jhotdraw.draw.event.AbstractAttributeEditorHandler< T >.updateAttributeEditor(), and org.jhotdraw.draw.event.AbstractAttributeEditorHandler< T >.updateFigures().
selectionChanged()
void org.jhotdraw.draw.event.AbstractAttributeEditorHandler< T >.EventHandler.selectionChanged (FigureSelectionEvent evt)
Implements org.jhotdraw.draw.event.FigureSelectionListener.
References org.jhotdraw.draw.event.AbstractAttributeEditorHandler< T >.attributeRestoreData, org.jhotdraw.draw.event.AbstractAttributeEditorHandler< T >.getEditedFigures(), and org.jhotdraw.draw.event.AbstractAttributeEditorHandler< T >.updateAttributeEditor().
The documentation for this class was generated from the following file:
jhotdraw-core/src/main/java/org/jhotdraw/draw/event/AbstractAttributeEditorHandler.java