jhotdraw: org.jhotdraw.draw.handle.HandleAttributeKeys Class Reference
org.jhotdraw.draw.handle.HandleAttributeKeys Class Reference
Static Public Attributes
static final AttributeKey< Integer > HANDLE_SIZE = new AttributeKey<Integer>("handleSize", Integer.class, 7)
static final AttributeKey< Color > HANDLE_STROKE_COLOR = new AttributeKey<Color>("handleStrokeColor", Color.class, Color.WHITE)
static final AttributeKey< Color > HANDLE_FILL_COLOR = new AttributeKey<Color>("handleFillColor", Color.class, Color.BLACK)
static final AttributeKey< Stroke > HANDLE_STROKE = new AttributeKey<Stroke>("handleStroke", Stroke.class, new BasicStroke(1f))
static final AttributeKey< Color > HANDLE_STROKE_COLOR_DISABLED = new AttributeKey<Color>("handleStrokeColor", Color.class, STROKE_COLOR_DISABLED)
static final AttributeKey< Color > HANDLE_FILL_COLOR_DISABLED = new AttributeKey<Color>("handleFillColor", Color.class, FILL_COLOR_DISABLED)
static final AttributeKey< Color > ROTATE_HANDLE_STROKE_COLOR = new AttributeKey<Color>("rotateHandleStrokeColor", Color.class, Color.WHITE)
static final AttributeKey< Color > ROTATE_HANDLE_FILL_COLOR = new AttributeKey<Color>("rotateHandleFillColor", Color.class, Color.MAGENTA)
static final AttributeKey< Color > ROTATE_HANDLE_STROKE_COLOR_DISABLED = new AttributeKey<Color>("rotateHandleStrokeColorDisabled", Color.class, STROKE_COLOR_DISABLED)
static final AttributeKey< Color > ROTATE_HANDLE_FILL_COLOR_DISABLED = new AttributeKey<Color>("rotateHandleFillColorDisabled", Color.class, FILL_COLOR_DISABLED)
static final AttributeKey< Color > BEZIER_CONTROL_POINT_HANDLE_STROKE_COLOR = new AttributeKey<Color>("bezierControlPointHandleStrokeColor", Color.class, Color.WHITE)
static final AttributeKey< Color > BEZIER_CONTROL_POINT_HANDLE_FILL_COLOR = new AttributeKey<Color>("bezierControlPointHandleFillColor", Color.class, Color.BLUE)
static final AttributeKey< Color > BEZIER_TANGENT_COLOR_1 = new AttributeKey<Color>("bezierTangentColor1", Color.class, Color.WHITE)
static final AttributeKey< Color > BEZIER_TANGENT_COLOR_2 = new AttributeKey<Color>("bezierTangentColor1", Color.class, Color.BLUE)
static final AttributeKey< Stroke > BEZIER_TANGENT_STROKE_1
static final AttributeKey< Stroke > BEZIER_TANGENT_STROKE_2
static final AttributeKey< Color > BEZIER_NODE_HANDLE_STROKE_COLOR = new AttributeKey<Color>("bezierControlPointStrokeColor", Color.class, Color.WHITE)
static final AttributeKey< Color > BEZIER_NODE_HANDLE_FILL_COLOR = new AttributeKey<Color>("bezierControlPointFillColor", Color.class, new Color(0x00a8ff))
static final AttributeKey< Color > BEZIER_PATH_COLOR_1 = new AttributeKey<Color>("bezierPathColor1", Color.class, Color.WHITE)
static final AttributeKey< Color > BEZIER_PATH_COLOR_2 = new AttributeKey<Color>("bezierPathColor2", Color.class, new Color(0x00a8ff))
static final AttributeKey< Stroke > BEZIER_PATH_STROKE_1
static final AttributeKey< Stroke > BEZIER_PATH_STROKE_2
static final AttributeKey< Color > BEZIER_PATH_COLOR_1_HOVER = new AttributeKey<Color>("bezierPathColor1Hover", Color.class, null)
static final AttributeKey< Color > BEZIER_PATH_COLOR_2_HOVER = new AttributeKey<Color>("bezierPathColor2Hover", Color.class, new Color(0x00a8ff))
static final AttributeKey< Stroke > BEZIER_PATH_STROKE_1_HOVER
static final AttributeKey< Stroke > BEZIER_PATH_STROKE_2_HOVER
static final AttributeKey< Color > BEZIER_CONTROL_POINT_HANDLE_STROKE_COLOR_DISABLED = new AttributeKey<Color>("bezierControlPointHandleStrokeColorDisabled", Color.class, STROKE_COLOR_DISABLED)
static final AttributeKey< Color > BEZIER_CONTROL_POINT_HANDLE_FILL_COLOR_DISABLED = new AttributeKey<Color>("bezierControlPointHandleFillColorDisabled", Color.class, FILL_COLOR_DISABLED)
static final AttributeKey< Color > BEZIER_TANGENT_COLOR_1_DISABLED = new AttributeKey<Color>("bezierTangentColor1Disabled", Color.class, STROKE_COLOR_DISABLED)
static final AttributeKey< Color > BEZIER_TANGENT_COLOR_2_DISABLED = new AttributeKey<Color>("bezierTangentColor1Disabled", Color.class, FILL_COLOR_DISABLED)
static final AttributeKey< Stroke > BEZIER_TANGENT_STROKE_1_DISABLED
static final AttributeKey< Stroke > BEZIER_TANGENT_STROKE_2_DISABLED
static final AttributeKey< Color > BEZIER_NODE_HANDLE_STROKE_COLOR_DISABLED = new AttributeKey<Color>("bezierControlPointStrokeColorDisabled", Color.class, STROKE_COLOR_DISABLED)
static final AttributeKey< Color > BEZIER_NODE_HANDLE_FILL_COLOR_DISABLED = new AttributeKey<Color>("bezierControlPointFillColorDisabled", Color.class, FILL_COLOR_DISABLED)
static final AttributeKey< Color > BEZIER_PATH_COLOR_1_DISABLED = new AttributeKey<Color>("bezierPathColor1Disabled", Color.class, Color.WHITE)
static final AttributeKey< Color > BEZIER_PATH_COLOR_2_DISABLED = new AttributeKey<Color>("bezierPathColor2Disabled", Color.class, new Color(0x0))
static final AttributeKey< Stroke > BEZIER_PATH_STROKE_1_DISABLED
static final AttributeKey< Stroke > BEZIER_PATH_STROKE_2_DISABLED
static final AttributeKey< Color > SCALE_HANDLE_STROKE_COLOR = new AttributeKey<Color>("scaleHandleStrokeColor", Color.class, Color.WHITE)
static final AttributeKey< Color > SCALE_HANDLE_FILL_COLOR = new AttributeKey<Color>("scaleHandleFillColor", Color.class, Color.ORANGE.darker())
static final AttributeKey< Color > RESIZE_HANDLE_STROKE_COLOR = new AttributeKey<Color>("resizeHandleStrokeColor", Color.class, Color.WHITE)
static final AttributeKey< Color > RESIZE_HANDLE_FILL_COLOR = new AttributeKey<Color>("resizeHandleFillColor", Color.class, Color.BLUE)
static final AttributeKey< Color > RESIZE_BOUNDS_COLOR_1 = new AttributeKey<Color>("resizeBoundsColor1", Color.class, Color.WHITE)
static final AttributeKey< Color > RESIZE_BOUNDS_COLOR_2 = new AttributeKey<Color>("resizeBoundsColor2", Color.class, Color.BLUE)
static final AttributeKey< Stroke > RESIZE_BOUNDS_STROKE_1
static final AttributeKey< Stroke > RESIZE_BOUNDS_STROKE_2
static final AttributeKey< Color > RESIZE_BOUNDS_COLOR_1_DISABLED = new AttributeKey<Color>("resizeBoundsColor1Hover", Color.class, STROKE_COLOR_DISABLED)
static final AttributeKey< Color > RESIZE_BOUNDS_COLOR_2_DISABLED = new AttributeKey<Color>("resizeBoundsColor2Hover", Color.class, FILL_COLOR_DISABLED)
static final AttributeKey< Stroke > RESIZE_BOUNDS_STROKE_1_DISABLED
static final AttributeKey< Stroke > RESIZE_BOUNDS_STROKE_2_DISABLED
static final AttributeKey< Color > RESIZE_BOUNDS_COLOR_1_HOVER = new AttributeKey<Color>("resizeBoundsColor1Hover", Color.class, null)
static final AttributeKey< Color > RESIZE_BOUNDS_COLOR_2_HOVER = new AttributeKey<Color>("resizeBoundsColor2Hover", Color.class, Color.BLUE)
static final AttributeKey< Stroke > RESIZE_BOUNDS_STROKE_1_HOVER
static final AttributeKey< Stroke > RESIZE_BOUNDS_STROKE_2_HOVER
static final AttributeKey< Color > TRANSFORM_HANDLE_STROKE_COLOR = new AttributeKey<Color>("transformHandleStrokeColor", Color.class, Color.WHITE)
static final AttributeKey< Color > TRANSFORM_HANDLE_FILL_COLOR = new AttributeKey<Color>("transformHandleFillColor", Color.class, Color.MAGENTA)
static final AttributeKey< Color > TRANSFORM_HANDLE_STROKE_COLOR_DISABLED = new AttributeKey<Color>("transformHandleStrokeColorDisabled", Color.class, STROKE_COLOR_DISABLED)
static final AttributeKey< Color > TRANSFORM_HANDLE_FILL_COLOR_DISABLED = new AttributeKey<Color>("transformHandleFillColorDisabled", Color.class, FILL_COLOR_DISABLED)
static final AttributeKey< Color > TRANSFORM_BOUNDS_COLOR_1 = new AttributeKey<Color>("transformBoundsColor1", Color.class, Color.WHITE)
static final AttributeKey< Color > TRANSFORM_BOUNDS_COLOR_2 = new AttributeKey<Color>("transformBoundsColor2", Color.class, Color.MAGENTA)
static final AttributeKey< Stroke > TRANSFORM_BOUNDS_STROKE_1
static final AttributeKey< Stroke > TRANSFORM_BOUNDS_STROKE_2
static final AttributeKey< Color > TRANSFORM_BOUNDS_COLOR_1_HOVER = new AttributeKey<Color>("transformBoundsColor1Hover", Color.class, null)
static final AttributeKey< Color > TRANSFORM_BOUNDS_COLOR_2_HOVER = new AttributeKey<Color>("transformBoundsColor2Hover", Color.class, Color.MAGENTA)
static final AttributeKey< Stroke > TRANSFORM_BOUNDS_STROKE_1_HOVER
static final AttributeKey< Stroke > TRANSFORM_BOUNDS_STROKE_2_HOVER
static final AttributeKey< Color > TRANSFORM_BOUNDS_COLOR_1_DISABLED = new AttributeKey<Color>("transformBoundsColor1Disabled", Color.class, STROKE_COLOR_DISABLED)
static final AttributeKey< Color > TRANSFORM_BOUNDS_COLOR_2_DISABLED = new AttributeKey<Color>("transformBoundsColor2Disabled", Color.class, FILL_COLOR_DISABLED)
static final AttributeKey< Stroke > TRANSFORM_BOUNDS_STROKE_1_DISABLED
static final AttributeKey< Stroke > TRANSFORM_BOUNDS_STROKE_2_DISABLED
static final AttributeKey< Color > GROUP_HANDLE_STROKE_COLOR = new AttributeKey<Color>("transformHandleStrokeColor", Color.class, Color.WHITE)
static final AttributeKey< Color > GROUP_HANDLE_FILL_COLOR = new AttributeKey<Color>("transformHandleFillColor", Color.class, Color.MAGENTA)
static final AttributeKey< Color > GROUP_HANDLE_STROKE_COLOR_DISABLED = new AttributeKey<Color>("transformHandleStrokeColorDisabled", Color.class, STROKE_COLOR_DISABLED)
static final AttributeKey< Color > GROUP_HANDLE_FILL_COLOR_DISABLED = new AttributeKey<Color>("transformHandleFillColorDisabled", Color.class, FILL_COLOR_DISABLED)
static final AttributeKey< Color > GROUP_BOUNDS_COLOR_1 = new AttributeKey<Color>("transformBoundsColor1", Color.class, Color.WHITE)
static final AttributeKey< Color > GROUP_BOUNDS_COLOR_2 = new AttributeKey<Color>("transformBoundsColor2", Color.class, Color.MAGENTA)
static final AttributeKey< Stroke > GROUP_BOUNDS_STROKE_1
static final AttributeKey< Stroke > GROUP_BOUNDS_STROKE_2
static final AttributeKey< Color > GROUP_BOUNDS_COLOR_1_HOVER = new AttributeKey<Color>("transformBoundsColor1Hover", Color.class, null)
static final AttributeKey< Color > GROUP_BOUNDS_COLOR_2_HOVER = new AttributeKey<Color>("transformBoundsColor2Hover", Color.class, Color.MAGENTA)
static final AttributeKey< Stroke > GROUP_BOUNDS_STROKE_1_HOVER
static final AttributeKey< Stroke > GROUP_BOUNDS_STROKE_2_HOVER
static final AttributeKey< Color > GROUP_BOUNDS_COLOR_1_DISABLED = new AttributeKey<Color>("transformBoundsColor1Disabled", Color.class, STROKE_COLOR_DISABLED)
static final AttributeKey< Color > GROUP_BOUNDS_COLOR_2_DISABLED = new AttributeKey<Color>("transformBoundsColor2Disabled", Color.class, FILL_COLOR_DISABLED)
static final AttributeKey< Stroke > GROUP_BOUNDS_STROKE_1_DISABLED
static final AttributeKey< Stroke > GROUP_BOUNDS_STROKE_2_DISABLED
static final AttributeKey< Color > CONNECTED_CONNECTION_HANDLE_STROKE_COLOR = new AttributeKey<Color>("connectedConnectionHandleStrokeColor", Color.class, Color.BLACK)
static final AttributeKey< Color > CONNECTED_CONNECTION_HANDLE_FILL_COLOR = new AttributeKey<Color>("connectedConnectionHandleFillColor", Color.class, Color.GREEN)
static final AttributeKey< Color > DISCONNECTED_CONNECTION_HANDLE_STROKE_COLOR = new AttributeKey<Color>("disconnectedConnectionHandleStrokeColor", Color.class, Color.BLACK)
static final AttributeKey< Color > DISCONNECTED_CONNECTION_HANDLE_FILL_COLOR = new AttributeKey<Color>("disconnectedConnectionHandleFillColor", Color.class, Color.RED)
static final AttributeKey< Color > CONNECTED_CONNECTOR_HANDLE_STROKE_COLOR = new AttributeKey<Color>("connectedConnectorHandleStrokeColor", Color.class, Color.BLACK)
static final AttributeKey< Color > CONNECTED_CONNECTOR_HANDLE_FILL_COLOR = new AttributeKey<Color>("connectedConnectorHandleFillColor", Color.class, Color.GREEN)
static final AttributeKey< Color > DISCONNECTED_CONNECTOR_HANDLE_STROKE_COLOR = new AttributeKey<Color>("disconnectedConnectorHandleStrokeColor", Color.class, Color.BLACK)
static final AttributeKey< Color > DISCONNECTED_CONNECTOR_HANDLE_FILL_COLOR = new AttributeKey<Color>("disconnectedConnectorHandleFillColor", Color.class, Color.RED)
static final AttributeKey< Color > MOVE_HANDLE_STROKE_COLOR = new AttributeKey<Color>("moveHandleStrokeColor", Color.class, Color.BLACK)
static final AttributeKey< Color > MOVE_HANDLE_FILL_COLOR = new AttributeKey<Color>("moveHandleFillColor", Color.class, Color.WHITE)
static final AttributeKey< Color > NULL_HANDLE_STROKE_COLOR = new AttributeKey<Color>("nullHandleStrokeColor", Color.class, Color.DARK_GRAY)
static final AttributeKey< Color > NULL_HANDLE_FILL_COLOR = new AttributeKey<Color>("nullHandleFillColor", Color.class, null)
static final AttributeKey< Color > OVERFLOW_HANDLE_STROKE_COLOR = new AttributeKey<Color>("overlfowHandleStrokeColor", Color.class, Color.RED)
static final AttributeKey< Color > OVERFLOW_HANDLE_FILL_COLOR = new AttributeKey<Color>("overflowHandleFillColor", Color.class, null)
static final AttributeKey< Color > ATTRIBUTE_HANDLE_STROKE_COLOR = new AttributeKey<Color>("attributeHandleStrokeColor", Color.class, Color.BLACK)
static final AttributeKey< Color > ATTRIBUTE_HANDLE_FILL_COLOR = new AttributeKey<Color>("attributeSizeHandleFillColor", Color.class, Color.YELLOW)
static final AttributeKey< Color > ATTRIBUTE_HANDLE_STROKE_COLOR_DISABLED = new AttributeKey<Color>("attributeHandleStrokeColorDisabled", Color.class, STROKE_COLOR_DISABLED)
static final AttributeKey< Color > ATTRIBUTE_HANDLE_FILL_COLOR_DISABLED = new AttributeKey<Color>("attributeSizeHandleFillColorDisabled", Color.class, FILL_COLOR_DISABLED)
Detailed Description
Defines a put of well known Handle attributes.
If you want different attribute values for your own editor, put the desired values using DrawingEditor#setHandleAttribute(org.jhotdraw.draw.AttributeKey, java.lang.Object).
Author
Werner Randelshofer
Version
$Id$
Member Data Documentation
ATTRIBUTE_HANDLE_FILL_COLOR
final AttributeKey<Color> org.jhotdraw.draw.handle.HandleAttributeKeys.ATTRIBUTE_HANDLE_FILL_COLOR = new AttributeKey<Color>("attributeSizeHandleFillColor", Color.class, Color.YELLOW) static
Attribute handle fill color.
Referenced by org.jhotdraw.draw.handle.FontSizeHandle.draw(), org.jhotdraw.draw.handle.OrientationHandle.draw(), and org.jhotdraw.draw.handle.RoundRectangleRadiusHandle.draw().
ATTRIBUTE_HANDLE_FILL_COLOR_DISABLED
final AttributeKey<Color> org.jhotdraw.draw.handle.HandleAttributeKeys.ATTRIBUTE_HANDLE_FILL_COLOR_DISABLED = new AttributeKey<Color>("attributeSizeHandleFillColorDisabled", Color.class, FILL_COLOR_DISABLED) static
Attribute handle fill color.
Referenced by org.jhotdraw.draw.handle.RoundRectangleRadiusHandle.draw().
ATTRIBUTE_HANDLE_STROKE_COLOR
final AttributeKey<Color> org.jhotdraw.draw.handle.HandleAttributeKeys.ATTRIBUTE_HANDLE_STROKE_COLOR = new AttributeKey<Color>("attributeHandleStrokeColor", Color.class, Color.BLACK) static
Attribute handle stroke color.
Referenced by org.jhotdraw.draw.handle.FontSizeHandle.draw(), org.jhotdraw.draw.handle.OrientationHandle.draw(), and org.jhotdraw.draw.handle.RoundRectangleRadiusHandle.draw().
ATTRIBUTE_HANDLE_STROKE_COLOR_DISABLED
final AttributeKey<Color> org.jhotdraw.draw.handle.HandleAttributeKeys.ATTRIBUTE_HANDLE_STROKE_COLOR_DISABLED = new AttributeKey<Color>("attributeHandleStrokeColorDisabled", Color.class, STROKE_COLOR_DISABLED) static
Attribute handle stroke color.
Referenced by org.jhotdraw.draw.handle.RoundRectangleRadiusHandle.draw().
BEZIER_CONTROL_POINT_HANDLE_FILL_COLOR
final AttributeKey<Color> org.jhotdraw.draw.handle.HandleAttributeKeys.BEZIER_CONTROL_POINT_HANDLE_FILL_COLOR = new AttributeKey<Color>("bezierControlPointHandleFillColor", Color.class, Color.BLUE) static
Bezier control point handle fill color.
Referenced by org.jhotdraw.draw.handle.BezierControlPointHandle.draw().
BEZIER_CONTROL_POINT_HANDLE_FILL_COLOR_DISABLED
final AttributeKey<Color> org.jhotdraw.draw.handle.HandleAttributeKeys.BEZIER_CONTROL_POINT_HANDLE_FILL_COLOR_DISABLED = new AttributeKey<Color>("bezierControlPointHandleFillColorDisabled", Color.class, FILL_COLOR_DISABLED) static
Bezier control point handle fill color.
Referenced by org.jhotdraw.draw.handle.BezierControlPointHandle.draw().
BEZIER_CONTROL_POINT_HANDLE_STROKE_COLOR
final AttributeKey<Color> org.jhotdraw.draw.handle.HandleAttributeKeys.BEZIER_CONTROL_POINT_HANDLE_STROKE_COLOR = new AttributeKey<Color>("bezierControlPointHandleStrokeColor", Color.class, Color.WHITE) static
Bezier control point handle stroke color.
Referenced by org.jhotdraw.draw.handle.BezierControlPointHandle.draw().
BEZIER_CONTROL_POINT_HANDLE_STROKE_COLOR_DISABLED
final AttributeKey<Color> org.jhotdraw.draw.handle.HandleAttributeKeys.BEZIER_CONTROL_POINT_HANDLE_STROKE_COLOR_DISABLED = new AttributeKey<Color>("bezierControlPointHandleStrokeColorDisabled", Color.class, STROKE_COLOR_DISABLED) static
Bezier control point handle stroke color.
Referenced by org.jhotdraw.draw.handle.BezierControlPointHandle.draw().
BEZIER_NODE_HANDLE_FILL_COLOR
final AttributeKey<Color> org.jhotdraw.draw.handle.HandleAttributeKeys.BEZIER_NODE_HANDLE_FILL_COLOR = new AttributeKey<Color>("bezierControlPointFillColor", Color.class, new Color(0x00a8ff)) static
Bezier node handle fill color.
Referenced by org.jhotdraw.draw.handle.BezierNodeHandle.draw().
BEZIER_NODE_HANDLE_FILL_COLOR_DISABLED
final AttributeKey<Color> org.jhotdraw.draw.handle.HandleAttributeKeys.BEZIER_NODE_HANDLE_FILL_COLOR_DISABLED = new AttributeKey<Color>("bezierControlPointFillColorDisabled", Color.class, FILL_COLOR_DISABLED) static
Bezier node handle fill color.
Referenced by org.jhotdraw.draw.handle.BezierNodeHandle.draw().
BEZIER_NODE_HANDLE_STROKE_COLOR
final AttributeKey<Color> org.jhotdraw.draw.handle.HandleAttributeKeys.BEZIER_NODE_HANDLE_STROKE_COLOR = new AttributeKey<Color>("bezierControlPointStrokeColor", Color.class, Color.WHITE) static
Bezier node handle stroke color.
Referenced by org.jhotdraw.draw.handle.BezierNodeHandle.draw().
BEZIER_NODE_HANDLE_STROKE_COLOR_DISABLED
final AttributeKey<Color> org.jhotdraw.draw.handle.HandleAttributeKeys.BEZIER_NODE_HANDLE_STROKE_COLOR_DISABLED = new AttributeKey<Color>("bezierControlPointStrokeColorDisabled", Color.class, STROKE_COLOR_DISABLED) static
Bezier node handle stroke color.
Referenced by org.jhotdraw.draw.handle.BezierNodeHandle.draw().
BEZIER_PATH_COLOR_1
final AttributeKey<Color> org.jhotdraw.draw.handle.HandleAttributeKeys.BEZIER_PATH_COLOR_1 = new AttributeKey<Color>("bezierPathColor1", Color.class, Color.WHITE) static
Bezier path stroke color 1.
Referenced by org.jhotdraw.draw.handle.BezierOutlineHandle.draw().
BEZIER_PATH_COLOR_1_DISABLED
final AttributeKey<Color> org.jhotdraw.draw.handle.HandleAttributeKeys.BEZIER_PATH_COLOR_1_DISABLED = new AttributeKey<Color>("bezierPathColor1Disabled", Color.class, Color.WHITE) static
Bezier path stroke color 1.
Referenced by org.jhotdraw.draw.handle.BezierOutlineHandle.draw().
BEZIER_PATH_COLOR_1_HOVER
final AttributeKey<Color> org.jhotdraw.draw.handle.HandleAttributeKeys.BEZIER_PATH_COLOR_1_HOVER = new AttributeKey<Color>("bezierPathColor1Hover", Color.class, null) static
Bezier path hover stroke color 1.
Referenced by org.jhotdraw.draw.handle.BezierOutlineHandle.draw().
BEZIER_PATH_COLOR_2
final AttributeKey<Color> org.jhotdraw.draw.handle.HandleAttributeKeys.BEZIER_PATH_COLOR_2 = new AttributeKey<Color>("bezierPathColor2", Color.class, new Color(0x00a8ff)) static
Bezier path stroke color 2.
Referenced by org.jhotdraw.draw.handle.BezierOutlineHandle.draw().
BEZIER_PATH_COLOR_2_DISABLED
final AttributeKey<Color> org.jhotdraw.draw.handle.HandleAttributeKeys.BEZIER_PATH_COLOR_2_DISABLED = new AttributeKey<Color>("bezierPathColor2Disabled", Color.class, new Color(0x0)) static
Bezier path stroke color 2.
Referenced by org.jhotdraw.draw.handle.BezierOutlineHandle.draw().
BEZIER_PATH_COLOR_2_HOVER
final AttributeKey<Color> org.jhotdraw.draw.handle.HandleAttributeKeys.BEZIER_PATH_COLOR_2_HOVER = new AttributeKey<Color>("bezierPathColor2Hover", Color.class, new Color(0x00a8ff)) static
Bezier path hover stroke color 2.
Referenced by org.jhotdraw.draw.handle.BezierOutlineHandle.draw().
BEZIER_PATH_STROKE_1
final AttributeKey<Stroke> org.jhotdraw.draw.handle.HandleAttributeKeys.BEZIER_PATH_STROKE_1 static
Initial value:
= new AttributeKey<Stroke>("bezierPathStroke1", Stroke.class,
            new BasicStroke(3f, BasicStroke.CAP_SQUARE, BasicStroke.JOIN_BEVEL))
Bezier path stroke 1.
Referenced by org.jhotdraw.draw.handle.BezierOutlineHandle.draw().
BEZIER_PATH_STROKE_1_DISABLED
final AttributeKey<Stroke> org.jhotdraw.draw.handle.HandleAttributeKeys.BEZIER_PATH_STROKE_1_DISABLED static
Initial value:
= new AttributeKey<Stroke>("bezierPathStroke1Disabled", Stroke.class,
            new BasicStroke(3f, BasicStroke.CAP_SQUARE, BasicStroke.JOIN_BEVEL))
Bezier path stroke 1.
Referenced by org.jhotdraw.draw.handle.BezierOutlineHandle.draw().
BEZIER_PATH_STROKE_1_HOVER
final AttributeKey<Stroke> org.jhotdraw.draw.handle.HandleAttributeKeys.BEZIER_PATH_STROKE_1_HOVER static
Initial value:
= new AttributeKey<Stroke>("bezierPathStroke1Hover", Stroke.class,
            null)
Bezier path hover stroke 1.
Referenced by org.jhotdraw.draw.handle.BezierOutlineHandle.draw().
BEZIER_PATH_STROKE_2
final AttributeKey<Stroke> org.jhotdraw.draw.handle.HandleAttributeKeys.BEZIER_PATH_STROKE_2 static
Initial value:
= new AttributeKey<Stroke>("bezierPathStroke2", Stroke.class,
            new BasicStroke(1f))
Bezier path stroke 2.
Referenced by org.jhotdraw.draw.handle.BezierOutlineHandle.draw().
BEZIER_PATH_STROKE_2_DISABLED
final AttributeKey<Stroke> org.jhotdraw.draw.handle.HandleAttributeKeys.BEZIER_PATH_STROKE_2_DISABLED static
Initial value:
= new AttributeKey<Stroke>("bezierPathStroke2Disabled", Stroke.class,
            new BasicStroke(1f))
Bezier path stroke 2.
Referenced by org.jhotdraw.draw.handle.BezierOutlineHandle.draw().
BEZIER_PATH_STROKE_2_HOVER
final AttributeKey<Stroke> org.jhotdraw.draw.handle.HandleAttributeKeys.BEZIER_PATH_STROKE_2_HOVER static
Initial value:
= new AttributeKey<Stroke>("bezierPathStroke2Hover", Stroke.class,
            new BasicStroke(1f))
Bezier path hover stroke 2.
Referenced by org.jhotdraw.draw.handle.BezierOutlineHandle.draw().
BEZIER_TANGENT_COLOR_1
final AttributeKey<Color> org.jhotdraw.draw.handle.HandleAttributeKeys.BEZIER_TANGENT_COLOR_1 = new AttributeKey<Color>("bezierTangentColor1", Color.class, Color.WHITE) static
Bezier tangent line stroke color 1.
Referenced by org.jhotdraw.draw.handle.BezierControlPointHandle.draw().
BEZIER_TANGENT_COLOR_1_DISABLED
final AttributeKey<Color> org.jhotdraw.draw.handle.HandleAttributeKeys.BEZIER_TANGENT_COLOR_1_DISABLED = new AttributeKey<Color>("bezierTangentColor1Disabled", Color.class, STROKE_COLOR_DISABLED) static
Bezier tangent line stroke color 1.
Referenced by org.jhotdraw.draw.handle.BezierControlPointHandle.draw().
BEZIER_TANGENT_COLOR_2
final AttributeKey<Color> org.jhotdraw.draw.handle.HandleAttributeKeys.BEZIER_TANGENT_COLOR_2 = new AttributeKey<Color>("bezierTangentColor1", Color.class, Color.BLUE) static
Bezier tangent line stroke color 2.
Referenced by org.jhotdraw.draw.handle.BezierControlPointHandle.draw().
BEZIER_TANGENT_COLOR_2_DISABLED
final AttributeKey<Color> org.jhotdraw.draw.handle.HandleAttributeKeys.BEZIER_TANGENT_COLOR_2_DISABLED = new AttributeKey<Color>("bezierTangentColor1Disabled", Color.class, FILL_COLOR_DISABLED) static
Bezier tangent line stroke color 2.
Referenced by org.jhotdraw.draw.handle.BezierControlPointHandle.draw().
BEZIER_TANGENT_STROKE_1
final AttributeKey<Stroke> org.jhotdraw.draw.handle.HandleAttributeKeys.BEZIER_TANGENT_STROKE_1 static
Initial value:
= new AttributeKey<Stroke>("bezierTangentStroke1", Stroke.class,
            new BasicStroke(1f, BasicStroke.CAP_BUTT, BasicStroke.JOIN_BEVEL, 0f, new float[]{5f, 5f}, 0f))
Bezier tangent line stroke 1.
Referenced by org.jhotdraw.draw.handle.BezierControlPointHandle.draw().
BEZIER_TANGENT_STROKE_1_DISABLED
final AttributeKey<Stroke> org.jhotdraw.draw.handle.HandleAttributeKeys.BEZIER_TANGENT_STROKE_1_DISABLED static
Initial value:
= new AttributeKey<Stroke>("bezierTangentStroke1Disabled", Stroke.class,
            new BasicStroke(1f, BasicStroke.CAP_BUTT, BasicStroke.JOIN_BEVEL, 0f, new float[]{5f, 5f}, 0f))
Bezier tangent line stroke 1.
Referenced by org.jhotdraw.draw.handle.BezierControlPointHandle.draw().
BEZIER_TANGENT_STROKE_2
final AttributeKey<Stroke> org.jhotdraw.draw.handle.HandleAttributeKeys.BEZIER_TANGENT_STROKE_2 static
Initial value:
= new AttributeKey<Stroke>("bezierTangentStroke2", Stroke.class,
            new BasicStroke(1f, BasicStroke.CAP_BUTT, BasicStroke.JOIN_BEVEL, 0f, new float[]{5f, 5f}, 5f))
Bezier tangent line stroke 2.
Referenced by org.jhotdraw.draw.handle.BezierControlPointHandle.draw().
BEZIER_TANGENT_STROKE_2_DISABLED
final AttributeKey<Stroke> org.jhotdraw.draw.handle.HandleAttributeKeys.BEZIER_TANGENT_STROKE_2_DISABLED static
Initial value:
= new AttributeKey<Stroke>("bezierTangentStroke2Disabled", Stroke.class,
            new BasicStroke(1f, BasicStroke.CAP_BUTT, BasicStroke.JOIN_BEVEL, 0f, new float[]{5f, 5f}, 5f))
Bezier tangent line stroke 2.
Referenced by org.jhotdraw.draw.handle.BezierControlPointHandle.draw().
CONNECTED_CONNECTION_HANDLE_FILL_COLOR
final AttributeKey<Color> org.jhotdraw.draw.handle.HandleAttributeKeys.CONNECTED_CONNECTION_HANDLE_FILL_COLOR = new AttributeKey<Color>("connectedConnectionHandleFillColor", Color.class, Color.GREEN) static
Handle fill color.
Referenced by org.jhotdraw.draw.handle.AbstractConnectionHandle.draw().
CONNECTED_CONNECTION_HANDLE_STROKE_COLOR
final AttributeKey<Color> org.jhotdraw.draw.handle.HandleAttributeKeys.CONNECTED_CONNECTION_HANDLE_STROKE_COLOR = new AttributeKey<Color>("connectedConnectionHandleStrokeColor", Color.class, Color.BLACK) static
Handle stroke color.
Referenced by org.jhotdraw.draw.handle.AbstractConnectionHandle.draw().
CONNECTED_CONNECTOR_HANDLE_FILL_COLOR
final AttributeKey<Color> org.jhotdraw.draw.handle.HandleAttributeKeys.CONNECTED_CONNECTOR_HANDLE_FILL_COLOR = new AttributeKey<Color>("connectedConnectorHandleFillColor", Color.class, Color.GREEN) static
Handle fill color.
Referenced by org.jhotdraw.draw.handle.ConnectorHandle.draw().
CONNECTED_CONNECTOR_HANDLE_STROKE_COLOR
final AttributeKey<Color> org.jhotdraw.draw.handle.HandleAttributeKeys.CONNECTED_CONNECTOR_HANDLE_STROKE_COLOR = new AttributeKey<Color>("connectedConnectorHandleStrokeColor", Color.class, Color.BLACK) static
Handle stroke color.
Referenced by org.jhotdraw.draw.handle.ConnectorHandle.draw().
DISCONNECTED_CONNECTION_HANDLE_FILL_COLOR
final AttributeKey<Color> org.jhotdraw.draw.handle.HandleAttributeKeys.DISCONNECTED_CONNECTION_HANDLE_FILL_COLOR = new AttributeKey<Color>("disconnectedConnectionHandleFillColor", Color.class, Color.RED) static
Handle fill color.
Referenced by org.jhotdraw.draw.handle.AbstractConnectionHandle.draw().
DISCONNECTED_CONNECTION_HANDLE_STROKE_COLOR
final AttributeKey<Color> org.jhotdraw.draw.handle.HandleAttributeKeys.DISCONNECTED_CONNECTION_HANDLE_STROKE_COLOR = new AttributeKey<Color>("disconnectedConnectionHandleStrokeColor", Color.class, Color.BLACK) static
Handle stroke color.
Referenced by org.jhotdraw.draw.handle.AbstractConnectionHandle.draw().
DISCONNECTED_CONNECTOR_HANDLE_FILL_COLOR
final AttributeKey<Color> org.jhotdraw.draw.handle.HandleAttributeKeys.DISCONNECTED_CONNECTOR_HANDLE_FILL_COLOR = new AttributeKey<Color>("disconnectedConnectorHandleFillColor", Color.class, Color.RED) static
Handle fill color.
Referenced by org.jhotdraw.draw.handle.ConnectorHandle.draw().
DISCONNECTED_CONNECTOR_HANDLE_STROKE_COLOR
final AttributeKey<Color> org.jhotdraw.draw.handle.HandleAttributeKeys.DISCONNECTED_CONNECTOR_HANDLE_STROKE_COLOR = new AttributeKey<Color>("disconnectedConnectorHandleStrokeColor", Color.class, Color.BLACK) static
Handle stroke color.
Referenced by org.jhotdraw.draw.handle.ConnectorHandle.draw().
GROUP_BOUNDS_COLOR_1
final AttributeKey<Color> org.jhotdraw.draw.handle.HandleAttributeKeys.GROUP_BOUNDS_COLOR_1 = new AttributeKey<Color>("transformBoundsColor1", Color.class, Color.WHITE) static
Group bounds color 1.
GROUP_BOUNDS_COLOR_1_DISABLED
final AttributeKey<Color> org.jhotdraw.draw.handle.HandleAttributeKeys.GROUP_BOUNDS_COLOR_1_DISABLED = new AttributeKey<Color>("transformBoundsColor1Disabled", Color.class, STROKE_COLOR_DISABLED) static
Group bounds disabled color 1.
GROUP_BOUNDS_COLOR_1_HOVER
final AttributeKey<Color> org.jhotdraw.draw.handle.HandleAttributeKeys.GROUP_BOUNDS_COLOR_1_HOVER = new AttributeKey<Color>("transformBoundsColor1Hover", Color.class, null) static
Group bounds hover color 1.
GROUP_BOUNDS_COLOR_2
final AttributeKey<Color> org.jhotdraw.draw.handle.HandleAttributeKeys.GROUP_BOUNDS_COLOR_2 = new AttributeKey<Color>("transformBoundsColor2", Color.class, Color.MAGENTA) static
Group bounds color 2.
GROUP_BOUNDS_COLOR_2_DISABLED
final AttributeKey<Color> org.jhotdraw.draw.handle.HandleAttributeKeys.GROUP_BOUNDS_COLOR_2_DISABLED = new AttributeKey<Color>("transformBoundsColor2Disabled", Color.class, FILL_COLOR_DISABLED) static
Group bounds disabled color 2.
GROUP_BOUNDS_COLOR_2_HOVER
final AttributeKey<Color> org.jhotdraw.draw.handle.HandleAttributeKeys.GROUP_BOUNDS_COLOR_2_HOVER = new AttributeKey<Color>("transformBoundsColor2Hover", Color.class, Color.MAGENTA) static
Group bounds hover color 2.
GROUP_BOUNDS_STROKE_1
final AttributeKey<Stroke> org.jhotdraw.draw.handle.HandleAttributeKeys.GROUP_BOUNDS_STROKE_1 static
Initial value:
= new AttributeKey<Stroke>("transformBoundsStroke1", Stroke.class,
            new BasicStroke(3f, BasicStroke.CAP_SQUARE, BasicStroke.JOIN_BEVEL))
Group bounds stroke 1.
GROUP_BOUNDS_STROKE_1_DISABLED
final AttributeKey<Stroke> org.jhotdraw.draw.handle.HandleAttributeKeys.GROUP_BOUNDS_STROKE_1_DISABLED static
Initial value:
= new AttributeKey<Stroke>("transformBoundsStroke1Disabled", Stroke.class,
            new BasicStroke(3f))
Group bounds disabled stroke 1.
GROUP_BOUNDS_STROKE_1_HOVER
final AttributeKey<Stroke> org.jhotdraw.draw.handle.HandleAttributeKeys.GROUP_BOUNDS_STROKE_1_HOVER static
Initial value:
= new AttributeKey<Stroke>("transformBoundsStroke1Hover", Stroke.class,
            null)
Group bounds hover stroke 1.
GROUP_BOUNDS_STROKE_2
final AttributeKey<Stroke> org.jhotdraw.draw.handle.HandleAttributeKeys.GROUP_BOUNDS_STROKE_2 static
Initial value:
= new AttributeKey<Stroke>("transformBoundsStroke2", Stroke.class,
            new BasicStroke(1f, BasicStroke.CAP_BUTT, BasicStroke.JOIN_BEVEL, 1f, new float[]{2f, 2f}, 0f))
Group bounds stroke 2.
GROUP_BOUNDS_STROKE_2_DISABLED
final AttributeKey<Stroke> org.jhotdraw.draw.handle.HandleAttributeKeys.GROUP_BOUNDS_STROKE_2_DISABLED static
Initial value:
= new AttributeKey<Stroke>("transformBoundsStroke2Disabled", Stroke.class,
            new BasicStroke(1f))
Group bounds disabled stroke 2.
GROUP_BOUNDS_STROKE_2_HOVER
final AttributeKey<Stroke> org.jhotdraw.draw.handle.HandleAttributeKeys.GROUP_BOUNDS_STROKE_2_HOVER static
Initial value:
= new AttributeKey<Stroke>("transformBoundsStroke2Hover", Stroke.class,
            new BasicStroke(1f, BasicStroke.CAP_BUTT, BasicStroke.JOIN_BEVEL, 1f, new float[]{2f, 2f}, 0f))
Group bounds hover stroke 2.
GROUP_HANDLE_FILL_COLOR
final AttributeKey<Color> org.jhotdraw.draw.handle.HandleAttributeKeys.GROUP_HANDLE_FILL_COLOR = new AttributeKey<Color>("transformHandleFillColor", Color.class, Color.MAGENTA) static
Group handle fill color.
GROUP_HANDLE_FILL_COLOR_DISABLED
final AttributeKey<Color> org.jhotdraw.draw.handle.HandleAttributeKeys.GROUP_HANDLE_FILL_COLOR_DISABLED = new AttributeKey<Color>("transformHandleFillColorDisabled", Color.class, FILL_COLOR_DISABLED) static
Group handle fill color.
GROUP_HANDLE_STROKE_COLOR
final AttributeKey<Color> org.jhotdraw.draw.handle.HandleAttributeKeys.GROUP_HANDLE_STROKE_COLOR = new AttributeKey<Color>("transformHandleStrokeColor", Color.class, Color.WHITE) static
Group handle stroke color.
GROUP_HANDLE_STROKE_COLOR_DISABLED
final AttributeKey<Color> org.jhotdraw.draw.handle.HandleAttributeKeys.GROUP_HANDLE_STROKE_COLOR_DISABLED = new AttributeKey<Color>("transformHandleStrokeColorDisabled", Color.class, STROKE_COLOR_DISABLED) static
Group handle stroke color.
HANDLE_FILL_COLOR
final AttributeKey<Color> org.jhotdraw.draw.handle.HandleAttributeKeys.HANDLE_FILL_COLOR = new AttributeKey<Color>("handleFillColor", Color.class, Color.BLACK) static
General handle fill color.
Referenced by org.jhotdraw.draw.handle.AbstractHandle.draw().
HANDLE_FILL_COLOR_DISABLED
final AttributeKey<Color> org.jhotdraw.draw.handle.HandleAttributeKeys.HANDLE_FILL_COLOR_DISABLED = new AttributeKey<Color>("handleFillColor", Color.class, FILL_COLOR_DISABLED) static
General handle fill color.
HANDLE_SIZE
final AttributeKey<Integer> org.jhotdraw.draw.handle.HandleAttributeKeys.HANDLE_SIZE = new AttributeKey<Integer>("handleSize", Integer.class, 7) static
General handle size.
Referenced by org.jhotdraw.draw.handle.AbstractHandle.getHandlesize().
HANDLE_STROKE
final AttributeKey<Stroke> org.jhotdraw.draw.handle.HandleAttributeKeys.HANDLE_STROKE = new AttributeKey<Stroke>("handleStroke", Stroke.class, new BasicStroke(1f)) static
General handle stroke.
HANDLE_STROKE_COLOR
final AttributeKey<Color> org.jhotdraw.draw.handle.HandleAttributeKeys.HANDLE_STROKE_COLOR = new AttributeKey<Color>("handleStrokeColor", Color.class, Color.WHITE) static
General handle stroke color.
Referenced by org.jhotdraw.draw.handle.AbstractHandle.draw().
HANDLE_STROKE_COLOR_DISABLED
final AttributeKey<Color> org.jhotdraw.draw.handle.HandleAttributeKeys.HANDLE_STROKE_COLOR_DISABLED = new AttributeKey<Color>("handleStrokeColor", Color.class, STROKE_COLOR_DISABLED) static
General handle stroke color.
MOVE_HANDLE_FILL_COLOR
final AttributeKey<Color> org.jhotdraw.draw.handle.HandleAttributeKeys.MOVE_HANDLE_FILL_COLOR = new AttributeKey<Color>("moveHandleFillColor", Color.class, Color.WHITE) static
Handle fill color.
Referenced by org.jhotdraw.draw.handle.MoveHandle.draw().
MOVE_HANDLE_STROKE_COLOR
final AttributeKey<Color> org.jhotdraw.draw.handle.HandleAttributeKeys.MOVE_HANDLE_STROKE_COLOR = new AttributeKey<Color>("moveHandleStrokeColor", Color.class, Color.BLACK) static
Handle stroke color.
Referenced by org.jhotdraw.draw.handle.MoveHandle.draw().
NULL_HANDLE_FILL_COLOR
final AttributeKey<Color> org.jhotdraw.draw.handle.HandleAttributeKeys.NULL_HANDLE_FILL_COLOR = new AttributeKey<Color>("nullHandleFillColor", Color.class, null) static
Handle fill color.
Referenced by org.jhotdraw.draw.handle.MoveHandle.draw(), and org.jhotdraw.draw.handle.NullHandle.draw().
NULL_HANDLE_STROKE_COLOR
final AttributeKey<Color> org.jhotdraw.draw.handle.HandleAttributeKeys.NULL_HANDLE_STROKE_COLOR = new AttributeKey<Color>("nullHandleStrokeColor", Color.class, Color.DARK_GRAY) static
Handle stroke color.
Referenced by org.jhotdraw.draw.handle.MoveHandle.draw(), and org.jhotdraw.draw.handle.NullHandle.draw().
OVERFLOW_HANDLE_FILL_COLOR
final AttributeKey<Color> org.jhotdraw.draw.handle.HandleAttributeKeys.OVERFLOW_HANDLE_FILL_COLOR = new AttributeKey<Color>("overflowHandleFillColor", Color.class, null) static
Handle fill color.
Referenced by org.jhotdraw.draw.handle.TextOverflowHandle.draw().
OVERFLOW_HANDLE_STROKE_COLOR
final AttributeKey<Color> org.jhotdraw.draw.handle.HandleAttributeKeys.OVERFLOW_HANDLE_STROKE_COLOR = new AttributeKey<Color>("overlfowHandleStrokeColor", Color.class, Color.RED) static
Handle stroke color.
Referenced by org.jhotdraw.draw.handle.TextOverflowHandle.draw().
RESIZE_BOUNDS_COLOR_1
final AttributeKey<Color> org.jhotdraw.draw.handle.HandleAttributeKeys.RESIZE_BOUNDS_COLOR_1 = new AttributeKey<Color>("resizeBoundsColor1", Color.class, Color.WHITE) static
Resize bounds stroke color 1.
Referenced by org.jhotdraw.draw.handle.BoundsOutlineHandle.BoundsOutlineHandle().
RESIZE_BOUNDS_COLOR_1_DISABLED
final AttributeKey<Color> org.jhotdraw.draw.handle.HandleAttributeKeys.RESIZE_BOUNDS_COLOR_1_DISABLED = new AttributeKey<Color>("resizeBoundsColor1Hover", Color.class, STROKE_COLOR_DISABLED) static
Disabled resize bounds stroke color 1.
Referenced by org.jhotdraw.draw.handle.BoundsOutlineHandle.BoundsOutlineHandle().
RESIZE_BOUNDS_COLOR_1_HOVER
final AttributeKey<Color> org.jhotdraw.draw.handle.HandleAttributeKeys.RESIZE_BOUNDS_COLOR_1_HOVER = new AttributeKey<Color>("resizeBoundsColor1Hover", Color.class, null) static
Handle bounds hover stroke color 1.
Referenced by org.jhotdraw.draw.handle.BoundsOutlineHandle.BoundsOutlineHandle().
RESIZE_BOUNDS_COLOR_2
final AttributeKey<Color> org.jhotdraw.draw.handle.HandleAttributeKeys.RESIZE_BOUNDS_COLOR_2 = new AttributeKey<Color>("resizeBoundsColor2", Color.class, Color.BLUE) static
Resize bounds stroke color 2.
Referenced by org.jhotdraw.draw.handle.BoundsOutlineHandle.BoundsOutlineHandle().
RESIZE_BOUNDS_COLOR_2_DISABLED
final AttributeKey<Color> org.jhotdraw.draw.handle.HandleAttributeKeys.RESIZE_BOUNDS_COLOR_2_DISABLED = new AttributeKey<Color>("resizeBoundsColor2Hover", Color.class, FILL_COLOR_DISABLED) static
Disabled resize bounds hover color 2.
Referenced by org.jhotdraw.draw.handle.BoundsOutlineHandle.BoundsOutlineHandle().
RESIZE_BOUNDS_COLOR_2_HOVER
final AttributeKey<Color> org.jhotdraw.draw.handle.HandleAttributeKeys.RESIZE_BOUNDS_COLOR_2_HOVER = new AttributeKey<Color>("resizeBoundsColor2Hover", Color.class, Color.BLUE) static
Resize bounds hover stroke color 2.
Referenced by org.jhotdraw.draw.handle.BoundsOutlineHandle.BoundsOutlineHandle().
RESIZE_BOUNDS_STROKE_1
final AttributeKey<Stroke> org.jhotdraw.draw.handle.HandleAttributeKeys.RESIZE_BOUNDS_STROKE_1 static
Initial value:
= new AttributeKey<Stroke>("resizeBoundsStroke1", Stroke.class,
            new BasicStroke(3f, BasicStroke.CAP_SQUARE, BasicStroke.JOIN_BEVEL))
Resize bounds stroke 1.
Referenced by org.jhotdraw.draw.handle.BoundsOutlineHandle.BoundsOutlineHandle().
RESIZE_BOUNDS_STROKE_1_DISABLED
final AttributeKey<Stroke> org.jhotdraw.draw.handle.HandleAttributeKeys.RESIZE_BOUNDS_STROKE_1_DISABLED static
Initial value:
= new AttributeKey<Stroke>("resizeBoundsStroke1Hover", Stroke.class,
            new BasicStroke(3f))
Disabled resize bounds stroke 1.
Referenced by org.jhotdraw.draw.handle.BoundsOutlineHandle.BoundsOutlineHandle().
RESIZE_BOUNDS_STROKE_1_HOVER
final AttributeKey<Stroke> org.jhotdraw.draw.handle.HandleAttributeKeys.RESIZE_BOUNDS_STROKE_1_HOVER static
Initial value:
= new AttributeKey<Stroke>("resizeBoundsStroke1Hover", Stroke.class,
            null)
Resize bounds hover stroke 1.
Referenced by org.jhotdraw.draw.handle.BoundsOutlineHandle.BoundsOutlineHandle().
RESIZE_BOUNDS_STROKE_2
final AttributeKey<Stroke> org.jhotdraw.draw.handle.HandleAttributeKeys.RESIZE_BOUNDS_STROKE_2 static
Initial value:
= new AttributeKey<Stroke>("resizeBoundsStroke2", Stroke.class,
            new BasicStroke(1f))
Resize bounds stroke 2.
Referenced by org.jhotdraw.draw.handle.BoundsOutlineHandle.BoundsOutlineHandle().
RESIZE_BOUNDS_STROKE_2_DISABLED
final AttributeKey<Stroke> org.jhotdraw.draw.handle.HandleAttributeKeys.RESIZE_BOUNDS_STROKE_2_DISABLED static
Initial value:
= new AttributeKey<Stroke>("resizeBoundsStroke2Hover", Stroke.class,
            new BasicStroke(1f))
Disabled bounds stroke 2.
Referenced by org.jhotdraw.draw.handle.BoundsOutlineHandle.BoundsOutlineHandle().
RESIZE_BOUNDS_STROKE_2_HOVER
final AttributeKey<Stroke> org.jhotdraw.draw.handle.HandleAttributeKeys.RESIZE_BOUNDS_STROKE_2_HOVER static
Initial value:
= new AttributeKey<Stroke>("resizeBoundsStroke2Hover", Stroke.class,
            new BasicStroke(1f))
Resize bounds hover stroke 2.
Referenced by org.jhotdraw.draw.handle.BoundsOutlineHandle.BoundsOutlineHandle().
RESIZE_HANDLE_FILL_COLOR
final AttributeKey<Color> org.jhotdraw.draw.handle.HandleAttributeKeys.RESIZE_HANDLE_FILL_COLOR = new AttributeKey<Color>("resizeHandleFillColor", Color.class, Color.BLUE) static
Resize handle fill color.
RESIZE_HANDLE_STROKE_COLOR
final AttributeKey<Color> org.jhotdraw.draw.handle.HandleAttributeKeys.RESIZE_HANDLE_STROKE_COLOR = new AttributeKey<Color>("resizeHandleStrokeColor", Color.class, Color.WHITE) static
Resize handle stroke color.
ROTATE_HANDLE_FILL_COLOR
final AttributeKey<Color> org.jhotdraw.draw.handle.HandleAttributeKeys.ROTATE_HANDLE_FILL_COLOR = new AttributeKey<Color>("rotateHandleFillColor", Color.class, Color.MAGENTA) static
Rotate handle fill color.
Referenced by org.jhotdraw.draw.handle.AbstractRotateHandle.draw().
ROTATE_HANDLE_FILL_COLOR_DISABLED
final AttributeKey<Color> org.jhotdraw.draw.handle.HandleAttributeKeys.ROTATE_HANDLE_FILL_COLOR_DISABLED = new AttributeKey<Color>("rotateHandleFillColorDisabled", Color.class, FILL_COLOR_DISABLED) static
Rotate handle fill color.
Referenced by org.jhotdraw.draw.handle.AbstractRotateHandle.draw().
ROTATE_HANDLE_STROKE_COLOR
final AttributeKey<Color> org.jhotdraw.draw.handle.HandleAttributeKeys.ROTATE_HANDLE_STROKE_COLOR = new AttributeKey<Color>("rotateHandleStrokeColor", Color.class, Color.WHITE) static
Rotate handle stroke color.
Referenced by org.jhotdraw.draw.handle.AbstractRotateHandle.draw().
ROTATE_HANDLE_STROKE_COLOR_DISABLED
final AttributeKey<Color> org.jhotdraw.draw.handle.HandleAttributeKeys.ROTATE_HANDLE_STROKE_COLOR_DISABLED = new AttributeKey<Color>("rotateHandleStrokeColorDisabled", Color.class, STROKE_COLOR_DISABLED) static
Rotate handle stroke color.
Referenced by org.jhotdraw.draw.handle.AbstractRotateHandle.draw().
SCALE_HANDLE_FILL_COLOR
final AttributeKey<Color> org.jhotdraw.draw.handle.HandleAttributeKeys.SCALE_HANDLE_FILL_COLOR = new AttributeKey<Color>("scaleHandleFillColor", Color.class, Color.ORANGE.darker()) static
Scale handle fill color.
Referenced by org.jhotdraw.draw.handle.BezierScaleHandle.draw().
SCALE_HANDLE_STROKE_COLOR
final AttributeKey<Color> org.jhotdraw.draw.handle.HandleAttributeKeys.SCALE_HANDLE_STROKE_COLOR = new AttributeKey<Color>("scaleHandleStrokeColor", Color.class, Color.WHITE) static
Scale handle stroke color.
Referenced by org.jhotdraw.draw.handle.BezierScaleHandle.draw().
TRANSFORM_BOUNDS_COLOR_1
final AttributeKey<Color> org.jhotdraw.draw.handle.HandleAttributeKeys.TRANSFORM_BOUNDS_COLOR_1 = new AttributeKey<Color>("transformBoundsColor1", Color.class, Color.WHITE) static
Transform bounds color 1.
Referenced by org.jhotdraw.draw.handle.BoundsOutlineHandle.BoundsOutlineHandle().
TRANSFORM_BOUNDS_COLOR_1_DISABLED
final AttributeKey<Color> org.jhotdraw.draw.handle.HandleAttributeKeys.TRANSFORM_BOUNDS_COLOR_1_DISABLED = new AttributeKey<Color>("transformBoundsColor1Disabled", Color.class, STROKE_COLOR_DISABLED) static
Transform bounds disabled color 1.
Referenced by org.jhotdraw.draw.handle.BoundsOutlineHandle.BoundsOutlineHandle().
TRANSFORM_BOUNDS_COLOR_1_HOVER
final AttributeKey<Color> org.jhotdraw.draw.handle.HandleAttributeKeys.TRANSFORM_BOUNDS_COLOR_1_HOVER = new AttributeKey<Color>("transformBoundsColor1Hover", Color.class, null) static
Transform bounds hover color 1.
Referenced by org.jhotdraw.draw.handle.BoundsOutlineHandle.BoundsOutlineHandle().
TRANSFORM_BOUNDS_COLOR_2
final AttributeKey<Color> org.jhotdraw.draw.handle.HandleAttributeKeys.TRANSFORM_BOUNDS_COLOR_2 = new AttributeKey<Color>("transformBoundsColor2", Color.class, Color.MAGENTA) static
Transform bounds color 2.
Referenced by org.jhotdraw.draw.handle.BoundsOutlineHandle.BoundsOutlineHandle().
TRANSFORM_BOUNDS_COLOR_2_DISABLED
final AttributeKey<Color> org.jhotdraw.draw.handle.HandleAttributeKeys.TRANSFORM_BOUNDS_COLOR_2_DISABLED = new AttributeKey<Color>("transformBoundsColor2Disabled", Color.class, FILL_COLOR_DISABLED) static
Transform bounds disabled color 2.
Referenced by org.jhotdraw.draw.handle.BoundsOutlineHandle.BoundsOutlineHandle().
TRANSFORM_BOUNDS_COLOR_2_HOVER
final AttributeKey<Color> org.jhotdraw.draw.handle.HandleAttributeKeys.TRANSFORM_BOUNDS_COLOR_2_HOVER = new AttributeKey<Color>("transformBoundsColor2Hover", Color.class, Color.MAGENTA) static
Transform bounds hover color 2.
Referenced by org.jhotdraw.draw.handle.BoundsOutlineHandle.BoundsOutlineHandle().
TRANSFORM_BOUNDS_STROKE_1
final AttributeKey<Stroke> org.jhotdraw.draw.handle.HandleAttributeKeys.TRANSFORM_BOUNDS_STROKE_1 static
Initial value:
= new AttributeKey<Stroke>("transformBoundsStroke1", Stroke.class,
            new BasicStroke(3f, BasicStroke.CAP_SQUARE, BasicStroke.JOIN_BEVEL))
Transform bounds stroke 1.
Referenced by org.jhotdraw.draw.handle.BoundsOutlineHandle.BoundsOutlineHandle().
TRANSFORM_BOUNDS_STROKE_1_DISABLED
final AttributeKey<Stroke> org.jhotdraw.draw.handle.HandleAttributeKeys.TRANSFORM_BOUNDS_STROKE_1_DISABLED static
Initial value:
= new AttributeKey<Stroke>("transformBoundsStroke1Disabled", Stroke.class,
            new BasicStroke(3f))
Transform bounds disabled stroke 1.
Referenced by org.jhotdraw.draw.handle.BoundsOutlineHandle.BoundsOutlineHandle().
TRANSFORM_BOUNDS_STROKE_1_HOVER
final AttributeKey<Stroke> org.jhotdraw.draw.handle.HandleAttributeKeys.TRANSFORM_BOUNDS_STROKE_1_HOVER static
Initial value:
= new AttributeKey<Stroke>("transformBoundsStroke1Hover", Stroke.class,
            null)
Transform bounds hover stroke 1.
Referenced by org.jhotdraw.draw.handle.BoundsOutlineHandle.BoundsOutlineHandle().
TRANSFORM_BOUNDS_STROKE_2
final AttributeKey<Stroke> org.jhotdraw.draw.handle.HandleAttributeKeys.TRANSFORM_BOUNDS_STROKE_2 static
Initial value:
= new AttributeKey<Stroke>("transformBoundsStroke2", Stroke.class,
            new BasicStroke(1f))
Transform bounds stroke 2.
Referenced by org.jhotdraw.draw.handle.BoundsOutlineHandle.BoundsOutlineHandle().
TRANSFORM_BOUNDS_STROKE_2_DISABLED
final AttributeKey<Stroke> org.jhotdraw.draw.handle.HandleAttributeKeys.TRANSFORM_BOUNDS_STROKE_2_DISABLED static
Initial value:
= new AttributeKey<Stroke>("transformBoundsStroke2Disabled", Stroke.class,
            new BasicStroke(1f))
Transform bounds disabled stroke 2.
Referenced by org.jhotdraw.draw.handle.BoundsOutlineHandle.BoundsOutlineHandle().
TRANSFORM_BOUNDS_STROKE_2_HOVER
final AttributeKey<Stroke> org.jhotdraw.draw.handle.HandleAttributeKeys.TRANSFORM_BOUNDS_STROKE_2_HOVER static
Initial value:
= new AttributeKey<Stroke>("transformBoundsStroke2Hover", Stroke.class,
            new BasicStroke(1f))
Transform bounds hover stroke 2.
Referenced by org.jhotdraw.draw.handle.BoundsOutlineHandle.BoundsOutlineHandle().
TRANSFORM_HANDLE_FILL_COLOR
final AttributeKey<Color> org.jhotdraw.draw.handle.HandleAttributeKeys.TRANSFORM_HANDLE_FILL_COLOR = new AttributeKey<Color>("transformHandleFillColor", Color.class, Color.MAGENTA) static
Transform handle fill color.
TRANSFORM_HANDLE_FILL_COLOR_DISABLED
final AttributeKey<Color> org.jhotdraw.draw.handle.HandleAttributeKeys.TRANSFORM_HANDLE_FILL_COLOR_DISABLED = new AttributeKey<Color>("transformHandleFillColorDisabled", Color.class, FILL_COLOR_DISABLED) static
Transform handle fill color.
TRANSFORM_HANDLE_STROKE_COLOR
final AttributeKey<Color> org.jhotdraw.draw.handle.HandleAttributeKeys.TRANSFORM_HANDLE_STROKE_COLOR = new AttributeKey<Color>("transformHandleStrokeColor", Color.class, Color.WHITE) static
Transform handle stroke color.
TRANSFORM_HANDLE_STROKE_COLOR_DISABLED
final AttributeKey<Color> org.jhotdraw.draw.handle.HandleAttributeKeys.TRANSFORM_HANDLE_STROKE_COLOR_DISABLED = new AttributeKey<Color>("transformHandleStrokeColorDisabled", Color.class, STROKE_COLOR_DISABLED) static
Transform handle stroke color.
The documentation for this class was generated from the following file:
jhotdraw-core/src/main/java/org/jhotdraw/draw/handle/HandleAttributeKeys.java