jhotdraw: org.jhotdraw.draw.event.AbstractAttributeEditorHandler< T > Class Template Reference
org.jhotdraw.draw.event.AbstractAttributeEditorHandler< T > Class Template Reference abstract
Classes
class EventHandler
Public Member Functions
AbstractAttributeEditorHandler (AttributeKey< T > key, AttributeEditor< T > attributeEditor, DrawingEditor drawingEditor)
AbstractAttributeEditorHandler (AttributeKey< T > key, AttributeEditor< T > attributeEditor, DrawingEditor drawingEditor, boolean updateDrawingEditorDefaults)
AbstractAttributeEditorHandler (AttributeKey< T > key, Map< AttributeKey<?>, Object > defaultAttributes, AttributeEditor< T > attributeEditor, DrawingEditor drawingEditor, boolean updateDrawingEditorDefaults)
void setEditor (DrawingEditor newValue)
DrawingEditor getEditor ()
void setView (DrawingView newValue)
DrawingView getView ()
void setUpdateDrawingEditorDefaults (boolean newValue)
boolean isUpdateDrawingEditorDefaults ()
void setAttributeEditor (AttributeEditor< T > newValue)
AttributeEditor< T > getAttributeEditor ()
AttributeKey< T > getAttributeKey ()
void setAttributeKey (AttributeKey< T > newValue)
void dispose ()
Protected Member Functions
DrawingView getActiveView ()
void updateActiveView ()
abstract Set< Figure > getEditedFigures ()
void updateAttributeEditor ()
void updateFigures ()
Protected Attributes
DrawingEditor editor
DrawingView view
DrawingView activeView
AttributeEditor< T > attributeEditor
AttributeKey< T > attributeKey
int updateDepth
LinkedList< Object > attributeRestoreData = new LinkedList<>()
Map< AttributeKey<?>, Object > defaultAttributes
Detailed Description
AbstractAttributeEditorHandler mediates between an AttributeEditor and the currently selected Figure's in a DrawingEditor.
Design Patterns
Observer
Selection changes of
DrawingView
are observed by user interface components:
Subject: org.jhotdraw.draw.DrawingView; Observer: FigureSelectionListener; Concrete-Observer: AbstractAttributeEditorHandler, SelectionComponentDisplayer, SelectionComponentRepainter.
Author
Werner Randelshofer
Version
$Id$
Constructor & Destructor Documentation
AbstractAttributeEditorHandler() [1/3]
org.jhotdraw.draw.event.AbstractAttributeEditorHandler< T >.AbstractAttributeEditorHandler (AttributeKey< T > key, AttributeEditor< T > attributeEditor, DrawingEditor drawingEditor)
References org.jhotdraw.draw.event.AbstractAttributeEditorHandler< T >.attributeEditor.
AbstractAttributeEditorHandler() [2/3]
org.jhotdraw.draw.event.AbstractAttributeEditorHandler< T >.AbstractAttributeEditorHandler (AttributeKey< T > key, AttributeEditor< T > attributeEditor, DrawingEditor drawingEditor, boolean updateDrawingEditorDefaults)
References org.jhotdraw.draw.event.AbstractAttributeEditorHandler< T >.attributeEditor.
AbstractAttributeEditorHandler() [3/3]
org.jhotdraw.draw.event.AbstractAttributeEditorHandler< T >.AbstractAttributeEditorHandler (AttributeKey< T > key, Map< AttributeKey<?>, Object > defaultAttributes, AttributeEditor< T > attributeEditor, DrawingEditor drawingEditor, boolean updateDrawingEditorDefaults)
References org.jhotdraw.draw.event.AbstractAttributeEditorHandler< T >.attributeEditor, org.jhotdraw.draw.event.AbstractAttributeEditorHandler< T >.defaultAttributes, org.jhotdraw.draw.event.AbstractAttributeEditorHandler< T >.setAttributeEditor(), org.jhotdraw.draw.event.AbstractAttributeEditorHandler< T >.setAttributeKey(), and org.jhotdraw.draw.event.AbstractAttributeEditorHandler< T >.setEditor().
Member Function Documentation
dispose()
void org.jhotdraw.draw.event.AbstractAttributeEditorHandler< T >.dispose ()
References org.jhotdraw.draw.event.AbstractAttributeEditorHandler< T >.setEditor().
getActiveView()
DrawingView org.jhotdraw.draw.event.AbstractAttributeEditorHandler< T >.getActiveView () protected
References org.jhotdraw.draw.event.AbstractAttributeEditorHandler< T >.editor, org.jhotdraw.draw.DrawingEditor.getActiveView(), and org.jhotdraw.draw.event.AbstractAttributeEditorHandler< T >.getView().
Referenced by org.jhotdraw.draw.event.AbstractAttributeEditorHandler< T >.updateFigures().
getAttributeEditor()
AttributeEditor<T> org.jhotdraw.draw.event.AbstractAttributeEditorHandler< T >.getAttributeEditor ()
Returns the AttributeEditor to which this FigureAttributeEditorHandler is attached.
References org.jhotdraw.draw.event.AbstractAttributeEditorHandler< T >.attributeEditor.
getAttributeKey()
AttributeKey<T> org.jhotdraw.draw.event.AbstractAttributeEditorHandler< T >.getAttributeKey ()
References org.jhotdraw.draw.event.AbstractAttributeEditorHandler< T >.attributeKey.
getEditedFigures()
abstract Set<Figure> org.jhotdraw.draw.event.AbstractAttributeEditorHandler< T >.getEditedFigures () abstract protected
Reimplemented in org.jhotdraw.draw.event.FigureAttributeEditorHandler< T >, and org.jhotdraw.draw.event.DrawingAttributeEditorHandler< T >.
Referenced by org.jhotdraw.draw.event.AbstractAttributeEditorHandler< T >.EventHandler.selectionChanged(), org.jhotdraw.draw.event.AbstractAttributeEditorHandler< T >.updateActiveView(), org.jhotdraw.draw.event.AbstractAttributeEditorHandler< T >.updateAttributeEditor(), and org.jhotdraw.draw.event.AbstractAttributeEditorHandler< T >.updateFigures().
getEditor()
DrawingEditor org.jhotdraw.draw.event.AbstractAttributeEditorHandler< T >.getEditor ()
Returns the DrawingEditor to which this FigureAttributeEditorHandler is attached.
References org.jhotdraw.draw.event.AbstractAttributeEditorHandler< T >.editor.
getView()
DrawingView org.jhotdraw.draw.event.AbstractAttributeEditorHandler< T >.getView ()
Returns the DrawingView to which this FigureAttributeEditorHandler is attached. Returns null, if the FigureAttributeEditorHandler is attached to all views of the DrawingEditor.
References org.jhotdraw.draw.event.AbstractAttributeEditorHandler< T >.view.
Referenced by org.jhotdraw.draw.event.AbstractAttributeEditorHandler< T >.getActiveView().
isUpdateDrawingEditorDefaults()
boolean org.jhotdraw.draw.event.AbstractAttributeEditorHandler< T >.isUpdateDrawingEditorDefaults ()
Returns true if the attribute editor updates the default values of the drawing editor.
setAttributeEditor()
void org.jhotdraw.draw.event.AbstractAttributeEditorHandler< T >.setAttributeEditor (AttributeEditor< T > newValue)
Attaches the FigureAttributeEditorHandler to the specified AttributeEditor.
References org.jhotdraw.draw.event.AbstractAttributeEditorHandler< T >.attributeEditor.
Referenced by org.jhotdraw.draw.event.AbstractAttributeEditorHandler< T >.AbstractAttributeEditorHandler().
setAttributeKey()
void org.jhotdraw.draw.event.AbstractAttributeEditorHandler< T >.setAttributeKey (AttributeKey< T > newValue)
References org.jhotdraw.draw.event.AbstractAttributeEditorHandler< T >.attributeKey.
Referenced by org.jhotdraw.draw.event.AbstractAttributeEditorHandler< T >.AbstractAttributeEditorHandler().
setEditor()
void org.jhotdraw.draw.event.AbstractAttributeEditorHandler< T >.setEditor (DrawingEditor newValue)
Attaches the FigureAttributeEditorHandler to the specified DrawingEditor.
The FigureAttributeEditorHandler listens to view changes and selection changes of the drawing editor and calls setEnabled(boolean) and updateField(Set<Figure>) on the field accordingly.
Parameters
newValue a drawing editor.
References org.jhotdraw.draw.DrawingEditor.addPropertyChangeListener(), org.jhotdraw.draw.event.AbstractAttributeEditorHandler< T >.editor, org.jhotdraw.draw.DrawingEditor.removePropertyChangeListener(), and org.jhotdraw.draw.event.AbstractAttributeEditorHandler< T >.updateActiveView().
Referenced by org.jhotdraw.draw.event.AbstractAttributeEditorHandler< T >.AbstractAttributeEditorHandler(), and org.jhotdraw.draw.event.AbstractAttributeEditorHandler< T >.dispose().
setUpdateDrawingEditorDefaults()
void org.jhotdraw.draw.event.AbstractAttributeEditorHandler< T >.setUpdateDrawingEditorDefaults (boolean newValue)
Set this to true if you want the attribute editor to update the default values of the drawing editor.
Parameters
newValue
setView()
void org.jhotdraw.draw.event.AbstractAttributeEditorHandler< T >.setView (DrawingView newValue)
Attaches the FigureAttributeEditorHandler to the specified DrawingView.
If a non-null value is provided, the FigureAttributeEditorHandler listens only to selection changes of the specified view. If a null value is provided, the FigureAttributeEditorHandler listens to all views of the drawing editor.
Parameters
newValue a drawing view.
References org.jhotdraw.draw.event.AbstractAttributeEditorHandler< T >.updateActiveView().
updateActiveView()
void org.jhotdraw.draw.event.AbstractAttributeEditorHandler< T >.updateActiveView () protected
References org.jhotdraw.draw.event.AbstractAttributeEditorHandler< T >.activeView, org.jhotdraw.draw.DrawingView.addFigureSelectionListener(), org.jhotdraw.draw.DrawingView.addPropertyChangeListener(), org.jhotdraw.draw.event.AbstractAttributeEditorHandler< T >.attributeRestoreData, org.jhotdraw.draw.event.AbstractAttributeEditorHandler< T >.editor, org.jhotdraw.draw.DrawingEditor.getActiveView(), org.jhotdraw.draw.event.AbstractAttributeEditorHandler< T >.getEditedFigures(), org.jhotdraw.draw.DrawingView.removeFigureSelectionListener(), org.jhotdraw.draw.DrawingView.removePropertyChangeListener(), org.jhotdraw.draw.event.AbstractAttributeEditorHandler< T >.updateAttributeEditor(), and org.jhotdraw.draw.event.AbstractAttributeEditorHandler< T >.view.
Referenced by org.jhotdraw.draw.event.AbstractAttributeEditorHandler< T >.EventHandler.propertyChange(), org.jhotdraw.draw.event.AbstractAttributeEditorHandler< T >.setEditor(), and org.jhotdraw.draw.event.AbstractAttributeEditorHandler< T >.setView().
updateAttributeEditor()
void org.jhotdraw.draw.event.AbstractAttributeEditorHandler< T >.updateAttributeEditor () protected
References org.jhotdraw.draw.event.AbstractAttributeEditorHandler< T >.activeView, org.jhotdraw.draw.event.AbstractAttributeEditorHandler< T >.attributeEditor, org.jhotdraw.draw.event.AbstractAttributeEditorHandler< T >.attributeKey, org.jhotdraw.draw.event.AbstractAttributeEditorHandler< T >.editor, org.jhotdraw.draw.DrawingEditor.getDefaultAttribute(), org.jhotdraw.draw.event.AbstractAttributeEditorHandler< T >.getEditedFigures(), and org.jhotdraw.draw.event.AbstractAttributeEditorHandler< T >.updateDepth.
Referenced by org.jhotdraw.draw.event.AbstractAttributeEditorHandler< T >.EventHandler.attributeChanged(), org.jhotdraw.draw.event.AbstractAttributeEditorHandler< T >.EventHandler.propertyChange(), org.jhotdraw.draw.event.AbstractAttributeEditorHandler< T >.EventHandler.selectionChanged(), org.jhotdraw.draw.event.DrawingAttributeEditorHandler< T >.setDrawing(), and org.jhotdraw.draw.event.AbstractAttributeEditorHandler< T >.updateActiveView().
updateFigures()
void org.jhotdraw.draw.event.AbstractAttributeEditorHandler< T >.updateFigures () protected
References org.jhotdraw.draw.event.AbstractAttributeEditorHandler< T >.activeView, org.jhotdraw.draw.event.AbstractAttributeEditorHandler< T >.attributeEditor, org.jhotdraw.draw.event.AbstractAttributeEditorHandler< T >.attributeKey, org.jhotdraw.draw.event.AbstractAttributeEditorHandler< T >.attributeRestoreData, org.jhotdraw.draw.event.AbstractAttributeEditorHandler< T >.defaultAttributes, org.jhotdraw.draw.event.AbstractAttributeEditorHandler< T >.editor, org.jhotdraw.draw.Drawing.fireUndoableEditHappened(), org.jhotdraw.draw.event.AbstractAttributeEditorHandler< T >.getActiveView(), org.jhotdraw.draw.DrawingView.getDrawing(), org.jhotdraw.draw.event.AbstractAttributeEditorHandler< T >.getEditedFigures(), org.jhotdraw.draw.DrawingEditor.setDefaultAttribute(), and org.jhotdraw.draw.event.AbstractAttributeEditorHandler< T >.updateDepth.
Referenced by org.jhotdraw.draw.event.AbstractAttributeEditorHandler< T >.EventHandler.propertyChange().
Member Data Documentation
activeView
DrawingView org.jhotdraw.draw.event.AbstractAttributeEditorHandler< T >.activeView protected
Referenced by org.jhotdraw.draw.event.DrawingAttributeEditorHandler< T >.getEditedFigures(), org.jhotdraw.draw.event.FigureAttributeEditorHandler< T >.getEditedFigures(), org.jhotdraw.draw.event.AbstractAttributeEditorHandler< T >.EventHandler.propertyChange(), org.jhotdraw.draw.event.AbstractAttributeEditorHandler< T >.updateActiveView(), org.jhotdraw.draw.event.AbstractAttributeEditorHandler< T >.updateAttributeEditor(), and org.jhotdraw.draw.event.AbstractAttributeEditorHandler< T >.updateFigures().
attributeEditor
AttributeEditor<T> org.jhotdraw.draw.event.AbstractAttributeEditorHandler< T >.attributeEditor protected
Referenced by org.jhotdraw.draw.event.AbstractAttributeEditorHandler< T >.AbstractAttributeEditorHandler(), org.jhotdraw.draw.event.DrawingAttributeEditorHandler< T >.DrawingAttributeEditorHandler(), org.jhotdraw.draw.event.FigureAttributeEditorHandler< T >.FigureAttributeEditorHandler(), org.jhotdraw.draw.event.AbstractAttributeEditorHandler< T >.getAttributeEditor(), org.jhotdraw.draw.event.AbstractAttributeEditorHandler< T >.EventHandler.propertyChange(), org.jhotdraw.draw.event.AbstractAttributeEditorHandler< T >.setAttributeEditor(), org.jhotdraw.draw.event.AbstractAttributeEditorHandler< T >.updateAttributeEditor(), and org.jhotdraw.draw.event.AbstractAttributeEditorHandler< T >.updateFigures().
attributeKey
AttributeKey<T> org.jhotdraw.draw.event.AbstractAttributeEditorHandler< T >.attributeKey protected
Referenced by org.jhotdraw.draw.event.AbstractAttributeEditorHandler< T >.EventHandler.attributeChanged(), org.jhotdraw.draw.event.AbstractAttributeEditorHandler< T >.getAttributeKey(), org.jhotdraw.draw.event.AbstractAttributeEditorHandler< T >.EventHandler.propertyChange(), org.jhotdraw.draw.event.AbstractAttributeEditorHandler< T >.setAttributeKey(), org.jhotdraw.draw.event.AbstractAttributeEditorHandler< T >.updateAttributeEditor(), and org.jhotdraw.draw.event.AbstractAttributeEditorHandler< T >.updateFigures().
attributeRestoreData
LinkedList<Object> org.jhotdraw.draw.event.AbstractAttributeEditorHandler< T >.attributeRestoreData = new LinkedList<>() protected
Referenced by org.jhotdraw.draw.event.AbstractAttributeEditorHandler< T >.EventHandler.selectionChanged(), org.jhotdraw.draw.event.AbstractAttributeEditorHandler< T >.updateActiveView(), and org.jhotdraw.draw.event.AbstractAttributeEditorHandler< T >.updateFigures().
defaultAttributes
Map<AttributeKey<?>, Object> org.jhotdraw.draw.event.AbstractAttributeEditorHandler< T >.defaultAttributes protected
Referenced by org.jhotdraw.draw.event.AbstractAttributeEditorHandler< T >.AbstractAttributeEditorHandler(), org.jhotdraw.draw.event.FigureAttributeEditorHandler< T >.FigureAttributeEditorHandler(), and org.jhotdraw.draw.event.AbstractAttributeEditorHandler< T >.updateFigures().
editor
DrawingEditor org.jhotdraw.draw.event.AbstractAttributeEditorHandler< T >.editor protected
Referenced by org.jhotdraw.draw.event.AbstractAttributeEditorHandler< T >.getActiveView(), org.jhotdraw.draw.event.AbstractAttributeEditorHandler< T >.getEditor(), org.jhotdraw.draw.event.AbstractAttributeEditorHandler< T >.EventHandler.propertyChange(), org.jhotdraw.draw.event.AbstractAttributeEditorHandler< T >.setEditor(), org.jhotdraw.draw.event.AbstractAttributeEditorHandler< T >.updateActiveView(), org.jhotdraw.draw.event.AbstractAttributeEditorHandler< T >.updateAttributeEditor(), and org.jhotdraw.draw.event.AbstractAttributeEditorHandler< T >.updateFigures().
updateDepth
int org.jhotdraw.draw.event.AbstractAttributeEditorHandler< T >.updateDepth protected
Referenced by org.jhotdraw.draw.event.AbstractAttributeEditorHandler< T >.updateAttributeEditor(), and org.jhotdraw.draw.event.AbstractAttributeEditorHandler< T >.updateFigures().
view
DrawingView org.jhotdraw.draw.event.AbstractAttributeEditorHandler< T >.view protected
Referenced by org.jhotdraw.draw.event.AbstractAttributeEditorHandler< T >.getView(), and org.jhotdraw.draw.event.AbstractAttributeEditorHandler< T >.updateActiveView().
The documentation for this class was generated from the following file:
jhotdraw-core/src/main/java/org/jhotdraw/draw/event/AbstractAttributeEditorHandler.java