jhotdraw: org.jhotdraw.draw.action.DrawingColorChooserHandler Class Reference
org.jhotdraw.draw.action.DrawingColorChooserHandler Class Reference
Public Member Functions
DrawingColorChooserHandler (DrawingEditor editor, AttributeKey< Color > key, JColorChooser colorChooser, JPopupMenu popupMenu)
void actionPerformed (java.awt.event.ActionEvent evt)
void stateChanged (ChangeEvent e)
Public Member Functions inherited from org.jhotdraw.draw.action.AbstractDrawingViewAction
AbstractDrawingViewAction (DrawingEditor editor)
AbstractDrawingViewAction (DrawingView view)
void dispose ()
void setUpdateEnabledState (boolean newValue)
boolean isUpdatEnabledState ()
Protected Member Functions
void applySelectedColorToFigures ()
void updateEnabledState ()
Protected Member Functions inherited from org.jhotdraw.draw.action.AbstractDrawingViewAction
void setEditor (DrawingEditor newValue)
DrawingEditor getEditor ()
DrawingView getView ()
Drawing getDrawing ()
void fireUndoableEditHappened (UndoableEdit edit)
void updateViewState ()
Protected Attributes
AttributeKey< Color > key
JColorChooser colorChooser
JPopupMenu popupMenu
int isUpdating
Detailed Description
DrawingColorChooserHandler.
Author
Werner Randelshofer
Version
$Id$
Constructor & Destructor Documentation
DrawingColorChooserHandler()
org.jhotdraw.draw.action.DrawingColorChooserHandler.DrawingColorChooserHandler (DrawingEditor editor, AttributeKey< Color > key, JColorChooser colorChooser, JPopupMenu popupMenu)
Creates a new instance.
References org.jhotdraw.draw.action.DrawingColorChooserHandler.colorChooser, org.jhotdraw.draw.action.DrawingColorChooserHandler.key, org.jhotdraw.draw.action.DrawingColorChooserHandler.popupMenu, and org.jhotdraw.draw.action.DrawingColorChooserHandler.updateEnabledState().
Member Function Documentation
actionPerformed()
void org.jhotdraw.draw.action.DrawingColorChooserHandler.actionPerformed (java.awt.event.ActionEvent evt)
References org.jhotdraw.draw.action.DrawingColorChooserHandler.popupMenu.
applySelectedColorToFigures()
void org.jhotdraw.draw.action.DrawingColorChooserHandler.applySelectedColorToFigures () protected
References org.jhotdraw.draw.figure.Figure.changed(), org.jhotdraw.draw.action.DrawingColorChooserHandler.colorChooser, org.jhotdraw.draw.action.AbstractDrawingViewAction.fireUndoableEditHappened(), org.jhotdraw.draw.AttributeKeys.FONT_FACE, org.jhotdraw.draw.figure.Figure.getAttributesRestoreData(), org.jhotdraw.draw.DrawingView.getDrawing(), org.jhotdraw.draw.action.AbstractDrawingViewAction.getEditor(), org.jhotdraw.draw.AttributeKey< T >.getPresentationName(), org.jhotdraw.draw.action.AbstractDrawingViewAction.getView(), org.jhotdraw.draw.action.DrawingColorChooserHandler.key, org.jhotdraw.draw.figure.Figure.restoreAttributesTo(), org.jhotdraw.draw.figure.Figure.set(), org.jhotdraw.draw.DrawingEditor.setDefaultAttribute(), and org.jhotdraw.draw.figure.Figure.willChange().
Referenced by org.jhotdraw.draw.action.DrawingColorChooserHandler.stateChanged().
stateChanged()
void org.jhotdraw.draw.action.DrawingColorChooserHandler.stateChanged (ChangeEvent e)
References org.jhotdraw.draw.action.DrawingColorChooserHandler.applySelectedColorToFigures(), and org.jhotdraw.draw.action.DrawingColorChooserHandler.isUpdating.
updateEnabledState()
void org.jhotdraw.draw.action.DrawingColorChooserHandler.updateEnabledState () protected
Updates the enabled state of this action to reflect the enabled state of the active
DrawingView
. If no drawing view is active, this action is disabled.
Reimplemented from org.jhotdraw.draw.action.AbstractDrawingViewAction.
References org.jhotdraw.draw.action.DrawingColorChooserHandler.colorChooser, org.jhotdraw.draw.figure.Figure.get(), org.jhotdraw.draw.DrawingView.getDrawing(), org.jhotdraw.draw.action.AbstractDrawingViewAction.getEditor(), org.jhotdraw.draw.action.AbstractDrawingViewAction.getView(), org.jhotdraw.draw.action.DrawingColorChooserHandler.isUpdating, org.jhotdraw.draw.action.DrawingColorChooserHandler.key, and org.jhotdraw.draw.action.DrawingColorChooserHandler.popupMenu.
Referenced by org.jhotdraw.draw.action.DrawingColorChooserHandler.DrawingColorChooserHandler().
Member Data Documentation
colorChooser
JColorChooser org.jhotdraw.draw.action.DrawingColorChooserHandler.colorChooser protected
Referenced by org.jhotdraw.draw.action.DrawingColorChooserHandler.applySelectedColorToFigures(), org.jhotdraw.draw.action.DrawingColorChooserHandler.DrawingColorChooserHandler(), and org.jhotdraw.draw.action.DrawingColorChooserHandler.updateEnabledState().
isUpdating
int org.jhotdraw.draw.action.DrawingColorChooserHandler.isUpdating protected
Referenced by org.jhotdraw.draw.action.DrawingColorChooserHandler.stateChanged(), and org.jhotdraw.draw.action.DrawingColorChooserHandler.updateEnabledState().
key
AttributeKey<Color> org.jhotdraw.draw.action.DrawingColorChooserHandler.key protected
Referenced by org.jhotdraw.draw.action.DrawingColorChooserHandler.applySelectedColorToFigures(), org.jhotdraw.draw.action.DrawingColorChooserHandler.DrawingColorChooserHandler(), and org.jhotdraw.draw.action.DrawingColorChooserHandler.updateEnabledState().
popupMenu
JPopupMenu org.jhotdraw.draw.action.DrawingColorChooserHandler.popupMenu protected
Referenced by org.jhotdraw.draw.action.DrawingColorChooserHandler.actionPerformed(), org.jhotdraw.draw.action.DrawingColorChooserHandler.DrawingColorChooserHandler(), and org.jhotdraw.draw.action.DrawingColorChooserHandler.updateEnabledState().
The documentation for this class was generated from the following file:
jhotdraw-core/src/main/java/org/jhotdraw/draw/action/DrawingColorChooserHandler.java