jhotdraw: org.jhotdraw.draw.action.AttributeToggler< T > Class Template Reference
org.jhotdraw.draw.action.AttributeToggler< T > Class Template Reference
Public Member Functions
AttributeToggler (DrawingEditor editor, AttributeKey< T > key, T value1, T value2)
AttributeToggler (DrawingEditor editor, AttributeKey< T > key, T value1, T value2, Action compatibleTextAction)
DrawingView getView ()
DrawingEditor getEditor ()
void actionPerformed (ActionEvent evt)
Detailed Description
AttributeToggler toggles an attribute of the selected figures between two different values. If the name of a compatible JTextComponent action is specified, the toggler checks if the current permant focus owner is a JTextComponent, and if it is, it will apply the text action to the JTextComponent.
Author
Werner Randelshofer
Version
$Id$
Constructor & Destructor Documentation
AttributeToggler() [1/2]
org.jhotdraw.draw.action.AttributeToggler< T >.AttributeToggler (DrawingEditor editor, AttributeKey< T > key, T value1, T value2)
Creates a new instance.
AttributeToggler() [2/2]
org.jhotdraw.draw.action.AttributeToggler< T >.AttributeToggler (DrawingEditor editor, AttributeKey< T > key, T value1, T value2, Action compatibleTextAction)
Member Function Documentation
actionPerformed()
void org.jhotdraw.draw.action.AttributeToggler< T >.actionPerformed (ActionEvent evt)
References org.jhotdraw.draw.Drawing.fireUndoableEditHappened(), org.jhotdraw.draw.figure.Figure.get(), org.jhotdraw.draw.DrawingView.getDrawing(), org.jhotdraw.draw.DrawingView.getSelectedFigures(), and org.jhotdraw.draw.action.AttributeToggler< T >.getView().
getEditor()
DrawingEditor org.jhotdraw.draw.action.AttributeToggler< T >.getEditor ()
getView()
DrawingView org.jhotdraw.draw.action.AttributeToggler< T >.getView ()
References org.jhotdraw.draw.DrawingEditor.getActiveView().
Referenced by org.jhotdraw.draw.action.AttributeToggler< T >.actionPerformed().
The documentation for this class was generated from the following file:
jhotdraw-core/src/main/java/org/jhotdraw/draw/action/AttributeToggler.java