jhotdraw: org.jhotdraw.draw.event.HandleMulticaster Class Reference
org.jhotdraw.draw.event.HandleMulticaster Class Reference
Public Member Functions
HandleMulticaster (Handle handle)
HandleMulticaster (Collection< Handle > handles)
void draw (java.awt.Graphics2D g)
void keyPressed (java.awt.event.KeyEvent e)
void keyReleased (java.awt.event.KeyEvent e)
void keyTyped (java.awt.event.KeyEvent e)
void trackEnd (Point current, Point anchor, int modifiersEx, DrawingView view)
void trackStart (Point anchor, int modifiersEx, DrawingView view)
void trackDoubleClick (Point p, int modifiersEx, DrawingView view)
void trackStep (Point anchor, Point lead, int modifiersEx, DrawingView view)
Detailed Description
Forwards events to one or many handles.
Author
Werner Randelshofer
Version
$Id$
Constructor & Destructor Documentation
HandleMulticaster() [1/2]
org.jhotdraw.draw.event.HandleMulticaster.HandleMulticaster (Handle handle)
Creates a new instance.
HandleMulticaster() [2/2]
org.jhotdraw.draw.event.HandleMulticaster.HandleMulticaster (Collection< Handle > handles)
Creates a new instance.
Member Function Documentation
draw()
void org.jhotdraw.draw.event.HandleMulticaster.draw (java.awt.Graphics2D g)
keyPressed()
void org.jhotdraw.draw.event.HandleMulticaster.keyPressed (java.awt.event.KeyEvent e)
Referenced by org.jhotdraw.draw.tool.DefaultHandleTracker.keyPressed().
keyReleased()
void org.jhotdraw.draw.event.HandleMulticaster.keyReleased (java.awt.event.KeyEvent e)
Referenced by org.jhotdraw.draw.tool.DefaultHandleTracker.keyReleased().
keyTyped()
void org.jhotdraw.draw.event.HandleMulticaster.keyTyped (java.awt.event.KeyEvent e)
Referenced by org.jhotdraw.draw.tool.DefaultHandleTracker.keyTyped().
trackDoubleClick()
void org.jhotdraw.draw.event.HandleMulticaster.trackDoubleClick (Point p, int modifiersEx, DrawingView view)
Referenced by org.jhotdraw.draw.tool.DefaultHandleTracker.mouseClicked().
trackEnd()
void org.jhotdraw.draw.event.HandleMulticaster.trackEnd (Point current, Point anchor, int modifiersEx, DrawingView view)
Referenced by org.jhotdraw.draw.tool.DefaultHandleTracker.mouseReleased().
trackStart()
void org.jhotdraw.draw.event.HandleMulticaster.trackStart (Point anchor, int modifiersEx, DrawingView view)
Referenced by org.jhotdraw.draw.tool.DefaultHandleTracker.mousePressed().
trackStep()
void org.jhotdraw.draw.event.HandleMulticaster.trackStep (Point anchor, Point lead, int modifiersEx, DrawingView view)
Referenced by org.jhotdraw.draw.tool.DefaultHandleTracker.keyPressed(), org.jhotdraw.draw.tool.DefaultHandleTracker.keyReleased(), and org.jhotdraw.draw.tool.DefaultHandleTracker.mouseDragged().
The documentation for this class was generated from the following file:
jhotdraw-core/src/main/java/org/jhotdraw/draw/event/HandleMulticaster.java