jhotdraw: org.jhotdraw.draw.connector.ChopRectangleConnector Class Reference
org.jhotdraw.draw.connector.ChopRectangleConnector Class Reference
Public Member Functions
ChopRectangleConnector ()
ChopRectangleConnector (Figure owner)
Point2D.Double findStart (ConnectionFigure connection)
Point2D.Double findEnd (ConnectionFigure connection)
Public Member Functions inherited from org.jhotdraw.draw.connector.AbstractConnector
AbstractConnector ()
AbstractConnector (Figure owner)
void setConnectToDecorator (boolean newValue)
boolean isConnectToDecorator ()
boolean contains (Point2D.Double p)
Figure getOwner ()
Object clone ()
void updateStartLocation (Point2D.Double p)
void updateEndLocation (Point2D.Double p)
Point2D.Double getAnchor ()
void updateAnchor (Point2D.Double p)
Rectangle2D.Double getBounds ()
void read (DOMInput in) throws IOException
void write (DOMOutput out) throws IOException
Rectangle2D.Double getDrawingArea ()
void draw (Graphics2D g)
Protected Member Functions
Point2D.Double chop (Figure target, Point2D.Double from)
Protected Member Functions inherited from org.jhotdraw.draw.connector.AbstractConnector
final Figure getConnectorTarget (Figure f)
Point2D.Double findPoint (ConnectionFigure connection)
void setOwner (Figure newValue)
Detailed Description
A Connector which locates a connection point at the bounds of any figure which has a rectangular shape, such as org.jhotdraw.draw.RectangleFigure.
See also
Connector
Author
Werner Randelshofer
Version
$Id$
Constructor & Destructor Documentation
ChopRectangleConnector() [1/2]
org.jhotdraw.draw.connector.ChopRectangleConnector.ChopRectangleConnector ()
Creates a new instance. Only used for storable.
ChopRectangleConnector() [2/2]
org.jhotdraw.draw.connector.ChopRectangleConnector.ChopRectangleConnector (Figure owner)
Member Function Documentation
chop()
Point2D.Double org.jhotdraw.draw.connector.ChopRectangleConnector.chop (Figure target, Point2D.Double from) protected
Reimplemented in org.jhotdraw.draw.connector.StickyRectangleConnector, org.jhotdraw.draw.connector.ChopTriangleConnector, org.jhotdraw.draw.connector.ChopRoundRectangleConnector, org.jhotdraw.draw.connector.ChopEllipseConnector, org.jhotdraw.draw.connector.ChopDiamondConnector, and org.jhotdraw.draw.connector.ChopBezierConnector.
References org.jhotdraw.draw.figure.Figure.get(), org.jhotdraw.draw.figure.Figure.getBounds(), org.jhotdraw.draw.connector.AbstractConnector.getConnectorTarget(), and org.jhotdraw.draw.AttributeKeys.getStrokeTotalWidth().
Referenced by org.jhotdraw.draw.connector.ChopRectangleConnector.findEnd(), and org.jhotdraw.draw.connector.ChopRectangleConnector.findStart().
findEnd()
Point2D.Double org.jhotdraw.draw.connector.ChopRectangleConnector.findEnd (ConnectionFigure connection)
Finds the end point for the connection.
Reimplemented from org.jhotdraw.draw.connector.AbstractConnector.
References org.jhotdraw.draw.connector.ChopRectangleConnector.chop(), org.jhotdraw.draw.figure.Figure.getBounds(), org.jhotdraw.draw.connector.AbstractConnector.getConnectorTarget(), org.jhotdraw.draw.figure.ConnectionFigure.getEndConnector(), org.jhotdraw.draw.figure.ConnectionFigure.getEndFigure(), org.jhotdraw.draw.figure.ConnectionFigure.getLiner(), org.jhotdraw.draw.figure.ConnectionFigure.getNodeCount(), org.jhotdraw.draw.connector.Connector.getOwner(), org.jhotdraw.draw.figure.ConnectionFigure.getPoint(), org.jhotdraw.draw.figure.ConnectionFigure.getStartConnector(), org.jhotdraw.draw.figure.ConnectionFigure.getStartFigure(), and org.jhotdraw.draw.figure.ConnectionFigure.getStartPoint().
findStart()
Point2D.Double org.jhotdraw.draw.connector.ChopRectangleConnector.findStart (ConnectionFigure connection)
Finds the start point for the connection.
Reimplemented from org.jhotdraw.draw.connector.AbstractConnector.
References org.jhotdraw.draw.connector.ChopRectangleConnector.chop(), org.jhotdraw.draw.figure.Figure.getBounds(), org.jhotdraw.draw.connector.AbstractConnector.getConnectorTarget(), org.jhotdraw.draw.figure.ConnectionFigure.getEndConnector(), org.jhotdraw.draw.figure.ConnectionFigure.getEndPoint(), org.jhotdraw.draw.figure.ConnectionFigure.getLiner(), org.jhotdraw.draw.figure.ConnectionFigure.getNodeCount(), org.jhotdraw.draw.connector.Connector.getOwner(), org.jhotdraw.draw.figure.ConnectionFigure.getPoint(), and org.jhotdraw.draw.figure.ConnectionFigure.getStartConnector().
The documentation for this class was generated from the following file:
jhotdraw-core/src/main/java/org/jhotdraw/draw/connector/ChopRectangleConnector.java