jhotdraw: org.jhotdraw.draw.figure.LineConnectionFigure Class Reference
org.jhotdraw.draw.figure.LineConnectionFigure Class Reference
Public Member Functions
LineConnectionFigure ()
void transform (AffineTransform tx)
Collection< Handle > createHandles (int detailLevel)
void setConnectable (boolean newValue)
void updateConnection ()
void validate ()
boolean canConnect (Connector start, Connector end)
Connector getEndConnector ()
Figure getEndFigure ()
Connector getStartConnector ()
Figure getStartFigure ()
void setEndConnector (Connector newEnd)
void setStartConnector (Connector newStart)
void addNotify (Drawing drawing)
void removeNotify (Drawing drawing)
LineConnectionFigure clone ()
void remap (Map< Figure, Figure > oldToNew, boolean disconnectIfNotInMap)
boolean canConnect (Connector start)
boolean handleMouseClick (Point2D.Double p, MouseEvent evt, DrawingView view)
void read (DOMInput in) throws IOException
void write (DOMOutput out) throws IOException
void setLiner (Liner newValue)
void setNode (int index, BezierPath.Node p)
void lineout ()
BezierPath getBezierPath ()
Liner getLiner ()
void setStartPoint (Point2D.Double p)
void setPoint (int index, Point2D.Double p)
void setEndPoint (Point2D.Double p)
void reverseConnection ()
Public Member Functions inherited from org.jhotdraw.draw.figure.LineFigure
LineFigure ()
Public Member Functions inherited from org.jhotdraw.draw.figure.BezierFigure
BezierFigure ()
BezierFigure (boolean isClosed)
Connector findConnector (Point2D.Double p, ConnectionFigure prototype)
Connector findCompatibleConnector (Connector c, boolean isStart)
boolean contains (Point2D.Double p)
Rectangle2D.Double getBounds ()
Rectangle2D.Double getDrawingArea (double factor)
void setBezierPath (BezierPath newValue)
Point2D.Double getPointOnPath (float relative, double flatness)
boolean isClosed ()
void setClosed (boolean newValue)
void setBounds (Point2D.Double anchor, Point2D.Double lead)
void invalidate ()
void layout ()
void addNode (BezierPath.Node p)
void addNode (final int index, BezierPath.Node p)
BezierPath.Node getNode (int index)
Point2D.Double getPoint (int index)
Point2D.Double getPoint (int index, int coord)
void setPoint (int index, int coord, Point2D.Double p)
Point2D.Double getStartPoint ()
Point2D.Double getEndPoint ()
int findNode (Point2D.Double p)
int findSegment (Point2D.Double find, double tolerance)
boolean joinSegments (Point2D.Double join, double tolerance)
int splitSegment (Point2D.Double split, double tolerance)
BezierPath.Node removeNode (int index)
int getNodeCount ()
void restoreTransformTo (Object geometry)
Object getTransformRestoreData ()
Point2D.Double chop (Point2D.Double p)
Point2D.Double getCenter ()
Point2D.Double getOutermostPoint ()
int joinSegments (Point2D.Double join, float tolerance)
int splitSegment (Point2D.Double split, float tolerance)
Public Member Functions inherited from org.jhotdraw.draw.figure.AbstractAttributedFigure
AbstractAttributedFigure ()
void setAttributeEnabled (AttributeKey<?> key, boolean b)
boolean isAttributeEnabled (AttributeKey<?> key)
void setAttributes (Map< AttributeKey<?>, Object > map)
Map< AttributeKey<?>, Object > getAttributes ()
Object getAttributesRestoreData ()
void restoreAttributesTo (Object restoreData)
void draw (Graphics2D g)
double getStrokeMiterLimitFactor ()
Rectangle2D.Double getDrawingArea ()
boolean hasAttribute (AttributeKey<?> key)
Public Member Functions inherited from org.jhotdraw.draw.figure.AbstractFigure
AbstractFigure ()
void addFigureListener (FigureListener l)
void removeFigureListener (FigureListener l)
void fireAreaInvalidated ()
void fireFigureChanged ()
Cursor getCursor (Point2D.Double p)
final void setBounds (Rectangle2D.Double bounds)
void willChange ()
void changed ()
boolean includes (Figure figure)
Figure findFigureInside (Point2D.Double p)
Collection< Action > getActions (Point2D.Double p)
Tool getTool (Point2D.Double p)
boolean handleDrop (Point2D.Double p, Collection< Figure > droppedFigures, DrawingView view)
Dimension2DDouble getPreferredSize ()
boolean isConnectable ()
boolean isSelectable ()
void setSelectable (boolean newValue)
boolean isRemovable ()
void setRemovable (boolean newValue)
boolean isTransformable ()
void setTransformable (boolean newValue)
boolean isVisible ()
void setVisible (boolean newValue)
Collection< Figure > getDecomposition ()
void requestRemove ()
int getLayer ()
String getToolTipText (Point2D.Double p)
String toString ()
Collection< Connector > getConnectors (ConnectionFigure prototype)
Public Member Functions inherited from org.jhotdraw.draw.figure.Figure
void addPropertyChangeListener (PropertyChangeListener listener)
void removePropertyChangeListener (PropertyChangeListener listener)
Public Member Functions inherited from org.jhotdraw.draw.figure.ConnectionFigure
int getNodeCount ()
Point2D.Double getPoint (int index)
BezierPath.Node getNode (int index)
Point2D.Double getStartPoint ()
Point2D.Double getEndPoint ()
Static Public Attributes
static final String LINER_PROPERTY = "liner"
Static Public Attributes inherited from org.jhotdraw.draw.figure.Figure
static final String CONNECTABLE_PROPERTY = "connectable"
static final String REMOVABLE_PROPERTY = "removable"
static final String SELECTABLE_PROPERTY = "selectable"
static final String TRANSFORMABLE_PROPERTY = "transformable"
Protected Member Functions
void handleDisconnect (Connector start, Connector end)
void handleConnect (Connector start, Connector end)
void readPoints (DOMInput in) throws IOException
void readLiner (DOMInput in) throws IOException
void writeLiner (DOMOutput out) throws IOException
void writePoints (DOMOutput out) throws IOException
Protected Member Functions inherited from org.jhotdraw.draw.figure.BezierFigure
void drawStroke (Graphics2D g)
void drawCaps (Graphics2D g)
void drawFill (Graphics2D g)
BezierPath getCappedPath ()
void removeAllNodes ()
Protected Member Functions inherited from org.jhotdraw.draw.figure.AbstractAttributedFigure
abstract void drawFill (java.awt.Graphics2D g)
abstract void drawStroke (java.awt.Graphics2D g)
void drawText (java.awt.Graphics2D g)
void writeAttributes (DOMOutput out) throws IOException
void readAttributes (DOMInput in) throws IOException
AttributeKey<?> getAttributeKey (String name)
void applyAttributesTo (Figure that)
Protected Member Functions inherited from org.jhotdraw.draw.figure.AbstractFigure
Drawing getDrawing ()
Object getLock ()
void fireAreaInvalidated (Rectangle2D.Double invalidatedArea)
void fireAreaInvalidated (FigureEvent event)
void fireFigureRequestRemove ()
void fireFigureAdded ()
void fireFigureRemoved ()
void fireFigureChanged (Rectangle2D.Double changedArea)
void fireFigureChanged (FigureEvent event)
void fireFigureHandlesChanged ()
void fireUndoableEditHappened (UndoableEdit edit)
boolean isChanging ()
int getChangingDepth ()
FontRenderContext getFontRenderContext ()
Additional Inherited Members
Protected Attributes inherited from org.jhotdraw.draw.figure.BezierFigure
BezierPath path
Protected Attributes inherited from org.jhotdraw.draw.figure.AbstractFigure
EventListenerList listenerList = new EventListenerList()
int changingDepth = 0
Detailed Description
A ConnectionFigure which connects two figures using a bezier path.
The bezier path can be laid out manually using bezier handles provided by this figure, or automatically using a Liner which can be set using the JavaBeans property
liner
.
Author
Werner Randelshofer
Version
$Id$
Constructor & Destructor Documentation
LineConnectionFigure()
org.jhotdraw.draw.figure.LineConnectionFigure.LineConnectionFigure ()
Creates a new instance.
Member Function Documentation
addNotify()
void org.jhotdraw.draw.figure.LineConnectionFigure.addNotify (Drawing drawing)
This method is invoked, when the Figure is being removed from a Drawing. This method invokes handleConnect, if the Figure is connected.
See also
handleConnect
Implements org.jhotdraw.draw.figure.Figure.
Reimplemented in org.jhotdraw.draw.figure.LabeledLineConnectionFigure.
canConnect() [1/2]
boolean org.jhotdraw.draw.figure.LineConnectionFigure.canConnect (Connector start)
Checks if this
ConnectionFigure
can be connect to the specified
Connector
. This is used to provide an early feedback to the user, when he/she creates a new connection.
Implements org.jhotdraw.draw.figure.ConnectionFigure.
References org.jhotdraw.draw.connector.Connector.getOwner(), and org.jhotdraw.draw.figure.Figure.isConnectable().
canConnect() [2/2]
boolean org.jhotdraw.draw.figure.LineConnectionFigure.canConnect (Connector start, Connector end)
Returns true, if this ConnectionFigure can connect the specified
Connector
s. Implement this method to constrain the allowed connections between figures.
Implements org.jhotdraw.draw.figure.ConnectionFigure.
References org.jhotdraw.draw.connector.Connector.getOwner(), and org.jhotdraw.draw.figure.Figure.isConnectable().
clone()
LineConnectionFigure org.jhotdraw.draw.figure.LineConnectionFigure.clone ()
Returns a clone of the figure, with clones of all aggregated figures, such as children and decorators. The cloned figure does not clone the list of FigureListeners from its original.
Reimplemented from org.jhotdraw.draw.figure.BezierFigure.
Reimplemented in org.jhotdraw.draw.figure.LabeledLineConnectionFigure.
References org.jhotdraw.draw.figure.Figure.addFigureListener(), org.jhotdraw.draw.connector.Connector.clone(), org.jhotdraw.draw.figure.LineConnectionFigure.clone(), org.jhotdraw.draw.liner.Liner.clone(), org.jhotdraw.draw.figure.LineConnectionFigure.getEndFigure(), org.jhotdraw.draw.figure.LineConnectionFigure.getStartFigure(), and org.jhotdraw.draw.figure.LineConnectionFigure.updateConnection().
Referenced by org.jhotdraw.draw.figure.LineConnectionFigure.clone().
createHandles()
Collection<Handle> org.jhotdraw.draw.figure.LineConnectionFigure.createHandles (int detailLevel)
Gets the handles of the figure. It returns the normal PolylineHandles but adds ChangeConnectionHandles at the start and end.
Reimplemented from org.jhotdraw.draw.figure.LineFigure.
References org.jhotdraw.draw.figure.LineConnectionFigure.getLiner(), and org.jhotdraw.draw.figure.ConnectionFigure.getNodeCount().
getBezierPath()
BezierPath org.jhotdraw.draw.figure.LineConnectionFigure.getBezierPath ()
FIXME - Liner must work with API of LineConnection!
Reimplemented from org.jhotdraw.draw.figure.BezierFigure.
getEndConnector()
Connector org.jhotdraw.draw.figure.LineConnectionFigure.getEndConnector ()
Gets the end Connector. Returns null, if there is no end connection.
Implements org.jhotdraw.draw.figure.ConnectionFigure.
Referenced by org.jhotdraw.draw.figure.LineConnectionFigure.setEndConnector(), org.jhotdraw.draw.figure.LineConnectionFigure.setStartConnector(), and org.jhotdraw.draw.figure.LineConnectionFigure.updateConnection().
getEndFigure()
Figure org.jhotdraw.draw.figure.LineConnectionFigure.getEndFigure ()
Gets the end figure of the connection. This is a convenience method for doing getEndConnector().getOwner() and handling null cases.
Implements org.jhotdraw.draw.figure.ConnectionFigure.
References org.jhotdraw.draw.connector.Connector.getOwner().
Referenced by org.jhotdraw.draw.figure.LineConnectionFigure.clone(), org.jhotdraw.draw.figure.LineConnectionFigure.setEndConnector(), and org.jhotdraw.draw.figure.LineConnectionFigure.setStartConnector().
getLiner()
Liner org.jhotdraw.draw.figure.LineConnectionFigure.getLiner ()
Get a Liner object which encapsulated a lineout algorithm for this figure. Typically, a Liner accesses the child components of this figure and arranges their graphical presentation.
Returns
lineout strategy used by this figure
Implements org.jhotdraw.draw.figure.ConnectionFigure.
Referenced by org.jhotdraw.draw.figure.LineConnectionFigure.createHandles().
getStartConnector()
Connector org.jhotdraw.draw.figure.LineConnectionFigure.getStartConnector ()
Gets the start
Connector
. Returns null, if there is no start connection.
Implements org.jhotdraw.draw.figure.ConnectionFigure.
Referenced by org.jhotdraw.draw.figure.LineConnectionFigure.setEndConnector(), org.jhotdraw.draw.figure.LineConnectionFigure.setStartConnector(), and org.jhotdraw.draw.figure.LineConnectionFigure.updateConnection().
getStartFigure()
Figure org.jhotdraw.draw.figure.LineConnectionFigure.getStartFigure ()
Gets the start figure of the connection. This is a convenience method for doing getStartConnector().getOwner() and handling null cases.
Implements org.jhotdraw.draw.figure.ConnectionFigure.
References org.jhotdraw.draw.connector.Connector.getOwner().
Referenced by org.jhotdraw.draw.figure.LineConnectionFigure.clone(), org.jhotdraw.draw.figure.LineConnectionFigure.setEndConnector(), and org.jhotdraw.draw.figure.LineConnectionFigure.setStartConnector().
handleConnect()
void org.jhotdraw.draw.figure.LineConnectionFigure.handleConnect (Connector start, Connector end) protected
Handles the connection of a connection. Override this method to handle this event.
Note: This method is only invoked, when the Figure is part of a Drawing. If the Figure is added to a Drawing this method is invoked on behalf of the addNotify call to the Figure.
Referenced by org.jhotdraw.draw.figure.LineConnectionFigure.setEndConnector(), and org.jhotdraw.draw.figure.LineConnectionFigure.setStartConnector().
handleDisconnect()
void org.jhotdraw.draw.figure.LineConnectionFigure.handleDisconnect (Connector start, Connector end) protected
Handles the disconnection of a connection. Override this method to handle this event.
Note: This method is only invoked, when the Figure is part of a Drawing. If the Figure is removed from a Drawing, this method is invoked on behalf of the removeNotify call to the Figure.
See also
removeNotify
Referenced by org.jhotdraw.draw.figure.LineConnectionFigure.setEndConnector(), and org.jhotdraw.draw.figure.LineConnectionFigure.setStartConnector().
handleMouseClick()
boolean org.jhotdraw.draw.figure.LineConnectionFigure.handleMouseClick (Point2D.Double p, MouseEvent evt, DrawingView view)
Handles a mouse click.
Reimplemented from org.jhotdraw.draw.figure.LineFigure.
References org.jhotdraw.draw.DrawingView.getScaleFactor().
lineout()
void org.jhotdraw.draw.figure.LineConnectionFigure.lineout ()
A "lineout" algorithm is used to define how the child components should be laid out in relation to each other. The task for layouting the child components for presentation is delegated to a Liner which can be plugged in at runtime.
Implements org.jhotdraw.draw.figure.ConnectionFigure.
References org.jhotdraw.draw.liner.Liner.lineout().
Referenced by org.jhotdraw.draw.figure.LineConnectionFigure.validate().
read()
void org.jhotdraw.draw.figure.LineConnectionFigure.read (DOMInput in) throws IOException
Reimplemented from org.jhotdraw.draw.figure.BezierFigure.
readLiner()
void org.jhotdraw.draw.figure.LineConnectionFigure.readLiner (DOMInput in) throws IOException protected
readPoints()
void org.jhotdraw.draw.figure.LineConnectionFigure.readPoints (DOMInput in) throws IOException protected
Reimplemented from org.jhotdraw.draw.figure.BezierFigure.
remap()
void org.jhotdraw.draw.figure.LineConnectionFigure.remap (Map< Figure, Figure > oldToNew, boolean disconnectIfNotInMap)
After cloning a collection of figures, the ConnectionFigures contained in this collection still connect to the original figures instead of to the clones. Using This operation and providing a map, which maps from the original collection of figures to the new collection, connections can be remapped to the new figures.
Implements org.jhotdraw.draw.figure.Figure.
Reimplemented in org.jhotdraw.draw.figure.LabeledLineConnectionFigure.
References org.jhotdraw.draw.figure.Figure.findCompatibleConnector(), and org.jhotdraw.draw.figure.Figure.get().
removeNotify()
void org.jhotdraw.draw.figure.LineConnectionFigure.removeNotify (Drawing drawing)
This method is invoked, when the Figure is being removed from a Drawing. This method invokes handleDisconnect, if the Figure is connected.
See also
handleDisconnect
Implements org.jhotdraw.draw.figure.Figure.
Reimplemented in org.jhotdraw.draw.figure.LabeledLineConnectionFigure.
reverseConnection()
void org.jhotdraw.draw.figure.LineConnectionFigure.reverseConnection ()
setConnectable()
void org.jhotdraw.draw.figure.LineConnectionFigure.setConnectable (boolean newValue)
ConnectionFigures cannot be connected and always sets connectable to false.
Reimplemented from org.jhotdraw.draw.figure.AbstractFigure.
setEndConnector()
void org.jhotdraw.draw.figure.LineConnectionFigure.setEndConnector (Connector end)
Sets the end Connector of the connection. Set this to null to disconnect the end connection.
Parameters
end the end Connector of the connection
Implements org.jhotdraw.draw.figure.ConnectionFigure.
References org.jhotdraw.draw.figure.Figure.addFigureListener(), org.jhotdraw.draw.figure.AbstractFigure.getDrawing(), org.jhotdraw.draw.figure.LineConnectionFigure.getEndConnector(), org.jhotdraw.draw.figure.LineConnectionFigure.getEndFigure(), org.jhotdraw.draw.figure.LineConnectionFigure.getStartConnector(), org.jhotdraw.draw.figure.LineConnectionFigure.getStartFigure(), org.jhotdraw.draw.figure.LineConnectionFigure.handleConnect(), org.jhotdraw.draw.figure.LineConnectionFigure.handleDisconnect(), org.jhotdraw.draw.figure.Figure.removeFigureListener(), and org.jhotdraw.draw.figure.LineConnectionFigure.updateConnection().
setEndPoint()
void org.jhotdraw.draw.figure.LineConnectionFigure.setEndPoint (Point2D.Double p)
Sets the end point.
Implements org.jhotdraw.draw.figure.ConnectionFigure.
Referenced by org.jhotdraw.draw.figure.LineConnectionFigure.updateConnection().
setLiner()
void org.jhotdraw.draw.figure.LineConnectionFigure.setLiner (Liner newValue)
Set a Liner object which encapsulated a lineout algorithm for this figure. Typically, a Liner accesses the child components of this figure and arranges their graphical presentation.
Parameters
newValue encapsulation of a lineout algorithm.
Implements org.jhotdraw.draw.figure.ConnectionFigure.
setNode()
void org.jhotdraw.draw.figure.LineConnectionFigure.setNode (int index, BezierPath.Node node)
Sets the specified node.
Implements org.jhotdraw.draw.figure.ConnectionFigure.
setPoint()
void org.jhotdraw.draw.figure.LineConnectionFigure.setPoint (int index, Point2D.Double p)
Sets the specified point.
Implements org.jhotdraw.draw.figure.ConnectionFigure.
setStartConnector()
void org.jhotdraw.draw.figure.LineConnectionFigure.setStartConnector (Connector start)
Sets the start
Connector
of the connection. Set this to null to disconnect the start connection.
Parameters
start the start Connector of the connection
Implements org.jhotdraw.draw.figure.ConnectionFigure.
References org.jhotdraw.draw.figure.Figure.addFigureListener(), org.jhotdraw.draw.figure.LineConnectionFigure.getEndConnector(), org.jhotdraw.draw.figure.LineConnectionFigure.getEndFigure(), org.jhotdraw.draw.figure.LineConnectionFigure.getStartConnector(), org.jhotdraw.draw.figure.LineConnectionFigure.getStartFigure(), org.jhotdraw.draw.figure.LineConnectionFigure.handleConnect(), org.jhotdraw.draw.figure.LineConnectionFigure.handleDisconnect(), org.jhotdraw.draw.figure.Figure.removeFigureListener(), and org.jhotdraw.draw.figure.LineConnectionFigure.updateConnection().
setStartPoint()
void org.jhotdraw.draw.figure.LineConnectionFigure.setStartPoint (Point2D.Double p)
Sets the start point.
Implements org.jhotdraw.draw.figure.ConnectionFigure.
Referenced by org.jhotdraw.draw.figure.LineConnectionFigure.updateConnection().
transform()
void org.jhotdraw.draw.figure.LineConnectionFigure.transform (AffineTransform tx)
Ensures that a connection is updated if the connection was moved.
Reimplemented from org.jhotdraw.draw.figure.BezierFigure.
Reimplemented in org.jhotdraw.draw.figure.LabeledLineConnectionFigure.
References org.jhotdraw.draw.figure.LineConnectionFigure.updateConnection().
updateConnection()
void org.jhotdraw.draw.figure.LineConnectionFigure.updateConnection ()
Updates the start and end point of the figure and fires figureChanged events.
Implements org.jhotdraw.draw.figure.ConnectionFigure.
Reimplemented in org.jhotdraw.draw.figure.LabeledLineConnectionFigure.
References org.jhotdraw.draw.figure.Figure.changed(), org.jhotdraw.draw.connector.Connector.findEnd(), org.jhotdraw.draw.connector.Connector.findStart(), org.jhotdraw.draw.figure.LineConnectionFigure.getEndConnector(), org.jhotdraw.draw.figure.LineConnectionFigure.getStartConnector(), org.jhotdraw.draw.figure.LineConnectionFigure.setEndPoint(), org.jhotdraw.draw.figure.LineConnectionFigure.setStartPoint(), and org.jhotdraw.draw.figure.Figure.willChange().
Referenced by org.jhotdraw.draw.figure.LineConnectionFigure.clone(), org.jhotdraw.draw.figure.LineConnectionFigure.setEndConnector(), org.jhotdraw.draw.figure.LineConnectionFigure.setStartConnector(), and org.jhotdraw.draw.figure.LineConnectionFigure.transform().
validate()
void org.jhotdraw.draw.figure.LineConnectionFigure.validate ()
Reimplemented from org.jhotdraw.draw.figure.BezierFigure.
Reimplemented in org.jhotdraw.draw.figure.LabeledLineConnectionFigure.
References org.jhotdraw.draw.figure.LineConnectionFigure.lineout().
write()
void org.jhotdraw.draw.figure.LineConnectionFigure.write (DOMOutput out) throws IOException
Reimplemented from org.jhotdraw.draw.figure.BezierFigure.
writeLiner()
void org.jhotdraw.draw.figure.LineConnectionFigure.writeLiner (DOMOutput out) throws IOException protected
writePoints()
void org.jhotdraw.draw.figure.LineConnectionFigure.writePoints (DOMOutput out) throws IOException protected
Reimplemented from org.jhotdraw.draw.figure.BezierFigure.
Member Data Documentation
LINER_PROPERTY
final String org.jhotdraw.draw.figure.LineConnectionFigure.LINER_PROPERTY = "liner" static
The name of the JaveBeans property
liner
.
The documentation for this class was generated from the following file:
jhotdraw-core/src/main/java/org/jhotdraw/draw/figure/LineConnectionFigure.java