jhotdraw: org.jhotdraw.draw.tool.DnDTracker Class Reference
org.jhotdraw.draw.tool.DnDTracker Class Reference
Public Member Functions
DnDTracker ()
DnDTracker (Figure figure)
void mouseMoved (MouseEvent evt)
void mousePressed (MouseEvent evt)
void mouseDragged (MouseEvent e)
void mouseReleased (MouseEvent evt)
void setDraggedFigure (Figure f)
Public Member Functions inherited from org.jhotdraw.draw.tool.AbstractTool
AbstractTool ()
void addUndoableEditListener (UndoableEditListener l)
void removeUndoableEditListener (UndoableEditListener l)
void activate (DrawingEditor editor)
void deactivate (DrawingEditor editor)
boolean isActive ()
void setInputMap (InputMap newValue)
InputMap getInputMap ()
void setActionMap (ActionMap newValue)
ActionMap getActionMap ()
void editDelete ()
void editCut ()
void editCopy ()
void editDuplicate ()
void editPaste ()
void keyReleased (KeyEvent evt)
void keyTyped (KeyEvent evt)
void keyPressed (KeyEvent evt)
void mouseClicked (MouseEvent evt)
void mouseEntered (MouseEvent evt)
void mouseExited (MouseEvent evt)
void addToolListener (ToolListener l)
void removeToolListener (ToolListener l)
void draw (Graphics2D g)
void updateCursor (DrawingView view, Point p)
String getToolTipText (DrawingView view, MouseEvent evt)
boolean supportsHandleInteraction ()
Protected Attributes
Figure anchorFigure
Rectangle2D.Double dragRect
Point2D.Double previousOrigin
Point2D.Double anchorOrigin
Point2D.Double previousPoint
Point2D.Double anchorPoint
Protected Attributes inherited from org.jhotdraw.draw.tool.AbstractTool
boolean isWorking
DrawingEditor editor
Point anchor = new Point()
EventListenerList listenerList = new EventListenerList()
Additional Inherited Members
Protected Member Functions inherited from org.jhotdraw.draw.tool.AbstractTool
DrawingView getView ()
DrawingEditor getEditor ()
Drawing getDrawing ()
Point2D.Double viewToDrawing (Point p)
Point2D.Double constrainPoint (Point p, Figure... figure)
Point2D.Double constrainPoint (Point2D.Double p, Figure... figure)
InputMap createInputMap ()
ActionMap createActionMap ()
void fireToolStarted (DrawingView view)
void fireToolDone ()
void fireAreaInvalidated (Rectangle2D.Double r)
void fireAreaInvalidated (Rectangle invalidatedArea)
void maybeFireBoundsInvalidated (Rectangle invalidatedArea)
void fireBoundsInvalidated (Rectangle invalidatedArea)
Detailed Description
This is a tracker which supports drag and drop of figures between drawing views and any other component or application which support drag and drop.
DnDTracker can be used stand-alone or instead of
DragTracker
in the
SelectionTool
or the
DelegationSelectionTool
.
To get a drag image using drag and drop, the drawing needs to provide an image output format.
Drag and Drop is about information moving, not images or objects. Its about moving a figure to another application and that application understanding both its shape, color, attributes, and everything about it - not necessarily how it looks.
Author
Werner Randelshofer
Version
$Id$
Constructor & Destructor Documentation
DnDTracker() [1/2]
org.jhotdraw.draw.tool.DnDTracker.DnDTracker ()
DnDTracker() [2/2]
org.jhotdraw.draw.tool.DnDTracker.DnDTracker (Figure figure)
References org.jhotdraw.draw.tool.DnDTracker.anchorFigure.
Member Function Documentation
mouseDragged()
void org.jhotdraw.draw.tool.DnDTracker.mouseDragged (MouseEvent e)
References org.jhotdraw.draw.DrawingView.addToSelection(), org.jhotdraw.draw.DrawingView.clearSelection(), org.jhotdraw.draw.DrawingView.findFigure(), org.jhotdraw.draw.tool.AbstractTool.fireToolDone(), org.jhotdraw.draw.DrawingView.getComponent(), org.jhotdraw.draw.DrawingView.getSelectedFigures(), and org.jhotdraw.draw.tool.AbstractTool.getView().
mouseMoved()
void org.jhotdraw.draw.tool.DnDTracker.mouseMoved (MouseEvent evt)
Reimplemented from org.jhotdraw.draw.tool.AbstractTool.
References org.jhotdraw.draw.tool.AbstractTool.editor, org.jhotdraw.draw.DrawingEditor.findView(), and org.jhotdraw.draw.tool.AbstractTool.updateCursor().
mousePressed()
void org.jhotdraw.draw.tool.DnDTracker.mousePressed (MouseEvent evt)
Reimplemented from org.jhotdraw.draw.tool.AbstractTool.
References org.jhotdraw.draw.DrawingView.addToSelection(), org.jhotdraw.draw.tool.AbstractTool.anchor, org.jhotdraw.draw.tool.DnDTracker.anchorFigure, org.jhotdraw.draw.tool.DnDTracker.anchorOrigin, org.jhotdraw.draw.tool.DnDTracker.anchorPoint, org.jhotdraw.draw.DrawingView.clearSelection(), org.jhotdraw.draw.tool.DnDTracker.dragRect, org.jhotdraw.draw.DrawingView.getSelectedFigures(), org.jhotdraw.draw.tool.AbstractTool.getView(), org.jhotdraw.draw.DrawingView.isFigureSelected(), org.jhotdraw.draw.tool.DnDTracker.previousOrigin, org.jhotdraw.draw.tool.DnDTracker.previousPoint, org.jhotdraw.draw.DrawingView.setHandleDetailLevel(), org.jhotdraw.draw.DrawingView.toggleSelection(), and org.jhotdraw.draw.DrawingView.viewToDrawing().
mouseReleased()
void org.jhotdraw.draw.tool.DnDTracker.mouseReleased (MouseEvent evt)
Reimplemented from org.jhotdraw.draw.tool.AbstractTool.
References org.jhotdraw.draw.tool.AbstractTool.editor, org.jhotdraw.draw.DrawingEditor.findView(), org.jhotdraw.draw.tool.AbstractTool.fireToolDone(), and org.jhotdraw.draw.tool.AbstractTool.updateCursor().
setDraggedFigure()
void org.jhotdraw.draw.tool.DnDTracker.setDraggedFigure (Figure f)
Implements org.jhotdraw.draw.tool.DragTracker.
References org.jhotdraw.draw.tool.DnDTracker.anchorFigure.
Member Data Documentation
anchorFigure
Figure org.jhotdraw.draw.tool.DnDTracker.anchorFigure protected
Referenced by org.jhotdraw.draw.tool.DnDTracker.DnDTracker(), org.jhotdraw.draw.tool.DnDTracker.mousePressed(), and org.jhotdraw.draw.tool.DnDTracker.setDraggedFigure().
anchorOrigin
Point2D.Double org.jhotdraw.draw.tool.DnDTracker.anchorOrigin protected
The anchorOrigin holds the origin of all dragged figures of the mousePressed event.
Referenced by org.jhotdraw.draw.tool.DnDTracker.mousePressed().
anchorPoint
Point2D.Double org.jhotdraw.draw.tool.DnDTracker.anchorPoint protected
The anchorPoint holds the location of the mouse of the mousePressed event. This coordinate is not constrained using the Constrainer of the DrawingView.
Referenced by org.jhotdraw.draw.tool.DnDTracker.mousePressed().
dragRect
Rectangle2D.Double org.jhotdraw.draw.tool.DnDTracker.dragRect protected
The drag rectangle encompasses the bounds of all dragged figures.
Referenced by org.jhotdraw.draw.tool.DnDTracker.mousePressed().
previousOrigin
Point2D.Double org.jhotdraw.draw.tool.DnDTracker.previousOrigin protected
The previousOrigin holds the origin of all dragged figures of the previous mouseDragged event. This coordinate is constrained using the Constrainer of the DrawingView.
Referenced by org.jhotdraw.draw.tool.DnDTracker.mousePressed().
previousPoint
Point2D.Double org.jhotdraw.draw.tool.DnDTracker.previousPoint protected
The previousPoint holds the location of the mouse of the previous mouseDragged event. This coordinate is not constrained using the Constrainer of the DrawingView.
Referenced by org.jhotdraw.draw.tool.DnDTracker.mousePressed().
The documentation for this class was generated from the following file:
jhotdraw-core/src/main/java/org/jhotdraw/draw/tool/DnDTracker.java