jhotdraw: org.jhotdraw.draw.tool.DefaultHandleTracker Class Reference
org.jhotdraw.draw.tool.DefaultHandleTracker Class Reference
Public Member Functions
DefaultHandleTracker (Handle handle)
DefaultHandleTracker (Handle master, Collection< Handle > handles)
DefaultHandleTracker ()
void draw (Graphics2D g)
void activate (DrawingEditor editor)
void deactivate (DrawingEditor editor)
void keyPressed (KeyEvent evt)
void keyReleased (KeyEvent evt)
void keyTyped (KeyEvent evt)
void mouseClicked (MouseEvent evt)
void mouseDragged (MouseEvent evt)
void mouseEntered (MouseEvent evt)
void mouseExited (MouseEvent evt)
void mouseMoved (MouseEvent evt)
void mousePressed (MouseEvent evt)
void mouseReleased (MouseEvent evt)
void setHandles (Handle handle, Collection< Handle > compatibleHandles)
Public Member Functions inherited from org.jhotdraw.draw.tool.AbstractTool
AbstractTool ()
void addUndoableEditListener (UndoableEditListener l)
void removeUndoableEditListener (UndoableEditListener l)
boolean isActive ()
void setInputMap (InputMap newValue)
InputMap getInputMap ()
void setActionMap (ActionMap newValue)
ActionMap getActionMap ()
void editDelete ()
void editCut ()
void editCopy ()
void editDuplicate ()
void editPaste ()
void addToolListener (ToolListener l)
void removeToolListener (ToolListener l)
void updateCursor (DrawingView view, Point p)
String getToolTipText (DrawingView view, MouseEvent evt)
boolean supportsHandleInteraction ()
Protected Member Functions
void clearHoverHandles ()
void updateHoverHandles (DrawingView view, Figure f)
Protected Member Functions inherited from org.jhotdraw.draw.tool.AbstractTool
DrawingView getView ()
DrawingEditor getEditor ()
Drawing getDrawing ()
Point2D.Double viewToDrawing (Point p)
Point2D.Double constrainPoint (Point p, Figure... figure)
Point2D.Double constrainPoint (Point2D.Double p, Figure... figure)
InputMap createInputMap ()
ActionMap createActionMap ()
void fireToolStarted (DrawingView view)
void fireToolDone ()
void fireAreaInvalidated (Rectangle2D.Double r)
void fireAreaInvalidated (Rectangle invalidatedArea)
void maybeFireBoundsInvalidated (Rectangle invalidatedArea)
void fireBoundsInvalidated (Rectangle invalidatedArea)
Additional Inherited Members
Protected Attributes inherited from org.jhotdraw.draw.tool.AbstractTool
boolean isWorking
DrawingEditor editor
Point anchor = new Point()
EventListenerList listenerList = new EventListenerList()
Detailed Description
DefaultHandleTracker implements interactions with the handles of a Figure.
The DefaultHandleTracker handles one of the three states of the SelectionTool. Iz comes into action, when the user presses the mouse button over a Figure.
Design pattern:
Name: Chain of Responsibility.
Role: Handler.
Partners: SelectionTool as Handler, SelectAreaTracker as Handler, DragTracker as Handler, DefaultHandleTracker as Handler.
Design pattern:
Name: State.
Role: State.
Partners: SelectAreaTracker as State, DragTracker as State, SelectionTool as Context.
See also
SelectionTool
Author
Werner Randelshofer
Version
$Id$
Constructor & Destructor Documentation
DefaultHandleTracker() [1/3]
org.jhotdraw.draw.tool.DefaultHandleTracker.DefaultHandleTracker (Handle handle)
Creates a new instance.
DefaultHandleTracker() [2/3]
org.jhotdraw.draw.tool.DefaultHandleTracker.DefaultHandleTracker (Handle master, Collection< Handle > handles)
DefaultHandleTracker() [3/3]
org.jhotdraw.draw.tool.DefaultHandleTracker.DefaultHandleTracker ()
Member Function Documentation
activate()
void org.jhotdraw.draw.tool.DefaultHandleTracker.activate (DrawingEditor editor)
Activates the tool for the given editor. This method is called whenever the user switches to this tool.
Reimplemented from org.jhotdraw.draw.tool.AbstractTool.
References org.jhotdraw.draw.handle.Handle.addHandleListener(), org.jhotdraw.draw.tool.DefaultHandleTracker.clearHoverHandles(), org.jhotdraw.draw.tool.AbstractTool.editor, org.jhotdraw.draw.handle.Handle.getCursor(), org.jhotdraw.draw.tool.AbstractTool.getView(), org.jhotdraw.draw.DrawingView.setActiveHandle(), and org.jhotdraw.draw.DrawingView.setCursor().
clearHoverHandles()
void org.jhotdraw.draw.tool.DefaultHandleTracker.clearHoverHandles () protected
References org.jhotdraw.draw.tool.DefaultHandleTracker.updateHoverHandles().
Referenced by org.jhotdraw.draw.tool.DefaultHandleTracker.activate(), org.jhotdraw.draw.tool.DefaultHandleTracker.deactivate(), org.jhotdraw.draw.tool.DefaultHandleTracker.mouseDragged(), org.jhotdraw.draw.tool.DefaultHandleTracker.mouseMoved(), and org.jhotdraw.draw.tool.DefaultHandleTracker.mousePressed().
deactivate()
void org.jhotdraw.draw.tool.DefaultHandleTracker.deactivate (DrawingEditor editor)
Deactivates the tool. This method is called whenever the user switches to another tool.
Reimplemented from org.jhotdraw.draw.tool.AbstractTool.
References org.jhotdraw.draw.tool.DefaultHandleTracker.clearHoverHandles(), org.jhotdraw.draw.tool.AbstractTool.editor, org.jhotdraw.draw.tool.AbstractTool.getView(), org.jhotdraw.draw.handle.Handle.removeHandleListener(), org.jhotdraw.draw.DrawingView.setActiveHandle(), and org.jhotdraw.draw.DrawingView.setCursor().
draw()
void org.jhotdraw.draw.tool.DefaultHandleTracker.draw (Graphics2D g)
Draws the tool.
Reimplemented from org.jhotdraw.draw.tool.AbstractTool.
References org.jhotdraw.draw.tool.AbstractTool.getView().
keyPressed()
void org.jhotdraw.draw.tool.DefaultHandleTracker.keyPressed (KeyEvent evt)
The Tool uses the InputMap to determine what to do, when a key is pressed. If the corresponding value of the InputMap is a String, the ActionMap of the tool is used, to find the action to be performed. If the corresponding value of the InputMap is a ActionListener, the actionPerformed method of the ActionListener is performed.
Reimplemented from org.jhotdraw.draw.tool.AbstractTool.
References org.jhotdraw.draw.tool.AbstractTool.anchor, org.jhotdraw.draw.tool.AbstractTool.getView(), org.jhotdraw.draw.event.HandleMulticaster.keyPressed(), and org.jhotdraw.draw.event.HandleMulticaster.trackStep().
keyReleased()
void org.jhotdraw.draw.tool.DefaultHandleTracker.keyReleased (KeyEvent evt)
Reimplemented from org.jhotdraw.draw.tool.AbstractTool.
References org.jhotdraw.draw.tool.AbstractTool.anchor, org.jhotdraw.draw.tool.AbstractTool.getView(), org.jhotdraw.draw.event.HandleMulticaster.keyReleased(), and org.jhotdraw.draw.event.HandleMulticaster.trackStep().
keyTyped()
void org.jhotdraw.draw.tool.DefaultHandleTracker.keyTyped (KeyEvent evt)
Reimplemented from org.jhotdraw.draw.tool.AbstractTool.
References org.jhotdraw.draw.event.HandleMulticaster.keyTyped().
mouseClicked()
void org.jhotdraw.draw.tool.DefaultHandleTracker.mouseClicked (MouseEvent evt)
Reimplemented from org.jhotdraw.draw.tool.AbstractTool.
References org.jhotdraw.draw.tool.AbstractTool.getView(), and org.jhotdraw.draw.event.HandleMulticaster.trackDoubleClick().
mouseDragged()
void org.jhotdraw.draw.tool.DefaultHandleTracker.mouseDragged (MouseEvent evt)
References org.jhotdraw.draw.tool.AbstractTool.anchor, org.jhotdraw.draw.tool.DefaultHandleTracker.clearHoverHandles(), org.jhotdraw.draw.tool.AbstractTool.getView(), and org.jhotdraw.draw.event.HandleMulticaster.trackStep().
mouseEntered()
void org.jhotdraw.draw.tool.DefaultHandleTracker.mouseEntered (MouseEvent evt)
Reimplemented from org.jhotdraw.draw.tool.AbstractTool.
mouseExited()
void org.jhotdraw.draw.tool.DefaultHandleTracker.mouseExited (MouseEvent evt)
Reimplemented from org.jhotdraw.draw.tool.AbstractTool.
References org.jhotdraw.draw.tool.AbstractTool.editor, org.jhotdraw.draw.DrawingEditor.findView(), and org.jhotdraw.draw.tool.DefaultHandleTracker.updateHoverHandles().
mouseMoved()
void org.jhotdraw.draw.tool.DefaultHandleTracker.mouseMoved (MouseEvent evt)
Reimplemented from org.jhotdraw.draw.tool.AbstractTool.
References org.jhotdraw.draw.tool.DefaultHandleTracker.clearHoverHandles(), org.jhotdraw.draw.tool.AbstractTool.editor, org.jhotdraw.draw.DrawingView.findFigure(), org.jhotdraw.draw.Drawing.findFigureBehind(), org.jhotdraw.draw.DrawingEditor.findView(), org.jhotdraw.draw.DrawingEditor.getActiveView(), org.jhotdraw.draw.DrawingView.getDrawing(), org.jhotdraw.draw.DrawingView.getSelectedFigures(), org.jhotdraw.draw.figure.Figure.isSelectable(), org.jhotdraw.draw.tool.AbstractTool.updateCursor(), org.jhotdraw.draw.tool.DefaultHandleTracker.updateHoverHandles(), and org.jhotdraw.draw.DrawingView.viewToDrawing().
mousePressed()
void org.jhotdraw.draw.tool.DefaultHandleTracker.mousePressed (MouseEvent evt)
Reimplemented from org.jhotdraw.draw.tool.AbstractTool.
References org.jhotdraw.draw.tool.AbstractTool.anchor, org.jhotdraw.draw.tool.DefaultHandleTracker.clearHoverHandles(), org.jhotdraw.draw.tool.AbstractTool.getView(), and org.jhotdraw.draw.event.HandleMulticaster.trackStart().
mouseReleased()
void org.jhotdraw.draw.tool.DefaultHandleTracker.mouseReleased (MouseEvent evt)
Reimplemented from org.jhotdraw.draw.tool.AbstractTool.
References org.jhotdraw.draw.tool.AbstractTool.anchor, org.jhotdraw.draw.tool.AbstractTool.getView(), org.jhotdraw.draw.tool.AbstractTool.maybeFireBoundsInvalidated(), and org.jhotdraw.draw.event.HandleMulticaster.trackEnd().
setHandles()
void org.jhotdraw.draw.tool.DefaultHandleTracker.setHandles (Handle handle, Collection< Handle > compatibleHandles)
Implements org.jhotdraw.draw.tool.HandleTracker.
updateHoverHandles()
void org.jhotdraw.draw.tool.DefaultHandleTracker.updateHoverHandles (DrawingView view, Figure f) protected
References org.jhotdraw.draw.figure.Figure.createHandles(), org.jhotdraw.draw.tool.AbstractTool.fireAreaInvalidated(), org.jhotdraw.draw.figure.Figure.getDrawingArea(), and org.jhotdraw.draw.figure.Figure.isSelectable().
Referenced by org.jhotdraw.draw.tool.DefaultHandleTracker.clearHoverHandles(), org.jhotdraw.draw.tool.DefaultHandleTracker.mouseExited(), and org.jhotdraw.draw.tool.DefaultHandleTracker.mouseMoved().
The documentation for this class was generated from the following file:
jhotdraw-core/src/main/java/org/jhotdraw/draw/tool/DefaultHandleTracker.java