jhotdraw: org.jhotdraw.draw.figure.QuadTreeCompositeFigure.FigureHandler Class Reference
org.jhotdraw.draw.figure.QuadTreeCompositeFigure.FigureHandler Class Reference
Public Member Functions
void undoableEditHappened (UndoableEditEvent e)
void areaInvalidated (FigureEvent e)
void figureChanged (FigureEvent e)
void figureRequestRemove (FigureEvent e)
Public Member Functions inherited from org.jhotdraw.draw.event.FigureAdapter
void attributeChanged (FigureEvent e)
void figureAdded (FigureEvent e)
void figureRemoved (FigureEvent e)
void figureHandlesChanged (FigureEvent e)
Detailed Description
Handles all figure events fired by Figures contained in the Drawing.
Member Function Documentation
areaInvalidated()
void org.jhotdraw.draw.figure.QuadTreeCompositeFigure.FigureHandler.areaInvalidated (FigureEvent e)
Sent when the drawing area used by the figure needs to be repainted.
Reimplemented from org.jhotdraw.draw.event.FigureAdapter.
References org.jhotdraw.draw.figure.AbstractFigure.fireAreaInvalidated(), and org.jhotdraw.draw.event.FigureEvent.getInvalidatedArea().
figureChanged()
void org.jhotdraw.draw.figure.QuadTreeCompositeFigure.FigureHandler.figureChanged (FigureEvent e)
Sent when the geometry (for example the bounds) of the figure has changed.
Reimplemented from org.jhotdraw.draw.event.FigureAdapter.
References org.jhotdraw.draw.figure.AbstractFigure.fireAreaInvalidated(), org.jhotdraw.draw.figure.Figure.getDrawingArea(), org.jhotdraw.draw.event.FigureEvent.getFigure(), org.jhotdraw.draw.event.FigureEvent.getInvalidatedArea(), and org.jhotdraw.draw.figure.AbstractFigure.isChanging().
figureRequestRemove()
void org.jhotdraw.draw.figure.QuadTreeCompositeFigure.FigureHandler.figureRequestRemove (FigureEvent e)
Sent when the figure requests to be removed from a drawing.
Reimplemented from org.jhotdraw.draw.event.FigureAdapter.
References org.jhotdraw.draw.event.FigureEvent.getFigure().
undoableEditHappened()
void org.jhotdraw.draw.figure.QuadTreeCompositeFigure.FigureHandler.undoableEditHappened (UndoableEditEvent e)
We propagate all edit events from our children to undoable edit listeners, which have registered with us.
References org.jhotdraw.draw.figure.AbstractFigure.fireUndoableEditHappened().
The documentation for this class was generated from the following file:
jhotdraw-core/src/main/java/org/jhotdraw/draw/figure/QuadTreeCompositeFigure.java