jhotdraw: org.jhotdraw.draw.layouter.HorizontalLayouter Class Reference
org.jhotdraw.draw.layouter.HorizontalLayouter Class Reference
Public Member Functions
Rectangle2D.Double calculateLayout (CompositeFigure compositeFigure, Point2D.Double anchor, Point2D.Double lead)
Rectangle2D.Double layout (CompositeFigure compositeFigure, Point2D.Double anchor, Point2D.Double lead)
Public Member Functions inherited from org.jhotdraw.draw.layouter.AbstractLayouter
Insets2D.Double getInsets (Figure child)
Detailed Description
A Layouter which lays out all children of a CompositeFigure in horizontal direction.
The preferred size of the figures is used to determine the layout. This may cause some figures to resize.
The HorizontalLayouter honors the LAYOUT_INSETS and the COMPOSITE_ALIGNMENT AttributeKey when laying out a CompositeFigure.
If COMPOSITE_ALIGNMENT is not set on the composite figure, the layout assigns the same height to all figures.
Author
Werner Randelshofer
Version
$Id$
Member Function Documentation
calculateLayout()
Rectangle2D.Double org.jhotdraw.draw.layouter.HorizontalLayouter.calculateLayout (CompositeFigure compositeFigure, Point2D.Double anchor, Point2D.Double lead)
Calculate the layout for the figure and all its subelements. The layout is not actually performed but just its dimensions are calculated.
Parameters
anchor start point for the layout
lead minimum lead point for the layout
Implements org.jhotdraw.draw.layouter.Layouter.
References org.jhotdraw.draw.figure.Figure.get(), org.jhotdraw.draw.figure.CompositeFigure.getChildren(), and org.jhotdraw.draw.layouter.AbstractLayouter.getInsets().
Referenced by org.jhotdraw.draw.layouter.HorizontalLayouter.layout().
layout()
Rectangle2D.Double org.jhotdraw.draw.layouter.HorizontalLayouter.layout (CompositeFigure compositeFigure, Point2D.Double anchor, Point2D.Double lead)
Method which lays out a figure. It is called by the figure if a layout task is to be performed. Implementing classes specify a certain layout algorithm in this method.
Parameters
anchor start point for the layout
lead minimum lead point for the layout
Implements org.jhotdraw.draw.layouter.Layouter.
References org.jhotdraw.draw.layouter.HorizontalLayouter.calculateLayout(), org.jhotdraw.draw.figure.Figure.get(), org.jhotdraw.draw.figure.CompositeFigure.getChildren(), and org.jhotdraw.draw.layouter.AbstractLayouter.getInsets().
The documentation for this class was generated from the following file:
jhotdraw-core/src/main/java/org/jhotdraw/draw/layouter/HorizontalLayouter.java