jhotdraw: org.jhotdraw.draw.figure.AbstractCompositeFigure.EventHandler Class Reference
org.jhotdraw.draw.figure.AbstractCompositeFigure.EventHandler Class Reference
Public Member Functions
void figureRequestRemove (FigureEvent e)
void figureChanged (FigureEvent e)
void areaInvalidated (FigureEvent e)
void undoableEditHappened (UndoableEditEvent e)
void attributeChanged (FigureEvent e)
void figureAdded (FigureEvent e)
void figureRemoved (FigureEvent e)
Public Member Functions inherited from org.jhotdraw.draw.event.FigureAdapter
void figureHandlesChanged (FigureEvent e)
Member Function Documentation
areaInvalidated()
void org.jhotdraw.draw.figure.AbstractCompositeFigure.EventHandler.areaInvalidated (FigureEvent e)
Sent when the drawing area used by the figure needs to be repainted.
Reimplemented from org.jhotdraw.draw.event.FigureAdapter.
References org.jhotdraw.draw.figure.AbstractFigure.fireAreaInvalidated().
attributeChanged()
void org.jhotdraw.draw.figure.AbstractCompositeFigure.EventHandler.attributeChanged (FigureEvent e)
Sent when an attribute of the figure has changed.
Reimplemented from org.jhotdraw.draw.event.FigureAdapter.
References org.jhotdraw.draw.figure.AbstractCompositeFigure.invalidate().
figureAdded()
void org.jhotdraw.draw.figure.AbstractCompositeFigure.EventHandler.figureAdded (FigureEvent e)
Sent when a figure was added to a drawing.
Reimplemented from org.jhotdraw.draw.event.FigureAdapter.
References org.jhotdraw.draw.figure.AbstractCompositeFigure.invalidate().
figureChanged()
void org.jhotdraw.draw.figure.AbstractCompositeFigure.EventHandler.figureChanged (FigureEvent e)
Sent when the geometry (for example the bounds) of the figure has changed.
Reimplemented from org.jhotdraw.draw.event.FigureAdapter.
Reimplemented in org.jhotdraw.draw.QuadTreeDrawing.QuadTreeEventHandler.
References org.jhotdraw.draw.figure.AbstractFigure.fireFigureChanged(), org.jhotdraw.draw.figure.AbstractCompositeFigure.getDrawingArea(), org.jhotdraw.draw.event.FigureEvent.getInvalidatedArea(), org.jhotdraw.draw.figure.AbstractCompositeFigure.invalidate(), org.jhotdraw.draw.figure.AbstractFigure.isChanging(), and org.jhotdraw.draw.figure.AbstractCompositeFigure.validate().
figureRemoved()
void org.jhotdraw.draw.figure.AbstractCompositeFigure.EventHandler.figureRemoved (FigureEvent e)
Sent when a figure was removed from a drawing.
Reimplemented from org.jhotdraw.draw.event.FigureAdapter.
References org.jhotdraw.draw.figure.AbstractCompositeFigure.invalidate().
figureRequestRemove()
void org.jhotdraw.draw.figure.AbstractCompositeFigure.EventHandler.figureRequestRemove (FigureEvent e)
Sent when the figure requests to be removed from a drawing.
Reimplemented from org.jhotdraw.draw.event.FigureAdapter.
References org.jhotdraw.draw.event.FigureEvent.getFigure().
undoableEditHappened()
void org.jhotdraw.draw.figure.AbstractCompositeFigure.EventHandler.undoableEditHappened (UndoableEditEvent e)
References org.jhotdraw.draw.figure.AbstractFigure.fireUndoableEditHappened().
The documentation for this class was generated from the following file:
jhotdraw-core/src/main/java/org/jhotdraw/draw/figure/AbstractCompositeFigure.java