jhotdraw: org.jhotdraw.draw.figure.EllipseFigure Class Reference
org.jhotdraw.draw.figure.EllipseFigure Class Reference
Public Member Functions
EllipseFigure ()
EllipseFigure (double x, double y, double width, double height)
Connector findConnector (Point2D.Double p, ConnectionFigure prototype)
Connector findCompatibleConnector (Connector c, boolean isStartConnector)
Rectangle2D.Double getBounds ()
Rectangle2D.Double getDrawingArea ()
boolean contains (Point2D.Double p)
void setBounds (Point2D.Double anchor, Point2D.Double lead)
void transform (AffineTransform tx)
EllipseFigure clone ()
void restoreTransformTo (Object geometry)
Object getTransformRestoreData ()
Public Member Functions inherited from org.jhotdraw.draw.figure.AbstractAttributedFigure
AbstractAttributedFigure ()
void setAttributeEnabled (AttributeKey<?> key, boolean b)
boolean isAttributeEnabled (AttributeKey<?> key)
void setAttributes (Map< AttributeKey<?>, Object > map)
Map< AttributeKey<?>, Object > getAttributes ()
Object getAttributesRestoreData ()
void restoreAttributesTo (Object restoreData)
void draw (Graphics2D g)
double getStrokeMiterLimitFactor ()
Rectangle2D.Double getDrawingArea (double factor)
void write (DOMOutput out) throws IOException
void read (DOMInput in) throws IOException
boolean hasAttribute (AttributeKey<?> key)
Public Member Functions inherited from org.jhotdraw.draw.figure.AbstractFigure
AbstractFigure ()
void addFigureListener (FigureListener l)
void removeFigureListener (FigureListener l)
void addNotify (Drawing d)
void removeNotify (Drawing d)
void fireAreaInvalidated ()
void fireFigureChanged ()
void remap (Map< Figure, Figure > oldToNew, boolean disconnectIfNotInMap)
Collection< Handle > createHandles (int detailLevel)
Cursor getCursor (Point2D.Double p)
final void setBounds (Rectangle2D.Double bounds)
void willChange ()
void changed ()
boolean includes (Figure figure)
Figure findFigureInside (Point2D.Double p)
Collection< Action > getActions (Point2D.Double p)
Tool getTool (Point2D.Double p)
boolean handleMouseClick (Point2D.Double p, MouseEvent evt, DrawingView view)
boolean handleDrop (Point2D.Double p, Collection< Figure > droppedFigures, DrawingView view)
Point2D.Double getEndPoint ()
Point2D.Double getStartPoint ()
Dimension2DDouble getPreferredSize ()
boolean isConnectable ()
void setConnectable (boolean newValue)
boolean isSelectable ()
void setSelectable (boolean newValue)
boolean isRemovable ()
void setRemovable (boolean newValue)
boolean isTransformable ()
void setTransformable (boolean newValue)
boolean isVisible ()
void setVisible (boolean newValue)
Collection< Figure > getDecomposition ()
void requestRemove ()
int getLayer ()
String getToolTipText (Point2D.Double p)
String toString ()
Collection< Connector > getConnectors (ConnectionFigure prototype)
Public Member Functions inherited from org.jhotdraw.draw.figure.Figure
void addPropertyChangeListener (PropertyChangeListener listener)
void removePropertyChangeListener (PropertyChangeListener listener)
Protected Member Functions
void drawFill (Graphics2D g)
void drawStroke (Graphics2D g)
Protected Member Functions inherited from org.jhotdraw.draw.figure.AbstractAttributedFigure
abstract void drawFill (java.awt.Graphics2D g)
abstract void drawStroke (java.awt.Graphics2D g)
void drawText (java.awt.Graphics2D g)
void writeAttributes (DOMOutput out) throws IOException
void readAttributes (DOMInput in) throws IOException
AttributeKey<?> getAttributeKey (String name)
void applyAttributesTo (Figure that)
Protected Member Functions inherited from org.jhotdraw.draw.figure.AbstractFigure
Drawing getDrawing ()
Object getLock ()
void fireAreaInvalidated (Rectangle2D.Double invalidatedArea)
void fireAreaInvalidated (FigureEvent event)
void fireFigureRequestRemove ()
void fireFigureAdded ()
void fireFigureRemoved ()
void fireFigureChanged (Rectangle2D.Double changedArea)
void fireFigureChanged (FigureEvent event)
void fireFigureHandlesChanged ()
void fireUndoableEditHappened (UndoableEdit edit)
void invalidate ()
boolean isChanging ()
int getChangingDepth ()
void validate ()
FontRenderContext getFontRenderContext ()
Protected Attributes
Ellipse2D.Double ellipse
Protected Attributes inherited from org.jhotdraw.draw.figure.AbstractFigure
EventListenerList listenerList = new EventListenerList()
int changingDepth = 0
Additional Inherited Members
Static Public Attributes inherited from org.jhotdraw.draw.figure.Figure
static final String CONNECTABLE_PROPERTY = "connectable"
static final String REMOVABLE_PROPERTY = "removable"
static final String SELECTABLE_PROPERTY = "selectable"
static final String TRANSFORMABLE_PROPERTY = "transformable"
Detailed Description
A Figure with an elliptic shape.
Author
Werner Randelshofer
Version
$Id$
Constructor & Destructor Documentation
EllipseFigure() [1/2]
org.jhotdraw.draw.figure.EllipseFigure.EllipseFigure ()
Constructs a new
EllipseFigure
, initialized to location (0, 0) and size (0, 0).
Referenced by org.jhotdraw.draw.figure.EllipseFigure.clone().
EllipseFigure() [2/2]
org.jhotdraw.draw.figure.EllipseFigure.EllipseFigure (double x, double y, double width, double height)
Constructs and initializes an
EllipseFigure
from the specified coordinates.
Parameters
x the x coordinate of the bounding rectangle
y the y coordinate of the bounding rectangle
width the width of the rectangle
height the height of the rectangle
References org.jhotdraw.draw.figure.EllipseFigure.ellipse.
Member Function Documentation
clone()
EllipseFigure org.jhotdraw.draw.figure.EllipseFigure.clone ()
Returns a clone of the figure, with clones of all aggregated figures, such as children and decorators. The cloned figure does not clone the list of FigureListeners from its original.
Reimplemented from org.jhotdraw.draw.figure.AbstractAttributedFigure.
References org.jhotdraw.draw.figure.EllipseFigure.clone(), org.jhotdraw.draw.figure.EllipseFigure.ellipse, and org.jhotdraw.draw.figure.EllipseFigure.EllipseFigure().
Referenced by org.jhotdraw.draw.figure.EllipseFigure.clone().
contains()
boolean org.jhotdraw.draw.figure.EllipseFigure.contains (Point2D.Double p)
Checks if a Point2D.Double is inside the figure.
Implements org.jhotdraw.draw.figure.Figure.
References org.jhotdraw.draw.figure.EllipseFigure.ellipse, and org.jhotdraw.draw.AttributeKeys.getPerpendicularHitGrowth().
drawFill()
void org.jhotdraw.draw.figure.EllipseFigure.drawFill (Graphics2D g) protected
References org.jhotdraw.draw.figure.EllipseFigure.ellipse, org.jhotdraw.draw.AttributeKeys.getPerpendicularFillGrowth(), and org.jhotdraw.draw.AttributeKeys.getScaleFactorFromGraphics().
drawStroke()
void org.jhotdraw.draw.figure.EllipseFigure.drawStroke (Graphics2D g) protected
References org.jhotdraw.draw.figure.EllipseFigure.ellipse, org.jhotdraw.draw.AttributeKeys.getPerpendicularDrawGrowth(), and org.jhotdraw.draw.AttributeKeys.getScaleFactorFromGraphics().
findCompatibleConnector()
Connector org.jhotdraw.draw.figure.EllipseFigure.findCompatibleConnector (Connector c, boolean isStartConnector)
Gets a compatible connector. If the provided connector is part of this figure, return the connector. If the provided connector is part of another figure, return a connector with the same semantics for this figure. Returns null, if no compatible connector is available.
Reimplemented from org.jhotdraw.draw.figure.AbstractFigure.
findConnector()
Connector org.jhotdraw.draw.figure.EllipseFigure.findConnector (Point2D.Double p, ConnectionFigure prototype)
Returns the Figures connector for the specified location. By default a ChopBoxConnector is returned.
See also
ChopRectangleConnector
Reimplemented from org.jhotdraw.draw.figure.AbstractFigure.
getBounds()
Rectangle2D.Double org.jhotdraw.draw.figure.EllipseFigure.getBounds ()
Returns the untransformed logical bounds of the figure as a Rectangle.
The bounds are used by Handle objects for adjusting the figure and for aligning the figure on a grid.
Implements org.jhotdraw.draw.figure.Figure.
References org.jhotdraw.draw.figure.EllipseFigure.ellipse.
getDrawingArea()
Rectangle2D.Double org.jhotdraw.draw.figure.EllipseFigure.getDrawingArea ()
Returns the drawing area of the figure as a Rectangle.
The drawing area is used to inform DrawingView about the area that is needed to draw this figure.
The drawing area needs to be large enough, to take line width, line caps and other decorations into account that exceed the bounds of the Figure.
Reimplemented from org.jhotdraw.draw.figure.AbstractAttributedFigure.
References org.jhotdraw.draw.figure.EllipseFigure.ellipse, and org.jhotdraw.draw.AttributeKeys.getPerpendicularHitGrowth().
getTransformRestoreData()
Object org.jhotdraw.draw.figure.EllipseFigure.getTransformRestoreData ()
Gets data which can be used to restore the transformation of the figure without loss of precision, after a transform has been applied to it.
See also
transform(AffineTransform)
Implements org.jhotdraw.draw.figure.Figure.
References org.jhotdraw.draw.figure.EllipseFigure.ellipse.
restoreTransformTo()
void org.jhotdraw.draw.figure.EllipseFigure.restoreTransformTo (Object restoreData)
Restores the transform of the figure to a previously stored state.
Implements org.jhotdraw.draw.figure.Figure.
References org.jhotdraw.draw.figure.EllipseFigure.ellipse.
setBounds()
void org.jhotdraw.draw.figure.EllipseFigure.setBounds (Point2D.Double start, Point2D.Double end)
Sets the logical and untransformed bounds of the figure.
This is used by Tool's which create a new Figure and by Tool's which connect a Figure to another Figure.
This is a basic operation which does not fire events. Use the following code sequence, if you need event firing:
figure.willChange();
figure.setBounds(...);
figure.changed();
Parameters
start the start point of the bounds
end the end point of the bounds
See also
getBounds
Reimplemented from org.jhotdraw.draw.figure.AbstractFigure.
References org.jhotdraw.draw.figure.EllipseFigure.ellipse.
Referenced by org.jhotdraw.draw.figure.EllipseFigure.transform().
transform()
void org.jhotdraw.draw.figure.EllipseFigure.transform (AffineTransform tx)
Transforms the figure.
Parameters
tx the transformation.
Implements org.jhotdraw.draw.figure.Figure.
References org.jhotdraw.draw.figure.AbstractFigure.getEndPoint(), org.jhotdraw.draw.figure.AbstractFigure.getStartPoint(), and org.jhotdraw.draw.figure.EllipseFigure.setBounds().
Member Data Documentation
ellipse
Ellipse2D.Double org.jhotdraw.draw.figure.EllipseFigure.ellipse protected
Referenced by org.jhotdraw.draw.figure.EllipseFigure.clone(), org.jhotdraw.draw.figure.EllipseFigure.contains(), org.jhotdraw.draw.figure.EllipseFigure.drawFill(), org.jhotdraw.draw.figure.EllipseFigure.drawStroke(), org.jhotdraw.draw.figure.EllipseFigure.EllipseFigure(), org.jhotdraw.draw.figure.EllipseFigure.getBounds(), org.jhotdraw.draw.figure.EllipseFigure.getDrawingArea(), org.jhotdraw.draw.figure.EllipseFigure.getTransformRestoreData(), org.jhotdraw.draw.figure.EllipseFigure.restoreTransformTo(), and org.jhotdraw.draw.figure.EllipseFigure.setBounds().
The documentation for this class was generated from the following file:
jhotdraw-core/src/main/java/org/jhotdraw/draw/figure/EllipseFigure.java