jhotdraw: org.jhotdraw.draw.tool.ConnectionTool Class Reference
org.jhotdraw.draw.tool.ConnectionTool Class Reference
Public Member Functions
ConnectionTool (ConnectionFigure prototype)
ConnectionTool (ConnectionFigure prototype, Map< AttributeKey<?>, Object > attributes)
ConnectionTool (ConnectionFigure prototype, Map< AttributeKey<?>, Object > attributes, String presentationName)
ConnectionTool (String prototypeClassName)
ConnectionTool (String prototypeClassName, Map< AttributeKey<?>, Object > attributes, String presentationName)
ConnectionFigure getPrototype ()
void mouseMoved (MouseEvent evt)
void repaintConnectors (MouseEvent evt)
void mousePressed (MouseEvent evt)
void mouseDragged (java.awt.event.MouseEvent e)
void mouseReleased (MouseEvent e)
void activate (DrawingEditor editor)
void deactivate (DrawingEditor editor)
void draw (Graphics2D g)
void setToolDoneAfterCreation (boolean newValue)
boolean isToolDoneAfterCreation ()
Public Member Functions inherited from org.jhotdraw.draw.tool.AbstractTool
AbstractTool ()
void addUndoableEditListener (UndoableEditListener l)
void removeUndoableEditListener (UndoableEditListener l)
boolean isActive ()
void setInputMap (InputMap newValue)
InputMap getInputMap ()
void setActionMap (ActionMap newValue)
ActionMap getActionMap ()
void editDelete ()
void editCut ()
void editCopy ()
void editDuplicate ()
void editPaste ()
void keyReleased (KeyEvent evt)
void keyTyped (KeyEvent evt)
void keyPressed (KeyEvent evt)
void mouseClicked (MouseEvent evt)
void mouseEntered (MouseEvent evt)
void mouseExited (MouseEvent evt)
void addToolListener (ToolListener l)
void removeToolListener (ToolListener l)
void updateCursor (DrawingView view, Point p)
String getToolTipText (DrawingView view, MouseEvent evt)
boolean supportsHandleInteraction ()
Protected Member Functions
int getAnchorWidth ()
boolean canConnect (ConnectionFigure f, Connector startConnector)
boolean canConnect (ConnectionFigure f, Connector startConnector, Connector endConnector)
ConnectionFigure createFigure ()
void creationFinished (Figure createdFigure)
Protected Member Functions inherited from org.jhotdraw.draw.tool.AbstractTool
DrawingView getView ()
DrawingEditor getEditor ()
Drawing getDrawing ()
Point2D.Double viewToDrawing (Point p)
Point2D.Double constrainPoint (Point p, Figure... figure)
Point2D.Double constrainPoint (Point2D.Double p, Figure... figure)
InputMap createInputMap ()
ActionMap createActionMap ()
void fireToolStarted (DrawingView view)
void fireToolDone ()
void fireAreaInvalidated (Rectangle2D.Double r)
void fireAreaInvalidated (Rectangle invalidatedArea)
void maybeFireBoundsInvalidated (Rectangle invalidatedArea)
void fireBoundsInvalidated (Rectangle invalidatedArea)
Protected Attributes
Connector startConnector
Connector endConnector
ConnectionFigure createdFigure
ConnectionFigure prototype
Figure targetFigure
Collection< Connector > connectors = Collections.emptyList()
Protected Attributes inherited from org.jhotdraw.draw.tool.AbstractTool
boolean isWorking
DrawingEditor editor
Point anchor = new Point()
EventListenerList listenerList = new EventListenerList()
Detailed Description
A tool to create a connection between two figures. The ConnectionFigure to be created is specified by a prototype. The location of the start and end points are controlled by Connectors.
To create a connection using the ConnectionTool, the user does the following mouse gestures on a DrawingView:
Press the mouse button inside of a Figure. If the ConnectionTool can find a Connector at this location, it uses it as the starting point for the connection.
Drag the mouse while keeping the mouse button pressed, and then release the mouse button. This defines the end point of the connection. If the ConnectionTool finds a Connector at this location, it uses it as the end point of the connection and creates a ConnectionFigure.
Design Patterns
Framework
Two figures can be connected using a connection figure. The location of the start or end point of the connection is handled by a connector object at each connected figure.
Contract: org.jhotdraw.draw.Figure, org.jhotdraw.draw.ConnectionFigure, org.jhotdraw.draw.connector.Connector, org.jhotdraw.draw.tool.ConnectionTool.
Author
Werner Randelshofer
Version
$Id$
Constructor & Destructor Documentation
ConnectionTool() [1/5]
org.jhotdraw.draw.tool.ConnectionTool.ConnectionTool (ConnectionFigure prototype)
Creates a new instance.
References org.jhotdraw.draw.tool.ConnectionTool.prototype.
ConnectionTool() [2/5]
org.jhotdraw.draw.tool.ConnectionTool.ConnectionTool (ConnectionFigure prototype, Map< AttributeKey<?>, Object > attributes)
References org.jhotdraw.draw.tool.ConnectionTool.prototype.
ConnectionTool() [3/5]
org.jhotdraw.draw.tool.ConnectionTool.ConnectionTool (ConnectionFigure prototype, Map< AttributeKey<?>, Object > attributes, String presentationName)
References org.jhotdraw.draw.tool.ConnectionTool.prototype.
ConnectionTool() [4/5]
org.jhotdraw.draw.tool.ConnectionTool.ConnectionTool (String prototypeClassName)
ConnectionTool() [5/5]
org.jhotdraw.draw.tool.ConnectionTool.ConnectionTool (String prototypeClassName, Map< AttributeKey<?>, Object > attributes, String presentationName)
Member Function Documentation
activate()
void org.jhotdraw.draw.tool.ConnectionTool.activate (DrawingEditor editor)
Activates the tool for the given editor. This method is called whenever the user switches to this tool.
Reimplemented from org.jhotdraw.draw.tool.AbstractTool.
References org.jhotdraw.draw.tool.AbstractTool.editor.
canConnect() [1/2]
boolean org.jhotdraw.draw.tool.ConnectionTool.canConnect (ConnectionFigure f, Connector startConnector) protected
This method is called on the Figure, onto which the user wants to start a new connection.
Parameters
f The ConnectionFigure.
startConnector The Connector of the start Figure.
Returns
True, if a connection can be made.
References org.jhotdraw.draw.figure.ConnectionFigure.canConnect(), and org.jhotdraw.draw.tool.ConnectionTool.startConnector.
Referenced by org.jhotdraw.draw.tool.ConnectionTool.mouseDragged(), and org.jhotdraw.draw.tool.ConnectionTool.mousePressed().
canConnect() [2/2]
boolean org.jhotdraw.draw.tool.ConnectionTool.canConnect (ConnectionFigure f, Connector startConnector, Connector endConnector) protected
This method is called on the Figure, onto which the user wants to end a new connection.
Parameters
f The ConnectionFigure.
startConnector The Connector of the start Figure.
endConnector The Connector of the end Figure.
Returns
True, if a connection can be made.
References org.jhotdraw.draw.figure.ConnectionFigure.canConnect(), org.jhotdraw.draw.tool.ConnectionTool.endConnector, and org.jhotdraw.draw.tool.ConnectionTool.startConnector.
createFigure()
ConnectionFigure org.jhotdraw.draw.tool.ConnectionTool.createFigure () protected
Creates the ConnectionFigure. By default the figure prototype is cloned.
References org.jhotdraw.draw.DrawingEditor.applyDefaultAttributesTo(), org.jhotdraw.draw.figure.Figure.clone(), org.jhotdraw.draw.tool.AbstractTool.getEditor(), org.jhotdraw.draw.tool.ConnectionTool.prototype, and org.jhotdraw.draw.figure.Figure.set().
Referenced by org.jhotdraw.draw.tool.ConnectionTool.mousePressed().
creationFinished()
void org.jhotdraw.draw.tool.ConnectionTool.creationFinished (Figure createdFigure) protected
This method allows subclasses to do perform additonal user interactions after the new figure has been created. The implementation of this class just invokes fireToolDone.
References org.jhotdraw.draw.tool.AbstractTool.fireToolDone().
Referenced by org.jhotdraw.draw.tool.ConnectionTool.mouseReleased().
deactivate()
void org.jhotdraw.draw.tool.ConnectionTool.deactivate (DrawingEditor editor)
Deactivates the tool. This method is called whenever the user switches to another tool.
Reimplemented from org.jhotdraw.draw.tool.AbstractTool.
References org.jhotdraw.draw.tool.ConnectionTool.createdFigure, org.jhotdraw.draw.tool.AbstractTool.editor, org.jhotdraw.draw.tool.ConnectionTool.endConnector, org.jhotdraw.draw.tool.AbstractTool.getDrawing(), org.jhotdraw.draw.Drawing.remove(), org.jhotdraw.draw.tool.ConnectionTool.startConnector, and org.jhotdraw.draw.tool.ConnectionTool.targetFigure.
draw()
void org.jhotdraw.draw.tool.ConnectionTool.draw (Graphics2D g)
Draws the tool.
Reimplemented from org.jhotdraw.draw.tool.AbstractTool.
References org.jhotdraw.draw.tool.ConnectionTool.createdFigure, org.jhotdraw.draw.figure.Figure.draw(), org.jhotdraw.draw.DrawingView.drawingToView(), org.jhotdraw.draw.figure.Figure.getConnectors(), org.jhotdraw.draw.DrawingView.getDrawingToViewTransform(), org.jhotdraw.draw.figure.ConnectionFigure.getEndPoint(), org.jhotdraw.draw.tool.ConnectionTool.getPrototype(), org.jhotdraw.draw.figure.ConnectionFigure.getStartPoint(), org.jhotdraw.draw.tool.AbstractTool.getView(), and org.jhotdraw.draw.tool.ConnectionTool.targetFigure.
getAnchorWidth()
int org.jhotdraw.draw.tool.ConnectionTool.getAnchorWidth () protected
getPrototype()
ConnectionFigure org.jhotdraw.draw.tool.ConnectionTool.getPrototype ()
References org.jhotdraw.draw.tool.ConnectionTool.prototype.
Referenced by org.jhotdraw.draw.tool.ConnectionTool.draw(), and org.jhotdraw.draw.tool.ConnectionTool.repaintConnectors().
isToolDoneAfterCreation()
boolean org.jhotdraw.draw.tool.ConnectionTool.isToolDoneAfterCreation ()
Returns true, if this tool fires toolDone immediately after a new figure has been created.
mouseDragged()
void org.jhotdraw.draw.tool.ConnectionTool.mouseDragged (java.awt.event.MouseEvent e)
Adjust the created connection.
References org.jhotdraw.draw.tool.ConnectionTool.canConnect(), org.jhotdraw.draw.figure.Figure.changed(), org.jhotdraw.draw.Constrainer.constrainPoint(), org.jhotdraw.draw.tool.ConnectionTool.createdFigure, org.jhotdraw.draw.tool.ConnectionTool.endConnector, org.jhotdraw.draw.figure.Figure.findConnector(), org.jhotdraw.draw.Drawing.findFigureExcept(), org.jhotdraw.draw.connector.Connector.getAnchor(), org.jhotdraw.draw.DrawingView.getComponent(), org.jhotdraw.draw.DrawingView.getConstrainer(), org.jhotdraw.draw.tool.AbstractTool.getDrawing(), org.jhotdraw.draw.figure.ConnectionFigure.getEndPoint(), org.jhotdraw.draw.tool.AbstractTool.getView(), org.jhotdraw.draw.tool.ConnectionTool.prototype, org.jhotdraw.draw.tool.ConnectionTool.repaintConnectors(), org.jhotdraw.draw.figure.ConnectionFigure.setEndPoint(), org.jhotdraw.draw.tool.ConnectionTool.startConnector, org.jhotdraw.draw.tool.AbstractTool.viewToDrawing(), and org.jhotdraw.draw.figure.Figure.willChange().
mouseMoved()
void org.jhotdraw.draw.tool.ConnectionTool.mouseMoved (MouseEvent evt)
Reimplemented from org.jhotdraw.draw.tool.AbstractTool.
References org.jhotdraw.draw.tool.ConnectionTool.repaintConnectors().
mousePressed()
void org.jhotdraw.draw.tool.ConnectionTool.mousePressed (MouseEvent evt)
Manipulates connections in a context dependent way. If the mouse down hits a figure start a new connection. If the mousedown hits a connection split a segment or join two segments.
Reimplemented from org.jhotdraw.draw.tool.AbstractTool.
References org.jhotdraw.draw.Drawing.add(), org.jhotdraw.draw.tool.AbstractTool.anchor, org.jhotdraw.draw.tool.ConnectionTool.canConnect(), org.jhotdraw.draw.DrawingView.clearSelection(), org.jhotdraw.draw.tool.ConnectionTool.createdFigure, org.jhotdraw.draw.tool.ConnectionTool.createFigure(), org.jhotdraw.draw.tool.ConnectionTool.endConnector, org.jhotdraw.draw.figure.Figure.findConnector(), org.jhotdraw.draw.Drawing.findFigure(), org.jhotdraw.draw.tool.AbstractTool.fireAreaInvalidated(), org.jhotdraw.draw.connector.Connector.getAnchor(), org.jhotdraw.draw.tool.AbstractTool.getDrawing(), org.jhotdraw.draw.tool.AbstractTool.getView(), org.jhotdraw.draw.tool.ConnectionTool.prototype, org.jhotdraw.draw.figure.ConnectionFigure.setEndPoint(), org.jhotdraw.draw.figure.ConnectionFigure.setStartPoint(), org.jhotdraw.draw.tool.ConnectionTool.startConnector, and org.jhotdraw.draw.tool.AbstractTool.viewToDrawing().
mouseReleased()
void org.jhotdraw.draw.tool.ConnectionTool.mouseReleased (MouseEvent e)
Connects the figures if the mouse is released over another figure.
Reimplemented from org.jhotdraw.draw.tool.AbstractTool.
References org.jhotdraw.draw.Drawing.add(), org.jhotdraw.draw.tool.AbstractTool.anchor, org.jhotdraw.draw.figure.ConnectionFigure.canConnect(), org.jhotdraw.draw.figure.Figure.changed(), org.jhotdraw.draw.tool.ConnectionTool.createdFigure, org.jhotdraw.draw.tool.ConnectionTool.creationFinished(), org.jhotdraw.draw.tool.ConnectionTool.endConnector, org.jhotdraw.draw.tool.AbstractTool.fireAreaInvalidated(), org.jhotdraw.draw.tool.AbstractTool.fireToolDone(), org.jhotdraw.draw.Drawing.fireUndoableEditHappened(), org.jhotdraw.draw.connector.Connector.getAnchor(), org.jhotdraw.draw.tool.AbstractTool.getDrawing(), org.jhotdraw.draw.tool.AbstractTool.getView(), org.jhotdraw.draw.Drawing.remove(), org.jhotdraw.draw.figure.ConnectionFigure.setEndConnector(), org.jhotdraw.draw.figure.ConnectionFigure.setStartConnector(), org.jhotdraw.draw.tool.ConnectionTool.startConnector, org.jhotdraw.draw.tool.ConnectionTool.targetFigure, org.jhotdraw.draw.figure.ConnectionFigure.updateConnection(), and org.jhotdraw.draw.figure.Figure.willChange().
repaintConnectors()
void org.jhotdraw.draw.tool.ConnectionTool.repaintConnectors (MouseEvent evt)
Updates the list of connectors that we draw when the user moves or drags the mouse over a figure to which can connect.
References org.jhotdraw.draw.tool.ConnectionTool.connectors, org.jhotdraw.draw.tool.ConnectionTool.createdFigure, org.jhotdraw.draw.Drawing.findFigureExcept(), org.jhotdraw.draw.DrawingView.getComponent(), org.jhotdraw.draw.figure.Figure.getConnectors(), org.jhotdraw.draw.tool.AbstractTool.getDrawing(), org.jhotdraw.draw.figure.Figure.getDrawingArea(), org.jhotdraw.draw.tool.ConnectionTool.getPrototype(), org.jhotdraw.draw.tool.AbstractTool.getView(), org.jhotdraw.draw.figure.Figure.isConnectable(), org.jhotdraw.draw.tool.ConnectionTool.targetFigure, and org.jhotdraw.draw.tool.AbstractTool.viewToDrawing().
Referenced by org.jhotdraw.draw.tool.ConnectionTool.mouseDragged(), and org.jhotdraw.draw.tool.ConnectionTool.mouseMoved().
setToolDoneAfterCreation()
void org.jhotdraw.draw.tool.ConnectionTool.setToolDoneAfterCreation (boolean newValue)
If this is set to false, the CreationTool does not fire toolDone after a new Figure has been created. This allows to create multiple figures consecutively.
Member Data Documentation
connectors
Collection<Connector> org.jhotdraw.draw.tool.ConnectionTool.connectors = Collections.emptyList() protected
Referenced by org.jhotdraw.draw.tool.ConnectionTool.repaintConnectors().
createdFigure
ConnectionFigure org.jhotdraw.draw.tool.ConnectionTool.createdFigure protected
The created figure.
Referenced by org.jhotdraw.draw.tool.ConnectionTool.deactivate(), org.jhotdraw.draw.tool.ConnectionTool.draw(), org.jhotdraw.draw.tool.ConnectionTool.mouseDragged(), org.jhotdraw.draw.tool.ConnectionTool.mousePressed(), org.jhotdraw.draw.tool.ConnectionTool.mouseReleased(), and org.jhotdraw.draw.tool.ConnectionTool.repaintConnectors().
endConnector
Connector org.jhotdraw.draw.tool.ConnectionTool.endConnector protected
The Connector at the end point of the connection.
Referenced by org.jhotdraw.draw.tool.ConnectionTool.canConnect(), org.jhotdraw.draw.tool.ConnectionTool.deactivate(), org.jhotdraw.draw.tool.ConnectionTool.mouseDragged(), org.jhotdraw.draw.tool.ConnectionTool.mousePressed(), and org.jhotdraw.draw.tool.ConnectionTool.mouseReleased().
prototype
ConnectionFigure org.jhotdraw.draw.tool.ConnectionTool.prototype protected
the prototypical figure that is used to create new connections.
Referenced by org.jhotdraw.draw.tool.ConnectionTool.ConnectionTool(), org.jhotdraw.draw.tool.ConnectionTool.createFigure(), org.jhotdraw.draw.tool.ConnectionTool.getPrototype(), org.jhotdraw.draw.tool.ConnectionTool.mouseDragged(), and org.jhotdraw.draw.tool.ConnectionTool.mousePressed().
startConnector
Connector org.jhotdraw.draw.tool.ConnectionTool.startConnector protected
The Connector at the start point of the connection.
Referenced by org.jhotdraw.draw.tool.ConnectionTool.canConnect(), org.jhotdraw.draw.tool.ConnectionTool.deactivate(), org.jhotdraw.draw.tool.ConnectionTool.mouseDragged(), org.jhotdraw.draw.tool.ConnectionTool.mousePressed(), and org.jhotdraw.draw.tool.ConnectionTool.mouseReleased().
targetFigure
Figure org.jhotdraw.draw.tool.ConnectionTool.targetFigure protected
The figure for which we enabled drawing of connectors.
Referenced by org.jhotdraw.draw.tool.ConnectionTool.deactivate(), org.jhotdraw.draw.tool.ConnectionTool.draw(), org.jhotdraw.draw.tool.ConnectionTool.mouseReleased(), and org.jhotdraw.draw.tool.ConnectionTool.repaintConnectors().
The documentation for this class was generated from the following file:
jhotdraw-core/src/main/java/org/jhotdraw/draw/tool/ConnectionTool.java