jhotdraw: org.jhotdraw.draw.AbstractConstrainer Class Reference
org.jhotdraw.draw.AbstractConstrainer Class Reference abstract
Public Member Functions
AbstractConstrainer ()
void addChangeListener (ChangeListener l)
void removeChangeListener (ChangeListener l)
AbstractConstrainer clone ()
Public Member Functions inherited from org.jhotdraw.draw.Constrainer
Point2D.Double constrainPoint (Point2D.Double p, Figure... figures)
Point2D.Double translatePoint (Point2D.Double p, TranslationDirection dir, Figure... figures)
Rectangle2D.Double constrainRectangle (Rectangle2D.Double r, Figure... figures)
Rectangle2D.Double translateRectangle (Rectangle2D.Double r, TranslationDirection dir, Figure... figures)
double constrainAngle (double angle, Figure... figures)
double rotateAngle (double angle, RotationDirection dir, Figure... figures)
void draw (Graphics2D g, DrawingView view)
Protected Member Functions
void fireStateChanged ()
Protected Attributes
EventListenerList listenerList = new EventListenerList()
transient ChangeEvent changeEvent = null
Detailed Description
This abstract class can be extended to implement a Constrainer.
Author
Werner Randelshofer
Version
$Id$
Constructor & Destructor Documentation
AbstractConstrainer()
org.jhotdraw.draw.AbstractConstrainer.AbstractConstrainer ()
Creates a new instance.
Referenced by org.jhotdraw.draw.AbstractConstrainer.clone().
Member Function Documentation
addChangeListener()
void org.jhotdraw.draw.AbstractConstrainer.addChangeListener (ChangeListener l)
Adds a ChangeListener.
Implements org.jhotdraw.draw.Constrainer.
References org.jhotdraw.draw.AbstractConstrainer.listenerList.
clone()
AbstractConstrainer org.jhotdraw.draw.AbstractConstrainer.clone ()
References org.jhotdraw.draw.AbstractConstrainer.AbstractConstrainer(), org.jhotdraw.draw.AbstractConstrainer.clone(), and org.jhotdraw.draw.AbstractConstrainer.listenerList.
Referenced by org.jhotdraw.draw.AbstractConstrainer.clone().
fireStateChanged()
void org.jhotdraw.draw.AbstractConstrainer.fireStateChanged () protected
Runs each ChangeListener's stateChanged method.
See also
EventListenerList
References org.jhotdraw.draw.AbstractConstrainer.changeEvent, and org.jhotdraw.draw.AbstractConstrainer.listenerList.
Referenced by org.jhotdraw.draw.GridConstrainer.setHeight(), org.jhotdraw.draw.GridConstrainer.setMajorGridSpacing(), org.jhotdraw.draw.GridConstrainer.setTheta(), org.jhotdraw.draw.GridConstrainer.setVisible(), and org.jhotdraw.draw.GridConstrainer.setWidth().
removeChangeListener()
void org.jhotdraw.draw.AbstractConstrainer.removeChangeListener (ChangeListener l)
Removes a ChangeListener.
Implements org.jhotdraw.draw.Constrainer.
References org.jhotdraw.draw.AbstractConstrainer.listenerList.
Member Data Documentation
changeEvent
transient ChangeEvent org.jhotdraw.draw.AbstractConstrainer.changeEvent = null protected
Only one ChangeEvent is needed per model instance since the event's only (read-only) state is the source property. The source of events generated here is always "this".
Referenced by org.jhotdraw.draw.AbstractConstrainer.fireStateChanged().
listenerList
EventListenerList org.jhotdraw.draw.AbstractConstrainer.listenerList = new EventListenerList() protected
The listeners waiting for model changes.
Referenced by org.jhotdraw.draw.AbstractConstrainer.addChangeListener(), org.jhotdraw.draw.AbstractConstrainer.clone(), org.jhotdraw.draw.AbstractConstrainer.fireStateChanged(), and org.jhotdraw.draw.AbstractConstrainer.removeChangeListener().
The documentation for this class was generated from the following file:
jhotdraw-core/src/main/java/org/jhotdraw/draw/AbstractConstrainer.java