jhotdraw: org.jhotdraw.draw.handle.BoundsOutlineHandle Class Reference
org.jhotdraw.draw.handle.BoundsOutlineHandle Class Reference
Public Member Functions
BoundsOutlineHandle (Figure owner)
BoundsOutlineHandle (Figure owner, boolean isTransformHandle, boolean isHoverHandle)
BoundsOutlineHandle (Figure owner, AttributeKey< Stroke > stroke1Enabled, AttributeKey< Color > strokeColor1Enabled, AttributeKey< Stroke > stroke2Enabled, AttributeKey< Color > strokeColor2Enabled, AttributeKey< Stroke > stroke1Disabled, AttributeKey< Color > strokeColor1Disabled, AttributeKey< Stroke > stroke2Disabled, AttributeKey< Color > strokeColor2Disabled)
boolean contains (Point p)
void trackStart (Point anchor, int modifiersEx)
void trackStep (Point anchor, Point lead, int modifiersEx)
void trackEnd (Point anchor, Point lead, int modifiersEx)
void draw (Graphics2D g)
Public Member Functions inherited from org.jhotdraw.draw.handle.AbstractHandle
AbstractHandle (Figure owner)
void addHandleListener (HandleListener l)
void removeHandleListener (HandleListener l)
Figure getOwner ()
void setView (DrawingView view)
DrawingView getView ()
DrawingEditor getEditor ()
void invalidate ()
void dispose ()
void areaInvalidated (FigureEvent evt)
void figureAdded (FigureEvent e)
void figureRemoved (FigureEvent e)
void figureRequestRemove (FigureEvent e)
void figureChanged (FigureEvent evt)
Cursor getCursor ()
boolean isCombinableWith (Handle handle)
void keyTyped (KeyEvent evt)
void keyReleased (KeyEvent evt)
void keyPressed (KeyEvent evt)
final Rectangle getBounds ()
Rectangle getDrawingArea ()
void trackDoubleClick (Point p, int modifiersEx)
void attributeChanged (FigureEvent e)
void viewTransformChanged ()
Collection< Handle > createSecondaryHandles ()
String getToolTipText (Point p)
void setToolTipText (String newValue)
void figureHandlesChanged (FigureEvent e)
Protected Member Functions
Rectangle basicGetBounds ()
Protected Member Functions inherited from org.jhotdraw.draw.handle.AbstractHandle
int getHandlesize ()
void fireAreaInvalidated (Rectangle invalidatedArea)
void fireUndoableEditHappened (UndoableEdit edit)
void fireHandleRequestRemove (Rectangle invalidatedArea)
void fireHandleRequestSecondaryHandles ()
void drawCircle (Graphics2D g, Color fill, Color stroke)
void drawRectangle (Graphics2D g, Color fill, Color stroke)
void drawDiamond (Graphics2D g, Color fill, Color stroke)
void updateBounds ()
Additional Inherited Members
Protected Attributes inherited from org.jhotdraw.draw.handle.AbstractHandle
DrawingView view
EventListenerList listenerList = new EventListenerList()
Detailed Description
A non-interactive Handle which draws the bounds of a Figure to make adjustments easier.
Author
Werner Randelshofer
Version
$Id$
Constructor & Destructor Documentation
BoundsOutlineHandle() [1/3]
org.jhotdraw.draw.handle.BoundsOutlineHandle.BoundsOutlineHandle (Figure owner)
Creates a bounds outline handle for resizing a component.
Parameters
owner
BoundsOutlineHandle() [2/3]
org.jhotdraw.draw.handle.BoundsOutlineHandle.BoundsOutlineHandle (Figure owner, boolean isTransformHandle, boolean isHoverHandle)
Creates a bounds outline handle for resizing or transforming a component.
Parameters
owner
References org.jhotdraw.draw.handle.HandleAttributeKeys.RESIZE_BOUNDS_COLOR_1, org.jhotdraw.draw.handle.HandleAttributeKeys.RESIZE_BOUNDS_COLOR_1_DISABLED, org.jhotdraw.draw.handle.HandleAttributeKeys.RESIZE_BOUNDS_COLOR_1_HOVER, org.jhotdraw.draw.handle.HandleAttributeKeys.RESIZE_BOUNDS_COLOR_2, org.jhotdraw.draw.handle.HandleAttributeKeys.RESIZE_BOUNDS_COLOR_2_DISABLED, org.jhotdraw.draw.handle.HandleAttributeKeys.RESIZE_BOUNDS_COLOR_2_HOVER, org.jhotdraw.draw.handle.HandleAttributeKeys.RESIZE_BOUNDS_STROKE_1, org.jhotdraw.draw.handle.HandleAttributeKeys.RESIZE_BOUNDS_STROKE_1_DISABLED, org.jhotdraw.draw.handle.HandleAttributeKeys.RESIZE_BOUNDS_STROKE_1_HOVER, org.jhotdraw.draw.handle.HandleAttributeKeys.RESIZE_BOUNDS_STROKE_2, org.jhotdraw.draw.handle.HandleAttributeKeys.RESIZE_BOUNDS_STROKE_2_DISABLED, org.jhotdraw.draw.handle.HandleAttributeKeys.RESIZE_BOUNDS_STROKE_2_HOVER, org.jhotdraw.draw.handle.HandleAttributeKeys.TRANSFORM_BOUNDS_COLOR_1, org.jhotdraw.draw.handle.HandleAttributeKeys.TRANSFORM_BOUNDS_COLOR_1_DISABLED, org.jhotdraw.draw.handle.HandleAttributeKeys.TRANSFORM_BOUNDS_COLOR_1_HOVER, org.jhotdraw.draw.handle.HandleAttributeKeys.TRANSFORM_BOUNDS_COLOR_2, org.jhotdraw.draw.handle.HandleAttributeKeys.TRANSFORM_BOUNDS_COLOR_2_DISABLED, org.jhotdraw.draw.handle.HandleAttributeKeys.TRANSFORM_BOUNDS_COLOR_2_HOVER, org.jhotdraw.draw.handle.HandleAttributeKeys.TRANSFORM_BOUNDS_STROKE_1, org.jhotdraw.draw.handle.HandleAttributeKeys.TRANSFORM_BOUNDS_STROKE_1_DISABLED, org.jhotdraw.draw.handle.HandleAttributeKeys.TRANSFORM_BOUNDS_STROKE_1_HOVER, org.jhotdraw.draw.handle.HandleAttributeKeys.TRANSFORM_BOUNDS_STROKE_2, org.jhotdraw.draw.handle.HandleAttributeKeys.TRANSFORM_BOUNDS_STROKE_2_DISABLED, and org.jhotdraw.draw.handle.HandleAttributeKeys.TRANSFORM_BOUNDS_STROKE_2_HOVER.
BoundsOutlineHandle() [3/3]
org.jhotdraw.draw.handle.BoundsOutlineHandle.BoundsOutlineHandle (Figure owner, AttributeKey< Stroke > stroke1Enabled, AttributeKey< Color > strokeColor1Enabled, AttributeKey< Stroke > stroke2Enabled, AttributeKey< Color > strokeColor2Enabled, AttributeKey< Stroke > stroke1Disabled, AttributeKey< Color > strokeColor1Disabled, AttributeKey< Stroke > stroke2Disabled, AttributeKey< Color > strokeColor2Disabled)
Creates a bounds outline handle for resizing or transforming a component.
Parameters
owner
Member Function Documentation
basicGetBounds()
Rectangle org.jhotdraw.draw.handle.BoundsOutlineHandle.basicGetBounds () protected
Reimplemented from org.jhotdraw.draw.handle.AbstractHandle.
References org.jhotdraw.draw.figure.Figure.get(), org.jhotdraw.draw.figure.Figure.getBounds(), org.jhotdraw.draw.DrawingView.getDrawingToViewTransform(), org.jhotdraw.draw.handle.AbstractHandle.getOwner(), and org.jhotdraw.draw.handle.AbstractHandle.view.
contains()
boolean org.jhotdraw.draw.handle.BoundsOutlineHandle.contains (Point p)
Tests if a point is contained in the handle.
Reimplemented from org.jhotdraw.draw.handle.AbstractHandle.
draw()
void org.jhotdraw.draw.handle.BoundsOutlineHandle.draw (Graphics2D g)
Draws this handle.
Reimplemented from org.jhotdraw.draw.handle.AbstractHandle.
References org.jhotdraw.draw.figure.Figure.get(), org.jhotdraw.draw.figure.Figure.getBounds(), org.jhotdraw.draw.DrawingView.getDrawingToViewTransform(), org.jhotdraw.draw.handle.AbstractHandle.getEditor(), org.jhotdraw.draw.DrawingEditor.getHandleAttribute(), org.jhotdraw.draw.handle.AbstractHandle.getOwner(), and org.jhotdraw.draw.handle.AbstractHandle.view.
trackEnd()
void org.jhotdraw.draw.handle.BoundsOutlineHandle.trackEnd (Point anchor, Point lead, int modifiersEx)
Tracks the end of the interaction.
Parameters
anchor the position where the interaction started
lead the current position
Implements org.jhotdraw.draw.handle.Handle.
trackStart()
void org.jhotdraw.draw.handle.BoundsOutlineHandle.trackStart (Point anchor, int modifiersEx)
Tracks the start of the interaction. The default implementation does nothing.
Parameters
anchor the position where the interaction started
Implements org.jhotdraw.draw.handle.Handle.
trackStep()
void org.jhotdraw.draw.handle.BoundsOutlineHandle.trackStep (Point anchor, Point lead, int modifiersEx)
Tracks a step of the interaction.
Parameters
anchor the position where the interaction started
lead the current position
Implements org.jhotdraw.draw.handle.Handle.
The documentation for this class was generated from the following file:
jhotdraw-core/src/main/java/org/jhotdraw/draw/handle/BoundsOutlineHandle.java