jhotdraw: org.jhotdraw.draw.DefaultDrawingViewTransferHandler Class Reference
org.jhotdraw.draw.DefaultDrawingViewTransferHandler Class Reference
Public Member Functions
DefaultDrawingViewTransferHandler ()
boolean importData (JComponent comp, Transferable t)
boolean importData (TransferSupport support)
int getSourceActions (JComponent c)
void exportAsDrag (JComponent comp, InputEvent e, int action)
Icon getVisualRepresentation (Transferable t)
boolean canImport (JComponent comp, DataFlavor[] transferFlavors)
Protected Member Functions
boolean importData (final JComponent comp, Transferable t, final HashSet< Figure > transferFigures, final Point dropPoint)
void moveToDropPoint (JComponent component, HashSet< Figure > transferFigures, Point dropPoint)
Transferable createTransferable (JComponent c)
Transferable createTransferable (DrawingView view, java.util.Set< Figure > transferFigures)
void exportDone (JComponent source, Transferable data, int action)
Detailed Description
Default TransferHandler for DrawingView objects.
Author
Werner Randelshofer
Version
$Id: DefaultDrawingViewTransferHandler.java 717 2010-11-21 12:30:57Z rawcoder $
Constructor & Destructor Documentation
DefaultDrawingViewTransferHandler()
org.jhotdraw.draw.DefaultDrawingViewTransferHandler.DefaultDrawingViewTransferHandler ()
Creates a new instance.
Member Function Documentation
canImport()
boolean org.jhotdraw.draw.DefaultDrawingViewTransferHandler.canImport (JComponent comp, DataFlavor[] transferFlavors)
References org.jhotdraw.draw.DrawingView.getDrawing(), and org.jhotdraw.draw.Drawing.getInputFormats().
createTransferable() [1/2]
Transferable org.jhotdraw.draw.DefaultDrawingViewTransferHandler.createTransferable (DrawingView view, java.util.Set< Figure > transferFigures) protected
References org.jhotdraw.draw.DrawingView.getDrawing(), org.jhotdraw.draw.Drawing.getOutputFormats(), org.jhotdraw.draw.DrawingView.getScaleFactor(), and org.jhotdraw.draw.Drawing.sort().
createTransferable() [2/2]
Transferable org.jhotdraw.draw.DefaultDrawingViewTransferHandler.createTransferable (JComponent c) protected
References org.jhotdraw.draw.DrawingView.getSelectedFigures().
Referenced by org.jhotdraw.draw.DefaultDrawingViewTransferHandler.exportAsDrag().
exportAsDrag()
void org.jhotdraw.draw.DefaultDrawingViewTransferHandler.exportAsDrag (JComponent comp, InputEvent e, int action)
References org.jhotdraw.draw.DefaultDrawingViewTransferHandler.createTransferable(), org.jhotdraw.draw.DrawingView.drawingToView(), org.jhotdraw.draw.DrawingView.findFigure(), org.jhotdraw.draw.figure.Figure.getDrawingArea(), org.jhotdraw.draw.DrawingView.getSelectedFigures(), and org.jhotdraw.draw.DefaultDrawingViewTransferHandler.getSourceActions().
exportDone()
void org.jhotdraw.draw.DefaultDrawingViewTransferHandler.exportDone (JComponent source, Transferable data, int action) protected
References org.jhotdraw.draw.Drawing.add(), org.jhotdraw.draw.figure.CompositeFigure.addCompositeFigureListener(), org.jhotdraw.draw.DrawingView.addToSelection(), org.jhotdraw.draw.DrawingView.clearSelection(), org.jhotdraw.draw.Drawing.fireUndoableEditHappened(), org.jhotdraw.draw.DrawingView.getDrawing(), org.jhotdraw.draw.Drawing.remove(), org.jhotdraw.draw.Drawing.removeAll(), and org.jhotdraw.draw.figure.CompositeFigure.removeCompositeFigureListener().
getSourceActions()
int org.jhotdraw.draw.DefaultDrawingViewTransferHandler.getSourceActions (JComponent c)
References org.jhotdraw.draw.DrawingView.getDrawing(), org.jhotdraw.draw.Drawing.getOutputFormats(), and org.jhotdraw.draw.DrawingView.getSelectionCount().
Referenced by org.jhotdraw.draw.DefaultDrawingViewTransferHandler.exportAsDrag().
getVisualRepresentation()
Icon org.jhotdraw.draw.DefaultDrawingViewTransferHandler.getVisualRepresentation (Transferable t)
importData() [1/3]
boolean org.jhotdraw.draw.DefaultDrawingViewTransferHandler.importData (final JComponent comp, Transferable t, final HashSet< Figure > transferFigures, final Point dropPoint) protected
Imports data and stores the transferred figures into the supplied transferFigures collection.
References org.jhotdraw.draw.Drawing.addAll(), org.jhotdraw.draw.DrawingView.addToSelection(), org.jhotdraw.draw.DrawingView.clearSelection(), org.jhotdraw.draw.Drawing.fireUndoableEditHappened(), org.jhotdraw.draw.figure.CompositeFigure.getChildren(), org.jhotdraw.draw.DrawingView.getDrawing(), org.jhotdraw.draw.DrawingView.getEditor(), org.jhotdraw.draw.Drawing.getInputFormats(), org.jhotdraw.draw.DefaultDrawingViewTransferHandler.moveToDropPoint(), org.jhotdraw.draw.Drawing.removeAll(), and org.jhotdraw.draw.DrawingEditor.setEnabled().
importData() [2/3]
boolean org.jhotdraw.draw.DefaultDrawingViewTransferHandler.importData (JComponent comp, Transferable t)
Referenced by org.jhotdraw.draw.DefaultDrawingViewTransferHandler.importData().
importData() [3/3]
boolean org.jhotdraw.draw.DefaultDrawingViewTransferHandler.importData (TransferSupport support)
References org.jhotdraw.draw.DefaultDrawingViewTransferHandler.importData().
moveToDropPoint()
void org.jhotdraw.draw.DefaultDrawingViewTransferHandler.moveToDropPoint (JComponent component, HashSet< Figure > transferFigures, Point dropPoint) protected
References org.jhotdraw.draw.DrawingView.viewToDrawing().
Referenced by org.jhotdraw.draw.DefaultDrawingViewTransferHandler.importData().
The documentation for this class was generated from the following file:
jhotdraw-core/src/main/java/org/jhotdraw/draw/DefaultDrawingViewTransferHandler.java