jhotdraw: org.jhotdraw.draw.text.FloatingTextArea Class Reference
org.jhotdraw.draw.text.FloatingTextArea Class Reference
Public Member Functions
FloatingTextArea ()
void createOverlay (DrawingView view)
void requestFocus ()
void createOverlay (DrawingView view, TextHolderFigure figure)
void setBounds (Rectangle2D.Double r, String text)
String getText ()
Dimension getPreferredSize (int cols)
void endOverlay ()
Protected Member Functions
void updateWidget ()
Protected Attributes
JScrollPane editScrollContainer
JTextArea textArea
DrawingView view
Detailed Description
A floating text area that is used to edit a TextHolderFigure.
Design Patterns
Framework
The text creation and editing tools and the
TextHolderFigure
interface define together the contracts of a smaller framework inside of the JHotDraw framework for structured drawing editors.
Contract: TextHolderFigure, org.jhotdraw.draw.tool.TextCreationTool, org.jhotdraw.draw.tool.TextAreaCreationTool, org.jhotdraw.draw.tool.TextEditingTool, org.jhotdraw.draw.tool.TextAreaEditingTool, FloatingTextField, FloatingTextArea.
Author
Werner Randelshofer
Version
Id
FloatingTextArea.java -1
Constructor & Destructor Documentation
FloatingTextArea()
org.jhotdraw.draw.text.FloatingTextArea.FloatingTextArea ()
Constructor for the FloatingTextArea object
References org.jhotdraw.draw.text.FloatingTextArea.editScrollContainer, and org.jhotdraw.draw.text.FloatingTextArea.textArea.
Member Function Documentation
createOverlay() [1/2]
void org.jhotdraw.draw.text.FloatingTextArea.createOverlay (DrawingView view)
Creates the overlay within the given container.
Parameters
view the DrawingView
References org.jhotdraw.draw.text.FloatingTextArea.view.
Referenced by org.jhotdraw.draw.tool.TextAreaCreationTool.beginEdit(), and org.jhotdraw.draw.tool.TextAreaEditingTool.beginEdit().
createOverlay() [2/2]
void org.jhotdraw.draw.text.FloatingTextArea.createOverlay (DrawingView view, TextHolderFigure figure)
Creates the overlay for the given Container using a specific font.
Parameters
view the DrawingView
figure the figure holding the text
References org.jhotdraw.draw.figure.Figure.addFigureListener(), org.jhotdraw.draw.text.FloatingTextArea.editScrollContainer, org.jhotdraw.draw.DrawingView.getComponent(), org.jhotdraw.draw.text.FloatingTextArea.updateWidget(), and org.jhotdraw.draw.text.FloatingTextArea.view.
endOverlay()
void org.jhotdraw.draw.text.FloatingTextArea.endOverlay ()
Removes the overlay.
References org.jhotdraw.draw.text.FloatingTextArea.editScrollContainer, org.jhotdraw.draw.DrawingView.getComponent(), org.jhotdraw.draw.figure.Figure.removeFigureListener(), and org.jhotdraw.draw.text.FloatingTextArea.view.
Referenced by org.jhotdraw.draw.tool.TextAreaCreationTool.endEdit(), and org.jhotdraw.draw.tool.TextAreaEditingTool.endEdit().
getPreferredSize()
Dimension org.jhotdraw.draw.text.FloatingTextArea.getPreferredSize (int cols)
Gets the preferred size of the overlay.
Parameters
cols Description of the Parameter
Returns
The preferredSize value
References org.jhotdraw.draw.text.FloatingTextArea.textArea.
getText()
String org.jhotdraw.draw.text.FloatingTextArea.getText ()
Gets the text contents of the overlay.
Returns
The text value
References org.jhotdraw.draw.text.FloatingTextArea.textArea.
Referenced by org.jhotdraw.draw.tool.TextAreaCreationTool.endEdit(), and org.jhotdraw.draw.tool.TextAreaEditingTool.endEdit().
requestFocus()
void org.jhotdraw.draw.text.FloatingTextArea.requestFocus ()
References org.jhotdraw.draw.text.FloatingTextArea.textArea.
Referenced by org.jhotdraw.draw.tool.TextAreaCreationTool.beginEdit(), and org.jhotdraw.draw.tool.TextAreaEditingTool.beginEdit().
setBounds()
void org.jhotdraw.draw.text.FloatingTextArea.setBounds (Rectangle2D.Double r, String text)
Positions and sizes the overlay.
Parameters
r the bounding Rectangle2D.Double for the overlay
text the text to edit
References org.jhotdraw.draw.DrawingView.drawingToView(), org.jhotdraw.draw.text.FloatingTextArea.editScrollContainer, org.jhotdraw.draw.text.FloatingTextArea.textArea, and org.jhotdraw.draw.text.FloatingTextArea.view.
Referenced by org.jhotdraw.draw.tool.TextAreaCreationTool.beginEdit(), and org.jhotdraw.draw.tool.TextAreaEditingTool.beginEdit().
updateWidget()
void org.jhotdraw.draw.text.FloatingTextArea.updateWidget () protected
References org.jhotdraw.draw.figure.TextHolderFigure.getFillColor(), org.jhotdraw.draw.figure.TextHolderFigure.getFont(), org.jhotdraw.draw.figure.TextHolderFigure.getFontSize(), org.jhotdraw.draw.DrawingView.getScaleFactor(), org.jhotdraw.draw.figure.TextHolderFigure.getTextColor(), org.jhotdraw.draw.text.FloatingTextArea.textArea, and org.jhotdraw.draw.text.FloatingTextArea.view.
Referenced by org.jhotdraw.draw.text.FloatingTextArea.createOverlay().
Member Data Documentation
editScrollContainer
JScrollPane org.jhotdraw.draw.text.FloatingTextArea.editScrollContainer protected
A scroll pane to allow for vertical scrolling while editing
Referenced by org.jhotdraw.draw.text.FloatingTextArea.createOverlay(), org.jhotdraw.draw.text.FloatingTextArea.endOverlay(), org.jhotdraw.draw.text.FloatingTextArea.FloatingTextArea(), and org.jhotdraw.draw.text.FloatingTextArea.setBounds().
textArea
JTextArea org.jhotdraw.draw.text.FloatingTextArea.textArea protected
The actual editor
Referenced by org.jhotdraw.draw.text.FloatingTextArea.FloatingTextArea(), org.jhotdraw.draw.text.FloatingTextArea.getPreferredSize(), org.jhotdraw.draw.text.FloatingTextArea.getText(), org.jhotdraw.draw.text.FloatingTextArea.requestFocus(), org.jhotdraw.draw.text.FloatingTextArea.setBounds(), and org.jhotdraw.draw.text.FloatingTextArea.updateWidget().
view
DrawingView org.jhotdraw.draw.text.FloatingTextArea.view protected
The drawing view.
Referenced by org.jhotdraw.draw.text.FloatingTextArea.createOverlay(), org.jhotdraw.draw.text.FloatingTextArea.endOverlay(), org.jhotdraw.draw.text.FloatingTextArea.setBounds(), and org.jhotdraw.draw.text.FloatingTextArea.updateWidget().
The documentation for this class was generated from the following file:
jhotdraw-core/src/main/java/org/jhotdraw/draw/text/FloatingTextArea.java