jhotdraw: org.jhotdraw.draw.action.SelectionColorChooserHandler Class Reference
org.jhotdraw.draw.action.SelectionColorChooserHandler Class Reference
Public Member Functions
SelectionColorChooserHandler (DrawingEditor editor, AttributeKey< Color > key, JColorChooser colorChooser, JPopupMenu popupMenu)
void actionPerformed (java.awt.event.ActionEvent evt)
void stateChanged (ChangeEvent e)
Public Member Functions inherited from org.jhotdraw.draw.action.AbstractSelectedAction
AbstractSelectedAction (DrawingEditor editor)
void dispose ()
void setEditor (DrawingEditor editor)
DrawingEditor getEditor ()
void setUpdateEnabledState (boolean newValue)
boolean isUpdatEnabledState ()
Protected Member Functions
void applySelectedColorToFigures ()
void updateEnabledState ()
Protected Member Functions inherited from org.jhotdraw.draw.action.AbstractSelectedAction
DrawingView getView ()
Drawing getDrawing ()
void fireUndoableEditHappened (UndoableEdit edit)
Protected Attributes
AttributeKey< Color > key
JColorChooser colorChooser
JPopupMenu popupMenu
int isUpdating
Detailed Description
SelectionColorChooserHandler.
Author
Werner Randelshofer
Version
$Id$
Constructor & Destructor Documentation
SelectionColorChooserHandler()
org.jhotdraw.draw.action.SelectionColorChooserHandler.SelectionColorChooserHandler (DrawingEditor editor, AttributeKey< Color > key, JColorChooser colorChooser, JPopupMenu popupMenu)
Creates a new instance.
References org.jhotdraw.draw.action.SelectionColorChooserHandler.colorChooser, org.jhotdraw.draw.action.SelectionColorChooserHandler.key, org.jhotdraw.draw.action.SelectionColorChooserHandler.popupMenu, and org.jhotdraw.draw.action.SelectionColorChooserHandler.updateEnabledState().
Member Function Documentation
actionPerformed()
void org.jhotdraw.draw.action.SelectionColorChooserHandler.actionPerformed (java.awt.event.ActionEvent evt)
References org.jhotdraw.draw.action.SelectionColorChooserHandler.popupMenu.
applySelectedColorToFigures()
void org.jhotdraw.draw.action.SelectionColorChooserHandler.applySelectedColorToFigures () protected
References org.jhotdraw.draw.action.SelectionColorChooserHandler.colorChooser, org.jhotdraw.draw.action.AbstractSelectedAction.fireUndoableEditHappened(), org.jhotdraw.draw.AttributeKeys.FONT_FACE, org.jhotdraw.draw.action.AbstractSelectedAction.getEditor(), org.jhotdraw.draw.AttributeKey< T >.getPresentationName(), org.jhotdraw.draw.action.AbstractSelectedAction.getView(), org.jhotdraw.draw.action.SelectionColorChooserHandler.key, and org.jhotdraw.draw.DrawingEditor.setDefaultAttribute().
Referenced by org.jhotdraw.draw.action.SelectionColorChooserHandler.stateChanged().
stateChanged()
void org.jhotdraw.draw.action.SelectionColorChooserHandler.stateChanged (ChangeEvent e)
References org.jhotdraw.draw.action.SelectionColorChooserHandler.applySelectedColorToFigures(), and org.jhotdraw.draw.action.SelectionColorChooserHandler.isUpdating.
updateEnabledState()
void org.jhotdraw.draw.action.SelectionColorChooserHandler.updateEnabledState () protected
Updates the enabled state of this action to reflect the enabled state of the active
DrawingView
. If no drawing view is active, this action is disabled.
Reimplemented from org.jhotdraw.draw.action.AbstractSelectedAction.
References org.jhotdraw.draw.action.SelectionColorChooserHandler.colorChooser, org.jhotdraw.draw.action.AbstractSelectedAction.getEditor(), org.jhotdraw.draw.action.AbstractSelectedAction.getView(), org.jhotdraw.draw.action.SelectionColorChooserHandler.isUpdating, org.jhotdraw.draw.action.SelectionColorChooserHandler.key, and org.jhotdraw.draw.action.SelectionColorChooserHandler.popupMenu.
Referenced by org.jhotdraw.draw.action.SelectionColorChooserHandler.SelectionColorChooserHandler().
Member Data Documentation
colorChooser
JColorChooser org.jhotdraw.draw.action.SelectionColorChooserHandler.colorChooser protected
Referenced by org.jhotdraw.draw.action.SelectionColorChooserHandler.applySelectedColorToFigures(), org.jhotdraw.draw.action.SelectionColorChooserHandler.SelectionColorChooserHandler(), and org.jhotdraw.draw.action.SelectionColorChooserHandler.updateEnabledState().
isUpdating
int org.jhotdraw.draw.action.SelectionColorChooserHandler.isUpdating protected
Referenced by org.jhotdraw.draw.action.SelectionColorChooserHandler.stateChanged(), and org.jhotdraw.draw.action.SelectionColorChooserHandler.updateEnabledState().
key
AttributeKey<Color> org.jhotdraw.draw.action.SelectionColorChooserHandler.key protected
Referenced by org.jhotdraw.draw.action.SelectionColorChooserHandler.applySelectedColorToFigures(), org.jhotdraw.draw.action.SelectionColorChooserHandler.SelectionColorChooserHandler(), and org.jhotdraw.draw.action.SelectionColorChooserHandler.updateEnabledState().
popupMenu
JPopupMenu org.jhotdraw.draw.action.SelectionColorChooserHandler.popupMenu protected
Referenced by org.jhotdraw.draw.action.SelectionColorChooserHandler.actionPerformed(), org.jhotdraw.draw.action.SelectionColorChooserHandler.SelectionColorChooserHandler(), and org.jhotdraw.draw.action.SelectionColorChooserHandler.updateEnabledState().
The documentation for this class was generated from the following file:
jhotdraw-core/src/main/java/org/jhotdraw/draw/action/SelectionColorChooserHandler.java