jhotdraw: org.jhotdraw.draw.DrawingEditorProxy Class Reference
org.jhotdraw.draw.DrawingEditorProxy Class Reference
Public Member Functions
DrawingEditorProxy ()
void setTarget (DrawingEditor newValue)
DrawingEditor getTarget ()
void add (DrawingView view)
void remove (DrawingView view)
Collection< DrawingView > getDrawingViews ()
DrawingView getActiveView ()
void setActiveView (DrawingView newValue)
DrawingView getFocusedView ()
void setTool (Tool t)
Tool getTool ()
void setCursor (Cursor c)
DrawingView findView (Container c)
void applyDefaultAttributesTo (Figure f)
Map< AttributeKey<?>, Object > getDefaultAttributes ()
void setEnabled (boolean newValue)
boolean isEnabled ()
void setInputMap (InputMap newValue)
InputMap getInputMap ()
void setActionMap (ActionMap newValue)
ActionMap getActionMap ()
Public Member Functions inherited from org.jhotdraw.draw.DrawingEditor
void addPropertyChangeListener (PropertyChangeListener listener)
void removePropertyChangeListener (PropertyChangeListener listener)
Additional Inherited Members
Static Public Attributes inherited from org.jhotdraw.draw.DrawingEditor
static final String ACTIVE_VIEW_PROPERTY = "activeView"
static final String TOOL_PROPERTY = "tool"
static final String INPUT_MAP_PROPERTY = "inputMap"
static final String ACTION_MAP_PROPERTY = "actionMap"
static final String DEFAULT_ATTRIBUTE_PROPERTY_PREFIX = "defaultAttribute."
Detailed Description
DrawingEditorProxy.
Design Patterns
Proxy
To remove the need for null-handling,
AbstractTool
makes use of a proxy for
DrawingEditor
. Subject: DrawingEditor; Proxy: DrawingEditorProxy; Client: org.jhotdraw.draw.tool.AbstractTool.
Author
Werner Randelshofer
Version
$Id$
Constructor & Destructor Documentation
DrawingEditorProxy()
org.jhotdraw.draw.DrawingEditorProxy.DrawingEditorProxy ()
Creates a new instance.
Member Function Documentation
add()
void org.jhotdraw.draw.DrawingEditorProxy.add (DrawingView view)
Gets the editor's current drawing. / Drawing getDrawing(); /** Sets the editor's current drawing. / void setDrawing(Drawing drawing); Adds a drawing view to the editor. The editor invokes addNotify on the view, and it registers its tool as an event listener on the view.
Implements org.jhotdraw.draw.DrawingEditor.
References org.jhotdraw.draw.DrawingEditor.add().
applyDefaultAttributesTo()
void org.jhotdraw.draw.DrawingEditorProxy.applyDefaultAttributesTo (Figure f)
Applies the default attributes to the specified figure.
Implements org.jhotdraw.draw.DrawingEditor.
References org.jhotdraw.draw.DrawingEditor.applyDefaultAttributesTo().
findView()
DrawingView org.jhotdraw.draw.DrawingEditorProxy.findView (Container c)
Finds a drawing view. This is used by Tool to identify the view of which it has received an event.
Implements org.jhotdraw.draw.DrawingEditor.
References org.jhotdraw.draw.DrawingEditor.findView().
getActionMap()
ActionMap org.jhotdraw.draw.DrawingEditorProxy.getActionMap ()
Gets the action map used by the tool of this drawing editor as a fall back for performing actions.
Tool
s use the action map of the drawing editor to determine what to do when an action needs to be invoked from the InputMap of the drawing editor.
This is a bound property.
Implements org.jhotdraw.draw.DrawingEditor.
References org.jhotdraw.draw.DrawingEditor.getActionMap().
getActiveView()
DrawingView org.jhotdraw.draw.DrawingEditorProxy.getActiveView ()
Gets the editor's active drawing view. This can be null, if the editor has no views.
Implements org.jhotdraw.draw.DrawingEditor.
References org.jhotdraw.draw.DrawingEditor.getActiveView().
getDefaultAttributes()
Map<AttributeKey<?>, Object> org.jhotdraw.draw.DrawingEditorProxy.getDefaultAttributes ()
Returns an immutable Map with the default attributes of this editor.
Implements org.jhotdraw.draw.DrawingEditor.
References org.jhotdraw.draw.DrawingEditor.getDefaultAttributes().
getDrawingViews()
Collection<DrawingView> org.jhotdraw.draw.DrawingEditorProxy.getDrawingViews ()
Gets all drawing views associated with this editor.
Implements org.jhotdraw.draw.DrawingEditor.
References org.jhotdraw.draw.DrawingEditor.getDrawingViews().
getFocusedView()
DrawingView org.jhotdraw.draw.DrawingEditorProxy.getFocusedView ()
References org.jhotdraw.draw.DrawingEditor.getActiveView().
getInputMap()
InputMap org.jhotdraw.draw.DrawingEditorProxy.getInputMap ()
Sets the input map used by the tool of this drawing editor as a fall back for handling keyboard events.
Tool
s use the input map of the drawing editor to determine what to do when a key was pressed that the tool can not handle.
This is a bound property.
Implements org.jhotdraw.draw.DrawingEditor.
References org.jhotdraw.draw.DrawingEditor.getInputMap().
getTarget()
DrawingEditor org.jhotdraw.draw.DrawingEditorProxy.getTarget ()
Gets the target of the proxy.
getTool()
Tool org.jhotdraw.draw.DrawingEditorProxy.getTool ()
Gets the current tool.
This is a bound property.
Implements org.jhotdraw.draw.DrawingEditor.
References org.jhotdraw.draw.DrawingEditor.getTool().
isEnabled()
boolean org.jhotdraw.draw.DrawingEditorProxy.isEnabled ()
Gets the enabled state of the drawing editor.
Implements org.jhotdraw.draw.DrawingEditor.
References org.jhotdraw.draw.DrawingEditor.isEnabled().
remove()
void org.jhotdraw.draw.DrawingEditorProxy.remove (DrawingView view)
Removes a drawing view from the editor. The editor invokes removeNotify on the view, and it unregisters its tool on the view.
Implements org.jhotdraw.draw.DrawingEditor.
References org.jhotdraw.draw.DrawingEditor.remove().
setActionMap()
void org.jhotdraw.draw.DrawingEditorProxy.setActionMap (ActionMap newValue)
Sets the action map used by the tool of this drawing editor as a fall back for performing actions.
This is a bound property.
Implements org.jhotdraw.draw.DrawingEditor.
References org.jhotdraw.draw.DrawingEditor.setActionMap().
setActiveView()
void org.jhotdraw.draw.DrawingEditorProxy.setActiveView (DrawingView newValue)
Sets the editor's active drawing view. This can be set to null, if the editor has no views.
Implements org.jhotdraw.draw.DrawingEditor.
References org.jhotdraw.draw.DrawingEditor.setActiveView().
setCursor()
void org.jhotdraw.draw.DrawingEditorProxy.setCursor (Cursor c)
Sets the cursor on the view(s) of the drawing editor.
Implements org.jhotdraw.draw.DrawingEditor.
References org.jhotdraw.draw.DrawingEditor.setCursor().
setEnabled()
void org.jhotdraw.draw.DrawingEditorProxy.setEnabled (boolean newValue)
Sets the enabled state of the drawing editor. This is a bound property.
Implements org.jhotdraw.draw.DrawingEditor.
References org.jhotdraw.draw.DrawingEditor.setEnabled().
setInputMap()
void org.jhotdraw.draw.DrawingEditorProxy.setInputMap (InputMap newValue)
Sets the input map used by the tool of this drawing editor as a fall back for handling keyboard events.
This is a bound property.
Implements org.jhotdraw.draw.DrawingEditor.
References org.jhotdraw.draw.DrawingEditor.setInputMap().
setTarget()
void org.jhotdraw.draw.DrawingEditorProxy.setTarget (DrawingEditor newValue)
Sets the target of the proxy.
References org.jhotdraw.draw.DrawingEditor.addPropertyChangeListener(), and org.jhotdraw.draw.DrawingEditor.removePropertyChangeListener().
Referenced by org.jhotdraw.draw.tool.AbstractTool.activate(), and org.jhotdraw.draw.tool.AbstractTool.deactivate().
setTool()
void org.jhotdraw.draw.DrawingEditorProxy.setTool (Tool t)
Calls deactivate on the previously active tool of this drawing editor. Calls activate on the provided tool. Forwards all mouse, mouse moation and keyboard events that occur on the DrawingView to the provided tool.
This is a bound property.
Implements org.jhotdraw.draw.DrawingEditor.
References org.jhotdraw.draw.DrawingEditor.setTool().
The documentation for this class was generated from the following file:
jhotdraw-core/src/main/java/org/jhotdraw/draw/DrawingEditorProxy.java