jhotdraw: org.jhotdraw.draw.action.AbstractDrawingViewAction Class Reference
org.jhotdraw.draw.action.AbstractDrawingViewAction Class Reference abstract
Public Member Functions
AbstractDrawingViewAction (DrawingEditor editor)
AbstractDrawingViewAction (DrawingView view)
void dispose ()
void setUpdateEnabledState (boolean newValue)
boolean isUpdatEnabledState ()
Protected Member Functions
void setEditor (DrawingEditor newValue)
DrawingEditor getEditor ()
DrawingView getView ()
Drawing getDrawing ()
void fireUndoableEditHappened (UndoableEdit edit)
void updateEnabledState ()
void updateViewState ()
Detailed Description
This abstract class can be extended to implement an
Action
that acts on behalf of a org.jhotdraw.draw.DrawingView.
By default the enabled state of this action reflects the enabled state of the
DrawingView
. If no drawing view is active, this action is disabled. When many actions listen to the enabled state this can considerably slow down the editor. If updating the enabled state is not necessary, you can disable it using setUpdateEnabledState.
If the
AbstractDrawingEditorAction
acts on the currently active
DrawingView
it listens for property changes in the
DrawingEditor
. It listens using a WeakPropertyChangeListener on the
DrawingEditor
and thus may become garbage collected if it is not referenced by any other object.
Author
Werner Randelshofer
Version
$Id$
Constructor & Destructor Documentation
AbstractDrawingViewAction() [1/2]
org.jhotdraw.draw.action.AbstractDrawingViewAction.AbstractDrawingViewAction (DrawingEditor editor)
Creates a view action which acts on the current view of the editor.
References org.jhotdraw.draw.action.AbstractDrawingViewAction.setEditor().
AbstractDrawingViewAction() [2/2]
org.jhotdraw.draw.action.AbstractDrawingViewAction.AbstractDrawingViewAction (DrawingView view)
Creates a view action which acts on the specified view.
Member Function Documentation
dispose()
void org.jhotdraw.draw.action.AbstractDrawingViewAction.dispose ()
Frees all resources held by this object, so that it can be garbage collected.
References org.jhotdraw.draw.action.AbstractDrawingViewAction.setEditor().
fireUndoableEditHappened()
void org.jhotdraw.draw.action.AbstractDrawingViewAction.fireUndoableEditHappened (UndoableEdit edit) protected
References org.jhotdraw.draw.Drawing.fireUndoableEditHappened(), and org.jhotdraw.draw.action.AbstractDrawingViewAction.getDrawing().
Referenced by org.jhotdraw.draw.action.DrawingAttributeAction.actionPerformed(), and org.jhotdraw.draw.action.DrawingColorChooserHandler.applySelectedColorToFigures().
getDrawing()
Drawing org.jhotdraw.draw.action.AbstractDrawingViewAction.getDrawing () protected
References org.jhotdraw.draw.DrawingView.getDrawing(), and org.jhotdraw.draw.action.AbstractDrawingViewAction.getView().
Referenced by org.jhotdraw.draw.action.AbstractDrawingViewAction.fireUndoableEditHappened().
getEditor()
DrawingEditor org.jhotdraw.draw.action.AbstractDrawingViewAction.getEditor () protected
Referenced by org.jhotdraw.draw.action.DrawingColorChooserHandler.applySelectedColorToFigures(), and org.jhotdraw.draw.action.DrawingColorChooserHandler.updateEnabledState().
getView()
DrawingView org.jhotdraw.draw.action.AbstractDrawingViewAction.getView () protected
References org.jhotdraw.draw.DrawingEditor.getActiveView().
Referenced by org.jhotdraw.draw.action.ToggleGridAction.actionPerformed(), org.jhotdraw.draw.action.ZoomAction.actionPerformed(), org.jhotdraw.draw.action.DrawingAttributeAction.actionPerformed(), org.jhotdraw.draw.action.DrawingColorChooserHandler.applySelectedColorToFigures(), org.jhotdraw.draw.action.AbstractDrawingViewAction.getDrawing(), org.jhotdraw.draw.action.AbstractDrawingViewAction.updateEnabledState(), org.jhotdraw.draw.action.DrawingColorChooserHandler.updateEnabledState(), and org.jhotdraw.draw.action.ToggleGridAction.updateViewState().
isUpdatEnabledState()
boolean org.jhotdraw.draw.action.AbstractDrawingViewAction.isUpdatEnabledState ()
Returns true, if this action automatically updates its enabled state to reflect the enabled state of the active
DrawingView
.
setEditor()
void org.jhotdraw.draw.action.AbstractDrawingViewAction.setEditor (DrawingEditor newValue) protected
References org.jhotdraw.draw.action.AbstractDrawingViewAction.updateEnabledState().
Referenced by org.jhotdraw.draw.action.AbstractDrawingViewAction.AbstractDrawingViewAction(), org.jhotdraw.draw.action.AbstractDrawingViewAction.dispose(), and org.jhotdraw.draw.action.ZoomAction.ZoomAction().
setUpdateEnabledState()
void org.jhotdraw.draw.action.AbstractDrawingViewAction.setUpdateEnabledState (boolean newValue)
By default, the enabled state of this action is updated to reflect the enabled state of the active
DrawingView
. Since this is not always necessary, and since many listening actions may considerably slow down the drawing editor, you can switch this behavior off here.
Parameters
newValue Specify false to prevent automatic updating of the enabled state.
References org.jhotdraw.draw.action.AbstractDrawingViewAction.updateEnabledState().
updateEnabledState()
void org.jhotdraw.draw.action.AbstractDrawingViewAction.updateEnabledState () protected
Updates the enabled state of this action to reflect the enabled state of the active
DrawingView
. If no drawing view is active, this action is disabled.
Reimplemented in org.jhotdraw.draw.action.DrawingColorChooserHandler.
References org.jhotdraw.draw.action.AbstractDrawingViewAction.getView().
Referenced by org.jhotdraw.draw.action.DrawingAttributeAction.DrawingAttributeAction(), org.jhotdraw.draw.action.AbstractDrawingViewAction.setEditor(), and org.jhotdraw.draw.action.AbstractDrawingViewAction.setUpdateEnabledState().
updateViewState()
void org.jhotdraw.draw.action.AbstractDrawingViewAction.updateViewState () protected
This method is called when the active drawing view of the drawing editor changed. The implementation in this class does nothing.
Reimplemented in org.jhotdraw.draw.action.ToggleGridAction.
The documentation for this class was generated from the following file:
jhotdraw-core/src/main/java/org/jhotdraw/draw/action/AbstractDrawingViewAction.java