jhotdraw: org.jhotdraw.draw.connector.LocatorConnector Class Reference
org.jhotdraw.draw.connector.LocatorConnector Class Reference
Public Member Functions
LocatorConnector ()
LocatorConnector (Figure owner, Locator l)
Locator getLocator ()
boolean contains (Point2D.Double p)
Rectangle2D.Double getBounds ()
void read (DOMInput in) throws IOException
void write (DOMOutput out) throws IOException
Public Member Functions inherited from org.jhotdraw.draw.connector.AbstractConnector
AbstractConnector ()
AbstractConnector (Figure owner)
void setConnectToDecorator (boolean newValue)
boolean isConnectToDecorator ()
Point2D.Double findStart (ConnectionFigure connection)
Point2D.Double findEnd (ConnectionFigure connection)
Figure getOwner ()
Object clone ()
void updateStartLocation (Point2D.Double p)
void updateEndLocation (Point2D.Double p)
Point2D.Double getAnchor ()
void updateAnchor (Point2D.Double p)
Rectangle2D.Double getDrawingArea ()
void draw (Graphics2D g)
Static Public Attributes
static final int SIZE = 2
Protected Member Functions
Point2D.Double locate (ConnectionFigure connection)
Protected Member Functions inherited from org.jhotdraw.draw.connector.AbstractConnector
final Figure getConnectorTarget (Figure f)
Point2D.Double findPoint (ConnectionFigure connection)
void setOwner (Figure newValue)
Detailed Description
A LocatorConnector locates connection points with the help of a Locator. It supports the definition of connection points to semantic locations.
See also
Locator
Connector
Author
Werner Randelshofer
Version
$Id$
Constructor & Destructor Documentation
LocatorConnector() [1/2]
org.jhotdraw.draw.connector.LocatorConnector.LocatorConnector ()
Creates a new instance. Only used for DOMStorable.
LocatorConnector() [2/2]
org.jhotdraw.draw.connector.LocatorConnector.LocatorConnector (Figure owner, Locator l)
Member Function Documentation
contains()
boolean org.jhotdraw.draw.connector.LocatorConnector.contains (Point2D.Double p)
Tests if a point is contained in the connector.
Reimplemented from org.jhotdraw.draw.connector.AbstractConnector.
References org.jhotdraw.draw.connector.LocatorConnector.getBounds().
getBounds()
Rectangle2D.Double org.jhotdraw.draw.connector.LocatorConnector.getBounds ()
Gets the display box of the connector.
Reimplemented from org.jhotdraw.draw.connector.AbstractConnector.
References org.jhotdraw.draw.connector.AbstractConnector.getOwner(), org.jhotdraw.draw.locator.Locator.locate(), and org.jhotdraw.draw.connector.LocatorConnector.SIZE.
Referenced by org.jhotdraw.draw.connector.LocatorConnector.contains().
getLocator()
Locator org.jhotdraw.draw.connector.LocatorConnector.getLocator ()
locate()
Point2D.Double org.jhotdraw.draw.connector.LocatorConnector.locate (ConnectionFigure connection) protected
References org.jhotdraw.draw.connector.AbstractConnector.getOwner(), and org.jhotdraw.draw.locator.Locator.locate().
read()
void org.jhotdraw.draw.connector.LocatorConnector.read (DOMInput in) throws IOException
Reimplemented from org.jhotdraw.draw.connector.AbstractConnector.
write()
void org.jhotdraw.draw.connector.LocatorConnector.write (DOMOutput out) throws IOException
Reimplemented from org.jhotdraw.draw.connector.AbstractConnector.
Member Data Documentation
SIZE
final int org.jhotdraw.draw.connector.LocatorConnector.SIZE = 2 static
The standard size of the connector. The display box is centered around the located point.
FIXME - Why do we need a standard size?
Referenced by org.jhotdraw.draw.connector.LocatorConnector.getBounds().
The documentation for this class was generated from the following file:
jhotdraw-core/src/main/java/org/jhotdraw/draw/connector/LocatorConnector.java