jhotdraw: org.jhotdraw.draw.QuadTreeDrawing.QuadTreeEventHandler Class Reference
org.jhotdraw.draw.QuadTreeDrawing.QuadTreeEventHandler Class Reference
Public Member Functions
void figureChanged (FigureEvent e)
Public Member Functions inherited from org.jhotdraw.draw.figure.AbstractCompositeFigure.EventHandler
void figureRequestRemove (FigureEvent e)
void areaInvalidated (FigureEvent e)
void undoableEditHappened (UndoableEditEvent e)
void attributeChanged (FigureEvent e)
void figureAdded (FigureEvent e)
void figureRemoved (FigureEvent e)
Public Member Functions inherited from org.jhotdraw.draw.event.FigureAdapter
void figureHandlesChanged (FigureEvent e)
Detailed Description
Handles all figure events fired by Figures contained in the Drawing.
Member Function Documentation
figureChanged()
void org.jhotdraw.draw.QuadTreeDrawing.QuadTreeEventHandler.figureChanged (FigureEvent e)
Sent when the geometry (for example the bounds) of the figure has changed.
Reimplemented from org.jhotdraw.draw.figure.AbstractCompositeFigure.EventHandler.
References org.jhotdraw.draw.figure.AbstractFigure.fireAreaInvalidated(), org.jhotdraw.draw.figure.Figure.getDrawingArea(), org.jhotdraw.draw.event.FigureEvent.getFigure(), org.jhotdraw.draw.figure.AbstractCompositeFigure.invalidate(), and org.jhotdraw.draw.figure.AbstractFigure.isChanging().
The documentation for this class was generated from the following file:
jhotdraw-core/src/main/java/org/jhotdraw/draw/QuadTreeDrawing.java