jhotdraw: org.jhotdraw.draw.figure.AbstractAttributedFigure Class Reference
org.jhotdraw.draw.figure.AbstractAttributedFigure Class Reference abstract
Public Member Functions
AbstractAttributedFigure ()
void setAttributeEnabled (AttributeKey<?> key, boolean b)
boolean isAttributeEnabled (AttributeKey<?> key)
void setAttributes (Map< AttributeKey<?>, Object > map)
Map< AttributeKey<?>, Object > getAttributes ()
Object getAttributesRestoreData ()
void restoreAttributesTo (Object restoreData)
void draw (Graphics2D g)
double getStrokeMiterLimitFactor ()
Rectangle2D.Double getDrawingArea ()
Rectangle2D.Double getDrawingArea (double factor)
AbstractAttributedFigure clone ()
void write (DOMOutput out) throws IOException
void read (DOMInput in) throws IOException
boolean hasAttribute (AttributeKey<?> key)
Public Member Functions inherited from org.jhotdraw.draw.figure.AbstractFigure
AbstractFigure ()
void addFigureListener (FigureListener l)
void removeFigureListener (FigureListener l)
void addNotify (Drawing d)
void removeNotify (Drawing d)
void fireAreaInvalidated ()
void fireFigureChanged ()
void remap (Map< Figure, Figure > oldToNew, boolean disconnectIfNotInMap)
Collection< Handle > createHandles (int detailLevel)
Cursor getCursor (Point2D.Double p)
final void setBounds (Rectangle2D.Double bounds)
void setBounds (Point2D.Double anchor, Point2D.Double lead)
void willChange ()
void changed ()
Connector findConnector (Point2D.Double p, ConnectionFigure prototype)
boolean includes (Figure figure)
Figure findFigureInside (Point2D.Double p)
Connector findCompatibleConnector (Connector c, boolean isStart)
Collection< Action > getActions (Point2D.Double p)
Tool getTool (Point2D.Double p)
boolean handleMouseClick (Point2D.Double p, MouseEvent evt, DrawingView view)
boolean handleDrop (Point2D.Double p, Collection< Figure > droppedFigures, DrawingView view)
Point2D.Double getEndPoint ()
Point2D.Double getStartPoint ()
Dimension2DDouble getPreferredSize ()
boolean isConnectable ()
void setConnectable (boolean newValue)
boolean isSelectable ()
void setSelectable (boolean newValue)
boolean isRemovable ()
void setRemovable (boolean newValue)
boolean isTransformable ()
void setTransformable (boolean newValue)
boolean isVisible ()
void setVisible (boolean newValue)
Collection< Figure > getDecomposition ()
void requestRemove ()
int getLayer ()
String getToolTipText (Point2D.Double p)
String toString ()
Collection< Connector > getConnectors (ConnectionFigure prototype)
Public Member Functions inherited from org.jhotdraw.draw.figure.Figure
Rectangle2D.Double getBounds ()
boolean contains (Point2D.Double p)
Object getTransformRestoreData ()
void restoreTransformTo (Object restoreData)
void transform (AffineTransform tx)
void addPropertyChangeListener (PropertyChangeListener listener)
void removePropertyChangeListener (PropertyChangeListener listener)
Protected Member Functions
abstract void drawFill (java.awt.Graphics2D g)
abstract void drawStroke (java.awt.Graphics2D g)
void drawText (java.awt.Graphics2D g)
void writeAttributes (DOMOutput out) throws IOException
void readAttributes (DOMInput in) throws IOException
AttributeKey<?> getAttributeKey (String name)
void applyAttributesTo (Figure that)
Protected Member Functions inherited from org.jhotdraw.draw.figure.AbstractFigure
Drawing getDrawing ()
Object getLock ()
void fireAreaInvalidated (Rectangle2D.Double invalidatedArea)
void fireAreaInvalidated (FigureEvent event)
void fireFigureRequestRemove ()
void fireFigureAdded ()
void fireFigureRemoved ()
void fireFigureChanged (Rectangle2D.Double changedArea)
void fireFigureChanged (FigureEvent event)
void fireFigureHandlesChanged ()
void fireUndoableEditHappened (UndoableEdit edit)
void invalidate ()
boolean isChanging ()
int getChangingDepth ()
void validate ()
FontRenderContext getFontRenderContext ()
Additional Inherited Members
Static Public Attributes inherited from org.jhotdraw.draw.figure.Figure
static final String CONNECTABLE_PROPERTY = "connectable"
static final String REMOVABLE_PROPERTY = "removable"
static final String SELECTABLE_PROPERTY = "selectable"
static final String TRANSFORMABLE_PROPERTY = "transformable"
Protected Attributes inherited from org.jhotdraw.draw.figure.AbstractFigure
EventListenerList listenerList = new EventListenerList()
int changingDepth = 0
Detailed Description
This abstract class can be extended to implement a Figure which has its own attribute set.
Author
Werner Randelshofer
Version
$Id: AbstractAttributedFigure.java 778 2012-04-13 15:37:19Z rawcoder $
Constructor & Destructor Documentation
AbstractAttributedFigure()
org.jhotdraw.draw.figure.AbstractAttributedFigure.AbstractAttributedFigure ()
Creates a new instance.
Referenced by org.jhotdraw.draw.figure.AbstractAttributedFigure.clone().
Member Function Documentation
applyAttributesTo()
void org.jhotdraw.draw.figure.AbstractAttributedFigure.applyAttributesTo (Figure that) protected
Applies all attributes of this figure to that figure.
clone()
AbstractAttributedFigure org.jhotdraw.draw.figure.AbstractAttributedFigure.clone ()
Returns a clone of the figure, with clones of all aggregated figures, such as children and decorators. The cloned figure does not clone the list of FigureListeners from its original.
Reimplemented from org.jhotdraw.draw.figure.AbstractFigure.
Reimplemented in org.jhotdraw.draw.figure.TriangleFigure, org.jhotdraw.draw.figure.TextFigure, org.jhotdraw.draw.figure.TextAreaFigure, org.jhotdraw.draw.figure.RoundRectangleFigure, org.jhotdraw.draw.figure.RectangleFigure, org.jhotdraw.draw.figure.LineConnectionFigure, org.jhotdraw.draw.figure.LabeledLineConnectionFigure, org.jhotdraw.draw.figure.ImageFigure, org.jhotdraw.draw.figure.EllipseFigure, org.jhotdraw.draw.figure.DiamondFigure, org.jhotdraw.draw.figure.BezierFigure, and org.jhotdraw.draw.figure.AbstractAttributedDecoratedFigure.
References org.jhotdraw.draw.figure.AbstractAttributedFigure.AbstractAttributedFigure(), and org.jhotdraw.draw.figure.AbstractAttributedFigure.clone().
Referenced by org.jhotdraw.draw.figure.AbstractAttributedFigure.clone().
draw()
void org.jhotdraw.draw.figure.AbstractAttributedFigure.draw (Graphics2D g)
Draws the figure.
Parameters
g The Graphics2D to draw to.
Implements org.jhotdraw.draw.figure.Figure.
Reimplemented in org.jhotdraw.draw.figure.LabeledLineConnectionFigure, and org.jhotdraw.draw.figure.AbstractAttributedDecoratedFigure.
References org.jhotdraw.draw.figure.AbstractAttributedFigure.drawFill(), org.jhotdraw.draw.figure.AbstractAttributedFigure.drawStroke(), org.jhotdraw.draw.figure.AbstractAttributedFigure.drawText(), org.jhotdraw.draw.AttributeKeys.getScaleFactorFromGraphics(), and org.jhotdraw.draw.AttributeKeys.getStroke().
Referenced by org.jhotdraw.draw.figure.BezierFigure.drawCaps(), and org.jhotdraw.draw.action.LineDecorationIcon.paintIcon().
drawFill()
abstract void org.jhotdraw.draw.figure.AbstractAttributedFigure.drawFill (java.awt.Graphics2D g) abstract protected
This method is called by method draw() to draw the fill area of the figure. AbstractAttributedFigure configures the Graphics2D object with the FILL_COLOR attribute before calling this method. If the FILL_COLOR attribute is null, this method is not called.
Reimplemented in org.jhotdraw.draw.figure.TextFigure.
Referenced by org.jhotdraw.draw.figure.AbstractAttributedFigure.draw().
drawStroke()
abstract void org.jhotdraw.draw.figure.AbstractAttributedFigure.drawStroke (java.awt.Graphics2D g) abstract protected
This method is called by method draw() to draw the lines of the figure . AttributedFigure configures the Graphics2D object with the STROKE_COLOR attribute before calling this method. If the STROKE_COLOR attribute is null, this method is not called.
Reimplemented in org.jhotdraw.draw.figure.TextFigure.
Referenced by org.jhotdraw.draw.figure.AbstractAttributedFigure.draw().
drawText()
void org.jhotdraw.draw.figure.AbstractAttributedFigure.drawText (java.awt.Graphics2D g) protected
This method is called by method draw() to draw the text of the figure . AbstractAttributedFigure configures the Graphics2D object with the TEXT_COLOR attribute before calling this method. If the TEXT_COLOR attribute is null, this method is not called.
Reimplemented in org.jhotdraw.draw.figure.TextFigure.
Referenced by org.jhotdraw.draw.figure.AbstractAttributedFigure.draw(), and org.jhotdraw.draw.figure.ImageFigure.drawFigure().
getAttributeKey()
AttributeKey<?> org.jhotdraw.draw.figure.AbstractAttributedFigure.getAttributeKey (String name) protected
References org.jhotdraw.draw.AttributeKeys.SUPPORTED_ATTRIBUTES_MAP.
Referenced by org.jhotdraw.draw.figure.AbstractAttributedFigure.readAttributes().
getAttributes()
Map<AttributeKey<?>, Object> org.jhotdraw.draw.figure.AbstractAttributedFigure.getAttributes ()
Returns a view to all attributes of this figure. By convention, an unmodifiable map is returned.
Implements org.jhotdraw.draw.figure.Figure.
Referenced by org.jhotdraw.draw.figure.AbstractAttributedFigure.getAttributesRestoreData().
getAttributesRestoreData()
Object org.jhotdraw.draw.figure.AbstractAttributedFigure.getAttributesRestoreData ()
Gets data which can be used to restore the attributes of the figure after a set has been applied to it.
Implements org.jhotdraw.draw.figure.Figure.
References org.jhotdraw.draw.figure.AbstractAttributedFigure.getAttributes().
getDrawingArea() [1/2]
Rectangle2D.Double org.jhotdraw.draw.figure.AbstractAttributedFigure.getDrawingArea ()
Returns the drawing area of the figure as a Rectangle.
The drawing area is used to inform DrawingView about the area that is needed to draw this figure.
The drawing area needs to be large enough, to take line width, line caps and other decorations into account that exceed the bounds of the Figure.
Implements org.jhotdraw.draw.figure.Figure.
Reimplemented in org.jhotdraw.draw.figure.TriangleFigure, org.jhotdraw.draw.figure.RoundRectangleFigure, org.jhotdraw.draw.figure.RectangleFigure, org.jhotdraw.draw.figure.LabeledLineConnectionFigure, org.jhotdraw.draw.figure.EllipseFigure, org.jhotdraw.draw.figure.DiamondFigure, and org.jhotdraw.draw.figure.AbstractAttributedDecoratedFigure.
Referenced by org.jhotdraw.draw.figure.BezierFigure.getDrawingArea().
getDrawingArea() [2/2]
Rectangle2D.Double org.jhotdraw.draw.figure.AbstractAttributedFigure.getDrawingArea (double factor)
Returns the drawing area of the figure as a Rectangle.
The drawing area is used to inform DrawingView about the area that is needed to draw this figure.
The drawing area needs to be large enough, to take line width, line caps and other decorations into account that exceed the bounds of the Figure.
Implements org.jhotdraw.draw.figure.Figure.
Reimplemented in org.jhotdraw.draw.figure.BezierFigure.
References org.jhotdraw.draw.figure.Figure.getBounds(), and org.jhotdraw.draw.AttributeKeys.getStrokeTotalWidth().
getStrokeMiterLimitFactor()
double org.jhotdraw.draw.figure.AbstractAttributedFigure.getStrokeMiterLimitFactor ()
References org.jhotdraw.draw.AttributeKeys.STROKE_MITER_LIMIT.
hasAttribute()
boolean org.jhotdraw.draw.figure.AbstractAttributedFigure.hasAttribute (AttributeKey<?> key)
isAttributeEnabled()
boolean org.jhotdraw.draw.figure.AbstractAttributedFigure.isAttributeEnabled (AttributeKey<?> key)
read()
void org.jhotdraw.draw.figure.AbstractAttributedFigure.read (DOMInput in) throws IOException
Reimplemented in org.jhotdraw.draw.figure.TextFigure, org.jhotdraw.draw.figure.TextAreaFigure, org.jhotdraw.draw.figure.RoundRectangleFigure, org.jhotdraw.draw.figure.LineConnectionFigure, org.jhotdraw.draw.figure.ImageFigure, org.jhotdraw.draw.figure.BezierFigure, and org.jhotdraw.draw.figure.AbstractAttributedDecoratedFigure.
References org.jhotdraw.draw.figure.AbstractAttributedFigure.readAttributes(), and org.jhotdraw.draw.figure.AbstractFigure.setBounds().
readAttributes()
void org.jhotdraw.draw.figure.AbstractAttributedFigure.readAttributes (DOMInput in) throws IOException protected
References org.jhotdraw.draw.figure.AbstractAttributedFigure.getAttributeKey(), and org.jhotdraw.draw.AttributeKey< T >.isAssignable().
Referenced by org.jhotdraw.draw.figure.AbstractAttributedFigure.read(), org.jhotdraw.draw.figure.BezierFigure.read(), org.jhotdraw.draw.figure.TextAreaFigure.read(), and org.jhotdraw.draw.figure.TextFigure.read().
restoreAttributesTo()
void org.jhotdraw.draw.figure.AbstractAttributedFigure.restoreAttributesTo (Object restoreData)
Restores the attributes of the figure to a previously stored state.
Implements org.jhotdraw.draw.figure.Figure.
References org.jhotdraw.draw.figure.AbstractAttributedFigure.setAttributes().
setAttributeEnabled()
void org.jhotdraw.draw.figure.AbstractAttributedFigure.setAttributeEnabled (AttributeKey<?> key, boolean b)
setAttributes()
void org.jhotdraw.draw.figure.AbstractAttributedFigure.setAttributes (Map< AttributeKey<?>, Object > map)
Referenced by org.jhotdraw.draw.figure.AbstractAttributedFigure.restoreAttributesTo().
write()
void org.jhotdraw.draw.figure.AbstractAttributedFigure.write (DOMOutput out) throws IOException
Reimplemented in org.jhotdraw.draw.figure.TextFigure, org.jhotdraw.draw.figure.TextAreaFigure, org.jhotdraw.draw.figure.RoundRectangleFigure, org.jhotdraw.draw.figure.LineConnectionFigure, org.jhotdraw.draw.figure.ImageFigure, org.jhotdraw.draw.figure.BezierFigure, and org.jhotdraw.draw.figure.AbstractAttributedDecoratedFigure.
References org.jhotdraw.draw.figure.Figure.getBounds(), and org.jhotdraw.draw.figure.AbstractAttributedFigure.writeAttributes().
writeAttributes()
void org.jhotdraw.draw.figure.AbstractAttributedFigure.writeAttributes (DOMOutput out) throws IOException protected
References org.jhotdraw.draw.figure.Figure.get(), and org.jhotdraw.draw.AttributeKey< T >.getKey().
Referenced by org.jhotdraw.draw.figure.AbstractAttributedFigure.write(), org.jhotdraw.draw.figure.BezierFigure.write(), org.jhotdraw.draw.figure.TextAreaFigure.write(), and org.jhotdraw.draw.figure.TextFigure.write().
The documentation for this class was generated from the following file:
jhotdraw-core/src/main/java/org/jhotdraw/draw/figure/AbstractAttributedFigure.java