jhotdraw: org.jhotdraw.draw.handle.TransformHandleKit Class Reference
org.jhotdraw.draw.handle.TransformHandleKit Class Reference
Public Member Functions
TransformHandleKit ()
Static Public Member Functions
static void addCornerTransformHandles (Figure f, Collection< Handle > handles)
static void addEdgeTransformHandles (Figure f, Collection< Handle > handles)
static void addScaleMoveTransformHandles (Figure f, Collection< Handle > handles)
static void addTransformHandles (Figure f, Collection< Handle > handles)
static void addGroupTransformHandles (Figure f, Collection< Handle > handles)
static void addGroupHoverHandles (Figure f, Collection< Handle > handles)
static Handle south (Figure owner)
static Handle southEast (Figure owner)
static Handle southWest (Figure owner)
static Handle north (Figure owner)
static Handle northEast (Figure owner)
static Handle northWest (Figure owner)
static Handle east (Figure owner)
static Handle west (Figure owner)
Detailed Description
A set of utility methods to create Handles which transform a Figure by using its transform method.
Author
Werner Randelshofer
Version
$Id$
Constructor & Destructor Documentation
TransformHandleKit()
org.jhotdraw.draw.handle.TransformHandleKit.TransformHandleKit ()
Creates a new instance.
Member Function Documentation
addCornerTransformHandles()
static void org.jhotdraw.draw.handle.TransformHandleKit.addCornerTransformHandles (Figure f, Collection< Handle > handles) static
Creates handles for each corner of a figure and adds them to the provided collection.
References org.jhotdraw.draw.figure.Figure.isTransformable(), org.jhotdraw.draw.handle.TransformHandleKit.northEast(), org.jhotdraw.draw.handle.TransformHandleKit.northWest(), org.jhotdraw.draw.handle.TransformHandleKit.southEast(), and org.jhotdraw.draw.handle.TransformHandleKit.southWest().
Referenced by org.jhotdraw.draw.handle.TransformHandleKit.addGroupTransformHandles(), org.jhotdraw.draw.handle.TransformHandleKit.addScaleMoveTransformHandles(), and org.jhotdraw.draw.handle.TransformHandleKit.addTransformHandles().
addEdgeTransformHandles()
static void org.jhotdraw.draw.handle.TransformHandleKit.addEdgeTransformHandles (Figure f, Collection< Handle > handles) static
Fills the given collection with handles at each the north, south, east, and west of the figure.
References org.jhotdraw.draw.handle.TransformHandleKit.east(), org.jhotdraw.draw.figure.Figure.isTransformable(), org.jhotdraw.draw.handle.TransformHandleKit.north(), org.jhotdraw.draw.handle.TransformHandleKit.south(), and org.jhotdraw.draw.handle.TransformHandleKit.west().
Referenced by org.jhotdraw.draw.handle.TransformHandleKit.addGroupTransformHandles(), org.jhotdraw.draw.handle.TransformHandleKit.addScaleMoveTransformHandles(), and org.jhotdraw.draw.handle.TransformHandleKit.addTransformHandles().
addGroupHoverHandles()
static void org.jhotdraw.draw.handle.TransformHandleKit.addGroupHoverHandles (Figure f, Collection< Handle > handles) static
Adds handles for scaling, moving, rotating and shearing a Figure.
addGroupTransformHandles()
static void org.jhotdraw.draw.handle.TransformHandleKit.addGroupTransformHandles (Figure f, Collection< Handle > handles) static
Adds handles for scaling, moving, rotating and shearing a Figure.
References org.jhotdraw.draw.handle.TransformHandleKit.addCornerTransformHandles(), and org.jhotdraw.draw.handle.TransformHandleKit.addEdgeTransformHandles().
addScaleMoveTransformHandles()
static void org.jhotdraw.draw.handle.TransformHandleKit.addScaleMoveTransformHandles (Figure f, Collection< Handle > handles) static
Adds handles for scaling and moving a Figure.
References org.jhotdraw.draw.handle.TransformHandleKit.addCornerTransformHandles(), org.jhotdraw.draw.handle.TransformHandleKit.addEdgeTransformHandles(), and org.jhotdraw.draw.figure.Figure.isTransformable().
Referenced by org.jhotdraw.draw.figure.AbstractCompositeFigure.createHandles().
addTransformHandles()
static void org.jhotdraw.draw.handle.TransformHandleKit.addTransformHandles (Figure f, Collection< Handle > handles) static
Adds handles for scaling, moving, rotating and shearing a Figure.
References org.jhotdraw.draw.handle.TransformHandleKit.addCornerTransformHandles(), org.jhotdraw.draw.handle.TransformHandleKit.addEdgeTransformHandles(), and org.jhotdraw.draw.figure.Figure.isTransformable().
Referenced by org.jhotdraw.draw.figure.BezierFigure.createHandles().
east()
static Handle org.jhotdraw.draw.handle.TransformHandleKit.east (Figure owner) static
Referenced by org.jhotdraw.draw.handle.TransformHandleKit.addEdgeTransformHandles().
north()
static Handle org.jhotdraw.draw.handle.TransformHandleKit.north (Figure owner) static
Referenced by org.jhotdraw.draw.handle.TransformHandleKit.addEdgeTransformHandles().
northEast()
static Handle org.jhotdraw.draw.handle.TransformHandleKit.northEast (Figure owner) static
Referenced by org.jhotdraw.draw.handle.TransformHandleKit.addCornerTransformHandles().
northWest()
static Handle org.jhotdraw.draw.handle.TransformHandleKit.northWest (Figure owner) static
Referenced by org.jhotdraw.draw.handle.TransformHandleKit.addCornerTransformHandles().
south()
static Handle org.jhotdraw.draw.handle.TransformHandleKit.south (Figure owner) static
Referenced by org.jhotdraw.draw.handle.TransformHandleKit.addEdgeTransformHandles().
southEast()
static Handle org.jhotdraw.draw.handle.TransformHandleKit.southEast (Figure owner) static
Referenced by org.jhotdraw.draw.handle.TransformHandleKit.addCornerTransformHandles().
southWest()
static Handle org.jhotdraw.draw.handle.TransformHandleKit.southWest (Figure owner) static
Referenced by org.jhotdraw.draw.handle.TransformHandleKit.addCornerTransformHandles().
west()
static Handle org.jhotdraw.draw.handle.TransformHandleKit.west (Figure owner) static
Referenced by org.jhotdraw.draw.handle.TransformHandleKit.addEdgeTransformHandles().
The documentation for this class was generated from the following file:
jhotdraw-core/src/main/java/org/jhotdraw/draw/handle/TransformHandleKit.java