jhotdraw: org.jhotdraw.draw.figure.ImageFigure Class Reference
org.jhotdraw.draw.figure.ImageFigure Class Reference
Public Member Functions
ImageFigure ()
ImageFigure (double x, double y, double width, double height)
Rectangle2D.Double getBounds ()
Rectangle2D.Double getFigureDrawingArea ()
boolean figureContains (Point2D.Double p)
void setBounds (Point2D.Double anchor, Point2D.Double lead)
void transform (AffineTransform tx)
void restoreTransformTo (Object geometry)
Object getTransformRestoreData ()
Collection< Action > getActions (Point2D.Double p)
Connector findConnector (Point2D.Double p, ConnectionFigure prototype)
Connector findCompatibleConnector (Connector c, boolean isStartConnector)
ImageFigure clone ()
void read (DOMInput in) throws IOException
void write (DOMOutput out) throws IOException
void setImage (byte[] imageData, BufferedImage bufferedImage)
void setImageData (byte[] imageData)
void setBufferedImage (BufferedImage image)
BufferedImage getBufferedImage ()
byte[] getImageData ()
void loadImage (File file) throws IOException
void loadImage (InputStream in) throws IOException
Public Member Functions inherited from org.jhotdraw.draw.figure.AbstractAttributedDecoratedFigure
final void draw (Graphics2D g)
final Rectangle2D.Double getDrawingArea ()
void setDecorator (Figure newValue)
Figure getDecorator ()
final boolean contains (Point2D.Double p)
Public Member Functions inherited from org.jhotdraw.draw.figure.AbstractAttributedFigure
AbstractAttributedFigure ()
void setAttributeEnabled (AttributeKey<?> key, boolean b)
boolean isAttributeEnabled (AttributeKey<?> key)
void setAttributes (Map< AttributeKey<?>, Object > map)
Map< AttributeKey<?>, Object > getAttributes ()
Object getAttributesRestoreData ()
void restoreAttributesTo (Object restoreData)
double getStrokeMiterLimitFactor ()
Rectangle2D.Double getDrawingArea (double factor)
boolean hasAttribute (AttributeKey<?> key)
Public Member Functions inherited from org.jhotdraw.draw.figure.AbstractFigure
AbstractFigure ()
void addFigureListener (FigureListener l)
void removeFigureListener (FigureListener l)
void addNotify (Drawing d)
void removeNotify (Drawing d)
void fireAreaInvalidated ()
void fireFigureChanged ()
void remap (Map< Figure, Figure > oldToNew, boolean disconnectIfNotInMap)
Collection< Handle > createHandles (int detailLevel)
Cursor getCursor (Point2D.Double p)
final void setBounds (Rectangle2D.Double bounds)
void willChange ()
void changed ()
boolean includes (Figure figure)
Figure findFigureInside (Point2D.Double p)
Tool getTool (Point2D.Double p)
boolean handleMouseClick (Point2D.Double p, MouseEvent evt, DrawingView view)
boolean handleDrop (Point2D.Double p, Collection< Figure > droppedFigures, DrawingView view)
Point2D.Double getEndPoint ()
Point2D.Double getStartPoint ()
Dimension2DDouble getPreferredSize ()
boolean isConnectable ()
void setConnectable (boolean newValue)
boolean isSelectable ()
void setSelectable (boolean newValue)
boolean isRemovable ()
void setRemovable (boolean newValue)
boolean isTransformable ()
void setTransformable (boolean newValue)
boolean isVisible ()
void setVisible (boolean newValue)
Collection< Figure > getDecomposition ()
void requestRemove ()
int getLayer ()
String getToolTipText (Point2D.Double p)
String toString ()
Collection< Connector > getConnectors (ConnectionFigure prototype)
Public Member Functions inherited from org.jhotdraw.draw.figure.Figure
void addPropertyChangeListener (PropertyChangeListener listener)
void removePropertyChangeListener (PropertyChangeListener listener)
Protected Member Functions
void drawFigure (Graphics2D g)
void drawFill (Graphics2D g)
void drawImage (Graphics2D g)
void drawStroke (Graphics2D g)
Protected Member Functions inherited from org.jhotdraw.draw.figure.AbstractAttributedDecoratedFigure
void drawDecorator (Graphics2D g)
void updateDecoratorBounds ()
void writeDecorator (DOMOutput out) throws IOException
void readDecorator (DOMInput in) throws IOException
Protected Member Functions inherited from org.jhotdraw.draw.figure.AbstractAttributedFigure
abstract void drawFill (java.awt.Graphics2D g)
abstract void drawStroke (java.awt.Graphics2D g)
void drawText (java.awt.Graphics2D g)
void writeAttributes (DOMOutput out) throws IOException
void readAttributes (DOMInput in) throws IOException
AttributeKey<?> getAttributeKey (String name)
void applyAttributesTo (Figure that)
Protected Member Functions inherited from org.jhotdraw.draw.figure.AbstractFigure
Drawing getDrawing ()
Object getLock ()
void fireAreaInvalidated (Rectangle2D.Double invalidatedArea)
void fireAreaInvalidated (FigureEvent event)
void fireFigureRequestRemove ()
void fireFigureAdded ()
void fireFigureRemoved ()
void fireFigureChanged (Rectangle2D.Double changedArea)
void fireFigureChanged (FigureEvent event)
void fireFigureHandlesChanged ()
void fireUndoableEditHappened (UndoableEdit edit)
void invalidate ()
boolean isChanging ()
int getChangingDepth ()
void validate ()
FontRenderContext getFontRenderContext ()
Additional Inherited Members
Static Public Attributes inherited from org.jhotdraw.draw.figure.Figure
static final String CONNECTABLE_PROPERTY = "connectable"
static final String REMOVABLE_PROPERTY = "removable"
static final String SELECTABLE_PROPERTY = "selectable"
static final String TRANSFORMABLE_PROPERTY = "transformable"
Protected Attributes inherited from org.jhotdraw.draw.figure.AbstractFigure
EventListenerList listenerList = new EventListenerList()
int changingDepth = 0
Detailed Description
A default implementation of ImageHolderFigure which can hold a buffered image.
Author
Werner Randelshofer
Version
$Id$
Constructor & Destructor Documentation
ImageFigure() [1/2]
org.jhotdraw.draw.figure.ImageFigure.ImageFigure ()
Creates a new instance.
Referenced by org.jhotdraw.draw.figure.ImageFigure.clone().
ImageFigure() [2/2]
org.jhotdraw.draw.figure.ImageFigure.ImageFigure (double x, double y, double width, double height)
Member Function Documentation
clone()
ImageFigure org.jhotdraw.draw.figure.ImageFigure.clone ()
Returns a clone of the figure, with clones of all aggregated figures, such as children and decorators. The cloned figure does not clone the list of FigureListeners from its original.
Reimplemented from org.jhotdraw.draw.figure.AbstractAttributedDecoratedFigure.
References org.jhotdraw.draw.figure.ImageFigure.clone(), and org.jhotdraw.draw.figure.ImageFigure.ImageFigure().
Referenced by org.jhotdraw.draw.figure.ImageFigure.clone().
drawFigure()
void org.jhotdraw.draw.figure.ImageFigure.drawFigure (Graphics2D g) protected
Reimplemented from org.jhotdraw.draw.figure.AbstractAttributedDecoratedFigure.
References org.jhotdraw.draw.figure.ImageFigure.drawFill(), org.jhotdraw.draw.figure.ImageFigure.drawImage(), org.jhotdraw.draw.figure.ImageFigure.drawStroke(), org.jhotdraw.draw.figure.AbstractAttributedFigure.drawText(), org.jhotdraw.draw.AttributeKeys.getScaleFactorFromGraphics(), and org.jhotdraw.draw.AttributeKeys.getStroke().
drawFill()
void org.jhotdraw.draw.figure.ImageFigure.drawFill (Graphics2D g) protected
References org.jhotdraw.draw.AttributeKeys.getPerpendicularFillGrowth(), and org.jhotdraw.draw.AttributeKeys.getScaleFactorFromGraphics().
Referenced by org.jhotdraw.draw.figure.ImageFigure.drawFigure().
drawImage()
void org.jhotdraw.draw.figure.ImageFigure.drawImage (Graphics2D g) protected
References org.jhotdraw.draw.figure.ImageFigure.getBufferedImage().
Referenced by org.jhotdraw.draw.figure.ImageFigure.drawFigure().
drawStroke()
void org.jhotdraw.draw.figure.ImageFigure.drawStroke (Graphics2D g) protected
References org.jhotdraw.draw.AttributeKeys.getPerpendicularDrawGrowth(), and org.jhotdraw.draw.AttributeKeys.getScaleFactorFromGraphics().
Referenced by org.jhotdraw.draw.figure.ImageFigure.drawFigure().
figureContains()
boolean org.jhotdraw.draw.figure.ImageFigure.figureContains (Point2D.Double p)
Checks if a Point2D.Double is inside the figure.
Reimplemented from org.jhotdraw.draw.figure.AbstractAttributedDecoratedFigure.
References org.jhotdraw.draw.AttributeKeys.getPerpendicularHitGrowth().
findCompatibleConnector()
Connector org.jhotdraw.draw.figure.ImageFigure.findCompatibleConnector (Connector c, boolean isStartConnector)
Gets a compatible connector. If the provided connector is part of this figure, return the connector. If the provided connector is part of another figure, return a connector with the same semantics for this figure. Returns null, if no compatible connector is available.
Implements org.jhotdraw.draw.figure.Figure.
findConnector()
Connector org.jhotdraw.draw.figure.ImageFigure.findConnector (Point2D.Double p, ConnectionFigure prototype)
Gets a connector for this figure at the given location. A figure can have different connectors at different locations.
Parameters
p the location of the connector.
prototype The prototype used to create a connection or null if unknown. This allows for specific connectors for different connection figures.
Implements org.jhotdraw.draw.figure.Figure.
getActions()
Collection<Action> org.jhotdraw.draw.figure.ImageFigure.getActions (Point2D.Double p)
Returns a collection of Action's for the specified location on the figure.
The collection may contain null entries. These entries are used interpreted as separators in the popup menu.
Actions can use the property Figure.ACTION_SUBMENU to specify a submenu.
Implements org.jhotdraw.draw.figure.Figure.
getBounds()
Rectangle2D.Double org.jhotdraw.draw.figure.ImageFigure.getBounds ()
Returns the untransformed logical bounds of the figure as a Rectangle.
The bounds are used by Handle objects for adjusting the figure and for aligning the figure on a grid.
Implements org.jhotdraw.draw.figure.Figure.
getBufferedImage()
BufferedImage org.jhotdraw.draw.figure.ImageFigure.getBufferedImage ()
Gets the buffered image. If necessary, this method creates the buffered image from the image data.
Implements org.jhotdraw.draw.figure.ImageHolderFigure.
Referenced by org.jhotdraw.draw.figure.ImageFigure.drawImage().
getFigureDrawingArea()
Rectangle2D.Double org.jhotdraw.draw.figure.ImageFigure.getFigureDrawingArea ()
Reimplemented from org.jhotdraw.draw.figure.AbstractAttributedDecoratedFigure.
References org.jhotdraw.draw.AttributeKeys.getPerpendicularHitGrowth().
getImageData()
byte [] org.jhotdraw.draw.figure.ImageFigure.getImageData ()
Gets the image data. If necessary, this method creates the image data from the buffered image.
Note: For performance reasons this method returns a reference to the internally used image data array instead of cloning it. Do not modify this array.
Implements org.jhotdraw.draw.figure.ImageHolderFigure.
Referenced by org.jhotdraw.draw.figure.ImageFigure.write().
getTransformRestoreData()
Object org.jhotdraw.draw.figure.ImageFigure.getTransformRestoreData ()
Gets data which can be used to restore the transformation of the figure without loss of precision, after a transform has been applied to it.
See also
transform(AffineTransform)
Implements org.jhotdraw.draw.figure.Figure.
loadImage() [1/2]
void org.jhotdraw.draw.figure.ImageFigure.loadImage (File f) throws IOException
Loads an image from a File. By convention this method is never invoked on the AWT Event Dispatcher Thread.
Implements org.jhotdraw.draw.figure.ImageHolderFigure.
loadImage() [2/2]
void org.jhotdraw.draw.figure.ImageFigure.loadImage (InputStream in) throws IOException
Loads an image from an Input Stream. By convention this method is never invoked on the AWT Event Dispatcher Thread.
Implements org.jhotdraw.draw.figure.ImageHolderFigure.
read()
void org.jhotdraw.draw.figure.ImageFigure.read (DOMInput in) throws IOException
Reimplemented from org.jhotdraw.draw.figure.AbstractAttributedDecoratedFigure.
References org.jhotdraw.draw.figure.ImageFigure.setImageData().
restoreTransformTo()
void org.jhotdraw.draw.figure.ImageFigure.restoreTransformTo (Object restoreData)
Restores the transform of the figure to a previously stored state.
Implements org.jhotdraw.draw.figure.Figure.
setBounds()
void org.jhotdraw.draw.figure.ImageFigure.setBounds (Point2D.Double start, Point2D.Double end)
Sets the logical and untransformed bounds of the figure.
This is used by Tool's which create a new Figure and by Tool's which connect a Figure to another Figure.
This is a basic operation which does not fire events. Use the following code sequence, if you need event firing:
figure.willChange();
figure.setBounds(...);
figure.changed();
Parameters
start the start point of the bounds
end the end point of the bounds
See also
getBounds
Implements org.jhotdraw.draw.figure.Figure.
Referenced by org.jhotdraw.draw.figure.ImageFigure.transform().
setBufferedImage()
void org.jhotdraw.draw.figure.ImageFigure.setBufferedImage (BufferedImage image)
Sets the buffered image. This clears the image data.
Implements org.jhotdraw.draw.figure.ImageHolderFigure.
References org.jhotdraw.draw.figure.Figure.changed(), and org.jhotdraw.draw.figure.Figure.willChange().
setImage()
void org.jhotdraw.draw.figure.ImageFigure.setImage (byte[] imageData, BufferedImage bufferedImage)
Sets the image.
Parameters
imageData The image data. If this is null, a buffered image must be provided.
bufferedImage An image constructed from the imageData. If this is null, imageData must be provided.
Implements org.jhotdraw.draw.figure.ImageHolderFigure.
References org.jhotdraw.draw.figure.Figure.changed(), and org.jhotdraw.draw.figure.Figure.willChange().
setImageData()
void org.jhotdraw.draw.figure.ImageFigure.setImageData (byte[] imageData)
Sets the image data. This clears the buffered image.
Note: For performance reasons this method stores a reference to the imageData array instead of cloning it. Do not modify the image data array after invoking this method.
References org.jhotdraw.draw.figure.Figure.changed(), and org.jhotdraw.draw.figure.Figure.willChange().
Referenced by org.jhotdraw.draw.figure.ImageFigure.read().
transform()
void org.jhotdraw.draw.figure.ImageFigure.transform (AffineTransform tx)
Transforms the figure.
Parameters
tx The transformation.
Implements org.jhotdraw.draw.figure.Figure.
References org.jhotdraw.draw.figure.Figure.getEndPoint(), org.jhotdraw.draw.figure.Figure.getStartPoint(), and org.jhotdraw.draw.figure.ImageFigure.setBounds().
write()
void org.jhotdraw.draw.figure.ImageFigure.write (DOMOutput out) throws IOException
Reimplemented from org.jhotdraw.draw.figure.AbstractAttributedDecoratedFigure.
References org.jhotdraw.draw.figure.ImageFigure.getImageData().
The documentation for this class was generated from the following file:
jhotdraw-core/src/main/java/org/jhotdraw/draw/figure/ImageFigure.java