jhotdraw: org.jhotdraw.draw.handle.AbstractConnectionHandle Class Reference
org.jhotdraw.draw.handle.AbstractConnectionHandle Class Reference abstract
Public Member Functions
ConnectionFigure getOwner ()
boolean isCombinableWith (Handle handle)
void trackStart (Point anchor, int modifiersEx)
void trackStep (Point anchor, Point lead, int modifiersEx)
void trackEnd (Point anchor, Point lead, int modifiersEx)
void draw (Graphics2D g)
final Collection< Handle > createSecondaryHandles ()
String getToolTipText (Point p)
void repaintConnectors ()
Public Member Functions inherited from org.jhotdraw.draw.handle.AbstractHandle
AbstractHandle (Figure owner)
void addHandleListener (HandleListener l)
void removeHandleListener (HandleListener l)
void setView (DrawingView view)
DrawingView getView ()
DrawingEditor getEditor ()
boolean contains (Point p)
void invalidate ()
void dispose ()
void areaInvalidated (FigureEvent evt)
void figureAdded (FigureEvent e)
void figureRemoved (FigureEvent e)
void figureRequestRemove (FigureEvent e)
void figureChanged (FigureEvent evt)
Cursor getCursor ()
void keyTyped (KeyEvent evt)
void keyReleased (KeyEvent evt)
void keyPressed (KeyEvent evt)
final Rectangle getBounds ()
Rectangle getDrawingArea ()
void trackDoubleClick (Point p, int modifiersEx)
void attributeChanged (FigureEvent e)
void viewTransformChanged ()
void setToolTipText (String newValue)
void figureHandlesChanged (FigureEvent e)
Protected Member Functions
AbstractConnectionHandle (ConnectionFigure owner)
abstract Connector getTarget ()
abstract void disconnect ()
abstract void connect (Connector c)
abstract void setLocation (Point2D.Double p)
abstract Point2D.Double getLocation ()
Connector getSource ()
abstract boolean canConnect (Connector existingEnd, Connector targetEnd)
Connector findConnector (Point2D.Double p, Figure f, ConnectionFigure prototype)
void setPotentialTarget (Connector newTarget)
Rectangle basicGetBounds ()
BezierFigure getBezierFigure ()
abstract int getBezierNodeIndex ()
BezierPath.Node getBezierNode ()
Protected Member Functions inherited from org.jhotdraw.draw.handle.AbstractHandle
int getHandlesize ()
void fireAreaInvalidated (Rectangle invalidatedArea)
void fireUndoableEditHappened (UndoableEdit edit)
void fireHandleRequestRemove (Rectangle invalidatedArea)
void fireHandleRequestSecondaryHandles ()
void drawCircle (Graphics2D g, Color fill, Color stroke)
void drawRectangle (Graphics2D g, Color fill, Color stroke)
void drawDiamond (Graphics2D g, Color fill, Color stroke)
void updateBounds ()
Protected Attributes
Collection< Connector > connectors = Collections.emptyList()
Protected Attributes inherited from org.jhotdraw.draw.handle.AbstractHandle
DrawingView view
EventListenerList listenerList = new EventListenerList()
Detailed Description
This abstract class can be extended to implement a Handle the start or end point of a ConnectionFigure.
XXX - Undo/Redo is not implemented yet.
Author
Werner Randelshofer
Version
Id
AbstractConnectionHandle.java 527 2009-06-07 14:28:19Z rawcoder
Constructor & Destructor Documentation
AbstractConnectionHandle()
org.jhotdraw.draw.handle.AbstractConnectionHandle.AbstractConnectionHandle (ConnectionFigure owner) protected
Initializes the change connection handle.
Member Function Documentation
basicGetBounds()
Rectangle org.jhotdraw.draw.handle.AbstractConnectionHandle.basicGetBounds () protected
Reimplemented from org.jhotdraw.draw.handle.AbstractHandle.
References org.jhotdraw.draw.DrawingView.drawingToView(), org.jhotdraw.draw.handle.AbstractHandle.getHandlesize(), org.jhotdraw.draw.handle.AbstractConnectionHandle.getLocation(), and org.jhotdraw.draw.handle.AbstractHandle.view.
canConnect()
abstract boolean org.jhotdraw.draw.handle.AbstractConnectionHandle.canConnect (Connector existingEnd, Connector targetEnd) abstract protected
Reimplemented in org.jhotdraw.draw.handle.ConnectionStartHandle, and org.jhotdraw.draw.handle.ConnectionEndHandle.
connect()
abstract void org.jhotdraw.draw.handle.AbstractConnectionHandle.connect (Connector c) abstract protected
Connect the connection with the given figure.
Reimplemented in org.jhotdraw.draw.handle.ConnectionStartHandle, and org.jhotdraw.draw.handle.ConnectionEndHandle.
Referenced by org.jhotdraw.draw.handle.AbstractConnectionHandle.trackEnd().
createSecondaryHandles()
final Collection<Handle> org.jhotdraw.draw.handle.AbstractConnectionHandle.createSecondaryHandles ()
Creates secondary handles.
Reimplemented from org.jhotdraw.draw.handle.AbstractHandle.
References org.jhotdraw.draw.handle.AbstractConnectionHandle.getBezierFigure(), org.jhotdraw.draw.handle.AbstractConnectionHandle.getBezierNodeIndex(), org.jhotdraw.draw.figure.BezierFigure.getNode(), org.jhotdraw.draw.figure.BezierFigure.getNodeCount(), org.jhotdraw.draw.handle.AbstractConnectionHandle.getOwner(), and org.jhotdraw.draw.figure.BezierFigure.isClosed().
disconnect()
abstract void org.jhotdraw.draw.handle.AbstractConnectionHandle.disconnect () abstract protected
Disconnects the connection.
Reimplemented in org.jhotdraw.draw.handle.ConnectionStartHandle, and org.jhotdraw.draw.handle.ConnectionEndHandle.
Referenced by org.jhotdraw.draw.handle.AbstractConnectionHandle.trackEnd().
draw()
void org.jhotdraw.draw.handle.AbstractConnectionHandle.draw (Graphics2D g)
Draws this handle.
Reimplemented from org.jhotdraw.draw.handle.AbstractHandle.
References org.jhotdraw.draw.handle.HandleAttributeKeys.CONNECTED_CONNECTION_HANDLE_FILL_COLOR, org.jhotdraw.draw.handle.HandleAttributeKeys.CONNECTED_CONNECTION_HANDLE_STROKE_COLOR, org.jhotdraw.draw.handle.AbstractConnectionHandle.connectors, org.jhotdraw.draw.handle.HandleAttributeKeys.DISCONNECTED_CONNECTION_HANDLE_FILL_COLOR, org.jhotdraw.draw.handle.HandleAttributeKeys.DISCONNECTED_CONNECTION_HANDLE_STROKE_COLOR, org.jhotdraw.draw.handle.AbstractHandle.drawCircle(), org.jhotdraw.draw.DrawingView.getDrawingToViewTransform(), org.jhotdraw.draw.handle.AbstractHandle.getEditor(), org.jhotdraw.draw.handle.AbstractConnectionHandle.getTarget(), and org.jhotdraw.draw.handle.AbstractHandle.view.
findConnector()
Connector org.jhotdraw.draw.handle.AbstractConnectionHandle.findConnector (Point2D.Double p, Figure f, ConnectionFigure prototype) protected
References org.jhotdraw.draw.figure.Figure.findConnector().
getBezierFigure()
BezierFigure org.jhotdraw.draw.handle.AbstractConnectionHandle.getBezierFigure () protected
References org.jhotdraw.draw.handle.AbstractConnectionHandle.getOwner().
Referenced by org.jhotdraw.draw.handle.AbstractConnectionHandle.createSecondaryHandles(), org.jhotdraw.draw.handle.AbstractConnectionHandle.getBezierNode(), and org.jhotdraw.draw.handle.ConnectionEndHandle.getBezierNodeIndex().
getBezierNode()
BezierPath.Node org.jhotdraw.draw.handle.AbstractConnectionHandle.getBezierNode () protected
References org.jhotdraw.draw.handle.AbstractConnectionHandle.getBezierFigure(), org.jhotdraw.draw.handle.AbstractConnectionHandle.getBezierNodeIndex(), org.jhotdraw.draw.figure.BezierFigure.getNode(), and org.jhotdraw.draw.figure.BezierFigure.getNodeCount().
Referenced by org.jhotdraw.draw.handle.AbstractConnectionHandle.getToolTipText().
getBezierNodeIndex()
abstract int org.jhotdraw.draw.handle.AbstractConnectionHandle.getBezierNodeIndex () abstract protected
Reimplemented in org.jhotdraw.draw.handle.ConnectionStartHandle, and org.jhotdraw.draw.handle.ConnectionEndHandle.
Referenced by org.jhotdraw.draw.handle.AbstractConnectionHandle.createSecondaryHandles(), org.jhotdraw.draw.handle.AbstractConnectionHandle.getBezierNode(), and org.jhotdraw.draw.handle.AbstractConnectionHandle.trackEnd().
getLocation()
abstract Point2D.Double org.jhotdraw.draw.handle.AbstractConnectionHandle.getLocation () abstract protected
Returns the start point of the connection.
Reimplemented in org.jhotdraw.draw.handle.ConnectionStartHandle, and org.jhotdraw.draw.handle.ConnectionEndHandle.
Referenced by org.jhotdraw.draw.handle.AbstractConnectionHandle.basicGetBounds().
getOwner()
ConnectionFigure org.jhotdraw.draw.handle.AbstractConnectionHandle.getOwner ()
Returns the owner of this handle.
Reimplemented from org.jhotdraw.draw.handle.AbstractHandle.
Referenced by org.jhotdraw.draw.handle.ConnectionEndHandle.canConnect(), org.jhotdraw.draw.handle.ConnectionStartHandle.canConnect(), org.jhotdraw.draw.handle.ConnectionEndHandle.connect(), org.jhotdraw.draw.handle.ConnectionStartHandle.connect(), org.jhotdraw.draw.handle.AbstractConnectionHandle.createSecondaryHandles(), org.jhotdraw.draw.handle.ConnectionEndHandle.disconnect(), org.jhotdraw.draw.handle.ConnectionStartHandle.disconnect(), org.jhotdraw.draw.handle.AbstractConnectionHandle.getBezierFigure(), org.jhotdraw.draw.handle.ConnectionEndHandle.getLocation(), org.jhotdraw.draw.handle.ConnectionStartHandle.getLocation(), org.jhotdraw.draw.handle.AbstractConnectionHandle.getSource(), org.jhotdraw.draw.handle.ConnectionEndHandle.getTarget(), org.jhotdraw.draw.handle.ConnectionStartHandle.getTarget(), org.jhotdraw.draw.handle.AbstractConnectionHandle.getToolTipText(), org.jhotdraw.draw.handle.AbstractConnectionHandle.repaintConnectors(), org.jhotdraw.draw.handle.ConnectionEndHandle.setLocation(), org.jhotdraw.draw.handle.ConnectionStartHandle.setLocation(), org.jhotdraw.draw.handle.AbstractConnectionHandle.trackEnd(), org.jhotdraw.draw.handle.AbstractConnectionHandle.trackStart(), and org.jhotdraw.draw.handle.AbstractConnectionHandle.trackStep().
getSource()
Connector org.jhotdraw.draw.handle.AbstractConnectionHandle.getSource () protected
Gets the side of the connection that is unaffected by the change.
References org.jhotdraw.draw.figure.ConnectionFigure.getEndConnector(), org.jhotdraw.draw.handle.AbstractConnectionHandle.getOwner(), org.jhotdraw.draw.figure.ConnectionFigure.getStartConnector(), and org.jhotdraw.draw.handle.AbstractConnectionHandle.getTarget().
getTarget()
abstract Connector org.jhotdraw.draw.handle.AbstractConnectionHandle.getTarget () abstract protected
Returns the connector of the change.
Reimplemented in org.jhotdraw.draw.handle.ConnectionStartHandle, and org.jhotdraw.draw.handle.ConnectionEndHandle.
Referenced by org.jhotdraw.draw.handle.AbstractConnectionHandle.draw(), org.jhotdraw.draw.handle.AbstractConnectionHandle.getSource(), and org.jhotdraw.draw.handle.AbstractConnectionHandle.trackStart().
getToolTipText()
String org.jhotdraw.draw.handle.AbstractConnectionHandle.getToolTipText (Point p)
Returns a tooltip for the specified location. By default, AbstractHandle returns null.
Reimplemented from org.jhotdraw.draw.handle.AbstractHandle.
References org.jhotdraw.draw.handle.AbstractConnectionHandle.getBezierNode(), org.jhotdraw.draw.figure.ConnectionFigure.getLiner(), and org.jhotdraw.draw.handle.AbstractConnectionHandle.getOwner().
isCombinableWith()
boolean org.jhotdraw.draw.handle.AbstractConnectionHandle.isCombinableWith (Handle handle)
Returns true, if the given handle is an instance of the same class or of a subclass of this handle,.
Reimplemented from org.jhotdraw.draw.handle.AbstractHandle.
repaintConnectors()
void org.jhotdraw.draw.handle.AbstractConnectionHandle.repaintConnectors ()
Updates the list of connectors that we draw when the user moves or drags the mouse over a figure to which can connect.
References org.jhotdraw.draw.handle.AbstractConnectionHandle.connectors, org.jhotdraw.draw.DrawingView.drawingToView(), org.jhotdraw.draw.DrawingView.getComponent(), org.jhotdraw.draw.figure.Figure.getConnectors(), org.jhotdraw.draw.handle.AbstractConnectionHandle.getOwner(), and org.jhotdraw.draw.handle.AbstractHandle.view.
Referenced by org.jhotdraw.draw.handle.AbstractConnectionHandle.trackStep().
setLocation()
abstract void org.jhotdraw.draw.handle.AbstractConnectionHandle.setLocation (Point2D.Double p) abstract protected
Sets the location of the connectableConnector point.
Reimplemented in org.jhotdraw.draw.handle.ConnectionStartHandle, and org.jhotdraw.draw.handle.ConnectionEndHandle.
Referenced by org.jhotdraw.draw.handle.AbstractConnectionHandle.trackEnd(), and org.jhotdraw.draw.handle.AbstractConnectionHandle.trackStep().
setPotentialTarget()
void org.jhotdraw.draw.handle.AbstractConnectionHandle.setPotentialTarget (Connector newTarget) protected
trackEnd()
void org.jhotdraw.draw.handle.AbstractConnectionHandle.trackEnd (Point anchor, Point lead, int modifiersEx)
Connects the figure to the new connectableConnector. If there is no new connectableConnector the connection reverts to its original one.
Implements org.jhotdraw.draw.handle.Handle.
References org.jhotdraw.draw.figure.Figure.changed(), org.jhotdraw.draw.handle.AbstractConnectionHandle.connect(), org.jhotdraw.draw.handle.AbstractConnectionHandle.connectors, org.jhotdraw.draw.Constrainer.constrainPoint(), org.jhotdraw.draw.handle.AbstractConnectionHandle.disconnect(), org.jhotdraw.draw.handle.AbstractHandle.fireHandleRequestSecondaryHandles(), org.jhotdraw.draw.handle.AbstractConnectionHandle.getBezierNodeIndex(), org.jhotdraw.draw.DrawingView.getConstrainer(), org.jhotdraw.draw.DrawingView.getDrawing(), org.jhotdraw.draw.figure.ConnectionFigure.getNode(), org.jhotdraw.draw.figure.ConnectionFigure.getNodeCount(), org.jhotdraw.draw.handle.AbstractConnectionHandle.getOwner(), org.jhotdraw.draw.figure.ConnectionFigure.setLiner(), org.jhotdraw.draw.handle.AbstractConnectionHandle.setLocation(), org.jhotdraw.draw.figure.ConnectionFigure.setNode(), org.jhotdraw.draw.figure.ConnectionFigure.updateConnection(), org.jhotdraw.draw.handle.AbstractHandle.view, org.jhotdraw.draw.DrawingView.viewToDrawing(), and org.jhotdraw.draw.figure.Figure.willChange().
trackStart()
void org.jhotdraw.draw.handle.AbstractConnectionHandle.trackStart (Point anchor, int modifiersEx)
Disconnects the connection.
Implements org.jhotdraw.draw.handle.Handle.
References org.jhotdraw.draw.handle.AbstractHandle.fireHandleRequestSecondaryHandles(), org.jhotdraw.draw.figure.ConnectionFigure.getLiner(), org.jhotdraw.draw.handle.AbstractConnectionHandle.getOwner(), org.jhotdraw.draw.handle.AbstractConnectionHandle.getTarget(), and org.jhotdraw.draw.figure.ConnectionFigure.setLiner().
trackStep()
void org.jhotdraw.draw.handle.AbstractConnectionHandle.trackStep (Point anchor, Point lead, int modifiersEx)
Finds a new connectableConnector of the connection.
Implements org.jhotdraw.draw.handle.Handle.
References org.jhotdraw.draw.figure.Figure.changed(), org.jhotdraw.draw.Constrainer.constrainPoint(), org.jhotdraw.draw.connector.Connector.getAnchor(), org.jhotdraw.draw.DrawingView.getConstrainer(), org.jhotdraw.draw.DrawingView.getDrawing(), org.jhotdraw.draw.handle.AbstractConnectionHandle.getOwner(), org.jhotdraw.draw.handle.AbstractConnectionHandle.repaintConnectors(), org.jhotdraw.draw.handle.AbstractConnectionHandle.setLocation(), org.jhotdraw.draw.handle.AbstractHandle.view, org.jhotdraw.draw.DrawingView.viewToDrawing(), and org.jhotdraw.draw.figure.Figure.willChange().
Member Data Documentation
connectors
Collection<Connector> org.jhotdraw.draw.handle.AbstractConnectionHandle.connectors = Collections.emptyList() protected
All connectors of the connectable Figure.
Referenced by org.jhotdraw.draw.handle.AbstractConnectionHandle.draw(), org.jhotdraw.draw.handle.AbstractConnectionHandle.repaintConnectors(), and org.jhotdraw.draw.handle.AbstractConnectionHandle.trackEnd().
The documentation for this class was generated from the following file:
jhotdraw-core/src/main/java/org/jhotdraw/draw/handle/AbstractConnectionHandle.java