jhotdraw: org.jhotdraw.draw.layouter.AbstractLayouter Class Reference
org.jhotdraw.draw.layouter.AbstractLayouter Class Reference abstract
Public Member Functions
Insets2D.Double getInsets (Figure child)
Public Member Functions inherited from org.jhotdraw.draw.layouter.Layouter
Rectangle2D.Double calculateLayout (CompositeFigure compositeFigure, Point2D.Double anchor, Point2D.Double lead)
Rectangle2D.Double layout (CompositeFigure compositeFigure, Point2D.Double anchor, Point2D.Double lead)
Detailed Description
This abstract class can be extended to implement a Layouter which has its own attribute set.
Author
Werner Randelshofer
Version
$Id$
Member Function Documentation
getInsets()
Insets2D.Double org.jhotdraw.draw.layouter.AbstractLayouter.getInsets (Figure child)
References org.jhotdraw.draw.figure.Figure.get(), and org.jhotdraw.draw.figure.CompositeFigure.LAYOUT_INSETS.
Referenced by org.jhotdraw.draw.layouter.HorizontalLayouter.calculateLayout(), org.jhotdraw.draw.layouter.VerticalLayouter.calculateLayout(), org.jhotdraw.draw.layouter.HorizontalLayouter.layout(), and org.jhotdraw.draw.layouter.VerticalLayouter.layout().
The documentation for this class was generated from the following file:
jhotdraw-core/src/main/java/org/jhotdraw/draw/layouter/AbstractLayouter.java