jhotdraw: org.jhotdraw.draw.locator.BezierLabelLocator Class Reference
org.jhotdraw.draw.locator.BezierLabelLocator Class Reference
Public Member Functions
BezierLabelLocator ()
BezierLabelLocator (double relativePosition, double angle, double distance)
Point2D.Double locate (Figure owner)
Point2D.Double locate (Figure owner, Figure label)
Point2D.Double getRelativePoint (BezierFigure owner)
Point2D.Double getRelativeLabelPoint (BezierFigure owner, Figure label)
void read (DOMInput in)
void write (DOMOutput out)
Detailed Description
A Locator which can be used to place a label on the path of a BezierFigure.
The point is located at a distance and an angle relative to the total length of the bezier path.
XXX - The angle should be perpendicular to the path.
Author
Werner Randelshofer
Version
$Id$
Constructor & Destructor Documentation
BezierLabelLocator() [1/2]
org.jhotdraw.draw.locator.BezierLabelLocator.BezierLabelLocator ()
Creates a new instance. This constructor is for use by DOMStorable only.
BezierLabelLocator() [2/2]
org.jhotdraw.draw.locator.BezierLabelLocator.BezierLabelLocator (double relativePosition, double angle, double distance)
Creates a new locator.
Parameters
relativePosition The relative position of the label on the polyline. 0.0 specifies the start of the bezier path, 1.0 the end of the polyline. Values between 0.0 and 1.0 are relative positions on the bezier path.
angle The angle of the distance vector.
distance The length of the distance vector.
Member Function Documentation
getRelativeLabelPoint()
Point2D.Double org.jhotdraw.draw.locator.BezierLabelLocator.getRelativeLabelPoint (BezierFigure owner, Figure label)
Returns a Point2D.Double on the polyline that is at the provided relative position. XXX - Implement this and move it to BezierPath
References org.jhotdraw.draw.figure.BezierFigure.getPointOnPath(), and org.jhotdraw.draw.figure.Figure.getPreferredSize().
Referenced by org.jhotdraw.draw.locator.BezierLabelLocator.locate().
getRelativePoint()
Point2D.Double org.jhotdraw.draw.locator.BezierLabelLocator.getRelativePoint (BezierFigure owner)
Returns the coordinates of the relative point on the path of the specified bezier figure.
References org.jhotdraw.draw.figure.BezierFigure.getPointOnPath().
Referenced by org.jhotdraw.draw.locator.BezierLabelLocator.locate().
locate() [1/2]
Point2D.Double org.jhotdraw.draw.locator.BezierLabelLocator.locate (Figure owner)
Locates a position on the provided figure.
Returns
a point on the figure.
Implements org.jhotdraw.draw.locator.Locator.
References org.jhotdraw.draw.locator.BezierLabelLocator.getRelativePoint().
locate() [2/2]
Point2D.Double org.jhotdraw.draw.locator.BezierLabelLocator.locate (Figure owner, Figure dependent)
Locates a position on the provided figure relative to the dependent figure.
Returns
a point on the figure.
Implements org.jhotdraw.draw.locator.Locator.
References org.jhotdraw.draw.locator.BezierLabelLocator.getRelativeLabelPoint().
read()
void org.jhotdraw.draw.locator.BezierLabelLocator.read (DOMInput in)
write()
void org.jhotdraw.draw.locator.BezierLabelLocator.write (DOMOutput out)
The documentation for this class was generated from the following file:
jhotdraw-core/src/main/java/org/jhotdraw/draw/locator/BezierLabelLocator.java