jhotdraw: org.jhotdraw.draw.figure.LabelFigure Class Reference
org.jhotdraw.draw.figure.LabelFigure Class Reference
Public Member Functions
LabelFigure ()
LabelFigure (String text)
void setLabelFor (TextHolderFigure target)
TextHolderFigure getLabelFor ()
Tool getTool (Point2D.Double p)
void areaInvalidated (FigureEvent e)
void attributeChanged (FigureEvent e)
void figureAdded (FigureEvent e)
void figureChanged (FigureEvent e)
void figureRemoved (FigureEvent e)
void figureRequestRemove (FigureEvent e)
void remap (Map< Figure, Figure > oldToNew, boolean disconnectIfNotInMap)
void figureHandlesChanged (FigureEvent e)
Public Member Functions inherited from org.jhotdraw.draw.figure.TextFigure
TextFigure ()
TextFigure (String text)
void transform (AffineTransform tx)
void setBounds (Point2D.Double anchor, Point2D.Double lead)
boolean figureContains (Point2D.Double p)
Rectangle2D.Double getBounds ()
Dimension2DDouble getPreferredSize ()
double getBaseline ()
void restoreTransformTo (Object geometry)
Object getTransformRestoreData ()
String getText ()
void setText (String newText)
int getTextColumns ()
int getTabSize ()
Insets2D.Double getInsets ()
Font getFont ()
Color getTextColor ()
Color getFillColor ()
void setFontSize (float size)
float getFontSize ()
boolean isEditable ()
void setEditable (boolean b)
Collection< Handle > createHandles (int detailLevel)
void invalidate ()
void read (DOMInput in) throws IOException
void write (DOMOutput out) throws IOException
TextFigure clone ()
boolean isTextOverflow ()
Public Member Functions inherited from org.jhotdraw.draw.figure.AbstractAttributedDecoratedFigure
final void draw (Graphics2D g)
final Rectangle2D.Double getDrawingArea ()
void setDecorator (Figure newValue)
Figure getDecorator ()
final boolean contains (Point2D.Double p)
Public Member Functions inherited from org.jhotdraw.draw.figure.AbstractAttributedFigure
AbstractAttributedFigure ()
void setAttributeEnabled (AttributeKey<?> key, boolean b)
boolean isAttributeEnabled (AttributeKey<?> key)
void setAttributes (Map< AttributeKey<?>, Object > map)
Map< AttributeKey<?>, Object > getAttributes ()
Object getAttributesRestoreData ()
void restoreAttributesTo (Object restoreData)
double getStrokeMiterLimitFactor ()
Rectangle2D.Double getDrawingArea (double factor)
boolean hasAttribute (AttributeKey<?> key)
Public Member Functions inherited from org.jhotdraw.draw.figure.AbstractFigure
AbstractFigure ()
void addFigureListener (FigureListener l)
void removeFigureListener (FigureListener l)
void addNotify (Drawing d)
void removeNotify (Drawing d)
void fireAreaInvalidated ()
void fireFigureChanged ()
Cursor getCursor (Point2D.Double p)
final void setBounds (Rectangle2D.Double bounds)
void willChange ()
void changed ()
Connector findConnector (Point2D.Double p, ConnectionFigure prototype)
boolean includes (Figure figure)
Figure findFigureInside (Point2D.Double p)
Connector findCompatibleConnector (Connector c, boolean isStart)
Collection< Action > getActions (Point2D.Double p)
boolean handleMouseClick (Point2D.Double p, MouseEvent evt, DrawingView view)
boolean handleDrop (Point2D.Double p, Collection< Figure > droppedFigures, DrawingView view)
Point2D.Double getEndPoint ()
Point2D.Double getStartPoint ()
boolean isConnectable ()
void setConnectable (boolean newValue)
boolean isSelectable ()
void setSelectable (boolean newValue)
boolean isRemovable ()
void setRemovable (boolean newValue)
boolean isTransformable ()
void setTransformable (boolean newValue)
boolean isVisible ()
void setVisible (boolean newValue)
Collection< Figure > getDecomposition ()
void requestRemove ()
int getLayer ()
String getToolTipText (Point2D.Double p)
String toString ()
Collection< Connector > getConnectors (ConnectionFigure prototype)
Public Member Functions inherited from org.jhotdraw.draw.figure.Figure
void addPropertyChangeListener (PropertyChangeListener listener)
void removePropertyChangeListener (PropertyChangeListener listener)
Additional Inherited Members
Static Public Attributes inherited from org.jhotdraw.draw.figure.Figure
static final String CONNECTABLE_PROPERTY = "connectable"
static final String REMOVABLE_PROPERTY = "removable"
static final String SELECTABLE_PROPERTY = "selectable"
static final String TRANSFORMABLE_PROPERTY = "transformable"
Protected Member Functions inherited from org.jhotdraw.draw.figure.TextFigure
void drawStroke (java.awt.Graphics2D g)
void drawFill (java.awt.Graphics2D g)
void drawText (java.awt.Graphics2D g)
TextLayout getTextLayout ()
Rectangle2D.Double getFigureDrawingArea ()
void validate ()
Protected Member Functions inherited from org.jhotdraw.draw.figure.AbstractAttributedDecoratedFigure
void drawFigure (Graphics2D g)
void drawDecorator (Graphics2D g)
void updateDecoratorBounds ()
void writeDecorator (DOMOutput out) throws IOException
void readDecorator (DOMInput in) throws IOException
Protected Member Functions inherited from org.jhotdraw.draw.figure.AbstractAttributedFigure
void writeAttributes (DOMOutput out) throws IOException
void readAttributes (DOMInput in) throws IOException
AttributeKey<?> getAttributeKey (String name)
void applyAttributesTo (Figure that)
Protected Member Functions inherited from org.jhotdraw.draw.figure.AbstractFigure
Drawing getDrawing ()
Object getLock ()
void fireAreaInvalidated (Rectangle2D.Double invalidatedArea)
void fireAreaInvalidated (FigureEvent event)
void fireFigureRequestRemove ()
void fireFigureAdded ()
void fireFigureRemoved ()
void fireFigureChanged (Rectangle2D.Double changedArea)
void fireFigureChanged (FigureEvent event)
void fireFigureHandlesChanged ()
void fireUndoableEditHappened (UndoableEdit edit)
boolean isChanging ()
int getChangingDepth ()
FontRenderContext getFontRenderContext ()
Protected Attributes inherited from org.jhotdraw.draw.figure.TextFigure
Point2D.Double origin = new Point2D.Double()
boolean editable = true
transient TextLayout textLayout
Protected Attributes inherited from org.jhotdraw.draw.figure.AbstractFigure
EventListenerList listenerList = new EventListenerList()
int changingDepth = 0
Detailed Description
A LabelFigure can be used to provide more double clickable area for a TextHolderFigure.
FIXME - Move FigureListener into inner class.
Author
Werner Randelshofer
Version
$Id$
Constructor & Destructor Documentation
LabelFigure() [1/2]
org.jhotdraw.draw.figure.LabelFigure.LabelFigure ()
Creates a new instance.
LabelFigure() [2/2]
org.jhotdraw.draw.figure.LabelFigure.LabelFigure (String text)
References org.jhotdraw.draw.figure.TextFigure.setEditable(), and org.jhotdraw.draw.figure.TextFigure.setText().
Member Function Documentation
areaInvalidated()
void org.jhotdraw.draw.figure.LabelFigure.areaInvalidated (FigureEvent e)
Sent when the drawing area used by the figure needs to be repainted.
Implements org.jhotdraw.draw.event.FigureListener.
attributeChanged()
void org.jhotdraw.draw.figure.LabelFigure.attributeChanged (FigureEvent e)
Sent when an attribute of the figure has changed.
Implements org.jhotdraw.draw.event.FigureListener.
figureAdded()
void org.jhotdraw.draw.figure.LabelFigure.figureAdded (FigureEvent e)
Sent when a figure was added to a drawing.
Implements org.jhotdraw.draw.event.FigureListener.
figureChanged()
void org.jhotdraw.draw.figure.LabelFigure.figureChanged (FigureEvent e)
Sent when the geometry (for example the bounds) of the figure has changed.
Implements org.jhotdraw.draw.event.FigureListener.
figureHandlesChanged()
void org.jhotdraw.draw.figure.LabelFigure.figureHandlesChanged (FigureEvent e)
Sent when handles of a Figure have been added, removed or replaced.
DrawingViews listen to this event to repopulate the Handles.
A Figure should not fire this event, if just the state or the location of Handle has changed.
Implements org.jhotdraw.draw.event.FigureListener.
figureRemoved()
void org.jhotdraw.draw.figure.LabelFigure.figureRemoved (FigureEvent e)
Sent when a figure was removed from a drawing.
Implements org.jhotdraw.draw.event.FigureListener.
References org.jhotdraw.draw.event.FigureEvent.getFigure(), and org.jhotdraw.draw.figure.Figure.removeFigureListener().
figureRequestRemove()
void org.jhotdraw.draw.figure.LabelFigure.figureRequestRemove (FigureEvent e)
Sent when the figure requests to be removed from a drawing.
Implements org.jhotdraw.draw.event.FigureListener.
getLabelFor()
TextHolderFigure org.jhotdraw.draw.figure.LabelFigure.getLabelFor ()
Sometimes we want to use a TextHolderFigure as a label for another TextHolderFigure. Returns the TextHolderFigure that should be really used.
Reimplemented from org.jhotdraw.draw.figure.TextFigure.
getTool()
Tool org.jhotdraw.draw.figure.LabelFigure.getTool (Point2D.Double p)
Returns a specialized tool for the given coordinate.
Returns null, if no specialized tool is available.
Reimplemented from org.jhotdraw.draw.figure.TextFigure.
References org.jhotdraw.draw.figure.AbstractAttributedDecoratedFigure.contains().
remap()
void org.jhotdraw.draw.figure.LabelFigure.remap (Map< Figure, Figure > oldToNew, boolean disconnectIfNotInMap)
After cloning a collection of figures, the ConnectionFigures contained in this collection still connect to the original figures instead of to the clones. Using This operation and providing a map, which maps from the original collection of figures to the new collection, connections can be remapped to the new figures.
Implements org.jhotdraw.draw.figure.Figure.
References org.jhotdraw.draw.figure.Figure.addFigureListener(), org.jhotdraw.draw.figure.Figure.get(), and org.jhotdraw.draw.figure.Figure.removeFigureListener().
setLabelFor()
void org.jhotdraw.draw.figure.LabelFigure.setLabelFor (TextHolderFigure target)
References org.jhotdraw.draw.figure.Figure.addFigureListener(), and org.jhotdraw.draw.figure.Figure.removeFigureListener().
The documentation for this class was generated from the following file:
jhotdraw-core/src/main/java/org/jhotdraw/draw/figure/LabelFigure.java