jhotdraw: org.jhotdraw.draw.event.TransformRestoreEdit Class Reference
org.jhotdraw.draw.event.TransformRestoreEdit Class Reference
Public Member Functions
TransformRestoreEdit (Figure owner, Object oldTransformRestoreData, Object newTransformRestoreData)
String getPresentationName ()
void undo () throws CannotUndoException
void redo () throws CannotRedoException
Detailed Description
An
UndoableEdit
event which can undo a lossy transform of a single Figure by restoring the figure using its transform restore data.
This object is useful for undoing lossy transformations, such as the rotation, scaling or shearing of a figure.
The transform restore data may consume a lot of memory. Undos of lossless transforms, such as translations of a figure, should use TransformEdit.
Author
Werner Randelshofer
Version
$Id$
Constructor & Destructor Documentation
TransformRestoreEdit()
org.jhotdraw.draw.event.TransformRestoreEdit.TransformRestoreEdit (Figure owner, Object oldTransformRestoreData, Object newTransformRestoreData)
Creates a new instance.
Member Function Documentation
getPresentationName()
String org.jhotdraw.draw.event.TransformRestoreEdit.getPresentationName ()
redo()
void org.jhotdraw.draw.event.TransformRestoreEdit.redo () throws CannotRedoException
References org.jhotdraw.draw.figure.Figure.changed(), org.jhotdraw.draw.figure.Figure.restoreTransformTo(), and org.jhotdraw.draw.figure.Figure.willChange().
undo()
void org.jhotdraw.draw.event.TransformRestoreEdit.undo () throws CannotUndoException
References org.jhotdraw.draw.figure.Figure.changed(), org.jhotdraw.draw.figure.Figure.restoreTransformTo(), and org.jhotdraw.draw.figure.Figure.willChange().
The documentation for this class was generated from the following file:
jhotdraw-core/src/main/java/org/jhotdraw/draw/event/TransformRestoreEdit.java