jhotdraw: org.jhotdraw.draw.tool.SelectionTool Class Reference
org.jhotdraw.draw.tool.SelectionTool Class Reference
Public Member Functions
SelectionTool ()
void setSelectBehindEnabled (boolean newValue)
boolean isSelectBehindEnabled ()
void activate (DrawingEditor editor)
void deactivate (DrawingEditor editor)
void keyPressed (KeyEvent e)
void keyReleased (KeyEvent evt)
void keyTyped (KeyEvent evt)
void mouseClicked (MouseEvent evt)
void mouseDragged (MouseEvent evt)
void mouseEntered (MouseEvent evt)
void mouseExited (MouseEvent evt)
void mouseMoved (MouseEvent evt)
void mouseReleased (MouseEvent evt)
void draw (Graphics2D g)
void mousePressed (MouseEvent evt)
void setHandleTracker (HandleTracker newValue)
void setSelectAreaTracker (SelectAreaTracker newValue)
void setDragTracker (DragTracker newValue)
boolean supportsHandleInteraction ()
Public Member Functions inherited from org.jhotdraw.draw.tool.AbstractTool
AbstractTool ()
void addUndoableEditListener (UndoableEditListener l)
void removeUndoableEditListener (UndoableEditListener l)
boolean isActive ()
void setInputMap (InputMap newValue)
InputMap getInputMap ()
void setActionMap (ActionMap newValue)
ActionMap getActionMap ()
void editDelete ()
void editCut ()
void editCopy ()
void editDuplicate ()
void editPaste ()
void addToolListener (ToolListener l)
void removeToolListener (ToolListener l)
void updateCursor (DrawingView view, Point p)
String getToolTipText (DrawingView view, MouseEvent evt)
Static Public Attributes
static final String SELECT_BEHIND_ENABLED_PROPERTY = "selectBehindEnabled"
Protected Member Functions
void setTracker (Tool newTracker)
HandleTracker getHandleTracker (Handle handle)
DragTracker getDragTracker (Figure f)
SelectAreaTracker getSelectAreaTracker ()
Protected Member Functions inherited from org.jhotdraw.draw.tool.AbstractTool
DrawingView getView ()
DrawingEditor getEditor ()
Drawing getDrawing ()
Point2D.Double viewToDrawing (Point p)
Point2D.Double constrainPoint (Point p, Figure... figure)
Point2D.Double constrainPoint (Point2D.Double p, Figure... figure)
InputMap createInputMap ()
ActionMap createActionMap ()
void fireToolStarted (DrawingView view)
void fireToolDone ()
void fireAreaInvalidated (Rectangle2D.Double r)
void fireAreaInvalidated (Rectangle invalidatedArea)
void maybeFireBoundsInvalidated (Rectangle invalidatedArea)
void fireBoundsInvalidated (Rectangle invalidatedArea)
Additional Inherited Members
Protected Attributes inherited from org.jhotdraw.draw.tool.AbstractTool
boolean isWorking
DrawingEditor editor
Point anchor = new Point()
EventListenerList listenerList = new EventListenerList()
Detailed Description
Tool to select and manipulate figures.
A selection tool is in one of three states: 1) area selection, 2) figure dragging, 3) handle manipulation. The different states are handled by different tracker objects: the DefaultSelectAreaTracker, the DefaultDragTracker and the DefaultHandleTracker.
A Figure can be selected by clicking at it. Holding the alt key or the ctrl key down, selects the Figure behind it.
Design Patterns
Strategy
The different behavior states of the selection tool are implemented by trackers.
Context: SelectionTool; State: DragTracker, HandleTracker, SelectAreaTracker.
Chain of responsibility
Mouse and keyboard events of the user occur on the drawing view, and are preprocessed by the
DragTracker
of a
SelectionTool
. In turn
DragTracker
invokes "track" methods on a
Handle
which in turn changes an aspect of a figure.
Client: SelectionTool; Handler: DragTracker, Handle.
Author
Werner Randelshofer
Version
$Id$
Constructor & Destructor Documentation
SelectionTool()
org.jhotdraw.draw.tool.SelectionTool.SelectionTool ()
Creates a new instance.
References org.jhotdraw.draw.tool.Tool.addToolListener(), and org.jhotdraw.draw.tool.SelectionTool.getSelectAreaTracker().
Member Function Documentation
activate()
void org.jhotdraw.draw.tool.SelectionTool.activate (DrawingEditor editor)
Activates the tool for the given editor. This method is called whenever the user switches to this tool.
Reimplemented from org.jhotdraw.draw.tool.AbstractTool.
References org.jhotdraw.draw.tool.Tool.activate(), and org.jhotdraw.draw.tool.AbstractTool.editor.
deactivate()
void org.jhotdraw.draw.tool.SelectionTool.deactivate (DrawingEditor editor)
Deactivates the tool. This method is called whenever the user switches to another tool.
Reimplemented from org.jhotdraw.draw.tool.AbstractTool.
References org.jhotdraw.draw.tool.Tool.deactivate(), and org.jhotdraw.draw.tool.AbstractTool.editor.
draw()
void org.jhotdraw.draw.tool.SelectionTool.draw (Graphics2D g)
Draws the tool.
Reimplemented from org.jhotdraw.draw.tool.AbstractTool.
References org.jhotdraw.draw.tool.Tool.draw().
getDragTracker()
DragTracker org.jhotdraw.draw.tool.SelectionTool.getDragTracker (Figure f) protected
Method to get a
DragTracker
which handles user interaction for dragging the specified figure.
References org.jhotdraw.draw.tool.DragTracker.setDraggedFigure().
Referenced by org.jhotdraw.draw.tool.SelectionTool.mousePressed().
getHandleTracker()
HandleTracker org.jhotdraw.draw.tool.SelectionTool.getHandleTracker (Handle handle) protected
Method to get a
HandleTracker
which handles user interaction for the specified handle.
References org.jhotdraw.draw.tool.AbstractTool.getView(), and org.jhotdraw.draw.tool.HandleTracker.setHandles().
Referenced by org.jhotdraw.draw.tool.SelectionTool.mousePressed().
getSelectAreaTracker()
SelectAreaTracker org.jhotdraw.draw.tool.SelectionTool.getSelectAreaTracker () protected
Method to get a
SelectAreaTracker
which handles user interaction for selecting an area on the drawing.
Referenced by org.jhotdraw.draw.tool.SelectionTool.mousePressed(), and org.jhotdraw.draw.tool.SelectionTool.SelectionTool().
isSelectBehindEnabled()
boolean org.jhotdraw.draw.tool.SelectionTool.isSelectBehindEnabled ()
Returns the value of the selectBehindEnabled property. This is a bound property.
Returns
The property value.
Referenced by org.jhotdraw.draw.tool.DelegationSelectionTool.handleDoubleClick().
keyPressed()
void org.jhotdraw.draw.tool.SelectionTool.keyPressed (KeyEvent evt)
The Tool uses the InputMap to determine what to do, when a key is pressed. If the corresponding value of the InputMap is a String, the ActionMap of the tool is used, to find the action to be performed. If the corresponding value of the InputMap is a ActionListener, the actionPerformed method of the ActionListener is performed.
Reimplemented from org.jhotdraw.draw.tool.AbstractTool.
References org.jhotdraw.draw.tool.AbstractTool.getView().
keyReleased()
void org.jhotdraw.draw.tool.SelectionTool.keyReleased (KeyEvent evt)
Reimplemented from org.jhotdraw.draw.tool.AbstractTool.
References org.jhotdraw.draw.tool.AbstractTool.getView().
keyTyped()
void org.jhotdraw.draw.tool.SelectionTool.keyTyped (KeyEvent evt)
Reimplemented from org.jhotdraw.draw.tool.AbstractTool.
References org.jhotdraw.draw.tool.AbstractTool.getView().
mouseClicked()
void org.jhotdraw.draw.tool.SelectionTool.mouseClicked (MouseEvent evt)
Reimplemented from org.jhotdraw.draw.tool.AbstractTool.
Reimplemented in org.jhotdraw.draw.tool.DelegationSelectionTool.
References org.jhotdraw.draw.tool.AbstractTool.getView().
mouseDragged()
void org.jhotdraw.draw.tool.SelectionTool.mouseDragged (MouseEvent evt)
Reimplemented in org.jhotdraw.draw.tool.DelegationSelectionTool.
References org.jhotdraw.draw.tool.AbstractTool.getView().
mouseEntered()
void org.jhotdraw.draw.tool.SelectionTool.mouseEntered (MouseEvent evt)
Reimplemented from org.jhotdraw.draw.tool.AbstractTool.
mouseExited()
void org.jhotdraw.draw.tool.SelectionTool.mouseExited (MouseEvent evt)
Reimplemented from org.jhotdraw.draw.tool.AbstractTool.
mouseMoved()
void org.jhotdraw.draw.tool.SelectionTool.mouseMoved (MouseEvent evt)
Reimplemented from org.jhotdraw.draw.tool.AbstractTool.
mousePressed()
void org.jhotdraw.draw.tool.SelectionTool.mousePressed (MouseEvent evt)
Reimplemented from org.jhotdraw.draw.tool.AbstractTool.
Reimplemented in org.jhotdraw.draw.tool.DelegationSelectionTool.
References org.jhotdraw.draw.tool.AbstractTool.anchor, org.jhotdraw.draw.DrawingView.clearSelection(), org.jhotdraw.draw.DrawingView.findFigure(), org.jhotdraw.draw.Drawing.findFigureBehind(), org.jhotdraw.draw.DrawingView.findHandle(), org.jhotdraw.draw.tool.SelectionTool.getDragTracker(), org.jhotdraw.draw.DrawingView.getDrawing(), org.jhotdraw.draw.tool.SelectionTool.getHandleTracker(), org.jhotdraw.draw.tool.SelectionTool.getSelectAreaTracker(), org.jhotdraw.draw.DrawingView.getSelectedFigures(), org.jhotdraw.draw.tool.AbstractTool.getView(), org.jhotdraw.draw.figure.Figure.isSelectable(), org.jhotdraw.draw.DrawingView.setHandleDetailLevel(), org.jhotdraw.draw.tool.SelectionTool.setTracker(), and org.jhotdraw.draw.DrawingView.viewToDrawing().
mouseReleased()
void org.jhotdraw.draw.tool.SelectionTool.mouseReleased (MouseEvent evt)
Reimplemented from org.jhotdraw.draw.tool.AbstractTool.
Reimplemented in org.jhotdraw.draw.tool.DelegationSelectionTool.
References org.jhotdraw.draw.tool.AbstractTool.getView().
setDragTracker()
void org.jhotdraw.draw.tool.SelectionTool.setDragTracker (DragTracker newValue)
Method to set a
DragTracker
. If you specify null, the
SelectionTool
uses the
DefaultDragTracker
.
setHandleTracker()
void org.jhotdraw.draw.tool.SelectionTool.setHandleTracker (HandleTracker newValue)
Method to set a
HandleTracker
. If you specify null, the
SelectionTool
uses the
DefaultHandleTracker
.
setSelectAreaTracker()
void org.jhotdraw.draw.tool.SelectionTool.setSelectAreaTracker (SelectAreaTracker newValue)
Method to set a
SelectAreaTracker
. If you specify null, the
SelectionTool
uses the
DefaultSelectAreaTracker
.
setSelectBehindEnabled()
void org.jhotdraw.draw.tool.SelectionTool.setSelectBehindEnabled (boolean newValue)
Sets the selectBehindEnabled property. This is a bound property.
Parameters
newValue The new value.
References org.jhotdraw.draw.tool.SelectionTool.SELECT_BEHIND_ENABLED_PROPERTY.
setTracker()
void org.jhotdraw.draw.tool.SelectionTool.setTracker (Tool newTracker) protected
References org.jhotdraw.draw.tool.Tool.activate(), org.jhotdraw.draw.tool.Tool.addToolListener(), org.jhotdraw.draw.tool.Tool.deactivate(), org.jhotdraw.draw.tool.AbstractTool.getEditor(), and org.jhotdraw.draw.tool.Tool.removeToolListener().
Referenced by org.jhotdraw.draw.tool.DelegationSelectionTool.handleDoubleClick(), and org.jhotdraw.draw.tool.SelectionTool.mousePressed().
supportsHandleInteraction()
boolean org.jhotdraw.draw.tool.SelectionTool.supportsHandleInteraction ()
Returns true, if this tool lets the user interact with handles.
Handles may draw differently, if interaction is not possible.
Returns
True, if this tool supports interaction with the handles.
Reimplemented from org.jhotdraw.draw.tool.AbstractTool.
Member Data Documentation
SELECT_BEHIND_ENABLED_PROPERTY
final String org.jhotdraw.draw.tool.SelectionTool.SELECT_BEHIND_ENABLED_PROPERTY = "selectBehindEnabled" static
Constant for the name of the selectBehindEnabled property.
Referenced by org.jhotdraw.draw.tool.SelectionTool.setSelectBehindEnabled().
The documentation for this class was generated from the following file:
jhotdraw-core/src/main/java/org/jhotdraw/draw/tool/SelectionTool.java