jhotdraw: org.jhotdraw.draw.event.AttributeChangeEdit< T > Class Template Reference
org.jhotdraw.draw.event.AttributeChangeEdit< T > Class Template Reference
Public Member Functions
AttributeChangeEdit (Figure owner, AttributeKey< T > name, T oldValue, T newValue)
String getPresentationName ()
void redo () throws CannotRedoException
void undo () throws CannotUndoException
Detailed Description
An
UndoableEdit
event which can undo a change of a Figure attribute.
Author
Werner Randelshofer
Version
$Id$
Constructor & Destructor Documentation
AttributeChangeEdit()
org.jhotdraw.draw.event.AttributeChangeEdit< T >.AttributeChangeEdit (Figure owner, AttributeKey< T > name, T oldValue, T newValue)
Creates a new instance.
Member Function Documentation
getPresentationName()
String org.jhotdraw.draw.event.AttributeChangeEdit< T >.getPresentationName ()
redo()
void org.jhotdraw.draw.event.AttributeChangeEdit< T >.redo () throws CannotRedoException
References org.jhotdraw.draw.figure.Figure.changed(), org.jhotdraw.draw.figure.Figure.set(), and org.jhotdraw.draw.figure.Figure.willChange().
undo()
void org.jhotdraw.draw.event.AttributeChangeEdit< T >.undo () throws CannotUndoException
References org.jhotdraw.draw.figure.Figure.changed(), org.jhotdraw.draw.figure.Figure.set(), and org.jhotdraw.draw.figure.Figure.willChange().
The documentation for this class was generated from the following file:
jhotdraw-core/src/main/java/org/jhotdraw/draw/event/AttributeChangeEdit.java