jhotdraw: org.jhotdraw.draw.action.MoveAction Class Reference
org.jhotdraw.draw.action.MoveAction Class Reference abstract
Classes
class East
class North
class South
class West
Public Member Functions
MoveAction (DrawingEditor editor, int dx, int dy)
void actionPerformed (java.awt.event.ActionEvent e)
Public Member Functions inherited from org.jhotdraw.draw.action.AbstractSelectedAction
AbstractSelectedAction (DrawingEditor editor)
void dispose ()
void setEditor (DrawingEditor editor)
DrawingEditor getEditor ()
void setUpdateEnabledState (boolean newValue)
boolean isUpdatEnabledState ()
Additional Inherited Members
Protected Member Functions inherited from org.jhotdraw.draw.action.AbstractSelectedAction
void updateEnabledState ()
DrawingView getView ()
Drawing getDrawing ()
void fireUndoableEditHappened (UndoableEdit edit)
Detailed Description
Moves the selected figures by one unit.
Author
Werner Randelshofer
Version
$Id$
Constructor & Destructor Documentation
MoveAction()
org.jhotdraw.draw.action.MoveAction.MoveAction (DrawingEditor editor, int dx, int dy)
Creates a new instance.
References org.jhotdraw.draw.action.AbstractSelectedAction.updateEnabledState().
Member Function Documentation
actionPerformed()
void org.jhotdraw.draw.action.MoveAction.actionPerformed (java.awt.event.ActionEvent e)
References org.jhotdraw.draw.action.AbstractSelectedAction.fireUndoableEditHappened(), and org.jhotdraw.draw.action.AbstractSelectedAction.getView().
The documentation for this class was generated from the following file:
jhotdraw-core/src/main/java/org/jhotdraw/draw/action/MoveAction.java