jhotdraw: org.jhotdraw.draw.tool.TextAreaEditingTool Class Reference
org.jhotdraw.draw.tool.TextAreaEditingTool Class Reference
Public Member Functions
TextAreaEditingTool (TextHolderFigure typingTarget)
void deactivate (DrawingEditor editor)
void mousePressed (MouseEvent e)
void draw (Graphics2D g)
void actionPerformed (ActionEvent event)
void mouseDragged (MouseEvent e)
Public Member Functions inherited from org.jhotdraw.draw.tool.AbstractTool
AbstractTool ()
void addUndoableEditListener (UndoableEditListener l)
void removeUndoableEditListener (UndoableEditListener l)
void activate (DrawingEditor editor)
boolean isActive ()
void setInputMap (InputMap newValue)
InputMap getInputMap ()
void setActionMap (ActionMap newValue)
ActionMap getActionMap ()
void editDelete ()
void editCut ()
void editCopy ()
void editDuplicate ()
void editPaste ()
void keyReleased (KeyEvent evt)
void keyTyped (KeyEvent evt)
void keyPressed (KeyEvent evt)
void mouseClicked (MouseEvent evt)
void mouseEntered (MouseEvent evt)
void mouseExited (MouseEvent evt)
void mouseMoved (MouseEvent evt)
void mouseReleased (MouseEvent evt)
void addToolListener (ToolListener l)
void removeToolListener (ToolListener l)
void updateCursor (DrawingView view, Point p)
String getToolTipText (DrawingView view, MouseEvent evt)
boolean supportsHandleInteraction ()
Protected Member Functions
void beginEdit (TextHolderFigure textHolder)
void endEdit ()
Protected Member Functions inherited from org.jhotdraw.draw.tool.AbstractTool
DrawingView getView ()
DrawingEditor getEditor ()
Drawing getDrawing ()
Point2D.Double viewToDrawing (Point p)
Point2D.Double constrainPoint (Point p, Figure... figure)
Point2D.Double constrainPoint (Point2D.Double p, Figure... figure)
InputMap createInputMap ()
ActionMap createActionMap ()
void fireToolStarted (DrawingView view)
void fireToolDone ()
void fireAreaInvalidated (Rectangle2D.Double r)
void fireAreaInvalidated (Rectangle invalidatedArea)
void maybeFireBoundsInvalidated (Rectangle invalidatedArea)
void fireBoundsInvalidated (Rectangle invalidatedArea)
Additional Inherited Members
Protected Attributes inherited from org.jhotdraw.draw.tool.AbstractTool
boolean isWorking
DrawingEditor editor
Point anchor = new Point()
EventListenerList listenerList = new EventListenerList()
Detailed Description
A tool to edit existing figures that implement the TextHolderFigure interface, such as TextAreaFigure.
To edit an existing text figure using the TextAreaEditingTool, the user does the following mouse gesture on a DrawingView:
Press the mouse button over a Figure on the DrawingView.
The TextAreaEditingTool then uses Figure.findFigureInside to find a Figure that implements the TextHolderFigure interface and that is editable. Then it overlays a text area over the drawing where the user can enter the text for the Figure.
Design Patterns
Framework
The text creation and editing tools and the
TextHolderFigure
interface define together the contracts of a smaller framework inside of the JHotDraw framework for structured drawing editors.
Contract: TextHolderFigure, TextCreationTool, TextAreaCreationTool, TextEditingTool, TextAreaEditingTool, FloatingTextField, FloatingTextArea.
Author
Werner Randelshofer
Version
$Id$
See also
TextHolderFigure
FloatingTextArea
Constructor & Destructor Documentation
TextAreaEditingTool()
org.jhotdraw.draw.tool.TextAreaEditingTool.TextAreaEditingTool (TextHolderFigure typingTarget)
Creates a new instance.
Member Function Documentation
actionPerformed()
void org.jhotdraw.draw.tool.TextAreaEditingTool.actionPerformed (ActionEvent event)
References org.jhotdraw.draw.tool.TextAreaEditingTool.endEdit(), and org.jhotdraw.draw.tool.AbstractTool.fireToolDone().
beginEdit()
void org.jhotdraw.draw.tool.TextAreaEditingTool.beginEdit (TextHolderFigure textHolder) protected
References org.jhotdraw.draw.text.FloatingTextArea.createOverlay(), org.jhotdraw.draw.tool.TextAreaEditingTool.endEdit(), org.jhotdraw.draw.figure.TextHolderFigure.getText(), org.jhotdraw.draw.tool.AbstractTool.getView(), org.jhotdraw.draw.text.FloatingTextArea.requestFocus(), and org.jhotdraw.draw.text.FloatingTextArea.setBounds().
Referenced by org.jhotdraw.draw.tool.TextAreaEditingTool.mousePressed().
deactivate()
void org.jhotdraw.draw.tool.TextAreaEditingTool.deactivate (DrawingEditor editor)
Deactivates the tool. This method is called whenever the user switches to another tool.
Reimplemented from org.jhotdraw.draw.tool.AbstractTool.
References org.jhotdraw.draw.tool.AbstractTool.editor, and org.jhotdraw.draw.tool.TextAreaEditingTool.endEdit().
draw()
void org.jhotdraw.draw.tool.TextAreaEditingTool.draw (Graphics2D g)
Draws the tool.
Reimplemented from org.jhotdraw.draw.tool.AbstractTool.
endEdit()
void org.jhotdraw.draw.tool.TextAreaEditingTool.endEdit () protected
References org.jhotdraw.draw.figure.Figure.changed(), org.jhotdraw.draw.text.FloatingTextArea.endOverlay(), org.jhotdraw.draw.Drawing.fireUndoableEditHappened(), org.jhotdraw.draw.tool.AbstractTool.getDrawing(), org.jhotdraw.draw.figure.TextHolderFigure.getText(), org.jhotdraw.draw.text.FloatingTextArea.getText(), org.jhotdraw.draw.figure.TextHolderFigure.setText(), and org.jhotdraw.draw.figure.Figure.willChange().
Referenced by org.jhotdraw.draw.tool.TextAreaEditingTool.actionPerformed(), org.jhotdraw.draw.tool.TextAreaEditingTool.beginEdit(), and org.jhotdraw.draw.tool.TextAreaEditingTool.deactivate().
mouseDragged()
void org.jhotdraw.draw.tool.TextAreaEditingTool.mouseDragged (MouseEvent e)
mousePressed()
void org.jhotdraw.draw.tool.TextAreaEditingTool.mousePressed (MouseEvent e)
Creates a new figure at the mouse location. If editing is in progress, this finishes editing.
Reimplemented from org.jhotdraw.draw.tool.AbstractTool.
References org.jhotdraw.draw.tool.TextAreaEditingTool.beginEdit(), org.jhotdraw.draw.tool.AbstractTool.getView(), and org.jhotdraw.draw.tool.AbstractTool.updateCursor().
The documentation for this class was generated from the following file:
jhotdraw-core/src/main/java/org/jhotdraw/draw/tool/TextAreaEditingTool.java