jhotdraw: org.jhotdraw.draw.io.SerializationInputOutputFormat Class Reference
org.jhotdraw.draw.io.SerializationInputOutputFormat Class Reference
Public Member Functions
SerializationInputOutputFormat ()
SerializationInputOutputFormat (String description, String fileExtension, Drawing prototype)
FileFilter getFileFilter ()
JComponent getInputFormatAccessory ()
void read (URI uri, Drawing drawing) throws IOException
void read (URI uri, Drawing drawing, boolean replace) throws IOException
void read (File file, Drawing drawing) throws IOException
void read (File file, Drawing drawing, boolean replace) throws IOException
void read (InputStream in, Drawing drawing, boolean replace) throws IOException
boolean isDataFlavorSupported (DataFlavor flavor)
void read (Transferable t, Drawing drawing, boolean replace) throws UnsupportedFlavorException, IOException
String getFileExtension ()
JComponent getOutputFormatAccessory ()
void write (URI uri, Drawing drawing) throws IOException
void write (File file, Drawing drawing) throws IOException
void write (OutputStream out, Drawing drawing) throws IOException
Transferable createTransferable (Drawing drawing, List< Figure > figures, double scaleFactor) throws IOException
Detailed Description
SerializationInputOutputFormat
uses Java Serialization for reading and and writing
Drawing
objects.
Author
Werner Randelshofer
Version
$Id$
Constructor & Destructor Documentation
SerializationInputOutputFormat() [1/2]
org.jhotdraw.draw.io.SerializationInputOutputFormat.SerializationInputOutputFormat ()
Creates a new instance with format name "Drawing", file extension "xml" and mime type "image/x-jhotdraw".
SerializationInputOutputFormat() [2/2]
org.jhotdraw.draw.io.SerializationInputOutputFormat.SerializationInputOutputFormat (String description, String fileExtension, Drawing prototype)
Creates a new instance using the specified parameters.
Member Function Documentation
createTransferable()
Transferable org.jhotdraw.draw.io.SerializationInputOutputFormat.createTransferable (Drawing drawing, List< Figure > figures, double scaleFactor) throws IOException
Creates a Transferable for the specified list of Figures.
Parameters
drawing The drawing.
figures A list of figures of the drawing.
scaleFactor The factor to be used, when the Transferable creates an image with a fixed size from the figures.
Returns
The Transferable.
Implements org.jhotdraw.draw.io.OutputFormat.
References org.jhotdraw.draw.Drawing.add(), org.jhotdraw.draw.figure.Figure.clone(), and org.jhotdraw.draw.io.SerializationInputOutputFormat.isDataFlavorSupported().
getFileExtension()
String org.jhotdraw.draw.io.SerializationInputOutputFormat.getFileExtension ()
Returns the file extension for the output format. The file extension should be appended to a file name when storing a Drawing with the specified file format.
Implements org.jhotdraw.draw.io.OutputFormat.
getFileFilter()
FileFilter org.jhotdraw.draw.io.SerializationInputOutputFormat.getFileFilter ()
Return a FileFilter that can be used to identify files which can be read with this input format. Typically, each input format has its own recognizable file naming convention.
Returns
FileFilter to be used with a javax.swing.JFileChooser
Implements org.jhotdraw.draw.io.InputFormat.
getInputFormatAccessory()
JComponent org.jhotdraw.draw.io.SerializationInputOutputFormat.getInputFormatAccessory ()
Return a JFileChooser accessory that can be used to customize the input format.
Returns
A JFileChooser accessory to be used with a javax.swing.JFileChooser Returns null, if no accessory is provided for this format.
Implements org.jhotdraw.draw.io.InputFormat.
getOutputFormatAccessory()
JComponent org.jhotdraw.draw.io.SerializationInputOutputFormat.getOutputFormatAccessory ()
Return a JFileChooser accessory that can be used to customize the output format.
Returns
A JFileChooser accessory to be used with a javax.swing.JFileChooser Returns null, if no accessory is provided for this format.
Implements org.jhotdraw.draw.io.OutputFormat.
isDataFlavorSupported()
boolean org.jhotdraw.draw.io.SerializationInputOutputFormat.isDataFlavorSupported (DataFlavor flavor)
Returns true, if this InputFormat can readFigures TransferData using the specified DataFlavor.
Parameters
flavor A DataFlavor.
Implements org.jhotdraw.draw.io.InputFormat.
Referenced by org.jhotdraw.draw.io.SerializationInputOutputFormat.createTransferable().
read() [1/6]
void org.jhotdraw.draw.io.SerializationInputOutputFormat.read (File file, Drawing drawing) throws IOException
References org.jhotdraw.draw.io.SerializationInputOutputFormat.read().
read() [2/6]
void org.jhotdraw.draw.io.SerializationInputOutputFormat.read (File file, Drawing drawing, boolean replace) throws IOException
References org.jhotdraw.draw.io.SerializationInputOutputFormat.read().
read() [3/6]
void org.jhotdraw.draw.io.SerializationInputOutputFormat.read (InputStream in, Drawing drawing, boolean replace) throws IOException
Reads figures from a file and adds them to the specified drawing.
Parameters
in The input stream.
drawing The drawing.
replace Set this to true, if the contents of the stream replaces the contents of the drawing (for example, when loading a drawing from a stream). Set this to false, to add the contents of the file to the drawing (for example, when the stream has been dropped into the drawing view).
Implements org.jhotdraw.draw.io.InputFormat.
References org.jhotdraw.draw.figure.Figure.getAttributes(), org.jhotdraw.draw.figure.CompositeFigure.getChildren(), and org.jhotdraw.draw.figure.Figure.set().
read() [4/6]
void org.jhotdraw.draw.io.SerializationInputOutputFormat.read (Transferable t, Drawing drawing, boolean replace) throws UnsupportedFlavorException, IOException
Reads figures from the specified Transferable and adds them to the specified drawing.
Parameters
t The Transferable.
drawing The drawing.
replace Set this to true, if the contents of the transferable replaces the contents of the drawing (for example, when loading a drawing from a transferable). Set this to false, to add the contents of the transferable to the drawing (for example, when the transferable has been dropped or pasted into the drawing view).
Implements org.jhotdraw.draw.io.InputFormat.
References org.jhotdraw.draw.figure.Figure.getAttributes(), org.jhotdraw.draw.figure.CompositeFigure.getChildren(), and org.jhotdraw.draw.figure.Figure.set().
read() [5/6]
void org.jhotdraw.draw.io.SerializationInputOutputFormat.read (URI uri, Drawing drawing) throws IOException
Reads figures from an URI and replaces the children of the drawing with them.
This is a convenience method for calling read(URI,Drawing,true).
Parameters
uri The URI.
drawing The drawing.
Implements org.jhotdraw.draw.io.InputFormat.
Referenced by org.jhotdraw.draw.io.SerializationInputOutputFormat.read().
read() [6/6]
void org.jhotdraw.draw.io.SerializationInputOutputFormat.read (URI uri, Drawing drawing, boolean replace) throws IOException
Reads figures from an URI and adds them to the specified drawing.
Parameters
uri The URI.
drawing The drawing.
replace Set this to true, if the contents of the file replaces the contents of the drawing (for example, when loading a drawing from a file). Set this to false, to add the contents of the file to the drawing (for example, when the file has been dropped into the drawing view).
Implements org.jhotdraw.draw.io.InputFormat.
References org.jhotdraw.draw.io.SerializationInputOutputFormat.read().
write() [1/3]
void org.jhotdraw.draw.io.SerializationInputOutputFormat.write (File file, Drawing drawing) throws IOException
References org.jhotdraw.draw.io.SerializationInputOutputFormat.write().
write() [2/3]
void org.jhotdraw.draw.io.SerializationInputOutputFormat.write (OutputStream out, Drawing drawing) throws IOException
Writes a Drawing into an output stream.
Parameters
out The output stream.
drawing The drawing.
Implements org.jhotdraw.draw.io.OutputFormat.
write() [3/3]
void org.jhotdraw.draw.io.SerializationInputOutputFormat.write (URI uri, Drawing drawing) throws IOException
Writes a Drawing into an URI.
Parameters
uri The uri.
drawing The drawing.
Implements org.jhotdraw.draw.io.OutputFormat.
Referenced by org.jhotdraw.draw.io.SerializationInputOutputFormat.write().
The documentation for this class was generated from the following file:
jhotdraw-core/src/main/java/org/jhotdraw/draw/io/SerializationInputOutputFormat.java