jhotdraw: org.jhotdraw.draw.GridConstrainer Class Reference
org.jhotdraw.draw.GridConstrainer Class Reference
Public Member Functions
GridConstrainer ()
GridConstrainer (double width, double height)
GridConstrainer (double width, double height, boolean visible)
GridConstrainer (double width, double height, double theta, boolean visible)
double getWidth ()
double getHeight ()
double getTheta ()
void setWidth (double newValue)
void setHeight (double newValue)
void setTheta (double newValue)
Point2D.Double constrainPoint (Point2D.Double p, Figure... figure)
Point2D.Double translatePoint (Point2D.Double p, TranslationDirection dir, Figure... figure)
Rectangle2D.Double constrainRectangle (Rectangle2D.Double r, Figure... figure)
Rectangle2D.Double translateRectangle (Rectangle2D.Double r, TranslationDirection dir, Figure... figure)
String toString ()
boolean isVisible ()
void setVisible (boolean newValue)
int getMajorGridSpacing ()
void setMajorGridSpacing (int newValue)
void draw (Graphics2D g, DrawingView view)
double constrainAngle (double angle, Figure... figure)
double rotateAngle (double angle, RotationDirection dir, Figure... figure)
Public Member Functions inherited from org.jhotdraw.draw.AbstractConstrainer
AbstractConstrainer ()
void addChangeListener (ChangeListener l)
void removeChangeListener (ChangeListener l)
AbstractConstrainer clone ()
Protected Member Functions
Point2D.Double constrainPoint (Point2D.Double p, TranslationDirection dir, Figure... figure)
Rectangle2D.Double constrainRectangle (Rectangle2D.Double r, TranslationDirection dir, Figure... figure)
Protected Member Functions inherited from org.jhotdraw.draw.AbstractConstrainer
void fireStateChanged ()
Additional Inherited Members
Protected Attributes inherited from org.jhotdraw.draw.AbstractConstrainer
EventListenerList listenerList = new EventListenerList()
transient ChangeEvent changeEvent = null
Detailed Description
Constrains a point such that it falls on a grid.
Author
Werner Randelshofer
Version
$Id$
Constructor & Destructor Documentation
GridConstrainer() [1/4]
org.jhotdraw.draw.GridConstrainer.GridConstrainer ()
Creates a new instance with a grid of 1x1.
GridConstrainer() [2/4]
org.jhotdraw.draw.GridConstrainer.GridConstrainer (double width, double height)
Creates a new instance with the specified grid size, and by 11.25° (in degrees) for rotations. The grid is visible.
Parameters
width The width of a grid cell.
height The height of a grid cell.
GridConstrainer() [3/4]
org.jhotdraw.draw.GridConstrainer.GridConstrainer (double width, double height, boolean visible)
Creates a new instance with the specified grid size. and by 11.25° (in degrees) for rotations.
Parameters
width The width of a grid cell.
height The height of a grid cell.
visible Wether the grid is visible or not.
GridConstrainer() [4/4]
org.jhotdraw.draw.GridConstrainer.GridConstrainer (double width, double height, double theta, boolean visible)
Creates a new instance with the specified grid size.
Parameters
width The width of a grid cell.
height The height of a grid cell.
theta The theta for rotations in radians.
visible Wether the grid is visible or not.
Member Function Documentation
constrainAngle()
double org.jhotdraw.draw.GridConstrainer.constrainAngle (double angle, Figure... figures)
Constrains the given angle (in radians). This method changes the angle which is passed as a parameter.
Parameters
angle The angle (in radians).
Returns
The closest constrained angle (in radians).
Implements org.jhotdraw.draw.Constrainer.
Referenced by org.jhotdraw.draw.GridConstrainer.rotateAngle().
constrainPoint() [1/2]
Point2D.Double org.jhotdraw.draw.GridConstrainer.constrainPoint (Point2D.Double p, Figure... figure)
Constrains a point to the closest grid point in any direction.
Implements org.jhotdraw.draw.Constrainer.
Referenced by org.jhotdraw.draw.GridConstrainer.constrainPoint(), org.jhotdraw.draw.GridConstrainer.constrainRectangle(), org.jhotdraw.draw.GridConstrainer.draw(), and org.jhotdraw.draw.GridConstrainer.translatePoint().
constrainPoint() [2/2]
Point2D.Double org.jhotdraw.draw.GridConstrainer.constrainPoint (Point2D.Double p, TranslationDirection dir, Figure... figure) protected
Constrains the placement of a point towards a direction.
This method changes the point which is passed as a parameter.
Parameters
p A point on the drawing.
dir A direction.
Returns
Returns the constrained point.
References org.jhotdraw.draw.GridConstrainer.constrainPoint().
constrainRectangle() [1/2]
Rectangle2D.Double org.jhotdraw.draw.GridConstrainer.constrainRectangle (Rectangle2D.Double r, Figure... figures)
Constrains the placement of a rectangle towards the closest constrainment in any direction.
This method changes the location of the rectangle which is passed as a parameter. This method does not change the size of the rectangle.
Parameters
r A rectangle on the drawing.
Returns
Returns the constrained rectangle.
Implements org.jhotdraw.draw.Constrainer.
References org.jhotdraw.draw.GridConstrainer.constrainPoint().
Referenced by org.jhotdraw.draw.GridConstrainer.translateRectangle().
constrainRectangle() [2/2]
Rectangle2D.Double org.jhotdraw.draw.GridConstrainer.constrainRectangle (Rectangle2D.Double r, TranslationDirection dir, Figure... figure) protected
Constrains the placement of a rectangle towards a direction.
This method changes the location of the rectangle which is passed as a parameter. This method does not change the size of the rectangle.
Parameters
r A rectangle on the drawing.
dir A direction.
Returns
Returns the constrained rectangle.
References org.jhotdraw.draw.GridConstrainer.constrainPoint().
draw()
void org.jhotdraw.draw.GridConstrainer.draw (Graphics2D g, DrawingView view)
Draws the constrainer grid for the specified drawing view.
Implements org.jhotdraw.draw.Constrainer.
References org.jhotdraw.draw.GridConstrainer.constrainPoint(), org.jhotdraw.draw.DrawingView.getDrawingToViewTransform(), org.jhotdraw.draw.DrawingView.getScaleFactor(), and org.jhotdraw.draw.DrawingView.viewToDrawing().
getHeight()
double org.jhotdraw.draw.GridConstrainer.getHeight ()
getMajorGridSpacing()
int org.jhotdraw.draw.GridConstrainer.getMajorGridSpacing ()
Spacing between major grid lines.
getTheta()
double org.jhotdraw.draw.GridConstrainer.getTheta ()
getWidth()
double org.jhotdraw.draw.GridConstrainer.getWidth ()
isVisible()
boolean org.jhotdraw.draw.GridConstrainer.isVisible ()
rotateAngle()
double org.jhotdraw.draw.GridConstrainer.rotateAngle (double angle, RotationDirection dir, Figure... figures)
Moves the given angle (in radians) to the closest constrained orientation in the specified direction.
Parameters
angle The angle (in radians).
Returns
The closest constrained angle (in radians) in the specified direction.
Implements org.jhotdraw.draw.Constrainer.
References org.jhotdraw.draw.GridConstrainer.constrainAngle().
setHeight()
void org.jhotdraw.draw.GridConstrainer.setHeight (double newValue)
References org.jhotdraw.draw.AbstractConstrainer.fireStateChanged().
setMajorGridSpacing()
void org.jhotdraw.draw.GridConstrainer.setMajorGridSpacing (int newValue)
Spacing between major grid lines.
References org.jhotdraw.draw.AbstractConstrainer.fireStateChanged().
setTheta()
void org.jhotdraw.draw.GridConstrainer.setTheta (double newValue)
References org.jhotdraw.draw.AbstractConstrainer.fireStateChanged().
setVisible()
void org.jhotdraw.draw.GridConstrainer.setVisible (boolean newValue)
References org.jhotdraw.draw.AbstractConstrainer.fireStateChanged().
setWidth()
void org.jhotdraw.draw.GridConstrainer.setWidth (double newValue)
References org.jhotdraw.draw.AbstractConstrainer.fireStateChanged().
toString()
String org.jhotdraw.draw.GridConstrainer.toString ()
translatePoint()
Point2D.Double org.jhotdraw.draw.GridConstrainer.translatePoint (Point2D.Double p, TranslationDirection dir, Figure... figure)
Moves a point to the closest grid point in a direction.
Implements org.jhotdraw.draw.Constrainer.
References org.jhotdraw.draw.GridConstrainer.constrainPoint().
translateRectangle()
Rectangle2D.Double org.jhotdraw.draw.GridConstrainer.translateRectangle (Rectangle2D.Double r, TranslationDirection dir, Figure... figures)
Moves a rectangle to the closest constrained location in the specified direction.
This method changes the location of the rectangle which is passed as a parameter. This method only performs a translation - it does not change the size of the rectangle.
Parameters
r A rectangle on the drawing.
dir A direction.
Returns
Returns the constrained rectangle.
Implements org.jhotdraw.draw.Constrainer.
References org.jhotdraw.draw.GridConstrainer.constrainRectangle().
The documentation for this class was generated from the following file:
jhotdraw-core/src/main/java/org/jhotdraw/draw/GridConstrainer.java