jhotdraw: org.jhotdraw.draw.action.DrawingColorChooserAction Class Reference
org.jhotdraw.draw.action.DrawingColorChooserAction Class Reference
Public Member Functions
DrawingColorChooserAction (DrawingEditor editor, AttributeKey< Color > key)
DrawingColorChooserAction (DrawingEditor editor, AttributeKey< Color > key, Icon icon)
DrawingColorChooserAction (DrawingEditor editor, AttributeKey< Color > key, String name)
DrawingColorChooserAction (DrawingEditor editor, final AttributeKey< Color > key, String name, Icon icon)
DrawingColorChooserAction (DrawingEditor editor, final AttributeKey< Color > key, String name, Icon icon, Map< AttributeKey<?>, Object > fixedAttributes)
void actionPerformed (java.awt.event.ActionEvent e)
Public Member Functions inherited from org.jhotdraw.draw.action.EditorColorChooserAction
EditorColorChooserAction (DrawingEditor editor, AttributeKey< Color > key)
EditorColorChooserAction (DrawingEditor editor, AttributeKey< Color > key, Icon icon)
EditorColorChooserAction (DrawingEditor editor, AttributeKey< Color > key, String name)
EditorColorChooserAction (DrawingEditor editor, final AttributeKey< Color > key, String name, Icon icon)
EditorColorChooserAction (DrawingEditor editor, final AttributeKey< Color > key, String name, Icon icon, Map< AttributeKey<?>, Object > fixedAttributes)
void selectionChanged (FigureSelectionEvent evt)
Public Member Functions inherited from org.jhotdraw.draw.action.AttributeAction
AttributeAction (DrawingEditor editor, Map< AttributeKey<?>, Object > attributes, String name, Icon icon)
void applyAttributesTo (final Map< AttributeKey<?>, Object > a, Set< Figure > figures)
Public Member Functions inherited from org.jhotdraw.draw.action.AbstractSelectedAction
AbstractSelectedAction (DrawingEditor editor)
void dispose ()
void setEditor (DrawingEditor editor)
DrawingEditor getEditor ()
void setUpdateEnabledState (boolean newValue)
boolean isUpdatEnabledState ()
Protected Member Functions
Color getInitialColor ()
void updateEnabledState ()
Protected Member Functions inherited from org.jhotdraw.draw.action.AbstractSelectedAction
DrawingView getView ()
Drawing getDrawing ()
void fireUndoableEditHappened (UndoableEdit edit)
Additional Inherited Members
Protected Attributes inherited from org.jhotdraw.draw.action.EditorColorChooserAction
AttributeKey< Color > key
Protected Attributes inherited from org.jhotdraw.draw.action.AttributeAction
Map< AttributeKey<?>, Object > attributes
Static Protected Attributes inherited from org.jhotdraw.draw.action.EditorColorChooserAction
static JColorChooser colorChooser
Detailed Description
The DrawingColorChooserAction changes a color attribute of the Drawing object in the current view of the DrawingEditor.
The behavior for choosing the initial color of the JColorChooser matches with DrawingColorIcon.
Author
Werner Randelshofer
Version
$Id$
Constructor & Destructor Documentation
DrawingColorChooserAction() [1/5]
org.jhotdraw.draw.action.DrawingColorChooserAction.DrawingColorChooserAction (DrawingEditor editor, AttributeKey< Color > key)
Creates a new instance.
References org.jhotdraw.draw.action.EditorColorChooserAction.key.
DrawingColorChooserAction() [2/5]
org.jhotdraw.draw.action.DrawingColorChooserAction.DrawingColorChooserAction (DrawingEditor editor, AttributeKey< Color > key, Icon icon)
Creates a new instance.
References org.jhotdraw.draw.action.EditorColorChooserAction.key.
DrawingColorChooserAction() [3/5]
org.jhotdraw.draw.action.DrawingColorChooserAction.DrawingColorChooserAction (DrawingEditor editor, AttributeKey< Color > key, String name)
Creates a new instance.
References org.jhotdraw.draw.action.EditorColorChooserAction.key.
DrawingColorChooserAction() [4/5]
org.jhotdraw.draw.action.DrawingColorChooserAction.DrawingColorChooserAction (DrawingEditor editor, final AttributeKey< Color > key, String name, Icon icon)
References org.jhotdraw.draw.action.EditorColorChooserAction.key.
DrawingColorChooserAction() [5/5]
org.jhotdraw.draw.action.DrawingColorChooserAction.DrawingColorChooserAction (DrawingEditor editor, final AttributeKey< Color > key, String name, Icon icon, Map< AttributeKey<?>, Object > fixedAttributes)
References org.jhotdraw.draw.action.EditorColorChooserAction.key.
Member Function Documentation
actionPerformed()
void org.jhotdraw.draw.action.DrawingColorChooserAction.actionPerformed (java.awt.event.ActionEvent e)
Reimplemented from org.jhotdraw.draw.action.EditorColorChooserAction.
References org.jhotdraw.draw.action.AttributeAction.applyAttributesTo(), org.jhotdraw.draw.action.AttributeAction.attributes, org.jhotdraw.draw.action.EditorColorChooserAction.colorChooser, org.jhotdraw.draw.action.AbstractSelectedAction.getDrawing(), org.jhotdraw.draw.action.DrawingColorChooserAction.getInitialColor(), org.jhotdraw.draw.action.AbstractSelectedAction.getView(), and org.jhotdraw.draw.action.EditorColorChooserAction.key.
getInitialColor()
Color org.jhotdraw.draw.action.DrawingColorChooserAction.getInitialColor () protected
Reimplemented from org.jhotdraw.draw.action.EditorColorChooserAction.
References org.jhotdraw.draw.figure.Figure.get(), org.jhotdraw.draw.DrawingEditor.getActiveView(), org.jhotdraw.draw.DrawingView.getDrawing(), org.jhotdraw.draw.action.AbstractSelectedAction.getEditor(), and org.jhotdraw.draw.action.EditorColorChooserAction.key.
Referenced by org.jhotdraw.draw.action.DrawingColorChooserAction.actionPerformed().
updateEnabledState()
void org.jhotdraw.draw.action.DrawingColorChooserAction.updateEnabledState () protected
Updates the enabled state of this action to reflect the enabled state of the active
DrawingView
. If no drawing view is active, this action is disabled.
Reimplemented from org.jhotdraw.draw.action.AttributeAction.
References org.jhotdraw.draw.action.AbstractSelectedAction.getView().
The documentation for this class was generated from the following file:
jhotdraw-core/src/main/java/org/jhotdraw/draw/action/DrawingColorChooserAction.java