jhotdraw: org.jhotdraw.draw.event.TransformEdit Class Reference
org.jhotdraw.draw.event.TransformEdit Class Reference
Public Member Functions
TransformEdit (Figure figure, AffineTransform tx)
TransformEdit (Collection< Figure > figures, AffineTransform tx)
String getPresentationName ()
boolean addEdit (UndoableEdit anEdit)
boolean replaceEdit (UndoableEdit anEdit)
void redo () throws CannotRedoException
void undo () throws CannotUndoException
String toString ()
Detailed Description
An
UndoableEdit
event which can undo a lossless transform of Figures by applying the inverse of the transform to the figures.
This object is useful for undoing lossless transformations, such as the translation of figures.
If a lossy transforms is performed, such as rotation, scaling or shearing, then undos should be performed with TransformRestoreEdit instead.
Author
Werner Randelshofer
Version
$Id$
Constructor & Destructor Documentation
TransformEdit() [1/2]
org.jhotdraw.draw.event.TransformEdit.TransformEdit (Figure figure, AffineTransform tx)
Creates a new instance.
Referenced by org.jhotdraw.draw.event.TransformEdit.addEdit(), and org.jhotdraw.draw.event.TransformEdit.replaceEdit().
TransformEdit() [2/2]
org.jhotdraw.draw.event.TransformEdit.TransformEdit (Collection< Figure > figures, AffineTransform tx)
Member Function Documentation
addEdit()
boolean org.jhotdraw.draw.event.TransformEdit.addEdit (UndoableEdit anEdit)
References org.jhotdraw.draw.event.TransformEdit.TransformEdit().
getPresentationName()
String org.jhotdraw.draw.event.TransformEdit.getPresentationName ()
redo()
void org.jhotdraw.draw.event.TransformEdit.redo () throws CannotRedoException
replaceEdit()
boolean org.jhotdraw.draw.event.TransformEdit.replaceEdit (UndoableEdit anEdit)
References org.jhotdraw.draw.event.TransformEdit.TransformEdit().
toString()
String org.jhotdraw.draw.event.TransformEdit.toString ()
undo()
void org.jhotdraw.draw.event.TransformEdit.undo () throws CannotUndoException
The documentation for this class was generated from the following file:
jhotdraw-core/src/main/java/org/jhotdraw/draw/event/TransformEdit.java