jhotdraw: org.jhotdraw.draw.handle.TextOverflowHandle Class Reference
org.jhotdraw.draw.handle.TextOverflowHandle Class Reference
Public Member Functions
TextOverflowHandle (TextHolderFigure owner)
TextHolderFigure getOwner ()
boolean contains (Point p)
void draw (Graphics2D g)
void trackStart (Point anchor, int modifiersEx)
void trackStep (Point anchor, Point lead, int modifiersEx)
void trackEnd (Point anchor, Point lead, int modifiersEx)
String getToolTipText (Point p)
Public Member Functions inherited from org.jhotdraw.draw.handle.AbstractHandle
AbstractHandle (Figure owner)
void addHandleListener (HandleListener l)
void removeHandleListener (HandleListener l)
void setView (DrawingView view)
DrawingView getView ()
DrawingEditor getEditor ()
void invalidate ()
void dispose ()
void areaInvalidated (FigureEvent evt)
void figureAdded (FigureEvent e)
void figureRemoved (FigureEvent e)
void figureRequestRemove (FigureEvent e)
void figureChanged (FigureEvent evt)
Cursor getCursor ()
boolean isCombinableWith (Handle handle)
void keyTyped (KeyEvent evt)
void keyReleased (KeyEvent evt)
void keyPressed (KeyEvent evt)
final Rectangle getBounds ()
Rectangle getDrawingArea ()
void trackDoubleClick (Point p, int modifiersEx)
void attributeChanged (FigureEvent e)
void viewTransformChanged ()
Collection< Handle > createSecondaryHandles ()
void setToolTipText (String newValue)
void figureHandlesChanged (FigureEvent e)
Protected Member Functions
Rectangle basicGetBounds ()
Protected Member Functions inherited from org.jhotdraw.draw.handle.AbstractHandle
int getHandlesize ()
void fireAreaInvalidated (Rectangle invalidatedArea)
void fireUndoableEditHappened (UndoableEdit edit)
void fireHandleRequestRemove (Rectangle invalidatedArea)
void fireHandleRequestSecondaryHandles ()
void drawCircle (Graphics2D g, Color fill, Color stroke)
void drawRectangle (Graphics2D g, Color fill, Color stroke)
void drawDiamond (Graphics2D g, Color fill, Color stroke)
void updateBounds ()
Additional Inherited Members
Protected Attributes inherited from org.jhotdraw.draw.handle.AbstractHandle
DrawingView view
EventListenerList listenerList = new EventListenerList()
Detailed Description
The TextOverflowHandle indicates when the text does not fit into the bounds of a TextAreaFigure.
Author
Werner Randelshofer
Version
Id
TextOverflowHandle.java -1
Constructor & Destructor Documentation
TextOverflowHandle()
org.jhotdraw.draw.handle.TextOverflowHandle.TextOverflowHandle (TextHolderFigure owner)
Creates a new instance.
Member Function Documentation
basicGetBounds()
Rectangle org.jhotdraw.draw.handle.TextOverflowHandle.basicGetBounds () protected
Reimplemented from org.jhotdraw.draw.handle.AbstractHandle.
References org.jhotdraw.draw.DrawingView.drawingToView(), org.jhotdraw.draw.figure.Figure.get(), org.jhotdraw.draw.figure.Figure.getBounds(), org.jhotdraw.draw.handle.AbstractHandle.getHandlesize(), org.jhotdraw.draw.handle.TextOverflowHandle.getOwner(), and org.jhotdraw.draw.handle.AbstractHandle.view.
Referenced by org.jhotdraw.draw.handle.TextOverflowHandle.draw().
contains()
boolean org.jhotdraw.draw.handle.TextOverflowHandle.contains (Point p)
Tests if a point is contained in the handle.
Reimplemented from org.jhotdraw.draw.handle.AbstractHandle.
draw()
void org.jhotdraw.draw.handle.TextOverflowHandle.draw (Graphics2D g)
Draws this handle.
Reimplemented from org.jhotdraw.draw.handle.AbstractHandle.
References org.jhotdraw.draw.handle.TextOverflowHandle.basicGetBounds(), org.jhotdraw.draw.handle.AbstractHandle.drawRectangle(), org.jhotdraw.draw.handle.AbstractHandle.getEditor(), org.jhotdraw.draw.handle.TextOverflowHandle.getOwner(), org.jhotdraw.draw.handle.HandleAttributeKeys.OVERFLOW_HANDLE_FILL_COLOR, and org.jhotdraw.draw.handle.HandleAttributeKeys.OVERFLOW_HANDLE_STROKE_COLOR.
getOwner()
TextHolderFigure org.jhotdraw.draw.handle.TextOverflowHandle.getOwner ()
Returns the owner of this handle.
Reimplemented from org.jhotdraw.draw.handle.AbstractHandle.
Referenced by org.jhotdraw.draw.handle.TextOverflowHandle.basicGetBounds(), org.jhotdraw.draw.handle.TextOverflowHandle.draw(), and org.jhotdraw.draw.handle.TextOverflowHandle.getToolTipText().
getToolTipText()
String org.jhotdraw.draw.handle.TextOverflowHandle.getToolTipText (Point p)
Returns a tooltip for the specified location. By default, AbstractHandle returns null.
Reimplemented from org.jhotdraw.draw.handle.AbstractHandle.
References org.jhotdraw.draw.handle.TextOverflowHandle.getOwner().
trackEnd()
void org.jhotdraw.draw.handle.TextOverflowHandle.trackEnd (Point anchor, Point lead, int modifiersEx)
Tracks the end of the interaction.
Parameters
anchor the position where the interaction started
lead the current position
Implements org.jhotdraw.draw.handle.Handle.
trackStart()
void org.jhotdraw.draw.handle.TextOverflowHandle.trackStart (Point anchor, int modifiersEx)
Tracks the start of the interaction. The default implementation does nothing.
Parameters
anchor the position where the interaction started
Implements org.jhotdraw.draw.handle.Handle.
trackStep()
void org.jhotdraw.draw.handle.TextOverflowHandle.trackStep (Point anchor, Point lead, int modifiersEx)
Tracks a step of the interaction.
Parameters
anchor the position where the interaction started
lead the current position
Implements org.jhotdraw.draw.handle.Handle.
The documentation for this class was generated from the following file:
jhotdraw-core/src/main/java/org/jhotdraw/draw/handle/TextOverflowHandle.java