jhotdraw: org.jhotdraw.draw.io.ImageOutputFormat Class Reference
org.jhotdraw.draw.io.ImageOutputFormat Class Reference
Public Member Functions
ImageOutputFormat ()
ImageOutputFormat (String formatName, String description, String fileExtension, int bufferedImageType)
javax.swing.filechooser.FileFilter getFileFilter ()
String getFileExtension ()
JComponent getOutputFormatAccessory ()
void write (URI uri, Drawing drawing) throws IOException
void write (File file, Drawing drawing) throws IOException
void write (OutputStream out, Drawing drawing) throws IOException
void write (OutputStream out, Drawing drawing, AffineTransform drawingTransform, Dimension imageSize) throws IOException
Transferable createTransferable (Drawing drawing, java.util.List< Figure > figures, double scaleFactor) throws IOException
void write (OutputStream out, Drawing drawing, java.util.List< Figure > figures) throws IOException
void write (OutputStream out, Drawing drawing, java.util.List< Figure > figures, AffineTransform drawingTransform, Dimension imageSize) throws IOException
BufferedImage toImage (Drawing drawing, java.util.List< Figure > figures, double scaleFactor, boolean clipToFigures)
BufferedImage toImage (Drawing drawing, java.util.List< Figure > figures, AffineTransform transform, Dimension imageSize)
Public Member Functions inherited from org.jhotdraw.draw.io.OutputFormat
Transferable createTransferable (Drawing drawing, List< Figure > figures, double scaleFactor) throws IOException
Protected Member Functions
void setRenderingHints (Graphics2D g)
Detailed Description
An output format for exporting drawings using one of the image formats supported by javax.imageio.
Author
Werner Randelshofer
Version
$Id$
Constructor & Destructor Documentation
ImageOutputFormat() [1/2]
org.jhotdraw.draw.io.ImageOutputFormat.ImageOutputFormat ()
Creates a new image output format for Portable Network Graphics PNG.
ImageOutputFormat() [2/2]
org.jhotdraw.draw.io.ImageOutputFormat.ImageOutputFormat (String formatName, String description, String fileExtension, int bufferedImageType)
Creates a new image output format for the specified image format.
Parameters
formatName The format name for the javax.imageio.ImageIO object.
description The format description to be used for the file filter.
fileExtension The file extension to be used for file filter.
bufferedImageType The BufferedImage type used to produce the image. The value of this parameter must match with the format name.
Member Function Documentation
createTransferable()
Transferable org.jhotdraw.draw.io.ImageOutputFormat.createTransferable (Drawing drawing, java.util.List< Figure > figures, double scaleFactor) throws IOException
Writes the drawing to the specified output stream. This method ensures that all figures of the drawing are visible on the image.
References org.jhotdraw.draw.io.ImageOutputFormat.toImage().
getFileExtension()
String org.jhotdraw.draw.io.ImageOutputFormat.getFileExtension ()
Returns the file extension for the output format. The file extension should be appended to a file name when storing a Drawing with the specified file format.
Implements org.jhotdraw.draw.io.OutputFormat.
getFileFilter()
javax.swing.filechooser.FileFilter org.jhotdraw.draw.io.ImageOutputFormat.getFileFilter ()
Return a FileFilter that can be used to identify files which can be stored with this output format. Typically, each output format has its own recognizable file extension.
Returns
FileFilter to be used with a javax.swing.JFileChooser
Implements org.jhotdraw.draw.io.OutputFormat.
getOutputFormatAccessory()
JComponent org.jhotdraw.draw.io.ImageOutputFormat.getOutputFormatAccessory ()
Return a JFileChooser accessory that can be used to customize the output format.
Returns
A JFileChooser accessory to be used with a javax.swing.JFileChooser Returns null, if no accessory is provided for this format.
Implements org.jhotdraw.draw.io.OutputFormat.
setRenderingHints()
void org.jhotdraw.draw.io.ImageOutputFormat.setRenderingHints (Graphics2D g) protected
Referenced by org.jhotdraw.draw.io.ImageOutputFormat.toImage().
toImage() [1/2]
BufferedImage org.jhotdraw.draw.io.ImageOutputFormat.toImage (Drawing drawing, java.util.List< Figure > figures, AffineTransform transform, Dimension imageSize)
Creates a BufferedImage from the specified list of figures.
Parameters
drawing The drawing.
figures A list of figures of the drawing.
transform The AffineTransform to be used when drawing the figures.
imageSize The width and height of the image.
References org.jhotdraw.draw.figure.Figure.get(), and org.jhotdraw.draw.io.ImageOutputFormat.setRenderingHints().
toImage() [2/2]
BufferedImage org.jhotdraw.draw.io.ImageOutputFormat.toImage (Drawing drawing, java.util.List< Figure > figures, double scaleFactor, boolean clipToFigures)
Creates a BufferedImage from the specified list of figures.
The images are drawn using the specified scale factor. If some figures have a drawing area located at negative coordinates, then the drawing coordinates are translated, so that all figures are visible on the image.
Parameters
drawing The drawing.
figures A list of figures of the drawing.
scaleFactor The scale factor used when drawing the figures.
clipToFigures If this is true, the image is clipped to the figures. If this is false, the image includes the drawing area,
References org.jhotdraw.draw.figure.CompositeFigure.getChildCount().
Referenced by org.jhotdraw.draw.io.ImageOutputFormat.createTransferable(), and org.jhotdraw.draw.io.ImageOutputFormat.write().
write() [1/6]
void org.jhotdraw.draw.io.ImageOutputFormat.write (File file, Drawing drawing) throws IOException
Writes the drawing to the specified file. This method ensures that all figures of the drawing are visible on the image.
References org.jhotdraw.draw.io.ImageOutputFormat.write().
write() [2/6]
void org.jhotdraw.draw.io.ImageOutputFormat.write (OutputStream out, Drawing drawing) throws IOException
Writes the drawing to the specified output stream. This method ensures that all figures of the drawing are visible on the image.
Implements org.jhotdraw.draw.io.OutputFormat.
References org.jhotdraw.draw.io.ImageOutputFormat.write().
write() [3/6]
void org.jhotdraw.draw.io.ImageOutputFormat.write (OutputStream out, Drawing drawing, AffineTransform drawingTransform, Dimension imageSize) throws IOException
Writes the drawing to the specified output stream. This method applies the specified transform to the drawing, and draws it on an image of the specified size.
References org.jhotdraw.draw.io.ImageOutputFormat.write().
write() [4/6]
void org.jhotdraw.draw.io.ImageOutputFormat.write (OutputStream out, Drawing drawing, java.util.List< Figure > figures) throws IOException
Writes the figures to the specified output stream. This method ensures that all figures of the drawing are visible on the image.
References org.jhotdraw.draw.io.ImageOutputFormat.write().
write() [5/6]
void org.jhotdraw.draw.io.ImageOutputFormat.write (OutputStream out, Drawing drawing, java.util.List< Figure > figures, AffineTransform drawingTransform, Dimension imageSize) throws IOException
Writes the figures to the specified output stream. This method applies the specified transform to the drawing, and draws it on an image of the specified size.
References org.jhotdraw.draw.io.ImageOutputFormat.toImage().
write() [6/6]
void org.jhotdraw.draw.io.ImageOutputFormat.write (URI uri, Drawing drawing) throws IOException
Writes a Drawing into an URI.
Parameters
uri The uri.
drawing The drawing.
Implements org.jhotdraw.draw.io.OutputFormat.
Referenced by org.jhotdraw.draw.io.ImageOutputFormat.write().
The documentation for this class was generated from the following file:
jhotdraw-core/src/main/java/org/jhotdraw/draw/io/ImageOutputFormat.java