jhotdraw: org.jhotdraw.draw.event.CompositeFigureEdit Class Reference
org.jhotdraw.draw.event.CompositeFigureEdit Class Reference
Public Member Functions
CompositeFigureEdit (Figure figure)
CompositeFigureEdit (Figure figure, boolean isSignificant)
CompositeFigureEdit (Figure figure, String presentationName)
CompositeFigureEdit (Figure figure, String presentationName, boolean isSignificant)
void undo ()
void redo ()
Detailed Description
A CompositeEdit which invokes
figure.willChange
and
figure.changed
when undoing or redoing a change.
Author
Werner Randelshofer
Version
$Id$
Constructor & Destructor Documentation
CompositeFigureEdit() [1/4]
org.jhotdraw.draw.event.CompositeFigureEdit.CompositeFigureEdit (Figure figure)
Creates a new
CompositeFigureEdit
which uses CompoundEdit.getPresentatioName and is significant.
See also
javax.swing.undo.CompoundEdit::getPresentationName()
CompositeFigureEdit() [2/4]
org.jhotdraw.draw.event.CompositeFigureEdit.CompositeFigureEdit (Figure figure, boolean isSignificant)
Creates new CompositeFigureEdit which uses the specified significance.
See also
javax.swing.undo.CompoundEdit::getPresentationName()
CompositeFigureEdit() [3/4]
org.jhotdraw.draw.event.CompositeFigureEdit.CompositeFigureEdit (Figure figure, String presentationName)
Creates new CompositeFigureEdit which uses the specified presentation name.
See also
javax.swing.undo.CompoundEdit::getPresentationName()
CompositeFigureEdit() [4/4]
org.jhotdraw.draw.event.CompositeFigureEdit.CompositeFigureEdit (Figure figure, String presentationName, boolean isSignificant)
Creates new CompositeEdit. Which uses the given presentation name. If the presentation name is null, then CompoundEdit.getPresentatioName is used.
See also
javax.swing.undo.CompoundEdit::getPresentationName()
Member Function Documentation
redo()
void org.jhotdraw.draw.event.CompositeFigureEdit.redo ()
References org.jhotdraw.draw.figure.Figure.changed(), and org.jhotdraw.draw.figure.Figure.willChange().
undo()
void org.jhotdraw.draw.event.CompositeFigureEdit.undo ()
References org.jhotdraw.draw.figure.Figure.changed(), and org.jhotdraw.draw.figure.Figure.willChange().
The documentation for this class was generated from the following file:
jhotdraw-core/src/main/java/org/jhotdraw/draw/event/CompositeFigureEdit.java