jhotdraw: org.jhotdraw.draw.tool.ImageTool Class Reference
org.jhotdraw.draw.tool.ImageTool Class Reference
Public Member Functions
ImageTool (ImageHolderFigure prototype)
ImageTool (ImageHolderFigure prototype, Map< AttributeKey<?>, Object > attributes)
void setUseFileDialog (boolean newValue)
boolean isUseFileDialog ()
void activate (DrawingEditor editor)
Public Member Functions inherited from org.jhotdraw.draw.tool.CreationTool
CreationTool (String prototypeClassName)
CreationTool (String prototypeClassName, Map< AttributeKey<?>, Object > attributes)
CreationTool (String prototypeClassName, Map< AttributeKey<?>, Object > attributes, String name)
CreationTool (Figure prototype)
CreationTool (Figure prototype, Map< AttributeKey<?>, Object > attributes)
CreationTool (Figure prototype, Map< AttributeKey<?>, Object > attributes, String name)
Figure getPrototype ()
void deactivate (DrawingEditor editor)
void mousePressed (MouseEvent evt)
void mouseDragged (MouseEvent evt)
void mouseReleased (MouseEvent evt)
void setToolDoneAfterCreation (boolean newValue)
boolean isToolDoneAfterCreation ()
void updateCursor (DrawingView view, Point p)
Public Member Functions inherited from org.jhotdraw.draw.tool.AbstractTool
AbstractTool ()
void addUndoableEditListener (UndoableEditListener l)
void removeUndoableEditListener (UndoableEditListener l)
boolean isActive ()
void setInputMap (InputMap newValue)
InputMap getInputMap ()
void setActionMap (ActionMap newValue)
ActionMap getActionMap ()
void editDelete ()
void editCut ()
void editCopy ()
void editDuplicate ()
void editPaste ()
void keyReleased (KeyEvent evt)
void keyTyped (KeyEvent evt)
void keyPressed (KeyEvent evt)
void mouseClicked (MouseEvent evt)
void mouseEntered (MouseEvent evt)
void mouseExited (MouseEvent evt)
void mouseMoved (MouseEvent evt)
void addToolListener (ToolListener l)
void removeToolListener (ToolListener l)
void draw (Graphics2D g)
String getToolTipText (DrawingView view, MouseEvent evt)
boolean supportsHandleInteraction ()
Protected Attributes
FileDialog fileDialog
JFileChooser fileChooser
boolean useFileDialog
Protected Attributes inherited from org.jhotdraw.draw.tool.CreationTool
Map< AttributeKey<?>, Object > prototypeAttributes
String presentationName
Dimension minimalSizeTreshold = new Dimension(2, 2)
Dimension minimalSize = new Dimension(40, 40)
Figure prototype
Figure createdFigure
Protected Attributes inherited from org.jhotdraw.draw.tool.AbstractTool
boolean isWorking
DrawingEditor editor
Point anchor = new Point()
EventListenerList listenerList = new EventListenerList()
Additional Inherited Members
Protected Member Functions inherited from org.jhotdraw.draw.tool.CreationTool
Figure createFigure ()
Figure getCreatedFigure ()
Figure getAddedFigure ()
void creationFinished (Figure createdFigure)
Protected Member Functions inherited from org.jhotdraw.draw.tool.AbstractTool
DrawingView getView ()
DrawingEditor getEditor ()
Drawing getDrawing ()
Point2D.Double viewToDrawing (Point p)
Point2D.Double constrainPoint (Point p, Figure... figure)
Point2D.Double constrainPoint (Point2D.Double p, Figure... figure)
InputMap createInputMap ()
ActionMap createActionMap ()
void fireToolStarted (DrawingView view)
void fireToolDone ()
void fireAreaInvalidated (Rectangle2D.Double r)
void fireAreaInvalidated (Rectangle invalidatedArea)
void maybeFireBoundsInvalidated (Rectangle invalidatedArea)
void fireBoundsInvalidated (Rectangle invalidatedArea)
Detailed Description
A tool to create new figures that implement the ImageHolderFigure interface, such as ImageFigure. The figure to be created is specified by a prototype.
Immediately, after the ImageTool has been activated, it opens a JFileChooser, letting the user specify an image file. The the user then performs the following mouse gesture:
Press the mouse button and drag the mouse over the DrawingView. This defines the bounds of the created figure.
Design Patterns
Prototype
The
ImageTool
creates new figures by cloning a prototype
ImageHolderFigure
object.
Prototype: ImageHolderFigure; Client: ImageTool.
Author
Werner Randelshofer
Version
$Id$
Constructor & Destructor Documentation
ImageTool() [1/2]
org.jhotdraw.draw.tool.ImageTool.ImageTool (ImageHolderFigure prototype)
Creates a new instance.
References org.jhotdraw.draw.tool.CreationTool.prototype.
ImageTool() [2/2]
org.jhotdraw.draw.tool.ImageTool.ImageTool (ImageHolderFigure prototype, Map< AttributeKey<?>, Object > attributes)
Creates a new instance.
References org.jhotdraw.draw.tool.CreationTool.prototype.
Member Function Documentation
activate()
void org.jhotdraw.draw.tool.ImageTool.activate (DrawingEditor editor)
Activates the tool for the given editor. This method is called whenever the user switches to this tool.
Reimplemented from org.jhotdraw.draw.tool.CreationTool.
References org.jhotdraw.draw.figure.Figure.clone(), org.jhotdraw.draw.tool.CreationTool.createdFigure, org.jhotdraw.draw.tool.AbstractTool.editor, org.jhotdraw.draw.tool.AbstractTool.fireToolDone(), org.jhotdraw.draw.figure.ImageHolderFigure.getBufferedImage(), org.jhotdraw.draw.DrawingView.getComponent(), org.jhotdraw.draw.tool.AbstractTool.getDrawing(), org.jhotdraw.draw.figure.ImageHolderFigure.getImageData(), org.jhotdraw.draw.tool.AbstractTool.getView(), org.jhotdraw.draw.tool.CreationTool.isToolDoneAfterCreation(), org.jhotdraw.draw.figure.ImageHolderFigure.loadImage(), org.jhotdraw.draw.tool.CreationTool.prototype, org.jhotdraw.draw.Drawing.remove(), and org.jhotdraw.draw.tool.ImageTool.useFileDialog.
isUseFileDialog()
boolean org.jhotdraw.draw.tool.ImageTool.isUseFileDialog ()
References org.jhotdraw.draw.tool.ImageTool.useFileDialog.
setUseFileDialog()
void org.jhotdraw.draw.tool.ImageTool.setUseFileDialog (boolean newValue)
References org.jhotdraw.draw.tool.ImageTool.fileChooser, org.jhotdraw.draw.tool.ImageTool.fileDialog, and org.jhotdraw.draw.tool.ImageTool.useFileDialog.
Member Data Documentation
fileChooser
JFileChooser org.jhotdraw.draw.tool.ImageTool.fileChooser protected
Referenced by org.jhotdraw.draw.tool.ImageTool.setUseFileDialog().
fileDialog
FileDialog org.jhotdraw.draw.tool.ImageTool.fileDialog protected
Referenced by org.jhotdraw.draw.tool.ImageTool.setUseFileDialog().
useFileDialog
boolean org.jhotdraw.draw.tool.ImageTool.useFileDialog protected
Referenced by org.jhotdraw.draw.tool.ImageTool.activate(), org.jhotdraw.draw.tool.ImageTool.isUseFileDialog(), and org.jhotdraw.draw.tool.ImageTool.setUseFileDialog().
The documentation for this class was generated from the following file:
jhotdraw-core/src/main/java/org/jhotdraw/draw/tool/ImageTool.java