jhotdraw: org.jhotdraw.draw.event.SetBoundsEdit Class Reference
org.jhotdraw.draw.event.SetBoundsEdit Class Reference
Public Member Functions
SetBoundsEdit (AbstractFigure owner, Point2D.Double oldAnchor, Point2D.Double oldLead, Point2D.Double newAnchor, Point2D.Double newLead)
String getPresentationName ()
boolean addEdit (UndoableEdit anEdit)
boolean replaceEdit (UndoableEdit anEdit)
void redo () throws CannotRedoException
void undo () throws CannotUndoException
Detailed Description
SetBoundsEdit.
Author
Werner Randelshofer
Version
$Id$
Constructor & Destructor Documentation
SetBoundsEdit()
org.jhotdraw.draw.event.SetBoundsEdit.SetBoundsEdit (AbstractFigure owner, Point2D.Double oldAnchor, Point2D.Double oldLead, Point2D.Double newAnchor, Point2D.Double newLead)
Creates a new instance.
Referenced by org.jhotdraw.draw.event.SetBoundsEdit.addEdit(), and org.jhotdraw.draw.event.SetBoundsEdit.replaceEdit().
Member Function Documentation
addEdit()
boolean org.jhotdraw.draw.event.SetBoundsEdit.addEdit (UndoableEdit anEdit)
References org.jhotdraw.draw.event.SetBoundsEdit.SetBoundsEdit().
getPresentationName()
String org.jhotdraw.draw.event.SetBoundsEdit.getPresentationName ()
redo()
void org.jhotdraw.draw.event.SetBoundsEdit.redo () throws CannotRedoException
References org.jhotdraw.draw.figure.AbstractFigure.changed(), org.jhotdraw.draw.figure.AbstractFigure.setBounds(), and org.jhotdraw.draw.figure.AbstractFigure.willChange().
replaceEdit()
boolean org.jhotdraw.draw.event.SetBoundsEdit.replaceEdit (UndoableEdit anEdit)
References org.jhotdraw.draw.event.SetBoundsEdit.SetBoundsEdit().
undo()
void org.jhotdraw.draw.event.SetBoundsEdit.undo () throws CannotUndoException
References org.jhotdraw.draw.figure.AbstractFigure.changed(), org.jhotdraw.draw.figure.AbstractFigure.setBounds(), and org.jhotdraw.draw.figure.AbstractFigure.willChange().
The documentation for this class was generated from the following file:
jhotdraw-core/src/main/java/org/jhotdraw/draw/event/SetBoundsEdit.java