jhotdraw: org.jhotdraw.draw.action.DrawingColorIcon Class Reference
org.jhotdraw.draw.action.DrawingColorIcon Class Reference
Public Member Functions
DrawingColorIcon (DrawingEditor editor, AttributeKey< Color > key, URL imageLocation, Shape colorShape)
DrawingColorIcon (DrawingEditor editor, AttributeKey< Color > key, Image image, Shape colorShape)
void paintIcon (java.awt.Component c, java.awt.Graphics gr, int x, int y)
Detailed Description
DrawingColorIcon draws a shape with the specified color for the drawing in the current drawing view.
The behavior for choosing the drawn color matches with DrawingColorChooserAction.
Author
Werner Randelshofer
Version
$Id$
Constructor & Destructor Documentation
DrawingColorIcon() [1/2]
org.jhotdraw.draw.action.DrawingColorIcon.DrawingColorIcon (DrawingEditor editor, AttributeKey< Color > key, URL imageLocation, Shape colorShape)
Creates a new instance.
Parameters
editor The drawing editor.
key The key of the default attribute
imageLocation the icon image
colorShape The shape to be drawn with the color of the default attribute.
DrawingColorIcon() [2/2]
org.jhotdraw.draw.action.DrawingColorIcon.DrawingColorIcon (DrawingEditor editor, AttributeKey< Color > key, Image image, Shape colorShape)
Member Function Documentation
paintIcon()
void org.jhotdraw.draw.action.DrawingColorIcon.paintIcon (java.awt.Component c, java.awt.Graphics gr, int x, int y)
References org.jhotdraw.draw.figure.Figure.get(), org.jhotdraw.draw.DrawingEditor.getActiveView(), org.jhotdraw.draw.AttributeKey< T >.getDefaultValue(), and org.jhotdraw.draw.DrawingView.getDrawing().
The documentation for this class was generated from the following file:
jhotdraw-core/src/main/java/org/jhotdraw/draw/action/DrawingColorIcon.java