jhotdraw: org.jhotdraw.draw.tool.AbstractTool Class Reference
org.jhotdraw.draw.tool.AbstractTool Class Reference abstract
Public Member Functions
AbstractTool ()
void addUndoableEditListener (UndoableEditListener l)
void removeUndoableEditListener (UndoableEditListener l)
void activate (DrawingEditor editor)
void deactivate (DrawingEditor editor)
boolean isActive ()
void setInputMap (InputMap newValue)
InputMap getInputMap ()
void setActionMap (ActionMap newValue)
ActionMap getActionMap ()
void editDelete ()
void editCut ()
void editCopy ()
void editDuplicate ()
void editPaste ()
void keyReleased (KeyEvent evt)
void keyTyped (KeyEvent evt)
void keyPressed (KeyEvent evt)
void mouseClicked (MouseEvent evt)
void mouseEntered (MouseEvent evt)
void mouseExited (MouseEvent evt)
void mouseMoved (MouseEvent evt)
void mousePressed (MouseEvent evt)
void mouseReleased (MouseEvent evt)
void addToolListener (ToolListener l)
void removeToolListener (ToolListener l)
void draw (Graphics2D g)
void updateCursor (DrawingView view, Point p)
String getToolTipText (DrawingView view, MouseEvent evt)
boolean supportsHandleInteraction ()
Protected Member Functions
DrawingView getView ()
DrawingEditor getEditor ()
Drawing getDrawing ()
Point2D.Double viewToDrawing (Point p)
Point2D.Double constrainPoint (Point p, Figure... figure)
Point2D.Double constrainPoint (Point2D.Double p, Figure... figure)
InputMap createInputMap ()
ActionMap createActionMap ()
void fireToolStarted (DrawingView view)
void fireToolDone ()
void fireAreaInvalidated (Rectangle2D.Double r)
void fireAreaInvalidated (Rectangle invalidatedArea)
void maybeFireBoundsInvalidated (Rectangle invalidatedArea)
void fireBoundsInvalidated (Rectangle invalidatedArea)
Protected Attributes
boolean isWorking
DrawingEditor editor
Point anchor = new Point()
EventListenerList listenerList = new EventListenerList()
Detailed Description
This abstract class can be extended to implement a Tool.
Design Patterns
Proxy
To remove the need for null-handling,
AbstractTool
makes use of a proxy for
DrawingEditor
. Subject: DrawingEditor; Proxy: DrawingEditorProxy; Client: AbstractTool.
Author
Werner Randelshofer
Version
$Id$
Constructor & Destructor Documentation
AbstractTool()
org.jhotdraw.draw.tool.AbstractTool.AbstractTool ()
Creates a new instance.
References org.jhotdraw.draw.tool.AbstractTool.createActionMap(), org.jhotdraw.draw.tool.AbstractTool.createInputMap(), org.jhotdraw.draw.tool.AbstractTool.setActionMap(), and org.jhotdraw.draw.tool.AbstractTool.setInputMap().
Member Function Documentation
activate()
void org.jhotdraw.draw.tool.AbstractTool.activate (DrawingEditor editor)
Activates the tool for the given editor. This method is called whenever the user switches to this tool.
Implements org.jhotdraw.draw.tool.Tool.
Reimplemented in org.jhotdraw.draw.tool.SelectionTool, org.jhotdraw.draw.tool.ImageTool, org.jhotdraw.draw.tool.DefaultSelectAreaTracker, org.jhotdraw.draw.tool.DefaultHandleTracker, org.jhotdraw.draw.tool.CreationTool, org.jhotdraw.draw.tool.ConnectionTool, and org.jhotdraw.draw.tool.BezierTool.
References org.jhotdraw.draw.tool.AbstractTool.editor, org.jhotdraw.draw.DrawingEditor.getDrawingViews(), and org.jhotdraw.draw.DrawingEditorProxy.setTarget().
addToolListener()
void org.jhotdraw.draw.tool.AbstractTool.addToolListener (ToolListener l)
Adds a listener for this tool.
Implements org.jhotdraw.draw.tool.Tool.
References org.jhotdraw.draw.tool.AbstractTool.listenerList.
addUndoableEditListener()
void org.jhotdraw.draw.tool.AbstractTool.addUndoableEditListener (UndoableEditListener l)
References org.jhotdraw.draw.tool.AbstractTool.listenerList.
constrainPoint() [1/2]
Point2D.Double org.jhotdraw.draw.tool.AbstractTool.constrainPoint (Point p, Figure... figure) protected
References org.jhotdraw.draw.tool.AbstractTool.getView(), and org.jhotdraw.draw.tool.AbstractTool.viewToDrawing().
Referenced by org.jhotdraw.draw.tool.CreationTool.mouseDragged(), org.jhotdraw.draw.tool.CreationTool.mousePressed(), org.jhotdraw.draw.tool.CreationTool.mouseReleased(), and org.jhotdraw.draw.tool.AbstractTool.viewToDrawing().
constrainPoint() [2/2]
Point2D.Double org.jhotdraw.draw.tool.AbstractTool.constrainPoint (Point2D.Double p, Figure... figure) protected
References org.jhotdraw.draw.Constrainer.constrainPoint(), org.jhotdraw.draw.DrawingView.getConstrainer(), and org.jhotdraw.draw.tool.AbstractTool.getView().
createActionMap()
ActionMap org.jhotdraw.draw.tool.AbstractTool.createActionMap () protected
Override this method to create a tool-specific action map, which overrides the action map of the drawing edtior.
The implementation of this class returns null.
Referenced by org.jhotdraw.draw.tool.AbstractTool.AbstractTool().
createInputMap()
InputMap org.jhotdraw.draw.tool.AbstractTool.createInputMap () protected
Override this method to create a tool-specific input map, which overrides the input map of the drawing edtior.
The implementation of this class returns null.
Referenced by org.jhotdraw.draw.tool.AbstractTool.AbstractTool().
deactivate()
void org.jhotdraw.draw.tool.AbstractTool.deactivate (DrawingEditor editor)
Deactivates the tool. This method is called whenever the user switches to another tool.
Implements org.jhotdraw.draw.tool.Tool.
Reimplemented in org.jhotdraw.draw.tool.TextEditingTool, org.jhotdraw.draw.tool.TextCreationTool, org.jhotdraw.draw.tool.TextAreaEditingTool, org.jhotdraw.draw.tool.TextAreaCreationTool, org.jhotdraw.draw.tool.SelectionTool, org.jhotdraw.draw.tool.DefaultSelectAreaTracker, org.jhotdraw.draw.tool.DefaultHandleTracker, org.jhotdraw.draw.tool.CreationTool, org.jhotdraw.draw.tool.ConnectionTool, and org.jhotdraw.draw.tool.BezierTool.
References org.jhotdraw.draw.tool.AbstractTool.editor, and org.jhotdraw.draw.DrawingEditorProxy.setTarget().
draw()
void org.jhotdraw.draw.tool.AbstractTool.draw (Graphics2D g)
Draws the tool.
Implements org.jhotdraw.draw.tool.Tool.
Reimplemented in org.jhotdraw.draw.tool.TextAreaEditingTool, org.jhotdraw.draw.tool.TextAreaCreationTool, org.jhotdraw.draw.tool.SelectionTool, org.jhotdraw.draw.tool.DefaultSelectAreaTracker, org.jhotdraw.draw.tool.DefaultHandleTracker, org.jhotdraw.draw.tool.ConnectionTool, and org.jhotdraw.draw.tool.BezierTool.
editCopy()
void org.jhotdraw.draw.tool.AbstractTool.editCopy ()
Copies the selection into the clipboard. Depending on the tool, this could be selected figures, selected points or selected text.
Implements org.jhotdraw.draw.tool.Tool.
editCut()
void org.jhotdraw.draw.tool.AbstractTool.editCut ()
Cuts the selection into the clipboard. Depending on the tool, this could be selected figures, selected points or selected text.
Implements org.jhotdraw.draw.tool.Tool.
editDelete()
void org.jhotdraw.draw.tool.AbstractTool.editDelete ()
Deletes the selection. Depending on the tool, this could be selected figures, selected points or selected text.
Implements org.jhotdraw.draw.tool.Tool.
References org.jhotdraw.draw.DrawingView.getDrawing(), org.jhotdraw.draw.tool.AbstractTool.getView(), and org.jhotdraw.draw.Drawing.removeAll().
editDuplicate()
void org.jhotdraw.draw.tool.AbstractTool.editDuplicate ()
Duplicates the selection. Depending on the tool, this could be selected figures, selected points or selected text.
Implements org.jhotdraw.draw.tool.Tool.
editPaste()
void org.jhotdraw.draw.tool.AbstractTool.editPaste ()
Pastes the contents of the clipboard. Depending on the tool, this could be selected figures, selected points or selected text.
Implements org.jhotdraw.draw.tool.Tool.
fireAreaInvalidated() [1/2]
void org.jhotdraw.draw.tool.AbstractTool.fireAreaInvalidated (Rectangle invalidatedArea) protected
Notify all listenerList that have registered interest for notification on this event type.
References org.jhotdraw.draw.tool.AbstractTool.getView(), and org.jhotdraw.draw.tool.AbstractTool.listenerList.
fireAreaInvalidated() [2/2]
void org.jhotdraw.draw.tool.AbstractTool.fireAreaInvalidated (Rectangle2D.Double r) protected
Notify all listenerList that have registered interest for notification on this event type.
References org.jhotdraw.draw.DrawingView.drawingToView(), and org.jhotdraw.draw.tool.AbstractTool.getView().
Referenced by org.jhotdraw.draw.tool.BezierTool.deactivate(), org.jhotdraw.draw.tool.DefaultSelectAreaTracker.mouseDragged(), org.jhotdraw.draw.tool.BezierTool.mouseMoved(), org.jhotdraw.draw.tool.BezierTool.mousePressed(), org.jhotdraw.draw.tool.ConnectionTool.mousePressed(), org.jhotdraw.draw.tool.ConnectionTool.mouseReleased(), org.jhotdraw.draw.tool.BezierTool.mouseReleased(), org.jhotdraw.draw.tool.DefaultHandleTracker.updateHoverHandles(), and org.jhotdraw.draw.tool.DefaultSelectAreaTracker.updateHoverHandles().
fireBoundsInvalidated()
void org.jhotdraw.draw.tool.AbstractTool.fireBoundsInvalidated (Rectangle invalidatedArea) protected
Notify all listenerList that have registered interest for notification on this event type.
References org.jhotdraw.draw.tool.AbstractTool.getView(), and org.jhotdraw.draw.tool.AbstractTool.listenerList.
Referenced by org.jhotdraw.draw.tool.AbstractTool.maybeFireBoundsInvalidated().
fireToolDone()
void org.jhotdraw.draw.tool.AbstractTool.fireToolDone () protected
Notify all listenerList that have registered interest for notification on this event type.
References org.jhotdraw.draw.tool.AbstractTool.getView(), and org.jhotdraw.draw.tool.AbstractTool.listenerList.
Referenced by org.jhotdraw.draw.tool.TextAreaCreationTool.actionPerformed(), org.jhotdraw.draw.tool.TextAreaEditingTool.actionPerformed(), org.jhotdraw.draw.tool.TextCreationTool.actionPerformed(), org.jhotdraw.draw.tool.TextEditingTool.actionPerformed(), org.jhotdraw.draw.tool.ImageTool.activate(), org.jhotdraw.draw.tool.ConnectionTool.creationFinished(), org.jhotdraw.draw.tool.CreationTool.creationFinished(), org.jhotdraw.draw.tool.BezierTool.finishCreation(), org.jhotdraw.draw.tool.AbstractTool.keyPressed(), org.jhotdraw.draw.tool.AbstractTool.keyReleased(), org.jhotdraw.draw.tool.TextCreationTool.keyReleased(), org.jhotdraw.draw.tool.TextEditingTool.keyReleased(), org.jhotdraw.draw.tool.BezierTool.mouseClicked(), org.jhotdraw.draw.tool.DnDTracker.mouseDragged(), org.jhotdraw.draw.tool.TextAreaCreationTool.mousePressed(), org.jhotdraw.draw.tool.TextCreationTool.mousePressed(), org.jhotdraw.draw.tool.ConnectionTool.mouseReleased(), org.jhotdraw.draw.tool.CreationTool.mouseReleased(), org.jhotdraw.draw.tool.DefaultDragTracker.mouseReleased(), and org.jhotdraw.draw.tool.DnDTracker.mouseReleased().
fireToolStarted()
void org.jhotdraw.draw.tool.AbstractTool.fireToolStarted (DrawingView view) protected
Notify all listenerList that have registered interest for notification on this event type.
References org.jhotdraw.draw.tool.AbstractTool.listenerList.
Referenced by org.jhotdraw.draw.tool.AbstractTool.mousePressed().
getActionMap()
ActionMap org.jhotdraw.draw.tool.AbstractTool.getActionMap ()
Gets the action map of the Tool
getDrawing()
Drawing org.jhotdraw.draw.tool.AbstractTool.getDrawing () protected
References org.jhotdraw.draw.DrawingView.getDrawing(), and org.jhotdraw.draw.tool.AbstractTool.getView().
Referenced by org.jhotdraw.draw.tool.ImageTool.activate(), org.jhotdraw.draw.tool.ConnectionTool.deactivate(), org.jhotdraw.draw.tool.TextAreaCreationTool.endEdit(), org.jhotdraw.draw.tool.TextAreaEditingTool.endEdit(), org.jhotdraw.draw.tool.TextCreationTool.endEdit(), org.jhotdraw.draw.tool.TextEditingTool.endEdit(), org.jhotdraw.draw.tool.BezierTool.fireUndoEvent(), org.jhotdraw.draw.tool.DelegationSelectionTool.handleDoubleClick(), org.jhotdraw.draw.tool.AbstractTool.maybeFireBoundsInvalidated(), org.jhotdraw.draw.tool.ConnectionTool.mouseDragged(), org.jhotdraw.draw.tool.BezierTool.mousePressed(), org.jhotdraw.draw.tool.ConnectionTool.mousePressed(), org.jhotdraw.draw.tool.CreationTool.mousePressed(), org.jhotdraw.draw.tool.ConnectionTool.mouseReleased(), org.jhotdraw.draw.tool.CreationTool.mouseReleased(), org.jhotdraw.draw.tool.DefaultDragTracker.mouseReleased(), and org.jhotdraw.draw.tool.ConnectionTool.repaintConnectors().
getEditor()
DrawingEditor org.jhotdraw.draw.tool.AbstractTool.getEditor () protected
References org.jhotdraw.draw.tool.AbstractTool.editor.
Referenced by org.jhotdraw.draw.tool.BezierTool.createFigure(), org.jhotdraw.draw.tool.ConnectionTool.createFigure(), org.jhotdraw.draw.tool.CreationTool.createFigure(), and org.jhotdraw.draw.tool.SelectionTool.setTracker().
getInputMap()
InputMap org.jhotdraw.draw.tool.AbstractTool.getInputMap ()
Gets the input map of the Tool
getToolTipText()
String org.jhotdraw.draw.tool.AbstractTool.getToolTipText (DrawingView view, MouseEvent evt)
Returns the tooltip text for a mouse event on a drawing view.
Parameters
view A drawing view.
evt A mouse event.
Returns
A tooltip text or null.
Implements org.jhotdraw.draw.tool.Tool.
Reimplemented in org.jhotdraw.draw.tool.DelegationSelectionTool.
getView()
DrawingView org.jhotdraw.draw.tool.AbstractTool.getView () protected
References org.jhotdraw.draw.tool.AbstractTool.editor, and org.jhotdraw.draw.DrawingEditor.getActiveView().
Referenced by org.jhotdraw.draw.tool.BezierTool.activate(), org.jhotdraw.draw.tool.CreationTool.activate(), org.jhotdraw.draw.tool.DefaultHandleTracker.activate(), org.jhotdraw.draw.tool.ImageTool.activate(), org.jhotdraw.draw.tool.BezierTool.addPointToFigure(), org.jhotdraw.draw.tool.TextAreaCreationTool.beginEdit(), org.jhotdraw.draw.tool.TextAreaEditingTool.beginEdit(), org.jhotdraw.draw.tool.TextCreationTool.beginEdit(), org.jhotdraw.draw.tool.TextEditingTool.beginEdit(), org.jhotdraw.draw.tool.BezierTool.calculateFittedCurve(), org.jhotdraw.draw.tool.AbstractTool.constrainPoint(), org.jhotdraw.draw.tool.CreationTool.creationFinished(), org.jhotdraw.draw.tool.TextAreaCreationTool.creationFinished(), org.jhotdraw.draw.tool.TextCreationTool.creationFinished(), org.jhotdraw.draw.tool.BezierTool.deactivate(), org.jhotdraw.draw.tool.CreationTool.deactivate(), org.jhotdraw.draw.tool.DefaultHandleTracker.deactivate(), org.jhotdraw.draw.tool.BezierTool.draw(), org.jhotdraw.draw.tool.ConnectionTool.draw(), org.jhotdraw.draw.tool.DefaultHandleTracker.draw(), org.jhotdraw.draw.tool.DefaultSelectAreaTracker.draw(), org.jhotdraw.draw.tool.TextAreaCreationTool.draw(), org.jhotdraw.draw.tool.AbstractTool.editDelete(), org.jhotdraw.draw.tool.AbstractTool.fireAreaInvalidated(), org.jhotdraw.draw.tool.AbstractTool.fireBoundsInvalidated(), org.jhotdraw.draw.tool.AbstractTool.fireToolDone(), org.jhotdraw.draw.tool.AbstractTool.getDrawing(), org.jhotdraw.draw.tool.SelectionTool.getHandleTracker(), org.jhotdraw.draw.tool.DelegationSelectionTool.handleDoubleClick(), org.jhotdraw.draw.tool.DelegationSelectionTool.handleMultiClick(), org.jhotdraw.draw.tool.DelegationSelectionTool.handlePopupMenu(), org.jhotdraw.draw.tool.SelectionTool.keyPressed(), org.jhotdraw.draw.tool.DefaultHandleTracker.keyPressed(), org.jhotdraw.draw.tool.DefaultHandleTracker.keyReleased(), org.jhotdraw.draw.tool.SelectionTool.keyReleased(), org.jhotdraw.draw.tool.SelectionTool.keyTyped(), org.jhotdraw.draw.tool.BezierTool.mouseClicked(), org.jhotdraw.draw.tool.DefaultHandleTracker.mouseClicked(), org.jhotdraw.draw.tool.SelectionTool.mouseClicked(), org.jhotdraw.draw.tool.ConnectionTool.mouseDragged(), org.jhotdraw.draw.tool.DnDTracker.mouseDragged(), org.jhotdraw.draw.tool.BezierTool.mouseDragged(), org.jhotdraw.draw.tool.DefaultDragTracker.mouseDragged(), org.jhotdraw.draw.tool.DefaultHandleTracker.mouseDragged(), org.jhotdraw.draw.tool.SelectionTool.mouseDragged(), org.jhotdraw.draw.tool.DelegationSelectionTool.mousePressed(), org.jhotdraw.draw.tool.TextAreaEditingTool.mousePressed(), org.jhotdraw.draw.tool.TextCreationTool.mousePressed(), org.jhotdraw.draw.tool.TextEditingTool.mousePressed(), org.jhotdraw.draw.tool.BezierTool.mousePressed(), org.jhotdraw.draw.tool.ConnectionTool.mousePressed(), org.jhotdraw.draw.tool.CreationTool.mousePressed(), org.jhotdraw.draw.tool.DefaultDragTracker.mousePressed(), org.jhotdraw.draw.tool.DefaultHandleTracker.mousePressed(), org.jhotdraw.draw.tool.DnDTracker.mousePressed(), org.jhotdraw.draw.tool.SelectionTool.mousePressed(), org.jhotdraw.draw.tool.ConnectionTool.mouseReleased(), org.jhotdraw.draw.tool.DefaultDragTracker.mouseReleased(), org.jhotdraw.draw.tool.DefaultHandleTracker.mouseReleased(), org.jhotdraw.draw.tool.SelectionTool.mouseReleased(), org.jhotdraw.draw.tool.ConnectionTool.repaintConnectors(), and org.jhotdraw.draw.tool.AbstractTool.viewToDrawing().
isActive()
boolean org.jhotdraw.draw.tool.AbstractTool.isActive ()
keyPressed()
void org.jhotdraw.draw.tool.AbstractTool.keyPressed (KeyEvent evt)
The Tool uses the InputMap to determine what to do, when a key is pressed. If the corresponding value of the InputMap is a String, the ActionMap of the tool is used, to find the action to be performed. If the corresponding value of the InputMap is a ActionListener, the actionPerformed method of the ActionListener is performed.
Reimplemented in org.jhotdraw.draw.tool.DefaultHandleTracker, and org.jhotdraw.draw.tool.SelectionTool.
References org.jhotdraw.draw.tool.AbstractTool.editor, org.jhotdraw.draw.DrawingEditor.findView(), org.jhotdraw.draw.tool.AbstractTool.fireToolDone(), org.jhotdraw.draw.DrawingEditor.getActionMap(), org.jhotdraw.draw.DrawingEditor.getInputMap(), and org.jhotdraw.draw.DrawingEditor.setActiveView().
keyReleased()
void org.jhotdraw.draw.tool.AbstractTool.keyReleased (KeyEvent evt)
Reimplemented in org.jhotdraw.draw.tool.TextEditingTool, org.jhotdraw.draw.tool.TextCreationTool, org.jhotdraw.draw.tool.SelectionTool, and org.jhotdraw.draw.tool.DefaultHandleTracker.
References org.jhotdraw.draw.tool.AbstractTool.fireToolDone().
keyTyped()
void org.jhotdraw.draw.tool.AbstractTool.keyTyped (KeyEvent evt)
Reimplemented in org.jhotdraw.draw.tool.SelectionTool, and org.jhotdraw.draw.tool.DefaultHandleTracker.
maybeFireBoundsInvalidated()
void org.jhotdraw.draw.tool.AbstractTool.maybeFireBoundsInvalidated (Rectangle invalidatedArea) protected
Notify all listenerList that have registered interest for notification on this event type.
Note: This method only fires an event, if the invalidated area is outside of the canvas bounds.
References org.jhotdraw.draw.tool.AbstractTool.fireBoundsInvalidated(), org.jhotdraw.draw.figure.Figure.get(), and org.jhotdraw.draw.tool.AbstractTool.getDrawing().
Referenced by org.jhotdraw.draw.tool.BezierTool.mouseReleased(), org.jhotdraw.draw.tool.CreationTool.mouseReleased(), org.jhotdraw.draw.tool.DefaultDragTracker.mouseReleased(), and org.jhotdraw.draw.tool.DefaultHandleTracker.mouseReleased().
mouseClicked()
void org.jhotdraw.draw.tool.AbstractTool.mouseClicked (MouseEvent evt)
Reimplemented in org.jhotdraw.draw.tool.SelectionTool, org.jhotdraw.draw.tool.DelegationSelectionTool, org.jhotdraw.draw.tool.DefaultHandleTracker, and org.jhotdraw.draw.tool.BezierTool.
mouseEntered()
void org.jhotdraw.draw.tool.AbstractTool.mouseEntered (MouseEvent evt)
Reimplemented in org.jhotdraw.draw.tool.SelectionTool, and org.jhotdraw.draw.tool.DefaultHandleTracker.
mouseExited()
void org.jhotdraw.draw.tool.AbstractTool.mouseExited (MouseEvent evt)
Reimplemented in org.jhotdraw.draw.tool.SelectionTool, org.jhotdraw.draw.tool.DefaultSelectAreaTracker, and org.jhotdraw.draw.tool.DefaultHandleTracker.
mouseMoved()
void org.jhotdraw.draw.tool.AbstractTool.mouseMoved (MouseEvent evt)
Reimplemented in org.jhotdraw.draw.tool.SelectionTool, org.jhotdraw.draw.tool.DnDTracker, org.jhotdraw.draw.tool.DefaultSelectAreaTracker, org.jhotdraw.draw.tool.DefaultHandleTracker, org.jhotdraw.draw.tool.DefaultDragTracker, org.jhotdraw.draw.tool.ConnectionTool, and org.jhotdraw.draw.tool.BezierTool.
mousePressed()
void org.jhotdraw.draw.tool.AbstractTool.mousePressed (MouseEvent evt)
Reimplemented in org.jhotdraw.draw.tool.SelectionTool, org.jhotdraw.draw.tool.DnDTracker, org.jhotdraw.draw.tool.DefaultSelectAreaTracker, org.jhotdraw.draw.tool.DefaultHandleTracker, org.jhotdraw.draw.tool.DefaultDragTracker, org.jhotdraw.draw.tool.CreationTool, org.jhotdraw.draw.tool.ConnectionTool, org.jhotdraw.draw.tool.BezierTool, org.jhotdraw.draw.tool.TextEditingTool, org.jhotdraw.draw.tool.TextCreationTool, org.jhotdraw.draw.tool.TextAreaEditingTool, org.jhotdraw.draw.tool.TextAreaCreationTool, and org.jhotdraw.draw.tool.DelegationSelectionTool.
References org.jhotdraw.draw.tool.AbstractTool.anchor, org.jhotdraw.draw.tool.AbstractTool.editor, org.jhotdraw.draw.DrawingEditor.findView(), org.jhotdraw.draw.tool.AbstractTool.fireToolStarted(), org.jhotdraw.draw.tool.AbstractTool.isWorking, and org.jhotdraw.draw.DrawingView.requestFocus().
mouseReleased()
void org.jhotdraw.draw.tool.AbstractTool.mouseReleased (MouseEvent evt)
Reimplemented in org.jhotdraw.draw.tool.TextEditingTool, org.jhotdraw.draw.tool.TextCreationTool, org.jhotdraw.draw.tool.SelectionTool, org.jhotdraw.draw.tool.DnDTracker, org.jhotdraw.draw.tool.DelegationSelectionTool, org.jhotdraw.draw.tool.DefaultSelectAreaTracker, org.jhotdraw.draw.tool.DefaultHandleTracker, org.jhotdraw.draw.tool.DefaultDragTracker, org.jhotdraw.draw.tool.CreationTool, org.jhotdraw.draw.tool.BezierTool, and org.jhotdraw.draw.tool.ConnectionTool.
References org.jhotdraw.draw.tool.AbstractTool.isWorking.
removeToolListener()
void org.jhotdraw.draw.tool.AbstractTool.removeToolListener (ToolListener l)
Removes a listener for this tool.
Implements org.jhotdraw.draw.tool.Tool.
References org.jhotdraw.draw.tool.AbstractTool.listenerList.
removeUndoableEditListener()
void org.jhotdraw.draw.tool.AbstractTool.removeUndoableEditListener (UndoableEditListener l)
References org.jhotdraw.draw.tool.AbstractTool.listenerList.
setActionMap()
void org.jhotdraw.draw.tool.AbstractTool.setActionMap (ActionMap newValue)
Sets the ActionMap for the Tool.
See also
keyPressed
Referenced by org.jhotdraw.draw.tool.AbstractTool.AbstractTool().
setInputMap()
void org.jhotdraw.draw.tool.AbstractTool.setInputMap (InputMap newValue)
Sets the InputMap for the Tool.
See also
keyPressed
setActionMap
Referenced by org.jhotdraw.draw.tool.AbstractTool.AbstractTool().
supportsHandleInteraction()
boolean org.jhotdraw.draw.tool.AbstractTool.supportsHandleInteraction ()
Returns true, if this tool lets the user interact with handles.
Handles may draw differently, if interaction is not possible.
Returns
True, if this tool supports interaction with the handles.
Implements org.jhotdraw.draw.tool.Tool.
Reimplemented in org.jhotdraw.draw.tool.SelectionTool.
updateCursor()
void org.jhotdraw.draw.tool.AbstractTool.updateCursor (DrawingView view, Point p)
Reimplemented in org.jhotdraw.draw.tool.TextEditingTool, org.jhotdraw.draw.tool.TextCreationTool, and org.jhotdraw.draw.tool.CreationTool.
References org.jhotdraw.draw.DrawingView.findFigure(), org.jhotdraw.draw.Drawing.findFigureBehind(), org.jhotdraw.draw.DrawingView.findHandle(), org.jhotdraw.draw.handle.Handle.getCursor(), org.jhotdraw.draw.figure.Figure.getCursor(), org.jhotdraw.draw.DrawingView.getDrawing(), org.jhotdraw.draw.DrawingView.isEnabled(), org.jhotdraw.draw.figure.Figure.isSelectable(), org.jhotdraw.draw.DrawingView.setCursor(), and org.jhotdraw.draw.DrawingView.viewToDrawing().
Referenced by org.jhotdraw.draw.tool.DefaultDragTracker.mouseDragged(), org.jhotdraw.draw.tool.DefaultDragTracker.mouseMoved(), org.jhotdraw.draw.tool.DefaultHandleTracker.mouseMoved(), org.jhotdraw.draw.tool.DefaultSelectAreaTracker.mouseMoved(), org.jhotdraw.draw.tool.DnDTracker.mouseMoved(), org.jhotdraw.draw.tool.TextAreaEditingTool.mousePressed(), org.jhotdraw.draw.tool.DefaultDragTracker.mouseReleased(), and org.jhotdraw.draw.tool.DnDTracker.mouseReleased().
viewToDrawing()
Point2D.Double org.jhotdraw.draw.tool.AbstractTool.viewToDrawing (Point p) protected
References org.jhotdraw.draw.tool.AbstractTool.constrainPoint(), and org.jhotdraw.draw.tool.AbstractTool.getView().
Referenced by org.jhotdraw.draw.tool.AbstractTool.constrainPoint(), org.jhotdraw.draw.tool.DelegationSelectionTool.getToolTipText(), org.jhotdraw.draw.tool.DelegationSelectionTool.handleDoubleClick(), org.jhotdraw.draw.tool.ConnectionTool.mouseDragged(), org.jhotdraw.draw.tool.BezierTool.mouseDragged(), org.jhotdraw.draw.tool.ConnectionTool.mousePressed(), org.jhotdraw.draw.tool.CreationTool.mousePressed(), org.jhotdraw.draw.tool.ConnectionTool.repaintConnectors(), and org.jhotdraw.draw.tool.DelegationSelectionTool.showPopupMenu().
Member Data Documentation
anchor
Point org.jhotdraw.draw.tool.AbstractTool.anchor = new Point() protected
Referenced by org.jhotdraw.draw.tool.BezierTool.deactivate(), org.jhotdraw.draw.tool.BezierTool.draw(), org.jhotdraw.draw.tool.DefaultHandleTracker.keyPressed(), org.jhotdraw.draw.tool.DefaultHandleTracker.keyReleased(), org.jhotdraw.draw.tool.CreationTool.mouseDragged(), org.jhotdraw.draw.tool.DefaultHandleTracker.mouseDragged(), org.jhotdraw.draw.tool.DefaultSelectAreaTracker.mouseDragged(), org.jhotdraw.draw.tool.BezierTool.mouseMoved(), org.jhotdraw.draw.tool.AbstractTool.mousePressed(), org.jhotdraw.draw.tool.BezierTool.mousePressed(), org.jhotdraw.draw.tool.ConnectionTool.mousePressed(), org.jhotdraw.draw.tool.CreationTool.mousePressed(), org.jhotdraw.draw.tool.DefaultDragTracker.mousePressed(), org.jhotdraw.draw.tool.DefaultHandleTracker.mousePressed(), org.jhotdraw.draw.tool.DnDTracker.mousePressed(), org.jhotdraw.draw.tool.SelectionTool.mousePressed(), org.jhotdraw.draw.tool.ConnectionTool.mouseReleased(), org.jhotdraw.draw.tool.BezierTool.mouseReleased(), org.jhotdraw.draw.tool.CreationTool.mouseReleased(), org.jhotdraw.draw.tool.DefaultDragTracker.mouseReleased(), and org.jhotdraw.draw.tool.DefaultHandleTracker.mouseReleased().
editor
DrawingEditor org.jhotdraw.draw.tool.AbstractTool.editor protected
Referenced by org.jhotdraw.draw.tool.AbstractTool.activate(), org.jhotdraw.draw.tool.BezierTool.activate(), org.jhotdraw.draw.tool.ConnectionTool.activate(), org.jhotdraw.draw.tool.CreationTool.activate(), org.jhotdraw.draw.tool.DefaultHandleTracker.activate(), org.jhotdraw.draw.tool.DefaultSelectAreaTracker.activate(), org.jhotdraw.draw.tool.ImageTool.activate(), org.jhotdraw.draw.tool.SelectionTool.activate(), org.jhotdraw.draw.tool.AbstractTool.deactivate(), org.jhotdraw.draw.tool.BezierTool.deactivate(), org.jhotdraw.draw.tool.ConnectionTool.deactivate(), org.jhotdraw.draw.tool.CreationTool.deactivate(), org.jhotdraw.draw.tool.DefaultHandleTracker.deactivate(), org.jhotdraw.draw.tool.DefaultSelectAreaTracker.deactivate(), org.jhotdraw.draw.tool.SelectionTool.deactivate(), org.jhotdraw.draw.tool.TextAreaCreationTool.deactivate(), org.jhotdraw.draw.tool.TextAreaEditingTool.deactivate(), org.jhotdraw.draw.tool.TextCreationTool.deactivate(), org.jhotdraw.draw.tool.TextEditingTool.deactivate(), org.jhotdraw.draw.tool.AbstractTool.getEditor(), org.jhotdraw.draw.tool.AbstractTool.getView(), org.jhotdraw.draw.tool.AbstractTool.keyPressed(), org.jhotdraw.draw.tool.DefaultDragTracker.mouseDragged(), org.jhotdraw.draw.tool.DefaultHandleTracker.mouseExited(), org.jhotdraw.draw.tool.DefaultSelectAreaTracker.mouseExited(), org.jhotdraw.draw.tool.DefaultDragTracker.mouseMoved(), org.jhotdraw.draw.tool.DefaultHandleTracker.mouseMoved(), org.jhotdraw.draw.tool.DefaultSelectAreaTracker.mouseMoved(), org.jhotdraw.draw.tool.DnDTracker.mouseMoved(), org.jhotdraw.draw.tool.AbstractTool.mousePressed(), org.jhotdraw.draw.tool.DefaultDragTracker.mouseReleased(), and org.jhotdraw.draw.tool.DnDTracker.mouseReleased().
isWorking
boolean org.jhotdraw.draw.tool.AbstractTool.isWorking protected
This is set to true, while the tool is doing some work. This prevents the currentView from being changed when a mouseEnter event is received.
Referenced by org.jhotdraw.draw.tool.BezierTool.draw(), org.jhotdraw.draw.tool.AbstractTool.mousePressed(), org.jhotdraw.draw.tool.AbstractTool.mouseReleased(), and org.jhotdraw.draw.tool.BezierTool.mouseReleased().
listenerList
EventListenerList org.jhotdraw.draw.tool.AbstractTool.listenerList = new EventListenerList() protected
Referenced by org.jhotdraw.draw.tool.AbstractTool.addToolListener(), org.jhotdraw.draw.tool.AbstractTool.addUndoableEditListener(), org.jhotdraw.draw.tool.AbstractTool.fireAreaInvalidated(), org.jhotdraw.draw.tool.AbstractTool.fireBoundsInvalidated(), org.jhotdraw.draw.tool.AbstractTool.fireToolDone(), org.jhotdraw.draw.tool.AbstractTool.fireToolStarted(), org.jhotdraw.draw.tool.AbstractTool.removeToolListener(), and org.jhotdraw.draw.tool.AbstractTool.removeUndoableEditListener().
The documentation for this class was generated from the following file:
jhotdraw-core/src/main/java/org/jhotdraw/draw/tool/AbstractTool.java