jhotdraw: org.jhotdraw.draw.handle.NullHandle Class Reference
org.jhotdraw.draw.handle.NullHandle Class Reference
Public Member Functions
NullHandle (Figure owner, Locator locator)
Cursor getCursor ()
void trackStart (Point anchor, int modifiersEx)
void trackStep (Point anchor, Point lead, int modifiersEx)
void trackEnd (Point anchor, Point lead, int modifiersEx)
void draw (Graphics2D g)
Public Member Functions inherited from org.jhotdraw.draw.handle.LocatorHandle
LocatorHandle (Figure owner, Locator l)
Point2D.Double getLocationOnDrawing ()
Point getLocation ()
Public Member Functions inherited from org.jhotdraw.draw.handle.AbstractHandle
AbstractHandle (Figure owner)
void addHandleListener (HandleListener l)
void removeHandleListener (HandleListener l)
Figure getOwner ()
void setView (DrawingView view)
DrawingView getView ()
DrawingEditor getEditor ()
boolean contains (Point p)
void invalidate ()
void dispose ()
void areaInvalidated (FigureEvent evt)
void figureAdded (FigureEvent e)
void figureRemoved (FigureEvent e)
void figureRequestRemove (FigureEvent e)
void figureChanged (FigureEvent evt)
boolean isCombinableWith (Handle handle)
void keyTyped (KeyEvent evt)
void keyReleased (KeyEvent evt)
void keyPressed (KeyEvent evt)
final Rectangle getBounds ()
Rectangle getDrawingArea ()
void trackDoubleClick (Point p, int modifiersEx)
void attributeChanged (FigureEvent e)
void viewTransformChanged ()
Collection< Handle > createSecondaryHandles ()
String getToolTipText (Point p)
void setToolTipText (String newValue)
void figureHandlesChanged (FigureEvent e)
Static Public Member Functions
static void addLeadHandles (Figure f, Collection< Handle > handles)
Additional Inherited Members
Protected Member Functions inherited from org.jhotdraw.draw.handle.LocatorHandle
Rectangle basicGetBounds ()
Protected Member Functions inherited from org.jhotdraw.draw.handle.AbstractHandle
int getHandlesize ()
void fireAreaInvalidated (Rectangle invalidatedArea)
void fireUndoableEditHappened (UndoableEdit edit)
void fireHandleRequestRemove (Rectangle invalidatedArea)
void fireHandleRequestSecondaryHandles ()
void drawCircle (Graphics2D g, Color fill, Color stroke)
void drawRectangle (Graphics2D g, Color fill, Color stroke)
void drawDiamond (Graphics2D g, Color fill, Color stroke)
void updateBounds ()
Protected Attributes inherited from org.jhotdraw.draw.handle.AbstractHandle
DrawingView view
EventListenerList listenerList = new EventListenerList()
Detailed Description
A handle that doesn't change the owned figure. Its only purpose is to show feedback that a figure is selected.
Author
Werner Randelshofer
Version
$Id$
Constructor & Destructor Documentation
NullHandle()
org.jhotdraw.draw.handle.NullHandle.NullHandle (Figure owner, Locator locator)
Creates a new instance.
Referenced by org.jhotdraw.draw.handle.NullHandle.addLeadHandles().
Member Function Documentation
addLeadHandles()
static void org.jhotdraw.draw.handle.NullHandle.addLeadHandles (Figure f, Collection< Handle > handles) static
Creates handles for each lead of a figure and adds them to the provided collection.
References org.jhotdraw.draw.handle.NullHandle.NullHandle().
draw()
void org.jhotdraw.draw.handle.NullHandle.draw (Graphics2D g)
Draws this handle. Null Handles are drawn as unfilled rectangles.
Reimplemented from org.jhotdraw.draw.handle.AbstractHandle.
References org.jhotdraw.draw.handle.AbstractHandle.drawRectangle(), org.jhotdraw.draw.handle.AbstractHandle.getEditor(), org.jhotdraw.draw.handle.HandleAttributeKeys.NULL_HANDLE_FILL_COLOR, and org.jhotdraw.draw.handle.HandleAttributeKeys.NULL_HANDLE_STROKE_COLOR.
getCursor()
Cursor org.jhotdraw.draw.handle.NullHandle.getCursor ()
Returns a cursor for the handle.
Reimplemented from org.jhotdraw.draw.handle.AbstractHandle.
trackEnd()
void org.jhotdraw.draw.handle.NullHandle.trackEnd (Point anchor, Point lead, int modifiersEx)
Tracks the end of the interaction.
Parameters
anchor the position where the interaction started
lead the current position
Implements org.jhotdraw.draw.handle.Handle.
trackStart()
void org.jhotdraw.draw.handle.NullHandle.trackStart (Point anchor, int modifiersEx)
Tracks the start of the interaction. The default implementation does nothing.
Parameters
anchor the position where the interaction started
Implements org.jhotdraw.draw.handle.Handle.
trackStep()
void org.jhotdraw.draw.handle.NullHandle.trackStep (Point anchor, Point lead, int modifiersEx)
Tracks a step of the interaction.
Parameters
anchor the position where the interaction started
lead the current position
Implements org.jhotdraw.draw.handle.Handle.
The documentation for this class was generated from the following file:
jhotdraw-core/src/main/java/org/jhotdraw/draw/handle/NullHandle.java