jhotdraw: org.jhotdraw.draw.figure.DiamondFigure Class Reference
org.jhotdraw.draw.figure.DiamondFigure Class Reference
Public Member Functions
DiamondFigure ()
DiamondFigure (double x, double y, double width, double height)
Rectangle2D.Double getBounds ()
Rectangle2D.Double getDrawingArea ()
boolean contains (Point2D.Double p)
void setBounds (Point2D.Double anchor, Point2D.Double lead)
void transform (AffineTransform tx)
void restoreTransformTo (Object geometry)
Object getTransformRestoreData ()
Connector findConnector (Point2D.Double p, ConnectionFigure prototype)
Connector findCompatibleConnector (Connector c, boolean isStart)
DiamondFigure clone ()
Public Member Functions inherited from org.jhotdraw.draw.figure.AbstractAttributedFigure
AbstractAttributedFigure ()
void setAttributeEnabled (AttributeKey<?> key, boolean b)
boolean isAttributeEnabled (AttributeKey<?> key)
void setAttributes (Map< AttributeKey<?>, Object > map)
Map< AttributeKey<?>, Object > getAttributes ()
Object getAttributesRestoreData ()
void restoreAttributesTo (Object restoreData)
void draw (Graphics2D g)
double getStrokeMiterLimitFactor ()
Rectangle2D.Double getDrawingArea (double factor)
void write (DOMOutput out) throws IOException
void read (DOMInput in) throws IOException
boolean hasAttribute (AttributeKey<?> key)
Public Member Functions inherited from org.jhotdraw.draw.figure.AbstractFigure
AbstractFigure ()
void addFigureListener (FigureListener l)
void removeFigureListener (FigureListener l)
void addNotify (Drawing d)
void removeNotify (Drawing d)
void fireAreaInvalidated ()
void fireFigureChanged ()
void remap (Map< Figure, Figure > oldToNew, boolean disconnectIfNotInMap)
Collection< Handle > createHandles (int detailLevel)
Cursor getCursor (Point2D.Double p)
final void setBounds (Rectangle2D.Double bounds)
void willChange ()
void changed ()
boolean includes (Figure figure)
Figure findFigureInside (Point2D.Double p)
Collection< Action > getActions (Point2D.Double p)
Tool getTool (Point2D.Double p)
boolean handleMouseClick (Point2D.Double p, MouseEvent evt, DrawingView view)
boolean handleDrop (Point2D.Double p, Collection< Figure > droppedFigures, DrawingView view)
Point2D.Double getEndPoint ()
Point2D.Double getStartPoint ()
Dimension2DDouble getPreferredSize ()
boolean isConnectable ()
void setConnectable (boolean newValue)
boolean isSelectable ()
void setSelectable (boolean newValue)
boolean isRemovable ()
void setRemovable (boolean newValue)
boolean isTransformable ()
void setTransformable (boolean newValue)
boolean isVisible ()
void setVisible (boolean newValue)
Collection< Figure > getDecomposition ()
void requestRemove ()
int getLayer ()
String getToolTipText (Point2D.Double p)
String toString ()
Collection< Connector > getConnectors (ConnectionFigure prototype)
Public Member Functions inherited from org.jhotdraw.draw.figure.Figure
void addPropertyChangeListener (PropertyChangeListener listener)
void removePropertyChangeListener (PropertyChangeListener listener)
Static Public Attributes
static final AttributeKey< Boolean > IS_QUADRATIC = new AttributeKey<Boolean>("isQuadratic", Boolean.class, false)
Static Public Attributes inherited from org.jhotdraw.draw.figure.Figure
static final String CONNECTABLE_PROPERTY = "connectable"
static final String REMOVABLE_PROPERTY = "removable"
static final String SELECTABLE_PROPERTY = "selectable"
static final String TRANSFORMABLE_PROPERTY = "transformable"
Protected Member Functions
void drawFill (Graphics2D g)
void drawStroke (Graphics2D g)
Protected Member Functions inherited from org.jhotdraw.draw.figure.AbstractAttributedFigure
abstract void drawFill (java.awt.Graphics2D g)
abstract void drawStroke (java.awt.Graphics2D g)
void drawText (java.awt.Graphics2D g)
void writeAttributes (DOMOutput out) throws IOException
void readAttributes (DOMInput in) throws IOException
AttributeKey<?> getAttributeKey (String name)
void applyAttributesTo (Figure that)
Protected Member Functions inherited from org.jhotdraw.draw.figure.AbstractFigure
Drawing getDrawing ()
Object getLock ()
void fireAreaInvalidated (Rectangle2D.Double invalidatedArea)
void fireAreaInvalidated (FigureEvent event)
void fireFigureRequestRemove ()
void fireFigureAdded ()
void fireFigureRemoved ()
void fireFigureChanged (Rectangle2D.Double changedArea)
void fireFigureChanged (FigureEvent event)
void fireFigureHandlesChanged ()
void fireUndoableEditHappened (UndoableEdit edit)
void invalidate ()
boolean isChanging ()
int getChangingDepth ()
void validate ()
FontRenderContext getFontRenderContext ()
Additional Inherited Members
Protected Attributes inherited from org.jhotdraw.draw.figure.AbstractFigure
EventListenerList listenerList = new EventListenerList()
int changingDepth = 0
Detailed Description
A Figure with a diamond shape.
The diamond vertices are located at the midpoints of its enclosing rectangle.
Author
Werner Randelshofer
Version
$Id$
Constructor & Destructor Documentation
DiamondFigure() [1/2]
org.jhotdraw.draw.figure.DiamondFigure.DiamondFigure ()
Creates a new instance.
Referenced by org.jhotdraw.draw.figure.DiamondFigure.clone().
DiamondFigure() [2/2]
org.jhotdraw.draw.figure.DiamondFigure.DiamondFigure (double x, double y, double width, double height)
Member Function Documentation
clone()
DiamondFigure org.jhotdraw.draw.figure.DiamondFigure.clone ()
Returns a clone of the figure, with clones of all aggregated figures, such as children and decorators. The cloned figure does not clone the list of FigureListeners from its original.
Reimplemented from org.jhotdraw.draw.figure.AbstractAttributedFigure.
References org.jhotdraw.draw.figure.DiamondFigure.clone(), and org.jhotdraw.draw.figure.DiamondFigure.DiamondFigure().
Referenced by org.jhotdraw.draw.figure.DiamondFigure.clone().
contains()
boolean org.jhotdraw.draw.figure.DiamondFigure.contains (Point2D.Double p)
Checks if a Point2D.Double is inside the figure.
Implements org.jhotdraw.draw.figure.Figure.
References org.jhotdraw.draw.AttributeKeys.getPerpendicularFillGrowth(), and org.jhotdraw.draw.figure.DiamondFigure.IS_QUADRATIC.
drawFill()
void org.jhotdraw.draw.figure.DiamondFigure.drawFill (Graphics2D g) protected
References org.jhotdraw.draw.AttributeKeys.getPerpendicularFillGrowth(), org.jhotdraw.draw.AttributeKeys.getScaleFactorFromGraphics(), and org.jhotdraw.draw.figure.DiamondFigure.IS_QUADRATIC.
drawStroke()
void org.jhotdraw.draw.figure.DiamondFigure.drawStroke (Graphics2D g) protected
References org.jhotdraw.draw.AttributeKeys.getPerpendicularDrawGrowth(), org.jhotdraw.draw.AttributeKeys.getScaleFactorFromGraphics(), and org.jhotdraw.draw.figure.DiamondFigure.IS_QUADRATIC.
findCompatibleConnector()
Connector org.jhotdraw.draw.figure.DiamondFigure.findCompatibleConnector (Connector c, boolean isStartConnector)
Gets a compatible connector. If the provided connector is part of this figure, return the connector. If the provided connector is part of another figure, return a connector with the same semantics for this figure. Returns null, if no compatible connector is available.
Reimplemented from org.jhotdraw.draw.figure.AbstractFigure.
findConnector()
Connector org.jhotdraw.draw.figure.DiamondFigure.findConnector (Point2D.Double p, ConnectionFigure prototype)
Returns the Figures connector for the specified location. By default a ChopDiamondConnector is returned.
See also
ChopDiamondConnector
Reimplemented from org.jhotdraw.draw.figure.AbstractFigure.
getBounds()
Rectangle2D.Double org.jhotdraw.draw.figure.DiamondFigure.getBounds ()
Returns the untransformed logical bounds of the figure as a Rectangle.
The bounds are used by Handle objects for adjusting the figure and for aligning the figure on a grid.
Implements org.jhotdraw.draw.figure.Figure.
getDrawingArea()
Rectangle2D.Double org.jhotdraw.draw.figure.DiamondFigure.getDrawingArea ()
Returns the drawing area of the figure as a Rectangle.
The drawing area is used to inform DrawingView about the area that is needed to draw this figure.
The drawing area needs to be large enough, to take line width, line caps and other decorations into account that exceed the bounds of the Figure.
Reimplemented from org.jhotdraw.draw.figure.AbstractAttributedFigure.
References org.jhotdraw.draw.AttributeKeys.getPerpendicularHitGrowth(), and org.jhotdraw.draw.figure.DiamondFigure.IS_QUADRATIC.
getTransformRestoreData()
Object org.jhotdraw.draw.figure.DiamondFigure.getTransformRestoreData ()
Gets data which can be used to restore the transformation of the figure without loss of precision, after a transform has been applied to it.
See also
transform(AffineTransform)
Implements org.jhotdraw.draw.figure.Figure.
restoreTransformTo()
void org.jhotdraw.draw.figure.DiamondFigure.restoreTransformTo (Object restoreData)
Restores the transform of the figure to a previously stored state.
Implements org.jhotdraw.draw.figure.Figure.
setBounds()
void org.jhotdraw.draw.figure.DiamondFigure.setBounds (Point2D.Double start, Point2D.Double end)
Sets the logical and untransformed bounds of the figure.
This is used by Tool's which create a new Figure and by Tool's which connect a Figure to another Figure.
This is a basic operation which does not fire events. Use the following code sequence, if you need event firing:
figure.willChange();
figure.setBounds(...);
figure.changed();
Parameters
start the start point of the bounds
end the end point of the bounds
See also
getBounds
Reimplemented from org.jhotdraw.draw.figure.AbstractFigure.
Referenced by org.jhotdraw.draw.figure.DiamondFigure.transform().
transform()
void org.jhotdraw.draw.figure.DiamondFigure.transform (AffineTransform tx)
Moves the Figure to a new location.
Parameters
tx the transformation matrix.
Implements org.jhotdraw.draw.figure.Figure.
References org.jhotdraw.draw.figure.AbstractFigure.getEndPoint(), org.jhotdraw.draw.figure.AbstractFigure.getStartPoint(), and org.jhotdraw.draw.figure.DiamondFigure.setBounds().
Member Data Documentation
IS_QUADRATIC
final AttributeKey<Boolean> org.jhotdraw.draw.figure.DiamondFigure.IS_QUADRATIC = new AttributeKey<Boolean>("isQuadratic", Boolean.class, false) static
If the attribute IS_QUADRATIC is put to true, all sides of the diamond have the same length.
Referenced by org.jhotdraw.draw.connector.ChopDiamondConnector.chop(), org.jhotdraw.draw.figure.DiamondFigure.contains(), org.jhotdraw.draw.figure.DiamondFigure.drawFill(), org.jhotdraw.draw.figure.DiamondFigure.drawStroke(), and org.jhotdraw.draw.figure.DiamondFigure.getDrawingArea().
The documentation for this class was generated from the following file:
jhotdraw-core/src/main/java/org/jhotdraw/draw/figure/DiamondFigure.java