jhotdraw: org.jhotdraw.draw.figure.RectangleFigure Class Reference
org.jhotdraw.draw.figure.RectangleFigure Class Reference
Public Member Functions
RectangleFigure ()
RectangleFigure (double x, double y, double width, double height)
Rectangle2D.Double getBounds ()
Rectangle2D.Double getDrawingArea ()
boolean contains (Point2D.Double p)
void setBounds (Point2D.Double anchor, Point2D.Double lead)
void transform (AffineTransform tx)
void restoreTransformTo (Object geometry)
Object getTransformRestoreData ()
RectangleFigure clone ()
Public Member Functions inherited from org.jhotdraw.draw.figure.AbstractAttributedFigure
AbstractAttributedFigure ()
void setAttributeEnabled (AttributeKey<?> key, boolean b)
boolean isAttributeEnabled (AttributeKey<?> key)
void setAttributes (Map< AttributeKey<?>, Object > map)
Map< AttributeKey<?>, Object > getAttributes ()
Object getAttributesRestoreData ()
void restoreAttributesTo (Object restoreData)
void draw (Graphics2D g)
double getStrokeMiterLimitFactor ()
Rectangle2D.Double getDrawingArea (double factor)
void write (DOMOutput out) throws IOException
void read (DOMInput in) throws IOException
boolean hasAttribute (AttributeKey<?> key)
Public Member Functions inherited from org.jhotdraw.draw.figure.AbstractFigure
AbstractFigure ()
void addFigureListener (FigureListener l)
void removeFigureListener (FigureListener l)
void addNotify (Drawing d)
void removeNotify (Drawing d)
void fireAreaInvalidated ()
void fireFigureChanged ()
void remap (Map< Figure, Figure > oldToNew, boolean disconnectIfNotInMap)
Collection< Handle > createHandles (int detailLevel)
Cursor getCursor (Point2D.Double p)
final void setBounds (Rectangle2D.Double bounds)
void willChange ()
void changed ()
Connector findConnector (Point2D.Double p, ConnectionFigure prototype)
boolean includes (Figure figure)
Figure findFigureInside (Point2D.Double p)
Connector findCompatibleConnector (Connector c, boolean isStart)
Collection< Action > getActions (Point2D.Double p)
Tool getTool (Point2D.Double p)
boolean handleMouseClick (Point2D.Double p, MouseEvent evt, DrawingView view)
boolean handleDrop (Point2D.Double p, Collection< Figure > droppedFigures, DrawingView view)
Point2D.Double getEndPoint ()
Point2D.Double getStartPoint ()
Dimension2DDouble getPreferredSize ()
boolean isConnectable ()
void setConnectable (boolean newValue)
boolean isSelectable ()
void setSelectable (boolean newValue)
boolean isRemovable ()
void setRemovable (boolean newValue)
boolean isTransformable ()
void setTransformable (boolean newValue)
boolean isVisible ()
void setVisible (boolean newValue)
Collection< Figure > getDecomposition ()
void requestRemove ()
int getLayer ()
String getToolTipText (Point2D.Double p)
String toString ()
Collection< Connector > getConnectors (ConnectionFigure prototype)
Public Member Functions inherited from org.jhotdraw.draw.figure.Figure
void addPropertyChangeListener (PropertyChangeListener listener)
void removePropertyChangeListener (PropertyChangeListener listener)
Protected Member Functions
void drawFill (Graphics2D g)
void drawStroke (Graphics2D g)
Protected Member Functions inherited from org.jhotdraw.draw.figure.AbstractAttributedFigure
abstract void drawFill (java.awt.Graphics2D g)
abstract void drawStroke (java.awt.Graphics2D g)
void drawText (java.awt.Graphics2D g)
void writeAttributes (DOMOutput out) throws IOException
void readAttributes (DOMInput in) throws IOException
AttributeKey<?> getAttributeKey (String name)
void applyAttributesTo (Figure that)
Protected Member Functions inherited from org.jhotdraw.draw.figure.AbstractFigure
Drawing getDrawing ()
Object getLock ()
void fireAreaInvalidated (Rectangle2D.Double invalidatedArea)
void fireAreaInvalidated (FigureEvent event)
void fireFigureRequestRemove ()
void fireFigureAdded ()
void fireFigureRemoved ()
void fireFigureChanged (Rectangle2D.Double changedArea)
void fireFigureChanged (FigureEvent event)
void fireFigureHandlesChanged ()
void fireUndoableEditHappened (UndoableEdit edit)
void invalidate ()
boolean isChanging ()
int getChangingDepth ()
void validate ()
FontRenderContext getFontRenderContext ()
Protected Attributes
Rectangle2D.Double rectangle
Protected Attributes inherited from org.jhotdraw.draw.figure.AbstractFigure
EventListenerList listenerList = new EventListenerList()
int changingDepth = 0
Additional Inherited Members
Static Public Attributes inherited from org.jhotdraw.draw.figure.Figure
static final String CONNECTABLE_PROPERTY = "connectable"
static final String REMOVABLE_PROPERTY = "removable"
static final String SELECTABLE_PROPERTY = "selectable"
static final String TRANSFORMABLE_PROPERTY = "transformable"
Detailed Description
A Figure with a rectangular shape.
Author
Werner Randelshofer
Version
$Id$
Constructor & Destructor Documentation
RectangleFigure() [1/2]
org.jhotdraw.draw.figure.RectangleFigure.RectangleFigure ()
Creates a new instance.
Referenced by org.jhotdraw.draw.figure.RectangleFigure.clone().
RectangleFigure() [2/2]
org.jhotdraw.draw.figure.RectangleFigure.RectangleFigure (double x, double y, double width, double height)
References org.jhotdraw.draw.figure.RectangleFigure.rectangle.
Member Function Documentation
clone()
RectangleFigure org.jhotdraw.draw.figure.RectangleFigure.clone ()
Returns a clone of the figure, with clones of all aggregated figures, such as children and decorators. The cloned figure does not clone the list of FigureListeners from its original.
Reimplemented from org.jhotdraw.draw.figure.AbstractAttributedFigure.
References org.jhotdraw.draw.figure.RectangleFigure.clone(), org.jhotdraw.draw.figure.RectangleFigure.rectangle, and org.jhotdraw.draw.figure.RectangleFigure.RectangleFigure().
Referenced by org.jhotdraw.draw.figure.RectangleFigure.clone().
contains()
boolean org.jhotdraw.draw.figure.RectangleFigure.contains (Point2D.Double p)
Checks if a Point2D.Double is inside the figure.
Implements org.jhotdraw.draw.figure.Figure.
References org.jhotdraw.draw.AttributeKeys.getPerpendicularHitGrowth(), and org.jhotdraw.draw.figure.RectangleFigure.rectangle.
drawFill()
void org.jhotdraw.draw.figure.RectangleFigure.drawFill (Graphics2D g) protected
References org.jhotdraw.draw.AttributeKeys.getPerpendicularFillGrowth(), org.jhotdraw.draw.AttributeKeys.getScaleFactorFromGraphics(), and org.jhotdraw.draw.figure.RectangleFigure.rectangle.
drawStroke()
void org.jhotdraw.draw.figure.RectangleFigure.drawStroke (Graphics2D g) protected
References org.jhotdraw.draw.AttributeKeys.getPerpendicularDrawGrowth(), org.jhotdraw.draw.AttributeKeys.getScaleFactorFromGraphics(), and org.jhotdraw.draw.figure.RectangleFigure.rectangle.
getBounds()
Rectangle2D.Double org.jhotdraw.draw.figure.RectangleFigure.getBounds ()
Returns the untransformed logical bounds of the figure as a Rectangle.
The bounds are used by Handle objects for adjusting the figure and for aligning the figure on a grid.
Implements org.jhotdraw.draw.figure.Figure.
References org.jhotdraw.draw.figure.RectangleFigure.rectangle.
getDrawingArea()
Rectangle2D.Double org.jhotdraw.draw.figure.RectangleFigure.getDrawingArea ()
Returns the drawing area of the figure as a Rectangle.
The drawing area is used to inform DrawingView about the area that is needed to draw this figure.
The drawing area needs to be large enough, to take line width, line caps and other decorations into account that exceed the bounds of the Figure.
Reimplemented from org.jhotdraw.draw.figure.AbstractAttributedFigure.
References org.jhotdraw.draw.AttributeKeys.getPerpendicularHitGrowth(), and org.jhotdraw.draw.figure.RectangleFigure.rectangle.
getTransformRestoreData()
Object org.jhotdraw.draw.figure.RectangleFigure.getTransformRestoreData ()
Gets data which can be used to restore the transformation of the figure without loss of precision, after a transform has been applied to it.
See also
transform(AffineTransform)
Implements org.jhotdraw.draw.figure.Figure.
References org.jhotdraw.draw.figure.RectangleFigure.rectangle.
restoreTransformTo()
void org.jhotdraw.draw.figure.RectangleFigure.restoreTransformTo (Object restoreData)
Restores the transform of the figure to a previously stored state.
Implements org.jhotdraw.draw.figure.Figure.
References org.jhotdraw.draw.figure.RectangleFigure.rectangle.
setBounds()
void org.jhotdraw.draw.figure.RectangleFigure.setBounds (Point2D.Double start, Point2D.Double end)
Sets the logical and untransformed bounds of the figure.
This is used by Tool's which create a new Figure and by Tool's which connect a Figure to another Figure.
This is a basic operation which does not fire events. Use the following code sequence, if you need event firing:
figure.willChange();
figure.setBounds(...);
figure.changed();
Parameters
start the start point of the bounds
end the end point of the bounds
See also
getBounds
Reimplemented from org.jhotdraw.draw.figure.AbstractFigure.
References org.jhotdraw.draw.figure.RectangleFigure.rectangle.
Referenced by org.jhotdraw.draw.figure.RectangleFigure.transform().
transform()
void org.jhotdraw.draw.figure.RectangleFigure.transform (AffineTransform tx)
Moves the Figure to a new location.
Parameters
tx the transformation matrix.
Implements org.jhotdraw.draw.figure.Figure.
References org.jhotdraw.draw.figure.AbstractFigure.getEndPoint(), org.jhotdraw.draw.figure.AbstractFigure.getStartPoint(), and org.jhotdraw.draw.figure.RectangleFigure.setBounds().
Member Data Documentation
rectangle
Rectangle2D.Double org.jhotdraw.draw.figure.RectangleFigure.rectangle protected
Referenced by org.jhotdraw.draw.figure.RectangleFigure.clone(), org.jhotdraw.draw.figure.RectangleFigure.contains(), org.jhotdraw.draw.figure.RectangleFigure.drawFill(), org.jhotdraw.draw.figure.RectangleFigure.drawStroke(), org.jhotdraw.draw.figure.RectangleFigure.getBounds(), org.jhotdraw.draw.figure.RectangleFigure.getDrawingArea(), org.jhotdraw.draw.figure.RectangleFigure.getTransformRestoreData(), org.jhotdraw.draw.figure.RectangleFigure.RectangleFigure(), org.jhotdraw.draw.figure.RectangleFigure.restoreTransformTo(), and org.jhotdraw.draw.figure.RectangleFigure.setBounds().
The documentation for this class was generated from the following file:
jhotdraw-core/src/main/java/org/jhotdraw/draw/figure/RectangleFigure.java