jhotdraw: org.jhotdraw.draw.action.EditorColorChooserAction Class Reference
org.jhotdraw.draw.action.EditorColorChooserAction Class Reference
Public Member Functions
EditorColorChooserAction (DrawingEditor editor, AttributeKey< Color > key)
EditorColorChooserAction (DrawingEditor editor, AttributeKey< Color > key, Icon icon)
EditorColorChooserAction (DrawingEditor editor, AttributeKey< Color > key, String name)
EditorColorChooserAction (DrawingEditor editor, final AttributeKey< Color > key, String name, Icon icon)
EditorColorChooserAction (DrawingEditor editor, final AttributeKey< Color > key, String name, Icon icon, Map< AttributeKey<?>, Object > fixedAttributes)
void actionPerformed (java.awt.event.ActionEvent e)
void selectionChanged (FigureSelectionEvent evt)
Public Member Functions inherited from org.jhotdraw.draw.action.AttributeAction
AttributeAction (DrawingEditor editor, Map< AttributeKey<?>, Object > attributes, String name, Icon icon)
void applyAttributesTo (final Map< AttributeKey<?>, Object > a, Set< Figure > figures)
Public Member Functions inherited from org.jhotdraw.draw.action.AbstractSelectedAction
AbstractSelectedAction (DrawingEditor editor)
void dispose ()
void setEditor (DrawingEditor editor)
DrawingEditor getEditor ()
void setUpdateEnabledState (boolean newValue)
boolean isUpdatEnabledState ()
Protected Member Functions
Color getInitialColor ()
Protected Member Functions inherited from org.jhotdraw.draw.action.AttributeAction
void updateEnabledState ()
Protected Member Functions inherited from org.jhotdraw.draw.action.AbstractSelectedAction
DrawingView getView ()
Drawing getDrawing ()
void fireUndoableEditHappened (UndoableEdit edit)
Protected Attributes
AttributeKey< Color > key
Protected Attributes inherited from org.jhotdraw.draw.action.AttributeAction
Map< AttributeKey<?>, Object > attributes
Static Protected Attributes
static JColorChooser colorChooser
Detailed Description
EditorColorChooserAction.
The behavior for choosing the initial color of the JColorChooser matches with EditorColorIcon.
Author
Werner Randelshofer
Version
$Id$
Constructor & Destructor Documentation
EditorColorChooserAction() [1/5]
org.jhotdraw.draw.action.EditorColorChooserAction.EditorColorChooserAction (DrawingEditor editor, AttributeKey< Color > key)
Creates a new instance.
References org.jhotdraw.draw.action.EditorColorChooserAction.key, and org.jhotdraw.draw.action.AttributeAction.updateEnabledState().
EditorColorChooserAction() [2/5]
org.jhotdraw.draw.action.EditorColorChooserAction.EditorColorChooserAction (DrawingEditor editor, AttributeKey< Color > key, Icon icon)
Creates a new instance.
References org.jhotdraw.draw.action.EditorColorChooserAction.key.
EditorColorChooserAction() [3/5]
org.jhotdraw.draw.action.EditorColorChooserAction.EditorColorChooserAction (DrawingEditor editor, AttributeKey< Color > key, String name)
Creates a new instance.
References org.jhotdraw.draw.action.EditorColorChooserAction.key.
EditorColorChooserAction() [4/5]
org.jhotdraw.draw.action.EditorColorChooserAction.EditorColorChooserAction (DrawingEditor editor, final AttributeKey< Color > key, String name, Icon icon)
References org.jhotdraw.draw.action.EditorColorChooserAction.key.
EditorColorChooserAction() [5/5]
org.jhotdraw.draw.action.EditorColorChooserAction.EditorColorChooserAction (DrawingEditor editor, final AttributeKey< Color > key, String name, Icon icon, Map< AttributeKey<?>, Object > fixedAttributes)
References org.jhotdraw.draw.action.EditorColorChooserAction.key, and org.jhotdraw.draw.action.AttributeAction.updateEnabledState().
Member Function Documentation
actionPerformed()
void org.jhotdraw.draw.action.EditorColorChooserAction.actionPerformed (java.awt.event.ActionEvent e)
Reimplemented from org.jhotdraw.draw.action.AttributeAction.
Reimplemented in org.jhotdraw.draw.action.DrawingColorChooserAction.
References org.jhotdraw.draw.action.AttributeAction.applyAttributesTo(), org.jhotdraw.draw.action.AttributeAction.attributes, org.jhotdraw.draw.action.EditorColorChooserAction.colorChooser, org.jhotdraw.draw.action.EditorColorChooserAction.getInitialColor(), org.jhotdraw.draw.action.AbstractSelectedAction.getView(), and org.jhotdraw.draw.action.EditorColorChooserAction.key.
getInitialColor()
Color org.jhotdraw.draw.action.EditorColorChooserAction.getInitialColor () protected
Reimplemented in org.jhotdraw.draw.action.SelectionColorChooserAction, and org.jhotdraw.draw.action.DrawingColorChooserAction.
References org.jhotdraw.draw.DrawingEditor.getDefaultAttribute(), org.jhotdraw.draw.action.AbstractSelectedAction.getEditor(), and org.jhotdraw.draw.action.EditorColorChooserAction.key.
Referenced by org.jhotdraw.draw.action.EditorColorChooserAction.actionPerformed().
selectionChanged()
void org.jhotdraw.draw.action.EditorColorChooserAction.selectionChanged (FigureSelectionEvent evt)
Member Data Documentation
colorChooser
JColorChooser org.jhotdraw.draw.action.EditorColorChooserAction.colorChooser static protected
Referenced by org.jhotdraw.draw.action.DrawingColorChooserAction.actionPerformed(), and org.jhotdraw.draw.action.EditorColorChooserAction.actionPerformed().
key
AttributeKey<Color> org.jhotdraw.draw.action.EditorColorChooserAction.key protected
Referenced by org.jhotdraw.draw.action.DrawingColorChooserAction.actionPerformed(), org.jhotdraw.draw.action.EditorColorChooserAction.actionPerformed(), org.jhotdraw.draw.action.DrawingColorChooserAction.DrawingColorChooserAction(), org.jhotdraw.draw.action.EditorColorChooserAction.EditorColorChooserAction(), org.jhotdraw.draw.action.DrawingColorChooserAction.getInitialColor(), org.jhotdraw.draw.action.EditorColorChooserAction.getInitialColor(), org.jhotdraw.draw.action.SelectionColorChooserAction.getInitialColor(), and org.jhotdraw.draw.action.SelectionColorChooserAction.SelectionColorChooserAction().
The documentation for this class was generated from the following file:
jhotdraw-core/src/main/java/org/jhotdraw/draw/action/EditorColorChooserAction.java