jhotdraw: org.jhotdraw.draw.figure.AbstractAttributedDecoratedFigure Class Reference
org.jhotdraw.draw.figure.AbstractAttributedDecoratedFigure Class Reference abstract
Public Member Functions
final void draw (Graphics2D g)
final Rectangle2D.Double getDrawingArea ()
void setDecorator (Figure newValue)
Figure getDecorator ()
final boolean contains (Point2D.Double p)
void read (DOMInput in) throws IOException
void write (DOMOutput out) throws IOException
AbstractAttributedDecoratedFigure clone ()
Public Member Functions inherited from org.jhotdraw.draw.figure.AbstractAttributedFigure
AbstractAttributedFigure ()
void setAttributeEnabled (AttributeKey<?> key, boolean b)
boolean isAttributeEnabled (AttributeKey<?> key)
void setAttributes (Map< AttributeKey<?>, Object > map)
Map< AttributeKey<?>, Object > getAttributes ()
Object getAttributesRestoreData ()
void restoreAttributesTo (Object restoreData)
double getStrokeMiterLimitFactor ()
Rectangle2D.Double getDrawingArea (double factor)
boolean hasAttribute (AttributeKey<?> key)
Public Member Functions inherited from org.jhotdraw.draw.figure.AbstractFigure
AbstractFigure ()
void addFigureListener (FigureListener l)
void removeFigureListener (FigureListener l)
void addNotify (Drawing d)
void removeNotify (Drawing d)
void fireAreaInvalidated ()
void fireFigureChanged ()
void remap (Map< Figure, Figure > oldToNew, boolean disconnectIfNotInMap)
Collection< Handle > createHandles (int detailLevel)
Cursor getCursor (Point2D.Double p)
final void setBounds (Rectangle2D.Double bounds)
void setBounds (Point2D.Double anchor, Point2D.Double lead)
void willChange ()
void changed ()
Connector findConnector (Point2D.Double p, ConnectionFigure prototype)
boolean includes (Figure figure)
Figure findFigureInside (Point2D.Double p)
Connector findCompatibleConnector (Connector c, boolean isStart)
Collection< Action > getActions (Point2D.Double p)
Tool getTool (Point2D.Double p)
boolean handleMouseClick (Point2D.Double p, MouseEvent evt, DrawingView view)
boolean handleDrop (Point2D.Double p, Collection< Figure > droppedFigures, DrawingView view)
Point2D.Double getEndPoint ()
Point2D.Double getStartPoint ()
Dimension2DDouble getPreferredSize ()
boolean isConnectable ()
void setConnectable (boolean newValue)
boolean isSelectable ()
void setSelectable (boolean newValue)
boolean isRemovable ()
void setRemovable (boolean newValue)
boolean isTransformable ()
void setTransformable (boolean newValue)
boolean isVisible ()
void setVisible (boolean newValue)
Collection< Figure > getDecomposition ()
void requestRemove ()
int getLayer ()
String getToolTipText (Point2D.Double p)
String toString ()
Collection< Connector > getConnectors (ConnectionFigure prototype)
Public Member Functions inherited from org.jhotdraw.draw.figure.Figure
Rectangle2D.Double getBounds ()
Object getTransformRestoreData ()
void restoreTransformTo (Object restoreData)
void transform (AffineTransform tx)
void addPropertyChangeListener (PropertyChangeListener listener)
void removePropertyChangeListener (PropertyChangeListener listener)
Protected Member Functions
void drawFigure (Graphics2D g)
void drawDecorator (Graphics2D g)
Rectangle2D.Double getFigureDrawingArea ()
void updateDecoratorBounds ()
abstract boolean figureContains (Point2D.Double p)
void writeDecorator (DOMOutput out) throws IOException
void readDecorator (DOMInput in) throws IOException
Protected Member Functions inherited from org.jhotdraw.draw.figure.AbstractAttributedFigure
abstract void drawFill (java.awt.Graphics2D g)
abstract void drawStroke (java.awt.Graphics2D g)
void drawText (java.awt.Graphics2D g)
void writeAttributes (DOMOutput out) throws IOException
void readAttributes (DOMInput in) throws IOException
AttributeKey<?> getAttributeKey (String name)
void applyAttributesTo (Figure that)
Protected Member Functions inherited from org.jhotdraw.draw.figure.AbstractFigure
Drawing getDrawing ()
Object getLock ()
void fireAreaInvalidated (Rectangle2D.Double invalidatedArea)
void fireAreaInvalidated (FigureEvent event)
void fireFigureRequestRemove ()
void fireFigureAdded ()
void fireFigureRemoved ()
void fireFigureChanged (Rectangle2D.Double changedArea)
void fireFigureChanged (FigureEvent event)
void fireFigureHandlesChanged ()
void fireUndoableEditHappened (UndoableEdit edit)
void invalidate ()
boolean isChanging ()
int getChangingDepth ()
void validate ()
FontRenderContext getFontRenderContext ()
Additional Inherited Members
Static Public Attributes inherited from org.jhotdraw.draw.figure.Figure
static final String CONNECTABLE_PROPERTY = "connectable"
static final String REMOVABLE_PROPERTY = "removable"
static final String SELECTABLE_PROPERTY = "selectable"
static final String TRANSFORMABLE_PROPERTY = "transformable"
Protected Attributes inherited from org.jhotdraw.draw.figure.AbstractFigure
EventListenerList listenerList = new EventListenerList()
int changingDepth = 0
Detailed Description
This abstract class can be extended to implement a DecoratedFigure which has an attribute set.
Author
Werner Randelshofer
Version
$Id$
Member Function Documentation
clone()
AbstractAttributedDecoratedFigure org.jhotdraw.draw.figure.AbstractAttributedDecoratedFigure.clone ()
Returns a clone of the figure, with clones of all aggregated figures, such as children and decorators. The cloned figure does not clone the list of FigureListeners from its original.
Reimplemented from org.jhotdraw.draw.figure.AbstractAttributedFigure.
Reimplemented in org.jhotdraw.draw.figure.TextFigure, org.jhotdraw.draw.figure.TextAreaFigure, and org.jhotdraw.draw.figure.ImageFigure.
References org.jhotdraw.draw.figure.AbstractAttributedDecoratedFigure.clone(), and org.jhotdraw.draw.figure.Figure.clone().
Referenced by org.jhotdraw.draw.figure.AbstractAttributedDecoratedFigure.clone().
contains()
final boolean org.jhotdraw.draw.figure.AbstractAttributedDecoratedFigure.contains (Point2D.Double p)
Checks if a point is contained by the figure.
This is used for hit testing by Tool's.
Implements org.jhotdraw.draw.figure.Figure.
References org.jhotdraw.draw.figure.Figure.contains(), org.jhotdraw.draw.figure.AbstractAttributedDecoratedFigure.figureContains(), and org.jhotdraw.draw.figure.AbstractAttributedDecoratedFigure.updateDecoratorBounds().
Referenced by org.jhotdraw.draw.figure.TextFigure.figureContains(), org.jhotdraw.draw.figure.LabelFigure.getTool(), org.jhotdraw.draw.figure.TextAreaFigure.getTool(), and org.jhotdraw.draw.figure.TextFigure.getTool().
draw()
final void org.jhotdraw.draw.figure.AbstractAttributedDecoratedFigure.draw (Graphics2D g)
Draws the figure.
Parameters
g The Graphics2D to draw to.
Reimplemented from org.jhotdraw.draw.figure.AbstractAttributedFigure.
References org.jhotdraw.draw.figure.AbstractAttributedDecoratedFigure.drawDecorator(), and org.jhotdraw.draw.figure.AbstractAttributedDecoratedFigure.drawFigure().
drawDecorator()
void org.jhotdraw.draw.figure.AbstractAttributedDecoratedFigure.drawDecorator (Graphics2D g) protected
References org.jhotdraw.draw.figure.Figure.draw(), and org.jhotdraw.draw.figure.AbstractAttributedDecoratedFigure.updateDecoratorBounds().
Referenced by org.jhotdraw.draw.figure.AbstractAttributedDecoratedFigure.draw().
drawFigure()
void org.jhotdraw.draw.figure.AbstractAttributedDecoratedFigure.drawFigure (Graphics2D g) protected
Reimplemented in org.jhotdraw.draw.figure.ImageFigure.
Referenced by org.jhotdraw.draw.figure.AbstractAttributedDecoratedFigure.draw().
figureContains()
abstract boolean org.jhotdraw.draw.figure.AbstractAttributedDecoratedFigure.figureContains (Point2D.Double p) abstract protected
Reimplemented in org.jhotdraw.draw.figure.TextFigure, org.jhotdraw.draw.figure.TextAreaFigure, and org.jhotdraw.draw.figure.ImageFigure.
Referenced by org.jhotdraw.draw.figure.AbstractAttributedDecoratedFigure.contains().
getDecorator()
Figure org.jhotdraw.draw.figure.AbstractAttributedDecoratedFigure.getDecorator ()
Gets the decorator for this figure.
Implements org.jhotdraw.draw.figure.DecoratedFigure.
getDrawingArea()
final Rectangle2D.Double org.jhotdraw.draw.figure.AbstractAttributedDecoratedFigure.getDrawingArea ()
Returns the drawing area of the figure as a Rectangle.
The drawing area is used to inform DrawingView about the area that is needed to draw this figure.
The drawing area needs to be large enough, to take line width, line caps and other decorations into account that exceed the bounds of the Figure.
Reimplemented from org.jhotdraw.draw.figure.AbstractAttributedFigure.
References org.jhotdraw.draw.figure.Figure.getDrawingArea(), org.jhotdraw.draw.figure.AbstractAttributedDecoratedFigure.getFigureDrawingArea(), and org.jhotdraw.draw.figure.AbstractAttributedDecoratedFigure.updateDecoratorBounds().
getFigureDrawingArea()
Rectangle2D.Double org.jhotdraw.draw.figure.AbstractAttributedDecoratedFigure.getFigureDrawingArea () protected
Reimplemented in org.jhotdraw.draw.figure.TextFigure, and org.jhotdraw.draw.figure.ImageFigure.
Referenced by org.jhotdraw.draw.figure.AbstractAttributedDecoratedFigure.getDrawingArea().
read()
void org.jhotdraw.draw.figure.AbstractAttributedDecoratedFigure.read (DOMInput in) throws IOException
Reimplemented from org.jhotdraw.draw.figure.AbstractAttributedFigure.
Reimplemented in org.jhotdraw.draw.figure.TextFigure, org.jhotdraw.draw.figure.TextAreaFigure, and org.jhotdraw.draw.figure.ImageFigure.
References org.jhotdraw.draw.figure.AbstractAttributedDecoratedFigure.readDecorator().
readDecorator()
void org.jhotdraw.draw.figure.AbstractAttributedDecoratedFigure.readDecorator (DOMInput in) throws IOException protected
Referenced by org.jhotdraw.draw.figure.AbstractAttributedDecoratedFigure.read(), and org.jhotdraw.draw.figure.TextFigure.read().
setDecorator()
void org.jhotdraw.draw.figure.AbstractAttributedDecoratedFigure.setDecorator (Figure newValue)
Sets a decorator Figure, for example a visual adornment to this Figure. Set this to null, if no decorator is desired. The decorator uses the same logical bounds as this Figure plus AttributeKeys.DECORATOR_INSETS. The decorator does not handle events. The decorator is drawn when the figure is drawn.
Implements org.jhotdraw.draw.figure.DecoratedFigure.
References org.jhotdraw.draw.figure.AbstractFigure.changed(), org.jhotdraw.draw.figure.AbstractFigure.getEndPoint(), org.jhotdraw.draw.figure.AbstractFigure.getStartPoint(), org.jhotdraw.draw.figure.Figure.setBounds(), and org.jhotdraw.draw.figure.AbstractFigure.willChange().
updateDecoratorBounds()
void org.jhotdraw.draw.figure.AbstractAttributedDecoratedFigure.updateDecoratorBounds () protected
References org.jhotdraw.draw.figure.AbstractFigure.getEndPoint(), org.jhotdraw.draw.figure.AbstractFigure.getStartPoint(), and org.jhotdraw.draw.figure.Figure.setBounds().
Referenced by org.jhotdraw.draw.figure.AbstractAttributedDecoratedFigure.contains(), org.jhotdraw.draw.figure.AbstractAttributedDecoratedFigure.drawDecorator(), and org.jhotdraw.draw.figure.AbstractAttributedDecoratedFigure.getDrawingArea().
write()
void org.jhotdraw.draw.figure.AbstractAttributedDecoratedFigure.write (DOMOutput out) throws IOException
Reimplemented from org.jhotdraw.draw.figure.AbstractAttributedFigure.
Reimplemented in org.jhotdraw.draw.figure.TextFigure, org.jhotdraw.draw.figure.TextAreaFigure, and org.jhotdraw.draw.figure.ImageFigure.
References org.jhotdraw.draw.figure.AbstractAttributedDecoratedFigure.writeDecorator().
writeDecorator()
void org.jhotdraw.draw.figure.AbstractAttributedDecoratedFigure.writeDecorator (DOMOutput out) throws IOException protected
Referenced by org.jhotdraw.draw.figure.AbstractAttributedDecoratedFigure.write(), and org.jhotdraw.draw.figure.TextFigure.write().
The documentation for this class was generated from the following file:
jhotdraw-core/src/main/java/org/jhotdraw/draw/figure/AbstractAttributedDecoratedFigure.java