jhotdraw: org.jhotdraw.draw.figure.RoundRectangleFigure Class Reference
org.jhotdraw.draw.figure.RoundRectangleFigure Class Reference
Public Member Functions
RoundRectangleFigure ()
RoundRectangleFigure (double x, double y, double width, double height)
Rectangle2D.Double getBounds ()
Rectangle2D.Double getDrawingArea ()
double getArcWidth ()
double getArcHeight ()
void setArcWidth (double newValue)
void setArcHeight (double newValue)
void setArc (double width, double height)
boolean contains (Point2D.Double p)
void setBounds (Point2D.Double anchor, Point2D.Double lead)
void transform (AffineTransform tx)
Collection< Handle > createHandles (int detailLevel)
void restoreTransformTo (Object geometry)
Object getTransformRestoreData ()
Connector findConnector (Point2D.Double p, ConnectionFigure prototype)
Connector findCompatibleConnector (Connector c, boolean isStartConnector)
RoundRectangleFigure clone ()
void read (DOMInput in) throws IOException
void write (DOMOutput out) throws IOException
Public Member Functions inherited from org.jhotdraw.draw.figure.AbstractAttributedFigure
AbstractAttributedFigure ()
void setAttributeEnabled (AttributeKey<?> key, boolean b)
boolean isAttributeEnabled (AttributeKey<?> key)
void setAttributes (Map< AttributeKey<?>, Object > map)
Map< AttributeKey<?>, Object > getAttributes ()
Object getAttributesRestoreData ()
void restoreAttributesTo (Object restoreData)
void draw (Graphics2D g)
double getStrokeMiterLimitFactor ()
Rectangle2D.Double getDrawingArea (double factor)
boolean hasAttribute (AttributeKey<?> key)
Public Member Functions inherited from org.jhotdraw.draw.figure.AbstractFigure
AbstractFigure ()
void addFigureListener (FigureListener l)
void removeFigureListener (FigureListener l)
void addNotify (Drawing d)
void removeNotify (Drawing d)
void fireAreaInvalidated ()
void fireFigureChanged ()
void remap (Map< Figure, Figure > oldToNew, boolean disconnectIfNotInMap)
Cursor getCursor (Point2D.Double p)
final void setBounds (Rectangle2D.Double bounds)
void willChange ()
void changed ()
boolean includes (Figure figure)
Figure findFigureInside (Point2D.Double p)
Collection< Action > getActions (Point2D.Double p)
Tool getTool (Point2D.Double p)
boolean handleMouseClick (Point2D.Double p, MouseEvent evt, DrawingView view)
boolean handleDrop (Point2D.Double p, Collection< Figure > droppedFigures, DrawingView view)
Point2D.Double getEndPoint ()
Point2D.Double getStartPoint ()
Dimension2DDouble getPreferredSize ()
boolean isConnectable ()
void setConnectable (boolean newValue)
boolean isSelectable ()
void setSelectable (boolean newValue)
boolean isRemovable ()
void setRemovable (boolean newValue)
boolean isTransformable ()
void setTransformable (boolean newValue)
boolean isVisible ()
void setVisible (boolean newValue)
Collection< Figure > getDecomposition ()
void requestRemove ()
int getLayer ()
String getToolTipText (Point2D.Double p)
String toString ()
Collection< Connector > getConnectors (ConnectionFigure prototype)
Public Member Functions inherited from org.jhotdraw.draw.figure.Figure
void addPropertyChangeListener (PropertyChangeListener listener)
void removePropertyChangeListener (PropertyChangeListener listener)
Static Public Attributes
static final String ARC_WIDTH_PROPERTY = "arcWidth"
static final String ARC_HEIGHT_PROPERTY = "arcHeight"
Static Public Attributes inherited from org.jhotdraw.draw.figure.Figure
static final String CONNECTABLE_PROPERTY = "connectable"
static final String REMOVABLE_PROPERTY = "removable"
static final String SELECTABLE_PROPERTY = "selectable"
static final String TRANSFORMABLE_PROPERTY = "transformable"
Protected Member Functions
void drawFill (Graphics2D g)
void drawStroke (Graphics2D g)
Protected Member Functions inherited from org.jhotdraw.draw.figure.AbstractAttributedFigure
abstract void drawFill (java.awt.Graphics2D g)
abstract void drawStroke (java.awt.Graphics2D g)
void drawText (java.awt.Graphics2D g)
void writeAttributes (DOMOutput out) throws IOException
void readAttributes (DOMInput in) throws IOException
AttributeKey<?> getAttributeKey (String name)
void applyAttributesTo (Figure that)
Protected Member Functions inherited from org.jhotdraw.draw.figure.AbstractFigure
Drawing getDrawing ()
Object getLock ()
void fireAreaInvalidated (Rectangle2D.Double invalidatedArea)
void fireAreaInvalidated (FigureEvent event)
void fireFigureRequestRemove ()
void fireFigureAdded ()
void fireFigureRemoved ()
void fireFigureChanged (Rectangle2D.Double changedArea)
void fireFigureChanged (FigureEvent event)
void fireFigureHandlesChanged ()
void fireUndoableEditHappened (UndoableEdit edit)
void invalidate ()
boolean isChanging ()
int getChangingDepth ()
void validate ()
FontRenderContext getFontRenderContext ()
Protected Attributes
RoundRectangle2D.Double roundrect
Protected Attributes inherited from org.jhotdraw.draw.figure.AbstractFigure
EventListenerList listenerList = new EventListenerList()
int changingDepth = 0
Static Protected Attributes
static final double DEFAULT_ARC = 20
Detailed Description
A Figure with a rounded rectangular shape.
This figure has two JavaBeans properties
arcWidth
and
arcHeight
which specify the corner radius.
This figure creates a RoundRectangleRadiusHandle which allows to interactively change the corner radius.
Author
Werner Randelshofer
Version
$Id$
Constructor & Destructor Documentation
RoundRectangleFigure() [1/2]
org.jhotdraw.draw.figure.RoundRectangleFigure.RoundRectangleFigure ()
Creates a new instance.
Referenced by org.jhotdraw.draw.figure.RoundRectangleFigure.clone().
RoundRectangleFigure() [2/2]
org.jhotdraw.draw.figure.RoundRectangleFigure.RoundRectangleFigure (double x, double y, double width, double height)
References org.jhotdraw.draw.figure.RoundRectangleFigure.DEFAULT_ARC, and org.jhotdraw.draw.figure.RoundRectangleFigure.roundrect.
Member Function Documentation
clone()
RoundRectangleFigure org.jhotdraw.draw.figure.RoundRectangleFigure.clone ()
Returns a clone of the figure, with clones of all aggregated figures, such as children and decorators. The cloned figure does not clone the list of FigureListeners from its original.
Reimplemented from org.jhotdraw.draw.figure.AbstractAttributedFigure.
References org.jhotdraw.draw.figure.RoundRectangleFigure.clone(), org.jhotdraw.draw.figure.RoundRectangleFigure.roundrect, and org.jhotdraw.draw.figure.RoundRectangleFigure.RoundRectangleFigure().
Referenced by org.jhotdraw.draw.figure.RoundRectangleFigure.clone().
contains()
boolean org.jhotdraw.draw.figure.RoundRectangleFigure.contains (Point2D.Double p)
Checks if a Point2D.Double is inside the figure.
Implements org.jhotdraw.draw.figure.Figure.
References org.jhotdraw.draw.AttributeKeys.getPerpendicularHitGrowth(), and org.jhotdraw.draw.figure.RoundRectangleFigure.roundrect.
createHandles()
Collection<Handle> org.jhotdraw.draw.figure.RoundRectangleFigure.createHandles (int detailLevel)
Creates handles used to manipulate the figure.
Parameters
detailLevel The detail level of the handles. Usually this is 0 for bounding box handles and 1 for point handles. The value -1 is used by the SelectAreaTracker and the HandleTracker to highlight figures, over which the mouse pointer is hovering.
Returns
a Collection of handles
See also
Handle
Reimplemented from org.jhotdraw.draw.figure.AbstractFigure.
drawFill()
void org.jhotdraw.draw.figure.RoundRectangleFigure.drawFill (Graphics2D g) protected
References org.jhotdraw.draw.AttributeKeys.getPerpendicularFillGrowth(), org.jhotdraw.draw.AttributeKeys.getScaleFactorFromGraphics(), and org.jhotdraw.draw.figure.RoundRectangleFigure.roundrect.
drawStroke()
void org.jhotdraw.draw.figure.RoundRectangleFigure.drawStroke (Graphics2D g) protected
References org.jhotdraw.draw.AttributeKeys.getPerpendicularDrawGrowth(), org.jhotdraw.draw.AttributeKeys.getScaleFactorFromGraphics(), and org.jhotdraw.draw.figure.RoundRectangleFigure.roundrect.
findCompatibleConnector()
Connector org.jhotdraw.draw.figure.RoundRectangleFigure.findCompatibleConnector (Connector c, boolean isStartConnector)
Gets a compatible connector. If the provided connector is part of this figure, return the connector. If the provided connector is part of another figure, return a connector with the same semantics for this figure. Returns null, if no compatible connector is available.
Reimplemented from org.jhotdraw.draw.figure.AbstractFigure.
findConnector()
Connector org.jhotdraw.draw.figure.RoundRectangleFigure.findConnector (Point2D.Double p, ConnectionFigure prototype)
Returns the Figures connector for the specified location. By default a ChopBoxConnector is returned.
See also
ChopRectangleConnector
Reimplemented from org.jhotdraw.draw.figure.AbstractFigure.
getArcHeight()
double org.jhotdraw.draw.figure.RoundRectangleFigure.getArcHeight ()
Gets the arc height.
References org.jhotdraw.draw.figure.RoundRectangleFigure.roundrect.
Referenced by org.jhotdraw.draw.connector.ChopRoundRectangleConnector.chop(), org.jhotdraw.draw.handle.RoundRectangleRadiusHandle.keyPressed(), and org.jhotdraw.draw.handle.RoundRectangleRadiusHandle.trackStart().
getArcWidth()
double org.jhotdraw.draw.figure.RoundRectangleFigure.getArcWidth ()
Gets the arc width.
References org.jhotdraw.draw.figure.RoundRectangleFigure.roundrect.
Referenced by org.jhotdraw.draw.connector.ChopRoundRectangleConnector.chop(), org.jhotdraw.draw.handle.RoundRectangleRadiusHandle.keyPressed(), and org.jhotdraw.draw.handle.RoundRectangleRadiusHandle.trackStart().
getBounds()
Rectangle2D.Double org.jhotdraw.draw.figure.RoundRectangleFigure.getBounds ()
Returns the untransformed logical bounds of the figure as a Rectangle.
The bounds are used by Handle objects for adjusting the figure and for aligning the figure on a grid.
Implements org.jhotdraw.draw.figure.Figure.
References org.jhotdraw.draw.figure.RoundRectangleFigure.roundrect.
Referenced by org.jhotdraw.draw.connector.ChopRoundRectangleConnector.chop(), org.jhotdraw.draw.handle.RoundRectangleRadiusHandle.trackEnd(), and org.jhotdraw.draw.handle.RoundRectangleRadiusHandle.trackStep().
getDrawingArea()
Rectangle2D.Double org.jhotdraw.draw.figure.RoundRectangleFigure.getDrawingArea ()
Returns the drawing area of the figure as a Rectangle.
The drawing area is used to inform DrawingView about the area that is needed to draw this figure.
The drawing area needs to be large enough, to take line width, line caps and other decorations into account that exceed the bounds of the Figure.
Reimplemented from org.jhotdraw.draw.figure.AbstractAttributedFigure.
References org.jhotdraw.draw.AttributeKeys.getPerpendicularHitGrowth(), and org.jhotdraw.draw.figure.RoundRectangleFigure.roundrect.
getTransformRestoreData()
Object org.jhotdraw.draw.figure.RoundRectangleFigure.getTransformRestoreData ()
Gets data which can be used to restore the transformation of the figure without loss of precision, after a transform has been applied to it.
See also
transform(AffineTransform)
Implements org.jhotdraw.draw.figure.Figure.
References org.jhotdraw.draw.figure.RoundRectangleFigure.roundrect.
read()
void org.jhotdraw.draw.figure.RoundRectangleFigure.read (DOMInput in) throws IOException
Reimplemented from org.jhotdraw.draw.figure.AbstractAttributedFigure.
References org.jhotdraw.draw.figure.RoundRectangleFigure.DEFAULT_ARC, and org.jhotdraw.draw.figure.RoundRectangleFigure.roundrect.
restoreTransformTo()
void org.jhotdraw.draw.figure.RoundRectangleFigure.restoreTransformTo (Object restoreData)
Restores the transform of the figure to a previously stored state.
Implements org.jhotdraw.draw.figure.Figure.
References org.jhotdraw.draw.figure.RoundRectangleFigure.roundrect.
setArc()
void org.jhotdraw.draw.figure.RoundRectangleFigure.setArc (double width, double height)
Convenience method for setting both the arc width and the arc height.
References org.jhotdraw.draw.figure.RoundRectangleFigure.setArcHeight(), and org.jhotdraw.draw.figure.RoundRectangleFigure.setArcWidth().
Referenced by org.jhotdraw.draw.handle.RoundRectangleRadiusHandle.trackStep().
setArcHeight()
void org.jhotdraw.draw.figure.RoundRectangleFigure.setArcHeight (double newValue)
Sets the arc height.
References org.jhotdraw.draw.figure.RoundRectangleFigure.ARC_HEIGHT_PROPERTY, and org.jhotdraw.draw.figure.RoundRectangleFigure.roundrect.
Referenced by org.jhotdraw.draw.handle.RoundRectangleRadiusHandle.keyPressed(), and org.jhotdraw.draw.figure.RoundRectangleFigure.setArc().
setArcWidth()
void org.jhotdraw.draw.figure.RoundRectangleFigure.setArcWidth (double newValue)
Sets the arc width.
References org.jhotdraw.draw.figure.RoundRectangleFigure.ARC_WIDTH_PROPERTY, and org.jhotdraw.draw.figure.RoundRectangleFigure.roundrect.
Referenced by org.jhotdraw.draw.handle.RoundRectangleRadiusHandle.keyPressed(), and org.jhotdraw.draw.figure.RoundRectangleFigure.setArc().
setBounds()
void org.jhotdraw.draw.figure.RoundRectangleFigure.setBounds (Point2D.Double start, Point2D.Double end)
Sets the logical and untransformed bounds of the figure.
This is used by Tool's which create a new Figure and by Tool's which connect a Figure to another Figure.
This is a basic operation which does not fire events. Use the following code sequence, if you need event firing:
figure.willChange();
figure.setBounds(...);
figure.changed();
Parameters
start the start point of the bounds
end the end point of the bounds
See also
getBounds
Reimplemented from org.jhotdraw.draw.figure.AbstractFigure.
References org.jhotdraw.draw.figure.RoundRectangleFigure.roundrect.
Referenced by org.jhotdraw.draw.figure.RoundRectangleFigure.transform().
transform()
void org.jhotdraw.draw.figure.RoundRectangleFigure.transform (AffineTransform tx)
Transforms the figure.
Parameters
tx The transformation.
Implements org.jhotdraw.draw.figure.Figure.
References org.jhotdraw.draw.figure.AbstractFigure.getEndPoint(), org.jhotdraw.draw.figure.AbstractFigure.getStartPoint(), and org.jhotdraw.draw.figure.RoundRectangleFigure.setBounds().
write()
void org.jhotdraw.draw.figure.RoundRectangleFigure.write (DOMOutput out) throws IOException
Reimplemented from org.jhotdraw.draw.figure.AbstractAttributedFigure.
References org.jhotdraw.draw.figure.RoundRectangleFigure.roundrect.
Member Data Documentation
ARC_HEIGHT_PROPERTY
final String org.jhotdraw.draw.figure.RoundRectangleFigure.ARC_HEIGHT_PROPERTY = "arcHeight" static
Identifies the
arcHeight
JavaBeans property.
Referenced by org.jhotdraw.draw.handle.RoundRectangleRadiusHandle.keyPressed(), org.jhotdraw.draw.figure.RoundRectangleFigure.setArcHeight(), and org.jhotdraw.draw.handle.RoundRectangleRadiusHandle.trackEnd().
ARC_WIDTH_PROPERTY
final String org.jhotdraw.draw.figure.RoundRectangleFigure.ARC_WIDTH_PROPERTY = "arcWidth" static
Identifies the
arcWidth
JavaBeans property.
Referenced by org.jhotdraw.draw.handle.RoundRectangleRadiusHandle.keyPressed(), org.jhotdraw.draw.figure.RoundRectangleFigure.setArcWidth(), and org.jhotdraw.draw.handle.RoundRectangleRadiusHandle.trackEnd().
DEFAULT_ARC
final double org.jhotdraw.draw.figure.RoundRectangleFigure.DEFAULT_ARC = 20 static protected
Referenced by org.jhotdraw.draw.figure.RoundRectangleFigure.read(), and org.jhotdraw.draw.figure.RoundRectangleFigure.RoundRectangleFigure().
roundrect
RoundRectangle2D.Double org.jhotdraw.draw.figure.RoundRectangleFigure.roundrect protected
Referenced by org.jhotdraw.draw.figure.RoundRectangleFigure.clone(), org.jhotdraw.draw.figure.RoundRectangleFigure.contains(), org.jhotdraw.draw.figure.RoundRectangleFigure.drawFill(), org.jhotdraw.draw.figure.RoundRectangleFigure.drawStroke(), org.jhotdraw.draw.figure.RoundRectangleFigure.getArcHeight(), org.jhotdraw.draw.figure.RoundRectangleFigure.getArcWidth(), org.jhotdraw.draw.figure.RoundRectangleFigure.getBounds(), org.jhotdraw.draw.figure.RoundRectangleFigure.getDrawingArea(), org.jhotdraw.draw.figure.RoundRectangleFigure.getTransformRestoreData(), org.jhotdraw.draw.figure.RoundRectangleFigure.read(), org.jhotdraw.draw.figure.RoundRectangleFigure.restoreTransformTo(), org.jhotdraw.draw.figure.RoundRectangleFigure.RoundRectangleFigure(), org.jhotdraw.draw.figure.RoundRectangleFigure.setArcHeight(), org.jhotdraw.draw.figure.RoundRectangleFigure.setArcWidth(), org.jhotdraw.draw.figure.RoundRectangleFigure.setBounds(), and org.jhotdraw.draw.figure.RoundRectangleFigure.write().
The documentation for this class was generated from the following file:
jhotdraw-core/src/main/java/org/jhotdraw/draw/figure/RoundRectangleFigure.java