jhotdraw: org.jhotdraw.draw.decoration.ArrowTip Class Reference
org.jhotdraw.draw.decoration.ArrowTip Class Reference
Public Member Functions
ArrowTip ()
ArrowTip (double angle, double outerRadius, double innerRadius)
ArrowTip (double angle, double outerRadius, double innerRadius, boolean isFilled, boolean isStroked, boolean isSolid)
double getAngle ()
double getInnerRadius ()
double getOuterRadius ()
void read (DOMInput in)
void write (DOMOutput out)
Public Member Functions inherited from org.jhotdraw.draw.decoration.AbstractLineDecoration
AbstractLineDecoration (boolean isFilled, boolean isStroked, boolean isSolid)
void draw (Graphics2D g, Figure f, Point2D.Double p1, Point2D.Double p2)
Rectangle2D.Double getDrawingArea (Figure f, Point2D.Double p1, Point2D.Double p2)
double getDecorationRadius (Figure f)
Protected Member Functions
Path2D.Double getDecoratorPath (Figure f)
double getDecoratorPathRadius (Figure f)
Protected Member Functions inherited from org.jhotdraw.draw.decoration.AbstractLineDecoration
boolean isFilled ()
boolean isStroked ()
boolean isSolid ()
void setFilled (boolean b)
void setStroked (boolean b)
void setSolid (boolean b)
Detailed Description
A LineDecoration which can draws an arrow tip.
The shape of the arrow can be controlled with three parameters:
angle - the angle in radians at which the two legs of the arrow meet.
outer radius - the length of the two legs of the arrow.
inner radius - the distance from the tip of the arrow to the point where its end meets the line.
Author
Werner Randelshofer
Version
$Id$
Constructor & Destructor Documentation
ArrowTip() [1/3]
org.jhotdraw.draw.decoration.ArrowTip.ArrowTip ()
ArrowTip() [2/3]
org.jhotdraw.draw.decoration.ArrowTip.ArrowTip (double angle, double outerRadius, double innerRadius)
Constructs an arrow tip with the specified angle and outer and inner radius.
ArrowTip() [3/3]
org.jhotdraw.draw.decoration.ArrowTip.ArrowTip (double angle, double outerRadius, double innerRadius, boolean isFilled, boolean isStroked, boolean isSolid)
Constructs an arrow tip with the specified parameters.
Member Function Documentation
getAngle()
double org.jhotdraw.draw.decoration.ArrowTip.getAngle ()
getDecoratorPath()
Path2D.Double org.jhotdraw.draw.decoration.ArrowTip.getDecoratorPath (Figure f) protected
Hook method to calculate the path of the decorator.
Reimplemented from org.jhotdraw.draw.decoration.AbstractLineDecoration.
References org.jhotdraw.draw.decoration.AbstractLineDecoration.isStroked().
getDecoratorPathRadius()
double org.jhotdraw.draw.decoration.ArrowTip.getDecoratorPathRadius (Figure f) protected
Hook method to calculate the radius of the decorator path.
Reimplemented from org.jhotdraw.draw.decoration.AbstractLineDecoration.
References org.jhotdraw.draw.decoration.AbstractLineDecoration.isStroked().
getInnerRadius()
double org.jhotdraw.draw.decoration.ArrowTip.getInnerRadius ()
getOuterRadius()
double org.jhotdraw.draw.decoration.ArrowTip.getOuterRadius ()
read()
void org.jhotdraw.draw.decoration.ArrowTip.read (DOMInput in)
References org.jhotdraw.draw.decoration.AbstractLineDecoration.setFilled(), org.jhotdraw.draw.decoration.AbstractLineDecoration.setSolid(), and org.jhotdraw.draw.decoration.AbstractLineDecoration.setStroked().
write()
void org.jhotdraw.draw.decoration.ArrowTip.write (DOMOutput out)
References org.jhotdraw.draw.decoration.AbstractLineDecoration.isFilled(), org.jhotdraw.draw.decoration.AbstractLineDecoration.isSolid(), and org.jhotdraw.draw.decoration.AbstractLineDecoration.isStroked().
The documentation for this class was generated from the following file:
jhotdraw-core/src/main/java/org/jhotdraw/draw/decoration/ArrowTip.java