jhotdraw: org.jhotdraw.draw.connector.ChopDiamondConnector Class Reference
org.jhotdraw.draw.connector.ChopDiamondConnector Class Reference
Public Member Functions
ChopDiamondConnector ()
ChopDiamondConnector (Figure owner)
Public Member Functions inherited from org.jhotdraw.draw.connector.ChopRectangleConnector
ChopRectangleConnector ()
ChopRectangleConnector (Figure owner)
Point2D.Double findStart (ConnectionFigure connection)
Point2D.Double findEnd (ConnectionFigure connection)
Public Member Functions inherited from org.jhotdraw.draw.connector.AbstractConnector
AbstractConnector ()
AbstractConnector (Figure owner)
void setConnectToDecorator (boolean newValue)
boolean isConnectToDecorator ()
boolean contains (Point2D.Double p)
Figure getOwner ()
Object clone ()
void updateStartLocation (Point2D.Double p)
void updateEndLocation (Point2D.Double p)
Point2D.Double getAnchor ()
void updateAnchor (Point2D.Double p)
Rectangle2D.Double getBounds ()
void read (DOMInput in) throws IOException
void write (DOMOutput out) throws IOException
Rectangle2D.Double getDrawingArea ()
void draw (Graphics2D g)
Protected Member Functions
Point2D.Double chop (Figure target, Point2D.Double from)
Protected Member Functions inherited from org.jhotdraw.draw.connector.AbstractConnector
final Figure getConnectorTarget (Figure f)
Point2D.Double findPoint (ConnectionFigure connection)
void setOwner (Figure newValue)
Detailed Description
A Connector which locates a connection point at the bounds of any figure which has a diamond shape, such as DiamondFigure.
Author
Werner Randelshofer
Version
$Id$
Constructor & Destructor Documentation
ChopDiamondConnector() [1/2]
org.jhotdraw.draw.connector.ChopDiamondConnector.ChopDiamondConnector ()
ChopDiamondConnector() [2/2]
org.jhotdraw.draw.connector.ChopDiamondConnector.ChopDiamondConnector (Figure owner)
Member Function Documentation
chop()
Point2D.Double org.jhotdraw.draw.connector.ChopDiamondConnector.chop (Figure target, Point2D.Double from) protected
Return an appropriate connection point on the edge of a diamond figure
Reimplemented from org.jhotdraw.draw.connector.ChopRectangleConnector.
References org.jhotdraw.draw.figure.Figure.get(), org.jhotdraw.draw.figure.Figure.getBounds(), org.jhotdraw.draw.connector.AbstractConnector.getConnectorTarget(), and org.jhotdraw.draw.figure.DiamondFigure.IS_QUADRATIC.
The documentation for this class was generated from the following file:
jhotdraw-core/src/main/java/org/jhotdraw/draw/connector/ChopDiamondConnector.java