jhotdraw: org.jhotdraw.draw.action.AbstractDrawingEditorAction Class Reference
org.jhotdraw.draw.action.AbstractDrawingEditorAction Class Reference abstract
Public Member Functions
AbstractDrawingEditorAction (DrawingEditor editor)
void setEditor (DrawingEditor newValue)
DrawingEditor getEditor ()
void setUpdateEnabledState (boolean newValue)
boolean isUpdatEnabledState ()
Protected Member Functions
void updateEnabledState ()
DrawingView getView ()
Drawing getDrawing ()
void fireUndoableEditHappened (UndoableEdit edit)
Protected Attributes
DrawingEditor editor
Detailed Description
This abstract class can be extended to implement an
Action
that acts on behalf of a org.jhotdraw.draw.DrawingEditor.
By default the enabled state of this action reflects the enabled state of the
DrawingEditor
. When many actions listen to the enabled state of the drawing editor this can considerably slow down the editor. If updating the enabled state is not necessary, you can prevent the action from doing so using setUpdateEnabledState.
AbstractDrawingEditorAction
listens using a WeakPropertyChangeListener on the
DrawingEditor
and thus may become garbage collected if it is not referenced by any other object.
Author
Werner Randelshofer
Version
$Id$
Constructor & Destructor Documentation
AbstractDrawingEditorAction()
org.jhotdraw.draw.action.AbstractDrawingEditorAction.AbstractDrawingEditorAction (DrawingEditor editor)
Creates a new instance.
References org.jhotdraw.draw.action.AbstractDrawingEditorAction.editor, and org.jhotdraw.draw.action.AbstractDrawingEditorAction.setEditor().
Member Function Documentation
fireUndoableEditHappened()
void org.jhotdraw.draw.action.AbstractDrawingEditorAction.fireUndoableEditHappened (UndoableEdit edit) protected
Updates the enabled state of this action to reflect the enabled state of the active
DrawingView
. If no drawing view is active, this action is disabled.
References org.jhotdraw.draw.Drawing.fireUndoableEditHappened(), and org.jhotdraw.draw.action.AbstractDrawingEditorAction.getDrawing().
getDrawing()
Drawing org.jhotdraw.draw.action.AbstractDrawingEditorAction.getDrawing () protected
References org.jhotdraw.draw.DrawingView.getDrawing(), and org.jhotdraw.draw.action.AbstractDrawingEditorAction.getView().
Referenced by org.jhotdraw.draw.action.AbstractDrawingEditorAction.fireUndoableEditHappened().
getEditor()
DrawingEditor org.jhotdraw.draw.action.AbstractDrawingEditorAction.getEditor ()
References org.jhotdraw.draw.action.AbstractDrawingEditorAction.editor.
Referenced by org.jhotdraw.draw.action.ZoomEditorAction.actionPerformed().
getView()
DrawingView org.jhotdraw.draw.action.AbstractDrawingEditorAction.getView () protected
References org.jhotdraw.draw.action.AbstractDrawingEditorAction.editor, and org.jhotdraw.draw.DrawingEditor.getActiveView().
Referenced by org.jhotdraw.draw.action.ZoomEditorAction.actionPerformed(), and org.jhotdraw.draw.action.AbstractDrawingEditorAction.getDrawing().
isUpdatEnabledState()
boolean org.jhotdraw.draw.action.AbstractDrawingEditorAction.isUpdatEnabledState ()
Returns true, if this action automatically updates its enabled state to reflect the enabled state of the active
DrawingView
.
setEditor()
void org.jhotdraw.draw.action.AbstractDrawingEditorAction.setEditor (DrawingEditor newValue)
References org.jhotdraw.draw.action.AbstractDrawingEditorAction.editor, and org.jhotdraw.draw.action.AbstractDrawingEditorAction.updateEnabledState().
Referenced by org.jhotdraw.draw.action.AbstractDrawingEditorAction.AbstractDrawingEditorAction().
setUpdateEnabledState()
void org.jhotdraw.draw.action.AbstractDrawingEditorAction.setUpdateEnabledState (boolean newValue)
By default, the enabled state of this action is updated to reflect the enabled state of the active
DrawingView
. Since this is not always necessary, and since many listening actions may considerably slow down the drawing editor, you can switch this behavior off here.
Parameters
newValue Specify false to prevent automatic updating of the enabled state.
References org.jhotdraw.draw.action.AbstractDrawingEditorAction.updateEnabledState().
updateEnabledState()
void org.jhotdraw.draw.action.AbstractDrawingEditorAction.updateEnabledState () protected
References org.jhotdraw.draw.action.AbstractDrawingEditorAction.editor, and org.jhotdraw.draw.DrawingEditor.isEnabled().
Referenced by org.jhotdraw.draw.action.AbstractDrawingEditorAction.setEditor(), and org.jhotdraw.draw.action.AbstractDrawingEditorAction.setUpdateEnabledState().
Member Data Documentation
editor
DrawingEditor org.jhotdraw.draw.action.AbstractDrawingEditorAction.editor protected
Referenced by org.jhotdraw.draw.action.AbstractDrawingEditorAction.AbstractDrawingEditorAction(), org.jhotdraw.draw.action.AbstractDrawingEditorAction.getEditor(), org.jhotdraw.draw.action.AbstractDrawingEditorAction.getView(), org.jhotdraw.draw.action.AbstractDrawingEditorAction.setEditor(), org.jhotdraw.draw.action.AbstractDrawingEditorAction.updateEnabledState(), and org.jhotdraw.draw.action.ZoomEditorAction.ZoomEditorAction().
The documentation for this class was generated from the following file:
jhotdraw-core/src/main/java/org/jhotdraw/draw/action/AbstractDrawingEditorAction.java