jhotdraw: org.jhotdraw.draw.figure.QuadTreeCompositeFigure Class Reference
org.jhotdraw.draw.figure.QuadTreeCompositeFigure Class Reference abstract
Classes
class FigureHandler
Public Member Functions
QuadTreeCompositeFigure ()
int indexOf (Figure figure)
void basicAdd (int index, Figure figure)
Figure basicRemoveChild (int index)
void draw (Graphics2D g)
java.util.List< Figure > sort (Collection< Figure > c)
void draw (Graphics2D g, Collection< Figure > c)
java.util.List< Figure > getFigures (Rectangle2D.Double bounds)
java.util.List< Figure > getChildren ()
Figure findFigureInside (Point2D.Double p)
java.util.List< Figure > getFiguresFrontToBack ()
Figure findFigure (Point2D.Double p)
Figure findFigureExcept (Point2D.Double p, Figure ignore)
Figure findFigureExcept (Point2D.Double p, Collection< Figure > ignore)
Figure findFigureBehind (Point2D.Double p, Figure figure)
Figure findFigureBehind (Point2D.Double p, Collection< Figure > figures)
java.util.List< Figure > findFigures (Rectangle2D.Double r)
java.util.List< Figure > findFiguresWithin (Rectangle2D.Double bounds)
void bringToFront (Figure figure)
void sendToBack (Figure figure)
boolean contains (Figure f)
void setCanvasSize (Dimension2DDouble newValue)
Dimension2DDouble getCanvasSize ()
Public Member Functions inherited from org.jhotdraw.draw.figure.AbstractCompositeFigure
AbstractCompositeFigure ()
Collection< Handle > createHandles (int detailLevel)
boolean add (Figure figure)
void add (int index, Figure figure)
void addAll (Collection<? extends Figure > figures)
final void addAll (int index, Collection<? extends Figure > figures)
void basicAdd (Figure figure)
void basicAddAll (int index, Collection<? extends Figure > newFigures)
void addNotify (Drawing drawing)
void removeNotify (Drawing drawing)
boolean remove (final Figure figure)
Figure removeChild (int index)
void removeAll (Collection<? extends Figure > figures)
void removeAllChildren ()
void basicRemoveAllChildren ()
void basicRemoveAll (Collection<? extends Figure > figures)
void transform (AffineTransform tx)
void setBounds (Point2D.Double anchor, Point2D.Double lead)
java.util.List< Figure > getChildrenFrontToBack ()
Map< AttributeKey<?>, Object > getAttributes ()
Object getAttributesRestoreData ()
void restoreAttributesTo (Object newData)
boolean contains (Point2D.Double p)
Figure findChild (Point2D.Double p)
int findChildIndex (Point2D.Double p)
Layouter getLayouter ()
void layout ()
void setLayouter (Layouter newLayouter)
Dimension2DDouble getPreferredSize ()
Collection< Figure > getDecomposition ()
void read (DOMInput in) throws IOException
void write (DOMOutput out) throws IOException
void restoreTransformTo (Object geometry)
Object getTransformRestoreData ()
int getChildCount ()
Figure getChild (int index)
AbstractCompositeFigure clone ()
void willChange ()
void changed ()
int basicRemove (Figure child)
Rectangle2D.Double getDrawingArea ()
Rectangle2D.Double getDrawingArea (double factor)
Rectangle2D.Double getBounds ()
void removeCompositeFigureListener (CompositeFigureListener listener)
void addCompositeFigureListener (CompositeFigureListener listener)
Public Member Functions inherited from org.jhotdraw.draw.figure.AbstractFigure
AbstractFigure ()
void addFigureListener (FigureListener l)
void removeFigureListener (FigureListener l)
void fireAreaInvalidated ()
void fireFigureChanged ()
void remap (Map< Figure, Figure > oldToNew, boolean disconnectIfNotInMap)
Cursor getCursor (Point2D.Double p)
final void setBounds (Rectangle2D.Double bounds)
Connector findConnector (Point2D.Double p, ConnectionFigure prototype)
boolean includes (Figure figure)
Connector findCompatibleConnector (Connector c, boolean isStart)
Collection< Action > getActions (Point2D.Double p)
Tool getTool (Point2D.Double p)
boolean handleMouseClick (Point2D.Double p, MouseEvent evt, DrawingView view)
boolean handleDrop (Point2D.Double p, Collection< Figure > droppedFigures, DrawingView view)
Point2D.Double getEndPoint ()
Point2D.Double getStartPoint ()
boolean isConnectable ()
void setConnectable (boolean newValue)
boolean isSelectable ()
void setSelectable (boolean newValue)
boolean isRemovable ()
void setRemovable (boolean newValue)
boolean isTransformable ()
void setTransformable (boolean newValue)
boolean isVisible ()
void setVisible (boolean newValue)
void requestRemove ()
int getLayer ()
String getToolTipText (Point2D.Double p)
String toString ()
Collection< Connector > getConnectors (ConnectionFigure prototype)
Public Member Functions inherited from org.jhotdraw.draw.figure.Figure
void addPropertyChangeListener (PropertyChangeListener listener)
void removePropertyChangeListener (PropertyChangeListener listener)
Protected Member Functions
FigureHandler createFigureHandler ()
Protected Member Functions inherited from org.jhotdraw.draw.figure.AbstractCompositeFigure
EventHandler createEventHandler ()
void validate ()
void invalidate ()
void fireFigureAdded (Figure f, int zIndex)
void fireFigureRemoved (Figure f, int zIndex)
Protected Member Functions inherited from org.jhotdraw.draw.figure.AbstractFigure
Drawing getDrawing ()
Object getLock ()
void fireAreaInvalidated (Rectangle2D.Double invalidatedArea)
void fireAreaInvalidated (FigureEvent event)
void fireFigureRequestRemove ()
void fireFigureAdded ()
void fireFigureRemoved ()
void fireFigureChanged (Rectangle2D.Double changedArea)
void fireFigureChanged (FigureEvent event)
void fireFigureHandlesChanged ()
void fireUndoableEditHappened (UndoableEdit edit)
boolean isChanging ()
int getChangingDepth ()
FontRenderContext getFontRenderContext ()
Additional Inherited Members
Static Public Attributes inherited from org.jhotdraw.draw.figure.Figure
static final String CONNECTABLE_PROPERTY = "connectable"
static final String REMOVABLE_PROPERTY = "removable"
static final String SELECTABLE_PROPERTY = "selectable"
static final String TRANSFORMABLE_PROPERTY = "transformable"
Static Public Attributes inherited from org.jhotdraw.draw.figure.CompositeFigure
static final AttributeKey< Insets2D.Double > LAYOUT_INSETS = new AttributeKey<Insets2D.Double>("layoutInsets", Insets2D.Double.class, new Insets2D.Double())
Protected Attributes inherited from org.jhotdraw.draw.figure.AbstractCompositeFigure
Layouter layouter
ArrayList< Figure > children = new ArrayList<>()
transient Rectangle2D.Double cachedDrawingArea
transient Rectangle2D.Double cachedBounds
EventHandler eventHandler
Protected Attributes inherited from org.jhotdraw.draw.figure.AbstractFigure
EventListenerList listenerList = new EventListenerList()
int changingDepth = 0
Detailed Description
QuadTreeCompositeFigure.
Author
Werner Randelshofer
Version
$Id$
Constructor & Destructor Documentation
QuadTreeCompositeFigure()
org.jhotdraw.draw.figure.QuadTreeCompositeFigure.QuadTreeCompositeFigure ()
Creates a new instance.
References org.jhotdraw.draw.figure.QuadTreeCompositeFigure.createFigureHandler().
Member Function Documentation
basicAdd()
void org.jhotdraw.draw.figure.QuadTreeCompositeFigure.basicAdd (int index, Figure child)
Adds a child to the figure at the specified index without firing events.
This method can be used to reinsert a child figure which has been temporarily removed from this CompositeFigure (for example to reorder the sequence of the children) and to efficiently build a drawing from an org.jhotdraw.draw.io.InputFormat.
Reimplemented from org.jhotdraw.draw.figure.AbstractCompositeFigure.
References org.jhotdraw.draw.figure.Figure.addFigureListener(), org.jhotdraw.draw.figure.AbstractCompositeFigure.children, and org.jhotdraw.draw.figure.Figure.getDrawingArea().
basicRemoveChild()
Figure org.jhotdraw.draw.figure.QuadTreeCompositeFigure.basicRemoveChild (int index)
Removes the child at the specified index without firing events.
This method can be used to temporarily remove a child from this CompositeFigure (for example to reorder the sequence of the children).
Returns the removed child figure.
Reimplemented from org.jhotdraw.draw.figure.AbstractCompositeFigure.
References org.jhotdraw.draw.figure.AbstractCompositeFigure.children, and org.jhotdraw.draw.figure.Figure.removeFigureListener().
bringToFront()
void org.jhotdraw.draw.figure.QuadTreeCompositeFigure.bringToFront (Figure figure)
Brings a figure to the front of the drawing.
Parameters
figure that is part of the drawing
Reimplemented from org.jhotdraw.draw.figure.AbstractCompositeFigure.
References org.jhotdraw.draw.figure.AbstractCompositeFigure.children, org.jhotdraw.draw.figure.AbstractFigure.fireAreaInvalidated(), and org.jhotdraw.draw.figure.Figure.getDrawingArea().
contains()
boolean org.jhotdraw.draw.figure.QuadTreeCompositeFigure.contains (Figure f)
Returns true if this composite figure contains the specified figure.
This is a convenience method for calling
getChildren().contains(f);
.
Reimplemented from org.jhotdraw.draw.figure.AbstractCompositeFigure.
References org.jhotdraw.draw.figure.AbstractCompositeFigure.children.
createFigureHandler()
FigureHandler org.jhotdraw.draw.figure.QuadTreeCompositeFigure.createFigureHandler () protected
Referenced by org.jhotdraw.draw.figure.QuadTreeCompositeFigure.QuadTreeCompositeFigure().
draw() [1/2]
void org.jhotdraw.draw.figure.QuadTreeCompositeFigure.draw (Graphics2D g)
Draws the figure.
Parameters
g The Graphics2D to draw to.
Reimplemented from org.jhotdraw.draw.figure.AbstractCompositeFigure.
References org.jhotdraw.draw.figure.AbstractCompositeFigure.children, and org.jhotdraw.draw.figure.QuadTreeCompositeFigure.sort().
draw() [2/2]
void org.jhotdraw.draw.figure.QuadTreeCompositeFigure.draw (Graphics2D g, Collection< Figure > c)
findFigure()
Figure org.jhotdraw.draw.figure.QuadTreeCompositeFigure.findFigure (Point2D.Double p)
References org.jhotdraw.draw.figure.Figure.contains(), and org.jhotdraw.draw.figure.QuadTreeCompositeFigure.getFiguresFrontToBack().
findFigureBehind() [1/2]
Figure org.jhotdraw.draw.figure.QuadTreeCompositeFigure.findFigureBehind (Point2D.Double p, Collection< Figure > figures)
References org.jhotdraw.draw.figure.QuadTreeCompositeFigure.getFiguresFrontToBack().
findFigureBehind() [2/2]
Figure org.jhotdraw.draw.figure.QuadTreeCompositeFigure.findFigureBehind (Point2D.Double p, Figure figure)
References org.jhotdraw.draw.figure.QuadTreeCompositeFigure.getFiguresFrontToBack().
findFigureExcept() [1/2]
Figure org.jhotdraw.draw.figure.QuadTreeCompositeFigure.findFigureExcept (Point2D.Double p, Collection< Figure > ignore)
References org.jhotdraw.draw.figure.Figure.contains(), and org.jhotdraw.draw.figure.QuadTreeCompositeFigure.getFiguresFrontToBack().
findFigureExcept() [2/2]
Figure org.jhotdraw.draw.figure.QuadTreeCompositeFigure.findFigureExcept (Point2D.Double p, Figure ignore)
References org.jhotdraw.draw.figure.Figure.contains(), and org.jhotdraw.draw.figure.QuadTreeCompositeFigure.getFiguresFrontToBack().
findFigureInside()
Figure org.jhotdraw.draw.figure.QuadTreeCompositeFigure.findFigureInside (Point2D.Double p)
Finds the innermost figure at the specified location.
In case of a
CompositeFigure
, this method descends into its children and into its children's children until the innermost figure is found.
This functionality is implemented using the Chain of Responsibility design pattern. A figure which is not composed of other figures returns itself if the point is contained by the figure. Composed figures pass the method call down to their children.
Parameters
p A location on the drawing.
Returns
Returns the innermost figure at the location, or null if the location is not contained in a figure.
Reimplemented from org.jhotdraw.draw.figure.AbstractCompositeFigure.
References org.jhotdraw.draw.figure.Figure.findFigureInside(), and org.jhotdraw.draw.figure.QuadTreeCompositeFigure.getFiguresFrontToBack().
findFigures()
java.util.List<Figure> org.jhotdraw.draw.figure.QuadTreeCompositeFigure.findFigures (Rectangle2D.Double r)
References org.jhotdraw.draw.figure.QuadTreeCompositeFigure.sort().
findFiguresWithin()
java.util.List<Figure> org.jhotdraw.draw.figure.QuadTreeCompositeFigure.findFiguresWithin (Rectangle2D.Double bounds)
References org.jhotdraw.draw.figure.AbstractCompositeFigure.children.
getCanvasSize()
Dimension2DDouble org.jhotdraw.draw.figure.QuadTreeCompositeFigure.getCanvasSize ()
getChildren()
java.util.List<Figure> org.jhotdraw.draw.figure.QuadTreeCompositeFigure.getChildren ()
Returns an unchangeable list view on the children.
Reimplemented from org.jhotdraw.draw.figure.AbstractCompositeFigure.
References org.jhotdraw.draw.figure.AbstractCompositeFigure.children.
getFigures()
java.util.List<Figure> org.jhotdraw.draw.figure.QuadTreeCompositeFigure.getFigures (Rectangle2D.Double bounds)
getFiguresFrontToBack()
java.util.List<Figure> org.jhotdraw.draw.figure.QuadTreeCompositeFigure.getFiguresFrontToBack ()
Returns an iterator to iterate in Z-order front to back over the children.
References org.jhotdraw.draw.figure.AbstractCompositeFigure.children.
Referenced by org.jhotdraw.draw.figure.QuadTreeCompositeFigure.findFigure(), org.jhotdraw.draw.figure.QuadTreeCompositeFigure.findFigureBehind(), org.jhotdraw.draw.figure.QuadTreeCompositeFigure.findFigureExcept(), and org.jhotdraw.draw.figure.QuadTreeCompositeFigure.findFigureInside().
indexOf()
int org.jhotdraw.draw.figure.QuadTreeCompositeFigure.indexOf (Figure child)
Returns the index of the specified child.
This is a convenience method for calling
getChildren().indexOf(index);
.
Returns
The index of the child, or -1 if the specified figure is not a child of this CompositeFigure.
Reimplemented from org.jhotdraw.draw.figure.AbstractCompositeFigure.
References org.jhotdraw.draw.figure.AbstractCompositeFigure.children.
sendToBack()
void org.jhotdraw.draw.figure.QuadTreeCompositeFigure.sendToBack (Figure figure)
Sends a figure to the back of the composite figure.
Parameters
figure that is part of this composite figure
Reimplemented from org.jhotdraw.draw.figure.AbstractCompositeFigure.
References org.jhotdraw.draw.figure.AbstractCompositeFigure.children, org.jhotdraw.draw.figure.AbstractFigure.fireAreaInvalidated(), and org.jhotdraw.draw.figure.Figure.getDrawingArea().
setCanvasSize()
void org.jhotdraw.draw.figure.QuadTreeCompositeFigure.setCanvasSize (Dimension2DDouble newValue)
sort()
java.util.List<Figure> org.jhotdraw.draw.figure.QuadTreeCompositeFigure.sort (Collection< Figure > c)
Implementation note: Sorting can not be done for orphaned children.
References org.jhotdraw.draw.figure.AbstractCompositeFigure.children.
Referenced by org.jhotdraw.draw.figure.QuadTreeCompositeFigure.draw(), and org.jhotdraw.draw.figure.QuadTreeCompositeFigure.findFigures().
The documentation for this class was generated from the following file:
jhotdraw-core/src/main/java/org/jhotdraw/draw/figure/QuadTreeCompositeFigure.java