jhotdraw: org.jhotdraw.draw.figure.LineFigure Class Reference
org.jhotdraw.draw.figure.LineFigure Class Reference
Public Member Functions
LineFigure ()
Collection< Handle > createHandles (int detailLevel)
boolean handleMouseClick (Point2D.Double p, MouseEvent evt, DrawingView view)
Public Member Functions inherited from org.jhotdraw.draw.figure.BezierFigure
BezierFigure ()
BezierFigure (boolean isClosed)
Connector findConnector (Point2D.Double p, ConnectionFigure prototype)
Connector findCompatibleConnector (Connector c, boolean isStart)
boolean contains (Point2D.Double p)
Rectangle2D.Double getBounds ()
Rectangle2D.Double getDrawingArea (double factor)
BezierPath getBezierPath ()
void setBezierPath (BezierPath newValue)
Point2D.Double getPointOnPath (float relative, double flatness)
boolean isClosed ()
void setClosed (boolean newValue)
void setBounds (Point2D.Double anchor, Point2D.Double lead)
void transform (AffineTransform tx)
void invalidate ()
void layout ()
void addNode (BezierPath.Node p)
void addNode (final int index, BezierPath.Node p)
void setNode (int index, BezierPath.Node p)
BezierPath.Node getNode (int index)
Point2D.Double getPoint (int index)
Point2D.Double getPoint (int index, int coord)
void setPoint (int index, Point2D.Double p)
void setPoint (int index, int coord, Point2D.Double p)
void setStartPoint (Point2D.Double p)
void setEndPoint (Point2D.Double p)
Point2D.Double getStartPoint ()
Point2D.Double getEndPoint ()
int findNode (Point2D.Double p)
int findSegment (Point2D.Double find, double tolerance)
boolean joinSegments (Point2D.Double join, double tolerance)
int splitSegment (Point2D.Double split, double tolerance)
BezierPath.Node removeNode (int index)
int getNodeCount ()
BezierFigure clone ()
void restoreTransformTo (Object geometry)
Object getTransformRestoreData ()
Point2D.Double chop (Point2D.Double p)
Point2D.Double getCenter ()
Point2D.Double getOutermostPoint ()
int joinSegments (Point2D.Double join, float tolerance)
int splitSegment (Point2D.Double split, float tolerance)
void write (DOMOutput out) throws IOException
void read (DOMInput in) throws IOException
Public Member Functions inherited from org.jhotdraw.draw.figure.AbstractAttributedFigure
AbstractAttributedFigure ()
void setAttributeEnabled (AttributeKey<?> key, boolean b)
boolean isAttributeEnabled (AttributeKey<?> key)
void setAttributes (Map< AttributeKey<?>, Object > map)
Map< AttributeKey<?>, Object > getAttributes ()
Object getAttributesRestoreData ()
void restoreAttributesTo (Object restoreData)
void draw (Graphics2D g)
double getStrokeMiterLimitFactor ()
Rectangle2D.Double getDrawingArea ()
boolean hasAttribute (AttributeKey<?> key)
Public Member Functions inherited from org.jhotdraw.draw.figure.AbstractFigure
AbstractFigure ()
void addFigureListener (FigureListener l)
void removeFigureListener (FigureListener l)
void addNotify (Drawing d)
void removeNotify (Drawing d)
void fireAreaInvalidated ()
void fireFigureChanged ()
void remap (Map< Figure, Figure > oldToNew, boolean disconnectIfNotInMap)
Cursor getCursor (Point2D.Double p)
final void setBounds (Rectangle2D.Double bounds)
void willChange ()
void changed ()
boolean includes (Figure figure)
Figure findFigureInside (Point2D.Double p)
Collection< Action > getActions (Point2D.Double p)
Tool getTool (Point2D.Double p)
boolean handleDrop (Point2D.Double p, Collection< Figure > droppedFigures, DrawingView view)
Dimension2DDouble getPreferredSize ()
boolean isConnectable ()
void setConnectable (boolean newValue)
boolean isSelectable ()
void setSelectable (boolean newValue)
boolean isRemovable ()
void setRemovable (boolean newValue)
boolean isTransformable ()
void setTransformable (boolean newValue)
boolean isVisible ()
void setVisible (boolean newValue)
Collection< Figure > getDecomposition ()
void requestRemove ()
int getLayer ()
String getToolTipText (Point2D.Double p)
String toString ()
Collection< Connector > getConnectors (ConnectionFigure prototype)
Public Member Functions inherited from org.jhotdraw.draw.figure.Figure
void addPropertyChangeListener (PropertyChangeListener listener)
void removePropertyChangeListener (PropertyChangeListener listener)
Additional Inherited Members
Static Public Attributes inherited from org.jhotdraw.draw.figure.Figure
static final String CONNECTABLE_PROPERTY = "connectable"
static final String REMOVABLE_PROPERTY = "removable"
static final String SELECTABLE_PROPERTY = "selectable"
static final String TRANSFORMABLE_PROPERTY = "transformable"
Protected Member Functions inherited from org.jhotdraw.draw.figure.BezierFigure
void drawStroke (Graphics2D g)
void drawCaps (Graphics2D g)
void drawFill (Graphics2D g)
void validate ()
BezierPath getCappedPath ()
void removeAllNodes ()
void writePoints (DOMOutput out) throws IOException
void readPoints (DOMInput in) throws IOException
Protected Member Functions inherited from org.jhotdraw.draw.figure.AbstractAttributedFigure
abstract void drawFill (java.awt.Graphics2D g)
abstract void drawStroke (java.awt.Graphics2D g)
void drawText (java.awt.Graphics2D g)
void writeAttributes (DOMOutput out) throws IOException
void readAttributes (DOMInput in) throws IOException
AttributeKey<?> getAttributeKey (String name)
void applyAttributesTo (Figure that)
Protected Member Functions inherited from org.jhotdraw.draw.figure.AbstractFigure
Drawing getDrawing ()
Object getLock ()
void fireAreaInvalidated (Rectangle2D.Double invalidatedArea)
void fireAreaInvalidated (FigureEvent event)
void fireFigureRequestRemove ()
void fireFigureAdded ()
void fireFigureRemoved ()
void fireFigureChanged (Rectangle2D.Double changedArea)
void fireFigureChanged (FigureEvent event)
void fireFigureHandlesChanged ()
void fireUndoableEditHappened (UndoableEdit edit)
boolean isChanging ()
int getChangingDepth ()
FontRenderContext getFontRenderContext ()
Protected Attributes inherited from org.jhotdraw.draw.figure.BezierFigure
BezierPath path
Protected Attributes inherited from org.jhotdraw.draw.figure.AbstractFigure
EventListenerList listenerList = new EventListenerList()
int changingDepth = 0
Detailed Description
A Figure which draws a continuous bezier path between two points.
Author
Werner Randelshofer
Version
$Id$
Constructor & Destructor Documentation
LineFigure()
org.jhotdraw.draw.figure.LineFigure.LineFigure ()
Creates a new instance.
References org.jhotdraw.draw.figure.BezierFigure.addNode(), and org.jhotdraw.draw.figure.AbstractFigure.setConnectable().
Member Function Documentation
createHandles()
Collection<Handle> org.jhotdraw.draw.figure.LineFigure.createHandles (int detailLevel)
Creates handles used to manipulate the figure.
Parameters
detailLevel The detail level of the handles. Usually this is 0 for bounding box handles and 1 for point handles. The value -1 is used by the SelectAreaTracker and the HandleTracker to highlight figures, over which the mouse pointer is hovering.
Returns
a Collection of handles
See also
Handle
Reimplemented from org.jhotdraw.draw.figure.BezierFigure.
Reimplemented in org.jhotdraw.draw.figure.LineConnectionFigure.
References org.jhotdraw.draw.figure.BezierFigure.path.
handleMouseClick()
boolean org.jhotdraw.draw.figure.LineFigure.handleMouseClick (Point2D.Double p, MouseEvent evt, DrawingView view)
Handles a mouse click.
Reimplemented from org.jhotdraw.draw.figure.BezierFigure.
Reimplemented in org.jhotdraw.draw.figure.LineConnectionFigure.
References org.jhotdraw.draw.figure.BezierFigure.addNode(), org.jhotdraw.draw.figure.AbstractFigure.changed(), org.jhotdraw.draw.figure.AbstractFigure.fireUndoableEditHappened(), org.jhotdraw.draw.DrawingView.getHandleDetailLevel(), org.jhotdraw.draw.figure.BezierFigure.getNode(), org.jhotdraw.draw.DrawingView.getScaleFactor(), org.jhotdraw.draw.figure.BezierFigure.removeNode(), org.jhotdraw.draw.figure.BezierFigure.splitSegment(), and org.jhotdraw.draw.figure.AbstractFigure.willChange().
The documentation for this class was generated from the following file:
jhotdraw-core/src/main/java/org/jhotdraw/draw/figure/LineFigure.java