jhotdraw: org.jhotdraw.draw.action.GroupAction Class Reference
org.jhotdraw.draw.action.GroupAction Class Reference
Public Member Functions
GroupAction (DrawingEditor editor)
GroupAction (DrawingEditor editor, CompositeFigure prototype)
GroupAction (DrawingEditor editor, CompositeFigure prototype, boolean isGroupingAction)
void actionPerformed (java.awt.event.ActionEvent e)
Collection< Figure > ungroupFigures (DrawingView view, CompositeFigure group)
void groupFigures (DrawingView view, CompositeFigure group, Collection< Figure > figures)
Public Member Functions inherited from org.jhotdraw.draw.action.AbstractSelectedAction
AbstractSelectedAction (DrawingEditor editor)
void dispose ()
void setEditor (DrawingEditor editor)
DrawingEditor getEditor ()
void setUpdateEnabledState (boolean newValue)
boolean isUpdatEnabledState ()
Static Public Attributes
static final String ID = "edit.groupSelection"
Protected Member Functions
void updateEnabledState ()
boolean canGroup ()
boolean canUngroup ()
Protected Member Functions inherited from org.jhotdraw.draw.action.AbstractSelectedAction
DrawingView getView ()
Drawing getDrawing ()
void fireUndoableEditHappened (UndoableEdit edit)
Detailed Description
GroupAction.
Author
Werner Randelshofer
Version
$Id$
Constructor & Destructor Documentation
GroupAction() [1/3]
org.jhotdraw.draw.action.GroupAction.GroupAction (DrawingEditor editor)
Creates a new instance.
GroupAction() [2/3]
org.jhotdraw.draw.action.GroupAction.GroupAction (DrawingEditor editor, CompositeFigure prototype)
GroupAction() [3/3]
org.jhotdraw.draw.action.GroupAction.GroupAction (DrawingEditor editor, CompositeFigure prototype, boolean isGroupingAction)
References org.jhotdraw.draw.action.GroupAction.ID, and org.jhotdraw.draw.action.GroupAction.updateEnabledState().
Member Function Documentation
actionPerformed()
void org.jhotdraw.draw.action.GroupAction.actionPerformed (java.awt.event.ActionEvent e)
References org.jhotdraw.draw.action.GroupAction.canGroup(), org.jhotdraw.draw.action.GroupAction.canUngroup(), org.jhotdraw.draw.figure.Figure.clone(), org.jhotdraw.draw.action.AbstractSelectedAction.fireUndoableEditHappened(), org.jhotdraw.draw.DrawingView.getSelectedFigures(), org.jhotdraw.draw.action.AbstractSelectedAction.getView(), org.jhotdraw.draw.action.GroupAction.groupFigures(), and org.jhotdraw.draw.action.GroupAction.ungroupFigures().
canGroup()
boolean org.jhotdraw.draw.action.GroupAction.canGroup () protected
References org.jhotdraw.draw.DrawingView.getSelectionCount(), and org.jhotdraw.draw.action.AbstractSelectedAction.getView().
Referenced by org.jhotdraw.draw.action.GroupAction.actionPerformed(), and org.jhotdraw.draw.action.GroupAction.updateEnabledState().
canUngroup()
boolean org.jhotdraw.draw.action.GroupAction.canUngroup () protected
References org.jhotdraw.draw.DrawingView.getSelectedFigures(), org.jhotdraw.draw.DrawingView.getSelectionCount(), and org.jhotdraw.draw.action.AbstractSelectedAction.getView().
Referenced by org.jhotdraw.draw.action.GroupAction.actionPerformed(), and org.jhotdraw.draw.action.GroupAction.updateEnabledState().
groupFigures()
void org.jhotdraw.draw.action.GroupAction.groupFigures (DrawingView view, CompositeFigure group, Collection< Figure > figures)
References org.jhotdraw.draw.Drawing.add(), org.jhotdraw.draw.DrawingView.addToSelection(), org.jhotdraw.draw.figure.CompositeFigure.basicAdd(), org.jhotdraw.draw.Drawing.basicRemoveAll(), org.jhotdraw.draw.figure.Figure.changed(), org.jhotdraw.draw.DrawingView.clearSelection(), org.jhotdraw.draw.DrawingView.getDrawing(), org.jhotdraw.draw.figure.CompositeFigure.indexOf(), org.jhotdraw.draw.Drawing.sort(), and org.jhotdraw.draw.figure.Figure.willChange().
Referenced by org.jhotdraw.draw.action.GroupAction.actionPerformed().
ungroupFigures()
Collection<Figure> org.jhotdraw.draw.action.GroupAction.ungroupFigures (DrawingView view, CompositeFigure group)
References org.jhotdraw.draw.DrawingView.addToSelection(), org.jhotdraw.draw.Drawing.basicAddAll(), org.jhotdraw.draw.figure.CompositeFigure.basicRemoveAllChildren(), org.jhotdraw.draw.DrawingView.clearSelection(), org.jhotdraw.draw.figure.CompositeFigure.getChildren(), org.jhotdraw.draw.DrawingView.getDrawing(), org.jhotdraw.draw.figure.CompositeFigure.indexOf(), and org.jhotdraw.draw.Drawing.remove().
Referenced by org.jhotdraw.draw.action.GroupAction.actionPerformed().
updateEnabledState()
void org.jhotdraw.draw.action.GroupAction.updateEnabledState () protected
Updates the enabled state of this action to reflect the enabled state of the active
DrawingView
. If no drawing view is active, this action is disabled.
Reimplemented from org.jhotdraw.draw.action.AbstractSelectedAction.
References org.jhotdraw.draw.action.GroupAction.canGroup(), org.jhotdraw.draw.action.GroupAction.canUngroup(), and org.jhotdraw.draw.action.AbstractSelectedAction.getView().
Referenced by org.jhotdraw.draw.action.GroupAction.GroupAction(), and org.jhotdraw.draw.action.UngroupAction.UngroupAction().
Member Data Documentation
ID
final String org.jhotdraw.draw.action.GroupAction.ID = "edit.groupSelection" static
Referenced by org.jhotdraw.draw.action.GroupAction.GroupAction().
The documentation for this class was generated from the following file:
jhotdraw-core/src/main/java/org/jhotdraw/draw/action/GroupAction.java