jhotdraw: org.jhotdraw.draw.figure.BezierFigure Class Reference
org.jhotdraw.draw.figure.BezierFigure Class Reference
Public Member Functions
BezierFigure ()
BezierFigure (boolean isClosed)
Connector findConnector (Point2D.Double p, ConnectionFigure prototype)
Connector findCompatibleConnector (Connector c, boolean isStart)
boolean contains (Point2D.Double p)
Collection< Handle > createHandles (int detailLevel)
Rectangle2D.Double getBounds ()
Rectangle2D.Double getDrawingArea (double factor)
BezierPath getBezierPath ()
void setBezierPath (BezierPath newValue)
Point2D.Double getPointOnPath (float relative, double flatness)
boolean isClosed ()
void setClosed (boolean newValue)
void setBounds (Point2D.Double anchor, Point2D.Double lead)
void transform (AffineTransform tx)
void invalidate ()
void layout ()
void addNode (BezierPath.Node p)
void addNode (final int index, BezierPath.Node p)
void setNode (int index, BezierPath.Node p)
BezierPath.Node getNode (int index)
Point2D.Double getPoint (int index)
Point2D.Double getPoint (int index, int coord)
void setPoint (int index, Point2D.Double p)
void setPoint (int index, int coord, Point2D.Double p)
void setStartPoint (Point2D.Double p)
void setEndPoint (Point2D.Double p)
Point2D.Double getStartPoint ()
Point2D.Double getEndPoint ()
int findNode (Point2D.Double p)
int findSegment (Point2D.Double find, double tolerance)
boolean joinSegments (Point2D.Double join, double tolerance)
int splitSegment (Point2D.Double split, double tolerance)
BezierPath.Node removeNode (int index)
int getNodeCount ()
BezierFigure clone ()
void restoreTransformTo (Object geometry)
Object getTransformRestoreData ()
Point2D.Double chop (Point2D.Double p)
Point2D.Double getCenter ()
Point2D.Double getOutermostPoint ()
int joinSegments (Point2D.Double join, float tolerance)
int splitSegment (Point2D.Double split, float tolerance)
boolean handleMouseClick (Point2D.Double p, MouseEvent evt, DrawingView view)
void write (DOMOutput out) throws IOException
void read (DOMInput in) throws IOException
Public Member Functions inherited from org.jhotdraw.draw.figure.AbstractAttributedFigure
AbstractAttributedFigure ()
void setAttributeEnabled (AttributeKey<?> key, boolean b)
boolean isAttributeEnabled (AttributeKey<?> key)
void setAttributes (Map< AttributeKey<?>, Object > map)
Map< AttributeKey<?>, Object > getAttributes ()
Object getAttributesRestoreData ()
void restoreAttributesTo (Object restoreData)
void draw (Graphics2D g)
double getStrokeMiterLimitFactor ()
Rectangle2D.Double getDrawingArea ()
boolean hasAttribute (AttributeKey<?> key)
Public Member Functions inherited from org.jhotdraw.draw.figure.AbstractFigure
AbstractFigure ()
void addFigureListener (FigureListener l)
void removeFigureListener (FigureListener l)
void addNotify (Drawing d)
void removeNotify (Drawing d)
void fireAreaInvalidated ()
void fireFigureChanged ()
void remap (Map< Figure, Figure > oldToNew, boolean disconnectIfNotInMap)
Cursor getCursor (Point2D.Double p)
final void setBounds (Rectangle2D.Double bounds)
void willChange ()
void changed ()
boolean includes (Figure figure)
Figure findFigureInside (Point2D.Double p)
Collection< Action > getActions (Point2D.Double p)
Tool getTool (Point2D.Double p)
boolean handleDrop (Point2D.Double p, Collection< Figure > droppedFigures, DrawingView view)
Dimension2DDouble getPreferredSize ()
boolean isConnectable ()
void setConnectable (boolean newValue)
boolean isSelectable ()
void setSelectable (boolean newValue)
boolean isRemovable ()
void setRemovable (boolean newValue)
boolean isTransformable ()
void setTransformable (boolean newValue)
boolean isVisible ()
void setVisible (boolean newValue)
Collection< Figure > getDecomposition ()
void requestRemove ()
int getLayer ()
String getToolTipText (Point2D.Double p)
String toString ()
Collection< Connector > getConnectors (ConnectionFigure prototype)
Public Member Functions inherited from org.jhotdraw.draw.figure.Figure
void addPropertyChangeListener (PropertyChangeListener listener)
void removePropertyChangeListener (PropertyChangeListener listener)
Protected Member Functions
void drawStroke (Graphics2D g)
void drawCaps (Graphics2D g)
void drawFill (Graphics2D g)
void validate ()
BezierPath getCappedPath ()
void removeAllNodes ()
void writePoints (DOMOutput out) throws IOException
void readPoints (DOMInput in) throws IOException
Protected Member Functions inherited from org.jhotdraw.draw.figure.AbstractAttributedFigure
abstract void drawFill (java.awt.Graphics2D g)
abstract void drawStroke (java.awt.Graphics2D g)
void drawText (java.awt.Graphics2D g)
void writeAttributes (DOMOutput out) throws IOException
void readAttributes (DOMInput in) throws IOException
AttributeKey<?> getAttributeKey (String name)
void applyAttributesTo (Figure that)
Protected Member Functions inherited from org.jhotdraw.draw.figure.AbstractFigure
Drawing getDrawing ()
Object getLock ()
void fireAreaInvalidated (Rectangle2D.Double invalidatedArea)
void fireAreaInvalidated (FigureEvent event)
void fireFigureRequestRemove ()
void fireFigureAdded ()
void fireFigureRemoved ()
void fireFigureChanged (Rectangle2D.Double changedArea)
void fireFigureChanged (FigureEvent event)
void fireFigureHandlesChanged ()
void fireUndoableEditHappened (UndoableEdit edit)
boolean isChanging ()
int getChangingDepth ()
FontRenderContext getFontRenderContext ()
Protected Attributes
BezierPath path
Protected Attributes inherited from org.jhotdraw.draw.figure.AbstractFigure
EventListenerList listenerList = new EventListenerList()
int changingDepth = 0
Additional Inherited Members
Static Public Attributes inherited from org.jhotdraw.draw.figure.Figure
static final String CONNECTABLE_PROPERTY = "connectable"
static final String REMOVABLE_PROPERTY = "removable"
static final String SELECTABLE_PROPERTY = "selectable"
static final String TRANSFORMABLE_PROPERTY = "transformable"
Detailed Description
A Figure which draws an opened or a closed bezier path.
A bezier figure can be used to draw arbitrary shapes using a BezierPath. It can be used to draw an open path or a closed shape.
A BezierFigure can have straight path segments and curved segments. A straight path segment can be added by clicking on the drawing area. Curved segments can be added by dragging the mouse pointer over the drawing area.
Design Patterns
Decorator
The start and end point of a
BezierFigure
can be decorated with a line decoration.
Component: BezierFigure; Decorator: org.jhotdraw.draw.decoration.LineDecoration.
See also
org.jhotdraw.geom.BezierPath
Author
Werner Randelshofer
Version
$Id$
Constructor & Destructor Documentation
BezierFigure() [1/2]
org.jhotdraw.draw.figure.BezierFigure.BezierFigure ()
Creates an empty BezierFigure, for example without any BezierPath.Nodes. The BezierFigure will not draw anything, if at least two nodes are added to it. The BezierPath created by this constructor is not closed.
Referenced by org.jhotdraw.draw.figure.BezierFigure.clone().
BezierFigure() [2/2]
org.jhotdraw.draw.figure.BezierFigure.BezierFigure (boolean isClosed)
Creates an empty BezierFigure, for example without any BezierPath.Nodes. The BezierFigure will not draw anything, unless at least two nodes are added to it.
Parameters
isClosed Specifies whether the BezierPath shall be closed.
References org.jhotdraw.draw.figure.BezierFigure.isClosed(), and org.jhotdraw.draw.figure.BezierFigure.path.
Member Function Documentation
addNode() [1/2]
void org.jhotdraw.draw.figure.BezierFigure.addNode (BezierPath.Node p)
Adds a control point.
References org.jhotdraw.draw.figure.BezierFigure.getNodeCount().
Referenced by org.jhotdraw.draw.tool.BezierTool.addPointToFigure(), org.jhotdraw.draw.figure.BezierFigure.handleMouseClick(), org.jhotdraw.draw.figure.LineFigure.handleMouseClick(), org.jhotdraw.draw.handle.BezierNodeHandle.keyPressed(), org.jhotdraw.draw.figure.LineFigure.LineFigure(), org.jhotdraw.draw.tool.BezierTool.mousePressed(), org.jhotdraw.draw.figure.BezierFigure.setEndPoint(), org.jhotdraw.draw.figure.BezierFigure.setStartPoint(), org.jhotdraw.draw.figure.BezierFigure.splitSegment(), and org.jhotdraw.draw.handle.BezierNodeHandle.trackDoubleClick().
addNode() [2/2]
void org.jhotdraw.draw.figure.BezierFigure.addNode (final int index, BezierPath.Node p)
Adds a node to the list of points.
References org.jhotdraw.draw.figure.BezierFigure.invalidate(), and org.jhotdraw.draw.figure.BezierFigure.path.
chop()
Point2D.Double org.jhotdraw.draw.figure.BezierFigure.chop (Point2D.Double p)
References org.jhotdraw.draw.AttributeKeys.getPerpendicularHitGrowth(), org.jhotdraw.draw.AttributeKeys.getStrokeTotalWidth(), org.jhotdraw.draw.figure.BezierFigure.isClosed(), and org.jhotdraw.draw.figure.BezierFigure.path.
Referenced by org.jhotdraw.draw.connector.ChopBezierConnector.chop().
clone()
BezierFigure org.jhotdraw.draw.figure.BezierFigure.clone ()
Returns a clone of the figure, with clones of all aggregated figures, such as children and decorators. The cloned figure does not clone the list of FigureListeners from its original.
Reimplemented from org.jhotdraw.draw.figure.AbstractAttributedFigure.
Reimplemented in org.jhotdraw.draw.figure.LineConnectionFigure, and org.jhotdraw.draw.figure.LabeledLineConnectionFigure.
References org.jhotdraw.draw.figure.BezierFigure.BezierFigure(), org.jhotdraw.draw.figure.BezierFigure.clone(), org.jhotdraw.draw.figure.BezierFigure.invalidate(), and org.jhotdraw.draw.figure.BezierFigure.path.
Referenced by org.jhotdraw.draw.figure.BezierFigure.clone(), and org.jhotdraw.draw.tool.BezierTool.createFigure().
contains()
boolean org.jhotdraw.draw.figure.BezierFigure.contains (Point2D.Double p)
Checks if a point is contained by the figure.
This is used for hit testing by Tool's.
Implements org.jhotdraw.draw.figure.Figure.
Reimplemented in org.jhotdraw.draw.figure.LabeledLineConnectionFigure.
References org.jhotdraw.draw.figure.BezierFigure.getCappedPath(), org.jhotdraw.draw.AttributeKeys.getPerpendicularHitGrowth(), org.jhotdraw.draw.AttributeKeys.getStrokeTotalWidth(), org.jhotdraw.draw.figure.BezierFigure.isClosed(), and org.jhotdraw.draw.figure.BezierFigure.path.
createHandles()
Collection<Handle> org.jhotdraw.draw.figure.BezierFigure.createHandles (int detailLevel)
Creates handles used to manipulate the figure.
Parameters
detailLevel The detail level of the handles. Usually this is 0 for bounding box handles and 1 for point handles. The value -1 is used by the SelectAreaTracker and the HandleTracker to highlight figures, over which the mouse pointer is hovering.
Returns
a Collection of handles
See also
Handle
Reimplemented from org.jhotdraw.draw.figure.AbstractFigure.
Reimplemented in org.jhotdraw.draw.figure.LineFigure, and org.jhotdraw.draw.figure.LineConnectionFigure.
References org.jhotdraw.draw.handle.TransformHandleKit.addTransformHandles(), and org.jhotdraw.draw.figure.BezierFigure.path.
drawCaps()
void org.jhotdraw.draw.figure.BezierFigure.drawCaps (Graphics2D g) protected
References org.jhotdraw.draw.figure.AbstractAttributedFigure.draw(), org.jhotdraw.draw.figure.BezierFigure.getCappedPath(), org.jhotdraw.draw.figure.BezierFigure.getNodeCount(), and org.jhotdraw.draw.figure.BezierFigure.path.
Referenced by org.jhotdraw.draw.figure.BezierFigure.drawStroke().
drawFill()
void org.jhotdraw.draw.figure.BezierFigure.drawFill (Graphics2D g) protected
References org.jhotdraw.draw.AttributeKeys.getPerpendicularFillGrowth(), org.jhotdraw.draw.AttributeKeys.getScaleFactorFromGraphics(), org.jhotdraw.draw.AttributeKeys.getStrokeTotalWidth(), org.jhotdraw.draw.figure.BezierFigure.isClosed(), and org.jhotdraw.draw.figure.BezierFigure.path.
drawStroke()
void org.jhotdraw.draw.figure.BezierFigure.drawStroke (Graphics2D g) protected
References org.jhotdraw.draw.figure.BezierFigure.drawCaps(), org.jhotdraw.draw.figure.BezierFigure.getCappedPath(), org.jhotdraw.draw.AttributeKeys.getPerpendicularDrawGrowth(), org.jhotdraw.draw.AttributeKeys.getScaleFactorFromGraphics(), org.jhotdraw.draw.AttributeKeys.getStrokeTotalWidth(), org.jhotdraw.draw.figure.BezierFigure.isClosed(), and org.jhotdraw.draw.figure.BezierFigure.path.
findCompatibleConnector()
Connector org.jhotdraw.draw.figure.BezierFigure.findCompatibleConnector (Connector c, boolean isStartConnector)
Gets a compatible connector. If the provided connector is part of this figure, return the connector. If the provided connector is part of another figure, return a connector with the same semantics for this figure. Returns null, if no compatible connector is available.
Reimplemented from org.jhotdraw.draw.figure.AbstractFigure.
findConnector()
Connector org.jhotdraw.draw.figure.BezierFigure.findConnector (Point2D.Double p, ConnectionFigure prototype)
Returns the Figures connector for the specified location. By default a ChopBezierConnector is returned.
Reimplemented from org.jhotdraw.draw.figure.AbstractFigure.
findNode()
int org.jhotdraw.draw.figure.BezierFigure.findNode (Point2D.Double p)
Finds a control point index. Returns -1 if no control point could be found. FIXME - Move this to BezierPath
References org.jhotdraw.draw.figure.BezierFigure.path.
findSegment()
int org.jhotdraw.draw.figure.BezierFigure.findSegment (Point2D.Double find, double tolerance)
Gets the segment of the polyline that is hit by the given Point2D.Double.
Parameters
find a Point on the bezier path
tolerance a tolerance, tolerance should take into account the line width, plus 2 divided by the zoom factor.
Returns
the index of the segment or -1 if no segment was hit.
References org.jhotdraw.draw.figure.BezierFigure.getBezierPath().
Referenced by org.jhotdraw.draw.figure.BezierFigure.joinSegments(), and org.jhotdraw.draw.figure.BezierFigure.splitSegment().
getBezierPath()
BezierPath org.jhotdraw.draw.figure.BezierFigure.getBezierPath ()
Returns a clone of the bezier path of this figure.
Reimplemented in org.jhotdraw.draw.figure.LineConnectionFigure.
References org.jhotdraw.draw.figure.BezierFigure.path.
Referenced by org.jhotdraw.draw.handle.BezierOutlineHandle.draw(), org.jhotdraw.draw.figure.BezierFigure.findSegment(), and org.jhotdraw.draw.tool.BezierTool.mouseReleased().
getBounds()
Rectangle2D.Double org.jhotdraw.draw.figure.BezierFigure.getBounds ()
Returns the untransformed logical bounds of the figure as a Rectangle.
The bounds are used by Handle objects for adjusting the figure and for aligning the figure on a grid.
Implements org.jhotdraw.draw.figure.Figure.
References org.jhotdraw.draw.figure.BezierFigure.path.
getCappedPath()
BezierPath org.jhotdraw.draw.figure.BezierFigure.getCappedPath () protected
Returns a path which is cappedPath at the ends, to prevent it from drawing under the end caps.
References org.jhotdraw.draw.figure.BezierFigure.isClosed(), and org.jhotdraw.draw.figure.BezierFigure.path.
Referenced by org.jhotdraw.draw.figure.BezierFigure.contains(), org.jhotdraw.draw.figure.BezierFigure.drawCaps(), and org.jhotdraw.draw.figure.BezierFigure.drawStroke().
getCenter()
Point2D.Double org.jhotdraw.draw.figure.BezierFigure.getCenter ()
References org.jhotdraw.draw.figure.BezierFigure.path.
Referenced by org.jhotdraw.draw.handle.BezierScaleHandle.trackStart().
getDrawingArea()
Rectangle2D.Double org.jhotdraw.draw.figure.BezierFigure.getDrawingArea (double factor)
Returns the drawing area of the figure as a Rectangle.
The drawing area is used to inform DrawingView about the area that is needed to draw this figure.
The drawing area needs to be large enough, to take line width, line caps and other decorations into account that exceed the bounds of the Figure.
Reimplemented from org.jhotdraw.draw.figure.AbstractAttributedFigure.
References org.jhotdraw.draw.figure.AbstractAttributedFigure.getDrawingArea(), org.jhotdraw.draw.figure.BezierFigure.getNodeCount(), and org.jhotdraw.draw.figure.BezierFigure.getPoint().
getEndPoint()
Point2D.Double org.jhotdraw.draw.figure.BezierFigure.getEndPoint ()
Convenience method for getting the end point.
Reimplemented from org.jhotdraw.draw.figure.AbstractFigure.
References org.jhotdraw.draw.figure.BezierFigure.getNodeCount(), and org.jhotdraw.draw.figure.BezierFigure.getPoint().
Referenced by org.jhotdraw.draw.tool.BezierTool.addPointToFigure().
getNode()
BezierPath.Node org.jhotdraw.draw.figure.BezierFigure.getNode (int index)
Gets a control point.
References org.jhotdraw.draw.figure.BezierFigure.path.
Referenced by org.jhotdraw.draw.handle.AbstractConnectionHandle.createSecondaryHandles(), org.jhotdraw.draw.handle.BezierNodeHandle.createSecondaryHandles(), org.jhotdraw.draw.handle.BezierControlPointHandle.draw(), org.jhotdraw.draw.handle.BezierNodeHandle.draw(), org.jhotdraw.draw.handle.AbstractConnectionHandle.getBezierNode(), org.jhotdraw.draw.handle.BezierControlPointHandle.getBezierNode(), org.jhotdraw.draw.handle.BezierNodeHandle.getBezierNode(), org.jhotdraw.draw.figure.BezierFigure.handleMouseClick(), org.jhotdraw.draw.figure.LineFigure.handleMouseClick(), org.jhotdraw.draw.handle.BezierControlPointHandle.keyPressed(), org.jhotdraw.draw.handle.BezierNodeHandle.keyPressed(), org.jhotdraw.draw.handle.BezierControlPointHandle.trackEnd(), org.jhotdraw.draw.handle.BezierNodeHandle.trackEnd(), org.jhotdraw.draw.handle.BezierControlPointHandle.trackStart(), org.jhotdraw.draw.handle.BezierNodeHandle.trackStart(), org.jhotdraw.draw.handle.BezierControlPointHandle.trackStep(), org.jhotdraw.draw.handle.BezierNodeHandle.trackStep(), and org.jhotdraw.draw.figure.BezierFigure.writePoints().
getNodeCount()
int org.jhotdraw.draw.figure.BezierFigure.getNodeCount ()
Gets the node count.
References org.jhotdraw.draw.figure.BezierFigure.path.
Referenced by org.jhotdraw.draw.figure.BezierFigure.addNode(), org.jhotdraw.draw.tool.BezierTool.addPointToFigure(), org.jhotdraw.draw.handle.AbstractConnectionHandle.createSecondaryHandles(), org.jhotdraw.draw.handle.BezierNodeHandle.createSecondaryHandles(), org.jhotdraw.draw.tool.BezierTool.deactivate(), org.jhotdraw.draw.handle.BezierControlPointHandle.draw(), org.jhotdraw.draw.handle.BezierNodeHandle.draw(), org.jhotdraw.draw.tool.BezierTool.draw(), org.jhotdraw.draw.figure.BezierFigure.drawCaps(), org.jhotdraw.draw.handle.AbstractConnectionHandle.getBezierNode(), org.jhotdraw.draw.handle.BezierControlPointHandle.getBezierNode(), org.jhotdraw.draw.handle.BezierNodeHandle.getBezierNode(), org.jhotdraw.draw.handle.ConnectionEndHandle.getBezierNodeIndex(), org.jhotdraw.draw.figure.BezierFigure.getDrawingArea(), org.jhotdraw.draw.figure.BezierFigure.getEndPoint(), org.jhotdraw.draw.handle.BezierControlPointHandle.isCombinableWith(), org.jhotdraw.draw.locator.BezierPointLocator.locate(), org.jhotdraw.draw.tool.BezierTool.mouseClicked(), org.jhotdraw.draw.tool.BezierTool.mouseMoved(), org.jhotdraw.draw.tool.BezierTool.mousePressed(), org.jhotdraw.draw.tool.BezierTool.mouseReleased(), org.jhotdraw.draw.figure.BezierFigure.setEndPoint(), org.jhotdraw.draw.figure.BezierFigure.setStartPoint(), org.jhotdraw.draw.handle.BezierNodeHandle.trackDoubleClick(), org.jhotdraw.draw.handle.BezierNodeHandle.trackEnd(), and org.jhotdraw.draw.figure.BezierFigure.writePoints().
getOutermostPoint()
Point2D.Double org.jhotdraw.draw.figure.BezierFigure.getOutermostPoint ()
References org.jhotdraw.draw.figure.BezierFigure.path.
getPoint() [1/2]
Point2D.Double org.jhotdraw.draw.figure.BezierFigure.getPoint (int index)
Convenience method for getting the point coordinate of the first control point of the specified node.
References org.jhotdraw.draw.figure.BezierFigure.path.
Referenced by org.jhotdraw.draw.tool.BezierTool.addPointToFigure(), org.jhotdraw.draw.figure.BezierFigure.getDrawingArea(), org.jhotdraw.draw.figure.BezierFigure.getEndPoint(), org.jhotdraw.draw.handle.BezierControlPointHandle.getLocation(), org.jhotdraw.draw.handle.BezierNodeHandle.getLocation(), org.jhotdraw.draw.figure.BezierFigure.getStartPoint(), org.jhotdraw.draw.locator.BezierPointLocator.locate(), and org.jhotdraw.draw.handle.BezierControlPointHandle.trackEnd().
getPoint() [2/2]
Point2D.Double org.jhotdraw.draw.figure.BezierFigure.getPoint (int index, int coord)
Gets the point coordinate of a control point.
References org.jhotdraw.draw.figure.BezierFigure.path.
getPointOnPath()
Point2D.Double org.jhotdraw.draw.figure.BezierFigure.getPointOnPath (float relative, double flatness)
References org.jhotdraw.draw.figure.BezierFigure.path.
Referenced by org.jhotdraw.draw.locator.BezierLabelLocator.getRelativeLabelPoint(), and org.jhotdraw.draw.locator.BezierLabelLocator.getRelativePoint().
getStartPoint()
Point2D.Double org.jhotdraw.draw.figure.BezierFigure.getStartPoint ()
Convenience method for getting the start point.
Reimplemented from org.jhotdraw.draw.figure.AbstractFigure.
References org.jhotdraw.draw.figure.BezierFigure.getPoint().
Referenced by org.jhotdraw.draw.tool.BezierTool.deactivate(), org.jhotdraw.draw.tool.BezierTool.draw(), org.jhotdraw.draw.tool.BezierTool.mouseClicked(), and org.jhotdraw.draw.tool.BezierTool.mouseMoved().
getTransformRestoreData()
Object org.jhotdraw.draw.figure.BezierFigure.getTransformRestoreData ()
Gets data which can be used to restore the transformation of the figure without loss of precision, after a transform has been applied to it.
See also
transform(AffineTransform)
Implements org.jhotdraw.draw.figure.Figure.
References org.jhotdraw.draw.figure.BezierFigure.path.
Referenced by org.jhotdraw.draw.handle.BezierScaleHandle.trackStart().
handleMouseClick()
boolean org.jhotdraw.draw.figure.BezierFigure.handleMouseClick (Point2D.Double p, MouseEvent evt, DrawingView view)
Handles a mouse click.
Reimplemented from org.jhotdraw.draw.figure.AbstractFigure.
Reimplemented in org.jhotdraw.draw.figure.LineFigure, and org.jhotdraw.draw.figure.LineConnectionFigure.
References org.jhotdraw.draw.figure.BezierFigure.addNode(), org.jhotdraw.draw.figure.AbstractFigure.changed(), org.jhotdraw.draw.figure.AbstractFigure.fireUndoableEditHappened(), org.jhotdraw.draw.DrawingView.getHandleDetailLevel(), org.jhotdraw.draw.figure.BezierFigure.getNode(), org.jhotdraw.draw.DrawingView.getScaleFactor(), org.jhotdraw.draw.figure.BezierFigure.removeNode(), org.jhotdraw.draw.figure.BezierFigure.splitSegment(), and org.jhotdraw.draw.figure.AbstractFigure.willChange().
invalidate()
void org.jhotdraw.draw.figure.BezierFigure.invalidate ()
Invalidates cached data of the Figure. This method must execute fast, because it can be called very often.
Reimplemented from org.jhotdraw.draw.figure.AbstractFigure.
Reimplemented in org.jhotdraw.draw.figure.LabeledLineConnectionFigure.
References org.jhotdraw.draw.figure.BezierFigure.path.
Referenced by org.jhotdraw.draw.figure.BezierFigure.addNode(), org.jhotdraw.draw.figure.BezierFigure.clone(), org.jhotdraw.draw.figure.BezierFigure.setBounds(), org.jhotdraw.draw.figure.BezierFigure.setNode(), org.jhotdraw.draw.figure.BezierFigure.setPoint(), and org.jhotdraw.draw.figure.BezierFigure.transform().
isClosed()
boolean org.jhotdraw.draw.figure.BezierFigure.isClosed ()
Referenced by org.jhotdraw.draw.figure.BezierFigure.BezierFigure(), org.jhotdraw.draw.figure.BezierFigure.chop(), org.jhotdraw.draw.figure.BezierFigure.contains(), org.jhotdraw.draw.handle.AbstractConnectionHandle.createSecondaryHandles(), org.jhotdraw.draw.handle.BezierNodeHandle.createSecondaryHandles(), org.jhotdraw.draw.tool.BezierTool.deactivate(), org.jhotdraw.draw.handle.BezierControlPointHandle.draw(), org.jhotdraw.draw.handle.BezierNodeHandle.draw(), org.jhotdraw.draw.tool.BezierTool.draw(), org.jhotdraw.draw.figure.BezierFigure.drawFill(), org.jhotdraw.draw.figure.BezierFigure.drawStroke(), org.jhotdraw.draw.figure.BezierFigure.getCappedPath(), org.jhotdraw.draw.tool.BezierTool.mouseMoved(), org.jhotdraw.draw.handle.BezierNodeHandle.trackEnd(), and org.jhotdraw.draw.figure.BezierFigure.writePoints().
joinSegments() [1/2]
boolean org.jhotdraw.draw.figure.BezierFigure.joinSegments (Point2D.Double join, double tolerance)
Joins two segments into one if the given Point2D.Double hits a node of the polyline.
Returns
true if the two segments were joined.
Parameters
join a Point at a node on the bezier path
tolerance a tolerance, tolerance should take into account the line width, plus 2 divided by the zoom factor.
References org.jhotdraw.draw.figure.BezierFigure.findSegment(), and org.jhotdraw.draw.figure.BezierFigure.removeNode().
joinSegments() [2/2]
int org.jhotdraw.draw.figure.BezierFigure.joinSegments (Point2D.Double join, float tolerance)
Joins two segments into one if the given Point2D.Double hits a node of the polyline.
Returns
true if the two segments were joined.
References org.jhotdraw.draw.figure.BezierFigure.path.
layout()
void org.jhotdraw.draw.figure.BezierFigure.layout ()
Reimplemented in org.jhotdraw.draw.figure.LabeledLineConnectionFigure.
read()
void org.jhotdraw.draw.figure.BezierFigure.read (DOMInput in) throws IOException
Reimplemented from org.jhotdraw.draw.figure.AbstractAttributedFigure.
Reimplemented in org.jhotdraw.draw.figure.LineConnectionFigure.
References org.jhotdraw.draw.figure.AbstractAttributedFigure.readAttributes(), and org.jhotdraw.draw.figure.BezierFigure.readPoints().
readPoints()
void org.jhotdraw.draw.figure.BezierFigure.readPoints (DOMInput in) throws IOException protected
Reimplemented in org.jhotdraw.draw.figure.LineConnectionFigure.
References org.jhotdraw.draw.figure.BezierFigure.path, and org.jhotdraw.draw.figure.BezierFigure.setClosed().
Referenced by org.jhotdraw.draw.figure.BezierFigure.read().
removeAllNodes()
void org.jhotdraw.draw.figure.BezierFigure.removeAllNodes () protected
Removes the Point2D.Double at the specified index.
References org.jhotdraw.draw.figure.BezierFigure.path.
removeNode()
BezierPath.Node org.jhotdraw.draw.figure.BezierFigure.removeNode (int index)
Removes the Node at the specified index.
References org.jhotdraw.draw.figure.BezierFigure.path.
Referenced by org.jhotdraw.draw.figure.BezierFigure.handleMouseClick(), org.jhotdraw.draw.figure.LineFigure.handleMouseClick(), org.jhotdraw.draw.figure.BezierFigure.joinSegments(), org.jhotdraw.draw.handle.BezierNodeHandle.keyPressed(), and org.jhotdraw.draw.handle.BezierNodeHandle.trackDoubleClick().
restoreTransformTo()
void org.jhotdraw.draw.figure.BezierFigure.restoreTransformTo (Object restoreData)
Restores the transform of the figure to a previously stored state.
Implements org.jhotdraw.draw.figure.Figure.
References org.jhotdraw.draw.figure.BezierFigure.path.
setBezierPath()
void org.jhotdraw.draw.figure.BezierFigure.setBezierPath (BezierPath newValue)
References org.jhotdraw.draw.figure.BezierFigure.path, and org.jhotdraw.draw.figure.BezierFigure.setClosed().
Referenced by org.jhotdraw.draw.tool.BezierTool.mouseReleased().
setBounds()
void org.jhotdraw.draw.figure.BezierFigure.setBounds (Point2D.Double anchor, Point2D.Double lead)
Sets the location of the first and the last BezierPath.Node of the BezierFigure. If the BezierFigure has not at least two nodes, nodes are added to the figure until the BezierFigure has at least two nodes.
Reimplemented from org.jhotdraw.draw.figure.AbstractFigure.
References org.jhotdraw.draw.figure.BezierFigure.invalidate(), org.jhotdraw.draw.figure.BezierFigure.setEndPoint(), and org.jhotdraw.draw.figure.BezierFigure.setStartPoint().
Referenced by org.jhotdraw.draw.action.LineDecorationIcon.LineDecorationIcon().
setClosed()
void org.jhotdraw.draw.figure.BezierFigure.setClosed (boolean newValue)
References org.jhotdraw.draw.figure.AbstractFigure.setConnectable().
Referenced by org.jhotdraw.draw.tool.BezierTool.mouseClicked(), org.jhotdraw.draw.figure.BezierFigure.readPoints(), and org.jhotdraw.draw.figure.BezierFigure.setBezierPath().
setEndPoint()
void org.jhotdraw.draw.figure.BezierFigure.setEndPoint (Point2D.Double p)
Convenience method for setting the point coordinate of the end point. If the BezierFigure has not at least two nodes, nodes are added to the figure until the BezierFigure has at least two nodes.
Reimplemented in org.jhotdraw.draw.figure.LineConnectionFigure.
References org.jhotdraw.draw.figure.BezierFigure.addNode(), org.jhotdraw.draw.figure.BezierFigure.getNodeCount(), and org.jhotdraw.draw.figure.BezierFigure.setPoint().
Referenced by org.jhotdraw.draw.figure.BezierFigure.setBounds().
setNode()
void org.jhotdraw.draw.figure.BezierFigure.setNode (int index, BezierPath.Node p)
Sets a control point.
Reimplemented in org.jhotdraw.draw.figure.LineConnectionFigure.
References org.jhotdraw.draw.figure.BezierFigure.invalidate(), and org.jhotdraw.draw.figure.BezierFigure.path.
Referenced by org.jhotdraw.draw.event.BezierNodeEdit.redo(), org.jhotdraw.draw.figure.BezierFigure.setPoint(), org.jhotdraw.draw.handle.BezierControlPointHandle.trackEnd(), org.jhotdraw.draw.handle.BezierNodeHandle.trackEnd(), org.jhotdraw.draw.handle.BezierNodeHandle.trackStep(), and org.jhotdraw.draw.event.BezierNodeEdit.undo().
setPoint() [1/2]
void org.jhotdraw.draw.figure.BezierFigure.setPoint (int index, int coord, Point2D.Double p)
Sets the point coordinate of a control point.
References org.jhotdraw.draw.figure.BezierFigure.path, and org.jhotdraw.draw.figure.BezierFigure.setNode().
setPoint() [2/2]
void org.jhotdraw.draw.figure.BezierFigure.setPoint (int index, Point2D.Double p)
Sets the point coordinate of control point 0 at the specified node.
Reimplemented in org.jhotdraw.draw.figure.LineConnectionFigure.
References org.jhotdraw.draw.figure.BezierFigure.invalidate(), and org.jhotdraw.draw.figure.BezierFigure.path.
Referenced by org.jhotdraw.draw.tool.BezierTool.addPointToFigure(), org.jhotdraw.draw.handle.BezierControlPointHandle.keyPressed(), org.jhotdraw.draw.handle.BezierNodeHandle.keyPressed(), org.jhotdraw.draw.figure.BezierFigure.setEndPoint(), org.jhotdraw.draw.figure.BezierFigure.setStartPoint(), and org.jhotdraw.draw.handle.BezierControlPointHandle.trackStep().
setStartPoint()
void org.jhotdraw.draw.figure.BezierFigure.setStartPoint (Point2D.Double p)
Convenience method for setting the point coordinate of the start point. If the BezierFigure has not at least two nodes, nodes are added to the figure until the BezierFigure has at least two nodes.
Reimplemented in org.jhotdraw.draw.figure.LineConnectionFigure.
References org.jhotdraw.draw.figure.BezierFigure.addNode(), org.jhotdraw.draw.figure.BezierFigure.getNodeCount(), and org.jhotdraw.draw.figure.BezierFigure.setPoint().
Referenced by org.jhotdraw.draw.figure.BezierFigure.setBounds().
splitSegment() [1/2]
int org.jhotdraw.draw.figure.BezierFigure.splitSegment (Point2D.Double split, double tolerance)
Splits the segment at the given Point2D.Double if a segment was hit.
Returns
the index of the segment or -1 if no segment was hit.
Parameters
split a Point on (or near) a line segment on the bezier path
tolerance a tolerance, tolerance should take into account the line width, plus 2 divided by the zoom factor.
References org.jhotdraw.draw.figure.BezierFigure.addNode(), and org.jhotdraw.draw.figure.BezierFigure.findSegment().
Referenced by org.jhotdraw.draw.figure.BezierFigure.handleMouseClick(), and org.jhotdraw.draw.figure.LineFigure.handleMouseClick().
splitSegment() [2/2]
int org.jhotdraw.draw.figure.BezierFigure.splitSegment (Point2D.Double split, float tolerance)
Splits the segment at the given Point2D.Double if a segment was hit.
Returns
the index of the segment or -1 if no segment was hit.
References org.jhotdraw.draw.figure.BezierFigure.path.
transform()
void org.jhotdraw.draw.figure.BezierFigure.transform (AffineTransform tx)
Transforms the shape of the Figure. Transformations using double precision arithmethics are inherently lossy operations. Therefore it is recommended to use getTransformRestoreData() restoreTransformTo() to provide lossless undo/redo functionality.
This is a basic operation which does not fire events. Use the following code sequence, if you need event firing:
figure.willChange();
figure.transform(...);
figure.changed();
Parameters
tx The transformation.
See also
getTransformRestoreData
restoreTransformTo
Implements org.jhotdraw.draw.figure.Figure.
Reimplemented in org.jhotdraw.draw.figure.LineConnectionFigure, and org.jhotdraw.draw.figure.LabeledLineConnectionFigure.
References org.jhotdraw.draw.figure.BezierFigure.invalidate(), and org.jhotdraw.draw.figure.BezierFigure.path.
validate()
void org.jhotdraw.draw.figure.BezierFigure.validate () protected
Reimplemented from org.jhotdraw.draw.figure.AbstractFigure.
Reimplemented in org.jhotdraw.draw.figure.LineConnectionFigure, and org.jhotdraw.draw.figure.LabeledLineConnectionFigure.
References org.jhotdraw.draw.figure.BezierFigure.path.
write()
void org.jhotdraw.draw.figure.BezierFigure.write (DOMOutput out) throws IOException
Reimplemented from org.jhotdraw.draw.figure.AbstractAttributedFigure.
Reimplemented in org.jhotdraw.draw.figure.LineConnectionFigure.
References org.jhotdraw.draw.figure.AbstractAttributedFigure.writeAttributes(), and org.jhotdraw.draw.figure.BezierFigure.writePoints().
writePoints()
void org.jhotdraw.draw.figure.BezierFigure.writePoints (DOMOutput out) throws IOException protected
Reimplemented in org.jhotdraw.draw.figure.LineConnectionFigure.
References org.jhotdraw.draw.figure.BezierFigure.getNode(), org.jhotdraw.draw.figure.BezierFigure.getNodeCount(), and org.jhotdraw.draw.figure.BezierFigure.isClosed().
Referenced by org.jhotdraw.draw.figure.BezierFigure.write().
Member Data Documentation
path
BezierPath org.jhotdraw.draw.figure.BezierFigure.path protected
The BezierPath.
Referenced by org.jhotdraw.draw.figure.BezierFigure.addNode(), org.jhotdraw.draw.figure.BezierFigure.BezierFigure(), org.jhotdraw.draw.figure.BezierFigure.chop(), org.jhotdraw.draw.figure.BezierFigure.clone(), org.jhotdraw.draw.figure.BezierFigure.contains(), org.jhotdraw.draw.figure.BezierFigure.createHandles(), org.jhotdraw.draw.figure.LineFigure.createHandles(), org.jhotdraw.draw.figure.BezierFigure.drawCaps(), org.jhotdraw.draw.figure.BezierFigure.drawFill(), org.jhotdraw.draw.figure.BezierFigure.drawStroke(), org.jhotdraw.draw.figure.BezierFigure.findNode(), org.jhotdraw.draw.figure.BezierFigure.getBezierPath(), org.jhotdraw.draw.figure.BezierFigure.getBounds(), org.jhotdraw.draw.figure.BezierFigure.getCappedPath(), org.jhotdraw.draw.figure.BezierFigure.getCenter(), org.jhotdraw.draw.figure.BezierFigure.getNode(), org.jhotdraw.draw.figure.BezierFigure.getNodeCount(), org.jhotdraw.draw.figure.BezierFigure.getOutermostPoint(), org.jhotdraw.draw.figure.BezierFigure.getPoint(), org.jhotdraw.draw.figure.BezierFigure.getPointOnPath(), org.jhotdraw.draw.figure.BezierFigure.getTransformRestoreData(), org.jhotdraw.draw.figure.BezierFigure.invalidate(), org.jhotdraw.draw.figure.BezierFigure.joinSegments(), org.jhotdraw.draw.figure.BezierFigure.readPoints(), org.jhotdraw.draw.figure.BezierFigure.removeAllNodes(), org.jhotdraw.draw.figure.BezierFigure.removeNode(), org.jhotdraw.draw.figure.BezierFigure.restoreTransformTo(), org.jhotdraw.draw.figure.BezierFigure.setBezierPath(), org.jhotdraw.draw.figure.BezierFigure.setNode(), org.jhotdraw.draw.figure.BezierFigure.setPoint(), org.jhotdraw.draw.figure.BezierFigure.splitSegment(), org.jhotdraw.draw.figure.BezierFigure.transform(), and org.jhotdraw.draw.figure.BezierFigure.validate().
The documentation for this class was generated from the following file:
jhotdraw-core/src/main/java/org/jhotdraw/draw/figure/BezierFigure.java