jhotdraw: org.jhotdraw.draw.action.ApplyAttributesAction Class Reference
org.jhotdraw.draw.action.ApplyAttributesAction Class Reference
Public Member Functions
ApplyAttributesAction (DrawingEditor editor)
void setExcludedAttributes (Set< AttributeKey<?>> a)
void actionPerformed (java.awt.event.ActionEvent e)
void applyAttributes ()
void selectionChanged (FigureSelectionEvent evt)
Public Member Functions inherited from org.jhotdraw.draw.action.AbstractSelectedAction
AbstractSelectedAction (DrawingEditor editor)
void dispose ()
void setEditor (DrawingEditor editor)
DrawingEditor getEditor ()
void setUpdateEnabledState (boolean newValue)
boolean isUpdatEnabledState ()
Additional Inherited Members
Protected Member Functions inherited from org.jhotdraw.draw.action.AbstractSelectedAction
void updateEnabledState ()
DrawingView getView ()
Drawing getDrawing ()
void fireUndoableEditHappened (UndoableEdit edit)
Detailed Description
ApplyAttributesAction.
Author
Werner Randelshofer
Version
$Id$
Constructor & Destructor Documentation
ApplyAttributesAction()
org.jhotdraw.draw.action.ApplyAttributesAction.ApplyAttributesAction (DrawingEditor editor)
Creates a new instance.
References org.jhotdraw.draw.action.AbstractSelectedAction.updateEnabledState().
Member Function Documentation
actionPerformed()
void org.jhotdraw.draw.action.ApplyAttributesAction.actionPerformed (java.awt.event.ActionEvent e)
References org.jhotdraw.draw.action.ApplyAttributesAction.applyAttributes().
applyAttributes()
void org.jhotdraw.draw.action.ApplyAttributesAction.applyAttributes ()
References org.jhotdraw.draw.Drawing.fireUndoableEditHappened(), org.jhotdraw.draw.DrawingEditor.getDefaultAttributes(), org.jhotdraw.draw.DrawingView.getDrawing(), org.jhotdraw.draw.action.AbstractSelectedAction.getEditor(), org.jhotdraw.draw.DrawingView.getSelectedFigures(), and org.jhotdraw.draw.action.AbstractSelectedAction.getView().
Referenced by org.jhotdraw.draw.action.ApplyAttributesAction.actionPerformed().
selectionChanged()
void org.jhotdraw.draw.action.ApplyAttributesAction.selectionChanged (FigureSelectionEvent evt)
References org.jhotdraw.draw.action.AbstractSelectedAction.getView().
setExcludedAttributes()
void org.jhotdraw.draw.action.ApplyAttributesAction.setExcludedAttributes (Set< AttributeKey<?>> a)
Set of attributes that is excluded when applying default attributes.
The documentation for this class was generated from the following file:
jhotdraw-core/src/main/java/org/jhotdraw/draw/action/ApplyAttributesAction.java