jhotdraw: org.jhotdraw.draw.handle.RotateHandle Class Reference
org.jhotdraw.draw.handle.RotateHandle Class Reference
Public Member Functions
RotateHandle (Figure owner)
Public Member Functions inherited from org.jhotdraw.draw.handle.AbstractRotateHandle
AbstractRotateHandle (Figure owner)
boolean isCombinableWith (Handle h)
String getToolTipText (Point p)
void draw (Graphics2D g)
Point getLocation ()
void trackStart (Point anchor, int modifiersEx)
void trackStep (Point anchor, Point lead, int modifiersEx)
void trackEnd (Point anchor, Point lead, int modifiersEx)
void keyPressed (KeyEvent evt)
Public Member Functions inherited from org.jhotdraw.draw.handle.AbstractHandle
AbstractHandle (Figure owner)
void addHandleListener (HandleListener l)
void removeHandleListener (HandleListener l)
Figure getOwner ()
void setView (DrawingView view)
DrawingView getView ()
DrawingEditor getEditor ()
boolean contains (Point p)
void invalidate ()
void dispose ()
void areaInvalidated (FigureEvent evt)
void figureAdded (FigureEvent e)
void figureRemoved (FigureEvent e)
void figureRequestRemove (FigureEvent e)
void figureChanged (FigureEvent evt)
Cursor getCursor ()
void keyTyped (KeyEvent evt)
void keyReleased (KeyEvent evt)
final Rectangle getBounds ()
Rectangle getDrawingArea ()
void trackDoubleClick (Point p, int modifiersEx)
void attributeChanged (FigureEvent e)
void viewTransformChanged ()
Collection< Handle > createSecondaryHandles ()
void setToolTipText (String newValue)
void figureHandlesChanged (FigureEvent e)
Protected Member Functions
Point2D.Double getCenter ()
Point2D.Double getOrigin ()
Protected Member Functions inherited from org.jhotdraw.draw.handle.AbstractRotateHandle
Rectangle basicGetBounds ()
Rectangle2D.Double getTransformedBounds ()
Object getRestoreData ()
double getStartTheta ()
Protected Member Functions inherited from org.jhotdraw.draw.handle.AbstractHandle
int getHandlesize ()
void fireAreaInvalidated (Rectangle invalidatedArea)
void fireUndoableEditHappened (UndoableEdit edit)
void fireHandleRequestRemove (Rectangle invalidatedArea)
void fireHandleRequestSecondaryHandles ()
void drawCircle (Graphics2D g, Color fill, Color stroke)
void drawRectangle (Graphics2D g, Color fill, Color stroke)
void drawDiamond (Graphics2D g, Color fill, Color stroke)
void updateBounds ()
Additional Inherited Members
Protected Attributes inherited from org.jhotdraw.draw.handle.AbstractHandle
DrawingView view
EventListenerList listenerList = new EventListenerList()
Detailed Description
A Handle to rotate a Figure.
Author
Werner Randelshofer.
Version
$Id$
Constructor & Destructor Documentation
RotateHandle()
org.jhotdraw.draw.handle.RotateHandle.RotateHandle (Figure owner)
Creates a new instance.
Member Function Documentation
getCenter()
Point2D.Double org.jhotdraw.draw.handle.RotateHandle.getCenter () protected
Reimplemented from org.jhotdraw.draw.handle.AbstractRotateHandle.
References org.jhotdraw.draw.handle.AbstractRotateHandle.getTransformedBounds().
getOrigin()
Point2D.Double org.jhotdraw.draw.handle.RotateHandle.getOrigin () protected
Reimplemented from org.jhotdraw.draw.handle.AbstractRotateHandle.
References org.jhotdraw.draw.handle.AbstractHandle.getHandlesize(), org.jhotdraw.draw.DrawingView.getScaleFactor(), org.jhotdraw.draw.handle.AbstractRotateHandle.getTransformedBounds(), and org.jhotdraw.draw.handle.AbstractHandle.view.
The documentation for this class was generated from the following file:
jhotdraw-core/src/main/java/org/jhotdraw/draw/handle/RotateHandle.java