jhotdraw: org.jhotdraw.draw.action.DefaultAttributeAction Class Reference
org.jhotdraw.draw.action.DefaultAttributeAction Class Reference
Public Member Functions
DefaultAttributeAction (DrawingEditor editor, AttributeKey<?> key)
DefaultAttributeAction (DrawingEditor editor, AttributeKey<?> key, Map< AttributeKey<?>, Object > fixedAttributes)
DefaultAttributeAction (DrawingEditor editor, AttributeKey<?>[] keys)
DefaultAttributeAction (DrawingEditor editor, AttributeKey<?> key, Icon icon)
DefaultAttributeAction (DrawingEditor editor, AttributeKey<?> key, String name)
DefaultAttributeAction (DrawingEditor editor, AttributeKey<?> key, String name, Icon icon)
DefaultAttributeAction (DrawingEditor editor, AttributeKey<?>[] keys, String name, Icon icon)
DefaultAttributeAction (DrawingEditor editor, AttributeKey<?>[] keys, String name, Icon icon, Map< AttributeKey<?>, Object > fixedAttributes)
void actionPerformed (java.awt.event.ActionEvent evt)
void changeAttribute ()
void selectionChanged (FigureSelectionEvent evt)
Public Member Functions inherited from org.jhotdraw.draw.action.AbstractSelectedAction
AbstractSelectedAction (DrawingEditor editor)
void dispose ()
void setEditor (DrawingEditor editor)
DrawingEditor getEditor ()
void setUpdateEnabledState (boolean newValue)
boolean isUpdatEnabledState ()
Additional Inherited Members
Protected Member Functions inherited from org.jhotdraw.draw.action.AbstractSelectedAction
void updateEnabledState ()
DrawingView getView ()
Drawing getDrawing ()
void fireUndoableEditHappened (UndoableEdit edit)
Detailed Description
DefaultAttributeAction.
XXX - should listen to changes in the default attributes of its DrawingEditor.
Author
Werner Randelshofer
Version
$Id$
Constructor & Destructor Documentation
DefaultAttributeAction() [1/8]
org.jhotdraw.draw.action.DefaultAttributeAction.DefaultAttributeAction (DrawingEditor editor, AttributeKey<?> key)
Creates a new instance.
DefaultAttributeAction() [2/8]
org.jhotdraw.draw.action.DefaultAttributeAction.DefaultAttributeAction (DrawingEditor editor, AttributeKey<?> key, Map< AttributeKey<?>, Object > fixedAttributes)
DefaultAttributeAction() [3/8]
org.jhotdraw.draw.action.DefaultAttributeAction.DefaultAttributeAction (DrawingEditor editor, AttributeKey<?>[] keys)
DefaultAttributeAction() [4/8]
org.jhotdraw.draw.action.DefaultAttributeAction.DefaultAttributeAction (DrawingEditor editor, AttributeKey<?> key, Icon icon)
Creates a new instance.
DefaultAttributeAction() [5/8]
org.jhotdraw.draw.action.DefaultAttributeAction.DefaultAttributeAction (DrawingEditor editor, AttributeKey<?> key, String name)
Creates a new instance.
DefaultAttributeAction() [6/8]
org.jhotdraw.draw.action.DefaultAttributeAction.DefaultAttributeAction (DrawingEditor editor, AttributeKey<?> key, String name, Icon icon)
DefaultAttributeAction() [7/8]
org.jhotdraw.draw.action.DefaultAttributeAction.DefaultAttributeAction (DrawingEditor editor, AttributeKey<?>[] keys, String name, Icon icon)
DefaultAttributeAction() [8/8]
org.jhotdraw.draw.action.DefaultAttributeAction.DefaultAttributeAction (DrawingEditor editor, AttributeKey<?>[] keys, String name, Icon icon, Map< AttributeKey<?>, Object > fixedAttributes)
References org.jhotdraw.draw.DrawingEditor.addPropertyChangeListener(), org.jhotdraw.draw.AttributeKey< T >.getKey(), and org.jhotdraw.draw.action.AbstractSelectedAction.updateEnabledState().
Member Function Documentation
actionPerformed()
void org.jhotdraw.draw.action.DefaultAttributeAction.actionPerformed (java.awt.event.ActionEvent evt)
References org.jhotdraw.draw.action.DefaultAttributeAction.changeAttribute(), org.jhotdraw.draw.action.AbstractSelectedAction.fireUndoableEditHappened(), and org.jhotdraw.draw.action.AbstractSelectedAction.getView().
changeAttribute()
void org.jhotdraw.draw.action.DefaultAttributeAction.changeAttribute ()
References org.jhotdraw.draw.action.AbstractSelectedAction.fireUndoableEditHappened(), org.jhotdraw.draw.DrawingEditor.getDefaultAttribute(), org.jhotdraw.draw.action.AbstractSelectedAction.getEditor(), and org.jhotdraw.draw.action.AbstractSelectedAction.getView().
Referenced by org.jhotdraw.draw.action.DefaultAttributeAction.actionPerformed().
selectionChanged()
void org.jhotdraw.draw.action.DefaultAttributeAction.selectionChanged (FigureSelectionEvent evt)
The documentation for this class was generated from the following file:
jhotdraw-core/src/main/java/org/jhotdraw/draw/action/DefaultAttributeAction.java