jhotdraw: org.jhotdraw.draw.AbstractDrawingView Class Reference
org.jhotdraw.draw.AbstractDrawingView Class Reference abstract
Public Member Functions
boolean isPaintBackground ()
void setPaintBackground (boolean paintBackground)
void repaintHandles ()
boolean isSelectionEmpty ()
AbstractDrawingView ()
Drawing getDrawing ()
String getToolTipText (MouseEvent evt)
void setEmptyDrawingMessage (String newValue)
String getEmptyDrawingMessage ()
void paintComponent (Graphics gr)
void printComponent (Graphics gr)
void setDrawing (Drawing newValue)
void addToSelection (Figure figure)
void addToSelection (Collection< Figure > figures)
void removeFromSelection (Figure figure)
void toggleSelection (Figure figure)
void selectAll ()
void clearSelection ()
boolean isFigureSelected (Figure checkFigure)
Set< Figure > getSelectedFigures ()
int getSelectionCount ()
Handle findHandle (Point p)
Collection< Handle > getCompatibleHandles (Handle master)
Figure findFigure (Point p)
Collection< Figure > findFigures (Rectangle r)
Collection< Figure > findFiguresWithin (Rectangle r)
void addFigureSelectionListener (FigureSelectionListener fsl)
void removeFigureSelectionListener (FigureSelectionListener fsl)
Constrainer getConstrainer ()
Point drawingToView (Point2D.Double p)
Rectangle drawingToView (Rectangle2D.Double r)
Point2D.Double viewToDrawing (Point p)
Rectangle2D.Double viewToDrawing (Rectangle r)
void fireViewTransformChanged ()
void setHandleDetailLevel (int newValue)
int getHandleDetailLevel ()
abstract AffineTransform getDrawingToViewTransform ()
void delete ()
void duplicate ()
void removeNotify (DrawingEditor editor)
void addNotify (DrawingEditor editor)
void setVisibleConstrainer (Constrainer newValue)
Constrainer getVisibleConstrainer ()
void setInvisibleConstrainer (Constrainer newValue)
Constrainer getInvisibleConstrainer ()
void setConstrainerVisible (boolean newValue)
boolean isConstrainerVisible ()
DrawingEditor getEditor ()
void setActiveHandle (Handle newValue)
Handle getActiveHandle ()
boolean isPaintEnabled ()
void addPropertyChangeListener (PropertyChangeListener listener)
void removePropertyChangeListener (PropertyChangeListener listener)
abstract void repaint (Rectangle r)
abstract Color getBackground ()
abstract void repaint ()
abstract int getWidth ()
abstract int getHeight ()
abstract void revalidate ()
Public Member Functions inherited from org.jhotdraw.draw.DrawingView
void setCursor (Cursor c)
void requestFocus ()
JComponent getComponent ()
double getScaleFactor ()
void setScaleFactor (double newValue)
void setEnabled (boolean newValue)
boolean isEnabled ()
void addMouseListener (MouseListener l)
void removeMouseListener (MouseListener l)
void addKeyListener (KeyListener l)
void removeKeyListener (KeyListener l)
void addMouseMotionListener (MouseMotionListener l)
void removeMouseMotionListener (MouseMotionListener l)
void addMouseWheelListener (MouseWheelListener l)
void removeMouseWheelListener (MouseWheelListener l)
Protected Member Functions
void drawBackground (Graphics2D g)
void setViewRenderingHints (Graphics2D g)
Rectangle getCanvasViewBounds ()
void drawCanvas (Graphics2D gr)
void drawConstrainer (Graphics2D g)
void drawDrawing (Graphics2D gr)
void drawHandles (java.awt.Graphics2D g)
void drawTool (Graphics2D g)
void repaintDrawingArea (Rectangle2D.Double r)
void fireSelectionChanged (Set< Figure > oldValue, Set< Figure > newValue)
Rectangle2D.Double getDrawingArea ()
Paint getBackgroundPaint (int x, int y)
Protected Attributes
BufferedImage backgroundTile
Additional Inherited Members
Static Public Attributes inherited from org.jhotdraw.draw.DrawingView
static final String DRAWING_PROPERTY = "drawing"
static final String CURSOR_PROPERTY = "cursor"
static final String CONSTRAINER_PROPERTY = "constrainer"
static final String VISIBLE_CONSTRAINER_PROPERTY = "visibleConstrainer"
static final String INVISIBLE_CONSTRAINER_PROPERTY = "invisibleConstrainer"
static final String CONSTRAINER_VISIBLE_PROPERTY = "constrainerVisible"
static final String SCALE_FACTOR_PROPERTY = "scaleFactor"
static final String HANDLE_DETAIL_LEVEL_PROPERTY = "handleDetailLevel"
static final String ENABLED_PROPERTY = "enabled"
static final String ACTIVE_HANDLE_PROPERTY = "activeHandle"
Detailed Description
Implementation of DrawingView using no JComponent as a backend. The displaying container comes with a delegator class. Therefore we have a Swing independend implementaion.
Author
tw
Constructor & Destructor Documentation
AbstractDrawingView()
org.jhotdraw.draw.AbstractDrawingView.AbstractDrawingView ()
Member Function Documentation
addFigureSelectionListener()
void org.jhotdraw.draw.AbstractDrawingView.addFigureSelectionListener (FigureSelectionListener fsl)
Add a listener for selection changes in this DrawingView.
Parameters
fsl jhotdraw.framework.FigureSelectionListener
Implements org.jhotdraw.draw.DrawingView.
addNotify()
void org.jhotdraw.draw.AbstractDrawingView.addNotify (DrawingEditor editor)
Informs the view that it has been added to the specified editor. The view must draw the tool of the editor, if getActiveView() of the editor returns the view.
Implements org.jhotdraw.draw.DrawingView.
References org.jhotdraw.draw.AbstractDrawingView.repaint().
addPropertyChangeListener()
void org.jhotdraw.draw.AbstractDrawingView.addPropertyChangeListener (PropertyChangeListener listener)
Adds a property change listener to the drawing view.
Parameters
listener
Implements org.jhotdraw.draw.DrawingView.
addToSelection() [1/2]
void org.jhotdraw.draw.AbstractDrawingView.addToSelection (Collection< Figure > figures)
Adds a collection of figures to the current selection.
Implements org.jhotdraw.draw.DrawingView.
References org.jhotdraw.draw.AbstractDrawingView.fireSelectionChanged(), org.jhotdraw.draw.AbstractDrawingView.getEditor(), and org.jhotdraw.draw.AbstractDrawingView.repaint().
addToSelection() [2/2]
void org.jhotdraw.draw.AbstractDrawingView.addToSelection (Figure figure)
Adds a figure to the current selection.
Implements org.jhotdraw.draw.DrawingView.
References org.jhotdraw.draw.figure.Figure.addFigureListener(), org.jhotdraw.draw.figure.Figure.createHandles(), org.jhotdraw.draw.AbstractDrawingView.fireSelectionChanged(), org.jhotdraw.draw.AbstractDrawingView.getEditor(), and org.jhotdraw.draw.AbstractDrawingView.repaint().
Referenced by org.jhotdraw.draw.AbstractDrawingView.delete(), org.jhotdraw.draw.AbstractDrawingView.duplicate(), and org.jhotdraw.draw.AbstractDrawingView.toggleSelection().
clearSelection()
void org.jhotdraw.draw.AbstractDrawingView.clearSelection ()
Clears the current selection.
Implements org.jhotdraw.draw.DrawingView.
References org.jhotdraw.draw.AbstractDrawingView.fireSelectionChanged(), and org.jhotdraw.draw.AbstractDrawingView.getSelectionCount().
Referenced by org.jhotdraw.draw.AbstractDrawingView.delete(), org.jhotdraw.draw.AbstractDrawingView.duplicate(), and org.jhotdraw.draw.AbstractDrawingView.setDrawing().
delete()
void org.jhotdraw.draw.AbstractDrawingView.delete ()
References org.jhotdraw.draw.Drawing.add(), org.jhotdraw.draw.AbstractDrawingView.addToSelection(), org.jhotdraw.draw.AbstractDrawingView.clearSelection(), org.jhotdraw.draw.Drawing.fireUndoableEditHappened(), org.jhotdraw.draw.AbstractDrawingView.getSelectedFigures(), org.jhotdraw.draw.figure.CompositeFigure.indexOf(), org.jhotdraw.draw.Drawing.remove(), org.jhotdraw.draw.Drawing.removeAll(), and org.jhotdraw.draw.Drawing.sort().
drawBackground()
void org.jhotdraw.draw.AbstractDrawingView.drawBackground (Graphics2D g) protected
Draws the background of the drawing view.
References org.jhotdraw.draw.AbstractDrawingView.drawingToView(), org.jhotdraw.draw.figure.Figure.get(), org.jhotdraw.draw.AbstractDrawingView.getBackground(), org.jhotdraw.draw.AbstractDrawingView.getBackgroundPaint(), org.jhotdraw.draw.AbstractDrawingView.getHeight(), and org.jhotdraw.draw.AbstractDrawingView.getWidth().
Referenced by org.jhotdraw.draw.AbstractDrawingView.paintComponent().
drawCanvas()
void org.jhotdraw.draw.AbstractDrawingView.drawCanvas (Graphics2D gr) protected
Draws the canvas. If the
AttributeKeys.CANVAS_FILL_OPACITY
is not fully opaque, the canvas area is filled with the background paint before the
AttributeKeys.CANVAS_FILL_COLOR
is drawn.
References org.jhotdraw.draw.Drawing.drawCanvas(), and org.jhotdraw.draw.Drawing.setFontRenderContext().
Referenced by org.jhotdraw.draw.AbstractDrawingView.paintComponent().
drawConstrainer()
void org.jhotdraw.draw.AbstractDrawingView.drawConstrainer (Graphics2D g) protected
References org.jhotdraw.draw.Constrainer.draw(), org.jhotdraw.draw.AbstractDrawingView.getCanvasViewBounds(), and org.jhotdraw.draw.AbstractDrawingView.getConstrainer().
Referenced by org.jhotdraw.draw.AbstractDrawingView.paintComponent().
drawDrawing()
void org.jhotdraw.draw.AbstractDrawingView.drawDrawing (Graphics2D gr) protected
References org.jhotdraw.draw.figure.Figure.draw(), org.jhotdraw.draw.figure.CompositeFigure.getChildCount(), org.jhotdraw.draw.AbstractDrawingView.getDrawingToViewTransform(), org.jhotdraw.draw.AbstractDrawingView.getHeight(), org.jhotdraw.draw.AbstractDrawingView.getWidth(), and org.jhotdraw.draw.Drawing.setFontRenderContext().
Referenced by org.jhotdraw.draw.AbstractDrawingView.paintComponent(), and org.jhotdraw.draw.AbstractDrawingView.printComponent().
drawHandles()
void org.jhotdraw.draw.AbstractDrawingView.drawHandles (java.awt.Graphics2D g) protected
References org.jhotdraw.draw.DrawingEditor.getActiveView().
Referenced by org.jhotdraw.draw.AbstractDrawingView.paintComponent().
drawingToView() [1/2]
Point org.jhotdraw.draw.AbstractDrawingView.drawingToView (Point2D.Double p)
Converts drawing coordinates to view coordinates.
Implements org.jhotdraw.draw.DrawingView.
References org.jhotdraw.draw.AbstractDrawingView.getDrawingToViewTransform().
Referenced by org.jhotdraw.draw.AbstractDrawingView.drawBackground(), org.jhotdraw.draw.AbstractDrawingView.drawingToView(), org.jhotdraw.draw.AbstractDrawingView.getCanvasViewBounds(), and org.jhotdraw.draw.AbstractDrawingView.repaintDrawingArea().
drawingToView() [2/2]
Rectangle org.jhotdraw.draw.AbstractDrawingView.drawingToView (Rectangle2D.Double r)
Minimal rectangle that encloses drawing rectangle (could be rotated).
Parameters
r
Returns
Implements org.jhotdraw.draw.DrawingView.
References org.jhotdraw.draw.AbstractDrawingView.drawingToView().
drawTool()
void org.jhotdraw.draw.AbstractDrawingView.drawTool (Graphics2D g) protected
References org.jhotdraw.draw.tool.Tool.draw(), org.jhotdraw.draw.DrawingEditor.getActiveView(), and org.jhotdraw.draw.DrawingEditor.getTool().
Referenced by org.jhotdraw.draw.AbstractDrawingView.paintComponent().
duplicate()
void org.jhotdraw.draw.AbstractDrawingView.duplicate ()
References org.jhotdraw.draw.Drawing.add(), org.jhotdraw.draw.Drawing.addAll(), org.jhotdraw.draw.AbstractDrawingView.addToSelection(), org.jhotdraw.draw.AbstractDrawingView.clearSelection(), org.jhotdraw.draw.figure.Figure.clone(), org.jhotdraw.draw.Drawing.fireUndoableEditHappened(), org.jhotdraw.draw.AbstractDrawingView.getSelectedFigures(), org.jhotdraw.draw.Drawing.removeAll(), org.jhotdraw.draw.Drawing.sort(), and org.jhotdraw.draw.figure.Figure.transform().
findFigure()
Figure org.jhotdraw.draw.AbstractDrawingView.findFigure (Point p)
Finds a figure at a given coordinates.
Returns
A figure, null if no figure is found.
Implements org.jhotdraw.draw.DrawingView.
References org.jhotdraw.draw.Drawing.findFigure(), and org.jhotdraw.draw.AbstractDrawingView.viewToDrawing().
findFigures()
Collection<Figure> org.jhotdraw.draw.AbstractDrawingView.findFigures (Rectangle r)
Returns all figures that lie within or intersect the specified bounds. The figures are returned in Z-order from back to front.
Implements org.jhotdraw.draw.DrawingView.
References org.jhotdraw.draw.Drawing.findFigures(), and org.jhotdraw.draw.AbstractDrawingView.viewToDrawing().
findFiguresWithin()
Collection<Figure> org.jhotdraw.draw.AbstractDrawingView.findFiguresWithin (Rectangle r)
Returns all figures that lie within the specified bounds. The figures are returned in Z-order from back to front.
Implements org.jhotdraw.draw.DrawingView.
References org.jhotdraw.draw.Drawing.findFiguresWithin(), and org.jhotdraw.draw.AbstractDrawingView.viewToDrawing().
findHandle()
Handle org.jhotdraw.draw.AbstractDrawingView.findHandle (Point p)
Finds a handle at a given coordinates.
Returns
A handle, null if no handle is found.
Implements org.jhotdraw.draw.DrawingView.
fireSelectionChanged()
void org.jhotdraw.draw.AbstractDrawingView.fireSelectionChanged (Set< Figure > oldValue, Set< Figure > newValue) protected
Notify all listenerList that have registered interest for notification on this event type. Also notify listeners who listen for EditableComponent#SELECTION_EMPTY_PROPERTY.
Referenced by org.jhotdraw.draw.AbstractDrawingView.addToSelection(), org.jhotdraw.draw.AbstractDrawingView.clearSelection(), org.jhotdraw.draw.AbstractDrawingView.removeFromSelection(), and org.jhotdraw.draw.AbstractDrawingView.selectAll().
fireViewTransformChanged()
void org.jhotdraw.draw.AbstractDrawingView.fireViewTransformChanged ()
getActiveHandle()
Handle org.jhotdraw.draw.AbstractDrawingView.getActiveHandle ()
Gets the active handle.
Implements org.jhotdraw.draw.DrawingView.
getBackground()
abstract Color org.jhotdraw.draw.AbstractDrawingView.getBackground () abstract
Reimplemented in org.jhotdraw.draw.DelegatorDrawingView.
Referenced by org.jhotdraw.draw.AbstractDrawingView.drawBackground().
getBackgroundPaint()
Paint org.jhotdraw.draw.AbstractDrawingView.getBackgroundPaint (int x, int y) protected
Returns a paint for drawing the background of the drawing area.
Returns
Paint.
References org.jhotdraw.draw.AbstractDrawingView.backgroundTile.
Referenced by org.jhotdraw.draw.AbstractDrawingView.drawBackground().
getCanvasViewBounds()
Rectangle org.jhotdraw.draw.AbstractDrawingView.getCanvasViewBounds () protected
Returns the bounds of the canvas on the drawing view.
Returns
The current bounds of the canvas on the drawing view.
References org.jhotdraw.draw.AbstractDrawingView.drawingToView(), org.jhotdraw.draw.figure.Figure.get(), org.jhotdraw.draw.AbstractDrawingView.getDrawing(), org.jhotdraw.draw.AbstractDrawingView.getHeight(), and org.jhotdraw.draw.AbstractDrawingView.getWidth().
Referenced by org.jhotdraw.draw.AbstractDrawingView.drawConstrainer().
getCompatibleHandles()
Collection<Handle> org.jhotdraw.draw.AbstractDrawingView.getCompatibleHandles (Handle master)
Gets compatible handles.
Returns
A collection containing the handle and all compatible handles.
Implements org.jhotdraw.draw.DrawingView.
References org.jhotdraw.draw.handle.Handle.getOwner().
getConstrainer()
Constrainer org.jhotdraw.draw.AbstractDrawingView.getConstrainer ()
Gets the current constrainer of this view. If isConstrainerVisible is true, this method returns getVisibleConstrainer, otherwise it returns getInvisibleConstrainer. This is a bound property.
Implements org.jhotdraw.draw.DrawingView.
Referenced by org.jhotdraw.draw.AbstractDrawingView.drawConstrainer().
getDrawing()
Drawing org.jhotdraw.draw.AbstractDrawingView.getDrawing ()
Gets the drawing. This is a bound property.
Implements org.jhotdraw.draw.DrawingView.
Referenced by org.jhotdraw.draw.AbstractDrawingView.getCanvasViewBounds().
getDrawingArea()
Rectangle2D.Double org.jhotdraw.draw.AbstractDrawingView.getDrawingArea () protected
References org.jhotdraw.draw.figure.Figure.getDrawingArea().
getDrawingToViewTransform()
abstract AffineTransform org.jhotdraw.draw.AbstractDrawingView.getDrawingToViewTransform () abstract
Gets an transform which can be used to convert drawing coordinates to view coordinates.
Implements org.jhotdraw.draw.DrawingView.
Reimplemented in org.jhotdraw.draw.DelegatorDrawingView.
Referenced by org.jhotdraw.draw.AbstractDrawingView.drawDrawing(), org.jhotdraw.draw.AbstractDrawingView.drawingToView(), and org.jhotdraw.draw.AbstractDrawingView.viewToDrawing().
getEditor()
DrawingEditor org.jhotdraw.draw.AbstractDrawingView.getEditor ()
Gets the drawing editor associated to the DrawingView. This is a bound property.
Implements org.jhotdraw.draw.DrawingView.
Referenced by org.jhotdraw.draw.AbstractDrawingView.addToSelection(), and org.jhotdraw.draw.AbstractDrawingView.getToolTipText().
getEmptyDrawingMessage()
String org.jhotdraw.draw.AbstractDrawingView.getEmptyDrawingMessage ()
getHandleDetailLevel()
int org.jhotdraw.draw.AbstractDrawingView.getHandleDetailLevel ()
Returns the detail level of the handles. This is a bound property.
Implements org.jhotdraw.draw.DrawingView.
getHeight()
abstract int org.jhotdraw.draw.AbstractDrawingView.getHeight () abstract
Reimplemented in org.jhotdraw.draw.DelegatorDrawingView.
Referenced by org.jhotdraw.draw.AbstractDrawingView.drawBackground(), org.jhotdraw.draw.AbstractDrawingView.drawDrawing(), and org.jhotdraw.draw.AbstractDrawingView.getCanvasViewBounds().
getInvisibleConstrainer()
Constrainer org.jhotdraw.draw.AbstractDrawingView.getInvisibleConstrainer ()
Gets the editor's constrainer for this view, for use, when the visible constrainer is turned off. This is a bound property.
Implements org.jhotdraw.draw.DrawingView.
getSelectedFigures()
Set<Figure> org.jhotdraw.draw.AbstractDrawingView.getSelectedFigures ()
Gets the current selection as a FigureSelection. A FigureSelection can be cut, copied, pasted.
Implements org.jhotdraw.draw.DrawingView.
Referenced by org.jhotdraw.draw.AbstractDrawingView.delete(), and org.jhotdraw.draw.AbstractDrawingView.duplicate().
getSelectionCount()
int org.jhotdraw.draw.AbstractDrawingView.getSelectionCount ()
Gets the number of selected figures.
Implements org.jhotdraw.draw.DrawingView.
Referenced by org.jhotdraw.draw.AbstractDrawingView.clearSelection().
getToolTipText()
String org.jhotdraw.draw.AbstractDrawingView.getToolTipText (MouseEvent evt)
References org.jhotdraw.draw.AbstractDrawingView.getEditor(), org.jhotdraw.draw.DrawingEditor.getTool(), and org.jhotdraw.draw.tool.Tool.getToolTipText().
getVisibleConstrainer()
Constrainer org.jhotdraw.draw.AbstractDrawingView.getVisibleConstrainer ()
Gets the editor's constrainer for this view, for use, when the visible constrainer is turned on. This is a bound property.
Implements org.jhotdraw.draw.DrawingView.
getWidth()
abstract int org.jhotdraw.draw.AbstractDrawingView.getWidth () abstract
Reimplemented in org.jhotdraw.draw.DelegatorDrawingView.
Referenced by org.jhotdraw.draw.AbstractDrawingView.drawBackground(), org.jhotdraw.draw.AbstractDrawingView.drawDrawing(), and org.jhotdraw.draw.AbstractDrawingView.getCanvasViewBounds().
isConstrainerVisible()
boolean org.jhotdraw.draw.AbstractDrawingView.isConstrainerVisible ()
Returns true, if the visible Constrainer is in use, returns false, if the invisible Constrainer is in use. This is a bound property.
Implements org.jhotdraw.draw.DrawingView.
isFigureSelected()
boolean org.jhotdraw.draw.AbstractDrawingView.isFigureSelected (Figure checkFigure)
Test whether a given figure is selected.
Implements org.jhotdraw.draw.DrawingView.
isPaintBackground()
boolean org.jhotdraw.draw.AbstractDrawingView.isPaintBackground ()
Referenced by org.jhotdraw.draw.AbstractDrawingView.paintComponent().
isPaintEnabled()
boolean org.jhotdraw.draw.AbstractDrawingView.isPaintEnabled ()
Referenced by org.jhotdraw.draw.AbstractDrawingView.paintComponent(), and org.jhotdraw.draw.AbstractDrawingView.printComponent().
isSelectionEmpty()
boolean org.jhotdraw.draw.AbstractDrawingView.isSelectionEmpty ()
paintComponent()
void org.jhotdraw.draw.AbstractDrawingView.paintComponent (Graphics gr)
Paints the drawing view. Uses rendering hints for fast painting. Paints the canvasColor, the grid, the drawing, the handles and the current tool. TODO: Rename to reflect this is not a Swing or AWT method.
References org.jhotdraw.draw.AbstractDrawingView.drawBackground(), org.jhotdraw.draw.AbstractDrawingView.drawCanvas(), org.jhotdraw.draw.AbstractDrawingView.drawConstrainer(), org.jhotdraw.draw.AbstractDrawingView.drawDrawing(), org.jhotdraw.draw.AbstractDrawingView.drawHandles(), org.jhotdraw.draw.AbstractDrawingView.drawTool(), org.jhotdraw.draw.AbstractDrawingView.isPaintBackground(), org.jhotdraw.draw.AbstractDrawingView.isPaintEnabled(), and org.jhotdraw.draw.AbstractDrawingView.setViewRenderingHints().
printComponent()
void org.jhotdraw.draw.AbstractDrawingView.printComponent (Graphics gr)
Prints the drawing view. Uses high quality rendering hints for printing. Only prints the drawing. Doesn't print the canvasColor, the grid, the handles and the tool. TODO: rename to reflect that this is not swing or awt
References org.jhotdraw.draw.AbstractDrawingView.drawDrawing(), and org.jhotdraw.draw.AbstractDrawingView.isPaintEnabled().
removeFigureSelectionListener()
void org.jhotdraw.draw.AbstractDrawingView.removeFigureSelectionListener (FigureSelectionListener fsl)
Remove a listener for selection changes in this DrawingView.
Parameters
fsl jhotdraw.framework.FigureSelectionListener
Implements org.jhotdraw.draw.DrawingView.
removeFromSelection()
void org.jhotdraw.draw.AbstractDrawingView.removeFromSelection (Figure figure)
Removes a figure from the selection.
Implements org.jhotdraw.draw.DrawingView.
References org.jhotdraw.draw.AbstractDrawingView.fireSelectionChanged(), org.jhotdraw.draw.figure.Figure.removeFigureListener(), and org.jhotdraw.draw.AbstractDrawingView.repaint().
Referenced by org.jhotdraw.draw.AbstractDrawingView.toggleSelection().
removeNotify()
void org.jhotdraw.draw.AbstractDrawingView.removeNotify (DrawingEditor editor)
Informs the view that it has been removed from the specified editor. The view must not draw the tool from the editor anymore.
Implements org.jhotdraw.draw.DrawingView.
References org.jhotdraw.draw.AbstractDrawingView.repaint().
removePropertyChangeListener()
void org.jhotdraw.draw.AbstractDrawingView.removePropertyChangeListener (PropertyChangeListener listener)
Removes a property change listener to the drawing view.
Parameters
listener
Implements org.jhotdraw.draw.DrawingView.
repaint() [1/2]
abstract void org.jhotdraw.draw.AbstractDrawingView.repaint () abstract
Reimplemented in org.jhotdraw.draw.DelegatorDrawingView.
Referenced by org.jhotdraw.draw.AbstractDrawingView.addNotify(), org.jhotdraw.draw.AbstractDrawingView.addToSelection(), org.jhotdraw.draw.AbstractDrawingView.removeFromSelection(), org.jhotdraw.draw.AbstractDrawingView.removeNotify(), org.jhotdraw.draw.AbstractDrawingView.repaintDrawingArea(), org.jhotdraw.draw.AbstractDrawingView.repaintHandles(), org.jhotdraw.draw.AbstractDrawingView.selectAll(), org.jhotdraw.draw.AbstractDrawingView.setActiveHandle(), org.jhotdraw.draw.AbstractDrawingView.setConstrainerVisible(), org.jhotdraw.draw.AbstractDrawingView.setDrawing(), and org.jhotdraw.draw.AbstractDrawingView.setEmptyDrawingMessage().
repaint() [2/2]
abstract void org.jhotdraw.draw.AbstractDrawingView.repaint (Rectangle r) abstract
Reimplemented in org.jhotdraw.draw.DelegatorDrawingView.
repaintDrawingArea()
void org.jhotdraw.draw.AbstractDrawingView.repaintDrawingArea (Rectangle2D.Double r) protected
References org.jhotdraw.draw.AbstractDrawingView.drawingToView(), and org.jhotdraw.draw.AbstractDrawingView.repaint().
repaintHandles()
void org.jhotdraw.draw.AbstractDrawingView.repaintHandles ()
Repaints the handles of the view.
Implements org.jhotdraw.draw.DrawingView.
References org.jhotdraw.draw.AbstractDrawingView.repaint().
revalidate()
abstract void org.jhotdraw.draw.AbstractDrawingView.revalidate () abstract
Reimplemented in org.jhotdraw.draw.DelegatorDrawingView.
Referenced by org.jhotdraw.draw.AbstractDrawingView.setDrawing().
selectAll()
void org.jhotdraw.draw.AbstractDrawingView.selectAll ()
Selects all selectable figures.
Implements org.jhotdraw.draw.DrawingView.
References org.jhotdraw.draw.AbstractDrawingView.fireSelectionChanged(), org.jhotdraw.draw.figure.CompositeFigure.getChildren(), and org.jhotdraw.draw.AbstractDrawingView.repaint().
setActiveHandle()
void org.jhotdraw.draw.AbstractDrawingView.setActiveHandle (Handle newValue)
Sets the active handle.
Implements org.jhotdraw.draw.DrawingView.
References org.jhotdraw.draw.DrawingView.ACTIVE_HANDLE_PROPERTY, org.jhotdraw.draw.handle.Handle.getDrawingArea(), and org.jhotdraw.draw.AbstractDrawingView.repaint().
setConstrainerVisible()
void org.jhotdraw.draw.AbstractDrawingView.setConstrainerVisible (boolean newValue)
Changes between a visible Constrainer and an invisible Constrainer. This is a bound property.
Implements org.jhotdraw.draw.DrawingView.
References org.jhotdraw.draw.DrawingView.CONSTRAINER_VISIBLE_PROPERTY, and org.jhotdraw.draw.AbstractDrawingView.repaint().
setDrawing()
void org.jhotdraw.draw.AbstractDrawingView.setDrawing (Drawing d)
Sets and installs another drawing in the view. This is a bound property.
Implements org.jhotdraw.draw.DrawingView.
References org.jhotdraw.draw.figure.CompositeFigure.addCompositeFigureListener(), org.jhotdraw.draw.figure.Figure.addFigureListener(), org.jhotdraw.draw.AbstractDrawingView.clearSelection(), org.jhotdraw.draw.DrawingView.DRAWING_PROPERTY, org.jhotdraw.draw.figure.CompositeFigure.removeCompositeFigureListener(), org.jhotdraw.draw.figure.Figure.removeFigureListener(), org.jhotdraw.draw.AbstractDrawingView.repaint(), and org.jhotdraw.draw.AbstractDrawingView.revalidate().
setEmptyDrawingMessage()
void org.jhotdraw.draw.AbstractDrawingView.setEmptyDrawingMessage (String newValue)
References org.jhotdraw.draw.AbstractDrawingView.repaint().
setHandleDetailLevel()
void org.jhotdraw.draw.AbstractDrawingView.setHandleDetailLevel (int newValue)
The detail level of the handles. This is a bound property.
Implements org.jhotdraw.draw.DrawingView.
setInvisibleConstrainer()
void org.jhotdraw.draw.AbstractDrawingView.setInvisibleConstrainer (Constrainer constrainer)
Sets the editor's constrainer for this view, for use, when the visible constrainer is turned off. This is a bound property.
Implements org.jhotdraw.draw.DrawingView.
References org.jhotdraw.draw.DrawingView.INVISIBLE_CONSTRAINER_PROPERTY.
setPaintBackground()
void org.jhotdraw.draw.AbstractDrawingView.setPaintBackground (boolean paintBackground)
setViewRenderingHints()
void org.jhotdraw.draw.AbstractDrawingView.setViewRenderingHints (Graphics2D g) protected
Referenced by org.jhotdraw.draw.AbstractDrawingView.paintComponent().
setVisibleConstrainer()
void org.jhotdraw.draw.AbstractDrawingView.setVisibleConstrainer (Constrainer constrainer)
Sets the editor's constrainer for this view, for use, when the visible constrainer is turned on. This is a bound property.
Implements org.jhotdraw.draw.DrawingView.
References org.jhotdraw.draw.DrawingView.VISIBLE_CONSTRAINER_PROPERTY.
toggleSelection()
void org.jhotdraw.draw.AbstractDrawingView.toggleSelection (Figure figure)
If a figure isn't selected it is added to the selection. Otherwise it is removed from the selection.
Implements org.jhotdraw.draw.DrawingView.
References org.jhotdraw.draw.AbstractDrawingView.addToSelection(), and org.jhotdraw.draw.AbstractDrawingView.removeFromSelection().
viewToDrawing() [1/2]
Point2D.Double org.jhotdraw.draw.AbstractDrawingView.viewToDrawing (Point p)
Converts view coordinates to drawing coordinates.
Implements org.jhotdraw.draw.DrawingView.
References org.jhotdraw.draw.AbstractDrawingView.getDrawingToViewTransform().
Referenced by org.jhotdraw.draw.AbstractDrawingView.findFigure(), org.jhotdraw.draw.AbstractDrawingView.findFigures(), org.jhotdraw.draw.AbstractDrawingView.findFiguresWithin(), and org.jhotdraw.draw.AbstractDrawingView.viewToDrawing().
viewToDrawing() [2/2]
Rectangle2D.Double org.jhotdraw.draw.AbstractDrawingView.viewToDrawing (Rectangle r)
Rectangles are not rotated. Therefore we deliver the smallest rectangle that encloses the rotated target rectangle.
Implements org.jhotdraw.draw.DrawingView.
References org.jhotdraw.draw.AbstractDrawingView.viewToDrawing().
Member Data Documentation
backgroundTile
BufferedImage org.jhotdraw.draw.AbstractDrawingView.backgroundTile protected
Referenced by org.jhotdraw.draw.AbstractDrawingView.getBackgroundPaint().
The documentation for this class was generated from the following file:
jhotdraw-core/src/main/java/org/jhotdraw/draw/AbstractDrawingView.java