jhotdraw: org.jhotdraw.draw.print.DrawingPageable Class Reference
org.jhotdraw.draw.print.DrawingPageable Class Reference
Public Member Functions
DrawingPageable (Drawing drawing)
int getNumberOfPages ()
PageFormat getPageFormat (int pageIndex) throws IndexOutOfBoundsException
Printable getPrintable (int pageIndex) throws IndexOutOfBoundsException
int printPage (Graphics graphics, PageFormat pageFormat, int pageIndex) throws PrinterException
Protected Member Functions
void setRenderingHints (Graphics2D g)
Detailed Description
DrawingPageable
can be used to print a Drawing using the java.awt.print API.
Usage:
Pageable pageable = new DrawingPageable(aDrawing);
PrinterJob job = PrinterJob.getPrinterJob();
job.setPageable(pageable);
if (job.printDialog()) {
    try {
        job.print();
     } catch (PrinterException e) {
         ...inform the user that we couldn't print...
     }
}
Author
Werner Randelshofer
Version
$Id$
See also
org.jhotdraw.app.action.file.PrintFileAction
Constructor & Destructor Documentation
DrawingPageable()
org.jhotdraw.draw.print.DrawingPageable.DrawingPageable (Drawing drawing)
Creates a new instance.
Member Function Documentation
getNumberOfPages()
int org.jhotdraw.draw.print.DrawingPageable.getNumberOfPages ()
Referenced by org.jhotdraw.draw.print.DrawingPageable.getPrintable(), and org.jhotdraw.draw.print.DrawingPageable.printPage().
getPageFormat()
PageFormat org.jhotdraw.draw.print.DrawingPageable.getPageFormat (int pageIndex) throws IndexOutOfBoundsException
getPrintable()
Printable org.jhotdraw.draw.print.DrawingPageable.getPrintable (int pageIndex) throws IndexOutOfBoundsException
References org.jhotdraw.draw.print.DrawingPageable.getNumberOfPages(), and org.jhotdraw.draw.print.DrawingPageable.printPage().
printPage()
int org.jhotdraw.draw.print.DrawingPageable.printPage (Graphics graphics, PageFormat pageFormat, int pageIndex) throws PrinterException
References org.jhotdraw.draw.figure.Figure.draw(), org.jhotdraw.draw.figure.CompositeFigure.getChildCount(), org.jhotdraw.draw.figure.CompositeFigure.getChildren(), org.jhotdraw.draw.print.DrawingPageable.getNumberOfPages(), org.jhotdraw.draw.AttributeKeys.getScaleFactorFromGraphics(), and org.jhotdraw.draw.print.DrawingPageable.setRenderingHints().
Referenced by org.jhotdraw.draw.print.DrawingPageable.getPrintable().
setRenderingHints()
void org.jhotdraw.draw.print.DrawingPageable.setRenderingHints (Graphics2D g) protected
Referenced by org.jhotdraw.draw.print.DrawingPageable.printPage().
The documentation for this class was generated from the following file:
jhotdraw-core/src/main/java/org/jhotdraw/draw/print/DrawingPageable.java