jhotdraw: org.jhotdraw.draw.tool.BezierTool Class Reference
org.jhotdraw.draw.tool.BezierTool Class Reference
Public Member Functions
BezierTool (BezierFigure prototype)
BezierTool (BezierFigure prototype, boolean calculateFittedCurveAfterCreation)
BezierTool (BezierFigure prototype, Map< AttributeKey<?>, Object > attributes)
BezierTool (BezierFigure prototype, Map< AttributeKey<?>, Object > attributes, String name)
BezierTool (BezierFigure prototype, Map< AttributeKey<?>, Object > attributes, String name, boolean calculateFittedCurveAfterCreation)
String getPresentationName ()
void activate (DrawingEditor editor)
void deactivate (DrawingEditor editor)
void mousePressed (MouseEvent evt)
void mouseClicked (MouseEvent evt)
void mouseReleased (MouseEvent evt)
void mouseDragged (MouseEvent evt)
void draw (Graphics2D g)
void mouseMoved (MouseEvent evt)
void setToolDoneAfterCreation (boolean b)
boolean isToolDoneAfterCreation ()
Public Member Functions inherited from org.jhotdraw.draw.tool.AbstractTool
AbstractTool ()
void addUndoableEditListener (UndoableEditListener l)
void removeUndoableEditListener (UndoableEditListener l)
boolean isActive ()
void setInputMap (InputMap newValue)
InputMap getInputMap ()
void setActionMap (ActionMap newValue)
ActionMap getActionMap ()
void editDelete ()
void editCut ()
void editCopy ()
void editDuplicate ()
void editPaste ()
void keyReleased (KeyEvent evt)
void keyTyped (KeyEvent evt)
void keyPressed (KeyEvent evt)
void mouseEntered (MouseEvent evt)
void mouseExited (MouseEvent evt)
void addToolListener (ToolListener l)
void removeToolListener (ToolListener l)
void updateCursor (DrawingView view, Point p)
String getToolTipText (DrawingView view, MouseEvent evt)
boolean supportsHandleInteraction ()
Protected Member Functions
BezierFigure createFigure ()
Figure getCreatedFigure ()
Figure getAddedFigure ()
void addPointToFigure (Point2D.Double newPoint)
void fireUndoEvent (Figure createdFigure, DrawingView creationView)
void finishCreation (BezierFigure createdFigure, DrawingView creationView)
BezierPath calculateFittedCurve (BezierPath path)
Protected Member Functions inherited from org.jhotdraw.draw.tool.AbstractTool
DrawingView getView ()
DrawingEditor getEditor ()
Drawing getDrawing ()
Point2D.Double viewToDrawing (Point p)
Point2D.Double constrainPoint (Point p, Figure... figure)
Point2D.Double constrainPoint (Point2D.Double p, Figure... figure)
InputMap createInputMap ()
ActionMap createActionMap ()
void fireToolStarted (DrawingView view)
void fireToolDone ()
void fireAreaInvalidated (Rectangle2D.Double r)
void fireAreaInvalidated (Rectangle invalidatedArea)
void maybeFireBoundsInvalidated (Rectangle invalidatedArea)
void fireBoundsInvalidated (Rectangle invalidatedArea)
Protected Attributes
Map< AttributeKey<?>, Object > attributes
BezierFigure createdFigure
Protected Attributes inherited from org.jhotdraw.draw.tool.AbstractTool
boolean isWorking
DrawingEditor editor
Point anchor = new Point()
EventListenerList listenerList = new EventListenerList()
Detailed Description
A Tool which allows to create a new BezierFigure by drawing its path.
To creation of the BezierFigure can be finished by adding a segment which closes the path, or by double clicking on the drawing area, or by selecting a different tool in the DrawingEditor.
Author
Werner Randelshofer
Version
$Id$
Constructor & Destructor Documentation
BezierTool() [1/5]
org.jhotdraw.draw.tool.BezierTool.BezierTool (BezierFigure prototype)
Creates a new instance.
BezierTool() [2/5]
org.jhotdraw.draw.tool.BezierTool.BezierTool (BezierFigure prototype, boolean calculateFittedCurveAfterCreation)
BezierTool() [3/5]
org.jhotdraw.draw.tool.BezierTool.BezierTool (BezierFigure prototype, Map< AttributeKey<?>, Object > attributes)
Creates a new instance.
References org.jhotdraw.draw.tool.BezierTool.attributes.
BezierTool() [4/5]
org.jhotdraw.draw.tool.BezierTool.BezierTool (BezierFigure prototype, Map< AttributeKey<?>, Object > attributes, String name)
References org.jhotdraw.draw.tool.BezierTool.attributes.
BezierTool() [5/5]
org.jhotdraw.draw.tool.BezierTool.BezierTool (BezierFigure prototype, Map< AttributeKey<?>, Object > attributes, String name, boolean calculateFittedCurveAfterCreation)
References org.jhotdraw.draw.tool.BezierTool.attributes.
Member Function Documentation
activate()
void org.jhotdraw.draw.tool.BezierTool.activate (DrawingEditor editor)
Activates the tool for the given editor. This method is called whenever the user switches to this tool.
Reimplemented from org.jhotdraw.draw.tool.AbstractTool.
References org.jhotdraw.draw.tool.AbstractTool.editor, org.jhotdraw.draw.tool.AbstractTool.getView(), and org.jhotdraw.draw.DrawingView.setCursor().
addPointToFigure()
void org.jhotdraw.draw.tool.BezierTool.addPointToFigure (Point2D.Double newPoint) protected
References org.jhotdraw.draw.figure.BezierFigure.addNode(), org.jhotdraw.draw.figure.AbstractFigure.changed(), org.jhotdraw.draw.tool.BezierTool.createdFigure, org.jhotdraw.draw.figure.BezierFigure.getEndPoint(), org.jhotdraw.draw.figure.BezierFigure.getNodeCount(), org.jhotdraw.draw.figure.BezierFigure.getPoint(), org.jhotdraw.draw.tool.AbstractTool.getView(), org.jhotdraw.draw.figure.BezierFigure.setPoint(), and org.jhotdraw.draw.figure.AbstractFigure.willChange().
Referenced by org.jhotdraw.draw.tool.BezierTool.mouseDragged(), and org.jhotdraw.draw.tool.BezierTool.mousePressed().
calculateFittedCurve()
BezierPath org.jhotdraw.draw.tool.BezierTool.calculateFittedCurve (BezierPath path) protected
References org.jhotdraw.draw.tool.AbstractTool.getView().
Referenced by org.jhotdraw.draw.tool.BezierTool.mouseReleased().
createFigure()
BezierFigure org.jhotdraw.draw.tool.BezierTool.createFigure () protected
References org.jhotdraw.draw.DrawingEditor.applyDefaultAttributesTo(), org.jhotdraw.draw.tool.BezierTool.attributes, org.jhotdraw.draw.figure.BezierFigure.clone(), and org.jhotdraw.draw.tool.AbstractTool.getEditor().
Referenced by org.jhotdraw.draw.tool.BezierTool.mousePressed().
deactivate()
void org.jhotdraw.draw.tool.BezierTool.deactivate (DrawingEditor editor)
Deactivates the tool. This method is called whenever the user switches to another tool.
Reimplemented from org.jhotdraw.draw.tool.AbstractTool.
References org.jhotdraw.draw.tool.AbstractTool.anchor, org.jhotdraw.draw.tool.BezierTool.createdFigure, org.jhotdraw.draw.tool.AbstractTool.editor, org.jhotdraw.draw.tool.BezierTool.finishCreation(), org.jhotdraw.draw.tool.AbstractTool.fireAreaInvalidated(), org.jhotdraw.draw.figure.BezierFigure.getNodeCount(), org.jhotdraw.draw.figure.BezierFigure.getStartPoint(), org.jhotdraw.draw.tool.AbstractTool.getView(), org.jhotdraw.draw.figure.BezierFigure.isClosed(), and org.jhotdraw.draw.DrawingView.setCursor().
draw()
void org.jhotdraw.draw.tool.BezierTool.draw (Graphics2D g)
Draws the tool.
Reimplemented from org.jhotdraw.draw.tool.AbstractTool.
References org.jhotdraw.draw.tool.AbstractTool.anchor, org.jhotdraw.draw.tool.BezierTool.createdFigure, org.jhotdraw.draw.DrawingView.drawingToView(), org.jhotdraw.draw.figure.BezierFigure.getNodeCount(), org.jhotdraw.draw.figure.BezierFigure.getStartPoint(), org.jhotdraw.draw.tool.AbstractTool.getView(), org.jhotdraw.draw.figure.BezierFigure.isClosed(), and org.jhotdraw.draw.tool.AbstractTool.isWorking.
finishCreation()
void org.jhotdraw.draw.tool.BezierTool.finishCreation (BezierFigure createdFigure, DrawingView creationView) protected
References org.jhotdraw.draw.DrawingView.addToSelection(), org.jhotdraw.draw.tool.BezierTool.createdFigure, org.jhotdraw.draw.tool.AbstractTool.fireToolDone(), and org.jhotdraw.draw.tool.BezierTool.fireUndoEvent().
Referenced by org.jhotdraw.draw.tool.BezierTool.deactivate(), org.jhotdraw.draw.tool.BezierTool.mouseClicked(), org.jhotdraw.draw.tool.BezierTool.mousePressed(), and org.jhotdraw.draw.tool.BezierTool.mouseReleased().
fireUndoEvent()
void org.jhotdraw.draw.tool.BezierTool.fireUndoEvent (Figure createdFigure, DrawingView creationView) protected
References org.jhotdraw.draw.Drawing.add(), org.jhotdraw.draw.DrawingView.addToSelection(), org.jhotdraw.draw.DrawingView.clearSelection(), org.jhotdraw.draw.tool.BezierTool.createdFigure, org.jhotdraw.draw.Drawing.fireUndoableEditHappened(), org.jhotdraw.draw.DrawingView.getDrawing(), org.jhotdraw.draw.tool.AbstractTool.getDrawing(), org.jhotdraw.draw.tool.BezierTool.getPresentationName(), and org.jhotdraw.draw.Drawing.remove().
Referenced by org.jhotdraw.draw.tool.BezierTool.finishCreation().
getAddedFigure()
Figure org.jhotdraw.draw.tool.BezierTool.getAddedFigure () protected
References org.jhotdraw.draw.tool.BezierTool.createdFigure.
getCreatedFigure()
Figure org.jhotdraw.draw.tool.BezierTool.getCreatedFigure () protected
References org.jhotdraw.draw.tool.BezierTool.createdFigure.
getPresentationName()
String org.jhotdraw.draw.tool.BezierTool.getPresentationName ()
Referenced by org.jhotdraw.draw.tool.BezierTool.fireUndoEvent().
isToolDoneAfterCreation()
boolean org.jhotdraw.draw.tool.BezierTool.isToolDoneAfterCreation ()
mouseClicked()
void org.jhotdraw.draw.tool.BezierTool.mouseClicked (MouseEvent evt)
Reimplemented from org.jhotdraw.draw.tool.AbstractTool.
References org.jhotdraw.draw.tool.BezierTool.createdFigure, org.jhotdraw.draw.tool.BezierTool.finishCreation(), org.jhotdraw.draw.tool.AbstractTool.fireToolDone(), org.jhotdraw.draw.figure.BezierFigure.getNodeCount(), org.jhotdraw.draw.figure.BezierFigure.getStartPoint(), org.jhotdraw.draw.tool.AbstractTool.getView(), and org.jhotdraw.draw.figure.BezierFigure.setClosed().
mouseDragged()
void org.jhotdraw.draw.tool.BezierTool.mouseDragged (MouseEvent evt)
References org.jhotdraw.draw.tool.BezierTool.addPointToFigure(), org.jhotdraw.draw.tool.AbstractTool.getView(), and org.jhotdraw.draw.tool.AbstractTool.viewToDrawing().
mouseMoved()
void org.jhotdraw.draw.tool.BezierTool.mouseMoved (MouseEvent evt)
Reimplemented from org.jhotdraw.draw.tool.AbstractTool.
References org.jhotdraw.draw.tool.AbstractTool.anchor, org.jhotdraw.draw.tool.BezierTool.createdFigure, org.jhotdraw.draw.DrawingView.drawingToView(), org.jhotdraw.draw.tool.AbstractTool.fireAreaInvalidated(), org.jhotdraw.draw.DrawingView.getComponent(), org.jhotdraw.draw.figure.BezierFigure.getNodeCount(), org.jhotdraw.draw.figure.BezierFigure.getStartPoint(), and org.jhotdraw.draw.figure.BezierFigure.isClosed().
mousePressed()
void org.jhotdraw.draw.tool.BezierTool.mousePressed (MouseEvent evt)
Reimplemented from org.jhotdraw.draw.tool.AbstractTool.
References org.jhotdraw.draw.Drawing.add(), org.jhotdraw.draw.figure.BezierFigure.addNode(), org.jhotdraw.draw.tool.BezierTool.addPointToFigure(), org.jhotdraw.draw.tool.AbstractTool.anchor, org.jhotdraw.draw.DrawingView.clearSelection(), org.jhotdraw.draw.Constrainer.constrainPoint(), org.jhotdraw.draw.tool.BezierTool.createdFigure, org.jhotdraw.draw.tool.BezierTool.createFigure(), org.jhotdraw.draw.tool.BezierTool.finishCreation(), org.jhotdraw.draw.tool.AbstractTool.fireAreaInvalidated(), org.jhotdraw.draw.DrawingView.getConstrainer(), org.jhotdraw.draw.tool.AbstractTool.getDrawing(), org.jhotdraw.draw.figure.BezierFigure.getNodeCount(), org.jhotdraw.draw.tool.AbstractTool.getView(), and org.jhotdraw.draw.DrawingView.viewToDrawing().
mouseReleased()
void org.jhotdraw.draw.tool.BezierTool.mouseReleased (MouseEvent evt)
Reimplemented from org.jhotdraw.draw.tool.AbstractTool.
References org.jhotdraw.draw.tool.AbstractTool.anchor, org.jhotdraw.draw.tool.BezierTool.calculateFittedCurve(), org.jhotdraw.draw.figure.AbstractFigure.changed(), org.jhotdraw.draw.tool.BezierTool.createdFigure, org.jhotdraw.draw.tool.BezierTool.finishCreation(), org.jhotdraw.draw.tool.AbstractTool.fireAreaInvalidated(), org.jhotdraw.draw.figure.BezierFigure.getBezierPath(), org.jhotdraw.draw.figure.BezierFigure.getNodeCount(), org.jhotdraw.draw.tool.AbstractTool.isWorking, org.jhotdraw.draw.tool.AbstractTool.maybeFireBoundsInvalidated(), org.jhotdraw.draw.figure.BezierFigure.setBezierPath(), and org.jhotdraw.draw.figure.AbstractFigure.willChange().
setToolDoneAfterCreation()
void org.jhotdraw.draw.tool.BezierTool.setToolDoneAfterCreation (boolean b)
Member Data Documentation
attributes
Map<AttributeKey<?>, Object> org.jhotdraw.draw.tool.BezierTool.attributes protected
Referenced by org.jhotdraw.draw.tool.BezierTool.BezierTool(), and org.jhotdraw.draw.tool.BezierTool.createFigure().
createdFigure
BezierFigure org.jhotdraw.draw.tool.BezierTool.createdFigure protected
The created figure.
Referenced by org.jhotdraw.draw.tool.BezierTool.addPointToFigure(), org.jhotdraw.draw.tool.BezierTool.deactivate(), org.jhotdraw.draw.tool.BezierTool.draw(), org.jhotdraw.draw.tool.BezierTool.finishCreation(), org.jhotdraw.draw.tool.BezierTool.fireUndoEvent(), org.jhotdraw.draw.tool.BezierTool.getAddedFigure(), org.jhotdraw.draw.tool.BezierTool.getCreatedFigure(), org.jhotdraw.draw.tool.BezierTool.mouseClicked(), org.jhotdraw.draw.tool.BezierTool.mouseMoved(), org.jhotdraw.draw.tool.BezierTool.mousePressed(), and org.jhotdraw.draw.tool.BezierTool.mouseReleased().
The documentation for this class was generated from the following file:
jhotdraw-core/src/main/java/org/jhotdraw/draw/tool/BezierTool.java