jhotdraw: org.jhotdraw.draw.figure.LabeledLineConnectionFigure Class Reference
org.jhotdraw.draw.figure.LabeledLineConnectionFigure Class Reference
Public Member Functions
LabeledLineConnectionFigure ()
void draw (Graphics2D g)
void transform (AffineTransform tx)
Rectangle2D.Double getDrawingArea ()
boolean contains (Point2D.Double p)
Figure findFigureInside (Point2D.Double p)
void updateConnection ()
java.util.List< Figure > getChildren ()
int getChildCount ()
Figure getChild (int index)
java.util.List< Figure > getChildrenFrontToBack ()
boolean add (Figure figure)
void add (int index, Figure figure)
void basicAdd (Figure figure)
void basicAdd (int index, Figure figure)
boolean remove (final Figure figure)
Figure removeChild (int index)
int basicRemove (final Figure figure)
Figure basicRemoveChild (int index)
void removeAllChildren ()
void basicRemoveAllChildren ()
Layouter getLayouter ()
void setLayouter (Layouter newLayouter)
void layout ()
void invalidate ()
void validate ()
void addNotify (Drawing drawing)
void removeNotify (Drawing drawing)
void removeCompositeFigureListener (CompositeFigureListener listener)
void addCompositeFigureListener (CompositeFigureListener listener)
LabeledLineConnectionFigure clone ()
void remap (Map< Figure, Figure > oldToNew, boolean disconnectIfNotInMap)
boolean contains (Figure f)
int indexOf (Figure child)
Public Member Functions inherited from org.jhotdraw.draw.figure.LineConnectionFigure
LineConnectionFigure ()
Collection< Handle > createHandles (int detailLevel)
void setConnectable (boolean newValue)
boolean canConnect (Connector start, Connector end)
Connector getEndConnector ()
Figure getEndFigure ()
Connector getStartConnector ()
Figure getStartFigure ()
void setEndConnector (Connector newEnd)
void setStartConnector (Connector newStart)
boolean canConnect (Connector start)
boolean handleMouseClick (Point2D.Double p, MouseEvent evt, DrawingView view)
void read (DOMInput in) throws IOException
void write (DOMOutput out) throws IOException
void setLiner (Liner newValue)
void setNode (int index, BezierPath.Node p)
void lineout ()
BezierPath getBezierPath ()
Liner getLiner ()
void setStartPoint (Point2D.Double p)
void setPoint (int index, Point2D.Double p)
void setEndPoint (Point2D.Double p)
void reverseConnection ()
Public Member Functions inherited from org.jhotdraw.draw.figure.LineFigure
LineFigure ()
Public Member Functions inherited from org.jhotdraw.draw.figure.BezierFigure
BezierFigure ()
BezierFigure (boolean isClosed)
Connector findConnector (Point2D.Double p, ConnectionFigure prototype)
Connector findCompatibleConnector (Connector c, boolean isStart)
Rectangle2D.Double getBounds ()
Rectangle2D.Double getDrawingArea (double factor)
void setBezierPath (BezierPath newValue)
Point2D.Double getPointOnPath (float relative, double flatness)
boolean isClosed ()
void setClosed (boolean newValue)
void setBounds (Point2D.Double anchor, Point2D.Double lead)
void addNode (BezierPath.Node p)
void addNode (final int index, BezierPath.Node p)
BezierPath.Node getNode (int index)
Point2D.Double getPoint (int index)
Point2D.Double getPoint (int index, int coord)
void setPoint (int index, int coord, Point2D.Double p)
Point2D.Double getStartPoint ()
Point2D.Double getEndPoint ()
int findNode (Point2D.Double p)
int findSegment (Point2D.Double find, double tolerance)
boolean joinSegments (Point2D.Double join, double tolerance)
int splitSegment (Point2D.Double split, double tolerance)
BezierPath.Node removeNode (int index)
int getNodeCount ()
void restoreTransformTo (Object geometry)
Object getTransformRestoreData ()
Point2D.Double chop (Point2D.Double p)
Point2D.Double getCenter ()
Point2D.Double getOutermostPoint ()
int joinSegments (Point2D.Double join, float tolerance)
int splitSegment (Point2D.Double split, float tolerance)
Public Member Functions inherited from org.jhotdraw.draw.figure.AbstractAttributedFigure
AbstractAttributedFigure ()
void setAttributeEnabled (AttributeKey<?> key, boolean b)
boolean isAttributeEnabled (AttributeKey<?> key)
void setAttributes (Map< AttributeKey<?>, Object > map)
Map< AttributeKey<?>, Object > getAttributes ()
Object getAttributesRestoreData ()
void restoreAttributesTo (Object restoreData)
double getStrokeMiterLimitFactor ()
boolean hasAttribute (AttributeKey<?> key)
Public Member Functions inherited from org.jhotdraw.draw.figure.AbstractFigure
AbstractFigure ()
void addFigureListener (FigureListener l)
void removeFigureListener (FigureListener l)
void fireAreaInvalidated ()
void fireFigureChanged ()
Cursor getCursor (Point2D.Double p)
final void setBounds (Rectangle2D.Double bounds)
void willChange ()
void changed ()
boolean includes (Figure figure)
Collection< Action > getActions (Point2D.Double p)
Tool getTool (Point2D.Double p)
boolean handleDrop (Point2D.Double p, Collection< Figure > droppedFigures, DrawingView view)
Dimension2DDouble getPreferredSize ()
boolean isConnectable ()
boolean isSelectable ()
void setSelectable (boolean newValue)
boolean isRemovable ()
void setRemovable (boolean newValue)
boolean isTransformable ()
void setTransformable (boolean newValue)
boolean isVisible ()
void setVisible (boolean newValue)
Collection< Figure > getDecomposition ()
void requestRemove ()
int getLayer ()
String getToolTipText (Point2D.Double p)
String toString ()
Collection< Connector > getConnectors (ConnectionFigure prototype)
Public Member Functions inherited from org.jhotdraw.draw.figure.Figure
void addPropertyChangeListener (PropertyChangeListener listener)
void removePropertyChangeListener (PropertyChangeListener listener)
Public Member Functions inherited from org.jhotdraw.draw.figure.ConnectionFigure
int getNodeCount ()
Point2D.Double getPoint (int index)
BezierPath.Node getNode (int index)
Point2D.Double getStartPoint ()
Point2D.Double getEndPoint ()
Protected Member Functions
void fireFigureAdded (Figure f, int zIndex)
void fireFigureRemoved (Figure f, int zIndex)
Protected Member Functions inherited from org.jhotdraw.draw.figure.LineConnectionFigure
void handleDisconnect (Connector start, Connector end)
void handleConnect (Connector start, Connector end)
void readPoints (DOMInput in) throws IOException
void readLiner (DOMInput in) throws IOException
void writeLiner (DOMOutput out) throws IOException
void writePoints (DOMOutput out) throws IOException
Protected Member Functions inherited from org.jhotdraw.draw.figure.BezierFigure
void drawStroke (Graphics2D g)
void drawCaps (Graphics2D g)
void drawFill (Graphics2D g)
BezierPath getCappedPath ()
void removeAllNodes ()
Protected Member Functions inherited from org.jhotdraw.draw.figure.AbstractAttributedFigure
abstract void drawFill (java.awt.Graphics2D g)
abstract void drawStroke (java.awt.Graphics2D g)
void drawText (java.awt.Graphics2D g)
void writeAttributes (DOMOutput out) throws IOException
void readAttributes (DOMInput in) throws IOException
AttributeKey<?> getAttributeKey (String name)
void applyAttributesTo (Figure that)
Protected Member Functions inherited from org.jhotdraw.draw.figure.AbstractFigure
Drawing getDrawing ()
Object getLock ()
void fireAreaInvalidated (Rectangle2D.Double invalidatedArea)
void fireAreaInvalidated (FigureEvent event)
void fireFigureRequestRemove ()
void fireFigureAdded ()
void fireFigureRemoved ()
void fireFigureChanged (Rectangle2D.Double changedArea)
void fireFigureChanged (FigureEvent event)
void fireFigureHandlesChanged ()
void fireUndoableEditHappened (UndoableEdit edit)
boolean isChanging ()
int getChangingDepth ()
FontRenderContext getFontRenderContext ()
Additional Inherited Members
Static Public Attributes inherited from org.jhotdraw.draw.figure.LineConnectionFigure
static final String LINER_PROPERTY = "liner"
Static Public Attributes inherited from org.jhotdraw.draw.figure.Figure
static final String CONNECTABLE_PROPERTY = "connectable"
static final String REMOVABLE_PROPERTY = "removable"
static final String SELECTABLE_PROPERTY = "selectable"
static final String TRANSFORMABLE_PROPERTY = "transformable"
Static Public Attributes inherited from org.jhotdraw.draw.figure.CompositeFigure
static final AttributeKey< Insets2D.Double > LAYOUT_INSETS = new AttributeKey<Insets2D.Double>("layoutInsets", Insets2D.Double.class, new Insets2D.Double())
Protected Attributes inherited from org.jhotdraw.draw.figure.BezierFigure
BezierPath path
Protected Attributes inherited from org.jhotdraw.draw.figure.AbstractFigure
EventListenerList listenerList = new EventListenerList()
int changingDepth = 0
Detailed Description
A LineConnection with labels.
Usage:
LineConnectionFigure lcf = new LineConnectionFigure();
lcf.setLayouter(new LocatorLayouter());
TextFigure label = new TextFigure();
label.setText("Hello");
LocatorLayouter.LAYOUT_LOCATOR.set(label, new BezierLabelLocator(0, -Math.PI / 4, 8));
lcf.add(label);
Author
Werner Randelshofer
Version
$Id$
Constructor & Destructor Documentation
LabeledLineConnectionFigure()
org.jhotdraw.draw.figure.LabeledLineConnectionFigure.LabeledLineConnectionFigure ()
Creates a new instance.
Referenced by org.jhotdraw.draw.figure.LabeledLineConnectionFigure.clone().
Member Function Documentation
add() [1/2]
boolean org.jhotdraw.draw.figure.LabeledLineConnectionFigure.add (Figure child)
Adds a child to the figure.
This is a convenience method for
add(getChildCount(), child);
This method calls
figureAdded
on all registered
CompositeFigureListener
s.
Returns
true
if this CompositeFigure changed as a result of the call
Implements org.jhotdraw.draw.figure.CompositeFigure.
References org.jhotdraw.draw.figure.Figure.addNotify(), org.jhotdraw.draw.figure.LabeledLineConnectionFigure.basicAdd(), and org.jhotdraw.draw.figure.AbstractFigure.getDrawing().
add() [2/2]
void org.jhotdraw.draw.figure.LabeledLineConnectionFigure.add (int index, Figure child)
Adds a child to the figure at the specified index.
This method calls
figureAdded
on all registered
CompositeFigureListener
s.
Implements org.jhotdraw.draw.figure.CompositeFigure.
References org.jhotdraw.draw.figure.Figure.addNotify(), org.jhotdraw.draw.figure.LabeledLineConnectionFigure.basicAdd(), and org.jhotdraw.draw.figure.AbstractFigure.getDrawing().
addCompositeFigureListener()
void org.jhotdraw.draw.figure.LabeledLineConnectionFigure.addCompositeFigureListener (CompositeFigureListener listener)
Adds a listener for this composite figure.
Implements org.jhotdraw.draw.figure.CompositeFigure.
References org.jhotdraw.draw.figure.AbstractFigure.listenerList.
addNotify()
void org.jhotdraw.draw.figure.LabeledLineConnectionFigure.addNotify (Drawing drawing)
This method is invoked, when the Figure is being removed from a Drawing. This method invokes handleConnect, if the Figure is connected.
See also
handleConnect
Reimplemented from org.jhotdraw.draw.figure.LineConnectionFigure.
basicAdd() [1/2]
void org.jhotdraw.draw.figure.LabeledLineConnectionFigure.basicAdd (Figure child)
Adds a child to the figure without firing events.
This method can be used to reinsert a child figure which has been temporarily removed from this CompositeFigure (for example to reorder the sequence of the children) and to efficiently build a drawing from an org.jhotdraw.draw.io.InputFormat.
This is a convenience method for calling
basicAdd(getChildCount(), child);
.
Implements org.jhotdraw.draw.figure.CompositeFigure.
Referenced by org.jhotdraw.draw.figure.LabeledLineConnectionFigure.add().
basicAdd() [2/2]
void org.jhotdraw.draw.figure.LabeledLineConnectionFigure.basicAdd (int index, Figure child)
Adds a child to the figure at the specified index without firing events.
This method can be used to reinsert a child figure which has been temporarily removed from this CompositeFigure (for example to reorder the sequence of the children) and to efficiently build a drawing from an org.jhotdraw.draw.io.InputFormat.
Implements org.jhotdraw.draw.figure.CompositeFigure.
References org.jhotdraw.draw.figure.Figure.addFigureListener(), and org.jhotdraw.draw.figure.LabeledLineConnectionFigure.invalidate().
basicRemove()
int org.jhotdraw.draw.figure.LabeledLineConnectionFigure.basicRemove (final Figure child)
Removes the specified child without firing events.
This method can be used to temporarily remove a child from this CompositeFigure (for example to reorder the sequence of the children).
This is a convenience method for calling
basicRemove(indexOf(child));
.
Returns the index of the removed figure. Returns -1 if the figure was not a child of this CompositeFigure.
Implements org.jhotdraw.draw.figure.CompositeFigure.
References org.jhotdraw.draw.figure.LabeledLineConnectionFigure.basicRemoveChild().
basicRemoveAllChildren()
void org.jhotdraw.draw.figure.LabeledLineConnectionFigure.basicRemoveAllChildren ()
Removes all children from the composite figure without firing events.
This method can be used to temporarily remove a child from this CompositeFigure (for example to reorder the sequence of the children).
This is a convenience method for
while(getChildCount() > 0) basicRemoveChild(0);
Implements org.jhotdraw.draw.figure.CompositeFigure.
References org.jhotdraw.draw.figure.LabeledLineConnectionFigure.basicRemoveChild().
basicRemoveChild()
Figure org.jhotdraw.draw.figure.LabeledLineConnectionFigure.basicRemoveChild (int index)
Removes the child at the specified index without firing events.
This method can be used to temporarily remove a child from this CompositeFigure (for example to reorder the sequence of the children).
Returns the removed child figure.
Implements org.jhotdraw.draw.figure.CompositeFigure.
References org.jhotdraw.draw.figure.Figure.removeFigureListener().
Referenced by org.jhotdraw.draw.figure.LabeledLineConnectionFigure.basicRemove(), org.jhotdraw.draw.figure.LabeledLineConnectionFigure.basicRemoveAllChildren(), org.jhotdraw.draw.figure.LabeledLineConnectionFigure.remove(), org.jhotdraw.draw.figure.LabeledLineConnectionFigure.removeAllChildren(), and org.jhotdraw.draw.figure.LabeledLineConnectionFigure.removeChild().
clone()
LabeledLineConnectionFigure org.jhotdraw.draw.figure.LabeledLineConnectionFigure.clone ()
Returns a clone of the figure, with clones of all aggregated figures, such as children and decorators. The cloned figure does not clone the list of FigureListeners from its original.
Reimplemented from org.jhotdraw.draw.figure.LineConnectionFigure.
References org.jhotdraw.draw.figure.Figure.addFigureListener(), org.jhotdraw.draw.figure.Figure.clone(), org.jhotdraw.draw.figure.LabeledLineConnectionFigure.clone(), and org.jhotdraw.draw.figure.LabeledLineConnectionFigure.LabeledLineConnectionFigure().
Referenced by org.jhotdraw.draw.figure.LabeledLineConnectionFigure.clone().
contains() [1/2]
boolean org.jhotdraw.draw.figure.LabeledLineConnectionFigure.contains (Figure f)
Returns true if this composite figure contains the specified figure.
This is a convenience method for calling
getChildren().contains(f);
.
Implements org.jhotdraw.draw.figure.CompositeFigure.
contains() [2/2]
boolean org.jhotdraw.draw.figure.LabeledLineConnectionFigure.contains (Point2D.Double p)
Checks if a point is contained by the figure.
This is used for hit testing by Tool's.
Implements org.jhotdraw.draw.figure.Figure.
References org.jhotdraw.draw.figure.LabeledLineConnectionFigure.getChildrenFrontToBack(), and org.jhotdraw.draw.figure.LabeledLineConnectionFigure.getDrawingArea().
Referenced by org.jhotdraw.draw.figure.LabeledLineConnectionFigure.findFigureInside().
draw()
void org.jhotdraw.draw.figure.LabeledLineConnectionFigure.draw (Graphics2D g)
Draw the figure. This method is delegated to the encapsulated presentation figure.
Implements org.jhotdraw.draw.figure.Figure.
findFigureInside()
Figure org.jhotdraw.draw.figure.LabeledLineConnectionFigure.findFigureInside (Point2D.Double p)
Finds the innermost figure at the specified location.
In case of a
CompositeFigure
, this method descends into its children and into its children's children until the innermost figure is found.
This functionality is implemented using the Chain of Responsibility design pattern. A figure which is not composed of other figures returns itself if the point is contained by the figure. Composed figures pass the method call down to their children.
Parameters
p A location on the drawing.
Returns
Returns the innermost figure at the location, or null if the location is not contained in a figure.
Implements org.jhotdraw.draw.figure.Figure.
References org.jhotdraw.draw.figure.LabeledLineConnectionFigure.contains(), org.jhotdraw.draw.figure.Figure.findFigureInside(), org.jhotdraw.draw.figure.LabeledLineConnectionFigure.getChildrenFrontToBack(), and org.jhotdraw.draw.figure.LabeledLineConnectionFigure.getDrawingArea().
fireFigureAdded()
void org.jhotdraw.draw.figure.LabeledLineConnectionFigure.fireFigureAdded (Figure f, int zIndex) protected
Notify all listenerList that have registered interest for notification on this event type.
References org.jhotdraw.draw.figure.Figure.getDrawingArea(), and org.jhotdraw.draw.figure.AbstractFigure.listenerList.
fireFigureRemoved()
void org.jhotdraw.draw.figure.LabeledLineConnectionFigure.fireFigureRemoved (Figure f, int zIndex) protected
Notify all listenerList that have registered interest for notification on this event type.
References org.jhotdraw.draw.figure.Figure.getDrawingArea(), and org.jhotdraw.draw.figure.AbstractFigure.listenerList.
getChild()
Figure org.jhotdraw.draw.figure.LabeledLineConnectionFigure.getChild (int index)
Returns the child figure at the specified index.
This is a convenience method for calling
getChildren().get(index);
.
Implements org.jhotdraw.draw.figure.CompositeFigure.
References org.jhotdraw.draw.figure.Figure.get().
getChildCount()
int org.jhotdraw.draw.figure.LabeledLineConnectionFigure.getChildCount ()
Returns the number of children.
This is a convenience method for calling
getChildren().size();
.
Implements org.jhotdraw.draw.figure.CompositeFigure.
getChildren()
java.util.List<Figure> org.jhotdraw.draw.figure.LabeledLineConnectionFigure.getChildren ()
Returns an unchangeable list view on the children.
Implements org.jhotdraw.draw.figure.CompositeFigure.
getChildrenFrontToBack()
java.util.List<Figure> org.jhotdraw.draw.figure.LabeledLineConnectionFigure.getChildrenFrontToBack ()
Returns an iterator to iterate in Z-order front to back over the children.
Referenced by org.jhotdraw.draw.figure.LabeledLineConnectionFigure.contains(), org.jhotdraw.draw.figure.LabeledLineConnectionFigure.findFigureInside(), and org.jhotdraw.draw.figure.LabeledLineConnectionFigure.getDrawingArea().
getDrawingArea()
Rectangle2D.Double org.jhotdraw.draw.figure.LabeledLineConnectionFigure.getDrawingArea ()
Returns the drawing area of the figure as a Rectangle.
The drawing area is used to inform DrawingView about the area that is needed to draw this figure.
The drawing area needs to be large enough, to take line width, line caps and other decorations into account that exceed the bounds of the Figure.
Implements org.jhotdraw.draw.figure.Figure.
References org.jhotdraw.draw.figure.LabeledLineConnectionFigure.getChildrenFrontToBack().
Referenced by org.jhotdraw.draw.figure.LabeledLineConnectionFigure.contains(), and org.jhotdraw.draw.figure.LabeledLineConnectionFigure.findFigureInside().
getLayouter()
Layouter org.jhotdraw.draw.figure.LabeledLineConnectionFigure.getLayouter ()
Get a Layouter object which encapsulated a layout algorithm for this figure. Typically, a Layouter accesses the child components of this figure and arranges their graphical presentation.
Returns
layout strategy used by this figure
Implements org.jhotdraw.draw.figure.CompositeFigure.
Referenced by org.jhotdraw.draw.figure.LabeledLineConnectionFigure.layout().
indexOf()
int org.jhotdraw.draw.figure.LabeledLineConnectionFigure.indexOf (Figure child)
Returns the index of the specified child.
This is a convenience method for calling
getChildren().indexOf(index);
.
Returns
The index of the child, or -1 if the specified figure is not a child of this CompositeFigure.
Implements org.jhotdraw.draw.figure.CompositeFigure.
invalidate()
void org.jhotdraw.draw.figure.LabeledLineConnectionFigure.invalidate ()
Invalidates cached data of the Figure. This method must execute fast, because it can be called very often.
Reimplemented from org.jhotdraw.draw.figure.BezierFigure.
Referenced by org.jhotdraw.draw.figure.LabeledLineConnectionFigure.basicAdd(), org.jhotdraw.draw.figure.LabeledLineConnectionFigure.layout(), and org.jhotdraw.draw.figure.LabeledLineConnectionFigure.transform().
layout()
void org.jhotdraw.draw.figure.LabeledLineConnectionFigure.layout ()
A layout algorithm is used to define how the child components should be laid out in relation to each other. The task for layouting the child components for presentation is delegated to a Layouter which can be plugged in at runtime.
Implements org.jhotdraw.draw.figure.CompositeFigure.
References org.jhotdraw.draw.figure.Figure.getBounds(), org.jhotdraw.draw.figure.LabeledLineConnectionFigure.getLayouter(), org.jhotdraw.draw.figure.LabeledLineConnectionFigure.invalidate(), and org.jhotdraw.draw.layouter.Layouter.layout().
Referenced by org.jhotdraw.draw.figure.LabeledLineConnectionFigure.updateConnection(), and org.jhotdraw.draw.figure.LabeledLineConnectionFigure.validate().
remap()
void org.jhotdraw.draw.figure.LabeledLineConnectionFigure.remap (Map< Figure, Figure > oldToNew, boolean disconnectIfNotInMap)
After cloning a collection of figures, the ConnectionFigures contained in this collection still connect to the original figures instead of to the clones. Using This operation and providing a map, which maps from the original collection of figures to the new collection, connections can be remapped to the new figures.
Reimplemented from org.jhotdraw.draw.figure.LineConnectionFigure.
remove()
boolean org.jhotdraw.draw.figure.LabeledLineConnectionFigure.remove (final Figure child)
Removes the specified child. Returns true, if the Figure contained the removed child.
This is a convenience method for calling
removeChild(getChildren().indexOf(child));
This method calls
figureRemoved
on all registered
CompositeFigureListener
's.
Implements org.jhotdraw.draw.figure.CompositeFigure.
References org.jhotdraw.draw.figure.LabeledLineConnectionFigure.basicRemoveChild(), org.jhotdraw.draw.figure.Figure.changed(), org.jhotdraw.draw.figure.AbstractFigure.getDrawing(), and org.jhotdraw.draw.figure.Figure.willChange().
removeAllChildren()
void org.jhotdraw.draw.figure.LabeledLineConnectionFigure.removeAllChildren ()
Removes all children from the composite figure.
This is a convenience method for
while(getChildCount() > 0) removeChild(0);
Implements org.jhotdraw.draw.figure.CompositeFigure.
References org.jhotdraw.draw.figure.LabeledLineConnectionFigure.basicRemoveChild(), org.jhotdraw.draw.figure.Figure.changed(), org.jhotdraw.draw.figure.AbstractFigure.getDrawing(), org.jhotdraw.draw.figure.Figure.removeNotify(), and org.jhotdraw.draw.figure.Figure.willChange().
removeChild()
Figure org.jhotdraw.draw.figure.LabeledLineConnectionFigure.removeChild (int index)
Removes the child at the specified index. Returns the removed child figure.
Calls
figureRemoved
on all registered
CompositeFigureListener
's.
Implements org.jhotdraw.draw.figure.CompositeFigure.
References org.jhotdraw.draw.figure.LabeledLineConnectionFigure.basicRemoveChild(), org.jhotdraw.draw.figure.Figure.changed(), org.jhotdraw.draw.figure.AbstractFigure.getDrawing(), org.jhotdraw.draw.figure.Figure.removeNotify(), and org.jhotdraw.draw.figure.Figure.willChange().
removeCompositeFigureListener()
void org.jhotdraw.draw.figure.LabeledLineConnectionFigure.removeCompositeFigureListener (CompositeFigureListener listener)
Removes a listener from this composite figure.
Implements org.jhotdraw.draw.figure.CompositeFigure.
References org.jhotdraw.draw.figure.AbstractFigure.listenerList.
removeNotify()
void org.jhotdraw.draw.figure.LabeledLineConnectionFigure.removeNotify (Drawing drawing)
This method is invoked, when the Figure is being removed from a Drawing. This method invokes handleDisconnect, if the Figure is connected.
See also
handleDisconnect
Reimplemented from org.jhotdraw.draw.figure.LineConnectionFigure.
setLayouter()
void org.jhotdraw.draw.figure.LabeledLineConnectionFigure.setLayouter (Layouter newValue)
Set a Layouter object which encapsulated a layout algorithm for this figure. Typically, a Layouter accesses the child components of this figure and arranges their graphical presentation. It is a good idea to put the Layouter in the protected initialize() method so it can be recreated if a GraphicalCompositeFigure is read and restored from a StorableInput stream.
Parameters
newValue encapsulation of a layout algorithm.
Implements org.jhotdraw.draw.figure.CompositeFigure.
transform()
void org.jhotdraw.draw.figure.LabeledLineConnectionFigure.transform (AffineTransform tx)
Transforms the figure.
Reimplemented from org.jhotdraw.draw.figure.LineConnectionFigure.
References org.jhotdraw.draw.figure.LabeledLineConnectionFigure.invalidate().
updateConnection()
void org.jhotdraw.draw.figure.LabeledLineConnectionFigure.updateConnection ()
Updates the start and end point of the figure and fires figureChanged events.
Reimplemented from org.jhotdraw.draw.figure.LineConnectionFigure.
References org.jhotdraw.draw.figure.LabeledLineConnectionFigure.layout().
validate()
void org.jhotdraw.draw.figure.LabeledLineConnectionFigure.validate ()
Reimplemented from org.jhotdraw.draw.figure.LineConnectionFigure.
References org.jhotdraw.draw.figure.LabeledLineConnectionFigure.layout().
The documentation for this class was generated from the following file:
jhotdraw-core/src/main/java/org/jhotdraw/draw/figure/LabeledLineConnectionFigure.java