jhotdraw: org.jhotdraw.draw.tool.DefaultSelectAreaTracker Class Reference
org.jhotdraw.draw.tool.DefaultSelectAreaTracker Class Reference
Public Member Functions
DefaultSelectAreaTracker ()
void mousePressed (MouseEvent evt)
void mouseReleased (MouseEvent evt)
void mouseDragged (MouseEvent evt)
void mouseMoved (MouseEvent evt)
void mouseExited (MouseEvent evt)
void draw (Graphics2D g)
void activate (DrawingEditor editor)
void deactivate (DrawingEditor editor)
Public Member Functions inherited from org.jhotdraw.draw.tool.AbstractTool
AbstractTool ()
void addUndoableEditListener (UndoableEditListener l)
void removeUndoableEditListener (UndoableEditListener l)
boolean isActive ()
void setInputMap (InputMap newValue)
InputMap getInputMap ()
void setActionMap (ActionMap newValue)
ActionMap getActionMap ()
void editDelete ()
void editCut ()
void editCopy ()
void editDuplicate ()
void editPaste ()
void keyReleased (KeyEvent evt)
void keyTyped (KeyEvent evt)
void keyPressed (KeyEvent evt)
void mouseClicked (MouseEvent evt)
void mouseEntered (MouseEvent evt)
void addToolListener (ToolListener l)
void removeToolListener (ToolListener l)
void updateCursor (DrawingView view, Point p)
String getToolTipText (DrawingView view, MouseEvent evt)
boolean supportsHandleInteraction ()
Protected Member Functions
void clearHoverHandles ()
void updateHoverHandles (DrawingView view, Figure f)
Protected Member Functions inherited from org.jhotdraw.draw.tool.AbstractTool
DrawingView getView ()
DrawingEditor getEditor ()
Drawing getDrawing ()
Point2D.Double viewToDrawing (Point p)
Point2D.Double constrainPoint (Point p, Figure... figure)
Point2D.Double constrainPoint (Point2D.Double p, Figure... figure)
InputMap createInputMap ()
ActionMap createActionMap ()
void fireToolStarted (DrawingView view)
void fireToolDone ()
void fireAreaInvalidated (Rectangle2D.Double r)
void fireAreaInvalidated (Rectangle invalidatedArea)
void maybeFireBoundsInvalidated (Rectangle invalidatedArea)
void fireBoundsInvalidated (Rectangle invalidatedArea)
Additional Inherited Members
Protected Attributes inherited from org.jhotdraw.draw.tool.AbstractTool
boolean isWorking
DrawingEditor editor
Point anchor = new Point()
EventListenerList listenerList = new EventListenerList()
Detailed Description
DefaultSelectAreaTracker implements interactions with the background area of a Drawing.
The DefaultSelectAreaTracker handles one of the three states of the SelectionTool. It comes into action, when the user presses the mouse button over the background of a Drawing.
Design pattern:
Name: Chain of Responsibility.
Role: Handler.
Partners: SelectionTool as Handler, DragTracker as Handler, HandleTracker as Handler.
Design pattern:
Name: State.
Role: State.
Partners: SelectionTool as Context, DragTracker as State, HandleTracker as State.
See also
SelectionTool
Author
Werner Randelshofer
Version
$Id$
Constructor & Destructor Documentation
DefaultSelectAreaTracker()
org.jhotdraw.draw.tool.DefaultSelectAreaTracker.DefaultSelectAreaTracker ()
Creates a new instance.
Member Function Documentation
activate()
void org.jhotdraw.draw.tool.DefaultSelectAreaTracker.activate (DrawingEditor editor)
Activates the tool for the given editor. This method is called whenever the user switches to this tool.
Reimplemented from org.jhotdraw.draw.tool.AbstractTool.
References org.jhotdraw.draw.tool.DefaultSelectAreaTracker.clearHoverHandles(), and org.jhotdraw.draw.tool.AbstractTool.editor.
clearHoverHandles()
void org.jhotdraw.draw.tool.DefaultSelectAreaTracker.clearHoverHandles () protected
References org.jhotdraw.draw.tool.DefaultSelectAreaTracker.updateHoverHandles().
Referenced by org.jhotdraw.draw.tool.DefaultSelectAreaTracker.activate(), org.jhotdraw.draw.tool.DefaultSelectAreaTracker.deactivate(), and org.jhotdraw.draw.tool.DefaultSelectAreaTracker.mouseMoved().
deactivate()
void org.jhotdraw.draw.tool.DefaultSelectAreaTracker.deactivate (DrawingEditor editor)
Deactivates the tool. This method is called whenever the user switches to another tool.
Reimplemented from org.jhotdraw.draw.tool.AbstractTool.
References org.jhotdraw.draw.tool.DefaultSelectAreaTracker.clearHoverHandles(), and org.jhotdraw.draw.tool.AbstractTool.editor.
draw()
void org.jhotdraw.draw.tool.DefaultSelectAreaTracker.draw (Graphics2D g)
Draws the tool.
Reimplemented from org.jhotdraw.draw.tool.AbstractTool.
References org.jhotdraw.draw.tool.AbstractTool.getView().
mouseDragged()
void org.jhotdraw.draw.tool.DefaultSelectAreaTracker.mouseDragged (MouseEvent evt)
References org.jhotdraw.draw.tool.AbstractTool.anchor, and org.jhotdraw.draw.tool.AbstractTool.fireAreaInvalidated().
mouseExited()
void org.jhotdraw.draw.tool.DefaultSelectAreaTracker.mouseExited (MouseEvent evt)
Reimplemented from org.jhotdraw.draw.tool.AbstractTool.
References org.jhotdraw.draw.tool.AbstractTool.editor, org.jhotdraw.draw.DrawingEditor.findView(), and org.jhotdraw.draw.tool.DefaultSelectAreaTracker.updateHoverHandles().
mouseMoved()
void org.jhotdraw.draw.tool.DefaultSelectAreaTracker.mouseMoved (MouseEvent evt)
Reimplemented from org.jhotdraw.draw.tool.AbstractTool.
References org.jhotdraw.draw.tool.DefaultSelectAreaTracker.clearHoverHandles(), org.jhotdraw.draw.tool.AbstractTool.editor, org.jhotdraw.draw.DrawingView.findFigure(), org.jhotdraw.draw.Drawing.findFigureBehind(), org.jhotdraw.draw.DrawingEditor.findView(), org.jhotdraw.draw.DrawingEditor.getActiveView(), org.jhotdraw.draw.DrawingView.getDrawing(), org.jhotdraw.draw.DrawingView.getSelectedFigures(), org.jhotdraw.draw.figure.Figure.isSelectable(), org.jhotdraw.draw.tool.AbstractTool.updateCursor(), org.jhotdraw.draw.tool.DefaultSelectAreaTracker.updateHoverHandles(), and org.jhotdraw.draw.DrawingView.viewToDrawing().
mousePressed()
void org.jhotdraw.draw.tool.DefaultSelectAreaTracker.mousePressed (MouseEvent evt)
Reimplemented from org.jhotdraw.draw.tool.AbstractTool.
mouseReleased()
void org.jhotdraw.draw.tool.DefaultSelectAreaTracker.mouseReleased (MouseEvent evt)
Reimplemented from org.jhotdraw.draw.tool.AbstractTool.
updateHoverHandles()
void org.jhotdraw.draw.tool.DefaultSelectAreaTracker.updateHoverHandles (DrawingView view, Figure f) protected
References org.jhotdraw.draw.figure.Figure.createHandles(), org.jhotdraw.draw.tool.AbstractTool.fireAreaInvalidated(), org.jhotdraw.draw.figure.Figure.getDrawingArea(), and org.jhotdraw.draw.figure.Figure.isSelectable().
Referenced by org.jhotdraw.draw.tool.DefaultSelectAreaTracker.clearHoverHandles(), org.jhotdraw.draw.tool.DefaultSelectAreaTracker.mouseExited(), and org.jhotdraw.draw.tool.DefaultSelectAreaTracker.mouseMoved().
The documentation for this class was generated from the following file:
jhotdraw-core/src/main/java/org/jhotdraw/draw/tool/DefaultSelectAreaTracker.java