jhotdraw: org.jhotdraw.draw.event.SelectionComponentRepainter Class Reference
org.jhotdraw.draw.event.SelectionComponentRepainter Class Reference
Public Member Functions
SelectionComponentRepainter (DrawingEditor editor, JComponent component)
void attributeChanged (FigureEvent evt)
void propertyChange (PropertyChangeEvent evt)
void selectionChanged (FigureSelectionEvent evt)
void dispose ()
Public Member Functions inherited from org.jhotdraw.draw.event.FigureAdapter
void areaInvalidated (FigureEvent e)
void figureAdded (FigureEvent e)
void figureChanged (FigureEvent e)
void figureRemoved (FigureEvent e)
void figureRequestRemove (FigureEvent e)
void figureHandlesChanged (FigureEvent e)
Detailed Description
Calls repaint on components, which show attributes of the drawing editor and of its views based on the current selection.
Author
Werner Randelshofer
Version
$Id$
Constructor & Destructor Documentation
SelectionComponentRepainter()
org.jhotdraw.draw.event.SelectionComponentRepainter.SelectionComponentRepainter (DrawingEditor editor, JComponent component)
References org.jhotdraw.draw.figure.Figure.addFigureListener(), org.jhotdraw.draw.DrawingView.addFigureSelectionListener(), org.jhotdraw.draw.DrawingEditor.addPropertyChangeListener(), org.jhotdraw.draw.DrawingView.addPropertyChangeListener(), org.jhotdraw.draw.DrawingEditor.getActiveView(), and org.jhotdraw.draw.DrawingView.getDrawing().
Member Function Documentation
attributeChanged()
void org.jhotdraw.draw.event.SelectionComponentRepainter.attributeChanged (FigureEvent e)
Sent when an attribute of the figure has changed.
Reimplemented from org.jhotdraw.draw.event.FigureAdapter.
dispose()
void org.jhotdraw.draw.event.SelectionComponentRepainter.dispose ()
References org.jhotdraw.draw.DrawingEditor.getActiveView(), org.jhotdraw.draw.DrawingView.getDrawing(), org.jhotdraw.draw.figure.Figure.removeFigureListener(), org.jhotdraw.draw.DrawingView.removeFigureSelectionListener(), org.jhotdraw.draw.DrawingEditor.removePropertyChangeListener(), and org.jhotdraw.draw.DrawingView.removePropertyChangeListener().
propertyChange()
void org.jhotdraw.draw.event.SelectionComponentRepainter.propertyChange (PropertyChangeEvent evt)
References org.jhotdraw.draw.DrawingEditor.ACTIVE_VIEW_PROPERTY, org.jhotdraw.draw.figure.Figure.addFigureListener(), org.jhotdraw.draw.DrawingView.addFigureSelectionListener(), org.jhotdraw.draw.DrawingView.addPropertyChangeListener(), org.jhotdraw.draw.DrawingView.DRAWING_PROPERTY, org.jhotdraw.draw.DrawingView.getDrawing(), org.jhotdraw.draw.figure.Figure.removeFigureListener(), org.jhotdraw.draw.DrawingView.removeFigureSelectionListener(), and org.jhotdraw.draw.DrawingView.removePropertyChangeListener().
selectionChanged()
void org.jhotdraw.draw.event.SelectionComponentRepainter.selectionChanged (FigureSelectionEvent evt)
Implements org.jhotdraw.draw.event.FigureSelectionListener.
The documentation for this class was generated from the following file:
jhotdraw-core/src/main/java/org/jhotdraw/draw/event/SelectionComponentRepainter.java