jhotdraw: org.jhotdraw.draw.handle.ResizeHandleKit Class Reference
org.jhotdraw.draw.handle.ResizeHandleKit Class Reference
Public Member Functions
ResizeHandleKit ()
Static Public Member Functions
static void addCornerResizeHandles (Figure f, Collection< Handle > handles)
static void addEdgeResizeHandles (Figure f, Collection< Handle > handles)
static void addResizeHandles (Figure f, Collection< Handle > handles)
static Handle south (Figure owner)
static Handle southEast (Figure owner)
static Handle southWest (Figure owner)
static Handle north (Figure owner)
static Handle northEast (Figure owner)
static Handle northWest (Figure owner)
static Handle east (Figure owner)
static Handle west (Figure owner)
Detailed Description
A set of utility methods to create handles which resize a Figure by using its setBounds method, if the Figure is transformable.
Author
Werner Randelshofer
Version
$Id$
Constructor & Destructor Documentation
ResizeHandleKit()
org.jhotdraw.draw.handle.ResizeHandleKit.ResizeHandleKit ()
Creates a new instance.
Member Function Documentation
addCornerResizeHandles()
static void org.jhotdraw.draw.handle.ResizeHandleKit.addCornerResizeHandles (Figure f, Collection< Handle > handles) static
Creates handles for each corner of a figure and adds them to the provided collection.
References org.jhotdraw.draw.figure.Figure.isTransformable(), org.jhotdraw.draw.handle.ResizeHandleKit.northEast(), org.jhotdraw.draw.handle.ResizeHandleKit.northWest(), org.jhotdraw.draw.handle.ResizeHandleKit.southEast(), and org.jhotdraw.draw.handle.ResizeHandleKit.southWest().
Referenced by org.jhotdraw.draw.handle.ResizeHandleKit.addResizeHandles().
addEdgeResizeHandles()
static void org.jhotdraw.draw.handle.ResizeHandleKit.addEdgeResizeHandles (Figure f, Collection< Handle > handles) static
Fills the given collection with handles at each the north, south, east, and west of the figure.
References org.jhotdraw.draw.handle.ResizeHandleKit.east(), org.jhotdraw.draw.figure.Figure.isTransformable(), org.jhotdraw.draw.handle.ResizeHandleKit.north(), org.jhotdraw.draw.handle.ResizeHandleKit.south(), and org.jhotdraw.draw.handle.ResizeHandleKit.west().
Referenced by org.jhotdraw.draw.handle.ResizeHandleKit.addResizeHandles().
addResizeHandles()
static void org.jhotdraw.draw.handle.ResizeHandleKit.addResizeHandles (Figure f, Collection< Handle > handles) static
Fills the given collection with handles at each the north, south, east, and west of the figure.
References org.jhotdraw.draw.handle.ResizeHandleKit.addCornerResizeHandles(), org.jhotdraw.draw.handle.ResizeHandleKit.addEdgeResizeHandles(), and org.jhotdraw.draw.figure.Figure.isTransformable().
Referenced by org.jhotdraw.draw.figure.AbstractFigure.createHandles().
east()
static Handle org.jhotdraw.draw.handle.ResizeHandleKit.east (Figure owner) static
Referenced by org.jhotdraw.draw.handle.ResizeHandleKit.addEdgeResizeHandles().
north()
static Handle org.jhotdraw.draw.handle.ResizeHandleKit.north (Figure owner) static
Referenced by org.jhotdraw.draw.handle.ResizeHandleKit.addEdgeResizeHandles().
northEast()
static Handle org.jhotdraw.draw.handle.ResizeHandleKit.northEast (Figure owner) static
Referenced by org.jhotdraw.draw.handle.ResizeHandleKit.addCornerResizeHandles().
northWest()
static Handle org.jhotdraw.draw.handle.ResizeHandleKit.northWest (Figure owner) static
Referenced by org.jhotdraw.draw.handle.ResizeHandleKit.addCornerResizeHandles().
south()
static Handle org.jhotdraw.draw.handle.ResizeHandleKit.south (Figure owner) static
Referenced by org.jhotdraw.draw.handle.ResizeHandleKit.addEdgeResizeHandles().
southEast()
static Handle org.jhotdraw.draw.handle.ResizeHandleKit.southEast (Figure owner) static
Referenced by org.jhotdraw.draw.handle.ResizeHandleKit.addCornerResizeHandles().
southWest()
static Handle org.jhotdraw.draw.handle.ResizeHandleKit.southWest (Figure owner) static
Referenced by org.jhotdraw.draw.handle.ResizeHandleKit.addCornerResizeHandles().
west()
static Handle org.jhotdraw.draw.handle.ResizeHandleKit.west (Figure owner) static
Referenced by org.jhotdraw.draw.handle.ResizeHandleKit.addEdgeResizeHandles().
The documentation for this class was generated from the following file:
jhotdraw-core/src/main/java/org/jhotdraw/draw/handle/ResizeHandleKit.java