jhotdraw: org.jhotdraw.draw.action.ToggleGridAction Class Reference
org.jhotdraw.draw.action.ToggleGridAction Class Reference
Public Member Functions
ToggleGridAction (DrawingEditor editor)
void actionPerformed (java.awt.event.ActionEvent e)
Public Member Functions inherited from org.jhotdraw.draw.action.AbstractDrawingViewAction
AbstractDrawingViewAction (DrawingEditor editor)
AbstractDrawingViewAction (DrawingView view)
void dispose ()
void setUpdateEnabledState (boolean newValue)
boolean isUpdatEnabledState ()
Static Public Attributes
static final String ID = "view.toggleGrid"
Protected Member Functions
void updateViewState ()
Protected Member Functions inherited from org.jhotdraw.draw.action.AbstractDrawingViewAction
void setEditor (DrawingEditor newValue)
DrawingEditor getEditor ()
DrawingView getView ()
Drawing getDrawing ()
void fireUndoableEditHappened (UndoableEdit edit)
void updateEnabledState ()
Detailed Description
Toggles the grid of the current view.
Author
Werner Randelshofer
Version
$Id$
Constructor & Destructor Documentation
ToggleGridAction()
org.jhotdraw.draw.action.ToggleGridAction.ToggleGridAction (DrawingEditor editor)
Creates a new instance.
References org.jhotdraw.draw.action.ToggleGridAction.ID, and org.jhotdraw.draw.action.ToggleGridAction.updateViewState().
Member Function Documentation
actionPerformed()
void org.jhotdraw.draw.action.ToggleGridAction.actionPerformed (java.awt.event.ActionEvent e)
References org.jhotdraw.draw.action.AbstractDrawingViewAction.getView(), org.jhotdraw.draw.DrawingView.isConstrainerVisible(), and org.jhotdraw.draw.DrawingView.setConstrainerVisible().
updateViewState()
void org.jhotdraw.draw.action.ToggleGridAction.updateViewState () protected
This method is called when the active drawing view of the drawing editor changed. The implementation in this class does nothing.
Reimplemented from org.jhotdraw.draw.action.AbstractDrawingViewAction.
References org.jhotdraw.draw.action.AbstractDrawingViewAction.getView(), and org.jhotdraw.draw.DrawingView.isConstrainerVisible().
Referenced by org.jhotdraw.draw.action.ToggleGridAction.ToggleGridAction().
Member Data Documentation
ID
final String org.jhotdraw.draw.action.ToggleGridAction.ID = "view.toggleGrid" static
Referenced by org.jhotdraw.draw.action.ToggleGridAction.ToggleGridAction().
The documentation for this class was generated from the following file:
jhotdraw-core/src/main/java/org/jhotdraw/draw/action/ToggleGridAction.java