jhotdraw: org.jhotdraw.draw.AttributeKey< T > Class Template Reference
org.jhotdraw.draw.AttributeKey< T > Class Template Reference
Public Member Functions
AttributeKey (String key, Class< T > clazz)
AttributeKey (String key, Class< T > clazz, T defaultValue)
AttributeKey (String key, Class< T > clazz, T defaultValue, boolean isNullValueAllowed)
AttributeKey (String key, Class< T > clazz, T defaultValue, boolean isNullValueAllowed, ResourceBundleUtil labels)
String getKey ()
String getPresentationName ()
T getDefaultValue ()
T getClone (Figure f)
T get (Figure f)
T get (Map< AttributeKey<?>, Object > a)
void set (Figure f, T value)
UndoableEdit setUndoable (final Figure f, final T value)
void setClone (Figure f, T value)
void putClone (Map< AttributeKey<?>, Object > a, T value)
T put (Map< AttributeKey<?>, Object > a, T value)
boolean isNullValueAllowed ()
boolean isAssignable (Object value)
String toString ()
int hashCode ()
boolean equals (Object that)
Detailed Description
An attribute key provides typesafe access to an attribute of a Figure.
An AttributeKey has a name, a type and a default value. The default value is returned by Figure.get, if a Figure does not have an attribute of the specified key.
The following code example shows how to set and get an attribute on a Figure.
Figure aFigure;
AttributeKeys.STROKE_COLOR.put(aFigure, Color.blue);
<p<blockquote>
See AttributeKeys for a list of useful attribute keys.
Author
Werner Randelshofer
Version
$Id$
Constructor & Destructor Documentation
AttributeKey() [1/4]
org.jhotdraw.draw.AttributeKey< T >.AttributeKey (String key, Class< T > clazz)
Creates a new instance with the specified attribute key, type token class, default value null, and allowing null values.
AttributeKey() [2/4]
org.jhotdraw.draw.AttributeKey< T >.AttributeKey (String key, Class< T > clazz, T defaultValue)
Creates a new instance with the specified attribute key, type token class, and default value, and allowing null values.
AttributeKey() [3/4]
org.jhotdraw.draw.AttributeKey< T >.AttributeKey (String key, Class< T > clazz, T defaultValue, boolean isNullValueAllowed)
Creates a new instance with the specified attribute key, type token class, default value, and allowing or disallowing null values.
AttributeKey() [4/4]
org.jhotdraw.draw.AttributeKey< T >.AttributeKey (String key, Class< T > clazz, T defaultValue, boolean isNullValueAllowed, ResourceBundleUtil labels)
Creates a new instance with the specified attribute key, type token class, default value, and allowing or disallowing null values.
Parameters
key The key string.
clazz This is used as a "type token" for assignability checks at runtime.
isNullValueAllowed whether null values are allowed.
labels ResourceBundle for human friendly representation of this attribute key. The ResourceBundle must have a property named
"attribute." + key + ".text"
.
Member Function Documentation
equals()
boolean org.jhotdraw.draw.AttributeKey< T >.equals (Object that)
get() [1/2]
T org.jhotdraw.draw.AttributeKey< T >.get (Figure f)
Gets the value of the attribute denoted by this AttributeKey from a Figure.
Parameters
f A figure.
Returns
The value of the attribute.
Referenced by org.jhotdraw.draw.action.SelectionColorIcon.paintIcon().
get() [2/2]
T org.jhotdraw.draw.AttributeKey< T >.get (Map< AttributeKey<?>, Object > a)
Gets the value of the attribute denoted by this AttributeKey from a Map.
Parameters
a A Map.
Returns
The value of the attribute.
getClone()
T org.jhotdraw.draw.AttributeKey< T >.getClone (Figure f)
Gets a clone of the value from the Figure.
getDefaultValue()
T org.jhotdraw.draw.AttributeKey< T >.getDefaultValue ()
Returns the default value of the attribute.
Returns
the default value.
Referenced by org.jhotdraw.draw.action.DrawingColorIcon.paintIcon().
getKey()
String org.jhotdraw.draw.AttributeKey< T >.getKey ()
Returns the key string.
Returns
key string.
Referenced by org.jhotdraw.draw.action.DefaultAttributeAction.DefaultAttributeAction(), org.jhotdraw.draw.figure.AbstractAttributedCompositeFigure.writeAttributes(), org.jhotdraw.draw.figure.AbstractAttributedFigure.writeAttributes(), and org.jhotdraw.draw.GraphicalCompositeFigure.writeAttributes().
getPresentationName()
String org.jhotdraw.draw.AttributeKey< T >.getPresentationName ()
Returns a localized human friendly presentation of the key.
Returns
the presentation name of the key.
Referenced by org.jhotdraw.draw.action.DrawingColorChooserHandler.applySelectedColorToFigures(), org.jhotdraw.draw.action.SelectionColorChooserHandler.applySelectedColorToFigures(), and org.jhotdraw.draw.AttributeKey< WindingRule >.setUndoable().
hashCode()
int org.jhotdraw.draw.AttributeKey< T >.hashCode ()
isAssignable()
boolean org.jhotdraw.draw.AttributeKey< T >.isAssignable (Object value)
Returns true if the specified value is assignable with this key.
Parameters
value
Returns
True if assignable.
Referenced by org.jhotdraw.draw.figure.AbstractAttributedCompositeFigure.readAttributes(), org.jhotdraw.draw.figure.AbstractAttributedFigure.readAttributes(), and org.jhotdraw.draw.GraphicalCompositeFigure.readAttributes().
isNullValueAllowed()
boolean org.jhotdraw.draw.AttributeKey< T >.isNullValueAllowed ()
Returns true if null values are allowed.
Returns
true if null values are allowed.
put()
T org.jhotdraw.draw.AttributeKey< T >.put (Map< AttributeKey<?>, Object > a, T value)
Use this method to perform a type-safe put operation of an attribute into a Map.
Parameters
a An attribute map.
value The new value.
Returns
The old value.
Referenced by org.jhotdraw.draw.AttributeKey< WindingRule >.putClone().
putClone()
void org.jhotdraw.draw.AttributeKey< T >.putClone (Map< AttributeKey<?>, Object > a, T value)
Convenience method for putting a clone of a value on a map.
Parameters
a the map
value the attribute value
set()
void org.jhotdraw.draw.AttributeKey< T >.set (Figure f, T value)
Convenience method for setting a value on a Figure.
Note: Unlike in previous versions of JHotDraw 7, this method does not call
f.willChange()
before setting the value, and
f.changed()
afterwards.
Parameters
f the Figure
value the attribute value
setClone()
void org.jhotdraw.draw.AttributeKey< T >.setClone (Figure f, T value)
Convenience method for setting a clone of a value on a figure.
Note: Unlike in previous versions of JHotDraw 7, this method does not call
f.willChange()
before setting the value, and
f.changed()
afterwards.
Parameters
f the Figure
value the attribute value
setUndoable()
UndoableEdit org.jhotdraw.draw.AttributeKey< T >.setUndoable (final Figure f, final T value)
Sets the attribute and returns an UndoableEditEvent which can be used to undo it.
Note: Unlike in previous versions of JHotDraw 7, this method does not call
f.willChange()
before setting the value, and
f.changed()
afterwards.
toString()
String org.jhotdraw.draw.AttributeKey< T >.toString ()
Returns the key string.
The documentation for this class was generated from the following file:
jhotdraw-core/src/main/java/org/jhotdraw/draw/AttributeKey.java