jhotdraw: org.jhotdraw.draw.action.AbstractSelectedAction Class Reference
org.jhotdraw.draw.action.AbstractSelectedAction Class Reference abstract
Public Member Functions
AbstractSelectedAction (DrawingEditor editor)
void dispose ()
void setEditor (DrawingEditor editor)
DrawingEditor getEditor ()
void setUpdateEnabledState (boolean newValue)
boolean isUpdatEnabledState ()
Protected Member Functions
void updateEnabledState ()
DrawingView getView ()
Drawing getDrawing ()
void fireUndoableEditHappened (UndoableEdit edit)
Detailed Description
This abstract class can be extended to implement an
Action
that acts on behalf of the selected figures of a org.jhotdraw.draw.DrawingView.
By default the enabled state of this action reflects the enabled state of the active
DrawingView
. If no drawing view is active, this action is disabled. When many actions listen to the enabled state of the active drawing views this can considerably slow down the editor. If updating the enabled state is not necessary, you can prevent the action from doing so using setUpdateEnabledState.
AbstractDrawingEditorAction
listens using a WeakPropertyChangeListener on the
DrawingEditor
and thus may become garbage collected if it is not referenced by any other object.
Author
Werner Randelshofer
Version
$Id$
Constructor & Destructor Documentation
AbstractSelectedAction()
org.jhotdraw.draw.action.AbstractSelectedAction.AbstractSelectedAction (DrawingEditor editor)
Creates an action which acts on the selected figures on the current view of the specified editor.
References org.jhotdraw.draw.action.AbstractSelectedAction.setEditor().
Member Function Documentation
dispose()
void org.jhotdraw.draw.action.AbstractSelectedAction.dispose ()
References org.jhotdraw.draw.action.AbstractSelectedAction.setEditor().
fireUndoableEditHappened()
void org.jhotdraw.draw.action.AbstractSelectedAction.fireUndoableEditHappened (UndoableEdit edit) protected
References org.jhotdraw.draw.Drawing.fireUndoableEditHappened(), and org.jhotdraw.draw.action.AbstractSelectedAction.getDrawing().
Referenced by org.jhotdraw.draw.action.AlignAction.actionPerformed(), org.jhotdraw.draw.action.BringToFrontAction.actionPerformed(), org.jhotdraw.draw.action.GroupAction.actionPerformed(), org.jhotdraw.draw.action.MoveAction.actionPerformed(), org.jhotdraw.draw.action.MoveConstrainedAction.actionPerformed(), org.jhotdraw.draw.action.SendToBackAction.actionPerformed(), org.jhotdraw.draw.action.DefaultAttributeAction.actionPerformed(), org.jhotdraw.draw.action.SelectionColorChooserHandler.applySelectedColorToFigures(), and org.jhotdraw.draw.action.DefaultAttributeAction.changeAttribute().
getDrawing()
Drawing org.jhotdraw.draw.action.AbstractSelectedAction.getDrawing () protected
References org.jhotdraw.draw.DrawingView.getDrawing(), and org.jhotdraw.draw.action.AbstractSelectedAction.getView().
Referenced by org.jhotdraw.draw.action.DrawingColorChooserAction.actionPerformed(), org.jhotdraw.draw.action.AttributeAction.applyAttributesTo(), org.jhotdraw.draw.action.AbstractSelectedAction.fireUndoableEditHappened(), and org.jhotdraw.draw.action.SelectSameAction.selectSame().
getEditor()
DrawingEditor org.jhotdraw.draw.action.AbstractSelectedAction.getEditor ()
Referenced by org.jhotdraw.draw.action.ApplyAttributesAction.applyAttributes(), org.jhotdraw.draw.action.AttributeAction.applyAttributesTo(), org.jhotdraw.draw.action.SelectionColorChooserHandler.applySelectedColorToFigures(), org.jhotdraw.draw.action.DefaultAttributeAction.changeAttribute(), org.jhotdraw.draw.action.DrawingColorChooserAction.getInitialColor(), org.jhotdraw.draw.action.EditorColorChooserAction.getInitialColor(), org.jhotdraw.draw.action.SelectionColorChooserAction.getInitialColor(), org.jhotdraw.draw.action.PickAttributesAction.pickAttributes(), org.jhotdraw.draw.action.AttributeAction.updateEnabledState(), and org.jhotdraw.draw.action.SelectionColorChooserHandler.updateEnabledState().
getView()
DrawingView org.jhotdraw.draw.action.AbstractSelectedAction.getView () protected
References org.jhotdraw.draw.DrawingEditor.getActiveView().
Referenced by org.jhotdraw.draw.action.AlignAction.actionPerformed(), org.jhotdraw.draw.action.BringToFrontAction.actionPerformed(), org.jhotdraw.draw.action.DrawingColorChooserAction.actionPerformed(), org.jhotdraw.draw.action.EditorColorChooserAction.actionPerformed(), org.jhotdraw.draw.action.GroupAction.actionPerformed(), org.jhotdraw.draw.action.MoveAction.actionPerformed(), org.jhotdraw.draw.action.MoveConstrainedAction.actionPerformed(), org.jhotdraw.draw.action.SendToBackAction.actionPerformed(), org.jhotdraw.draw.action.AttributeAction.actionPerformed(), org.jhotdraw.draw.action.DefaultAttributeAction.actionPerformed(), org.jhotdraw.draw.action.ApplyAttributesAction.applyAttributes(), org.jhotdraw.draw.action.SelectionColorChooserHandler.applySelectedColorToFigures(), org.jhotdraw.draw.action.GroupAction.canGroup(), org.jhotdraw.draw.action.GroupAction.canUngroup(), org.jhotdraw.draw.action.DefaultAttributeAction.changeAttribute(), org.jhotdraw.draw.action.AbstractSelectedAction.getDrawing(), org.jhotdraw.draw.action.AlignAction.getSelectionBounds(), org.jhotdraw.draw.action.IncreaseHandleDetailLevelAction.increaseHandleDetaiLevel(), org.jhotdraw.draw.action.PickAttributesAction.pickAttributes(), org.jhotdraw.draw.action.ApplyAttributesAction.selectionChanged(), org.jhotdraw.draw.action.PickAttributesAction.selectionChanged(), org.jhotdraw.draw.action.SelectSameAction.selectSame(), org.jhotdraw.draw.action.AbstractSelectedAction.updateEnabledState(), org.jhotdraw.draw.action.AlignAction.updateEnabledState(), org.jhotdraw.draw.action.DrawingColorChooserAction.updateEnabledState(), org.jhotdraw.draw.action.GroupAction.updateEnabledState(), and org.jhotdraw.draw.action.SelectionColorChooserHandler.updateEnabledState().
isUpdatEnabledState()
boolean org.jhotdraw.draw.action.AbstractSelectedAction.isUpdatEnabledState ()
Returns true, if this action automatically updates its enabled state to reflect the enabled state of the active
DrawingView
.
setEditor()
void org.jhotdraw.draw.action.AbstractSelectedAction.setEditor (DrawingEditor editor)
References org.jhotdraw.draw.action.AbstractSelectedAction.updateEnabledState().
Referenced by org.jhotdraw.draw.action.AbstractSelectedAction.AbstractSelectedAction(), and org.jhotdraw.draw.action.AbstractSelectedAction.dispose().
setUpdateEnabledState()
void org.jhotdraw.draw.action.AbstractSelectedAction.setUpdateEnabledState (boolean newValue)
By default, the enabled state of this action is updated to reflect the enabled state of the active
DrawingView
. Since this is not always necessary, and since many listening actions may considerably slow down the drawing editor, you can switch this behavior off here.
Parameters
newValue Specify false to prevent automatic updating of the enabled state.
References org.jhotdraw.draw.action.AbstractSelectedAction.updateEnabledState().
updateEnabledState()
void org.jhotdraw.draw.action.AbstractSelectedAction.updateEnabledState () protected
Updates the enabled state of this action to reflect the enabled state of the active
DrawingView
. If no drawing view is active, this action is disabled.
Reimplemented in org.jhotdraw.draw.action.SelectionColorChooserHandler, org.jhotdraw.draw.action.GroupAction, org.jhotdraw.draw.action.DrawingColorChooserAction, org.jhotdraw.draw.action.AttributeAction, and org.jhotdraw.draw.action.AlignAction.
References org.jhotdraw.draw.action.AbstractSelectedAction.getView().
Referenced by org.jhotdraw.draw.action.ApplyAttributesAction.ApplyAttributesAction(), org.jhotdraw.draw.action.BringToFrontAction.BringToFrontAction(), org.jhotdraw.draw.action.DefaultAttributeAction.DefaultAttributeAction(), org.jhotdraw.draw.action.IncreaseHandleDetailLevelAction.IncreaseHandleDetailLevelAction(), org.jhotdraw.draw.action.MoveAction.MoveAction(), org.jhotdraw.draw.action.MoveConstrainedAction.MoveConstrainedAction(), org.jhotdraw.draw.action.PickAttributesAction.PickAttributesAction(), org.jhotdraw.draw.action.SelectSameAction.SelectSameAction(), org.jhotdraw.draw.action.SendToBackAction.SendToBackAction(), org.jhotdraw.draw.action.AbstractSelectedAction.setEditor(), and org.jhotdraw.draw.action.AbstractSelectedAction.setUpdateEnabledState().
The documentation for this class was generated from the following file:
jhotdraw-core/src/main/java/org/jhotdraw/draw/action/AbstractSelectedAction.java