jhotdraw: org.jhotdraw.draw.GraphicalCompositeFigure Class Reference
org.jhotdraw.draw.GraphicalCompositeFigure Class Reference
Public Member Functions
GraphicalCompositeFigure ()
GraphicalCompositeFigure (Figure newPresentationFigure)
Rectangle2D.Double getBounds ()
boolean contains (Point2D.Double p)
void addNotify (Drawing drawing)
void removeNotify (Drawing drawing)
Rectangle2D.Double getDrawingArea ()
void setBounds (Point2D.Double anchor, Point2D.Double lead)
void transform (AffineTransform tx)
void draw (Graphics2D g)
Collection< Handle > createHandles (int detailLevel)
void setPresentationFigure (Figure newPresentationFigure)
Figure getPresentationFigure ()
GraphicalCompositeFigure clone ()
void remap (HashMap< Figure, Figure > oldToNew, boolean disconnectIfNotInMap)
void setAttributeEnabled (AttributeKey<?> key, boolean b)
void read (DOMInput in) throws IOException
void write (DOMOutput out) throws IOException
Map< AttributeKey<?>, Object > getAttributes ()
Point2D.Double chop (Point2D.Double from)
Public Member Functions inherited from org.jhotdraw.draw.figure.AbstractCompositeFigure
AbstractCompositeFigure ()
boolean add (Figure figure)
void add (int index, Figure figure)
void addAll (Collection<? extends Figure > figures)
final void addAll (int index, Collection<? extends Figure > figures)
void basicAdd (Figure figure)
void basicAddAll (int index, Collection<? extends Figure > newFigures)
boolean remove (final Figure figure)
Figure removeChild (int index)
void removeAll (Collection<? extends Figure > figures)
void removeAllChildren ()
void basicRemoveAllChildren ()
void basicRemoveAll (Collection<? extends Figure > figures)
void sendToBack (Figure figure)
void bringToFront (Figure figure)
java.util.List< Figure > getChildrenFrontToBack ()
Object getAttributesRestoreData ()
void restoreAttributesTo (Object newData)
boolean contains (Figure f)
Figure findFigureInside (Point2D.Double p)
Figure findChild (Point2D.Double p)
int findChildIndex (Point2D.Double p)
Layouter getLayouter ()
void layout ()
void setLayouter (Layouter newLayouter)
Dimension2DDouble getPreferredSize ()
Collection< Figure > getDecomposition ()
void restoreTransformTo (Object geometry)
Object getTransformRestoreData ()
void basicAdd (int index, Figure figure)
Figure basicRemoveChild (int index)
java.util.List< Figure > getChildren ()
int getChildCount ()
Figure getChild (int index)
void willChange ()
void changed ()
int basicRemove (Figure child)
int indexOf (Figure child)
Rectangle2D.Double getDrawingArea (double factor)
void removeCompositeFigureListener (CompositeFigureListener listener)
void addCompositeFigureListener (CompositeFigureListener listener)
Public Member Functions inherited from org.jhotdraw.draw.figure.AbstractFigure
AbstractFigure ()
void addFigureListener (FigureListener l)
void removeFigureListener (FigureListener l)
void fireAreaInvalidated ()
void fireFigureChanged ()
void remap (Map< Figure, Figure > oldToNew, boolean disconnectIfNotInMap)
Cursor getCursor (Point2D.Double p)
final void setBounds (Rectangle2D.Double bounds)
Connector findConnector (Point2D.Double p, ConnectionFigure prototype)
boolean includes (Figure figure)
Connector findCompatibleConnector (Connector c, boolean isStart)
Collection< Action > getActions (Point2D.Double p)
Tool getTool (Point2D.Double p)
boolean handleMouseClick (Point2D.Double p, MouseEvent evt, DrawingView view)
boolean handleDrop (Point2D.Double p, Collection< Figure > droppedFigures, DrawingView view)
Point2D.Double getEndPoint ()
Point2D.Double getStartPoint ()
boolean isConnectable ()
void setConnectable (boolean newValue)
boolean isSelectable ()
void setSelectable (boolean newValue)
boolean isRemovable ()
void setRemovable (boolean newValue)
boolean isTransformable ()
void setTransformable (boolean newValue)
boolean isVisible ()
void setVisible (boolean newValue)
void requestRemove ()
int getLayer ()
String getToolTipText (Point2D.Double p)
String toString ()
Collection< Connector > getConnectors (ConnectionFigure prototype)
Public Member Functions inherited from org.jhotdraw.draw.figure.Figure
void addPropertyChangeListener (PropertyChangeListener listener)
void removePropertyChangeListener (PropertyChangeListener listener)
Protected Member Functions
void superBasicSetBounds (Point2D.Double anchor, Point2D.Double lead)
void basicSetPresentationFigureBounds (Point2D.Double anchor, Point2D.Double lead)
void drawPresentationFigure (Graphics2D g)
void applyAttributesTo (Figure that)
void writeAttributes (DOMOutput out) throws IOException
void readAttributes (DOMInput in) throws IOException
AttributeKey<?> getAttributeKey (String name)
Protected Member Functions inherited from org.jhotdraw.draw.figure.AbstractCompositeFigure
EventHandler createEventHandler ()
void validate ()
void invalidate ()
void fireFigureAdded (Figure f, int zIndex)
void fireFigureRemoved (Figure f, int zIndex)
Protected Member Functions inherited from org.jhotdraw.draw.figure.AbstractFigure
Drawing getDrawing ()
Object getLock ()
void fireAreaInvalidated (Rectangle2D.Double invalidatedArea)
void fireAreaInvalidated (FigureEvent event)
void fireFigureRequestRemove ()
void fireFigureAdded ()
void fireFigureRemoved ()
void fireFigureChanged (Rectangle2D.Double changedArea)
void fireFigureChanged (FigureEvent event)
void fireFigureHandlesChanged ()
void fireUndoableEditHappened (UndoableEdit edit)
boolean isChanging ()
int getChangingDepth ()
FontRenderContext getFontRenderContext ()
Protected Attributes
HashMap< AttributeKey<?>, Object > attributes = new HashMap<>()
Protected Attributes inherited from org.jhotdraw.draw.figure.AbstractCompositeFigure
Layouter layouter
ArrayList< Figure > children = new ArrayList<>()
transient Rectangle2D.Double cachedDrawingArea
transient Rectangle2D.Double cachedBounds
EventHandler eventHandler
Protected Attributes inherited from org.jhotdraw.draw.figure.AbstractFigure
EventListenerList listenerList = new EventListenerList()
int changingDepth = 0
Additional Inherited Members
Static Public Attributes inherited from org.jhotdraw.draw.figure.Figure
static final String CONNECTABLE_PROPERTY = "connectable"
static final String REMOVABLE_PROPERTY = "removable"
static final String SELECTABLE_PROPERTY = "selectable"
static final String TRANSFORMABLE_PROPERTY = "transformable"
Static Public Attributes inherited from org.jhotdraw.draw.figure.CompositeFigure
static final AttributeKey< Insets2D.Double > LAYOUT_INSETS = new AttributeKey<Insets2D.Double>("layoutInsets", Insets2D.Double.class, new Insets2D.Double())
Detailed Description
The GraphicalCompositeFigure fills in the gap between a CompositeFigure and other figures which mainly have a presentation purpose. The GraphicalCompositeFigure can be configured with any Figure which takes over the task for rendering the graphical presentation for a CompositeFigure. Therefore, the GraphicalCompositeFigure manages contained figures like a CompositeFigure does, but delegates its graphical presentation to another (graphical) figure which purpose it is to draw the container for all contained figures.
The GraphicalCompositeFigure adds to the CompositeFigure by containing a presentation figure by default which can not be removed. Normally, the
CompositeFigure
can not be seen without containing a figure because it has no mechanism to draw itself. It instead relies on its contained figures to draw themselves thereby giving the
CompositeFigure
its appearance. However, the GraphicalCompositeFigure's presentation figure can draw itself even when the GraphicalCompositeFigure contains no other figures. The GraphicalCompositeFigure also uses a org.jhotdraw.draw.layouter.Layouter to lay out its child figures.
Author
Wolfram Kaiser (original code), Werner Randelshofer (this derived version)
Version
$Id$
Constructor & Destructor Documentation
GraphicalCompositeFigure() [1/2]
org.jhotdraw.draw.GraphicalCompositeFigure.GraphicalCompositeFigure ()
Default constructor which uses nothing as presentation figure. This constructor is needed by the Storable mechanism.
Referenced by org.jhotdraw.draw.GraphicalCompositeFigure.clone().
GraphicalCompositeFigure() [2/2]
org.jhotdraw.draw.GraphicalCompositeFigure.GraphicalCompositeFigure (Figure newPresentationFigure)
Constructor which creates a GraphicalCompositeFigure with a given graphical figure for presenting it.
Parameters
newPresentationFigure figure which renders the container
References org.jhotdraw.draw.GraphicalCompositeFigure.setPresentationFigure().
Member Function Documentation
addNotify()
void org.jhotdraw.draw.GraphicalCompositeFigure.addNotify (Drawing d)
Informs a figure, that it has been added to a drawing. The figure must inform all FigureListeners that it has been added.
Reimplemented from org.jhotdraw.draw.figure.AbstractCompositeFigure.
References org.jhotdraw.draw.figure.Figure.addNotify(), and org.jhotdraw.draw.GraphicalCompositeFigure.getPresentationFigure().
applyAttributesTo()
void org.jhotdraw.draw.GraphicalCompositeFigure.applyAttributesTo (Figure that) protected
Applies all attributes of this figure to that figure.
References org.jhotdraw.draw.GraphicalCompositeFigure.attributes.
basicSetPresentationFigureBounds()
void org.jhotdraw.draw.GraphicalCompositeFigure.basicSetPresentationFigureBounds (Point2D.Double anchor, Point2D.Double lead) protected
References org.jhotdraw.draw.GraphicalCompositeFigure.getPresentationFigure(), and org.jhotdraw.draw.figure.Figure.setBounds().
Referenced by org.jhotdraw.draw.GraphicalCompositeFigure.setBounds().
chop()
Point2D.Double org.jhotdraw.draw.GraphicalCompositeFigure.chop (Point2D.Double from)
This is a default implementation that chops the point at the rectangle returned by getBounds() of the figure.
Figures which have a non-rectangular shape need to override this method.
This method takes the following attributes into account: AttributeKeys.STROKE_COLOR, AttributeKeys.STROKE_PLACEMENT, and AttributeKeys.StrokeTotalWidth.
References org.jhotdraw.draw.GraphicalCompositeFigure.getBounds(), and org.jhotdraw.draw.AttributeKeys.getStrokeTotalWidth().
clone()
GraphicalCompositeFigure org.jhotdraw.draw.GraphicalCompositeFigure.clone ()
Returns a clone of the figure, with clones of all aggregated figures, such as children and decorators. The cloned figure does not clone the list of FigureListeners from its original.
Reimplemented from org.jhotdraw.draw.figure.AbstractCompositeFigure.
References org.jhotdraw.draw.figure.Figure.addFigureListener(), org.jhotdraw.draw.GraphicalCompositeFigure.attributes, org.jhotdraw.draw.figure.Figure.clone(), org.jhotdraw.draw.GraphicalCompositeFigure.clone(), and org.jhotdraw.draw.GraphicalCompositeFigure.GraphicalCompositeFigure().
Referenced by org.jhotdraw.draw.GraphicalCompositeFigure.clone().
contains()
boolean org.jhotdraw.draw.GraphicalCompositeFigure.contains (Point2D.Double p)
Checks if a point is contained by the figure.
This is used for hit testing by Tool's.
Reimplemented from org.jhotdraw.draw.figure.AbstractCompositeFigure.
References org.jhotdraw.draw.figure.Figure.contains(), and org.jhotdraw.draw.GraphicalCompositeFigure.getPresentationFigure().
createHandles()
Collection<Handle> org.jhotdraw.draw.GraphicalCompositeFigure.createHandles (int detailLevel)
Return default handles from the presentation figure.
Reimplemented from org.jhotdraw.draw.figure.AbstractCompositeFigure.
References org.jhotdraw.draw.handle.MoveHandle.addMoveHandles().
draw()
void org.jhotdraw.draw.GraphicalCompositeFigure.draw (Graphics2D g)
Draw the figure. This method is delegated to the encapsulated presentation figure.
Reimplemented from org.jhotdraw.draw.figure.AbstractCompositeFigure.
References org.jhotdraw.draw.GraphicalCompositeFigure.drawPresentationFigure().
drawPresentationFigure()
void org.jhotdraw.draw.GraphicalCompositeFigure.drawPresentationFigure (Graphics2D g) protected
References org.jhotdraw.draw.figure.Figure.draw(), and org.jhotdraw.draw.GraphicalCompositeFigure.getPresentationFigure().
Referenced by org.jhotdraw.draw.GraphicalCompositeFigure.draw().
getAttributeKey()
AttributeKey<?> org.jhotdraw.draw.GraphicalCompositeFigure.getAttributeKey (String name) protected
References org.jhotdraw.draw.AttributeKeys.SUPPORTED_ATTRIBUTES_MAP.
Referenced by org.jhotdraw.draw.GraphicalCompositeFigure.readAttributes().
getAttributes()
Map<AttributeKey<?>, Object> org.jhotdraw.draw.GraphicalCompositeFigure.getAttributes ()
Returns a view to all attributes of this figure. By convention, an unmodifiable map is returned.
Reimplemented from org.jhotdraw.draw.figure.AbstractCompositeFigure.
References org.jhotdraw.draw.GraphicalCompositeFigure.attributes.
getBounds()
Rectangle2D.Double org.jhotdraw.draw.GraphicalCompositeFigure.getBounds ()
Return the logcal display area. This method is delegated to the encapsulated presentation figure.
Reimplemented from org.jhotdraw.draw.figure.AbstractCompositeFigure.
References org.jhotdraw.draw.figure.Figure.getBounds(), and org.jhotdraw.draw.GraphicalCompositeFigure.getPresentationFigure().
Referenced by org.jhotdraw.draw.GraphicalCompositeFigure.chop().
getDrawingArea()
Rectangle2D.Double org.jhotdraw.draw.GraphicalCompositeFigure.getDrawingArea ()
Return the draw area. This method is delegated to the encapsulated presentation figure.
Reimplemented from org.jhotdraw.draw.figure.AbstractCompositeFigure.
References org.jhotdraw.draw.GraphicalCompositeFigure.getPresentationFigure().
getPresentationFigure()
Figure org.jhotdraw.draw.GraphicalCompositeFigure.getPresentationFigure ()
Get a figure which renders this BasicCompositeFigure. The presentation tasks for the BasicCompositeFigure are delegated to this presentation figure.
Returns
figure takes over the presentation tasks
Referenced by org.jhotdraw.draw.GraphicalCompositeFigure.addNotify(), org.jhotdraw.draw.GraphicalCompositeFigure.basicSetPresentationFigureBounds(), org.jhotdraw.draw.GraphicalCompositeFigure.contains(), org.jhotdraw.draw.GraphicalCompositeFigure.drawPresentationFigure(), org.jhotdraw.draw.GraphicalCompositeFigure.getBounds(), org.jhotdraw.draw.GraphicalCompositeFigure.getDrawingArea(), org.jhotdraw.draw.GraphicalCompositeFigure.removeNotify(), and org.jhotdraw.draw.GraphicalCompositeFigure.transform().
read()
void org.jhotdraw.draw.GraphicalCompositeFigure.read (DOMInput in) throws IOException
Reimplemented from org.jhotdraw.draw.figure.AbstractCompositeFigure.
References org.jhotdraw.draw.GraphicalCompositeFigure.readAttributes().
readAttributes()
void org.jhotdraw.draw.GraphicalCompositeFigure.readAttributes (DOMInput in) throws IOException protected
References org.jhotdraw.draw.GraphicalCompositeFigure.getAttributeKey(), and org.jhotdraw.draw.AttributeKey< T >.isAssignable().
Referenced by org.jhotdraw.draw.GraphicalCompositeFigure.read().
remap()
void org.jhotdraw.draw.GraphicalCompositeFigure.remap (HashMap< Figure, Figure > oldToNew, boolean disconnectIfNotInMap)
References org.jhotdraw.draw.figure.Figure.remap().
removeNotify()
void org.jhotdraw.draw.GraphicalCompositeFigure.removeNotify (Drawing d)
Informs a figure, that it has been removed from a drawing. The figure must inform all FigureListeners that it has been removed.
Reimplemented from org.jhotdraw.draw.figure.AbstractCompositeFigure.
References org.jhotdraw.draw.GraphicalCompositeFigure.getPresentationFigure(), and org.jhotdraw.draw.figure.Figure.removeNotify().
setAttributeEnabled()
void org.jhotdraw.draw.GraphicalCompositeFigure.setAttributeEnabled (AttributeKey<?> key, boolean b)
setBounds()
void org.jhotdraw.draw.GraphicalCompositeFigure.setBounds (Point2D.Double anchor, Point2D.Double lead)
Moves the figure. This is the method that subclassers override. Clients usually call displayBox.
Reimplemented from org.jhotdraw.draw.figure.AbstractCompositeFigure.
References org.jhotdraw.draw.GraphicalCompositeFigure.basicSetPresentationFigureBounds(), org.jhotdraw.draw.figure.AbstractCompositeFigure.getLayouter(), org.jhotdraw.draw.figure.AbstractCompositeFigure.invalidate(), and org.jhotdraw.draw.layouter.Layouter.layout().
setPresentationFigure()
void org.jhotdraw.draw.GraphicalCompositeFigure.setPresentationFigure (Figure newPresentationFigure)
Set a figure which renders this BasicCompositeFigure. The presentation tasks for the BasicCompositeFigure are delegated to this presentation figure.
Parameters
newPresentationFigure figure takes over the presentation tasks
References org.jhotdraw.draw.figure.Figure.addFigureListener(), org.jhotdraw.draw.figure.Figure.addNotify(), org.jhotdraw.draw.figure.AbstractFigure.getDrawing(), org.jhotdraw.draw.figure.Figure.removeFigureListener(), and org.jhotdraw.draw.figure.Figure.removeNotify().
Referenced by org.jhotdraw.draw.GraphicalCompositeFigure.GraphicalCompositeFigure().
superBasicSetBounds()
void org.jhotdraw.draw.GraphicalCompositeFigure.superBasicSetBounds (Point2D.Double anchor, Point2D.Double lead) protected
transform()
void org.jhotdraw.draw.GraphicalCompositeFigure.transform (AffineTransform tx)
Standard presentation method which is delegated to the encapsulated presentation figure. The presentation figure is moved as well as all contained figures.
Reimplemented from org.jhotdraw.draw.figure.AbstractCompositeFigure.
References org.jhotdraw.draw.GraphicalCompositeFigure.getPresentationFigure(), and org.jhotdraw.draw.figure.Figure.transform().
write()
void org.jhotdraw.draw.GraphicalCompositeFigure.write (DOMOutput out) throws IOException
Reimplemented from org.jhotdraw.draw.figure.AbstractCompositeFigure.
References org.jhotdraw.draw.GraphicalCompositeFigure.writeAttributes().
writeAttributes()
void org.jhotdraw.draw.GraphicalCompositeFigure.writeAttributes (DOMOutput out) throws IOException protected
References org.jhotdraw.draw.GraphicalCompositeFigure.attributes, org.jhotdraw.draw.figure.Figure.get(), and org.jhotdraw.draw.AttributeKey< T >.getKey().
Referenced by org.jhotdraw.draw.GraphicalCompositeFigure.write().
Member Data Documentation
attributes
HashMap<AttributeKey<?>, Object> org.jhotdraw.draw.GraphicalCompositeFigure.attributes = new HashMap<>() protected
Referenced by org.jhotdraw.draw.GraphicalCompositeFigure.applyAttributesTo(), org.jhotdraw.draw.GraphicalCompositeFigure.clone(), org.jhotdraw.draw.GraphicalCompositeFigure.getAttributes(), and org.jhotdraw.draw.GraphicalCompositeFigure.writeAttributes().
The documentation for this class was generated from the following file:
jhotdraw-core/src/main/java/org/jhotdraw/draw/GraphicalCompositeFigure.java