jhotdraw: org.jhotdraw.draw.tool.TextAreaCreationTool Class Reference
org.jhotdraw.draw.tool.TextAreaCreationTool Class Reference
Public Member Functions
TextAreaCreationTool (TextHolderFigure prototype)
TextAreaCreationTool (TextHolderFigure prototype, Map< AttributeKey<?>, Object > attributes)
void setRubberbandColor (Color c)
void deactivate (DrawingEditor editor)
void mousePressed (MouseEvent e)
void draw (Graphics2D g)
void actionPerformed (ActionEvent event)
Public Member Functions inherited from org.jhotdraw.draw.tool.CreationTool
CreationTool (String prototypeClassName)
CreationTool (String prototypeClassName, Map< AttributeKey<?>, Object > attributes)
CreationTool (String prototypeClassName, Map< AttributeKey<?>, Object > attributes, String name)
CreationTool (Figure prototype)
CreationTool (Figure prototype, Map< AttributeKey<?>, Object > attributes)
CreationTool (Figure prototype, Map< AttributeKey<?>, Object > attributes, String name)
Figure getPrototype ()
void activate (DrawingEditor editor)
void mouseDragged (MouseEvent evt)
void mouseReleased (MouseEvent evt)
void setToolDoneAfterCreation (boolean newValue)
boolean isToolDoneAfterCreation ()
void updateCursor (DrawingView view, Point p)
Public Member Functions inherited from org.jhotdraw.draw.tool.AbstractTool
AbstractTool ()
void addUndoableEditListener (UndoableEditListener l)
void removeUndoableEditListener (UndoableEditListener l)
boolean isActive ()
void setInputMap (InputMap newValue)
InputMap getInputMap ()
void setActionMap (ActionMap newValue)
ActionMap getActionMap ()
void editDelete ()
void editCut ()
void editCopy ()
void editDuplicate ()
void editPaste ()
void keyReleased (KeyEvent evt)
void keyTyped (KeyEvent evt)
void keyPressed (KeyEvent evt)
void mouseClicked (MouseEvent evt)
void mouseEntered (MouseEvent evt)
void mouseExited (MouseEvent evt)
void mouseMoved (MouseEvent evt)
void addToolListener (ToolListener l)
void removeToolListener (ToolListener l)
String getToolTipText (DrawingView view, MouseEvent evt)
boolean supportsHandleInteraction ()
Protected Member Functions
void creationFinished (Figure createdFigure)
void beginEdit (TextHolderFigure textHolder)
void endEdit ()
Protected Member Functions inherited from org.jhotdraw.draw.tool.CreationTool
Figure createFigure ()
Figure getCreatedFigure ()
Figure getAddedFigure ()
Protected Member Functions inherited from org.jhotdraw.draw.tool.AbstractTool
DrawingView getView ()
DrawingEditor getEditor ()
Drawing getDrawing ()
Point2D.Double viewToDrawing (Point p)
Point2D.Double constrainPoint (Point p, Figure... figure)
Point2D.Double constrainPoint (Point2D.Double p, Figure... figure)
InputMap createInputMap ()
ActionMap createActionMap ()
void fireToolStarted (DrawingView view)
void fireToolDone ()
void fireAreaInvalidated (Rectangle2D.Double r)
void fireAreaInvalidated (Rectangle invalidatedArea)
void maybeFireBoundsInvalidated (Rectangle invalidatedArea)
void fireBoundsInvalidated (Rectangle invalidatedArea)
Additional Inherited Members
Protected Attributes inherited from org.jhotdraw.draw.tool.CreationTool
Map< AttributeKey<?>, Object > prototypeAttributes
String presentationName
Dimension minimalSizeTreshold = new Dimension(2, 2)
Dimension minimalSize = new Dimension(40, 40)
Figure prototype
Figure createdFigure
Protected Attributes inherited from org.jhotdraw.draw.tool.AbstractTool
boolean isWorking
DrawingEditor editor
Point anchor = new Point()
EventListenerList listenerList = new EventListenerList()
Detailed Description
A tool to create new or edit existing figures that implement the TextHolderFigure interface, such as TextAreaFigure. The figure to be created is specified by a prototype.
To create a figure using the TextAreaCreationTool, the user does the following mouse gestures on a DrawingView:
Press the mouse button over the DrawingView. This defines the start point of the Figure bounds.
Drag the mouse while keeping the mouse button pressed, and then release the mouse button. This defines the end point of the Figure bounds.
When the user has performed these mouse gesture, the TextAreaCreationTool overlays a text area over the drawing where the user can enter the text for the Figure.
To edit an existing text figure using the TextAreaCreationTool, the user does the following mouse gesture on a DrawingView:
Press the mouse button over a Figure on the DrawingView.
The TextAreaCreationTool then uses Figure.findFigureInside to find a Figure that implements the TextHolderFigure interface and that is editable. Then it overlays a text area over the drawing where the user can enter the text for the Figure.
XXX - Maybe this class should be split up into a CreateTextAreaTool and a EditTextAreaTool.
Design Patterns
Framework
The text creation and editing tools and the
TextHolderFigure
interface define together the contracts of a smaller framework inside of the JHotDraw framework for structured drawing editors.
Contract: TextHolderFigure, TextCreationTool, TextAreaCreationTool, TextEditingTool, TextAreaEditingTool, FloatingTextField, FloatingTextArea.
Prototype
The text creation tools create new figures by cloning a prototype
TextHolderFigure
object.
Prototype: TextHolderFigure; Client: TextCreationTool, TextAreaCreationTool.
Author
Werner Randelshofer
Version
$Id$
Constructor & Destructor Documentation
TextAreaCreationTool() [1/2]
org.jhotdraw.draw.tool.TextAreaCreationTool.TextAreaCreationTool (TextHolderFigure prototype)
Creates a new instance.
References org.jhotdraw.draw.tool.CreationTool.prototype.
TextAreaCreationTool() [2/2]
org.jhotdraw.draw.tool.TextAreaCreationTool.TextAreaCreationTool (TextHolderFigure prototype, Map< AttributeKey<?>, Object > attributes)
References org.jhotdraw.draw.tool.CreationTool.prototype.
Member Function Documentation
actionPerformed()
void org.jhotdraw.draw.tool.TextAreaCreationTool.actionPerformed (ActionEvent event)
References org.jhotdraw.draw.tool.TextAreaCreationTool.endEdit(), org.jhotdraw.draw.tool.AbstractTool.fireToolDone(), and org.jhotdraw.draw.tool.CreationTool.isToolDoneAfterCreation().
beginEdit()
void org.jhotdraw.draw.tool.TextAreaCreationTool.beginEdit (TextHolderFigure textHolder) protected
References org.jhotdraw.draw.text.FloatingTextArea.createOverlay(), org.jhotdraw.draw.tool.TextAreaCreationTool.endEdit(), org.jhotdraw.draw.figure.TextHolderFigure.getText(), org.jhotdraw.draw.tool.AbstractTool.getView(), org.jhotdraw.draw.text.FloatingTextArea.requestFocus(), and org.jhotdraw.draw.text.FloatingTextArea.setBounds().
Referenced by org.jhotdraw.draw.tool.TextAreaCreationTool.creationFinished().
creationFinished()
void org.jhotdraw.draw.tool.TextAreaCreationTool.creationFinished (Figure createdFigure) protected
This method allows subclasses to do perform additonal user interactions after the new figure has been created. The implementation of this class just invokes fireToolDone.
Reimplemented from org.jhotdraw.draw.tool.CreationTool.
References org.jhotdraw.draw.DrawingView.addToSelection(), org.jhotdraw.draw.tool.TextAreaCreationTool.beginEdit(), org.jhotdraw.draw.DrawingView.clearSelection(), org.jhotdraw.draw.tool.CreationTool.createdFigure, and org.jhotdraw.draw.tool.AbstractTool.getView().
deactivate()
void org.jhotdraw.draw.tool.TextAreaCreationTool.deactivate (DrawingEditor editor)
Deactivates the tool. This method is called whenever the user switches to another tool.
Reimplemented from org.jhotdraw.draw.tool.CreationTool.
References org.jhotdraw.draw.tool.AbstractTool.editor, and org.jhotdraw.draw.tool.TextAreaCreationTool.endEdit().
draw()
void org.jhotdraw.draw.tool.TextAreaCreationTool.draw (Graphics2D g)
Draws the tool.
Reimplemented from org.jhotdraw.draw.tool.AbstractTool.
References org.jhotdraw.draw.tool.CreationTool.createdFigure, org.jhotdraw.draw.figure.Figure.getBounds(), and org.jhotdraw.draw.tool.AbstractTool.getView().
endEdit()
void org.jhotdraw.draw.tool.TextAreaCreationTool.endEdit () protected
References org.jhotdraw.draw.figure.Figure.changed(), org.jhotdraw.draw.tool.CreationTool.createdFigure, org.jhotdraw.draw.text.FloatingTextArea.endOverlay(), org.jhotdraw.draw.Drawing.fireUndoableEditHappened(), org.jhotdraw.draw.tool.CreationTool.getAddedFigure(), org.jhotdraw.draw.tool.AbstractTool.getDrawing(), org.jhotdraw.draw.figure.TextHolderFigure.getText(), org.jhotdraw.draw.text.FloatingTextArea.getText(), org.jhotdraw.draw.Drawing.remove(), org.jhotdraw.draw.figure.TextHolderFigure.setText(), and org.jhotdraw.draw.figure.Figure.willChange().
Referenced by org.jhotdraw.draw.tool.TextAreaCreationTool.actionPerformed(), org.jhotdraw.draw.tool.TextAreaCreationTool.beginEdit(), org.jhotdraw.draw.tool.TextAreaCreationTool.deactivate(), and org.jhotdraw.draw.tool.TextAreaCreationTool.mousePressed().
mousePressed()
void org.jhotdraw.draw.tool.TextAreaCreationTool.mousePressed (MouseEvent e)
Creates a new figure at the mouse location. If editing is in progress, this finishes editing.
Reimplemented from org.jhotdraw.draw.tool.CreationTool.
References org.jhotdraw.draw.tool.TextAreaCreationTool.endEdit(), org.jhotdraw.draw.tool.AbstractTool.fireToolDone(), and org.jhotdraw.draw.tool.CreationTool.isToolDoneAfterCreation().
setRubberbandColor()
void org.jhotdraw.draw.tool.TextAreaCreationTool.setRubberbandColor (Color c)
Sets the rubberband color for the tool. Setting this to null, disables the rubberband.
Parameters
c Rubberband color or null.
The documentation for this class was generated from the following file:
jhotdraw-core/src/main/java/org/jhotdraw/draw/tool/TextAreaCreationTool.java