jhotdraw: org.jhotdraw.draw.tool.TextCreationTool Class Reference
org.jhotdraw.draw.tool.TextCreationTool Class Reference
Public Member Functions
TextCreationTool (TextHolderFigure prototype)
TextCreationTool (TextHolderFigure prototype, Map< AttributeKey<?>, Object > attributes)
void deactivate (DrawingEditor editor)
void mousePressed (MouseEvent e)
void mouseDragged (java.awt.event.MouseEvent e)
void mouseReleased (MouseEvent evt)
void keyReleased (KeyEvent evt)
void actionPerformed (ActionEvent event)
boolean isEditing ()
void updateCursor (DrawingView view, Point p)
Public Member Functions inherited from org.jhotdraw.draw.tool.CreationTool
CreationTool (String prototypeClassName)
CreationTool (String prototypeClassName, Map< AttributeKey<?>, Object > attributes)
CreationTool (String prototypeClassName, Map< AttributeKey<?>, Object > attributes, String name)
CreationTool (Figure prototype)
CreationTool (Figure prototype, Map< AttributeKey<?>, Object > attributes)
CreationTool (Figure prototype, Map< AttributeKey<?>, Object > attributes, String name)
Figure getPrototype ()
void activate (DrawingEditor editor)
void mouseDragged (MouseEvent evt)
void setToolDoneAfterCreation (boolean newValue)
boolean isToolDoneAfterCreation ()
Public Member Functions inherited from org.jhotdraw.draw.tool.AbstractTool
AbstractTool ()
void addUndoableEditListener (UndoableEditListener l)
void removeUndoableEditListener (UndoableEditListener l)
boolean isActive ()
void setInputMap (InputMap newValue)
InputMap getInputMap ()
void setActionMap (ActionMap newValue)
ActionMap getActionMap ()
void editDelete ()
void editCut ()
void editCopy ()
void editDuplicate ()
void editPaste ()
void keyTyped (KeyEvent evt)
void keyPressed (KeyEvent evt)
void mouseClicked (MouseEvent evt)
void mouseEntered (MouseEvent evt)
void mouseExited (MouseEvent evt)
void mouseMoved (MouseEvent evt)
void addToolListener (ToolListener l)
void removeToolListener (ToolListener l)
void draw (Graphics2D g)
String getToolTipText (DrawingView view, MouseEvent evt)
boolean supportsHandleInteraction ()
Protected Member Functions
void beginEdit (TextHolderFigure textHolder)
void endEdit ()
void creationFinished (Figure createdFigure)
Protected Member Functions inherited from org.jhotdraw.draw.tool.CreationTool
Figure createFigure ()
Figure getCreatedFigure ()
Figure getAddedFigure ()
Protected Member Functions inherited from org.jhotdraw.draw.tool.AbstractTool
DrawingView getView ()
DrawingEditor getEditor ()
Drawing getDrawing ()
Point2D.Double viewToDrawing (Point p)
Point2D.Double constrainPoint (Point p, Figure... figure)
Point2D.Double constrainPoint (Point2D.Double p, Figure... figure)
InputMap createInputMap ()
ActionMap createActionMap ()
void fireToolStarted (DrawingView view)
void fireToolDone ()
void fireAreaInvalidated (Rectangle2D.Double r)
void fireAreaInvalidated (Rectangle invalidatedArea)
void maybeFireBoundsInvalidated (Rectangle invalidatedArea)
void fireBoundsInvalidated (Rectangle invalidatedArea)
Additional Inherited Members
Protected Attributes inherited from org.jhotdraw.draw.tool.CreationTool
Map< AttributeKey<?>, Object > prototypeAttributes
String presentationName
Dimension minimalSizeTreshold = new Dimension(2, 2)
Dimension minimalSize = new Dimension(40, 40)
Figure prototype
Figure createdFigure
Protected Attributes inherited from org.jhotdraw.draw.tool.AbstractTool
boolean isWorking
DrawingEditor editor
Point anchor = new Point()
EventListenerList listenerList = new EventListenerList()
Detailed Description
A tool to create figures which implement the
TextHolderFigure
interface, such as
TextFigure
. The figure to be created is specified by a prototype.
To create a figure using this tool, the user does the following mouse gestures on a DrawingView:
Press the mouse button over an area on the DrawingView on which there isn't a text figure present. This defines the location of the figure.
When the user has performed this mouse gesture, the TextCreationTool overlays a text field over the drawing where the user can enter the text for the Figure.
Design Patterns
Framework
The text creation and editing tools and the
TextHolderFigure
interface define together the contracts of a smaller framework inside of the JHotDraw framework for structured drawing editors.
Contract: TextHolderFigure, TextCreationTool, TextAreaCreationTool, TextEditingTool, TextAreaEditingTool, FloatingTextField, FloatingTextArea.
Prototype
The text creation tools create new figures by cloning a prototype
TextHolderFigure
object.
Prototype: TextHolderFigure; Client: TextCreationTool, TextAreaCreationTool.
Author
Werner Randelshofer
Version
$Id$
Constructor & Destructor Documentation
TextCreationTool() [1/2]
org.jhotdraw.draw.tool.TextCreationTool.TextCreationTool (TextHolderFigure prototype)
Creates a new instance.
References org.jhotdraw.draw.tool.CreationTool.prototype.
TextCreationTool() [2/2]
org.jhotdraw.draw.tool.TextCreationTool.TextCreationTool (TextHolderFigure prototype, Map< AttributeKey<?>, Object > attributes)
Creates a new instance.
References org.jhotdraw.draw.tool.CreationTool.prototype.
Member Function Documentation
actionPerformed()
void org.jhotdraw.draw.tool.TextCreationTool.actionPerformed (ActionEvent event)
References org.jhotdraw.draw.tool.TextCreationTool.endEdit(), org.jhotdraw.draw.tool.AbstractTool.fireToolDone(), and org.jhotdraw.draw.tool.CreationTool.isToolDoneAfterCreation().
beginEdit()
void org.jhotdraw.draw.tool.TextCreationTool.beginEdit (TextHolderFigure textHolder) protected
References org.jhotdraw.draw.text.FloatingTextField.addActionListener(), org.jhotdraw.draw.text.FloatingTextField.createOverlay(), org.jhotdraw.draw.tool.TextCreationTool.endEdit(), org.jhotdraw.draw.tool.AbstractTool.getView(), and org.jhotdraw.draw.text.FloatingTextField.requestFocus().
Referenced by org.jhotdraw.draw.tool.TextCreationTool.creationFinished(), and org.jhotdraw.draw.tool.TextCreationTool.mousePressed().
creationFinished()
void org.jhotdraw.draw.tool.TextCreationTool.creationFinished (Figure createdFigure) protected
This method allows subclasses to do perform additonal user interactions after the new figure has been created. The implementation of this class just invokes fireToolDone.
Reimplemented from org.jhotdraw.draw.tool.CreationTool.
References org.jhotdraw.draw.tool.TextCreationTool.beginEdit(), org.jhotdraw.draw.tool.CreationTool.createdFigure, org.jhotdraw.draw.tool.AbstractTool.getView(), and org.jhotdraw.draw.tool.TextCreationTool.updateCursor().
deactivate()
void org.jhotdraw.draw.tool.TextCreationTool.deactivate (DrawingEditor editor)
Deactivates the tool. This method is called whenever the user switches to another tool.
Reimplemented from org.jhotdraw.draw.tool.CreationTool.
References org.jhotdraw.draw.tool.AbstractTool.editor, and org.jhotdraw.draw.tool.TextCreationTool.endEdit().
endEdit()
void org.jhotdraw.draw.tool.TextCreationTool.endEdit () protected
References org.jhotdraw.draw.figure.Figure.changed(), org.jhotdraw.draw.tool.CreationTool.createdFigure, org.jhotdraw.draw.text.FloatingTextField.endOverlay(), org.jhotdraw.draw.Drawing.fireUndoableEditHappened(), org.jhotdraw.draw.tool.CreationTool.getAddedFigure(), org.jhotdraw.draw.tool.AbstractTool.getDrawing(), org.jhotdraw.draw.figure.TextHolderFigure.getText(), org.jhotdraw.draw.text.FloatingTextField.getText(), org.jhotdraw.draw.Drawing.remove(), org.jhotdraw.draw.figure.TextHolderFigure.setText(), and org.jhotdraw.draw.figure.Figure.willChange().
Referenced by org.jhotdraw.draw.tool.TextCreationTool.actionPerformed(), org.jhotdraw.draw.tool.TextCreationTool.beginEdit(), org.jhotdraw.draw.tool.TextCreationTool.deactivate(), and org.jhotdraw.draw.tool.TextCreationTool.mousePressed().
isEditing()
boolean org.jhotdraw.draw.tool.TextCreationTool.isEditing ()
Referenced by org.jhotdraw.draw.tool.TextCreationTool.updateCursor().
keyReleased()
void org.jhotdraw.draw.tool.TextCreationTool.keyReleased (KeyEvent evt)
Reimplemented from org.jhotdraw.draw.tool.AbstractTool.
References org.jhotdraw.draw.tool.AbstractTool.fireToolDone(), and org.jhotdraw.draw.tool.CreationTool.isToolDoneAfterCreation().
mouseDragged()
void org.jhotdraw.draw.tool.TextCreationTool.mouseDragged (java.awt.event.MouseEvent e)
mousePressed()
void org.jhotdraw.draw.tool.TextCreationTool.mousePressed (MouseEvent e)
Creates a new figure at the location where the mouse was pressed.
Reimplemented from org.jhotdraw.draw.tool.CreationTool.
References org.jhotdraw.draw.DrawingView.addToSelection(), org.jhotdraw.draw.tool.TextCreationTool.beginEdit(), org.jhotdraw.draw.DrawingView.clearSelection(), org.jhotdraw.draw.tool.TextCreationTool.endEdit(), org.jhotdraw.draw.tool.AbstractTool.fireToolDone(), org.jhotdraw.draw.tool.CreationTool.getCreatedFigure(), org.jhotdraw.draw.tool.AbstractTool.getView(), org.jhotdraw.draw.tool.CreationTool.isToolDoneAfterCreation(), and org.jhotdraw.draw.tool.TextCreationTool.updateCursor().
mouseReleased()
void org.jhotdraw.draw.tool.TextCreationTool.mouseReleased (MouseEvent evt)
Reimplemented from org.jhotdraw.draw.tool.CreationTool.
updateCursor()
void org.jhotdraw.draw.tool.TextCreationTool.updateCursor (DrawingView view, Point p)
Reimplemented from org.jhotdraw.draw.tool.CreationTool.
References org.jhotdraw.draw.tool.TextCreationTool.isEditing(), org.jhotdraw.draw.DrawingView.isEnabled(), and org.jhotdraw.draw.DrawingView.setCursor().
Referenced by org.jhotdraw.draw.tool.TextCreationTool.creationFinished(), and org.jhotdraw.draw.tool.TextCreationTool.mousePressed().
The documentation for this class was generated from the following file:
jhotdraw-core/src/main/java/org/jhotdraw/draw/tool/TextCreationTool.java