jhotdraw: org.jhotdraw.draw.handle.BezierControlPointHandle Class Reference
org.jhotdraw.draw.handle.BezierControlPointHandle Class Reference
Public Member Functions
BezierControlPointHandle (BezierFigure owner, int index, int coord)
BezierControlPointHandle (BezierFigure owner, int index, int coord, Figure transformOwner)
void dispose ()
void draw (Graphics2D g)
void trackStart (Point anchor, int modifiersEx)
void trackStep (Point anchor, Point lead, int modifiersEx)
void trackEnd (Point anchor, Point lead, int modifiersEx)
boolean isCombinableWith (Handle h)
String getToolTipText (Point p)
BezierFigure getOwner ()
void keyPressed (KeyEvent evt)
Public Member Functions inherited from org.jhotdraw.draw.handle.AbstractHandle
AbstractHandle (Figure owner)
void addHandleListener (HandleListener l)
void removeHandleListener (HandleListener l)
void setView (DrawingView view)
DrawingView getView ()
DrawingEditor getEditor ()
boolean contains (Point p)
void invalidate ()
void areaInvalidated (FigureEvent evt)
void figureAdded (FigureEvent e)
void figureRemoved (FigureEvent e)
void figureRequestRemove (FigureEvent e)
void figureChanged (FigureEvent evt)
Cursor getCursor ()
void keyTyped (KeyEvent evt)
void keyReleased (KeyEvent evt)
final Rectangle getBounds ()
Rectangle getDrawingArea ()
void trackDoubleClick (Point p, int modifiersEx)
void attributeChanged (FigureEvent e)
void viewTransformChanged ()
Collection< Handle > createSecondaryHandles ()
void setToolTipText (String newValue)
void figureHandlesChanged (FigureEvent e)
Protected Member Functions
BezierFigure getBezierFigure ()
Figure getTransformOwner ()
Point getLocation ()
BezierPath.Node getBezierNode ()
Rectangle basicGetBounds ()
Protected Member Functions inherited from org.jhotdraw.draw.handle.AbstractHandle
int getHandlesize ()
void fireAreaInvalidated (Rectangle invalidatedArea)
void fireUndoableEditHappened (UndoableEdit edit)
void fireHandleRequestRemove (Rectangle invalidatedArea)
void fireHandleRequestSecondaryHandles ()
void drawCircle (Graphics2D g, Color fill, Color stroke)
void drawRectangle (Graphics2D g, Color fill, Color stroke)
void drawDiamond (Graphics2D g, Color fill, Color stroke)
void updateBounds ()
Protected Attributes
int index
Protected Attributes inherited from org.jhotdraw.draw.handle.AbstractHandle
DrawingView view
EventListenerList listenerList = new EventListenerList()
Detailed Description
A Handle which allows to interactively change a control point of a bezier path.
Author
Werner Randelshofer
Version
$Id$
Constructor & Destructor Documentation
BezierControlPointHandle() [1/2]
org.jhotdraw.draw.handle.BezierControlPointHandle.BezierControlPointHandle (BezierFigure owner, int index, int coord)
Creates a new instance.
References org.jhotdraw.draw.handle.BezierControlPointHandle.index.
Referenced by org.jhotdraw.draw.handle.BezierControlPointHandle.isCombinableWith().
BezierControlPointHandle() [2/2]
org.jhotdraw.draw.handle.BezierControlPointHandle.BezierControlPointHandle (BezierFigure owner, int index, int coord, Figure transformOwner)
References org.jhotdraw.draw.figure.Figure.addFigureListener(), and org.jhotdraw.draw.handle.BezierControlPointHandle.index.
Member Function Documentation
basicGetBounds()
Rectangle org.jhotdraw.draw.handle.BezierControlPointHandle.basicGetBounds () protected
Reimplemented from org.jhotdraw.draw.handle.AbstractHandle.
References org.jhotdraw.draw.handle.AbstractHandle.getHandlesize(), and org.jhotdraw.draw.handle.BezierControlPointHandle.getLocation().
dispose()
void org.jhotdraw.draw.handle.BezierControlPointHandle.dispose ()
Disposes the resources acquired by the handler.
Reimplemented from org.jhotdraw.draw.handle.AbstractHandle.
References org.jhotdraw.draw.figure.Figure.removeFigureListener().
draw()
void org.jhotdraw.draw.handle.BezierControlPointHandle.draw (Graphics2D g)
Draws this handle.
Reimplemented from org.jhotdraw.draw.handle.AbstractHandle.
References org.jhotdraw.draw.handle.HandleAttributeKeys.BEZIER_CONTROL_POINT_HANDLE_FILL_COLOR, org.jhotdraw.draw.handle.HandleAttributeKeys.BEZIER_CONTROL_POINT_HANDLE_FILL_COLOR_DISABLED, org.jhotdraw.draw.handle.HandleAttributeKeys.BEZIER_CONTROL_POINT_HANDLE_STROKE_COLOR, org.jhotdraw.draw.handle.HandleAttributeKeys.BEZIER_CONTROL_POINT_HANDLE_STROKE_COLOR_DISABLED, org.jhotdraw.draw.handle.HandleAttributeKeys.BEZIER_TANGENT_COLOR_1, org.jhotdraw.draw.handle.HandleAttributeKeys.BEZIER_TANGENT_COLOR_1_DISABLED, org.jhotdraw.draw.handle.HandleAttributeKeys.BEZIER_TANGENT_COLOR_2, org.jhotdraw.draw.handle.HandleAttributeKeys.BEZIER_TANGENT_COLOR_2_DISABLED, org.jhotdraw.draw.handle.HandleAttributeKeys.BEZIER_TANGENT_STROKE_1, org.jhotdraw.draw.handle.HandleAttributeKeys.BEZIER_TANGENT_STROKE_1_DISABLED, org.jhotdraw.draw.handle.HandleAttributeKeys.BEZIER_TANGENT_STROKE_2, org.jhotdraw.draw.handle.HandleAttributeKeys.BEZIER_TANGENT_STROKE_2_DISABLED, org.jhotdraw.draw.handle.AbstractHandle.drawCircle(), org.jhotdraw.draw.DrawingView.drawingToView(), org.jhotdraw.draw.figure.Figure.get(), org.jhotdraw.draw.handle.BezierControlPointHandle.getBezierFigure(), org.jhotdraw.draw.handle.AbstractHandle.getEditor(), org.jhotdraw.draw.DrawingEditor.getHandleAttribute(), org.jhotdraw.draw.figure.BezierFigure.getNode(), org.jhotdraw.draw.figure.BezierFigure.getNodeCount(), org.jhotdraw.draw.handle.BezierControlPointHandle.getTransformOwner(), org.jhotdraw.draw.handle.BezierControlPointHandle.index, org.jhotdraw.draw.figure.BezierFigure.isClosed(), and org.jhotdraw.draw.handle.AbstractHandle.view.
getBezierFigure()
BezierFigure org.jhotdraw.draw.handle.BezierControlPointHandle.getBezierFigure () protected
References org.jhotdraw.draw.handle.BezierControlPointHandle.getOwner().
Referenced by org.jhotdraw.draw.handle.BezierControlPointHandle.draw(), org.jhotdraw.draw.handle.BezierControlPointHandle.getBezierNode(), org.jhotdraw.draw.handle.BezierControlPointHandle.getLocation(), org.jhotdraw.draw.handle.BezierControlPointHandle.isCombinableWith(), org.jhotdraw.draw.handle.BezierControlPointHandle.trackEnd(), and org.jhotdraw.draw.handle.BezierControlPointHandle.trackStep().
getBezierNode()
BezierPath.Node org.jhotdraw.draw.handle.BezierControlPointHandle.getBezierNode () protected
References org.jhotdraw.draw.handle.BezierControlPointHandle.getBezierFigure(), org.jhotdraw.draw.figure.BezierFigure.getNode(), org.jhotdraw.draw.figure.BezierFigure.getNodeCount(), and org.jhotdraw.draw.handle.BezierControlPointHandle.index.
Referenced by org.jhotdraw.draw.handle.BezierControlPointHandle.getToolTipText().
getLocation()
Point org.jhotdraw.draw.handle.BezierControlPointHandle.getLocation () protected
References org.jhotdraw.draw.DrawingView.drawingToView(), org.jhotdraw.draw.figure.Figure.get(), org.jhotdraw.draw.handle.BezierControlPointHandle.getBezierFigure(), org.jhotdraw.draw.figure.BezierFigure.getPoint(), org.jhotdraw.draw.handle.BezierControlPointHandle.getTransformOwner(), org.jhotdraw.draw.handle.BezierControlPointHandle.index, and org.jhotdraw.draw.handle.AbstractHandle.view.
Referenced by org.jhotdraw.draw.handle.BezierControlPointHandle.basicGetBounds().
getOwner()
BezierFigure org.jhotdraw.draw.handle.BezierControlPointHandle.getOwner ()
Returns the owner of this handle.
Reimplemented from org.jhotdraw.draw.handle.AbstractHandle.
Referenced by org.jhotdraw.draw.handle.BezierControlPointHandle.getBezierFigure(), org.jhotdraw.draw.handle.BezierControlPointHandle.keyPressed(), and org.jhotdraw.draw.handle.BezierControlPointHandle.trackStart().
getToolTipText()
String org.jhotdraw.draw.handle.BezierControlPointHandle.getToolTipText (Point p)
Returns a tooltip for the specified location. By default, AbstractHandle returns null.
Reimplemented from org.jhotdraw.draw.handle.AbstractHandle.
References org.jhotdraw.draw.handle.BezierControlPointHandle.getBezierNode().
getTransformOwner()
Figure org.jhotdraw.draw.handle.BezierControlPointHandle.getTransformOwner () protected
Referenced by org.jhotdraw.draw.handle.BezierControlPointHandle.draw(), org.jhotdraw.draw.handle.BezierControlPointHandle.getLocation(), and org.jhotdraw.draw.handle.BezierControlPointHandle.trackStep().
isCombinableWith()
boolean org.jhotdraw.draw.handle.BezierControlPointHandle.isCombinableWith (Handle handle)
Returns true, if the given handle is an instance of the same class or of a subclass of this handle,.
Reimplemented from org.jhotdraw.draw.handle.AbstractHandle.
References org.jhotdraw.draw.handle.BezierControlPointHandle.BezierControlPointHandle(), org.jhotdraw.draw.handle.BezierControlPointHandle.getBezierFigure(), org.jhotdraw.draw.figure.BezierFigure.getNodeCount(), and org.jhotdraw.draw.handle.BezierControlPointHandle.index.
keyPressed()
void org.jhotdraw.draw.handle.BezierControlPointHandle.keyPressed (KeyEvent evt)
Reimplemented from org.jhotdraw.draw.handle.AbstractHandle.
References org.jhotdraw.draw.figure.AbstractFigure.changed(), org.jhotdraw.draw.Drawing.fireUndoableEditHappened(), org.jhotdraw.draw.DrawingView.getDrawing(), org.jhotdraw.draw.figure.BezierFigure.getNode(), org.jhotdraw.draw.handle.BezierControlPointHandle.getOwner(), org.jhotdraw.draw.handle.BezierControlPointHandle.index, org.jhotdraw.draw.figure.BezierFigure.setPoint(), org.jhotdraw.draw.handle.AbstractHandle.view, and org.jhotdraw.draw.figure.AbstractFigure.willChange().
trackEnd()
void org.jhotdraw.draw.handle.BezierControlPointHandle.trackEnd (Point anchor, Point lead, int modifiersEx)
Tracks the end of the interaction.
Parameters
anchor the position where the interaction started
lead the current position
Implements org.jhotdraw.draw.handle.Handle.
References org.jhotdraw.draw.figure.AbstractFigure.changed(), org.jhotdraw.draw.handle.AbstractHandle.fireHandleRequestSecondaryHandles(), org.jhotdraw.draw.Drawing.fireUndoableEditHappened(), org.jhotdraw.draw.handle.BezierControlPointHandle.getBezierFigure(), org.jhotdraw.draw.DrawingView.getDrawing(), org.jhotdraw.draw.figure.BezierFigure.getNode(), org.jhotdraw.draw.figure.BezierFigure.getPoint(), org.jhotdraw.draw.handle.BezierControlPointHandle.index, org.jhotdraw.draw.event.BezierNodeEdit.redo(), org.jhotdraw.draw.figure.BezierFigure.setNode(), org.jhotdraw.draw.handle.AbstractHandle.view, and org.jhotdraw.draw.figure.AbstractFigure.willChange().
trackStart()
void org.jhotdraw.draw.handle.BezierControlPointHandle.trackStart (Point anchor, int modifiersEx)
Tracks the start of the interaction. The default implementation does nothing.
Parameters
anchor the position where the interaction started
Implements org.jhotdraw.draw.handle.Handle.
References org.jhotdraw.draw.Drawing.fireUndoableEditHappened(), org.jhotdraw.draw.DrawingView.getDrawing(), org.jhotdraw.draw.figure.BezierFigure.getNode(), org.jhotdraw.draw.handle.BezierControlPointHandle.getOwner(), org.jhotdraw.draw.handle.BezierControlPointHandle.index, and org.jhotdraw.draw.handle.AbstractHandle.view.
trackStep()
void org.jhotdraw.draw.handle.BezierControlPointHandle.trackStep (Point anchor, Point lead, int modifiersEx)
Tracks a step of the interaction.
Parameters
anchor the position where the interaction started
lead the current position
Implements org.jhotdraw.draw.handle.Handle.
References org.jhotdraw.draw.figure.AbstractFigure.changed(), org.jhotdraw.draw.Constrainer.constrainPoint(), org.jhotdraw.draw.figure.Figure.get(), org.jhotdraw.draw.handle.BezierControlPointHandle.getBezierFigure(), org.jhotdraw.draw.DrawingView.getConstrainer(), org.jhotdraw.draw.figure.BezierFigure.getNode(), org.jhotdraw.draw.handle.BezierControlPointHandle.getTransformOwner(), org.jhotdraw.draw.handle.BezierControlPointHandle.index, org.jhotdraw.draw.figure.BezierFigure.setPoint(), org.jhotdraw.draw.handle.AbstractHandle.view, org.jhotdraw.draw.DrawingView.viewToDrawing(), and org.jhotdraw.draw.figure.AbstractFigure.willChange().
Member Data Documentation
index
int org.jhotdraw.draw.handle.BezierControlPointHandle.index protected
Referenced by org.jhotdraw.draw.handle.BezierControlPointHandle.BezierControlPointHandle(), org.jhotdraw.draw.handle.BezierControlPointHandle.draw(), org.jhotdraw.draw.handle.BezierControlPointHandle.getBezierNode(), org.jhotdraw.draw.handle.BezierControlPointHandle.getLocation(), org.jhotdraw.draw.handle.BezierControlPointHandle.isCombinableWith(), org.jhotdraw.draw.handle.BezierControlPointHandle.keyPressed(), org.jhotdraw.draw.handle.BezierControlPointHandle.trackEnd(), org.jhotdraw.draw.handle.BezierControlPointHandle.trackStart(), and org.jhotdraw.draw.handle.BezierControlPointHandle.trackStep().
The documentation for this class was generated from the following file:
jhotdraw-core/src/main/java/org/jhotdraw/draw/handle/BezierControlPointHandle.java