jhotdraw: org.jhotdraw.draw.tool.TextEditingTool Class Reference
org.jhotdraw.draw.tool.TextEditingTool Class Reference
Public Member Functions
TextEditingTool (TextHolderFigure typingTarget)
void deactivate (DrawingEditor editor)
void mousePressed (MouseEvent e)
void mouseReleased (MouseEvent evt)
void keyReleased (KeyEvent evt)
void actionPerformed (ActionEvent event)
boolean isEditing ()
void updateCursor (DrawingView view, Point p)
void mouseDragged (MouseEvent e)
Public Member Functions inherited from org.jhotdraw.draw.tool.AbstractTool
AbstractTool ()
void addUndoableEditListener (UndoableEditListener l)
void removeUndoableEditListener (UndoableEditListener l)
void activate (DrawingEditor editor)
boolean isActive ()
void setInputMap (InputMap newValue)
InputMap getInputMap ()
void setActionMap (ActionMap newValue)
ActionMap getActionMap ()
void editDelete ()
void editCut ()
void editCopy ()
void editDuplicate ()
void editPaste ()
void keyTyped (KeyEvent evt)
void keyPressed (KeyEvent evt)
void mouseClicked (MouseEvent evt)
void mouseEntered (MouseEvent evt)
void mouseExited (MouseEvent evt)
void mouseMoved (MouseEvent evt)
void addToolListener (ToolListener l)
void removeToolListener (ToolListener l)
void draw (Graphics2D g)
String getToolTipText (DrawingView view, MouseEvent evt)
boolean supportsHandleInteraction ()
Protected Member Functions
void beginEdit (TextHolderFigure textHolder)
void endEdit ()
Protected Member Functions inherited from org.jhotdraw.draw.tool.AbstractTool
DrawingView getView ()
DrawingEditor getEditor ()
Drawing getDrawing ()
Point2D.Double viewToDrawing (Point p)
Point2D.Double constrainPoint (Point p, Figure... figure)
Point2D.Double constrainPoint (Point2D.Double p, Figure... figure)
InputMap createInputMap ()
ActionMap createActionMap ()
void fireToolStarted (DrawingView view)
void fireToolDone ()
void fireAreaInvalidated (Rectangle2D.Double r)
void fireAreaInvalidated (Rectangle invalidatedArea)
void maybeFireBoundsInvalidated (Rectangle invalidatedArea)
void fireBoundsInvalidated (Rectangle invalidatedArea)
Additional Inherited Members
Protected Attributes inherited from org.jhotdraw.draw.tool.AbstractTool
boolean isWorking
DrawingEditor editor
Point anchor = new Point()
EventListenerList listenerList = new EventListenerList()
Detailed Description
A tool to edit figures which implement the
TextHolderFigure
interface, such as
TextFigure
.
Design Patterns
Framework
The text creation and editing tools and the
TextHolderFigure
interface define together the contracts of a smaller framework inside of the JHotDraw framework for structured drawing editors.
Contract: TextHolderFigure, TextCreationTool, TextAreaCreationTool, TextEditingTool, TextAreaEditingTool, FloatingTextField, FloatingTextArea.
Prototype
The text creation tools create new figures by cloning a prototype
TextHolderFigure
object.
Prototype: TextHolderFigure; Client: TextCreationTool, TextAreaCreationTool.
Author
Werner Randelshofer
Version
$Id$
Constructor & Destructor Documentation
TextEditingTool()
org.jhotdraw.draw.tool.TextEditingTool.TextEditingTool (TextHolderFigure typingTarget)
Creates a new instance.
Member Function Documentation
actionPerformed()
void org.jhotdraw.draw.tool.TextEditingTool.actionPerformed (ActionEvent event)
References org.jhotdraw.draw.tool.TextEditingTool.endEdit(), and org.jhotdraw.draw.tool.AbstractTool.fireToolDone().
beginEdit()
void org.jhotdraw.draw.tool.TextEditingTool.beginEdit (TextHolderFigure textHolder) protected
References org.jhotdraw.draw.text.FloatingTextField.addActionListener(), org.jhotdraw.draw.text.FloatingTextField.createOverlay(), org.jhotdraw.draw.tool.TextEditingTool.endEdit(), org.jhotdraw.draw.tool.AbstractTool.getView(), and org.jhotdraw.draw.text.FloatingTextField.requestFocus().
Referenced by org.jhotdraw.draw.tool.TextEditingTool.mousePressed().
deactivate()
void org.jhotdraw.draw.tool.TextEditingTool.deactivate (DrawingEditor editor)
Deactivates the tool. This method is called whenever the user switches to another tool.
Reimplemented from org.jhotdraw.draw.tool.AbstractTool.
References org.jhotdraw.draw.tool.AbstractTool.editor, and org.jhotdraw.draw.tool.TextEditingTool.endEdit().
endEdit()
void org.jhotdraw.draw.tool.TextEditingTool.endEdit () protected
References org.jhotdraw.draw.figure.Figure.changed(), org.jhotdraw.draw.text.FloatingTextField.endOverlay(), org.jhotdraw.draw.Drawing.fireUndoableEditHappened(), org.jhotdraw.draw.tool.AbstractTool.getDrawing(), org.jhotdraw.draw.figure.TextHolderFigure.getText(), org.jhotdraw.draw.text.FloatingTextField.getText(), org.jhotdraw.draw.figure.TextHolderFigure.setText(), and org.jhotdraw.draw.figure.Figure.willChange().
Referenced by org.jhotdraw.draw.tool.TextEditingTool.actionPerformed(), org.jhotdraw.draw.tool.TextEditingTool.beginEdit(), and org.jhotdraw.draw.tool.TextEditingTool.deactivate().
isEditing()
boolean org.jhotdraw.draw.tool.TextEditingTool.isEditing ()
Referenced by org.jhotdraw.draw.tool.TextEditingTool.updateCursor().
keyReleased()
void org.jhotdraw.draw.tool.TextEditingTool.keyReleased (KeyEvent evt)
Reimplemented from org.jhotdraw.draw.tool.AbstractTool.
References org.jhotdraw.draw.tool.AbstractTool.fireToolDone().
mouseDragged()
void org.jhotdraw.draw.tool.TextEditingTool.mouseDragged (MouseEvent e)
mousePressed()
void org.jhotdraw.draw.tool.TextEditingTool.mousePressed (MouseEvent e)
If the pressed figure is a TextHolderFigure it can be edited.
Reimplemented from org.jhotdraw.draw.tool.AbstractTool.
References org.jhotdraw.draw.tool.TextEditingTool.beginEdit(), org.jhotdraw.draw.tool.AbstractTool.getView(), and org.jhotdraw.draw.tool.TextEditingTool.updateCursor().
mouseReleased()
void org.jhotdraw.draw.tool.TextEditingTool.mouseReleased (MouseEvent evt)
Reimplemented from org.jhotdraw.draw.tool.AbstractTool.
updateCursor()
void org.jhotdraw.draw.tool.TextEditingTool.updateCursor (DrawingView view, Point p)
Reimplemented from org.jhotdraw.draw.tool.AbstractTool.
References org.jhotdraw.draw.tool.TextEditingTool.isEditing(), org.jhotdraw.draw.DrawingView.isEnabled(), and org.jhotdraw.draw.DrawingView.setCursor().
Referenced by org.jhotdraw.draw.tool.TextEditingTool.mousePressed().
The documentation for this class was generated from the following file:
jhotdraw-core/src/main/java/org/jhotdraw/draw/tool/TextEditingTool.java