jhotdraw: org.jhotdraw.draw.event.FigureEvent Class Reference
org.jhotdraw.draw.event.FigureEvent Class Reference
Public Member Functions
FigureEvent (Figure source, Rectangle2D.Double invalidatedArea)
FigureEvent (Figure source, AttributeKey<?> attribute, Object oldValue, Object newValue)
Figure getFigure ()
Rectangle2D.Double getInvalidatedArea ()
AttributeKey<?> getAttribute ()
Object getOldValue ()
Object getNewValue ()
Detailed Description
An
EventObject
sent to FigureListeners.
Design Patterns
Observer
State changes of figures can be observed by other objects. Specifically
CompositeFigure
observes area invalidations and remove requests of its child figures. DrawingView also observes area invalidations of its drawing object. Subject: Figure; Observer: FigureListener; Event: FigureEvent; Concrete Observer: org.jhotdraw.draw.CompositeFigure, DrawingView.
Author
Werner Randelshofer
Version
$Id$
Constructor & Destructor Documentation
FigureEvent() [1/2]
org.jhotdraw.draw.event.FigureEvent.FigureEvent (Figure source, Rectangle2D.Double invalidatedArea)
Constructs an event for the given source Figure.
Parameters
invalidatedArea The bounds of the invalidated area on the drawing.
FigureEvent() [2/2]
org.jhotdraw.draw.event.FigureEvent.FigureEvent (Figure source, AttributeKey<?> attribute, Object oldValue, Object newValue)
Constructs an event for the given source Figure.
Member Function Documentation
getAttribute()
AttributeKey<?> org.jhotdraw.draw.event.FigureEvent.getAttribute ()
Referenced by org.jhotdraw.draw.event.AbstractAttributeEditorHandler< T >.EventHandler.attributeChanged().
getFigure()
Figure org.jhotdraw.draw.event.FigureEvent.getFigure ()
Gets the changed figure
Referenced by org.jhotdraw.draw.figure.QuadTreeCompositeFigure.FigureHandler.figureChanged(), org.jhotdraw.draw.QuadTreeDrawing.QuadTreeEventHandler.figureChanged(), org.jhotdraw.draw.figure.LabelFigure.figureRemoved(), org.jhotdraw.draw.figure.AbstractCompositeFigure.EventHandler.figureRequestRemove(), and org.jhotdraw.draw.figure.QuadTreeCompositeFigure.FigureHandler.figureRequestRemove().
getInvalidatedArea()
Rectangle2D.Double org.jhotdraw.draw.event.FigureEvent.getInvalidatedArea ()
Gets the bounds of the invalidated area on the drawing.
Referenced by org.jhotdraw.draw.figure.QuadTreeCompositeFigure.FigureHandler.areaInvalidated(), org.jhotdraw.draw.figure.AbstractCompositeFigure.EventHandler.figureChanged(), and org.jhotdraw.draw.figure.QuadTreeCompositeFigure.FigureHandler.figureChanged().
getNewValue()
Object org.jhotdraw.draw.event.FigureEvent.getNewValue ()
getOldValue()
Object org.jhotdraw.draw.event.FigureEvent.getOldValue ()
The documentation for this class was generated from the following file:
jhotdraw-core/src/main/java/org/jhotdraw/draw/event/FigureEvent.java