jhotdraw: org.jhotdraw.draw.handle.MoveHandle Class Reference
org.jhotdraw.draw.handle.MoveHandle Class Reference
Public Member Functions
MoveHandle (Figure owner, Locator locator)
void draw (Graphics2D g)
Cursor getCursor ()
void trackStart (Point anchor, int modifiersEx)
void trackStep (Point anchor, Point lead, int modifiersEx)
void trackEnd (Point anchor, Point lead, int modifiersEx)
void keyPressed (KeyEvent evt)
Public Member Functions inherited from org.jhotdraw.draw.handle.LocatorHandle
LocatorHandle (Figure owner, Locator l)
Point2D.Double getLocationOnDrawing ()
Point getLocation ()
Public Member Functions inherited from org.jhotdraw.draw.handle.AbstractHandle
AbstractHandle (Figure owner)
void addHandleListener (HandleListener l)
void removeHandleListener (HandleListener l)
Figure getOwner ()
void setView (DrawingView view)
DrawingView getView ()
DrawingEditor getEditor ()
boolean contains (Point p)
void invalidate ()
void dispose ()
void areaInvalidated (FigureEvent evt)
void figureAdded (FigureEvent e)
void figureRemoved (FigureEvent e)
void figureRequestRemove (FigureEvent e)
void figureChanged (FigureEvent evt)
boolean isCombinableWith (Handle handle)
void keyTyped (KeyEvent evt)
void keyReleased (KeyEvent evt)
final Rectangle getBounds ()
Rectangle getDrawingArea ()
void trackDoubleClick (Point p, int modifiersEx)
void attributeChanged (FigureEvent e)
void viewTransformChanged ()
Collection< Handle > createSecondaryHandles ()
String getToolTipText (Point p)
void setToolTipText (String newValue)
void figureHandlesChanged (FigureEvent e)
Static Public Member Functions
static void addMoveHandles (Figure f, Collection< Handle > handles)
static Handle south (Figure owner)
static Handle southEast (Figure owner)
static Handle southWest (Figure owner)
static Handle north (Figure owner)
static Handle northEast (Figure owner)
static Handle northWest (Figure owner)
static Handle east (Figure owner)
static Handle west (Figure owner)
Additional Inherited Members
Protected Member Functions inherited from org.jhotdraw.draw.handle.LocatorHandle
Rectangle basicGetBounds ()
Protected Member Functions inherited from org.jhotdraw.draw.handle.AbstractHandle
int getHandlesize ()
void fireAreaInvalidated (Rectangle invalidatedArea)
void fireUndoableEditHappened (UndoableEdit edit)
void fireHandleRequestRemove (Rectangle invalidatedArea)
void fireHandleRequestSecondaryHandles ()
void drawCircle (Graphics2D g, Color fill, Color stroke)
void drawRectangle (Graphics2D g, Color fill, Color stroke)
void drawDiamond (Graphics2D g, Color fill, Color stroke)
void updateBounds ()
Protected Attributes inherited from org.jhotdraw.draw.handle.AbstractHandle
DrawingView view
EventListenerList listenerList = new EventListenerList()
Detailed Description
A handle that changes the location of the owning figure, if the figure is transformable.
Author
Werner Randelshofer
Version
$Id$
Constructor & Destructor Documentation
MoveHandle()
org.jhotdraw.draw.handle.MoveHandle.MoveHandle (Figure owner, Locator locator)
Creates a new instance.
Referenced by org.jhotdraw.draw.handle.MoveHandle.east(), org.jhotdraw.draw.handle.MoveHandle.north(), org.jhotdraw.draw.handle.MoveHandle.northEast(), org.jhotdraw.draw.handle.MoveHandle.northWest(), org.jhotdraw.draw.handle.MoveHandle.south(), org.jhotdraw.draw.handle.MoveHandle.southEast(), org.jhotdraw.draw.handle.MoveHandle.southWest(), and org.jhotdraw.draw.handle.MoveHandle.west().
Member Function Documentation
addMoveHandles()
static void org.jhotdraw.draw.handle.MoveHandle.addMoveHandles (Figure f, Collection< Handle > handles) static
Creates handles for each corner of a figure and adds them to the provided collection.
References org.jhotdraw.draw.handle.MoveHandle.northEast(), org.jhotdraw.draw.handle.MoveHandle.northWest(), org.jhotdraw.draw.handle.MoveHandle.southEast(), and org.jhotdraw.draw.handle.MoveHandle.southWest().
Referenced by org.jhotdraw.draw.GraphicalCompositeFigure.createHandles().
draw()
void org.jhotdraw.draw.handle.MoveHandle.draw (Graphics2D g)
Draws this handle.
If the figure is transformable, the handle is drawn as a filled rectangle. If the figure is not transformable, the handle is drawn as an unfilled rectangle.
Reimplemented from org.jhotdraw.draw.handle.AbstractHandle.
References org.jhotdraw.draw.handle.AbstractHandle.drawRectangle(), org.jhotdraw.draw.handle.AbstractHandle.getEditor(), org.jhotdraw.draw.handle.AbstractHandle.getOwner(), org.jhotdraw.draw.handle.HandleAttributeKeys.MOVE_HANDLE_FILL_COLOR, org.jhotdraw.draw.handle.HandleAttributeKeys.MOVE_HANDLE_STROKE_COLOR, org.jhotdraw.draw.handle.HandleAttributeKeys.NULL_HANDLE_FILL_COLOR, and org.jhotdraw.draw.handle.HandleAttributeKeys.NULL_HANDLE_STROKE_COLOR.
east()
static Handle org.jhotdraw.draw.handle.MoveHandle.east (Figure owner) static
References org.jhotdraw.draw.locator.RelativeLocator.east(), and org.jhotdraw.draw.handle.MoveHandle.MoveHandle().
getCursor()
Cursor org.jhotdraw.draw.handle.MoveHandle.getCursor ()
Returns a cursor for the handle.
Returns
Returns a move cursor, if the figure is transformable. Returns a default cursor otherwise.
Reimplemented from org.jhotdraw.draw.handle.AbstractHandle.
References org.jhotdraw.draw.handle.AbstractHandle.getOwner().
keyPressed()
void org.jhotdraw.draw.handle.MoveHandle.keyPressed (KeyEvent evt)
Reimplemented from org.jhotdraw.draw.handle.AbstractHandle.
References org.jhotdraw.draw.figure.Figure.changed(), org.jhotdraw.draw.handle.AbstractHandle.fireUndoableEditHappened(), org.jhotdraw.draw.handle.AbstractHandle.getOwner(), org.jhotdraw.draw.figure.Figure.isTransformable(), org.jhotdraw.draw.figure.Figure.transform(), and org.jhotdraw.draw.figure.Figure.willChange().
north()
static Handle org.jhotdraw.draw.handle.MoveHandle.north (Figure owner) static
References org.jhotdraw.draw.handle.MoveHandle.MoveHandle(), and org.jhotdraw.draw.locator.RelativeLocator.north().
northEast()
static Handle org.jhotdraw.draw.handle.MoveHandle.northEast (Figure owner) static
References org.jhotdraw.draw.handle.MoveHandle.MoveHandle(), and org.jhotdraw.draw.locator.RelativeLocator.northEast().
Referenced by org.jhotdraw.draw.handle.MoveHandle.addMoveHandles().
northWest()
static Handle org.jhotdraw.draw.handle.MoveHandle.northWest (Figure owner) static
References org.jhotdraw.draw.handle.MoveHandle.MoveHandle(), and org.jhotdraw.draw.locator.RelativeLocator.northWest().
Referenced by org.jhotdraw.draw.handle.MoveHandle.addMoveHandles().
south()
static Handle org.jhotdraw.draw.handle.MoveHandle.south (Figure owner) static
References org.jhotdraw.draw.handle.MoveHandle.MoveHandle(), and org.jhotdraw.draw.locator.RelativeLocator.south().
southEast()
static Handle org.jhotdraw.draw.handle.MoveHandle.southEast (Figure owner) static
References org.jhotdraw.draw.handle.MoveHandle.MoveHandle(), and org.jhotdraw.draw.locator.RelativeLocator.southEast().
Referenced by org.jhotdraw.draw.handle.MoveHandle.addMoveHandles().
southWest()
static Handle org.jhotdraw.draw.handle.MoveHandle.southWest (Figure owner) static
References org.jhotdraw.draw.handle.MoveHandle.MoveHandle(), and org.jhotdraw.draw.locator.RelativeLocator.southWest().
Referenced by org.jhotdraw.draw.handle.MoveHandle.addMoveHandles().
trackEnd()
void org.jhotdraw.draw.handle.MoveHandle.trackEnd (Point anchor, Point lead, int modifiersEx)
Tracks the end of the interaction.
Parameters
anchor the position where the interaction started
lead the current position
Implements org.jhotdraw.draw.handle.Handle.
References org.jhotdraw.draw.handle.AbstractHandle.fireUndoableEditHappened(), and org.jhotdraw.draw.handle.AbstractHandle.getOwner().
trackStart()
void org.jhotdraw.draw.handle.MoveHandle.trackStart (Point anchor, int modifiersEx)
Tracks the start of the interaction. The default implementation does nothing.
Parameters
anchor the position where the interaction started
Implements org.jhotdraw.draw.handle.Handle.
References org.jhotdraw.draw.Constrainer.constrainPoint(), org.jhotdraw.draw.DrawingView.getConstrainer(), org.jhotdraw.draw.handle.AbstractHandle.view, and org.jhotdraw.draw.DrawingView.viewToDrawing().
trackStep()
void org.jhotdraw.draw.handle.MoveHandle.trackStep (Point anchor, Point lead, int modifiersEx)
Tracks a step of the interaction.
Parameters
anchor the position where the interaction started
lead the current position
Implements org.jhotdraw.draw.handle.Handle.
References org.jhotdraw.draw.figure.Figure.changed(), org.jhotdraw.draw.Constrainer.constrainPoint(), org.jhotdraw.draw.DrawingView.getConstrainer(), org.jhotdraw.draw.handle.AbstractHandle.getOwner(), org.jhotdraw.draw.figure.Figure.isTransformable(), org.jhotdraw.draw.figure.Figure.transform(), org.jhotdraw.draw.handle.AbstractHandle.view, org.jhotdraw.draw.DrawingView.viewToDrawing(), and org.jhotdraw.draw.figure.Figure.willChange().
west()
static Handle org.jhotdraw.draw.handle.MoveHandle.west (Figure owner) static
References org.jhotdraw.draw.handle.MoveHandle.MoveHandle(), and org.jhotdraw.draw.locator.RelativeLocator.west().
The documentation for this class was generated from the following file:
jhotdraw-core/src/main/java/org/jhotdraw/draw/handle/MoveHandle.java