jhotdraw: org.jhotdraw.draw.handle.BezierScaleHandle Class Reference
org.jhotdraw.draw.handle.BezierScaleHandle Class Reference
Public Member Functions
BezierScaleHandle (BezierFigure owner)
boolean isCombinableWith (Handle h)
void draw (Graphics2D g)
Point getLocation ()
void trackStart (Point anchor, int modifiersEx)
void trackStep (Point anchor, Point lead, int modifiersEx)
void trackEnd (Point anchor, Point lead, int modifiersEx)
Public Member Functions inherited from org.jhotdraw.draw.handle.AbstractHandle
AbstractHandle (Figure owner)
void addHandleListener (HandleListener l)
void removeHandleListener (HandleListener l)
Figure getOwner ()
void setView (DrawingView view)
DrawingView getView ()
DrawingEditor getEditor ()
boolean contains (Point p)
void invalidate ()
void dispose ()
void areaInvalidated (FigureEvent evt)
void figureAdded (FigureEvent e)
void figureRemoved (FigureEvent e)
void figureRequestRemove (FigureEvent e)
void figureChanged (FigureEvent evt)
Cursor getCursor ()
void keyTyped (KeyEvent evt)
void keyReleased (KeyEvent evt)
void keyPressed (KeyEvent evt)
final Rectangle getBounds ()
Rectangle getDrawingArea ()
void trackDoubleClick (Point p, int modifiersEx)
void attributeChanged (FigureEvent e)
void viewTransformChanged ()
Collection< Handle > createSecondaryHandles ()
String getToolTipText (Point p)
void setToolTipText (String newValue)
void figureHandlesChanged (FigureEvent e)
Protected Member Functions
Rectangle basicGetBounds ()
Protected Member Functions inherited from org.jhotdraw.draw.handle.AbstractHandle
int getHandlesize ()
void fireAreaInvalidated (Rectangle invalidatedArea)
void fireUndoableEditHappened (UndoableEdit edit)
void fireHandleRequestRemove (Rectangle invalidatedArea)
void fireHandleRequestSecondaryHandles ()
void drawCircle (Graphics2D g, Color fill, Color stroke)
void drawRectangle (Graphics2D g, Color fill, Color stroke)
void drawDiamond (Graphics2D g, Color fill, Color stroke)
void updateBounds ()
Additional Inherited Members
Protected Attributes inherited from org.jhotdraw.draw.handle.AbstractHandle
DrawingView view
EventListenerList listenerList = new EventListenerList()
Detailed Description
A Handle which allows to interactively scale and rotate a BezierFigure.
Pressing the alt key or the shift key while manipulating the handle restricts the handle to rotate the BezierFigure without scaling it.
Author
Werner Randelshofer.
Version
$Id$
Constructor & Destructor Documentation
BezierScaleHandle()
org.jhotdraw.draw.handle.BezierScaleHandle.BezierScaleHandle (BezierFigure owner)
Creates a new instance.
Member Function Documentation
basicGetBounds()
Rectangle org.jhotdraw.draw.handle.BezierScaleHandle.basicGetBounds () protected
Reimplemented from org.jhotdraw.draw.handle.AbstractHandle.
References org.jhotdraw.draw.handle.AbstractHandle.getHandlesize(), and org.jhotdraw.draw.handle.BezierScaleHandle.getLocation().
draw()
void org.jhotdraw.draw.handle.BezierScaleHandle.draw (Graphics2D g)
Draws this handle.
Reimplemented from org.jhotdraw.draw.handle.AbstractHandle.
References org.jhotdraw.draw.handle.AbstractHandle.drawCircle(), org.jhotdraw.draw.handle.AbstractHandle.getEditor(), org.jhotdraw.draw.handle.HandleAttributeKeys.SCALE_HANDLE_FILL_COLOR, and org.jhotdraw.draw.handle.HandleAttributeKeys.SCALE_HANDLE_STROKE_COLOR.
getLocation()
Point org.jhotdraw.draw.handle.BezierScaleHandle.getLocation ()
References org.jhotdraw.draw.DrawingView.drawingToView(), and org.jhotdraw.draw.handle.AbstractHandle.view.
Referenced by org.jhotdraw.draw.handle.BezierScaleHandle.basicGetBounds().
isCombinableWith()
boolean org.jhotdraw.draw.handle.BezierScaleHandle.isCombinableWith (Handle handle)
Returns true, if the given handle is an instance of the same class or of a subclass of this handle,.
Reimplemented from org.jhotdraw.draw.handle.AbstractHandle.
trackEnd()
void org.jhotdraw.draw.handle.BezierScaleHandle.trackEnd (Point anchor, Point lead, int modifiersEx)
Tracks the end of the interaction.
Parameters
anchor the position where the interaction started
lead the current position
Implements org.jhotdraw.draw.handle.Handle.
References org.jhotdraw.draw.Drawing.fireUndoableEditHappened(), org.jhotdraw.draw.DrawingView.getDrawing(), org.jhotdraw.draw.handle.AbstractHandle.getOwner(), and org.jhotdraw.draw.handle.AbstractHandle.view.
trackStart()
void org.jhotdraw.draw.handle.BezierScaleHandle.trackStart (Point anchor, int modifiersEx)
Tracks the start of the interaction. The default implementation does nothing.
Parameters
anchor the position where the interaction started
Implements org.jhotdraw.draw.handle.Handle.
References org.jhotdraw.draw.figure.BezierFigure.getCenter(), org.jhotdraw.draw.figure.BezierFigure.getTransformRestoreData(), org.jhotdraw.draw.handle.AbstractHandle.view, and org.jhotdraw.draw.DrawingView.viewToDrawing().
trackStep()
void org.jhotdraw.draw.handle.BezierScaleHandle.trackStep (Point anchor, Point lead, int modifiersEx)
Tracks a step of the interaction.
Parameters
anchor the position where the interaction started
lead the current position
Implements org.jhotdraw.draw.handle.Handle.
References org.jhotdraw.draw.figure.Figure.changed(), org.jhotdraw.draw.handle.AbstractHandle.getOwner(), org.jhotdraw.draw.figure.Figure.restoreTransformTo(), org.jhotdraw.draw.figure.Figure.transform(), org.jhotdraw.draw.handle.AbstractHandle.view, org.jhotdraw.draw.DrawingView.viewToDrawing(), and org.jhotdraw.draw.figure.Figure.willChange().
The documentation for this class was generated from the following file:
jhotdraw-core/src/main/java/org/jhotdraw/draw/handle/BezierScaleHandle.java