jhotdraw: org.jhotdraw.draw.action.DrawingAttributeAction Class Reference
org.jhotdraw.draw.action.DrawingAttributeAction Class Reference
Public Member Functions
DrawingAttributeAction (DrawingEditor editor, Map< AttributeKey<?>, Object > attributes, String name, Icon icon)
void actionPerformed (java.awt.event.ActionEvent evt)
Public Member Functions inherited from org.jhotdraw.draw.action.AbstractDrawingViewAction
AbstractDrawingViewAction (DrawingEditor editor)
AbstractDrawingViewAction (DrawingView view)
void dispose ()
void setUpdateEnabledState (boolean newValue)
boolean isUpdatEnabledState ()
Protected Attributes
Map< AttributeKey<?>, Object > attributes
Additional Inherited Members
Protected Member Functions inherited from org.jhotdraw.draw.action.AbstractDrawingViewAction
void setEditor (DrawingEditor newValue)
DrawingEditor getEditor ()
DrawingView getView ()
Drawing getDrawing ()
void fireUndoableEditHappened (UndoableEdit edit)
void updateEnabledState ()
void updateViewState ()
Detailed Description
AttributeAction.
Author
Werner Randelshofer
Version
$Id$
Constructor & Destructor Documentation
DrawingAttributeAction()
org.jhotdraw.draw.action.DrawingAttributeAction.DrawingAttributeAction (DrawingEditor editor, Map< AttributeKey<?>, Object > attributes, String name, Icon icon)
References org.jhotdraw.draw.action.DrawingAttributeAction.attributes, and org.jhotdraw.draw.action.AbstractDrawingViewAction.updateEnabledState().
Member Function Documentation
actionPerformed()
void org.jhotdraw.draw.action.DrawingAttributeAction.actionPerformed (java.awt.event.ActionEvent evt)
References org.jhotdraw.draw.Drawing.add(), org.jhotdraw.draw.action.DrawingAttributeAction.attributes, org.jhotdraw.draw.figure.Figure.changed(), org.jhotdraw.draw.action.AbstractDrawingViewAction.fireUndoableEditHappened(), org.jhotdraw.draw.figure.Figure.getAttributesRestoreData(), org.jhotdraw.draw.DrawingView.getDrawing(), org.jhotdraw.draw.action.AbstractDrawingViewAction.getView(), org.jhotdraw.draw.figure.Figure.restoreAttributesTo(), org.jhotdraw.draw.figure.Figure.set(), and org.jhotdraw.draw.figure.Figure.willChange().
Member Data Documentation
attributes
Map<AttributeKey<?>, Object> org.jhotdraw.draw.action.DrawingAttributeAction.attributes protected
Referenced by org.jhotdraw.draw.action.DrawingAttributeAction.actionPerformed(), and org.jhotdraw.draw.action.DrawingAttributeAction.DrawingAttributeAction().
The documentation for this class was generated from the following file:
jhotdraw-core/src/main/java/org/jhotdraw/draw/action/DrawingAttributeAction.java