jhotdraw: org.jhotdraw.draw.figure.AbstractFigure Class Reference
org.jhotdraw.draw.figure.AbstractFigure Class Reference abstract
Public Member Functions
AbstractFigure ()
void addFigureListener (FigureListener l)
void removeFigureListener (FigureListener l)
void addNotify (Drawing d)
void removeNotify (Drawing d)
void fireAreaInvalidated ()
void fireFigureChanged ()
AbstractFigure clone ()
void remap (Map< Figure, Figure > oldToNew, boolean disconnectIfNotInMap)
Collection< Handle > createHandles (int detailLevel)
Cursor getCursor (Point2D.Double p)
final void setBounds (Rectangle2D.Double bounds)
void setBounds (Point2D.Double anchor, Point2D.Double lead)
void willChange ()
void changed ()
Connector findConnector (Point2D.Double p, ConnectionFigure prototype)
boolean includes (Figure figure)
Figure findFigureInside (Point2D.Double p)
Connector findCompatibleConnector (Connector c, boolean isStart)
Collection< Action > getActions (Point2D.Double p)
Tool getTool (Point2D.Double p)
boolean handleMouseClick (Point2D.Double p, MouseEvent evt, DrawingView view)
boolean handleDrop (Point2D.Double p, Collection< Figure > droppedFigures, DrawingView view)
Point2D.Double getEndPoint ()
Point2D.Double getStartPoint ()
Dimension2DDouble getPreferredSize ()
boolean isConnectable ()
void setConnectable (boolean newValue)
boolean isSelectable ()
void setSelectable (boolean newValue)
boolean isRemovable ()
void setRemovable (boolean newValue)
boolean isTransformable ()
void setTransformable (boolean newValue)
boolean isVisible ()
void setVisible (boolean newValue)
Collection< Figure > getDecomposition ()
void requestRemove ()
int getLayer ()
String getToolTipText (Point2D.Double p)
String toString ()
Collection< Connector > getConnectors (ConnectionFigure prototype)
Public Member Functions inherited from org.jhotdraw.draw.figure.Figure
void draw (Graphics2D g)
Rectangle2D.Double getBounds ()
Rectangle2D.Double getDrawingArea ()
Rectangle2D.Double getDrawingArea (double factor)
boolean contains (Point2D.Double p)
Object getTransformRestoreData ()
void restoreTransformTo (Object restoreData)
void transform (AffineTransform tx)
public< T > void set (AttributeKey< T > key, T value)
public< T > T get (AttributeKey< T > key)
Map< AttributeKey<?>, Object > getAttributes ()
Object getAttributesRestoreData ()
void restoreAttributesTo (Object restoreData)
void addPropertyChangeListener (PropertyChangeListener listener)
void removePropertyChangeListener (PropertyChangeListener listener)
Protected Member Functions
Drawing getDrawing ()
Object getLock ()
void fireAreaInvalidated (Rectangle2D.Double invalidatedArea)
void fireAreaInvalidated (FigureEvent event)
void fireFigureRequestRemove ()
void fireFigureAdded ()
void fireFigureRemoved ()
void fireFigureChanged (Rectangle2D.Double changedArea)
void fireFigureChanged (FigureEvent event)
void fireFigureHandlesChanged ()
void fireUndoableEditHappened (UndoableEdit edit)
void invalidate ()
boolean isChanging ()
int getChangingDepth ()
void validate ()
FontRenderContext getFontRenderContext ()
Protected Attributes
EventListenerList listenerList = new EventListenerList()
int changingDepth = 0
Additional Inherited Members
Static Public Attributes inherited from org.jhotdraw.draw.figure.Figure
static final String CONNECTABLE_PROPERTY = "connectable"
static final String REMOVABLE_PROPERTY = "removable"
static final String SELECTABLE_PROPERTY = "selectable"
static final String TRANSFORMABLE_PROPERTY = "transformable"
Detailed Description
This abstract class can be extended to implement a Figure.
Author
Werner Randelshofer
Version
$Id$
Constructor & Destructor Documentation
AbstractFigure()
org.jhotdraw.draw.figure.AbstractFigure.AbstractFigure ()
Creates a new instance.
Referenced by org.jhotdraw.draw.figure.AbstractFigure.clone().
Member Function Documentation
addFigureListener()
void org.jhotdraw.draw.figure.AbstractFigure.addFigureListener (FigureListener l)
Adds a listener for FigureEvent's.
Implements org.jhotdraw.draw.figure.Figure.
References org.jhotdraw.draw.figure.AbstractFigure.listenerList.
addNotify()
void org.jhotdraw.draw.figure.AbstractFigure.addNotify (Drawing d)
Informs a figure, that it has been added to a drawing. The figure must inform all FigureListeners that it has been added.
Implements org.jhotdraw.draw.figure.Figure.
Reimplemented in org.jhotdraw.draw.GraphicalCompositeFigure, org.jhotdraw.draw.figure.LineConnectionFigure, org.jhotdraw.draw.figure.LabeledLineConnectionFigure, and org.jhotdraw.draw.figure.AbstractCompositeFigure.
References org.jhotdraw.draw.figure.AbstractFigure.fireFigureAdded().
changed()
void org.jhotdraw.draw.figure.AbstractFigure.changed ()
Informs that a figure changed the area of its display box.
Implements org.jhotdraw.draw.figure.Figure.
Reimplemented in org.jhotdraw.draw.figure.AbstractCompositeFigure.
References org.jhotdraw.draw.figure.AbstractFigure.changingDepth, org.jhotdraw.draw.figure.AbstractFigure.fireFigureChanged(), org.jhotdraw.draw.figure.Figure.getDrawingArea(), and org.jhotdraw.draw.figure.AbstractFigure.validate().
Referenced by org.jhotdraw.draw.tool.BezierTool.addPointToFigure(), org.jhotdraw.draw.figure.BezierFigure.handleMouseClick(), org.jhotdraw.draw.figure.LineFigure.handleMouseClick(), org.jhotdraw.draw.handle.BezierControlPointHandle.keyPressed(), org.jhotdraw.draw.handle.BezierNodeHandle.keyPressed(), org.jhotdraw.draw.handle.RoundRectangleRadiusHandle.keyPressed(), org.jhotdraw.draw.tool.BezierTool.mouseReleased(), org.jhotdraw.draw.event.BezierNodeEdit.redo(), org.jhotdraw.draw.event.SetBoundsEdit.redo(), org.jhotdraw.draw.figure.AbstractFigure.setBounds(), org.jhotdraw.draw.figure.AbstractAttributedDecoratedFigure.setDecorator(), org.jhotdraw.draw.figure.AbstractFigure.setVisible(), org.jhotdraw.draw.figure.AbstractFigureNGTest.testChangedWithoutWillChange(), org.jhotdraw.draw.figure.AbstractFigureNGTest.testWillChangeChangedEvents(), org.jhotdraw.draw.handle.BezierNodeHandle.trackDoubleClick(), org.jhotdraw.draw.handle.BezierControlPointHandle.trackEnd(), org.jhotdraw.draw.handle.BezierNodeHandle.trackEnd(), org.jhotdraw.draw.handle.BezierControlPointHandle.trackStep(), org.jhotdraw.draw.handle.BezierNodeHandle.trackStep(), org.jhotdraw.draw.handle.RoundRectangleRadiusHandle.trackStep(), org.jhotdraw.draw.event.BezierNodeEdit.undo(), and org.jhotdraw.draw.event.SetBoundsEdit.undo().
clone()
AbstractFigure org.jhotdraw.draw.figure.AbstractFigure.clone ()
Returns a clone of the figure, with clones of all aggregated figures, such as children and decorators. The cloned figure does not clone the list of FigureListeners from its original.
Implements org.jhotdraw.draw.figure.Figure.
Reimplemented in org.jhotdraw.draw.QuadTreeDrawing, org.jhotdraw.draw.GraphicalCompositeFigure, org.jhotdraw.draw.figure.TriangleFigure, org.jhotdraw.draw.figure.TextFigure, org.jhotdraw.draw.figure.TextAreaFigure, org.jhotdraw.draw.figure.RoundRectangleFigure, org.jhotdraw.draw.figure.RectangleFigure, org.jhotdraw.draw.figure.LineConnectionFigure, org.jhotdraw.draw.figure.LabeledLineConnectionFigure, org.jhotdraw.draw.figure.ImageFigure, org.jhotdraw.draw.figure.EllipseFigure, org.jhotdraw.draw.figure.DiamondFigure, org.jhotdraw.draw.figure.BezierFigure, org.jhotdraw.draw.figure.AbstractCompositeFigure, org.jhotdraw.draw.figure.AbstractAttributedFigure, org.jhotdraw.draw.figure.AbstractAttributedDecoratedFigure, org.jhotdraw.draw.figure.AbstractAttributedCompositeFigure, and org.jhotdraw.draw.AbstractDrawing.
References org.jhotdraw.draw.figure.AbstractFigure.AbstractFigure(), org.jhotdraw.draw.figure.AbstractFigure.clone(), and org.jhotdraw.draw.figure.AbstractFigure.listenerList.
Referenced by org.jhotdraw.draw.figure.AbstractFigure.clone().
createHandles()
Collection<Handle> org.jhotdraw.draw.figure.AbstractFigure.createHandles (int detailLevel)
Creates handles used to manipulate the figure.
Parameters
detailLevel The detail level of the handles. Usually this is 0 for bounding box handles and 1 for point handles. The value -1 is used by the SelectAreaTracker and the HandleTracker to highlight figures, over which the mouse pointer is hovering.
Returns
a Collection of handles
See also
Handle
Implements org.jhotdraw.draw.figure.Figure.
Reimplemented in org.jhotdraw.draw.GraphicalCompositeFigure, org.jhotdraw.draw.figure.TriangleFigure, org.jhotdraw.draw.figure.TextFigure, org.jhotdraw.draw.figure.TextAreaFigure, org.jhotdraw.draw.figure.RoundRectangleFigure, org.jhotdraw.draw.figure.LineFigure, org.jhotdraw.draw.figure.LineConnectionFigure, org.jhotdraw.draw.figure.BezierFigure, and org.jhotdraw.draw.figure.AbstractCompositeFigure.
References org.jhotdraw.draw.handle.ResizeHandleKit.addResizeHandles().
findCompatibleConnector()
Connector org.jhotdraw.draw.figure.AbstractFigure.findCompatibleConnector (Connector c, boolean isStartConnector)
Gets a compatible connector. If the provided connector is part of this figure, return the connector. If the provided connector is part of another figure, return a connector with the same semantics for this figure. Returns null, if no compatible connector is available.
Implements org.jhotdraw.draw.figure.Figure.
Reimplemented in org.jhotdraw.draw.figure.TriangleFigure, org.jhotdraw.draw.figure.RoundRectangleFigure, org.jhotdraw.draw.figure.ImageFigure, org.jhotdraw.draw.figure.EllipseFigure, org.jhotdraw.draw.figure.DiamondFigure, and org.jhotdraw.draw.figure.BezierFigure.
findConnector()
Connector org.jhotdraw.draw.figure.AbstractFigure.findConnector (Point2D.Double p, ConnectionFigure prototype)
Returns the Figures connector for the specified location. By default a ChopBoxConnector is returned.
See also
ChopRectangleConnector
Implements org.jhotdraw.draw.figure.Figure.
Reimplemented in org.jhotdraw.draw.figure.TriangleFigure, org.jhotdraw.draw.figure.RoundRectangleFigure, org.jhotdraw.draw.figure.ImageFigure, org.jhotdraw.draw.figure.EllipseFigure, org.jhotdraw.draw.figure.DiamondFigure, and org.jhotdraw.draw.figure.BezierFigure.
findFigureInside()
Figure org.jhotdraw.draw.figure.AbstractFigure.findFigureInside (Point2D.Double p)
Finds the innermost figure at the specified location.
In case of a
CompositeFigure
, this method descends into its children and into its children's children until the innermost figure is found.
This functionality is implemented using the Chain of Responsibility design pattern. A figure which is not composed of other figures returns itself if the point is contained by the figure. Composed figures pass the method call down to their children.
Parameters
p A location on the drawing.
Returns
Returns the innermost figure at the location, or null if the location is not contained in a figure.
Implements org.jhotdraw.draw.figure.Figure.
Reimplemented in org.jhotdraw.draw.QuadTreeDrawing, org.jhotdraw.draw.figure.QuadTreeCompositeFigure, org.jhotdraw.draw.figure.LabeledLineConnectionFigure, org.jhotdraw.draw.figure.AbstractCompositeFigure, and org.jhotdraw.draw.DefaultDrawing.
References org.jhotdraw.draw.figure.Figure.contains().
fireAreaInvalidated() [1/3]
void org.jhotdraw.draw.figure.AbstractFigure.fireAreaInvalidated ()
Notify all listenerList that have registered interest for notification on this event type.
References org.jhotdraw.draw.figure.Figure.getDrawingArea().
Referenced by org.jhotdraw.draw.figure.AbstractCompositeFigure.EventHandler.areaInvalidated(), org.jhotdraw.draw.figure.QuadTreeCompositeFigure.FigureHandler.areaInvalidated(), org.jhotdraw.draw.figure.AbstractCompositeFigure.bringToFront(), org.jhotdraw.draw.figure.QuadTreeCompositeFigure.bringToFront(), org.jhotdraw.draw.QuadTreeDrawing.bringToFront(), org.jhotdraw.draw.figure.QuadTreeCompositeFigure.FigureHandler.figureChanged(), org.jhotdraw.draw.QuadTreeDrawing.QuadTreeEventHandler.figureChanged(), org.jhotdraw.draw.figure.AbstractCompositeFigure.sendToBack(), org.jhotdraw.draw.figure.QuadTreeCompositeFigure.sendToBack(), org.jhotdraw.draw.QuadTreeDrawing.sendToBack(), and org.jhotdraw.draw.figure.AbstractFigure.willChange().
fireAreaInvalidated() [2/3]
void org.jhotdraw.draw.figure.AbstractFigure.fireAreaInvalidated (FigureEvent event) protected
Notify all listenerList that have registered interest for notification on this event type.
References org.jhotdraw.draw.figure.AbstractFigure.listenerList.
fireAreaInvalidated() [3/3]
void org.jhotdraw.draw.figure.AbstractFigure.fireAreaInvalidated (Rectangle2D.Double invalidatedArea) protected
Notify all listenerList that have registered interest for notification on this event type.
References org.jhotdraw.draw.figure.AbstractFigure.listenerList.
fireFigureAdded()
void org.jhotdraw.draw.figure.AbstractFigure.fireFigureAdded () protected
Notify all listenerList that have registered interest for notification on this event type.
References org.jhotdraw.draw.figure.Figure.getBounds(), and org.jhotdraw.draw.figure.AbstractFigure.listenerList.
Referenced by org.jhotdraw.draw.figure.AbstractCompositeFigure.add(), org.jhotdraw.draw.figure.AbstractCompositeFigure.addAll(), and org.jhotdraw.draw.figure.AbstractFigure.addNotify().
fireFigureChanged() [1/3]
void org.jhotdraw.draw.figure.AbstractFigure.fireFigureChanged ()
References org.jhotdraw.draw.figure.Figure.getDrawingArea().
Referenced by org.jhotdraw.draw.figure.AbstractFigure.changed(), and org.jhotdraw.draw.figure.AbstractCompositeFigure.EventHandler.figureChanged().
fireFigureChanged() [2/3]
void org.jhotdraw.draw.figure.AbstractFigure.fireFigureChanged (FigureEvent event) protected
References org.jhotdraw.draw.figure.AbstractFigure.listenerList.
fireFigureChanged() [3/3]
void org.jhotdraw.draw.figure.AbstractFigure.fireFigureChanged (Rectangle2D.Double changedArea) protected
Notify all listenerList that have registered interest for notification on this event type.
References org.jhotdraw.draw.figure.AbstractFigure.listenerList.
fireFigureHandlesChanged()
void org.jhotdraw.draw.figure.AbstractFigure.fireFigureHandlesChanged () protected
Notify all listenerList that have registered interest for notification on this event type.
References org.jhotdraw.draw.figure.Figure.getDrawingArea(), and org.jhotdraw.draw.figure.AbstractFigure.listenerList.
fireFigureRemoved()
void org.jhotdraw.draw.figure.AbstractFigure.fireFigureRemoved () protected
Notify all listenerList that have registered interest for notification on this event type.
References org.jhotdraw.draw.figure.Figure.getBounds(), and org.jhotdraw.draw.figure.AbstractFigure.listenerList.
Referenced by org.jhotdraw.draw.figure.AbstractCompositeFigure.remove(), and org.jhotdraw.draw.figure.AbstractFigure.removeNotify().
fireFigureRequestRemove()
void org.jhotdraw.draw.figure.AbstractFigure.fireFigureRequestRemove () protected
Notify all listenerList that have registered interest for notification on this event type.
References org.jhotdraw.draw.figure.Figure.getBounds(), and org.jhotdraw.draw.figure.AbstractFigure.listenerList.
Referenced by org.jhotdraw.draw.figure.AbstractFigure.requestRemove().
fireUndoableEditHappened()
void org.jhotdraw.draw.figure.AbstractFigure.fireUndoableEditHappened (UndoableEdit edit) protected
Notify all UndoableEditListener of the Drawing, to which this Figure has been added to. If this Figure is not part of a Drawing, the event is lost.
Reimplemented in org.jhotdraw.draw.AbstractDrawing.
References org.jhotdraw.draw.Drawing.fireUndoableEditHappened(), and org.jhotdraw.draw.figure.AbstractFigure.getDrawing().
Referenced by org.jhotdraw.draw.figure.BezierFigure.handleMouseClick(), org.jhotdraw.draw.figure.LineFigure.handleMouseClick(), org.jhotdraw.draw.figure.AbstractFigure.setBounds(), org.jhotdraw.draw.figure.AbstractCompositeFigure.EventHandler.undoableEditHappened(), and org.jhotdraw.draw.figure.QuadTreeCompositeFigure.FigureHandler.undoableEditHappened().
getActions()
Collection<Action> org.jhotdraw.draw.figure.AbstractFigure.getActions (Point2D.Double p)
Returns a collection of actions which are presented to the user in a popup menu.
The collection may contain null entries. These entries are used interpreted as separators in the popup menu.
Implements org.jhotdraw.draw.figure.Figure.
Reimplemented in org.jhotdraw.draw.figure.ImageFigure.
getChangingDepth()
int org.jhotdraw.draw.figure.AbstractFigure.getChangingDepth () protected
References org.jhotdraw.draw.figure.AbstractFigure.changingDepth.
Referenced by org.jhotdraw.draw.figure.AbstractFigureNGTest.testWillChangeChangedEvents().
getConnectors()
Collection<Connector> org.jhotdraw.draw.figure.AbstractFigure.getConnectors (ConnectionFigure prototype)
Returns all connectors of this Figure for the specified prototype of a ConnectionFigure.
This is used by connection tools and connection handles to visualize the connectors when the user is about to create a ConnectionFigure to this Figure.
Parameters
prototype The prototype used to create a connection or null if unknown. This allows for specific connectors for different connection figures.
Implements org.jhotdraw.draw.figure.Figure.
getCursor()
Cursor org.jhotdraw.draw.figure.AbstractFigure.getCursor (Point2D.Double p)
Returns a cursor for the specified location.
Implements org.jhotdraw.draw.figure.Figure.
References org.jhotdraw.draw.figure.Figure.contains().
getDecomposition()
Collection<Figure> org.jhotdraw.draw.figure.AbstractFigure.getDecomposition ()
Returns a decompositon of a figure into its parts. A figure is considered as a part of itself.
Implements org.jhotdraw.draw.figure.Figure.
Reimplemented in org.jhotdraw.draw.figure.AbstractCompositeFigure.
getDrawing()
Drawing org.jhotdraw.draw.figure.AbstractFigure.getDrawing () protected
Reimplemented in org.jhotdraw.draw.AbstractDrawing.
Referenced by org.jhotdraw.draw.figure.LabeledLineConnectionFigure.add(), org.jhotdraw.draw.figure.AbstractCompositeFigure.add(), org.jhotdraw.draw.figure.AbstractCompositeFigure.addAll(), org.jhotdraw.draw.figure.AbstractFigure.fireUndoableEditHappened(), org.jhotdraw.draw.figure.AbstractFigure.getLock(), org.jhotdraw.draw.figure.AbstractCompositeFigure.remove(), org.jhotdraw.draw.figure.LabeledLineConnectionFigure.remove(), org.jhotdraw.draw.figure.LabeledLineConnectionFigure.removeAllChildren(), org.jhotdraw.draw.figure.AbstractCompositeFigure.removeChild(), org.jhotdraw.draw.figure.LabeledLineConnectionFigure.removeChild(), org.jhotdraw.draw.figure.LineConnectionFigure.setEndConnector(), and org.jhotdraw.draw.GraphicalCompositeFigure.setPresentationFigure().
getEndPoint()
Point2D.Double org.jhotdraw.draw.figure.AbstractFigure.getEndPoint ()
Returns the untransformed logical end point of the bounds.
See also
setBounds
Implements org.jhotdraw.draw.figure.Figure.
Reimplemented in org.jhotdraw.draw.figure.BezierFigure.
References org.jhotdraw.draw.figure.Figure.getBounds().
Referenced by org.jhotdraw.draw.figure.AbstractCompositeFigure.getPreferredSize(), org.jhotdraw.draw.figure.AbstractFigure.setBounds(), org.jhotdraw.draw.figure.AbstractAttributedDecoratedFigure.setDecorator(), org.jhotdraw.draw.figure.DiamondFigure.transform(), org.jhotdraw.draw.figure.EllipseFigure.transform(), org.jhotdraw.draw.figure.RectangleFigure.transform(), org.jhotdraw.draw.figure.RoundRectangleFigure.transform(), org.jhotdraw.draw.figure.TriangleFigure.transform(), and org.jhotdraw.draw.figure.AbstractAttributedDecoratedFigure.updateDecoratorBounds().
getFontRenderContext()
FontRenderContext org.jhotdraw.draw.figure.AbstractFigure.getFontRenderContext () protected
Reimplemented in org.jhotdraw.draw.AbstractDrawing.
Referenced by org.jhotdraw.draw.figure.TextAreaFigure.drawText(), org.jhotdraw.draw.figure.TextAreaFigure.getBaseline(), org.jhotdraw.draw.figure.TextAreaFigure.getPreferredTextSize(), and org.jhotdraw.draw.figure.TextFigure.getTextLayout().
getLayer()
int org.jhotdraw.draw.figure.AbstractFigure.getLayer ()
AbstractFigure always returns 0. Override this method if your figure needs to be on a different layer.
Implements org.jhotdraw.draw.figure.Figure.
getLock()
Object org.jhotdraw.draw.figure.AbstractFigure.getLock () protected
Reimplemented in org.jhotdraw.draw.AbstractDrawing.
References org.jhotdraw.draw.figure.AbstractFigure.getDrawing(), and org.jhotdraw.draw.Drawing.getLock().
getPreferredSize()
Dimension2DDouble org.jhotdraw.draw.figure.AbstractFigure.getPreferredSize ()
The preferred size is used by Layouter to determine the preferred size of a Figure. For most Figure's this is the same as the dimensions returned by getBounds.
Implements org.jhotdraw.draw.figure.Figure.
Reimplemented in org.jhotdraw.draw.figure.TextFigure, and org.jhotdraw.draw.figure.AbstractCompositeFigure.
References org.jhotdraw.draw.figure.Figure.getBounds().
getStartPoint()
Point2D.Double org.jhotdraw.draw.figure.AbstractFigure.getStartPoint ()
Returns the untransformed logical start point of the bounds.
See also
setBounds
Implements org.jhotdraw.draw.figure.Figure.
Reimplemented in org.jhotdraw.draw.figure.BezierFigure.
References org.jhotdraw.draw.figure.Figure.getBounds().
Referenced by org.jhotdraw.draw.figure.AbstractCompositeFigure.getPreferredSize(), org.jhotdraw.draw.figure.AbstractFigure.setBounds(), org.jhotdraw.draw.figure.AbstractAttributedDecoratedFigure.setDecorator(), org.jhotdraw.draw.figure.DiamondFigure.transform(), org.jhotdraw.draw.figure.EllipseFigure.transform(), org.jhotdraw.draw.figure.RectangleFigure.transform(), org.jhotdraw.draw.figure.RoundRectangleFigure.transform(), org.jhotdraw.draw.figure.TriangleFigure.transform(), and org.jhotdraw.draw.figure.AbstractAttributedDecoratedFigure.updateDecoratorBounds().
getTool()
Tool org.jhotdraw.draw.figure.AbstractFigure.getTool (Point2D.Double p)
Returns a specialized tool for the given coordinate.
Returns null, if no specialized tool is available.
Implements org.jhotdraw.draw.figure.Figure.
Reimplemented in org.jhotdraw.draw.figure.TextFigure, org.jhotdraw.draw.figure.TextAreaFigure, and org.jhotdraw.draw.figure.LabelFigure.
getToolTipText()
String org.jhotdraw.draw.figure.AbstractFigure.getToolTipText (Point2D.Double p)
Returns a tooltip for the specified location on the figure.
Implements org.jhotdraw.draw.figure.Figure.
handleDrop()
boolean org.jhotdraw.draw.figure.AbstractFigure.handleDrop (Point2D.Double p, Collection< Figure > droppedFigures, DrawingView view)
Handles a drop.
Parameters
p The location of the mouse event.
droppedFigures The dropped figures.
view The drawing view which is the source of the mouse event.
Returns
Returns true, if the figures should snap back to the location they were dragged from.
Implements org.jhotdraw.draw.figure.Figure.
handleMouseClick()
boolean org.jhotdraw.draw.figure.AbstractFigure.handleMouseClick (Point2D.Double p, MouseEvent evt, DrawingView view)
Handles a mouse click.
Implements org.jhotdraw.draw.figure.Figure.
Reimplemented in org.jhotdraw.draw.figure.LineFigure, org.jhotdraw.draw.figure.LineConnectionFigure, and org.jhotdraw.draw.figure.BezierFigure.
includes()
boolean org.jhotdraw.draw.figure.AbstractFigure.includes (Figure figure)
Checks whether the given figure is contained in this figure. A figure includes itself.
Implements org.jhotdraw.draw.figure.Figure.
invalidate()
void org.jhotdraw.draw.figure.AbstractFigure.invalidate () protected
Invalidates cached data of the Figure. This method must execute fast, because it can be called very often.
Reimplemented in org.jhotdraw.draw.figure.TextFigure, org.jhotdraw.draw.figure.TextAreaFigure, org.jhotdraw.draw.figure.LabeledLineConnectionFigure, org.jhotdraw.draw.figure.BezierFigure, and org.jhotdraw.draw.figure.AbstractCompositeFigure.
Referenced by org.jhotdraw.draw.figure.AbstractFigure.willChange().
isChanging()
boolean org.jhotdraw.draw.figure.AbstractFigure.isChanging () protected
References org.jhotdraw.draw.figure.AbstractFigure.changingDepth.
Referenced by org.jhotdraw.draw.figure.AbstractCompositeFigure.EventHandler.figureChanged(), org.jhotdraw.draw.figure.QuadTreeCompositeFigure.FigureHandler.figureChanged(), and org.jhotdraw.draw.QuadTreeDrawing.QuadTreeEventHandler.figureChanged().
isConnectable()
boolean org.jhotdraw.draw.figure.AbstractFigure.isConnectable ()
Checks whether this figure is connectable. By default
AbstractFigure
can be connected.
Implements org.jhotdraw.draw.figure.Figure.
isRemovable()
boolean org.jhotdraw.draw.figure.AbstractFigure.isRemovable ()
Checks whether this figure is removable. By default
AbstractFigure
can be removed.
Implements org.jhotdraw.draw.figure.Figure.
isSelectable()
boolean org.jhotdraw.draw.figure.AbstractFigure.isSelectable ()
Checks whether this figure is selectable. By default
AbstractFigure
can be selected.
Implements org.jhotdraw.draw.figure.Figure.
isTransformable()
boolean org.jhotdraw.draw.figure.AbstractFigure.isTransformable ()
Checks whether this figure is transformable. By default
AbstractFigure
can be transformed.
Implements org.jhotdraw.draw.figure.Figure.
Reimplemented in org.jhotdraw.draw.figure.GroupFigure.
isVisible()
boolean org.jhotdraw.draw.figure.AbstractFigure.isVisible ()
Checks whether this figure is visible. By default
AbstractFigure
is visible.
Implements org.jhotdraw.draw.figure.Figure.
remap()
void org.jhotdraw.draw.figure.AbstractFigure.remap (Map< Figure, Figure > oldToNew, boolean disconnectIfNotInMap)
After cloning a collection of figures, the ConnectionFigures contained in this collection still connect to the original figures instead of to the clones. Using This operation and providing a map, which maps from the original collection of figures to the new collection, connections can be remapped to the new figures.
Implements org.jhotdraw.draw.figure.Figure.
Reimplemented in org.jhotdraw.draw.figure.LineConnectionFigure, org.jhotdraw.draw.figure.LabelFigure, and org.jhotdraw.draw.figure.LabeledLineConnectionFigure.
removeFigureListener()
void org.jhotdraw.draw.figure.AbstractFigure.removeFigureListener (FigureListener l)
Removes a listener for FigureEvent's.
Implements org.jhotdraw.draw.figure.Figure.
References org.jhotdraw.draw.figure.AbstractFigure.listenerList.
removeNotify()
void org.jhotdraw.draw.figure.AbstractFigure.removeNotify (Drawing d)
Informs a figure, that it has been removed from a drawing. The figure must inform all FigureListeners that it has been removed.
Implements org.jhotdraw.draw.figure.Figure.
Reimplemented in org.jhotdraw.draw.GraphicalCompositeFigure, org.jhotdraw.draw.figure.LineConnectionFigure, org.jhotdraw.draw.figure.LabeledLineConnectionFigure, and org.jhotdraw.draw.figure.AbstractCompositeFigure.
References org.jhotdraw.draw.figure.AbstractFigure.fireFigureRemoved().
requestRemove()
void org.jhotdraw.draw.figure.AbstractFigure.requestRemove ()
Fires a FigureListener.figureRequestRemove event.
Implements org.jhotdraw.draw.figure.Figure.
References org.jhotdraw.draw.figure.AbstractFigure.fireFigureRequestRemove().
setBounds() [1/2]
void org.jhotdraw.draw.figure.AbstractFigure.setBounds (Point2D.Double start, Point2D.Double end)
Sets the logical and untransformed bounds of the figure.
This is used by Tool's which create a new Figure and by Tool's which connect a Figure to another Figure.
This is a basic operation which does not fire events. Use the following code sequence, if you need event firing:
figure.willChange();
figure.setBounds(...);
figure.changed();
Parameters
start the start point of the bounds
end the end point of the bounds
See also
getBounds
Implements org.jhotdraw.draw.figure.Figure.
Reimplemented in org.jhotdraw.draw.GraphicalCompositeFigure, org.jhotdraw.draw.figure.TriangleFigure, org.jhotdraw.draw.figure.TextFigure, org.jhotdraw.draw.figure.TextAreaFigure, org.jhotdraw.draw.figure.RoundRectangleFigure, org.jhotdraw.draw.figure.RectangleFigure, org.jhotdraw.draw.figure.ImageFigure, org.jhotdraw.draw.figure.EllipseFigure, org.jhotdraw.draw.figure.DiamondFigure, org.jhotdraw.draw.figure.BezierFigure, and org.jhotdraw.draw.figure.AbstractCompositeFigure.
References org.jhotdraw.draw.figure.AbstractFigure.changed(), org.jhotdraw.draw.figure.AbstractFigure.fireUndoableEditHappened(), org.jhotdraw.draw.figure.AbstractFigure.getEndPoint(), org.jhotdraw.draw.figure.AbstractFigure.getStartPoint(), org.jhotdraw.draw.figure.AbstractFigure.setBounds(), and org.jhotdraw.draw.figure.AbstractFigure.willChange().
setBounds() [2/2]
final void org.jhotdraw.draw.figure.AbstractFigure.setBounds (Rectangle2D.Double bounds)
Referenced by org.jhotdraw.draw.figure.AbstractAttributedFigure.read(), org.jhotdraw.draw.event.SetBoundsEdit.redo(), org.jhotdraw.draw.figure.AbstractFigure.setBounds(), and org.jhotdraw.draw.event.SetBoundsEdit.undo().
setConnectable()
void org.jhotdraw.draw.figure.AbstractFigure.setConnectable (boolean newValue)
Reimplemented in org.jhotdraw.draw.figure.LineConnectionFigure.
References org.jhotdraw.draw.figure.Figure.CONNECTABLE_PROPERTY.
Referenced by org.jhotdraw.draw.figure.GroupFigure.GroupFigure(), org.jhotdraw.draw.figure.LineFigure.LineFigure(), and org.jhotdraw.draw.figure.BezierFigure.setClosed().
setRemovable()
void org.jhotdraw.draw.figure.AbstractFigure.setRemovable (boolean newValue)
References org.jhotdraw.draw.figure.Figure.REMOVABLE_PROPERTY.
setSelectable()
void org.jhotdraw.draw.figure.AbstractFigure.setSelectable (boolean newValue)
References org.jhotdraw.draw.figure.Figure.SELECTABLE_PROPERTY.
setTransformable()
void org.jhotdraw.draw.figure.AbstractFigure.setTransformable (boolean newValue)
References org.jhotdraw.draw.figure.Figure.TRANSFORMABLE_PROPERTY.
setVisible()
void org.jhotdraw.draw.figure.AbstractFigure.setVisible (boolean newValue)
References org.jhotdraw.draw.figure.AbstractFigure.changed(), and org.jhotdraw.draw.figure.AbstractFigure.willChange().
toString()
String org.jhotdraw.draw.figure.AbstractFigure.toString ()
validate()
void org.jhotdraw.draw.figure.AbstractFigure.validate () protected
Reimplemented in org.jhotdraw.draw.figure.TextFigure, org.jhotdraw.draw.figure.LineConnectionFigure, org.jhotdraw.draw.figure.LabeledLineConnectionFigure, org.jhotdraw.draw.figure.BezierFigure, and org.jhotdraw.draw.figure.AbstractCompositeFigure.
Referenced by org.jhotdraw.draw.figure.AbstractFigure.changed().
willChange()
void org.jhotdraw.draw.figure.AbstractFigure.willChange ()
Informs that a figure is about to change something that affects the contents of its display box.
Implements org.jhotdraw.draw.figure.Figure.
Reimplemented in org.jhotdraw.draw.figure.AbstractCompositeFigure.
References org.jhotdraw.draw.figure.AbstractFigure.changingDepth, org.jhotdraw.draw.figure.AbstractFigure.fireAreaInvalidated(), and org.jhotdraw.draw.figure.AbstractFigure.invalidate().
Referenced by org.jhotdraw.draw.tool.BezierTool.addPointToFigure(), org.jhotdraw.draw.figure.BezierFigure.handleMouseClick(), org.jhotdraw.draw.figure.LineFigure.handleMouseClick(), org.jhotdraw.draw.handle.BezierControlPointHandle.keyPressed(), org.jhotdraw.draw.handle.BezierNodeHandle.keyPressed(), org.jhotdraw.draw.handle.RoundRectangleRadiusHandle.keyPressed(), org.jhotdraw.draw.tool.BezierTool.mouseReleased(), org.jhotdraw.draw.event.BezierNodeEdit.redo(), org.jhotdraw.draw.event.SetBoundsEdit.redo(), org.jhotdraw.draw.figure.AbstractFigure.setBounds(), org.jhotdraw.draw.figure.AbstractAttributedDecoratedFigure.setDecorator(), org.jhotdraw.draw.figure.AbstractFigure.setVisible(), org.jhotdraw.draw.figure.AbstractFigureNGTest.testWillChangeChangedEvents(), org.jhotdraw.draw.handle.BezierNodeHandle.trackDoubleClick(), org.jhotdraw.draw.handle.BezierControlPointHandle.trackEnd(), org.jhotdraw.draw.handle.BezierNodeHandle.trackEnd(), org.jhotdraw.draw.handle.BezierControlPointHandle.trackStep(), org.jhotdraw.draw.handle.BezierNodeHandle.trackStep(), org.jhotdraw.draw.handle.RoundRectangleRadiusHandle.trackStep(), org.jhotdraw.draw.event.BezierNodeEdit.undo(), and org.jhotdraw.draw.event.SetBoundsEdit.undo().
Member Data Documentation
changingDepth
int org.jhotdraw.draw.figure.AbstractFigure.changingDepth = 0 protected
This variable is used to prevent endless change loops. We increase its value on each invocation of willChange() and decrease it on each invocation of changed().
Referenced by org.jhotdraw.draw.figure.AbstractFigure.changed(), org.jhotdraw.draw.figure.AbstractFigure.getChangingDepth(), org.jhotdraw.draw.figure.AbstractFigure.isChanging(), org.jhotdraw.draw.figure.AbstractCompositeFigure.layout(), and org.jhotdraw.draw.figure.AbstractFigure.willChange().
listenerList
EventListenerList org.jhotdraw.draw.figure.AbstractFigure.listenerList = new EventListenerList() protected
Referenced by org.jhotdraw.draw.figure.AbstractCompositeFigure.addCompositeFigureListener(), org.jhotdraw.draw.figure.LabeledLineConnectionFigure.addCompositeFigureListener(), org.jhotdraw.draw.figure.AbstractFigure.addFigureListener(), org.jhotdraw.draw.AbstractDrawing.addUndoableEditListener(), org.jhotdraw.draw.figure.AbstractFigure.clone(), org.jhotdraw.draw.figure.AbstractFigure.fireAreaInvalidated(), org.jhotdraw.draw.figure.AbstractFigure.fireFigureAdded(), org.jhotdraw.draw.figure.AbstractCompositeFigure.fireFigureAdded(), org.jhotdraw.draw.figure.LabeledLineConnectionFigure.fireFigureAdded(), org.jhotdraw.draw.figure.AbstractFigure.fireFigureChanged(), org.jhotdraw.draw.figure.AbstractFigure.fireFigureHandlesChanged(), org.jhotdraw.draw.figure.AbstractFigure.fireFigureRemoved(), org.jhotdraw.draw.figure.AbstractCompositeFigure.fireFigureRemoved(), org.jhotdraw.draw.figure.LabeledLineConnectionFigure.fireFigureRemoved(), org.jhotdraw.draw.figure.AbstractFigure.fireFigureRequestRemove(), org.jhotdraw.draw.AbstractDrawing.fireUndoableEditHappened(), org.jhotdraw.draw.figure.AbstractCompositeFigure.removeCompositeFigureListener(), org.jhotdraw.draw.figure.LabeledLineConnectionFigure.removeCompositeFigureListener(), org.jhotdraw.draw.figure.AbstractFigure.removeFigureListener(), and org.jhotdraw.draw.AbstractDrawing.removeUndoableEditListener().
The documentation for this class was generated from the following file:
jhotdraw-core/src/main/java/org/jhotdraw/draw/figure/AbstractFigure.java