jhotdraw: org.jhotdraw.draw.figure.TextFigure Class Reference
org.jhotdraw.draw.figure.TextFigure Class Reference
Public Member Functions
TextFigure ()
TextFigure (String text)
void transform (AffineTransform tx)
void setBounds (Point2D.Double anchor, Point2D.Double lead)
boolean figureContains (Point2D.Double p)
Rectangle2D.Double getBounds ()
Dimension2DDouble getPreferredSize ()
double getBaseline ()
void restoreTransformTo (Object geometry)
Object getTransformRestoreData ()
String getText ()
void setText (String newText)
int getTextColumns ()
int getTabSize ()
TextHolderFigure getLabelFor ()
Insets2D.Double getInsets ()
Font getFont ()
Color getTextColor ()
Color getFillColor ()
void setFontSize (float size)
float getFontSize ()
boolean isEditable ()
void setEditable (boolean b)
Collection< Handle > createHandles (int detailLevel)
Tool getTool (Point2D.Double p)
void invalidate ()
void read (DOMInput in) throws IOException
void write (DOMOutput out) throws IOException
TextFigure clone ()
boolean isTextOverflow ()
Public Member Functions inherited from org.jhotdraw.draw.figure.AbstractAttributedDecoratedFigure
final void draw (Graphics2D g)
final Rectangle2D.Double getDrawingArea ()
void setDecorator (Figure newValue)
Figure getDecorator ()
final boolean contains (Point2D.Double p)
Public Member Functions inherited from org.jhotdraw.draw.figure.AbstractAttributedFigure
AbstractAttributedFigure ()
void setAttributeEnabled (AttributeKey<?> key, boolean b)
boolean isAttributeEnabled (AttributeKey<?> key)
void setAttributes (Map< AttributeKey<?>, Object > map)
Map< AttributeKey<?>, Object > getAttributes ()
Object getAttributesRestoreData ()
void restoreAttributesTo (Object restoreData)
double getStrokeMiterLimitFactor ()
Rectangle2D.Double getDrawingArea (double factor)
boolean hasAttribute (AttributeKey<?> key)
Public Member Functions inherited from org.jhotdraw.draw.figure.AbstractFigure
AbstractFigure ()
void addFigureListener (FigureListener l)
void removeFigureListener (FigureListener l)
void addNotify (Drawing d)
void removeNotify (Drawing d)
void fireAreaInvalidated ()
void fireFigureChanged ()
void remap (Map< Figure, Figure > oldToNew, boolean disconnectIfNotInMap)
Cursor getCursor (Point2D.Double p)
final void setBounds (Rectangle2D.Double bounds)
void willChange ()
void changed ()
Connector findConnector (Point2D.Double p, ConnectionFigure prototype)
boolean includes (Figure figure)
Figure findFigureInside (Point2D.Double p)
Connector findCompatibleConnector (Connector c, boolean isStart)
Collection< Action > getActions (Point2D.Double p)
boolean handleMouseClick (Point2D.Double p, MouseEvent evt, DrawingView view)
boolean handleDrop (Point2D.Double p, Collection< Figure > droppedFigures, DrawingView view)
Point2D.Double getEndPoint ()
Point2D.Double getStartPoint ()
boolean isConnectable ()
void setConnectable (boolean newValue)
boolean isSelectable ()
void setSelectable (boolean newValue)
boolean isRemovable ()
void setRemovable (boolean newValue)
boolean isTransformable ()
void setTransformable (boolean newValue)
boolean isVisible ()
void setVisible (boolean newValue)
Collection< Figure > getDecomposition ()
void requestRemove ()
int getLayer ()
String getToolTipText (Point2D.Double p)
String toString ()
Collection< Connector > getConnectors (ConnectionFigure prototype)
Public Member Functions inherited from org.jhotdraw.draw.figure.Figure
void addPropertyChangeListener (PropertyChangeListener listener)
void removePropertyChangeListener (PropertyChangeListener listener)
Protected Member Functions
void drawStroke (java.awt.Graphics2D g)
void drawFill (java.awt.Graphics2D g)
void drawText (java.awt.Graphics2D g)
TextLayout getTextLayout ()
Rectangle2D.Double getFigureDrawingArea ()
void validate ()
Protected Member Functions inherited from org.jhotdraw.draw.figure.AbstractAttributedDecoratedFigure
void drawFigure (Graphics2D g)
void drawDecorator (Graphics2D g)
void updateDecoratorBounds ()
void writeDecorator (DOMOutput out) throws IOException
void readDecorator (DOMInput in) throws IOException
Protected Member Functions inherited from org.jhotdraw.draw.figure.AbstractAttributedFigure
void writeAttributes (DOMOutput out) throws IOException
void readAttributes (DOMInput in) throws IOException
AttributeKey<?> getAttributeKey (String name)
void applyAttributesTo (Figure that)
Protected Member Functions inherited from org.jhotdraw.draw.figure.AbstractFigure
Drawing getDrawing ()
Object getLock ()
void fireAreaInvalidated (Rectangle2D.Double invalidatedArea)
void fireAreaInvalidated (FigureEvent event)
void fireFigureRequestRemove ()
void fireFigureAdded ()
void fireFigureRemoved ()
void fireFigureChanged (Rectangle2D.Double changedArea)
void fireFigureChanged (FigureEvent event)
void fireFigureHandlesChanged ()
void fireUndoableEditHappened (UndoableEdit edit)
boolean isChanging ()
int getChangingDepth ()
FontRenderContext getFontRenderContext ()
Protected Attributes
Point2D.Double origin = new Point2D.Double()
boolean editable = true
transient TextLayout textLayout
Protected Attributes inherited from org.jhotdraw.draw.figure.AbstractFigure
EventListenerList listenerList = new EventListenerList()
int changingDepth = 0
Additional Inherited Members
Static Public Attributes inherited from org.jhotdraw.draw.figure.Figure
static final String CONNECTABLE_PROPERTY = "connectable"
static final String REMOVABLE_PROPERTY = "removable"
static final String SELECTABLE_PROPERTY = "selectable"
static final String TRANSFORMABLE_PROPERTY = "transformable"
Detailed Description
A
TextHolderFigure
which holds a single line of text.
A DrawingEditor should provide the org.jhotdraw.draw.tool.TextCreationTool to create a
TextFigure
.
Author
Werner Randelshofer
Version
$Id$
Constructor & Destructor Documentation
TextFigure() [1/2]
org.jhotdraw.draw.figure.TextFigure.TextFigure ()
Creates a new instance.
Referenced by org.jhotdraw.draw.figure.TextFigure.clone().
TextFigure() [2/2]
org.jhotdraw.draw.figure.TextFigure.TextFigure (String text)
References org.jhotdraw.draw.figure.TextFigure.setText().
Member Function Documentation
clone()
TextFigure org.jhotdraw.draw.figure.TextFigure.clone ()
Returns a clone of the figure, with clones of all aggregated figures, such as children and decorators. The cloned figure does not clone the list of FigureListeners from its original.
Reimplemented from org.jhotdraw.draw.figure.AbstractAttributedDecoratedFigure.
References org.jhotdraw.draw.figure.TextFigure.clone(), org.jhotdraw.draw.figure.TextFigure.origin, org.jhotdraw.draw.figure.TextFigure.TextFigure(), and org.jhotdraw.draw.figure.TextFigure.textLayout.
Referenced by org.jhotdraw.draw.figure.TextFigure.clone().
createHandles()
Collection<Handle> org.jhotdraw.draw.figure.TextFigure.createHandles (int detailLevel)
Creates handles used to manipulate the figure.
Parameters
detailLevel The detail level of the handles. Usually this is 0 for bounding box handles and 1 for point handles. The value -1 is used by the SelectAreaTracker and the HandleTracker to highlight figures, over which the mouse pointer is hovering.
Returns
a Collection of handles
See also
Handle
Implements org.jhotdraw.draw.figure.Figure.
References org.jhotdraw.draw.locator.RelativeLocator.northEast(), org.jhotdraw.draw.locator.RelativeLocator.northWest(), org.jhotdraw.draw.locator.RelativeLocator.southEast(), and org.jhotdraw.draw.locator.RelativeLocator.southWest().
drawFill()
void org.jhotdraw.draw.figure.TextFigure.drawFill (java.awt.Graphics2D g) protected
This method is called by method draw() to draw the fill area of the figure. AbstractAttributedFigure configures the Graphics2D object with the FILL_COLOR attribute before calling this method. If the FILL_COLOR attribute is null, this method is not called.
Reimplemented from org.jhotdraw.draw.figure.AbstractAttributedFigure.
drawStroke()
void org.jhotdraw.draw.figure.TextFigure.drawStroke (java.awt.Graphics2D g) protected
This method is called by method draw() to draw the lines of the figure . AttributedFigure configures the Graphics2D object with the STROKE_COLOR attribute before calling this method. If the STROKE_COLOR attribute is null, this method is not called.
Reimplemented from org.jhotdraw.draw.figure.AbstractAttributedFigure.
drawText()
void org.jhotdraw.draw.figure.TextFigure.drawText (java.awt.Graphics2D g) protected
This method is called by method draw() to draw the text of the figure . AbstractAttributedFigure configures the Graphics2D object with the TEXT_COLOR attribute before calling this method. If the TEXT_COLOR attribute is null, this method is not called.
Reimplemented from org.jhotdraw.draw.figure.AbstractAttributedFigure.
References org.jhotdraw.draw.figure.TextFigure.getText(), org.jhotdraw.draw.figure.TextFigure.getTextLayout(), org.jhotdraw.draw.figure.TextFigure.isEditable(), and org.jhotdraw.draw.figure.TextFigure.origin.
figureContains()
boolean org.jhotdraw.draw.figure.TextFigure.figureContains (Point2D.Double p)
Reimplemented from org.jhotdraw.draw.figure.AbstractAttributedDecoratedFigure.
References org.jhotdraw.draw.figure.AbstractAttributedDecoratedFigure.contains(), and org.jhotdraw.draw.figure.TextFigure.getBounds().
getBaseline()
double org.jhotdraw.draw.figure.TextFigure.getBaseline ()
Gets the baseline of the first line of text, relative to the upper left corner of the figure bounds.
Implements org.jhotdraw.draw.figure.TextHolderFigure.
References org.jhotdraw.draw.figure.TextFigure.getBounds(), org.jhotdraw.draw.figure.TextFigure.getTextLayout(), and org.jhotdraw.draw.figure.TextFigure.origin.
getBounds()
Rectangle2D.Double org.jhotdraw.draw.figure.TextFigure.getBounds ()
Returns the untransformed logical bounds of the figure as a Rectangle.
The bounds are used by Handle objects for adjusting the figure and for aligning the figure on a grid.
Implements org.jhotdraw.draw.figure.Figure.
References org.jhotdraw.draw.figure.TextFigure.getTextLayout(), and org.jhotdraw.draw.figure.TextFigure.origin.
Referenced by org.jhotdraw.draw.figure.TextFigure.figureContains(), org.jhotdraw.draw.figure.TextFigure.getBaseline(), org.jhotdraw.draw.figure.TextFigure.getFigureDrawingArea(), org.jhotdraw.draw.figure.TextFigure.getPreferredSize(), and org.jhotdraw.draw.figure.TextFigure.write().
getFigureDrawingArea()
Rectangle2D.Double org.jhotdraw.draw.figure.TextFigure.getFigureDrawingArea () protected
Gets the drawing area without taking the decorator into account.
Reimplemented from org.jhotdraw.draw.figure.AbstractAttributedDecoratedFigure.
References org.jhotdraw.draw.figure.TextFigure.getBounds(), org.jhotdraw.draw.figure.TextFigure.getText(), org.jhotdraw.draw.figure.TextFigure.getTextLayout(), and org.jhotdraw.draw.figure.TextFigure.origin.
getFillColor()
Color org.jhotdraw.draw.figure.TextFigure.getFillColor ()
Returns the fill color to be used by a text editor for editing this Figure.
Implements org.jhotdraw.draw.figure.TextHolderFigure.
getFont()
Font org.jhotdraw.draw.figure.TextFigure.getFont ()
Returns the font to be used by a text editor for editing this Figure.
Implements org.jhotdraw.draw.figure.TextHolderFigure.
References org.jhotdraw.draw.AttributeKeys.getFont().
Referenced by org.jhotdraw.draw.figure.TextFigure.getTextLayout().
getFontSize()
float org.jhotdraw.draw.figure.TextFigure.getFontSize ()
Gets the font size of the text held by the TextHolderFigure.
Implements org.jhotdraw.draw.figure.TextHolderFigure.
getInsets()
Insets2D.Double org.jhotdraw.draw.figure.TextFigure.getInsets ()
Returns Insets to be used by the text editor relative to the handle bounds of the figure.
Implements org.jhotdraw.draw.figure.TextHolderFigure.
getLabelFor()
TextHolderFigure org.jhotdraw.draw.figure.TextFigure.getLabelFor ()
Sometimes we want to use a TextHolderFigure as a label for another TextHolderFigure. Returns the TextHolderFigure that should be really used.
Implements org.jhotdraw.draw.figure.TextHolderFigure.
Reimplemented in org.jhotdraw.draw.figure.LabelFigure.
getPreferredSize()
Dimension2DDouble org.jhotdraw.draw.figure.TextFigure.getPreferredSize ()
The preferred size is used by Layouter to determine the preferred size of a Figure. For most Figure's this is the same as the dimensions returned by getBounds.
Implements org.jhotdraw.draw.figure.Figure.
References org.jhotdraw.draw.figure.TextFigure.getBounds().
getTabSize()
int org.jhotdraw.draw.figure.TextFigure.getTabSize ()
Gets the number of characters used to expand tabs.
Implements org.jhotdraw.draw.figure.TextHolderFigure.
getText()
String org.jhotdraw.draw.figure.TextFigure.getText ()
Gets the text shown by the text figure.
Implements org.jhotdraw.draw.figure.TextHolderFigure.
Referenced by org.jhotdraw.draw.figure.TextFigure.drawText(), org.jhotdraw.draw.figure.TextFigure.getFigureDrawingArea(), and org.jhotdraw.draw.figure.TextFigure.getTextLayout().
getTextColor()
Color org.jhotdraw.draw.figure.TextFigure.getTextColor ()
Returns the text color to be used by a text editor for editing this Figure.
Implements org.jhotdraw.draw.figure.TextHolderFigure.
getTextColumns()
int org.jhotdraw.draw.figure.TextFigure.getTextColumns ()
Gets the number of columns to be overlaid when the figure is edited.
Implements org.jhotdraw.draw.figure.TextHolderFigure.
getTextLayout()
TextLayout org.jhotdraw.draw.figure.TextFigure.getTextLayout () protected
References org.jhotdraw.draw.figure.TextFigure.getFont(), org.jhotdraw.draw.figure.AbstractFigure.getFontRenderContext(), org.jhotdraw.draw.figure.TextFigure.getText(), and org.jhotdraw.draw.figure.TextFigure.textLayout.
Referenced by org.jhotdraw.draw.figure.TextFigure.drawText(), org.jhotdraw.draw.figure.TextFigure.getBaseline(), org.jhotdraw.draw.figure.TextFigure.getBounds(), and org.jhotdraw.draw.figure.TextFigure.getFigureDrawingArea().
getTool()
Tool org.jhotdraw.draw.figure.TextFigure.getTool (Point2D.Double p)
Returns a specialized tool for the given coordinate.
Returns null, if no specialized tool is available.
Implements org.jhotdraw.draw.figure.Figure.
Reimplemented in org.jhotdraw.draw.figure.LabelFigure.
References org.jhotdraw.draw.figure.AbstractAttributedDecoratedFigure.contains(), and org.jhotdraw.draw.figure.TextFigure.isEditable().
getTransformRestoreData()
Object org.jhotdraw.draw.figure.TextFigure.getTransformRestoreData ()
Gets data which can be used to restore the transformation of the figure without loss of precision, after a transform has been applied to it.
See also
transform(AffineTransform)
Implements org.jhotdraw.draw.figure.Figure.
References org.jhotdraw.draw.figure.TextFigure.origin.
invalidate()
void org.jhotdraw.draw.figure.TextFigure.invalidate ()
Invalidates cached data of the Figure. This method must execute fast, because it can be called very often.
Reimplemented from org.jhotdraw.draw.figure.AbstractFigure.
References org.jhotdraw.draw.figure.TextFigure.textLayout.
Referenced by org.jhotdraw.draw.figure.TextFigure.read().
isEditable()
boolean org.jhotdraw.draw.figure.TextFigure.isEditable ()
Returns true if the text of the TextHolderFigure can be edited.
Implements org.jhotdraw.draw.figure.TextHolderFigure.
References org.jhotdraw.draw.figure.TextFigure.editable.
Referenced by org.jhotdraw.draw.figure.TextFigure.drawText(), and org.jhotdraw.draw.figure.TextFigure.getTool().
isTextOverflow()
boolean org.jhotdraw.draw.figure.TextFigure.isTextOverflow ()
Returns true, if the text does not fit into the bounds of the Figure.
Implements org.jhotdraw.draw.figure.TextHolderFigure.
read()
void org.jhotdraw.draw.figure.TextFigure.read (DOMInput in) throws IOException
Reimplemented from org.jhotdraw.draw.figure.AbstractAttributedDecoratedFigure.
References org.jhotdraw.draw.figure.TextFigure.invalidate(), org.jhotdraw.draw.figure.AbstractAttributedFigure.readAttributes(), org.jhotdraw.draw.figure.AbstractAttributedDecoratedFigure.readDecorator(), and org.jhotdraw.draw.figure.TextFigure.setBounds().
restoreTransformTo()
void org.jhotdraw.draw.figure.TextFigure.restoreTransformTo (Object restoreData)
Restores the transform of the figure to a previously stored state.
Implements org.jhotdraw.draw.figure.Figure.
References org.jhotdraw.draw.figure.TextFigure.origin.
setBounds()
void org.jhotdraw.draw.figure.TextFigure.setBounds (Point2D.Double start, Point2D.Double end)
Sets the logical and untransformed bounds of the figure.
This is used by Tool's which create a new Figure and by Tool's which connect a Figure to another Figure.
This is a basic operation which does not fire events. Use the following code sequence, if you need event firing:
figure.willChange();
figure.setBounds(...);
figure.changed();
Parameters
start the start point of the bounds
end the end point of the bounds
See also
getBounds
Implements org.jhotdraw.draw.figure.Figure.
References org.jhotdraw.draw.figure.TextFigure.origin.
Referenced by org.jhotdraw.draw.figure.TextFigure.read().
setEditable()
void org.jhotdraw.draw.figure.TextFigure.setEditable (boolean b)
Referenced by org.jhotdraw.draw.figure.LabelFigure.LabelFigure().
setFontSize()
void org.jhotdraw.draw.figure.TextFigure.setFontSize (float size)
Sets the font size of the text held by the TextHolderFigure.
Implements org.jhotdraw.draw.figure.TextHolderFigure.
setText()
void org.jhotdraw.draw.figure.TextFigure.setText (String newText)
Sets the text shown by the text figure. This is a convenience method for calling
set(TEXT,newText)
.
Implements org.jhotdraw.draw.figure.TextHolderFigure.
Referenced by org.jhotdraw.draw.figure.LabelFigure.LabelFigure(), and org.jhotdraw.draw.figure.TextFigure.TextFigure().
transform()
void org.jhotdraw.draw.figure.TextFigure.transform (AffineTransform tx)
Transforms the shape of the Figure. Transformations using double precision arithmethics are inherently lossy operations. Therefore it is recommended to use getTransformRestoreData() restoreTransformTo() to provide lossless undo/redo functionality.
This is a basic operation which does not fire events. Use the following code sequence, if you need event firing:
figure.willChange();
figure.transform(...);
figure.changed();
Parameters
tx The transformation.
See also
getTransformRestoreData
restoreTransformTo
Implements org.jhotdraw.draw.figure.Figure.
References org.jhotdraw.draw.figure.TextFigure.origin.
validate()
void org.jhotdraw.draw.figure.TextFigure.validate () protected
Reimplemented from org.jhotdraw.draw.figure.AbstractFigure.
References org.jhotdraw.draw.figure.TextFigure.textLayout.
write()
void org.jhotdraw.draw.figure.TextFigure.write (DOMOutput out) throws IOException
Reimplemented from org.jhotdraw.draw.figure.AbstractAttributedDecoratedFigure.
References org.jhotdraw.draw.figure.TextFigure.getBounds(), org.jhotdraw.draw.figure.AbstractAttributedFigure.writeAttributes(), and org.jhotdraw.draw.figure.AbstractAttributedDecoratedFigure.writeDecorator().
Member Data Documentation
editable
boolean org.jhotdraw.draw.figure.TextFigure.editable = true protected
Referenced by org.jhotdraw.draw.figure.TextFigure.isEditable().
origin
Point2D.Double org.jhotdraw.draw.figure.TextFigure.origin = new Point2D.Double() protected
Referenced by org.jhotdraw.draw.figure.TextFigure.clone(), org.jhotdraw.draw.figure.TextFigure.drawText(), org.jhotdraw.draw.figure.TextFigure.getBaseline(), org.jhotdraw.draw.figure.TextFigure.getBounds(), org.jhotdraw.draw.figure.TextFigure.getFigureDrawingArea(), org.jhotdraw.draw.figure.TextFigure.getTransformRestoreData(), org.jhotdraw.draw.figure.TextFigure.restoreTransformTo(), org.jhotdraw.draw.figure.TextFigure.setBounds(), and org.jhotdraw.draw.figure.TextFigure.transform().
textLayout
transient TextLayout org.jhotdraw.draw.figure.TextFigure.textLayout protected
Referenced by org.jhotdraw.draw.figure.TextFigure.clone(), org.jhotdraw.draw.figure.TextFigure.getTextLayout(), org.jhotdraw.draw.figure.TextFigure.invalidate(), and org.jhotdraw.draw.figure.TextFigure.validate().
The documentation for this class was generated from the following file:
jhotdraw-core/src/main/java/org/jhotdraw/draw/figure/TextFigure.java