jhotdraw: org.jhotdraw.draw.io.DOMStorableInputOutputFormat Class Reference
org.jhotdraw.draw.io.DOMStorableInputOutputFormat Class Reference
Public Member Functions
DOMStorableInputOutputFormat (DOMFactory factory)
DOMStorableInputOutputFormat (DOMFactory factory, String description, String fileExtension, String mimeType)
javax.swing.filechooser.FileFilter getFileFilter ()
JComponent getOutputFormatAccessory ()
JComponent getInputFormatAccessory ()
String getFileExtension ()
boolean isDataFlavorSupported (DataFlavor flavor)
void write (URI uri, Drawing drawing) throws IOException
void write (File file, Drawing drawing) throws IOException
void write (OutputStream out, Drawing drawing) throws IOException
void read (URI uri, Drawing drawing) throws IOException
void read (URI uri, Drawing drawing, boolean replace) throws IOException
void read (File file, Drawing drawing) throws IOException
void read (File file, Drawing drawing, boolean replace) throws IOException
void read (InputStream in, Drawing drawing, boolean replace) throws IOException
void read (Transferable t, Drawing drawing, boolean replace) throws UnsupportedFlavorException, IOException
Transferable createTransferable (Drawing drawing, List< Figure > figures, double scaleFactor) throws IOException
Protected Member Functions
void read (URL url, InputStream in, Drawing drawing, LinkedList< Figure > figures) throws IOException
Detailed Description
An OutputFormat that can write Drawings with DOMStorable Figure's.
This class is here to support quick-and-dirty implementations of drawings that can be read and written from/to output streams. For example, in student projects.
This class should no be used as a means to implement long-term storage of drawings, since it does not support structural changes that might occur in a drawing application over time.
Author
Werner Randelshofer
Version
$Id$
Constructor & Destructor Documentation
DOMStorableInputOutputFormat() [1/2]
org.jhotdraw.draw.io.DOMStorableInputOutputFormat.DOMStorableInputOutputFormat (DOMFactory factory)
Creates a new instance with format name "Drawing", file extension "xml" and mime type "image/x-jhotdraw".
DOMStorableInputOutputFormat() [2/2]
org.jhotdraw.draw.io.DOMStorableInputOutputFormat.DOMStorableInputOutputFormat (DOMFactory factory, String description, String fileExtension, String mimeType)
Creates a new instance using the specified parameters.
Parameters
factory The factory for creating Figures from XML elements.
description The format description to be used for the file filter.
fileExtension The file extension to be used for file filter.
mimeType The Mime Type is used for clipboard access.
Member Function Documentation
createTransferable()
Transferable org.jhotdraw.draw.io.DOMStorableInputOutputFormat.createTransferable (Drawing drawing, List< Figure > figures, double scaleFactor) throws IOException
Creates a Transferable for the specified list of Figures.
Parameters
drawing The drawing.
figures A list of figures of the drawing.
scaleFactor The factor to be used, when the Transferable creates an image with a fixed size from the figures.
Returns
The Transferable.
Implements org.jhotdraw.draw.io.OutputFormat.
getFileExtension()
String org.jhotdraw.draw.io.DOMStorableInputOutputFormat.getFileExtension ()
Returns the file extension for the output format. The file extension should be appended to a file name when storing a Drawing with the specified file format.
Implements org.jhotdraw.draw.io.OutputFormat.
getFileFilter()
javax.swing.filechooser.FileFilter org.jhotdraw.draw.io.DOMStorableInputOutputFormat.getFileFilter ()
Return a FileFilter that can be used to identify files which can be read with this input format. Typically, each input format has its own recognizable file naming convention.
Returns
FileFilter to be used with a javax.swing.JFileChooser
Implements org.jhotdraw.draw.io.InputFormat.
getInputFormatAccessory()
JComponent org.jhotdraw.draw.io.DOMStorableInputOutputFormat.getInputFormatAccessory ()
Return a JFileChooser accessory that can be used to customize the input format.
Returns
A JFileChooser accessory to be used with a javax.swing.JFileChooser Returns null, if no accessory is provided for this format.
Implements org.jhotdraw.draw.io.InputFormat.
getOutputFormatAccessory()
JComponent org.jhotdraw.draw.io.DOMStorableInputOutputFormat.getOutputFormatAccessory ()
Return a JFileChooser accessory that can be used to customize the output format.
Returns
A JFileChooser accessory to be used with a javax.swing.JFileChooser Returns null, if no accessory is provided for this format.
Implements org.jhotdraw.draw.io.OutputFormat.
isDataFlavorSupported()
boolean org.jhotdraw.draw.io.DOMStorableInputOutputFormat.isDataFlavorSupported (DataFlavor flavor)
Returns true, if this InputFormat can readFigures TransferData using the specified DataFlavor.
Parameters
flavor A DataFlavor.
Implements org.jhotdraw.draw.io.InputFormat.
read() [1/7]
void org.jhotdraw.draw.io.DOMStorableInputOutputFormat.read (File file, Drawing drawing) throws IOException
References org.jhotdraw.draw.io.DOMStorableInputOutputFormat.read().
read() [2/7]
void org.jhotdraw.draw.io.DOMStorableInputOutputFormat.read (File file, Drawing drawing, boolean replace) throws IOException
References org.jhotdraw.draw.io.DOMStorableInputOutputFormat.read().
read() [3/7]
void org.jhotdraw.draw.io.DOMStorableInputOutputFormat.read (InputStream in, Drawing drawing, boolean replace) throws IOException
Reads figures from a file and adds them to the specified drawing.
Parameters
in The input stream.
drawing The drawing.
replace Set this to true, if the contents of the stream replaces the contents of the drawing (for example, when loading a drawing from a stream). Set this to false, to add the contents of the file to the drawing (for example, when the stream has been dropped into the drawing view).
Implements org.jhotdraw.draw.io.InputFormat.
read() [4/7]
void org.jhotdraw.draw.io.DOMStorableInputOutputFormat.read (Transferable t, Drawing drawing, boolean replace) throws UnsupportedFlavorException, IOException
Reads figures from the specified Transferable and adds them to the specified drawing.
Parameters
t The Transferable.
drawing The drawing.
replace Set this to true, if the contents of the transferable replaces the contents of the drawing (for example, when loading a drawing from a transferable). Set this to false, to add the contents of the transferable to the drawing (for example, when the transferable has been dropped or pasted into the drawing view).
Implements org.jhotdraw.draw.io.InputFormat.
read() [5/7]
void org.jhotdraw.draw.io.DOMStorableInputOutputFormat.read (URI uri, Drawing drawing) throws IOException
Reads figures from an URI and replaces the children of the drawing with them.
This is a convenience method for calling read(URI,Drawing,true).
Parameters
uri The URI.
drawing The drawing.
Implements org.jhotdraw.draw.io.InputFormat.
References org.jhotdraw.draw.io.DOMStorableInputOutputFormat.read().
read() [6/7]
void org.jhotdraw.draw.io.DOMStorableInputOutputFormat.read (URI uri, Drawing drawing, boolean replace) throws IOException
Reads figures from an URI and adds them to the specified drawing.
Parameters
uri The URI.
drawing The drawing.
replace Set this to true, if the contents of the file replaces the contents of the drawing (for example, when loading a drawing from a file). Set this to false, to add the contents of the file to the drawing (for example, when the file has been dropped into the drawing view).
Implements org.jhotdraw.draw.io.InputFormat.
References org.jhotdraw.draw.io.DOMStorableInputOutputFormat.read().
read() [7/7]
void org.jhotdraw.draw.io.DOMStorableInputOutputFormat.read (URL url, InputStream in, Drawing drawing, LinkedList< Figure > figures) throws IOException protected
Reads a list of figures into the specified drawing. This method expects that there is a child element named "figures" in the element that represents the drawing.
Referenced by org.jhotdraw.draw.io.DOMStorableInputOutputFormat.read().
write() [1/3]
void org.jhotdraw.draw.io.DOMStorableInputOutputFormat.write (File file, Drawing drawing) throws IOException
References org.jhotdraw.draw.io.DOMStorableInputOutputFormat.write().
write() [2/3]
void org.jhotdraw.draw.io.DOMStorableInputOutputFormat.write (OutputStream out, Drawing drawing) throws IOException
Writes a Drawing into an output stream.
Parameters
out The output stream.
drawing The drawing.
Implements org.jhotdraw.draw.io.OutputFormat.
write() [3/3]
void org.jhotdraw.draw.io.DOMStorableInputOutputFormat.write (URI uri, Drawing drawing) throws IOException
Writes a Drawing into an URI.
Parameters
uri The uri.
drawing The drawing.
Implements org.jhotdraw.draw.io.OutputFormat.
Referenced by org.jhotdraw.draw.io.DOMStorableInputOutputFormat.write().
The documentation for this class was generated from the following file:
jhotdraw-core/src/main/java/org/jhotdraw/draw/io/DOMStorableInputOutputFormat.java