jhotdraw: org.jhotdraw.draw.liner.CurvedLiner Class Reference
org.jhotdraw.draw.liner.CurvedLiner Class Reference
Public Member Functions
CurvedLiner ()
CurvedLiner (double slantSize)
Collection< Handle > createHandles (BezierPath path)
void lineout (ConnectionFigure figure)
void read (DOMInput in)
void write (DOMOutput out)
Liner clone ()
Detailed Description
A Liner that constrains a connection to a curved line.
Author
Werner Randelshofer
Version
$Id$
Constructor & Destructor Documentation
CurvedLiner() [1/2]
org.jhotdraw.draw.liner.CurvedLiner.CurvedLiner ()
Creates a new instance.
CurvedLiner() [2/2]
org.jhotdraw.draw.liner.CurvedLiner.CurvedLiner (double slantSize)
Member Function Documentation
clone()
Liner org.jhotdraw.draw.liner.CurvedLiner.clone ()
Implements org.jhotdraw.draw.liner.Liner.
References org.jhotdraw.draw.liner.Liner.clone().
createHandles()
Collection<Handle> org.jhotdraw.draw.liner.CurvedLiner.createHandles (BezierPath path)
Creates Handle's for the Liner. The ConnectionFigure can provide these handles to the user, in order to let her control the lineout.
Parameters
path The path for which to create handles.
Implements org.jhotdraw.draw.liner.Liner.
lineout()
void org.jhotdraw.draw.liner.CurvedLiner.lineout (ConnectionFigure figure)
Layouts the Path. This may alter the number and type of points in the Path.
Parameters
figure The ConnectionFigure to be lined out.
Implements org.jhotdraw.draw.liner.Liner.
References org.jhotdraw.draw.connector.Connector.findEnd(), org.jhotdraw.draw.connector.Connector.findStart(), org.jhotdraw.draw.connector.Connector.getBounds(), org.jhotdraw.draw.figure.ConnectionFigure.getEndConnector(), org.jhotdraw.draw.figure.ConnectionFigure.getEndFigure(), org.jhotdraw.draw.figure.ConnectionFigure.getStartConnector(), and org.jhotdraw.draw.figure.ConnectionFigure.getStartFigure().
read()
void org.jhotdraw.draw.liner.CurvedLiner.read (DOMInput in)
write()
void org.jhotdraw.draw.liner.CurvedLiner.write (DOMOutput out)
The documentation for this class was generated from the following file:
jhotdraw-core/src/main/java/org/jhotdraw/draw/liner/CurvedLiner.java