jhotdraw: org.jhotdraw.draw.locator.RelativeDecoratorLocator Class Reference
org.jhotdraw.draw.locator.RelativeDecoratorLocator Class Reference
Public Member Functions
RelativeDecoratorLocator ()
RelativeDecoratorLocator (double relativeX, double relativeY)
RelativeDecoratorLocator (double relativeX, double relativeY, boolean isQuadratic)
java.awt.geom.Point2D.Double locate (Figure owner)
Public Member Functions inherited from org.jhotdraw.draw.locator.RelativeLocator
RelativeLocator ()
RelativeLocator (double relativeX, double relativeY)
RelativeLocator (double relativeX, double relativeY, boolean isTransform)
void write (DOMOutput out)
void read (DOMInput in)
boolean equals (Object obj)
int hashCode ()
Public Member Functions inherited from org.jhotdraw.draw.locator.AbstractLocator
AbstractLocator ()
Point2D.Double locate (Figure owner, Figure dependent)
Static Public Member Functions
static Locator east ()
static Locator north ()
static Locator west ()
static Locator northEast ()
static Locator northWest ()
static Locator south ()
static Locator southEast ()
static Locator southWest ()
static Locator center ()
Static Public Member Functions inherited from org.jhotdraw.draw.locator.RelativeLocator
static Locator east (boolean isTransform)
static Locator north (boolean isTransform)
static Locator west (boolean isTransform)
static Locator northEast (boolean isTransform)
static Locator northWest (boolean isTransform)
static Locator south (boolean isTransform)
static Locator southEast (boolean isTransform)
static Locator southWest (boolean isTransform)
static Locator center (boolean isTransform)
Additional Inherited Members
Protected Attributes inherited from org.jhotdraw.draw.locator.RelativeLocator
double relativeX
double relativeY
boolean isTransform
Detailed Description
A locator that specfies a point that is relative to the bounds of a figures decorator.
Design Patterns
Strategy
RelativeDecoratorLocator
encapsulates a strategy for locating a point on a decorator.
Component: DecoratedFigure; Strategy: RelativeDecoratorLocator.
Author
Werner Randelshofer
Version
$Id$
Constructor & Destructor Documentation
RelativeDecoratorLocator() [1/3]
org.jhotdraw.draw.locator.RelativeDecoratorLocator.RelativeDecoratorLocator ()
Referenced by org.jhotdraw.draw.locator.RelativeDecoratorLocator.center(), org.jhotdraw.draw.locator.RelativeDecoratorLocator.east(), org.jhotdraw.draw.locator.RelativeDecoratorLocator.north(), org.jhotdraw.draw.locator.RelativeDecoratorLocator.northEast(), org.jhotdraw.draw.locator.RelativeDecoratorLocator.northWest(), org.jhotdraw.draw.locator.RelativeDecoratorLocator.south(), org.jhotdraw.draw.locator.RelativeDecoratorLocator.southEast(), org.jhotdraw.draw.locator.RelativeDecoratorLocator.southWest(), and org.jhotdraw.draw.locator.RelativeDecoratorLocator.west().
RelativeDecoratorLocator() [2/3]
org.jhotdraw.draw.locator.RelativeDecoratorLocator.RelativeDecoratorLocator (double relativeX, double relativeY)
Creates a new instance.
References org.jhotdraw.draw.locator.RelativeLocator.relativeX, and org.jhotdraw.draw.locator.RelativeLocator.relativeY.
RelativeDecoratorLocator() [3/3]
org.jhotdraw.draw.locator.RelativeDecoratorLocator.RelativeDecoratorLocator (double relativeX, double relativeY, boolean isQuadratic)
References org.jhotdraw.draw.locator.RelativeLocator.relativeX, and org.jhotdraw.draw.locator.RelativeLocator.relativeY.
Member Function Documentation
center()
static Locator org.jhotdraw.draw.locator.RelativeDecoratorLocator.center () static
Center.
Reimplemented from org.jhotdraw.draw.locator.RelativeLocator.
References org.jhotdraw.draw.locator.RelativeDecoratorLocator.RelativeDecoratorLocator().
east()
static Locator org.jhotdraw.draw.locator.RelativeDecoratorLocator.east () static
Non-transforming East.
Reimplemented from org.jhotdraw.draw.locator.RelativeLocator.
References org.jhotdraw.draw.locator.RelativeDecoratorLocator.RelativeDecoratorLocator().
locate()
java.awt.geom.Point2D.Double org.jhotdraw.draw.locator.RelativeDecoratorLocator.locate (Figure owner)
Locates a position on the provided figure.
Returns
a point on the figure.
Reimplemented from org.jhotdraw.draw.locator.RelativeLocator.
References org.jhotdraw.draw.figure.Figure.getBounds(), org.jhotdraw.draw.locator.RelativeLocator.relativeX, and org.jhotdraw.draw.locator.RelativeLocator.relativeY.
north()
static Locator org.jhotdraw.draw.locator.RelativeDecoratorLocator.north () static
North.
Reimplemented from org.jhotdraw.draw.locator.RelativeLocator.
References org.jhotdraw.draw.locator.RelativeDecoratorLocator.RelativeDecoratorLocator().
northEast()
static Locator org.jhotdraw.draw.locator.RelativeDecoratorLocator.northEast () static
North east.
Reimplemented from org.jhotdraw.draw.locator.RelativeLocator.
References org.jhotdraw.draw.locator.RelativeDecoratorLocator.RelativeDecoratorLocator().
northWest()
static Locator org.jhotdraw.draw.locator.RelativeDecoratorLocator.northWest () static
North west.
Reimplemented from org.jhotdraw.draw.locator.RelativeLocator.
References org.jhotdraw.draw.locator.RelativeDecoratorLocator.RelativeDecoratorLocator().
south()
static Locator org.jhotdraw.draw.locator.RelativeDecoratorLocator.south () static
South.
Reimplemented from org.jhotdraw.draw.locator.RelativeLocator.
References org.jhotdraw.draw.locator.RelativeDecoratorLocator.RelativeDecoratorLocator().
southEast()
static Locator org.jhotdraw.draw.locator.RelativeDecoratorLocator.southEast () static
South east.
Reimplemented from org.jhotdraw.draw.locator.RelativeLocator.
References org.jhotdraw.draw.locator.RelativeDecoratorLocator.RelativeDecoratorLocator().
southWest()
static Locator org.jhotdraw.draw.locator.RelativeDecoratorLocator.southWest () static
South west.
Reimplemented from org.jhotdraw.draw.locator.RelativeLocator.
References org.jhotdraw.draw.locator.RelativeDecoratorLocator.RelativeDecoratorLocator().
west()
static Locator org.jhotdraw.draw.locator.RelativeDecoratorLocator.west () static
West.
Reimplemented from org.jhotdraw.draw.locator.RelativeLocator.
References org.jhotdraw.draw.locator.RelativeDecoratorLocator.RelativeDecoratorLocator().
The documentation for this class was generated from the following file:
jhotdraw-core/src/main/java/org/jhotdraw/draw/locator/RelativeDecoratorLocator.java