jhotdraw: org.jhotdraw.draw.io.TextInputFormat Class Reference
org.jhotdraw.draw.io.TextInputFormat Class Reference
Public Member Functions
TextInputFormat (TextHolderFigure prototype)
TextInputFormat (TextHolderFigure prototype, String formatName, String description, String fileExtension, boolean isMultiline)
javax.swing.filechooser.FileFilter getFileFilter ()
String getFileExtension ()
JComponent getInputFormatAccessory ()
void read (URI uri, Drawing drawing) throws IOException
void read (URI uri, Drawing drawing, boolean replace) throws IOException
void read (File file, Drawing drawing) throws IOException
void read (File file, Drawing drawing, boolean replace) throws IOException
void read (InputStream in, Drawing drawing, boolean replace) throws IOException
LinkedList< Figure > createTextHolderFigures (InputStream in) throws IOException
boolean isDataFlavorSupported (DataFlavor flavor)
void read (Transferable t, Drawing drawing, boolean replace) throws UnsupportedFlavorException, IOException
Detailed Description
An input format for importing text into a drawing.
This class uses the prototype design pattern. A TextHolderFigure figure is used as a prototype for creating a figure that holds the imported text.
For text that spans multiple lines, TextInputFormat can either add all the text to the same Figure, or it can create a new Figure for each line.
Design Patterns
Prototype
The text input format creates new text holder figures by cloning a prototype figure object and assigning an image to it, which was read from data input. That's the reason why
Figure
extends the
Cloneable
interface.
Prototype: TextHolderFigure; Client: org.jhotdraw.draw.io.TextInputFormat.
Author
Werner Randelshofer
Version
$Id$
Constructor & Destructor Documentation
TextInputFormat() [1/2]
org.jhotdraw.draw.io.TextInputFormat.TextInputFormat (TextHolderFigure prototype)
Creates a new image output format for text, for a figure that can not. hold multiple lines of text.
TextInputFormat() [2/2]
org.jhotdraw.draw.io.TextInputFormat.TextInputFormat (TextHolderFigure prototype, String formatName, String description, String fileExtension, boolean isMultiline)
Creates a new image output format for the specified image format.
Parameters
formatName The format name for the javax.imageio.ImageIO object.
description The format description to be used for the file filter.
fileExtension The file extension to be used for file filter.
isMultiline Set this to true, if the TextHolderFigure can hold multiple lines of text. If this is true, multiple lines of text are added to the same figure. If this is false, a new Figure is created for each line of text.
Member Function Documentation
createTextHolderFigures()
LinkedList<Figure> org.jhotdraw.draw.io.TextInputFormat.createTextHolderFigures (InputStream in) throws IOException
References org.jhotdraw.draw.figure.Figure.clone(), org.jhotdraw.draw.figure.Figure.getPreferredSize(), org.jhotdraw.draw.figure.Figure.setBounds(), and org.jhotdraw.draw.figure.TextHolderFigure.setText().
Referenced by org.jhotdraw.draw.io.TextInputFormat.read().
getFileExtension()
String org.jhotdraw.draw.io.TextInputFormat.getFileExtension ()
getFileFilter()
javax.swing.filechooser.FileFilter org.jhotdraw.draw.io.TextInputFormat.getFileFilter ()
Return a FileFilter that can be used to identify files which can be read with this input format. Typically, each input format has its own recognizable file naming convention.
Returns
FileFilter to be used with a javax.swing.JFileChooser
Implements org.jhotdraw.draw.io.InputFormat.
getInputFormatAccessory()
JComponent org.jhotdraw.draw.io.TextInputFormat.getInputFormatAccessory ()
Return a JFileChooser accessory that can be used to customize the input format.
Returns
A JFileChooser accessory to be used with a javax.swing.JFileChooser Returns null, if no accessory is provided for this format.
Implements org.jhotdraw.draw.io.InputFormat.
isDataFlavorSupported()
boolean org.jhotdraw.draw.io.TextInputFormat.isDataFlavorSupported (DataFlavor flavor)
Returns true, if this InputFormat can readFigures TransferData using the specified DataFlavor.
Parameters
flavor A DataFlavor.
Implements org.jhotdraw.draw.io.InputFormat.
read() [1/6]
void org.jhotdraw.draw.io.TextInputFormat.read (File file, Drawing drawing) throws IOException
References org.jhotdraw.draw.io.TextInputFormat.read().
read() [2/6]
void org.jhotdraw.draw.io.TextInputFormat.read (File file, Drawing drawing, boolean replace) throws IOException
References org.jhotdraw.draw.io.TextInputFormat.read().
read() [3/6]
void org.jhotdraw.draw.io.TextInputFormat.read (InputStream in, Drawing drawing, boolean replace) throws IOException
Reads figures from a file and adds them to the specified drawing.
Parameters
in The input stream.
drawing The drawing.
replace Set this to true, if the contents of the stream replaces the contents of the drawing (for example, when loading a drawing from a stream). Set this to false, to add the contents of the file to the drawing (for example, when the stream has been dropped into the drawing view).
Implements org.jhotdraw.draw.io.InputFormat.
References org.jhotdraw.draw.io.TextInputFormat.createTextHolderFigures().
read() [4/6]
void org.jhotdraw.draw.io.TextInputFormat.read (Transferable t, Drawing drawing, boolean replace) throws UnsupportedFlavorException, IOException
Reads figures from the specified Transferable and adds them to the specified drawing.
Parameters
t The Transferable.
drawing The drawing.
replace Set this to true, if the contents of the transferable replaces the contents of the drawing (for example, when loading a drawing from a transferable). Set this to false, to add the contents of the transferable to the drawing (for example, when the transferable has been dropped or pasted into the drawing view).
Implements org.jhotdraw.draw.io.InputFormat.
References org.jhotdraw.draw.figure.Figure.changed(), org.jhotdraw.draw.figure.Figure.clone(), org.jhotdraw.draw.figure.Figure.getPreferredSize(), org.jhotdraw.draw.figure.Figure.setBounds(), org.jhotdraw.draw.figure.TextHolderFigure.setText(), and org.jhotdraw.draw.figure.Figure.willChange().
read() [5/6]
void org.jhotdraw.draw.io.TextInputFormat.read (URI uri, Drawing drawing) throws IOException
Reads figures from an URI and replaces the children of the drawing with them.
This is a convenience method for calling read(URI,Drawing,true).
Parameters
uri The URI.
drawing The drawing.
Implements org.jhotdraw.draw.io.InputFormat.
Referenced by org.jhotdraw.draw.io.TextInputFormat.read().
read() [6/6]
void org.jhotdraw.draw.io.TextInputFormat.read (URI uri, Drawing drawing, boolean replace) throws IOException
Reads figures from an URI and adds them to the specified drawing.
Parameters
uri The URI.
drawing The drawing.
replace Set this to true, if the contents of the file replaces the contents of the drawing (for example, when loading a drawing from a file). Set this to false, to add the contents of the file to the drawing (for example, when the file has been dropped into the drawing view).
Implements org.jhotdraw.draw.io.InputFormat.
References org.jhotdraw.draw.io.TextInputFormat.read().
The documentation for this class was generated from the following file:
jhotdraw-core/src/main/java/org/jhotdraw/draw/io/TextInputFormat.java