jhotdraw: org.jhotdraw.draw.tool.CreationTool Class Reference
org.jhotdraw.draw.tool.CreationTool Class Reference
Public Member Functions
CreationTool (String prototypeClassName)
CreationTool (String prototypeClassName, Map< AttributeKey<?>, Object > attributes)
CreationTool (String prototypeClassName, Map< AttributeKey<?>, Object > attributes, String name)
CreationTool (Figure prototype)
CreationTool (Figure prototype, Map< AttributeKey<?>, Object > attributes)
CreationTool (Figure prototype, Map< AttributeKey<?>, Object > attributes, String name)
Figure getPrototype ()
void activate (DrawingEditor editor)
void deactivate (DrawingEditor editor)
void mousePressed (MouseEvent evt)
void mouseDragged (MouseEvent evt)
void mouseReleased (MouseEvent evt)
void setToolDoneAfterCreation (boolean newValue)
boolean isToolDoneAfterCreation ()
void updateCursor (DrawingView view, Point p)
Public Member Functions inherited from org.jhotdraw.draw.tool.AbstractTool
AbstractTool ()
void addUndoableEditListener (UndoableEditListener l)
void removeUndoableEditListener (UndoableEditListener l)
boolean isActive ()
void setInputMap (InputMap newValue)
InputMap getInputMap ()
void setActionMap (ActionMap newValue)
ActionMap getActionMap ()
void editDelete ()
void editCut ()
void editCopy ()
void editDuplicate ()
void editPaste ()
void keyReleased (KeyEvent evt)
void keyTyped (KeyEvent evt)
void keyPressed (KeyEvent evt)
void mouseClicked (MouseEvent evt)
void mouseEntered (MouseEvent evt)
void mouseExited (MouseEvent evt)
void mouseMoved (MouseEvent evt)
void addToolListener (ToolListener l)
void removeToolListener (ToolListener l)
void draw (Graphics2D g)
String getToolTipText (DrawingView view, MouseEvent evt)
boolean supportsHandleInteraction ()
Protected Member Functions
Figure createFigure ()
Figure getCreatedFigure ()
Figure getAddedFigure ()
void creationFinished (Figure createdFigure)
Protected Member Functions inherited from org.jhotdraw.draw.tool.AbstractTool
DrawingView getView ()
DrawingEditor getEditor ()
Drawing getDrawing ()
Point2D.Double viewToDrawing (Point p)
Point2D.Double constrainPoint (Point p, Figure... figure)
Point2D.Double constrainPoint (Point2D.Double p, Figure... figure)
InputMap createInputMap ()
ActionMap createActionMap ()
void fireToolStarted (DrawingView view)
void fireToolDone ()
void fireAreaInvalidated (Rectangle2D.Double r)
void fireAreaInvalidated (Rectangle invalidatedArea)
void maybeFireBoundsInvalidated (Rectangle invalidatedArea)
void fireBoundsInvalidated (Rectangle invalidatedArea)
Protected Attributes
Map< AttributeKey<?>, Object > prototypeAttributes
String presentationName
Dimension minimalSizeTreshold = new Dimension(2, 2)
Dimension minimalSize = new Dimension(40, 40)
Figure prototype
Figure createdFigure
Protected Attributes inherited from org.jhotdraw.draw.tool.AbstractTool
boolean isWorking
DrawingEditor editor
Point anchor = new Point()
EventListenerList listenerList = new EventListenerList()
Detailed Description
A Tool to create a new figure by drawing its bounds. The figure to be created is specified by a prototype.
To create a figure using the
CreationTool
, the user does the following mouse gestures on a DrawingView:
Press the mouse button over the DrawingView. This defines the start point of the Figure bounds.
Drag the mouse while keeping the mouse button pressed, and then release the mouse button. This defines the end point of the Figure bounds.
The CreationTool works well with most figures that fit into a rectangular shape or that concist of a single straight line. For figures that need additional editing after these mouse gestures, the use of a specialized creation tool is recommended. For example the TextTool allows to enter the text into a TextFigure after the user has performed the mouse gestures.
Alltough the mouse gestures might be fitting for the creation of a connection, the CreationTool is not suited for the creation of a ConnectionFigure. Use the ConnectionTool for this type of figures instead.
Design Patterns
Prototype
The creation tool creates new figures by cloning a prototype figure object. That's the reason why
Figure
extends the
Cloneable
interface.
Prototype: Figure; Client: CreationTool.
Author
Werner Randelshofer
Version
$Id$
Constructor & Destructor Documentation
CreationTool() [1/6]
org.jhotdraw.draw.tool.CreationTool.CreationTool (String prototypeClassName)
Creates a new instance.
CreationTool() [2/6]
org.jhotdraw.draw.tool.CreationTool.CreationTool (String prototypeClassName, Map< AttributeKey<?>, Object > attributes)
CreationTool() [3/6]
org.jhotdraw.draw.tool.CreationTool.CreationTool (String prototypeClassName, Map< AttributeKey<?>, Object > attributes, String name)
CreationTool() [4/6]
org.jhotdraw.draw.tool.CreationTool.CreationTool (Figure prototype)
Creates a new instance with the specified prototype but without an attribute set. The CreationTool clones this prototype each time a new Figure needs to be created. When a new Figure is created, the CreationTool applies the default attributes from the DrawingEditor to it.
Parameters
prototype The prototype used to create a new Figure.
References org.jhotdraw.draw.tool.CreationTool.prototype.
CreationTool() [5/6]
org.jhotdraw.draw.tool.CreationTool.CreationTool (Figure prototype, Map< AttributeKey<?>, Object > attributes)
Creates a new instance with the specified prototype but without an attribute set. The CreationTool clones this prototype each time a new Figure needs to be created. When a new Figure is created, the CreationTool applies the default attributes from the DrawingEditor to it, and then it applies the attributes to it, that have been supplied in this constructor.
Parameters
prototype The prototype used to create a new Figure.
attributes The CreationTool applies these attributes to the prototype after having applied the default attributes from the DrawingEditor.
References org.jhotdraw.draw.tool.CreationTool.prototype.
CreationTool() [6/6]
org.jhotdraw.draw.tool.CreationTool.CreationTool (Figure prototype, Map< AttributeKey<?>, Object > attributes, String name)
Creates a new instance with the specified prototype and attribute set.
Parameters
prototype The prototype used to create a new Figure.
attributes The CreationTool applies these attributes to the prototype after having applied the default attributes from the DrawingEditor.
name The name parameter is currently not used.
Deprecated:
This constructor might go away, because the name parameter is not used.
References org.jhotdraw.draw.tool.CreationTool.prototype.
Member Function Documentation
activate()
void org.jhotdraw.draw.tool.CreationTool.activate (DrawingEditor editor)
Activates the tool for the given editor. This method is called whenever the user switches to this tool.
Reimplemented from org.jhotdraw.draw.tool.AbstractTool.
Reimplemented in org.jhotdraw.draw.tool.ImageTool.
References org.jhotdraw.draw.tool.AbstractTool.editor, org.jhotdraw.draw.tool.AbstractTool.getView(), and org.jhotdraw.draw.DrawingView.setCursor().
createFigure()
Figure org.jhotdraw.draw.tool.CreationTool.createFigure () protected
References org.jhotdraw.draw.DrawingEditor.applyDefaultAttributesTo(), org.jhotdraw.draw.figure.Figure.clone(), org.jhotdraw.draw.tool.AbstractTool.getEditor(), org.jhotdraw.draw.tool.CreationTool.prototype, org.jhotdraw.draw.tool.CreationTool.prototypeAttributes, and org.jhotdraw.draw.figure.Figure.set().
Referenced by org.jhotdraw.draw.tool.CreationTool.mousePressed().
creationFinished()
void org.jhotdraw.draw.tool.CreationTool.creationFinished (Figure createdFigure) protected
This method allows subclasses to do perform additonal user interactions after the new figure has been created. The implementation of this class just invokes fireToolDone.
Reimplemented in org.jhotdraw.draw.tool.TextCreationTool, and org.jhotdraw.draw.tool.TextAreaCreationTool.
References org.jhotdraw.draw.DrawingView.addToSelection(), org.jhotdraw.draw.tool.CreationTool.createdFigure, org.jhotdraw.draw.tool.AbstractTool.fireToolDone(), org.jhotdraw.draw.tool.AbstractTool.getView(), and org.jhotdraw.draw.figure.Figure.isSelectable().
Referenced by org.jhotdraw.draw.tool.CreationTool.mouseReleased().
deactivate()
void org.jhotdraw.draw.tool.CreationTool.deactivate (DrawingEditor editor)
Deactivates the tool. This method is called whenever the user switches to another tool.
Reimplemented from org.jhotdraw.draw.tool.AbstractTool.
Reimplemented in org.jhotdraw.draw.tool.TextCreationTool, and org.jhotdraw.draw.tool.TextAreaCreationTool.
References org.jhotdraw.draw.tool.CreationTool.createdFigure, org.jhotdraw.draw.tool.AbstractTool.editor, org.jhotdraw.draw.tool.AbstractTool.getView(), and org.jhotdraw.draw.DrawingView.setCursor().
getAddedFigure()
Figure org.jhotdraw.draw.tool.CreationTool.getAddedFigure () protected
References org.jhotdraw.draw.tool.CreationTool.createdFigure.
Referenced by org.jhotdraw.draw.tool.TextAreaCreationTool.endEdit(), and org.jhotdraw.draw.tool.TextCreationTool.endEdit().
getCreatedFigure()
Figure org.jhotdraw.draw.tool.CreationTool.getCreatedFigure () protected
References org.jhotdraw.draw.tool.CreationTool.createdFigure.
Referenced by org.jhotdraw.draw.tool.TextCreationTool.mousePressed().
getPrototype()
Figure org.jhotdraw.draw.tool.CreationTool.getPrototype ()
References org.jhotdraw.draw.tool.CreationTool.prototype.
isToolDoneAfterCreation()
boolean org.jhotdraw.draw.tool.CreationTool.isToolDoneAfterCreation ()
Returns true, if this tool fires toolDone immediately after a new figure has been created.
Referenced by org.jhotdraw.draw.tool.TextAreaCreationTool.actionPerformed(), org.jhotdraw.draw.tool.TextCreationTool.actionPerformed(), org.jhotdraw.draw.tool.ImageTool.activate(), org.jhotdraw.draw.tool.TextCreationTool.keyReleased(), org.jhotdraw.draw.tool.TextAreaCreationTool.mousePressed(), and org.jhotdraw.draw.tool.TextCreationTool.mousePressed().
mouseDragged()
void org.jhotdraw.draw.tool.CreationTool.mouseDragged (MouseEvent evt)
References org.jhotdraw.draw.tool.AbstractTool.anchor, org.jhotdraw.draw.figure.Figure.changed(), org.jhotdraw.draw.tool.AbstractTool.constrainPoint(), org.jhotdraw.draw.tool.CreationTool.createdFigure, org.jhotdraw.draw.figure.Figure.setBounds(), and org.jhotdraw.draw.figure.Figure.willChange().
mousePressed()
void org.jhotdraw.draw.tool.CreationTool.mousePressed (MouseEvent evt)
Reimplemented from org.jhotdraw.draw.tool.AbstractTool.
Reimplemented in org.jhotdraw.draw.tool.TextCreationTool, and org.jhotdraw.draw.tool.TextAreaCreationTool.
References org.jhotdraw.draw.Drawing.add(), org.jhotdraw.draw.tool.AbstractTool.anchor, org.jhotdraw.draw.DrawingView.clearSelection(), org.jhotdraw.draw.tool.AbstractTool.constrainPoint(), org.jhotdraw.draw.tool.CreationTool.createdFigure, org.jhotdraw.draw.tool.CreationTool.createFigure(), org.jhotdraw.draw.tool.AbstractTool.getDrawing(), org.jhotdraw.draw.tool.AbstractTool.getView(), org.jhotdraw.draw.figure.Figure.setBounds(), and org.jhotdraw.draw.tool.AbstractTool.viewToDrawing().
mouseReleased()
void org.jhotdraw.draw.tool.CreationTool.mouseReleased (MouseEvent evt)
Reimplemented from org.jhotdraw.draw.tool.AbstractTool.
Reimplemented in org.jhotdraw.draw.tool.TextCreationTool.
References org.jhotdraw.draw.Drawing.add(), org.jhotdraw.draw.tool.AbstractTool.anchor, org.jhotdraw.draw.figure.Figure.changed(), org.jhotdraw.draw.tool.AbstractTool.constrainPoint(), org.jhotdraw.draw.tool.CreationTool.createdFigure, org.jhotdraw.draw.tool.CreationTool.creationFinished(), org.jhotdraw.draw.tool.AbstractTool.fireToolDone(), org.jhotdraw.draw.Drawing.fireUndoableEditHappened(), org.jhotdraw.draw.figure.Figure.getBounds(), org.jhotdraw.draw.tool.AbstractTool.getDrawing(), org.jhotdraw.draw.tool.AbstractTool.maybeFireBoundsInvalidated(), org.jhotdraw.draw.tool.CreationTool.minimalSize, org.jhotdraw.draw.tool.CreationTool.minimalSizeTreshold, org.jhotdraw.draw.tool.CreationTool.presentationName, org.jhotdraw.draw.Drawing.remove(), org.jhotdraw.draw.figure.Figure.setBounds(), and org.jhotdraw.draw.figure.Figure.willChange().
setToolDoneAfterCreation()
void org.jhotdraw.draw.tool.CreationTool.setToolDoneAfterCreation (boolean newValue)
If this is set to false, the CreationTool does not fire toolDone after a new Figure has been created. This allows to create multiple figures consecutively.
updateCursor()
void org.jhotdraw.draw.tool.CreationTool.updateCursor (DrawingView view, Point p)
Reimplemented from org.jhotdraw.draw.tool.AbstractTool.
Reimplemented in org.jhotdraw.draw.tool.TextCreationTool.
References org.jhotdraw.draw.DrawingView.isEnabled(), and org.jhotdraw.draw.DrawingView.setCursor().
Member Data Documentation
createdFigure
Figure org.jhotdraw.draw.tool.CreationTool.createdFigure protected
The created figure.
Referenced by org.jhotdraw.draw.tool.ImageTool.activate(), org.jhotdraw.draw.tool.CreationTool.creationFinished(), org.jhotdraw.draw.tool.TextAreaCreationTool.creationFinished(), org.jhotdraw.draw.tool.TextCreationTool.creationFinished(), org.jhotdraw.draw.tool.CreationTool.deactivate(), org.jhotdraw.draw.tool.TextAreaCreationTool.draw(), org.jhotdraw.draw.tool.TextAreaCreationTool.endEdit(), org.jhotdraw.draw.tool.TextCreationTool.endEdit(), org.jhotdraw.draw.tool.CreationTool.getAddedFigure(), org.jhotdraw.draw.tool.CreationTool.getCreatedFigure(), org.jhotdraw.draw.tool.CreationTool.mouseDragged(), org.jhotdraw.draw.tool.CreationTool.mousePressed(), and org.jhotdraw.draw.tool.CreationTool.mouseReleased().
minimalSize
Dimension org.jhotdraw.draw.tool.CreationTool.minimalSize = new Dimension(40, 40) protected
We set the figure to this minimal size, if it is smaller than the minimal size treshold.
Referenced by org.jhotdraw.draw.tool.CreationTool.mouseReleased().
minimalSizeTreshold
Dimension org.jhotdraw.draw.tool.CreationTool.minimalSizeTreshold = new Dimension(2, 2) protected
Treshold for which we create a larger shape of a minimal size.
Referenced by org.jhotdraw.draw.tool.CreationTool.mouseReleased().
presentationName
String org.jhotdraw.draw.tool.CreationTool.presentationName protected
A localized name for this tool. The presentationName is displayed by the UndoableEdit.
Referenced by org.jhotdraw.draw.tool.CreationTool.mouseReleased().
prototype
Figure org.jhotdraw.draw.tool.CreationTool.prototype protected
The prototype for new figures.
Referenced by org.jhotdraw.draw.tool.ImageTool.activate(), org.jhotdraw.draw.tool.CreationTool.createFigure(), org.jhotdraw.draw.tool.CreationTool.CreationTool(), org.jhotdraw.draw.tool.CreationTool.getPrototype(), org.jhotdraw.draw.tool.ImageTool.ImageTool(), org.jhotdraw.draw.tool.TextAreaCreationTool.TextAreaCreationTool(), and org.jhotdraw.draw.tool.TextCreationTool.TextCreationTool().
prototypeAttributes
Map<AttributeKey<?>, Object> org.jhotdraw.draw.tool.CreationTool.prototypeAttributes protected
Attributes to be applied to the created ConnectionFigure. These attributes override the default attributes of the DrawingEditor.
Referenced by org.jhotdraw.draw.tool.CreationTool.createFigure().
The documentation for this class was generated from the following file:
jhotdraw-core/src/main/java/org/jhotdraw/draw/tool/CreationTool.java