jhotdraw: org.jhotdraw.draw.locator.RelativeLocator Class Reference
org.jhotdraw.draw.locator.RelativeLocator Class Reference
Public Member Functions
RelativeLocator ()
RelativeLocator (double relativeX, double relativeY)
RelativeLocator (double relativeX, double relativeY, boolean isTransform)
java.awt.geom.Point2D.Double locate (Figure owner)
void write (DOMOutput out)
void read (DOMInput in)
boolean equals (Object obj)
int hashCode ()
Public Member Functions inherited from org.jhotdraw.draw.locator.AbstractLocator
AbstractLocator ()
Point2D.Double locate (Figure owner, Figure dependent)
Static Public Member Functions
static Locator east ()
static Locator east (boolean isTransform)
static Locator north ()
static Locator north (boolean isTransform)
static Locator west ()
static Locator west (boolean isTransform)
static Locator northEast ()
static Locator northEast (boolean isTransform)
static Locator northWest ()
static Locator northWest (boolean isTransform)
static Locator south ()
static Locator south (boolean isTransform)
static Locator southEast ()
static Locator southEast (boolean isTransform)
static Locator southWest ()
static Locator southWest (boolean isTransform)
static Locator center ()
static Locator center (boolean isTransform)
Protected Attributes
double relativeX
double relativeY
boolean isTransform
Detailed Description
A locator that specfies a point that is relative to the bounds of a figure.
Author
Werner Randelshofer
Version
$Id$
Constructor & Destructor Documentation
RelativeLocator() [1/3]
org.jhotdraw.draw.locator.RelativeLocator.RelativeLocator ()
Creates a new instance.
Referenced by org.jhotdraw.draw.locator.RelativeLocator.center(), org.jhotdraw.draw.locator.RelativeLocator.east(), org.jhotdraw.draw.locator.RelativeLocator.equals(), org.jhotdraw.draw.locator.RelativeLocator.north(), org.jhotdraw.draw.locator.RelativeLocator.northEast(), org.jhotdraw.draw.locator.RelativeLocator.northWest(), org.jhotdraw.draw.locator.RelativeLocator.south(), org.jhotdraw.draw.locator.RelativeLocator.southEast(), org.jhotdraw.draw.locator.RelativeLocator.southWest(), and org.jhotdraw.draw.locator.RelativeLocator.west().
RelativeLocator() [2/3]
org.jhotdraw.draw.locator.RelativeLocator.RelativeLocator (double relativeX, double relativeY)
Creates a new instance.
References org.jhotdraw.draw.locator.RelativeLocator.relativeX, and org.jhotdraw.draw.locator.RelativeLocator.relativeY.
RelativeLocator() [3/3]
org.jhotdraw.draw.locator.RelativeLocator.RelativeLocator (double relativeX, double relativeY, boolean isTransform)
Parameters
relativeX x-position relative to bounds expressed as a value between 0 and 1.
relativeY y-position relative to bounds expressed as a value between 0 and 1.
isTransform Set this to true, if the locator shall honor the TRANSFORM attribute of the Figure.
References org.jhotdraw.draw.locator.RelativeLocator.isTransform, org.jhotdraw.draw.locator.RelativeLocator.relativeX, and org.jhotdraw.draw.locator.RelativeLocator.relativeY.
Member Function Documentation
center() [1/2]
static Locator org.jhotdraw.draw.locator.RelativeLocator.center () static
Non-transforming Center.
Reimplemented in org.jhotdraw.draw.locator.RelativeDecoratorLocator.
center() [2/2]
static Locator org.jhotdraw.draw.locator.RelativeLocator.center (boolean isTransform) static
Center.
Parameters
isTransform Set this to true, if RelativeLocator shall honour the AttributesKey.TRANSFORM attribute of the Figure.
References org.jhotdraw.draw.locator.RelativeLocator.isTransform, and org.jhotdraw.draw.locator.RelativeLocator.RelativeLocator().
east() [1/2]
static Locator org.jhotdraw.draw.locator.RelativeLocator.east () static
Non-transforming East.
Reimplemented in org.jhotdraw.draw.locator.RelativeDecoratorLocator.
Referenced by org.jhotdraw.draw.handle.MoveHandle.east().
east() [2/2]
static Locator org.jhotdraw.draw.locator.RelativeLocator.east (boolean isTransform) static
East.
Parameters
isTransform Set this to true, if RelativeLocator shall honour the AttributesKey.TRANSFORM attribute of the Figure.
References org.jhotdraw.draw.locator.RelativeLocator.isTransform, and org.jhotdraw.draw.locator.RelativeLocator.RelativeLocator().
equals()
boolean org.jhotdraw.draw.locator.RelativeLocator.equals (Object obj)
References org.jhotdraw.draw.locator.RelativeLocator.RelativeLocator(), org.jhotdraw.draw.locator.RelativeLocator.relativeX, and org.jhotdraw.draw.locator.RelativeLocator.relativeY.
hashCode()
int org.jhotdraw.draw.locator.RelativeLocator.hashCode ()
locate()
java.awt.geom.Point2D.Double org.jhotdraw.draw.locator.RelativeLocator.locate (Figure owner)
Locates a position on the provided figure.
Returns
a point on the figure.
Implements org.jhotdraw.draw.locator.Locator.
Reimplemented in org.jhotdraw.draw.locator.RelativeDecoratorLocator.
References org.jhotdraw.draw.figure.Figure.get(), org.jhotdraw.draw.figure.Figure.getBounds(), org.jhotdraw.draw.locator.RelativeLocator.isTransform, org.jhotdraw.draw.locator.RelativeLocator.relativeX, and org.jhotdraw.draw.locator.RelativeLocator.relativeY.
north() [1/2]
static Locator org.jhotdraw.draw.locator.RelativeLocator.north () static
Non-transforming North.
Reimplemented in org.jhotdraw.draw.locator.RelativeDecoratorLocator.
Referenced by org.jhotdraw.draw.handle.MoveHandle.north().
north() [2/2]
static Locator org.jhotdraw.draw.locator.RelativeLocator.north (boolean isTransform) static
North.
Parameters
isTransform Set this to true, if RelativeLocator shall honour the AttributesKey.TRANSFORM attribute of the Figure.
References org.jhotdraw.draw.locator.RelativeLocator.isTransform, and org.jhotdraw.draw.locator.RelativeLocator.RelativeLocator().
northEast() [1/2]
static Locator org.jhotdraw.draw.locator.RelativeLocator.northEast () static
Non-transforming North east.
Reimplemented in org.jhotdraw.draw.locator.RelativeDecoratorLocator.
Referenced by org.jhotdraw.draw.figure.TextFigure.createHandles(), and org.jhotdraw.draw.handle.MoveHandle.northEast().
northEast() [2/2]
static Locator org.jhotdraw.draw.locator.RelativeLocator.northEast (boolean isTransform) static
Norht East.
Parameters
isTransform Set this to true, if RelativeLocator shall honour the AttributesKey.TRANSFORM attribute of the Figure.
References org.jhotdraw.draw.locator.RelativeLocator.isTransform, and org.jhotdraw.draw.locator.RelativeLocator.RelativeLocator().
northWest() [1/2]
static Locator org.jhotdraw.draw.locator.RelativeLocator.northWest () static
Non-transforming North west.
Reimplemented in org.jhotdraw.draw.locator.RelativeDecoratorLocator.
Referenced by org.jhotdraw.draw.figure.TextFigure.createHandles(), and org.jhotdraw.draw.handle.MoveHandle.northWest().
northWest() [2/2]
static Locator org.jhotdraw.draw.locator.RelativeLocator.northWest (boolean isTransform) static
North West.
Parameters
isTransform Set this to true, if RelativeLocator shall honour the AttributesKey.TRANSFORM attribute of the Figure.
References org.jhotdraw.draw.locator.RelativeLocator.isTransform, and org.jhotdraw.draw.locator.RelativeLocator.RelativeLocator().
read()
void org.jhotdraw.draw.locator.RelativeLocator.read (DOMInput in)
References org.jhotdraw.draw.locator.RelativeLocator.relativeX, and org.jhotdraw.draw.locator.RelativeLocator.relativeY.
south() [1/2]
static Locator org.jhotdraw.draw.locator.RelativeLocator.south () static
Non-transforming South.
Reimplemented in org.jhotdraw.draw.locator.RelativeDecoratorLocator.
Referenced by org.jhotdraw.draw.handle.MoveHandle.south().
south() [2/2]
static Locator org.jhotdraw.draw.locator.RelativeLocator.south (boolean isTransform) static
South.
Parameters
isTransform Set this to true, if RelativeLocator shall honour the AttributesKey.TRANSFORM attribute of the Figure.
References org.jhotdraw.draw.locator.RelativeLocator.isTransform, and org.jhotdraw.draw.locator.RelativeLocator.RelativeLocator().
southEast() [1/2]
static Locator org.jhotdraw.draw.locator.RelativeLocator.southEast () static
Non-transforming South east.
Reimplemented in org.jhotdraw.draw.locator.RelativeDecoratorLocator.
Referenced by org.jhotdraw.draw.figure.TextFigure.createHandles(), and org.jhotdraw.draw.handle.MoveHandle.southEast().
southEast() [2/2]
static Locator org.jhotdraw.draw.locator.RelativeLocator.southEast (boolean isTransform) static
South East.
Parameters
isTransform Set this to true, if RelativeLocator shall honour the AttributesKey.TRANSFORM attribute of the Figure.
References org.jhotdraw.draw.locator.RelativeLocator.isTransform, and org.jhotdraw.draw.locator.RelativeLocator.RelativeLocator().
southWest() [1/2]
static Locator org.jhotdraw.draw.locator.RelativeLocator.southWest () static
Non-transforming South west.
Reimplemented in org.jhotdraw.draw.locator.RelativeDecoratorLocator.
Referenced by org.jhotdraw.draw.figure.TextFigure.createHandles(), and org.jhotdraw.draw.handle.MoveHandle.southWest().
southWest() [2/2]
static Locator org.jhotdraw.draw.locator.RelativeLocator.southWest (boolean isTransform) static
South West.
Parameters
isTransform Set this to true, if RelativeLocator shall honour the AttributesKey.TRANSFORM attribute of the Figure.
References org.jhotdraw.draw.locator.RelativeLocator.isTransform, and org.jhotdraw.draw.locator.RelativeLocator.RelativeLocator().
west() [1/2]
static Locator org.jhotdraw.draw.locator.RelativeLocator.west () static
Non-transforming West.
Reimplemented in org.jhotdraw.draw.locator.RelativeDecoratorLocator.
Referenced by org.jhotdraw.draw.handle.MoveHandle.west().
west() [2/2]
static Locator org.jhotdraw.draw.locator.RelativeLocator.west (boolean isTransform) static
West.
Parameters
isTransform Set this to true, if RelativeLocator shall honour the AttributesKey.TRANSFORM attribute of the Figure.
References org.jhotdraw.draw.locator.RelativeLocator.isTransform, and org.jhotdraw.draw.locator.RelativeLocator.RelativeLocator().
write()
void org.jhotdraw.draw.locator.RelativeLocator.write (DOMOutput out)
References org.jhotdraw.draw.locator.RelativeLocator.relativeX, and org.jhotdraw.draw.locator.RelativeLocator.relativeY.
Member Data Documentation
isTransform
boolean org.jhotdraw.draw.locator.RelativeLocator.isTransform protected
If this is set to true, if the locator is transforming with the figure.
Referenced by org.jhotdraw.draw.locator.RelativeLocator.center(), org.jhotdraw.draw.locator.RelativeLocator.east(), org.jhotdraw.draw.locator.RelativeLocator.locate(), org.jhotdraw.draw.locator.RelativeLocator.north(), org.jhotdraw.draw.locator.RelativeLocator.northEast(), org.jhotdraw.draw.locator.RelativeLocator.northWest(), org.jhotdraw.draw.locator.RelativeLocator.RelativeLocator(), org.jhotdraw.draw.locator.RelativeLocator.south(), org.jhotdraw.draw.locator.RelativeLocator.southEast(), org.jhotdraw.draw.locator.RelativeLocator.southWest(), and org.jhotdraw.draw.locator.RelativeLocator.west().
relativeX
double org.jhotdraw.draw.locator.RelativeLocator.relativeX protected
Relative x-coordinate on the bounds of the figure. The value 0 is on the left boundary of the figure, the value 1 on the right boundary.
Referenced by org.jhotdraw.draw.locator.RelativeLocator.equals(), org.jhotdraw.draw.locator.RelativeDecoratorLocator.locate(), org.jhotdraw.draw.locator.RelativeLocator.locate(), org.jhotdraw.draw.locator.RelativeLocator.read(), org.jhotdraw.draw.locator.RelativeDecoratorLocator.RelativeDecoratorLocator(), org.jhotdraw.draw.locator.RelativeLocator.RelativeLocator(), and org.jhotdraw.draw.locator.RelativeLocator.write().
relativeY
double org.jhotdraw.draw.locator.RelativeLocator.relativeY protected
Relative y-coordinate on the bounds of the figure. The value 0 is on the top boundary of the figure, the value 1 on the bottom boundary.
Referenced by org.jhotdraw.draw.locator.RelativeLocator.equals(), org.jhotdraw.draw.locator.RelativeDecoratorLocator.locate(), org.jhotdraw.draw.locator.RelativeLocator.locate(), org.jhotdraw.draw.locator.RelativeLocator.read(), org.jhotdraw.draw.locator.RelativeDecoratorLocator.RelativeDecoratorLocator(), org.jhotdraw.draw.locator.RelativeLocator.RelativeLocator(), and org.jhotdraw.draw.locator.RelativeLocator.write().
The documentation for this class was generated from the following file:
jhotdraw-core/src/main/java/org/jhotdraw/draw/locator/RelativeLocator.java