jhotdraw: org.jhotdraw.draw.handle.CloseHandle Class Reference
org.jhotdraw.draw.handle.CloseHandle Class Reference
Public Member Functions
CloseHandle (Figure owner)
CloseHandle (Figure owner, Locator locator)
void draw (Graphics2D g)
Cursor getCursor ()
void trackEnd (Point anchor, Point lead, int modifiersEx)
void trackStart (Point anchor, int modifiersEx)
void trackStep (Point anchor, Point lead, int modifiersEx)
Public Member Functions inherited from org.jhotdraw.draw.handle.LocatorHandle
LocatorHandle (Figure owner, Locator l)
Point2D.Double getLocationOnDrawing ()
Point getLocation ()
Public Member Functions inherited from org.jhotdraw.draw.handle.AbstractHandle
AbstractHandle (Figure owner)
void addHandleListener (HandleListener l)
void removeHandleListener (HandleListener l)
Figure getOwner ()
void setView (DrawingView view)
DrawingView getView ()
DrawingEditor getEditor ()
boolean contains (Point p)
void invalidate ()
void dispose ()
void areaInvalidated (FigureEvent evt)
void figureAdded (FigureEvent e)
void figureRemoved (FigureEvent e)
void figureRequestRemove (FigureEvent e)
void figureChanged (FigureEvent evt)
boolean isCombinableWith (Handle handle)
void keyTyped (KeyEvent evt)
void keyReleased (KeyEvent evt)
void keyPressed (KeyEvent evt)
final Rectangle getBounds ()
Rectangle getDrawingArea ()
void trackDoubleClick (Point p, int modifiersEx)
void attributeChanged (FigureEvent e)
void viewTransformChanged ()
Collection< Handle > createSecondaryHandles ()
String getToolTipText (Point p)
void setToolTipText (String newValue)
void figureHandlesChanged (FigureEvent e)
Protected Member Functions
int getHandlesize ()
Protected Member Functions inherited from org.jhotdraw.draw.handle.LocatorHandle
Rectangle basicGetBounds ()
Protected Member Functions inherited from org.jhotdraw.draw.handle.AbstractHandle
void fireAreaInvalidated (Rectangle invalidatedArea)
void fireUndoableEditHappened (UndoableEdit edit)
void fireHandleRequestRemove (Rectangle invalidatedArea)
void fireHandleRequestSecondaryHandles ()
void drawCircle (Graphics2D g, Color fill, Color stroke)
void drawRectangle (Graphics2D g, Color fill, Color stroke)
void drawDiamond (Graphics2D g, Color fill, Color stroke)
void updateBounds ()
Additional Inherited Members
Protected Attributes inherited from org.jhotdraw.draw.handle.AbstractHandle
DrawingView view
EventListenerList listenerList = new EventListenerList()
Detailed Description
A Handle which requests to remove its owning figure when clicked.
Author
Werner Randelshofer
Version
$Id$
Constructor & Destructor Documentation
CloseHandle() [1/2]
org.jhotdraw.draw.handle.CloseHandle.CloseHandle (Figure owner)
Creates a new instance.
CloseHandle() [2/2]
org.jhotdraw.draw.handle.CloseHandle.CloseHandle (Figure owner, Locator locator)
Creates a new instance.
Member Function Documentation
draw()
void org.jhotdraw.draw.handle.CloseHandle.draw (Graphics2D g)
Draws this handle.
Reimplemented from org.jhotdraw.draw.handle.AbstractHandle.
References org.jhotdraw.draw.handle.AbstractHandle.drawRectangle(), and org.jhotdraw.draw.handle.AbstractHandle.getBounds().
getCursor()
Cursor org.jhotdraw.draw.handle.CloseHandle.getCursor ()
Returns a cursor for the handle.
Reimplemented from org.jhotdraw.draw.handle.AbstractHandle.
getHandlesize()
int org.jhotdraw.draw.handle.CloseHandle.getHandlesize () protected
Reimplemented from org.jhotdraw.draw.handle.AbstractHandle.
trackEnd()
void org.jhotdraw.draw.handle.CloseHandle.trackEnd (Point anchor, Point lead, int modifiersEx)
Tracks the end of the interaction.
Parameters
anchor the position where the interaction started
lead the current position
Implements org.jhotdraw.draw.handle.Handle.
References org.jhotdraw.draw.handle.LocatorHandle.basicGetBounds(), org.jhotdraw.draw.handle.AbstractHandle.fireAreaInvalidated(), org.jhotdraw.draw.handle.AbstractHandle.getDrawingArea(), org.jhotdraw.draw.handle.AbstractHandle.getOwner(), and org.jhotdraw.draw.figure.Figure.requestRemove().
trackStart()
void org.jhotdraw.draw.handle.CloseHandle.trackStart (Point anchor, int modifiersEx)
Tracks the start of the interaction. The default implementation does nothing.
Parameters
anchor the position where the interaction started
Implements org.jhotdraw.draw.handle.Handle.
References org.jhotdraw.draw.handle.AbstractHandle.fireAreaInvalidated(), and org.jhotdraw.draw.handle.AbstractHandle.getDrawingArea().
trackStep()
void org.jhotdraw.draw.handle.CloseHandle.trackStep (Point anchor, Point lead, int modifiersEx)
Tracks a step of the interaction.
Parameters
anchor the position where the interaction started
lead the current position
Implements org.jhotdraw.draw.handle.Handle.
References org.jhotdraw.draw.handle.LocatorHandle.basicGetBounds(), org.jhotdraw.draw.handle.AbstractHandle.fireAreaInvalidated(), and org.jhotdraw.draw.handle.AbstractHandle.getDrawingArea().
The documentation for this class was generated from the following file:
jhotdraw-core/src/main/java/org/jhotdraw/draw/handle/CloseHandle.java