jhotdraw: org.jhotdraw.draw.tool.DefaultDragTracker Class Reference
org.jhotdraw.draw.tool.DefaultDragTracker Class Reference
Public Member Functions
DefaultDragTracker (Figure figure)
DefaultDragTracker ()
void mouseMoved (MouseEvent evt)
void mousePressed (MouseEvent evt)
void mouseDragged (MouseEvent evt)
void mouseReleased (MouseEvent evt)
void setDraggedFigure (Figure f)
Public Member Functions inherited from org.jhotdraw.draw.tool.AbstractTool
AbstractTool ()
void addUndoableEditListener (UndoableEditListener l)
void removeUndoableEditListener (UndoableEditListener l)
void activate (DrawingEditor editor)
void deactivate (DrawingEditor editor)
boolean isActive ()
void setInputMap (InputMap newValue)
InputMap getInputMap ()
void setActionMap (ActionMap newValue)
ActionMap getActionMap ()
void editDelete ()
void editCut ()
void editCopy ()
void editDuplicate ()
void editPaste ()
void keyReleased (KeyEvent evt)
void keyTyped (KeyEvent evt)
void keyPressed (KeyEvent evt)
void mouseClicked (MouseEvent evt)
void mouseEntered (MouseEvent evt)
void mouseExited (MouseEvent evt)
void addToolListener (ToolListener l)
void removeToolListener (ToolListener l)
void draw (Graphics2D g)
void updateCursor (DrawingView view, Point p)
String getToolTipText (DrawingView view, MouseEvent evt)
boolean supportsHandleInteraction ()
Protected Attributes
Figure anchorFigure
Rectangle2D.Double dragRect
Point2D.Double previousOrigin
Point2D.Double anchorOrigin
Point2D.Double previousPoint
Point2D.Double anchorPoint
Protected Attributes inherited from org.jhotdraw.draw.tool.AbstractTool
boolean isWorking
DrawingEditor editor
Point anchor = new Point()
EventListenerList listenerList = new EventListenerList()
Additional Inherited Members
Protected Member Functions inherited from org.jhotdraw.draw.tool.AbstractTool
DrawingView getView ()
DrawingEditor getEditor ()
Drawing getDrawing ()
Point2D.Double viewToDrawing (Point p)
Point2D.Double constrainPoint (Point p, Figure... figure)
Point2D.Double constrainPoint (Point2D.Double p, Figure... figure)
InputMap createInputMap ()
ActionMap createActionMap ()
void fireToolStarted (DrawingView view)
void fireToolDone ()
void fireAreaInvalidated (Rectangle2D.Double r)
void fireAreaInvalidated (Rectangle invalidatedArea)
void maybeFireBoundsInvalidated (Rectangle invalidatedArea)
void fireBoundsInvalidated (Rectangle invalidatedArea)
Detailed Description
DefaultDragTracker implements interactions with the content area of a Figure.
The DefaultDragTracker handles one of the three states of the SelectionTool. It comes into action, when the user presses the mouse button over the content area of a Figure.
Design pattern:
Name: Chain of Responsibility.
Role: Handler.
Partners: SelectionTool as Handler, SelectAreaTracker as Handler, HandleTracker as Handler.
Design pattern:
Name: State.
Role: State.
Partners: SelectAreaTracker as State, SelectionTool as Context, HandleTracker as State.
See also
SelectionTool
Author
Werner Randelshofer
Version
$Id$
Constructor & Destructor Documentation
DefaultDragTracker() [1/2]
org.jhotdraw.draw.tool.DefaultDragTracker.DefaultDragTracker (Figure figure)
Creates a new instance.
References org.jhotdraw.draw.tool.DefaultDragTracker.anchorFigure.
DefaultDragTracker() [2/2]
org.jhotdraw.draw.tool.DefaultDragTracker.DefaultDragTracker ()
Member Function Documentation
mouseDragged()
void org.jhotdraw.draw.tool.DefaultDragTracker.mouseDragged (MouseEvent evt)
References org.jhotdraw.draw.Constrainer.constrainRectangle(), org.jhotdraw.draw.tool.DefaultDragTracker.dragRect, org.jhotdraw.draw.tool.AbstractTool.editor, org.jhotdraw.draw.DrawingEditor.findView(), org.jhotdraw.draw.DrawingView.getConstrainer(), org.jhotdraw.draw.tool.AbstractTool.getView(), org.jhotdraw.draw.tool.DefaultDragTracker.previousOrigin, org.jhotdraw.draw.tool.DefaultDragTracker.previousPoint, org.jhotdraw.draw.tool.AbstractTool.updateCursor(), and org.jhotdraw.draw.DrawingView.viewToDrawing().
mouseMoved()
void org.jhotdraw.draw.tool.DefaultDragTracker.mouseMoved (MouseEvent evt)
Reimplemented from org.jhotdraw.draw.tool.AbstractTool.
References org.jhotdraw.draw.tool.AbstractTool.editor, org.jhotdraw.draw.DrawingEditor.findView(), and org.jhotdraw.draw.tool.AbstractTool.updateCursor().
mousePressed()
void org.jhotdraw.draw.tool.DefaultDragTracker.mousePressed (MouseEvent evt)
Reimplemented from org.jhotdraw.draw.tool.AbstractTool.
References org.jhotdraw.draw.DrawingView.addToSelection(), org.jhotdraw.draw.tool.AbstractTool.anchor, org.jhotdraw.draw.tool.DefaultDragTracker.anchorFigure, org.jhotdraw.draw.tool.DefaultDragTracker.anchorOrigin, org.jhotdraw.draw.tool.DefaultDragTracker.anchorPoint, org.jhotdraw.draw.DrawingView.clearSelection(), org.jhotdraw.draw.tool.DefaultDragTracker.dragRect, org.jhotdraw.draw.DrawingView.getSelectedFigures(), org.jhotdraw.draw.tool.AbstractTool.getView(), org.jhotdraw.draw.DrawingView.isFigureSelected(), org.jhotdraw.draw.tool.DefaultDragTracker.previousOrigin, org.jhotdraw.draw.tool.DefaultDragTracker.previousPoint, org.jhotdraw.draw.DrawingView.setHandleDetailLevel(), org.jhotdraw.draw.DrawingView.toggleSelection(), and org.jhotdraw.draw.DrawingView.viewToDrawing().
mouseReleased()
void org.jhotdraw.draw.tool.DefaultDragTracker.mouseReleased (MouseEvent evt)
Reimplemented from org.jhotdraw.draw.tool.AbstractTool.
References org.jhotdraw.draw.tool.AbstractTool.anchor, org.jhotdraw.draw.tool.DefaultDragTracker.anchorOrigin, org.jhotdraw.draw.tool.AbstractTool.editor, org.jhotdraw.draw.Drawing.findFigureExcept(), org.jhotdraw.draw.DrawingEditor.findView(), org.jhotdraw.draw.tool.AbstractTool.fireToolDone(), org.jhotdraw.draw.Drawing.fireUndoableEditHappened(), org.jhotdraw.draw.tool.AbstractTool.getDrawing(), org.jhotdraw.draw.tool.AbstractTool.getView(), org.jhotdraw.draw.figure.Figure.handleDrop(), org.jhotdraw.draw.tool.AbstractTool.maybeFireBoundsInvalidated(), org.jhotdraw.draw.tool.DefaultDragTracker.previousOrigin, org.jhotdraw.draw.tool.AbstractTool.updateCursor(), and org.jhotdraw.draw.DrawingView.viewToDrawing().
setDraggedFigure()
void org.jhotdraw.draw.tool.DefaultDragTracker.setDraggedFigure (Figure f)
Implements org.jhotdraw.draw.tool.DragTracker.
References org.jhotdraw.draw.tool.DefaultDragTracker.anchorFigure.
Member Data Documentation
anchorFigure
Figure org.jhotdraw.draw.tool.DefaultDragTracker.anchorFigure protected
Referenced by org.jhotdraw.draw.tool.DefaultDragTracker.DefaultDragTracker(), org.jhotdraw.draw.tool.DefaultDragTracker.mousePressed(), and org.jhotdraw.draw.tool.DefaultDragTracker.setDraggedFigure().
anchorOrigin
Point2D.Double org.jhotdraw.draw.tool.DefaultDragTracker.anchorOrigin protected
The anchorOrigin holds the origin of all dragged figures of the mousePressed event.
Referenced by org.jhotdraw.draw.tool.DefaultDragTracker.mousePressed(), and org.jhotdraw.draw.tool.DefaultDragTracker.mouseReleased().
anchorPoint
Point2D.Double org.jhotdraw.draw.tool.DefaultDragTracker.anchorPoint protected
The anchorPoint holds the location of the mouse of the mousePressed event. This coordinate is not constrained using the Constrainer of the DrawingView.
Referenced by org.jhotdraw.draw.tool.DefaultDragTracker.mousePressed().
dragRect
Rectangle2D.Double org.jhotdraw.draw.tool.DefaultDragTracker.dragRect protected
The drag rectangle encompasses the bounds of all dragged figures.
Referenced by org.jhotdraw.draw.tool.DefaultDragTracker.mouseDragged(), and org.jhotdraw.draw.tool.DefaultDragTracker.mousePressed().
previousOrigin
Point2D.Double org.jhotdraw.draw.tool.DefaultDragTracker.previousOrigin protected
The previousOrigin holds the origin of all dragged figures of the previous mouseDragged event. This coordinate is constrained using the Constrainer of the DrawingView.
Referenced by org.jhotdraw.draw.tool.DefaultDragTracker.mouseDragged(), org.jhotdraw.draw.tool.DefaultDragTracker.mousePressed(), and org.jhotdraw.draw.tool.DefaultDragTracker.mouseReleased().
previousPoint
Point2D.Double org.jhotdraw.draw.tool.DefaultDragTracker.previousPoint protected
The previousPoint holds the location of the mouse of the previous mouseDragged event. This coordinate is not constrained using the Constrainer of the DrawingView.
Referenced by org.jhotdraw.draw.tool.DefaultDragTracker.mouseDragged(), and org.jhotdraw.draw.tool.DefaultDragTracker.mousePressed().
The documentation for this class was generated from the following file:
jhotdraw-core/src/main/java/org/jhotdraw/draw/tool/DefaultDragTracker.java