jhotdraw: org.jhotdraw.draw.figure.AbstractAttributedCompositeFigure Class Reference
org.jhotdraw.draw.figure.AbstractAttributedCompositeFigure Class Reference abstract
Public Member Functions
AbstractAttributedCompositeFigure ()
void setAttributeEnabled (AttributeKey<?> key, boolean b)
void setAttributes (Map< AttributeKey<?>, Object > map)
Map< AttributeKey<?>, Object > getAttributes ()
Object getAttributesRestoreData ()
void restoreAttributesTo (Object restoreData)
void drawFigure (Graphics2D g)
Stroke getStroke ()
double getStrokeMiterLimitFactor ()
Rectangle2D.Double getFigureDrawBounds ()
AbstractAttributedCompositeFigure clone ()
void write (DOMOutput out) throws IOException
void read (DOMInput in) throws IOException
Public Member Functions inherited from org.jhotdraw.draw.figure.AbstractCompositeFigure
AbstractCompositeFigure ()
Collection< Handle > createHandles (int detailLevel)
boolean add (Figure figure)
void add (int index, Figure figure)
void addAll (Collection<? extends Figure > figures)
final void addAll (int index, Collection<? extends Figure > figures)
void basicAdd (Figure figure)
void basicAddAll (int index, Collection<? extends Figure > newFigures)
void addNotify (Drawing drawing)
void removeNotify (Drawing drawing)
boolean remove (final Figure figure)
Figure removeChild (int index)
void removeAll (Collection<? extends Figure > figures)
void removeAllChildren ()
void basicRemoveAllChildren ()
void basicRemoveAll (Collection<? extends Figure > figures)
void sendToBack (Figure figure)
void bringToFront (Figure figure)
void transform (AffineTransform tx)
void setBounds (Point2D.Double anchor, Point2D.Double lead)
java.util.List< Figure > getChildrenFrontToBack ()
boolean contains (Figure f)
boolean contains (Point2D.Double p)
Figure findFigureInside (Point2D.Double p)
Figure findChild (Point2D.Double p)
int findChildIndex (Point2D.Double p)
Layouter getLayouter ()
void layout ()
void setLayouter (Layouter newLayouter)
Dimension2DDouble getPreferredSize ()
void draw (Graphics2D g)
Collection< Figure > getDecomposition ()
void restoreTransformTo (Object geometry)
Object getTransformRestoreData ()
void basicAdd (int index, Figure figure)
Figure basicRemoveChild (int index)
java.util.List< Figure > getChildren ()
int getChildCount ()
Figure getChild (int index)
void willChange ()
void changed ()
int basicRemove (Figure child)
int indexOf (Figure child)
Rectangle2D.Double getDrawingArea ()
Rectangle2D.Double getDrawingArea (double factor)
Rectangle2D.Double getBounds ()
void removeCompositeFigureListener (CompositeFigureListener listener)
void addCompositeFigureListener (CompositeFigureListener listener)
Public Member Functions inherited from org.jhotdraw.draw.figure.AbstractFigure
AbstractFigure ()
void addFigureListener (FigureListener l)
void removeFigureListener (FigureListener l)
void fireAreaInvalidated ()
void fireFigureChanged ()
void remap (Map< Figure, Figure > oldToNew, boolean disconnectIfNotInMap)
Cursor getCursor (Point2D.Double p)
final void setBounds (Rectangle2D.Double bounds)
Connector findConnector (Point2D.Double p, ConnectionFigure prototype)
boolean includes (Figure figure)
Connector findCompatibleConnector (Connector c, boolean isStart)
Collection< Action > getActions (Point2D.Double p)
Tool getTool (Point2D.Double p)
boolean handleMouseClick (Point2D.Double p, MouseEvent evt, DrawingView view)
boolean handleDrop (Point2D.Double p, Collection< Figure > droppedFigures, DrawingView view)
Point2D.Double getEndPoint ()
Point2D.Double getStartPoint ()
boolean isConnectable ()
void setConnectable (boolean newValue)
boolean isSelectable ()
void setSelectable (boolean newValue)
boolean isRemovable ()
void setRemovable (boolean newValue)
boolean isTransformable ()
void setTransformable (boolean newValue)
boolean isVisible ()
void setVisible (boolean newValue)
void requestRemove ()
int getLayer ()
String getToolTipText (Point2D.Double p)
String toString ()
Collection< Connector > getConnectors (ConnectionFigure prototype)
Public Member Functions inherited from org.jhotdraw.draw.figure.Figure
void addPropertyChangeListener (PropertyChangeListener listener)
void removePropertyChangeListener (PropertyChangeListener listener)
Protected Member Functions
void drawChildren (Graphics2D g)
abstract void drawFill (java.awt.Graphics2D g)
abstract void drawStroke (java.awt.Graphics2D g)
void drawText (java.awt.Graphics2D g)
void writeAttributes (DOMOutput out) throws IOException
void readAttributes (DOMInput in) throws IOException
AttributeKey<?> getAttributeKey (String name)
void applyAttributesTo (Figure that)
Protected Member Functions inherited from org.jhotdraw.draw.figure.AbstractCompositeFigure
EventHandler createEventHandler ()
void validate ()
void invalidate ()
void fireFigureAdded (Figure f, int zIndex)
void fireFigureRemoved (Figure f, int zIndex)
Protected Member Functions inherited from org.jhotdraw.draw.figure.AbstractFigure
Drawing getDrawing ()
Object getLock ()
void fireAreaInvalidated (Rectangle2D.Double invalidatedArea)
void fireAreaInvalidated (FigureEvent event)
void fireFigureRequestRemove ()
void fireFigureAdded ()
void fireFigureRemoved ()
void fireFigureChanged (Rectangle2D.Double changedArea)
void fireFigureChanged (FigureEvent event)
void fireFigureHandlesChanged ()
void fireUndoableEditHappened (UndoableEdit edit)
boolean isChanging ()
int getChangingDepth ()
FontRenderContext getFontRenderContext ()
Additional Inherited Members
Static Public Attributes inherited from org.jhotdraw.draw.figure.Figure
static final String CONNECTABLE_PROPERTY = "connectable"
static final String REMOVABLE_PROPERTY = "removable"
static final String SELECTABLE_PROPERTY = "selectable"
static final String TRANSFORMABLE_PROPERTY = "transformable"
Static Public Attributes inherited from org.jhotdraw.draw.figure.CompositeFigure
static final AttributeKey< Insets2D.Double > LAYOUT_INSETS = new AttributeKey<Insets2D.Double>("layoutInsets", Insets2D.Double.class, new Insets2D.Double())
Protected Attributes inherited from org.jhotdraw.draw.figure.AbstractCompositeFigure
Layouter layouter
ArrayList< Figure > children = new ArrayList<>()
transient Rectangle2D.Double cachedDrawingArea
transient Rectangle2D.Double cachedBounds
EventHandler eventHandler
Protected Attributes inherited from org.jhotdraw.draw.figure.AbstractFigure
EventListenerList listenerList = new EventListenerList()
int changingDepth = 0
Detailed Description
This abstract class can be extended to implement a CompositeFigure which has its own attribute set.
Author
Werner Randelshofer
Version
$Id$
Constructor & Destructor Documentation
AbstractAttributedCompositeFigure()
org.jhotdraw.draw.figure.AbstractAttributedCompositeFigure.AbstractAttributedCompositeFigure ()
Creates a new instance.
Referenced by org.jhotdraw.draw.figure.AbstractAttributedCompositeFigure.clone().
Member Function Documentation
applyAttributesTo()
void org.jhotdraw.draw.figure.AbstractAttributedCompositeFigure.applyAttributesTo (Figure that) protected
Applies all attributes of this figure to that figure.
clone()
AbstractAttributedCompositeFigure org.jhotdraw.draw.figure.AbstractAttributedCompositeFigure.clone ()
Returns a clone of the figure, with clones of all aggregated figures, such as children and decorators. The cloned figure does not clone the list of FigureListeners from its original.
Reimplemented from org.jhotdraw.draw.figure.AbstractCompositeFigure.
Reimplemented in org.jhotdraw.draw.QuadTreeDrawing, and org.jhotdraw.draw.AbstractDrawing.
References org.jhotdraw.draw.figure.AbstractAttributedCompositeFigure.AbstractAttributedCompositeFigure(), and org.jhotdraw.draw.figure.AbstractAttributedCompositeFigure.clone().
Referenced by org.jhotdraw.draw.figure.AbstractAttributedCompositeFigure.clone().
drawChildren()
void org.jhotdraw.draw.figure.AbstractAttributedCompositeFigure.drawChildren (Graphics2D g) protected
References org.jhotdraw.draw.figure.AbstractCompositeFigure.getChildren().
Referenced by org.jhotdraw.draw.figure.AbstractAttributedCompositeFigure.drawFigure().
drawFigure()
void org.jhotdraw.draw.figure.AbstractAttributedCompositeFigure.drawFigure (Graphics2D g)
References org.jhotdraw.draw.figure.AbstractAttributedCompositeFigure.drawChildren(), org.jhotdraw.draw.figure.AbstractAttributedCompositeFigure.drawFill(), org.jhotdraw.draw.figure.AbstractAttributedCompositeFigure.drawStroke(), org.jhotdraw.draw.figure.AbstractAttributedCompositeFigure.drawText(), org.jhotdraw.draw.AttributeKeys.getScaleFactorFromGraphics(), and org.jhotdraw.draw.AttributeKeys.getStroke().
drawFill()
abstract void org.jhotdraw.draw.figure.AbstractAttributedCompositeFigure.drawFill (java.awt.Graphics2D g) abstract protected
This method is called by method draw() to draw the fill area of the figure. AttributedFigure configures the Graphics2D object with the FILL_COLOR attribute before calling this method. If the FILL_COLOR attribute is null, this method is not called.
Referenced by org.jhotdraw.draw.figure.AbstractAttributedCompositeFigure.drawFigure().
drawStroke()
abstract void org.jhotdraw.draw.figure.AbstractAttributedCompositeFigure.drawStroke (java.awt.Graphics2D g) abstract protected
This method is called by method draw() to draw the lines of the figure . AttributedFigure configures the Graphics2D object with the STROKE_COLOR attribute before calling this method. If the STROKE_COLOR attribute is null, this method is not called. This method is called by method draw() to draw the text of the figure . AttributedFigure configures the Graphics2D object with the TEXT_COLOR attribute before calling this method. If the TEXT_COLOR attribute is null, this method is not called.
Referenced by org.jhotdraw.draw.figure.AbstractAttributedCompositeFigure.drawFigure().
drawText()
void org.jhotdraw.draw.figure.AbstractAttributedCompositeFigure.drawText (java.awt.Graphics2D g) protected
Referenced by org.jhotdraw.draw.figure.AbstractAttributedCompositeFigure.drawFigure().
getAttributeKey()
AttributeKey<?> org.jhotdraw.draw.figure.AbstractAttributedCompositeFigure.getAttributeKey (String name) protected
References org.jhotdraw.draw.AttributeKeys.SUPPORTED_ATTRIBUTES_MAP.
Referenced by org.jhotdraw.draw.figure.AbstractAttributedCompositeFigure.readAttributes().
getAttributes()
Map<AttributeKey<?>, Object> org.jhotdraw.draw.figure.AbstractAttributedCompositeFigure.getAttributes ()
Returns a view to all attributes of this figure. By convention, an unmodifiable map is returned.
Reimplemented from org.jhotdraw.draw.figure.AbstractCompositeFigure.
Referenced by org.jhotdraw.draw.figure.AbstractAttributedCompositeFigure.getAttributesRestoreData().
getAttributesRestoreData()
Object org.jhotdraw.draw.figure.AbstractAttributedCompositeFigure.getAttributesRestoreData ()
Gets data which can be used to restore the attributes of the figure after a set has been applied to it.
Reimplemented from org.jhotdraw.draw.figure.AbstractCompositeFigure.
References org.jhotdraw.draw.figure.AbstractAttributedCompositeFigure.getAttributes(), and org.jhotdraw.draw.figure.AbstractCompositeFigure.getChildren().
getFigureDrawBounds()
Rectangle2D.Double org.jhotdraw.draw.figure.AbstractAttributedCompositeFigure.getFigureDrawBounds ()
References org.jhotdraw.draw.figure.AbstractCompositeFigure.getBounds(), and org.jhotdraw.draw.AttributeKeys.getStrokeTotalWidth().
getStroke()
Stroke org.jhotdraw.draw.figure.AbstractAttributedCompositeFigure.getStroke ()
References org.jhotdraw.draw.AttributeKeys.getStroke().
getStrokeMiterLimitFactor()
double org.jhotdraw.draw.figure.AbstractAttributedCompositeFigure.getStrokeMiterLimitFactor ()
References org.jhotdraw.draw.AttributeKeys.STROKE_MITER_LIMIT.
read()
void org.jhotdraw.draw.figure.AbstractAttributedCompositeFigure.read (DOMInput in) throws IOException
Reimplemented from org.jhotdraw.draw.figure.AbstractCompositeFigure.
Reimplemented in org.jhotdraw.draw.AbstractDrawing.
References org.jhotdraw.draw.figure.AbstractAttributedCompositeFigure.readAttributes().
readAttributes()
void org.jhotdraw.draw.figure.AbstractAttributedCompositeFigure.readAttributes (DOMInput in) throws IOException protected
References org.jhotdraw.draw.figure.AbstractAttributedCompositeFigure.getAttributeKey(), and org.jhotdraw.draw.AttributeKey< T >.isAssignable().
Referenced by org.jhotdraw.draw.figure.AbstractAttributedCompositeFigure.read().
restoreAttributesTo()
void org.jhotdraw.draw.figure.AbstractAttributedCompositeFigure.restoreAttributesTo (Object restoreData)
Restores the attributes of the figure to a previously stored state.
Reimplemented from org.jhotdraw.draw.figure.AbstractCompositeFigure.
References org.jhotdraw.draw.figure.AbstractCompositeFigure.getChildren(), and org.jhotdraw.draw.figure.AbstractAttributedCompositeFigure.setAttributes().
setAttributeEnabled()
void org.jhotdraw.draw.figure.AbstractAttributedCompositeFigure.setAttributeEnabled (AttributeKey<?> key, boolean b)
setAttributes()
void org.jhotdraw.draw.figure.AbstractAttributedCompositeFigure.setAttributes (Map< AttributeKey<?>, Object > map)
Referenced by org.jhotdraw.draw.figure.AbstractAttributedCompositeFigure.restoreAttributesTo().
write()
void org.jhotdraw.draw.figure.AbstractAttributedCompositeFigure.write (DOMOutput out) throws IOException
Reimplemented from org.jhotdraw.draw.figure.AbstractCompositeFigure.
Reimplemented in org.jhotdraw.draw.AbstractDrawing.
References org.jhotdraw.draw.figure.AbstractAttributedCompositeFigure.writeAttributes().
writeAttributes()
void org.jhotdraw.draw.figure.AbstractAttributedCompositeFigure.writeAttributes (DOMOutput out) throws IOException protected
References org.jhotdraw.draw.figure.Figure.get(), and org.jhotdraw.draw.AttributeKey< T >.getKey().
Referenced by org.jhotdraw.draw.figure.AbstractAttributedCompositeFigure.write().
The documentation for this class was generated from the following file:
jhotdraw-core/src/main/java/org/jhotdraw/draw/figure/AbstractAttributedCompositeFigure.java