jhotdraw: org.jhotdraw.draw.AttributeKeys Class Reference
org.jhotdraw.draw.AttributeKeys Class Reference
Classes
enum Alignment
enum Orientation
enum StrokePlacement
enum StrokeType
enum Underfill
enum WindingRule
Static Public Member Functions
static double getGlobalValueFactor (Figure f, double factor)
static double getScaleFactorFromGraphics (Graphics2D g)
static double getScaleFactor (AffineTransform transform)
static double getStrokeTotalWidth (Figure f, double factor)
static double getStrokeTotalMiterLimit (Figure f, double factor)
static Stroke getStroke (Figure f, double factor)
static Stroke getHitStroke (Figure f, double factor)
static Font getFont (Figure f)
static int getFontStyle (Figure f)
static double getPerpendicularFillGrowth (Figure f, double factor)
static double getPerpendicularDrawGrowth (Figure f, double factor)
static double getPerpendicularHitGrowth (Figure f, double factor)
Static Public Attributes
static final AttributeKey< Color > CANVAS_FILL_COLOR = new AttributeKey<Color>("canvasFillColor", Color.class, Color.white, true, LABELS)
static final AttributeKey< Double > CANVAS_FILL_OPACITY = new AttributeKey<Double>("canvasFillOpacity", Double.class, 1d, false, LABELS)
static final AttributeKey< Double > CANVAS_WIDTH = new AttributeKey<Double>("canvasWidth", Double.class, null, true, LABELS)
static final AttributeKey< Double > CANVAS_HEIGHT = new AttributeKey<Double>("canvasHeight", Double.class, null, true, LABELS)
static final AttributeKey< Color > FILL_COLOR = new AttributeKey<Color>("fillColor", Color.class, Color.white, true, LABELS)
static final AttributeKey< Boolean > PATH_CLOSED = new AttributeKey<Boolean>("pathClosed", Boolean.class, false, false, LABELS)
static final AttributeKey< Boolean > UNCLOSED_PATH_FILLED = new AttributeKey<Boolean>("unclosedPathFilled", Boolean.class, false, false, LABELS)
static final AttributeKey< WindingRule > WINDING_RULE = new AttributeKey<WindingRule>("windingRule", WindingRule.class, WindingRule.EVEN_ODD, false, LABELS)
static final AttributeKey< Underfill > FILL_UNDER_STROKE = new AttributeKey<Underfill>("fillUnderStroke", Underfill.class, Underfill.CENTER, false, LABELS)
static final AttributeKey< Color > STROKE_COLOR = new AttributeKey<Color>("strokeColor", Color.class, Color.black, true, LABELS)
static final AttributeKey< Double > STROKE_WIDTH = new AttributeKey<Double>("strokeWidth", Double.class, 1d, false, LABELS)
static final AttributeKey< Double > STROKE_INNER_WIDTH_FACTOR = new AttributeKey<Double>("innerStrokeWidthFactor", Double.class, 2d, false, LABELS)
static final AttributeKey< Integer > STROKE_JOIN = new AttributeKey<Integer>("strokeJoin", Integer.class, BasicStroke.JOIN_MITER, false, LABELS)
static final AttributeKey< Integer > STROKE_CAP = new AttributeKey<Integer>("strokeCap", Integer.class, BasicStroke.CAP_BUTT, false, LABELS)
static final AttributeKey< Double > STROKE_MITER_LIMIT = new AttributeKey<Double>("strokeMiterLimitFactor", Double.class, 3d, false, LABELS)
static final AttributeKey< Boolean > IS_STROKE_MITER_LIMIT_FACTOR = new AttributeKey<Boolean>("isStrokeMiterLimitFactor", Boolean.class, true, false, LABELS)
static final AttributeKey< double[]> STROKE_DASHES = new AttributeKey<double[]>("strokeDashes", double[].class, null, true, LABELS)
static final AttributeKey< Double > STROKE_DASH_PHASE = new AttributeKey<Double>("strokeDashPhase", Double.class, 0d, false, LABELS)
static final AttributeKey< Boolean > IS_STROKE_DASH_FACTOR = new AttributeKey<Boolean>("isStrokeDashFactor", Boolean.class, true, false, LABELS)
static final AttributeKey< Boolean > IS_STROKE_PIXEL_VALUE = new AttributeKey<Boolean>("isStrokePixelValue", Boolean.class, false, false, LABELS)
static final AttributeKey< StrokeType > STROKE_TYPE = new AttributeKey<StrokeType>("strokeType", StrokeType.class, StrokeType.BASIC, false, LABELS)
static final AttributeKey< StrokePlacement > STROKE_PLACEMENT = new AttributeKey<StrokePlacement>("strokePlacement", StrokePlacement.class, StrokePlacement.CENTER, false, LABELS)
static final AttributeKey< String > TEXT = new AttributeKey<String>("text", String.class, null, true, LABELS)
static final AttributeKey< Color > TEXT_COLOR = new AttributeKey<Color>("textColor", Color.class, Color.BLACK, false, LABELS)
static final AttributeKey< Color > TEXT_SHADOW_COLOR = new AttributeKey<Color>("textShadowColor", Color.class, null, true, LABELS)
static final AttributeKey< Dimension2DDouble > TEXT_SHADOW_OFFSET = new AttributeKey<Dimension2DDouble>("textShadowOffset", Dimension2DDouble.class, new Dimension2DDouble(1d, 1d), false, LABELS)
static final AttributeKey< Alignment > TEXT_ALIGNMENT = new AttributeKey<Alignment>("textAlignment", Alignment.class, Alignment.LEADING, false, LABELS)
static final AttributeKey< Font > FONT_FACE = new AttributeKey<Font>("fontFace", Font.class, new Font("VERDANA", Font.PLAIN, 10), false, LABELS)
static final AttributeKey< Double > FONT_SIZE = new AttributeKey<Double>("fontSize", Double.class, 12d, false, LABELS)
static final AttributeKey< Boolean > FONT_BOLD = new AttributeKey<Boolean>("fontBold", Boolean.class, false, false, LABELS)
static final AttributeKey< Boolean > FONT_ITALIC = new AttributeKey<Boolean>("fontItalic", Boolean.class, false, false, LABELS)
static final AttributeKey< Boolean > FONT_UNDERLINE = new AttributeKey<Boolean>("fontUnderline", Boolean.class, false, false, LABELS)
static final AttributeKey< Liner > BEZIER_PATH_LAYOUTER = new AttributeKey<Liner>("bezierPathLayouter", Liner.class, null, true, LABELS)
static final AttributeKey< LineDecoration > END_DECORATION = new AttributeKey<LineDecoration>("endDecoration", LineDecoration.class, null, true, LABELS)
static final AttributeKey< LineDecoration > START_DECORATION = new AttributeKey<LineDecoration>("startDecoration", LineDecoration.class, null, true, LABELS)
static final AttributeKey< Insets2D.Double > DECORATOR_INSETS = new AttributeKey<Insets2D.Double>("decoratorInsets", Insets2D.Double.class, new Insets2D.Double(), false, LABELS)
static final AttributeKey< Insets2D.Double > LAYOUT_INSETS = new AttributeKey<Insets2D.Double>("borderInsets", Insets2D.Double.class, new Insets2D.Double(), false, LABELS)
static final AttributeKey< Alignment > COMPOSITE_ALIGNMENT = new AttributeKey<Alignment>("layoutAlignment", Alignment.class, Alignment.BLOCK, false, LABELS)
static final AttributeKey< Alignment > CHILD_ALIGNMENT = new AttributeKey<Alignment>("layoutAlignment", Alignment.class, null, true, LABELS)
static final AttributeKey< AffineTransform > TRANSFORM = new AttributeKey<AffineTransform>("transform", AffineTransform.class, null, true, LABELS)
static final AttributeKey< Orientation > ORIENTATION = new AttributeKey<Orientation>("orientation", Orientation.class, Orientation.NORTH, false, LABELS)
static final Set< AttributeKey<?> > SUPPORTED_ATTRIBUTES
static final Map< String, AttributeKey<?> > SUPPORTED_ATTRIBUTES_MAP
Detailed Description
Defines a put of well known Figure attributes.
If you are developing an applications that uses a different put or an extended put of attributes, it is recommended to create a new AttributeKeys class, and to define all needed AttributeKeys as static variables in there.
Author
Werner Randelshofer
Version
$Id$
Member Function Documentation
getFont()
static Font org.jhotdraw.draw.AttributeKeys.getFont (Figure f) static
References org.jhotdraw.draw.AttributeKeys.FONT_FACE, org.jhotdraw.draw.AttributeKeys.FONT_SIZE, org.jhotdraw.draw.figure.Figure.get(), and org.jhotdraw.draw.AttributeKeys.getFontStyle().
Referenced by org.jhotdraw.draw.figure.TextAreaFigure.getFont(), and org.jhotdraw.draw.figure.TextFigure.getFont().
getFontStyle()
static int org.jhotdraw.draw.AttributeKeys.getFontStyle (Figure f) static
References org.jhotdraw.draw.AttributeKeys.FONT_BOLD, org.jhotdraw.draw.AttributeKeys.FONT_ITALIC, and org.jhotdraw.draw.figure.Figure.get().
Referenced by org.jhotdraw.draw.AttributeKeys.getFont().
getGlobalValueFactor()
static double org.jhotdraw.draw.AttributeKeys.getGlobalValueFactor (Figure f, double factor) static
Computing a global scale factor derived from pixel with or different measures.
References org.jhotdraw.draw.figure.Figure.get(), and org.jhotdraw.draw.AttributeKeys.IS_STROKE_PIXEL_VALUE.
Referenced by org.jhotdraw.draw.AttributeKeys.getHitStroke(), org.jhotdraw.draw.AttributeKeys.getStroke(), org.jhotdraw.draw.AttributeKeys.getStrokeTotalMiterLimit(), and org.jhotdraw.draw.AttributeKeys.getStrokeTotalWidth().
getHitStroke()
static Stroke org.jhotdraw.draw.AttributeKeys.getHitStroke (Figure f, double factor) static
Returns a stroke which is useful for hit-testing. The stroke reflects the stroke width, but not the stroke dashes attribute.
Parameters
f
Returns
A stroke suited for creating a shape for hit testing.
References org.jhotdraw.draw.figure.Figure.get(), org.jhotdraw.draw.AttributeKeys.getGlobalValueFactor(), org.jhotdraw.draw.AttributeKeys.getStrokeTotalMiterLimit(), org.jhotdraw.draw.AttributeKeys.IS_STROKE_DASH_FACTOR, org.jhotdraw.draw.AttributeKeys.STROKE_CAP, org.jhotdraw.draw.AttributeKeys.STROKE_DASH_PHASE, org.jhotdraw.draw.AttributeKeys.STROKE_INNER_WIDTH_FACTOR, org.jhotdraw.draw.AttributeKeys.STROKE_JOIN, org.jhotdraw.draw.AttributeKeys.STROKE_TYPE, and org.jhotdraw.draw.AttributeKeys.STROKE_WIDTH.
getPerpendicularDrawGrowth()
static double org.jhotdraw.draw.AttributeKeys.getPerpendicularDrawGrowth (Figure f, double factor) static
Returns the distance, that a Rectangle needs to grow (or shrink) to draw (aka stroke) its shape as specified by the FILL_UNDER_STROKE and STROKE_POSITION attributes of a figure. The value returned is the number of units that need to be grown (or shrunk) perpendicular to a stroke on an outline of the shape.
References org.jhotdraw.draw.figure.Figure.get(), org.jhotdraw.draw.AttributeKeys.getStrokeTotalWidth(), and org.jhotdraw.draw.AttributeKeys.STROKE_PLACEMENT.
Referenced by org.jhotdraw.draw.figure.BezierFigure.drawStroke(), org.jhotdraw.draw.figure.DiamondFigure.drawStroke(), org.jhotdraw.draw.figure.EllipseFigure.drawStroke(), org.jhotdraw.draw.figure.ImageFigure.drawStroke(), org.jhotdraw.draw.figure.RectangleFigure.drawStroke(), org.jhotdraw.draw.figure.RoundRectangleFigure.drawStroke(), org.jhotdraw.draw.figure.TriangleFigure.drawStroke(), and org.jhotdraw.draw.AttributeKeys.getPerpendicularHitGrowth().
getPerpendicularFillGrowth()
static double org.jhotdraw.draw.AttributeKeys.getPerpendicularFillGrowth (Figure f, double factor) static
Returns the distance, that a Rectangle needs to grow (or shrink) to fill its shape as specified by the FILL_UNDER_STROKE and STROKE_POSITION attributes of a figure. The value returned is the number of units that need to be grown (or shrunk) perpendicular to a stroke on an outline of the shape.
References org.jhotdraw.draw.AttributeKeys.FILL_UNDER_STROKE, org.jhotdraw.draw.figure.Figure.get(), org.jhotdraw.draw.AttributeKeys.getStrokeTotalWidth(), and org.jhotdraw.draw.AttributeKeys.STROKE_PLACEMENT.
Referenced by org.jhotdraw.draw.figure.DiamondFigure.contains(), org.jhotdraw.draw.figure.BezierFigure.drawFill(), org.jhotdraw.draw.figure.DiamondFigure.drawFill(), org.jhotdraw.draw.figure.EllipseFigure.drawFill(), org.jhotdraw.draw.figure.ImageFigure.drawFill(), org.jhotdraw.draw.figure.RectangleFigure.drawFill(), org.jhotdraw.draw.figure.RoundRectangleFigure.drawFill(), org.jhotdraw.draw.figure.TriangleFigure.drawFill(), and org.jhotdraw.draw.AttributeKeys.getPerpendicularHitGrowth().
getPerpendicularHitGrowth()
static double org.jhotdraw.draw.AttributeKeys.getPerpendicularHitGrowth (Figure f, double factor) static
Returns the distance, that a Rectangle needs to grow (or shrink) to make hit detections on a shape as specified by the FILL_UNDER_STROKE and STROKE_POSITION attributes of a figure. The value returned is the number of units that need to be grown (or shrunk) perpendicular to a stroke on an outline of the shape.
References org.jhotdraw.draw.figure.Figure.get(), org.jhotdraw.draw.AttributeKeys.getPerpendicularDrawGrowth(), org.jhotdraw.draw.AttributeKeys.getPerpendicularFillGrowth(), org.jhotdraw.draw.AttributeKeys.getStrokeTotalWidth(), and org.jhotdraw.draw.AttributeKeys.STROKE_COLOR.
Referenced by org.jhotdraw.draw.figure.BezierFigure.chop(), org.jhotdraw.draw.figure.TriangleFigure.chop(), org.jhotdraw.draw.figure.BezierFigure.contains(), org.jhotdraw.draw.figure.EllipseFigure.contains(), org.jhotdraw.draw.figure.RectangleFigure.contains(), org.jhotdraw.draw.figure.RoundRectangleFigure.contains(), org.jhotdraw.draw.figure.TriangleFigure.contains(), org.jhotdraw.draw.figure.ImageFigure.figureContains(), org.jhotdraw.draw.figure.DiamondFigure.getDrawingArea(), org.jhotdraw.draw.figure.EllipseFigure.getDrawingArea(), org.jhotdraw.draw.figure.RectangleFigure.getDrawingArea(), org.jhotdraw.draw.figure.RoundRectangleFigure.getDrawingArea(), and org.jhotdraw.draw.figure.ImageFigure.getFigureDrawingArea().
getScaleFactor()
static double org.jhotdraw.draw.AttributeKeys.getScaleFactor (AffineTransform transform) static
Returns a scale factor derived from a AffineTransform.
Parameters
transform
Returns
Referenced by org.jhotdraw.draw.AttributeKeys.getScaleFactorFromGraphics().
getScaleFactorFromGraphics()
static double org.jhotdraw.draw.AttributeKeys.getScaleFactorFromGraphics (Graphics2D g) static
Returns a scale factor derived from a Graphics2D context.
Parameters
g
Returns
References org.jhotdraw.draw.AttributeKeys.getScaleFactor().
Referenced by org.jhotdraw.draw.DefaultDrawing.draw(), org.jhotdraw.draw.figure.AbstractAttributedFigure.draw(), org.jhotdraw.draw.QuadTreeDrawing.draw(), org.jhotdraw.draw.decoration.AbstractLineDecoration.draw(), org.jhotdraw.draw.figure.AbstractAttributedCompositeFigure.drawFigure(), org.jhotdraw.draw.figure.ImageFigure.drawFigure(), org.jhotdraw.draw.figure.BezierFigure.drawFill(), org.jhotdraw.draw.figure.DiamondFigure.drawFill(), org.jhotdraw.draw.figure.EllipseFigure.drawFill(), org.jhotdraw.draw.figure.ImageFigure.drawFill(), org.jhotdraw.draw.figure.RectangleFigure.drawFill(), org.jhotdraw.draw.figure.RoundRectangleFigure.drawFill(), org.jhotdraw.draw.figure.TriangleFigure.drawFill(), org.jhotdraw.draw.figure.BezierFigure.drawStroke(), org.jhotdraw.draw.figure.DiamondFigure.drawStroke(), org.jhotdraw.draw.figure.EllipseFigure.drawStroke(), org.jhotdraw.draw.figure.ImageFigure.drawStroke(), org.jhotdraw.draw.figure.RectangleFigure.drawStroke(), org.jhotdraw.draw.figure.RoundRectangleFigure.drawStroke(), org.jhotdraw.draw.figure.TriangleFigure.drawStroke(), and org.jhotdraw.draw.print.DrawingPageable.printPage().
getStroke()
static Stroke org.jhotdraw.draw.AttributeKeys.getStroke (Figure f, double factor) static
References org.jhotdraw.draw.figure.Figure.get(), org.jhotdraw.draw.AttributeKeys.getGlobalValueFactor(), org.jhotdraw.draw.AttributeKeys.getStrokeTotalMiterLimit(), org.jhotdraw.draw.AttributeKeys.IS_STROKE_DASH_FACTOR, org.jhotdraw.draw.AttributeKeys.STROKE_CAP, org.jhotdraw.draw.AttributeKeys.STROKE_DASH_PHASE, org.jhotdraw.draw.AttributeKeys.STROKE_DASHES, org.jhotdraw.draw.AttributeKeys.STROKE_INNER_WIDTH_FACTOR, org.jhotdraw.draw.AttributeKeys.STROKE_JOIN, org.jhotdraw.draw.AttributeKeys.STROKE_TYPE, and org.jhotdraw.draw.AttributeKeys.STROKE_WIDTH.
Referenced by org.jhotdraw.draw.figure.AbstractAttributedFigure.draw(), org.jhotdraw.draw.decoration.AbstractLineDecoration.draw(), org.jhotdraw.draw.figure.AbstractAttributedCompositeFigure.drawFigure(), org.jhotdraw.draw.figure.ImageFigure.drawFigure(), and org.jhotdraw.draw.figure.AbstractAttributedCompositeFigure.getStroke().
getStrokeTotalMiterLimit()
static double org.jhotdraw.draw.AttributeKeys.getStrokeTotalMiterLimit (Figure f, double factor) static
Convenience method for computing the total stroke miter limit from the STROKE_MITER_LIMIT, and IS_STROKE_MITER_LIMIT factor.
References org.jhotdraw.draw.figure.Figure.get(), org.jhotdraw.draw.AttributeKeys.getGlobalValueFactor(), org.jhotdraw.draw.AttributeKeys.IS_STROKE_MITER_LIMIT_FACTOR, org.jhotdraw.draw.AttributeKeys.STROKE_MITER_LIMIT, and org.jhotdraw.draw.AttributeKeys.STROKE_WIDTH.
Referenced by org.jhotdraw.draw.AttributeKeys.getHitStroke(), and org.jhotdraw.draw.AttributeKeys.getStroke().
getStrokeTotalWidth()
static double org.jhotdraw.draw.AttributeKeys.getStrokeTotalWidth (Figure f, double factor) static
Convenience method for computing the total stroke width from the STROKE_WIDTH, STROKE_INNER_WIDTH and STROKE_TYPE attributes.
References org.jhotdraw.draw.figure.Figure.get(), org.jhotdraw.draw.AttributeKeys.getGlobalValueFactor(), org.jhotdraw.draw.AttributeKeys.STROKE_INNER_WIDTH_FACTOR, org.jhotdraw.draw.AttributeKeys.STROKE_TYPE, and org.jhotdraw.draw.AttributeKeys.STROKE_WIDTH.
Referenced by org.jhotdraw.draw.connector.ChopRectangleConnector.chop(), org.jhotdraw.draw.connector.ChopRoundRectangleConnector.chop(), org.jhotdraw.draw.GraphicalCompositeFigure.chop(), org.jhotdraw.draw.figure.BezierFigure.chop(), org.jhotdraw.draw.figure.TriangleFigure.chop(), org.jhotdraw.draw.figure.BezierFigure.contains(), org.jhotdraw.draw.figure.TriangleFigure.contains(), org.jhotdraw.draw.figure.BezierFigure.drawFill(), org.jhotdraw.draw.figure.TriangleFigure.drawFill(), org.jhotdraw.draw.figure.BezierFigure.drawStroke(), org.jhotdraw.draw.figure.TriangleFigure.drawStroke(), org.jhotdraw.draw.figure.TriangleFigure.getDrawingArea(), org.jhotdraw.draw.figure.AbstractAttributedFigure.getDrawingArea(), org.jhotdraw.draw.figure.AbstractAttributedCompositeFigure.getFigureDrawBounds(), org.jhotdraw.draw.AttributeKeys.getPerpendicularDrawGrowth(), org.jhotdraw.draw.AttributeKeys.getPerpendicularFillGrowth(), and org.jhotdraw.draw.AttributeKeys.getPerpendicularHitGrowth().
Member Data Documentation
BEZIER_PATH_LAYOUTER
final AttributeKey<Liner> org.jhotdraw.draw.AttributeKeys.BEZIER_PATH_LAYOUTER = new AttributeKey<Liner>("bezierPathLayouter", Liner.class, null, true, LABELS) static
The value of this attribute is a Liner object.
CANVAS_FILL_COLOR
final AttributeKey<Color> org.jhotdraw.draw.AttributeKeys.CANVAS_FILL_COLOR = new AttributeKey<Color>("canvasFillColor", Color.class, Color.white, true, LABELS) static
Canvas fill color. The value of this attribute is a Color object. This attribute is used by a Drawing object to specify the fill color of the drawing. The default value is white.
CANVAS_FILL_OPACITY
final AttributeKey<Double> org.jhotdraw.draw.AttributeKeys.CANVAS_FILL_OPACITY = new AttributeKey<Double>("canvasFillOpacity", Double.class, 1d, false, LABELS) static
Canvas fill opacity. The value of this attribute is a Double object. This is a value between 0 and 1 whereas 0 is translucent and 1 is fully opaque.
CANVAS_HEIGHT
final AttributeKey<Double> org.jhotdraw.draw.AttributeKeys.CANVAS_HEIGHT = new AttributeKey<Double>("canvasHeight", Double.class, null, true, LABELS) static
The height of the canvas. The value of this attribute is a Double object. This is a value between 1 and Double.MAX_VALUE. If the value is null, the height is dynamically adapted to the content of the drawing.
CANVAS_WIDTH
final AttributeKey<Double> org.jhotdraw.draw.AttributeKeys.CANVAS_WIDTH = new AttributeKey<Double>("canvasWidth", Double.class, null, true, LABELS) static
The width of the canvas. The value of this attribute is a Double object. This is a value between 1 and Double.MAX_VALUE. If the value is null, the width is dynamically adapted to the content of the drawing.
CHILD_ALIGNMENT
final AttributeKey<Alignment> org.jhotdraw.draw.AttributeKeys.CHILD_ALIGNMENT = new AttributeKey<Alignment>("layoutAlignment", Alignment.class, null, true, LABELS) static
The value of this attribute is a Alignment object.
This attribute can be put on a child of a CompositeFigure, which uses a Layouter to lay out its children.
Layouters should use this attribute, to determine the default alignment of the child figures contained in the CompositeFigure which they lay out.
COMPOSITE_ALIGNMENT
final AttributeKey<Alignment> org.jhotdraw.draw.AttributeKeys.COMPOSITE_ALIGNMENT = new AttributeKey<Alignment>("layoutAlignment", Alignment.class, Alignment.BLOCK, false, LABELS) static
The value of this attribute is a Alignment object.
This attribute can be put on a CompositeFigure, which uses a Layouter to lay out its children.
The insets are used to determine the default alignment of the children of the CompositeFigure.
DECORATOR_INSETS
final AttributeKey<Insets2D.Double> org.jhotdraw.draw.AttributeKeys.DECORATOR_INSETS = new AttributeKey<Insets2D.Double>("decoratorInsets", Insets2D.Double.class, new Insets2D.Double(), false, LABELS) static
The value of this attribute is a Insets2D.Double object.
END_DECORATION
final AttributeKey<LineDecoration> org.jhotdraw.draw.AttributeKeys.END_DECORATION = new AttributeKey<LineDecoration>("endDecoration", LineDecoration.class, null, true, LABELS) static
FILL_COLOR
final AttributeKey<Color> org.jhotdraw.draw.AttributeKeys.FILL_COLOR = new AttributeKey<Color>("fillColor", Color.class, Color.white, true, LABELS) static
Figure fill color. The value of this attribute is a Color object.
FILL_UNDER_STROKE
final AttributeKey<Underfill> org.jhotdraw.draw.AttributeKeys.FILL_UNDER_STROKE = new AttributeKey<Underfill>("fillUnderStroke", Underfill.class, Underfill.CENTER, false, LABELS) static
Fill under stroke. The value of this attribute is a Boolean object.
Referenced by org.jhotdraw.draw.AttributeKeys.getPerpendicularFillGrowth().
FONT_BOLD
final AttributeKey<Boolean> org.jhotdraw.draw.AttributeKeys.FONT_BOLD = new AttributeKey<Boolean>("fontBold", Boolean.class, false, false, LABELS) static
The value of this attribute is a Boolean object.
Referenced by org.jhotdraw.draw.AttributeKeys.getFontStyle().
FONT_FACE
final AttributeKey<Font> org.jhotdraw.draw.AttributeKeys.FONT_FACE = new AttributeKey<Font>("fontFace", Font.class, new Font("VERDANA", Font.PLAIN, 10), false, LABELS) static
The value of this attribute is a Font object, which is used as a prototype to create the font for the text.
Referenced by org.jhotdraw.draw.action.DrawingColorChooserHandler.applySelectedColorToFigures(), org.jhotdraw.draw.action.SelectionColorChooserHandler.applySelectedColorToFigures(), and org.jhotdraw.draw.AttributeKeys.getFont().
FONT_ITALIC
final AttributeKey<Boolean> org.jhotdraw.draw.AttributeKeys.FONT_ITALIC = new AttributeKey<Boolean>("fontItalic", Boolean.class, false, false, LABELS) static
The value of this attribute is a Boolean object.
Referenced by org.jhotdraw.draw.AttributeKeys.getFontStyle().
FONT_SIZE
final AttributeKey<Double> org.jhotdraw.draw.AttributeKeys.FONT_SIZE = new AttributeKey<Double>("fontSize", Double.class, 12d, false, LABELS) static
The value of this attribute is a double object.
Referenced by org.jhotdraw.draw.AttributeKeys.getFont().
FONT_UNDERLINE
final AttributeKey<Boolean> org.jhotdraw.draw.AttributeKeys.FONT_UNDERLINE = new AttributeKey<Boolean>("fontUnderline", Boolean.class, false, false, LABELS) static
The value of this attribute is a Boolean object.
IS_STROKE_DASH_FACTOR
final AttributeKey<Boolean> org.jhotdraw.draw.AttributeKeys.IS_STROKE_DASH_FACTOR = new AttributeKey<Boolean>("isStrokeDashFactor", Boolean.class, true, false, LABELS) static
A boolean used to indicate whether STROKE_DASHES and STROKE_DASH_PHASE shall be interpreted as factors of STROKE_WIDTH, or whether they are absolute values.
Referenced by org.jhotdraw.draw.AttributeKeys.getHitStroke(), and org.jhotdraw.draw.AttributeKeys.getStroke().
IS_STROKE_MITER_LIMIT_FACTOR
final AttributeKey<Boolean> org.jhotdraw.draw.AttributeKeys.IS_STROKE_MITER_LIMIT_FACTOR = new AttributeKey<Boolean>("isStrokeMiterLimitFactor", Boolean.class, true, false, LABELS) static
A boolean used to indicate whether STROKE_MITER_LIMIT is a factor of STROKE_WIDTH, or whether it represents an absolute value.
Referenced by org.jhotdraw.draw.AttributeKeys.getStrokeTotalMiterLimit().
IS_STROKE_PIXEL_VALUE
final AttributeKey<Boolean> org.jhotdraw.draw.AttributeKeys.IS_STROKE_PIXEL_VALUE = new AttributeKey<Boolean>("isStrokePixelValue", Boolean.class, false, false, LABELS) static
Are stroke values pixel values or should they be transformed as well.
Referenced by org.jhotdraw.draw.AttributeKeys.getGlobalValueFactor().
LAYOUT_INSETS
final AttributeKey<Insets2D.Double> org.jhotdraw.draw.AttributeKeys.LAYOUT_INSETS = new AttributeKey<Insets2D.Double>("borderInsets", Insets2D.Double.class, new Insets2D.Double(), false, LABELS) static
The value of this attribute is a Insets2D.Double object.
This attribute can be put on a CompositeFigure, which uses a Layouter to lay out its children.
The insets are used to determine the insets between the bounds of the CompositeFigure and its children.
ORIENTATION
final AttributeKey<Orientation> org.jhotdraw.draw.AttributeKeys.ORIENTATION = new AttributeKey<Orientation>("orientation", Orientation.class, Orientation.NORTH, false, LABELS) static
Specifies the orientation of a Figure.
PATH_CLOSED
final AttributeKey<Boolean> org.jhotdraw.draw.AttributeKeys.PATH_CLOSED = new AttributeKey<Boolean>("pathClosed", Boolean.class, false, false, LABELS) static
Whether to path a BezierFigure is closed. The value of this attribute is a Boolean object.
START_DECORATION
final AttributeKey<LineDecoration> org.jhotdraw.draw.AttributeKeys.START_DECORATION = new AttributeKey<LineDecoration>("startDecoration", LineDecoration.class, null, true, LABELS) static
STROKE_CAP
final AttributeKey<Integer> org.jhotdraw.draw.AttributeKeys.STROKE_CAP = new AttributeKey<Integer>("strokeCap", Integer.class, BasicStroke.CAP_BUTT, false, LABELS) static
Stroke join. One of the BasicStroke.CAP_... values used to construct a BasicStroke.
Referenced by org.jhotdraw.draw.AttributeKeys.getHitStroke(), and org.jhotdraw.draw.AttributeKeys.getStroke().
STROKE_COLOR
final AttributeKey<Color> org.jhotdraw.draw.AttributeKeys.STROKE_COLOR = new AttributeKey<Color>("strokeColor", Color.class, Color.black, true, LABELS) static
Stroke color. The value of this attribute is a Color object.
Referenced by org.jhotdraw.draw.AttributeKeys.getPerpendicularHitGrowth().
STROKE_DASH_PHASE
final AttributeKey<Double> org.jhotdraw.draw.AttributeKeys.STROKE_DASH_PHASE = new AttributeKey<Double>("strokeDashPhase", Double.class, 0d, false, LABELS) static
A double used to specify the starting phase of the stroke dashes.
Referenced by org.jhotdraw.draw.AttributeKeys.getHitStroke(), and org.jhotdraw.draw.AttributeKeys.getStroke().
STROKE_DASHES
final AttributeKey<double[]> org.jhotdraw.draw.AttributeKeys.STROKE_DASHES = new AttributeKey<double[]>("strokeDashes", double[].class, null, true, LABELS) static
An array of doubles used to specify the dash pattern in a BasicStroke;
Referenced by org.jhotdraw.draw.AttributeKeys.getStroke().
STROKE_INNER_WIDTH_FACTOR
final AttributeKey<Double> org.jhotdraw.draw.AttributeKeys.STROKE_INNER_WIDTH_FACTOR = new AttributeKey<Double>("innerStrokeWidthFactor", Double.class, 2d, false, LABELS) static
Factor for the stroke inner width. This is a double. The default value is 2.
FIXME - This is not flexible enough. Lets replace this with a STROKE_STRIPES_ARRAY<Double[]> and a IS_STROKE_STRIPES_FACTOR.
Referenced by org.jhotdraw.draw.AttributeKeys.getHitStroke(), org.jhotdraw.draw.AttributeKeys.getStroke(), and org.jhotdraw.draw.AttributeKeys.getStrokeTotalWidth().
STROKE_JOIN
final AttributeKey<Integer> org.jhotdraw.draw.AttributeKeys.STROKE_JOIN = new AttributeKey<Integer>("strokeJoin", Integer.class, BasicStroke.JOIN_MITER, false, LABELS) static
Stroke join. One of the BasicStroke.JOIN_... values used to construct a BasicStroke.
Referenced by org.jhotdraw.draw.AttributeKeys.getHitStroke(), and org.jhotdraw.draw.AttributeKeys.getStroke().
STROKE_MITER_LIMIT
final AttributeKey<Double> org.jhotdraw.draw.AttributeKeys.STROKE_MITER_LIMIT = new AttributeKey<Double>("strokeMiterLimitFactor", Double.class, 3d, false, LABELS) static
Stroke miter limit factor. A double multiplied by total stroke width, used to construct the miter limit of a BasicStroke.
Referenced by org.jhotdraw.draw.figure.AbstractAttributedCompositeFigure.getStrokeMiterLimitFactor(), org.jhotdraw.draw.figure.AbstractAttributedFigure.getStrokeMiterLimitFactor(), and org.jhotdraw.draw.AttributeKeys.getStrokeTotalMiterLimit().
STROKE_PLACEMENT
final AttributeKey<StrokePlacement> org.jhotdraw.draw.AttributeKeys.STROKE_PLACEMENT = new AttributeKey<StrokePlacement>("strokePlacement", StrokePlacement.class, StrokePlacement.CENTER, false, LABELS) static
Stroke placement. The value is either StrokePlacement.CENTER, StrokePlacement.INSIDE or StrokePlacement.OUTSIDE. This only has effect for closed paths. On open paths, the stroke is always centered on the path.
The default value is StrokePlacement.CENTER.
Referenced by org.jhotdraw.draw.AttributeKeys.getPerpendicularDrawGrowth(), and org.jhotdraw.draw.AttributeKeys.getPerpendicularFillGrowth().
STROKE_TYPE
final AttributeKey<StrokeType> org.jhotdraw.draw.AttributeKeys.STROKE_TYPE = new AttributeKey<StrokeType>("strokeType", StrokeType.class, StrokeType.BASIC, false, LABELS) static
Stroke type. The value of this attribute is either VALUE_STROKE_TYPE_BASIC or VALUE_STROKE_TYPE_DOUBLE. FIXME - Type should be an enumeration.
Referenced by org.jhotdraw.draw.AttributeKeys.getHitStroke(), org.jhotdraw.draw.AttributeKeys.getStroke(), and org.jhotdraw.draw.AttributeKeys.getStrokeTotalWidth().
STROKE_WIDTH
final AttributeKey<Double> org.jhotdraw.draw.AttributeKeys.STROKE_WIDTH = new AttributeKey<Double>("strokeWidth", Double.class, 1d, false, LABELS) static
Stroke width. A double used to construct a BasicStroke or the outline of a DoubleStroke.
Referenced by org.jhotdraw.draw.AttributeKeys.getHitStroke(), org.jhotdraw.draw.AttributeKeys.getStroke(), org.jhotdraw.draw.AttributeKeys.getStrokeTotalMiterLimit(), and org.jhotdraw.draw.AttributeKeys.getStrokeTotalWidth().
SUPPORTED_ATTRIBUTES
final Set<AttributeKey<?> > org.jhotdraw.draw.AttributeKeys.SUPPORTED_ATTRIBUTES static
A put with all attributes defined by this class.
SUPPORTED_ATTRIBUTES_MAP
final Map<String, AttributeKey<?> > org.jhotdraw.draw.AttributeKeys.SUPPORTED_ATTRIBUTES_MAP static
Referenced by org.jhotdraw.draw.figure.AbstractAttributedCompositeFigure.getAttributeKey(), org.jhotdraw.draw.figure.AbstractAttributedFigure.getAttributeKey(), and org.jhotdraw.draw.GraphicalCompositeFigure.getAttributeKey().
TEXT
final AttributeKey<String> org.jhotdraw.draw.AttributeKeys.TEXT = new AttributeKey<String>("text", String.class, null, true, LABELS) static
The value of this attribute is a String object, which is used to display the text of the figure.
TEXT_ALIGNMENT
final AttributeKey<Alignment> org.jhotdraw.draw.AttributeKeys.TEXT_ALIGNMENT = new AttributeKey<Alignment>("textAlignment", Alignment.class, Alignment.LEADING, false, LABELS) static
Text alignment. The value of this attribute is a Alignment enum.
TEXT_COLOR
final AttributeKey<Color> org.jhotdraw.draw.AttributeKeys.TEXT_COLOR = new AttributeKey<Color>("textColor", Color.class, Color.BLACK, false, LABELS) static
Text color. The value of this attribute is a Color object.
TEXT_SHADOW_COLOR
final AttributeKey<Color> org.jhotdraw.draw.AttributeKeys.TEXT_SHADOW_COLOR = new AttributeKey<Color>("textShadowColor", Color.class, null, true, LABELS) static
Text shadow color. The value of this attribute is a Color object.
TEXT_SHADOW_OFFSET
final AttributeKey<Dimension2DDouble> org.jhotdraw.draw.AttributeKeys.TEXT_SHADOW_OFFSET = new AttributeKey<Dimension2DDouble>("textShadowOffset", Dimension2DDouble.class, new Dimension2DDouble(1d, 1d), false, LABELS) static
Text shadow offset. The value of this attribute is a Dimension2DDouble object.
TRANSFORM
final AttributeKey<AffineTransform> org.jhotdraw.draw.AttributeKeys.TRANSFORM = new AttributeKey<AffineTransform>("transform", AffineTransform.class, null, true, LABELS) static
Specifies the transform of a Figure.
UNCLOSED_PATH_FILLED
final AttributeKey<Boolean> org.jhotdraw.draw.AttributeKeys.UNCLOSED_PATH_FILLED = new AttributeKey<Boolean>("unclosedPathFilled", Boolean.class, false, false, LABELS) static
Whether an unclosed path of a BezierFigure is filled. The value of this attribute is a Boolean object.
WINDING_RULE
final AttributeKey<WindingRule> org.jhotdraw.draw.AttributeKeys.WINDING_RULE = new AttributeKey<WindingRule>("windingRule", WindingRule.class, WindingRule.EVEN_ODD, false, LABELS) static
Fill under stroke. The value of this attribute is a Boolean object.
The documentation for this class was generated from the following file:
jhotdraw-core/src/main/java/org/jhotdraw/draw/AttributeKeys.java