jhotdraw: org.jhotdraw.draw.DefaultDrawingEditor Class Reference
org.jhotdraw.draw.DefaultDrawingEditor Class Reference
Public Member Functions
DefaultDrawingEditor ()
void setTool (Tool newValue)
void setActiveView (DrawingView newValue)
Tool getTool ()
DrawingView getActiveView ()
void applyDefaultAttributesTo (Figure f)
void remove (DrawingView view)
void add (DrawingView view)
void setCursor (Cursor c)
Collection< DrawingView > getDrawingViews ()
DrawingView findView (Container c)
void setEnabled (boolean newValue)
boolean isEnabled ()
Map< AttributeKey<?>, Object > getDefaultAttributes ()
void setInputMap (InputMap newValue)
InputMap getInputMap ()
void setActionMap (ActionMap newValue)
ActionMap getActionMap ()
Public Member Functions inherited from org.jhotdraw.draw.DrawingEditor
void addPropertyChangeListener (PropertyChangeListener listener)
void removePropertyChangeListener (PropertyChangeListener listener)
Protected Member Functions
InputMap createInputMap ()
ActionMap createActionMap ()
Additional Inherited Members
Static Public Attributes inherited from org.jhotdraw.draw.DrawingEditor
static final String ACTIVE_VIEW_PROPERTY = "activeView"
static final String TOOL_PROPERTY = "tool"
static final String INPUT_MAP_PROPERTY = "inputMap"
static final String ACTION_MAP_PROPERTY = "actionMap"
static final String DEFAULT_ATTRIBUTE_PROPERTY_PREFIX = "defaultAttribute."
Detailed Description
A default implementation of DrawingEditor.
XXX - DefaultDrawingEditor should not publicly implement ToolListener.
Author
Werner Randelshofer
Version
$Id$
Constructor & Destructor Documentation
DefaultDrawingEditor()
org.jhotdraw.draw.DefaultDrawingEditor.DefaultDrawingEditor ()
Creates a new instance.
References org.jhotdraw.draw.DefaultDrawingEditor.createActionMap(), and org.jhotdraw.draw.DefaultDrawingEditor.createInputMap().
Member Function Documentation
add()
void org.jhotdraw.draw.DefaultDrawingEditor.add (DrawingView view)
Gets the editor's current drawing. / Drawing getDrawing(); /** Sets the editor's current drawing. / void setDrawing(Drawing drawing); Adds a drawing view to the editor. The editor invokes addNotify on the view, and it registers its tool as an event listener on the view.
Implements org.jhotdraw.draw.DrawingEditor.
References org.jhotdraw.draw.DrawingView.addKeyListener(), org.jhotdraw.draw.DrawingView.addMouseListener(), org.jhotdraw.draw.DrawingView.addMouseMotionListener(), org.jhotdraw.draw.DrawingView.addNotify(), and org.jhotdraw.draw.DrawingView.getComponent().
applyDefaultAttributesTo()
void org.jhotdraw.draw.DefaultDrawingEditor.applyDefaultAttributesTo (Figure f)
Applies the default attributes to the specified figure.
Implements org.jhotdraw.draw.DrawingEditor.
References org.jhotdraw.draw.figure.Figure.set().
createActionMap()
ActionMap org.jhotdraw.draw.DefaultDrawingEditor.createActionMap () protected
Override this method to create a tool-specific action map, which overrides the action map of the drawing editor.
The implementation of this class creates an action map which maps the following action ID's to the classes which define them:
DeleteAction
SelectAllAction
IncreaseHandleDetailLevelAction
MoveConstrainedAction.West, .East, .North, .South
MoveAction.West, .East, .North, .South
CutAction
CopyAction
PasteAction
References org.jhotdraw.draw.action.IncreaseHandleDetailLevelAction.ID.
Referenced by org.jhotdraw.draw.DefaultDrawingEditor.DefaultDrawingEditor().
createInputMap()
InputMap org.jhotdraw.draw.DefaultDrawingEditor.createInputMap () protected
Override this method to create a tool-specific input map, which overrides the input map of the drawing editor.
The implementation of this class creates an input map for the following action ID's:
DeleteAction
SelectAllAction
IncreaseHandleDetailLevelAction
MoveConstrainedAction.West, .East, .North, .South
MoveAction.West, .East, .North, .South
CutAction
CopyAction
PasteAction
References org.jhotdraw.draw.action.IncreaseHandleDetailLevelAction.ID.
Referenced by org.jhotdraw.draw.DefaultDrawingEditor.DefaultDrawingEditor().
findView()
DrawingView org.jhotdraw.draw.DefaultDrawingEditor.findView (Container c)
Finds a drawing view. This is used by Tool to identify the view of which it has received an event.
Implements org.jhotdraw.draw.DrawingEditor.
getActionMap()
ActionMap org.jhotdraw.draw.DefaultDrawingEditor.getActionMap ()
Gets the action map used by the tool of this drawing editor as a fall back for performing actions.
Tool
s use the action map of the drawing editor to determine what to do when an action needs to be invoked from the InputMap of the drawing editor.
This is a bound property.
Implements org.jhotdraw.draw.DrawingEditor.
getActiveView()
DrawingView org.jhotdraw.draw.DefaultDrawingEditor.getActiveView ()
Gets the editor's active drawing view. This can be null, if the editor has no views.
Implements org.jhotdraw.draw.DrawingEditor.
getDefaultAttributes()
Map<AttributeKey<?>, Object> org.jhotdraw.draw.DefaultDrawingEditor.getDefaultAttributes ()
Returns an immutable Map with the default attributes of this editor.
Implements org.jhotdraw.draw.DrawingEditor.
getDrawingViews()
Collection<DrawingView> org.jhotdraw.draw.DefaultDrawingEditor.getDrawingViews ()
Gets all drawing views associated with this editor.
Implements org.jhotdraw.draw.DrawingEditor.
getInputMap()
InputMap org.jhotdraw.draw.DefaultDrawingEditor.getInputMap ()
Sets the input map used by the tool of this drawing editor as a fall back for handling keyboard events.
Tool
s use the input map of the drawing editor to determine what to do when a key was pressed that the tool can not handle.
This is a bound property.
Implements org.jhotdraw.draw.DrawingEditor.
getTool()
Tool org.jhotdraw.draw.DefaultDrawingEditor.getTool ()
Gets the current tool.
This is a bound property.
Implements org.jhotdraw.draw.DrawingEditor.
isEnabled()
boolean org.jhotdraw.draw.DefaultDrawingEditor.isEnabled ()
Gets the enabled state of the drawing editor.
Implements org.jhotdraw.draw.DrawingEditor.
remove()
void org.jhotdraw.draw.DefaultDrawingEditor.remove (DrawingView view)
Removes a drawing view from the editor. The editor invokes removeNotify on the view, and it unregisters its tool on the view.
Implements org.jhotdraw.draw.DrawingEditor.
setActionMap()
void org.jhotdraw.draw.DefaultDrawingEditor.setActionMap (ActionMap newValue)
Sets the action map used by the tool of this drawing editor as a fall back for performing actions.
This is a bound property.
Implements org.jhotdraw.draw.DrawingEditor.
References org.jhotdraw.draw.DrawingEditor.ACTION_MAP_PROPERTY.
setActiveView()
void org.jhotdraw.draw.DefaultDrawingEditor.setActiveView (DrawingView newValue)
Sets the editor's active drawing view. This can be set to null, if the editor has no views.
Implements org.jhotdraw.draw.DrawingEditor.
References org.jhotdraw.draw.DrawingEditor.ACTIVE_VIEW_PROPERTY.
setCursor()
void org.jhotdraw.draw.DefaultDrawingEditor.setCursor (Cursor c)
Sets the cursor on the view(s) of the drawing editor.
Implements org.jhotdraw.draw.DrawingEditor.
setEnabled()
void org.jhotdraw.draw.DefaultDrawingEditor.setEnabled (boolean newValue)
Sets the enabled state of the drawing editor. This is a bound property.
Implements org.jhotdraw.draw.DrawingEditor.
setInputMap()
void org.jhotdraw.draw.DefaultDrawingEditor.setInputMap (InputMap newValue)
Sets the input map used by the tool of this drawing editor as a fall back for handling keyboard events.
This is a bound property.
Implements org.jhotdraw.draw.DrawingEditor.
References org.jhotdraw.draw.DrawingEditor.INPUT_MAP_PROPERTY.
setTool()
void org.jhotdraw.draw.DefaultDrawingEditor.setTool (Tool t)
Calls deactivate on the previously active tool of this drawing editor. Calls activate on the provided tool. Forwards all mouse, mouse moation and keyboard events that occur on the DrawingView to the provided tool.
This is a bound property.
Implements org.jhotdraw.draw.DrawingEditor.
References org.jhotdraw.draw.tool.Tool.activate(), org.jhotdraw.draw.tool.Tool.addToolListener(), org.jhotdraw.draw.tool.Tool.deactivate(), org.jhotdraw.draw.tool.Tool.removeToolListener(), and org.jhotdraw.draw.DrawingEditor.TOOL_PROPERTY.
The documentation for this class was generated from the following file:
jhotdraw-core/src/main/java/org/jhotdraw/draw/DefaultDrawingEditor.java