jhotdraw: org.jhotdraw.draw.action.PickAttributesAction Class Reference
org.jhotdraw.draw.action.PickAttributesAction Class Reference
Public Member Functions
PickAttributesAction (DrawingEditor editor)
void setExcludedAttributes (Set< AttributeKey<?>> a)
void actionPerformed (java.awt.event.ActionEvent e)
void pickAttributes ()
void selectionChanged (FigureSelectionEvent evt)
Public Member Functions inherited from org.jhotdraw.draw.action.AbstractSelectedAction
AbstractSelectedAction (DrawingEditor editor)
void dispose ()
void setEditor (DrawingEditor editor)
DrawingEditor getEditor ()
void setUpdateEnabledState (boolean newValue)
boolean isUpdatEnabledState ()
Additional Inherited Members
Protected Member Functions inherited from org.jhotdraw.draw.action.AbstractSelectedAction
void updateEnabledState ()
DrawingView getView ()
Drawing getDrawing ()
void fireUndoableEditHappened (UndoableEdit edit)
Detailed Description
PickAttributesAction.
Author
Werner Randelshofer
Version
$Id$
Constructor & Destructor Documentation
PickAttributesAction()
org.jhotdraw.draw.action.PickAttributesAction.PickAttributesAction (DrawingEditor editor)
Creates a new instance.
References org.jhotdraw.draw.action.AbstractSelectedAction.updateEnabledState().
Member Function Documentation
actionPerformed()
void org.jhotdraw.draw.action.PickAttributesAction.actionPerformed (java.awt.event.ActionEvent e)
References org.jhotdraw.draw.action.PickAttributesAction.pickAttributes().
pickAttributes()
void org.jhotdraw.draw.action.PickAttributesAction.pickAttributes ()
References org.jhotdraw.draw.figure.Figure.getAttributes(), org.jhotdraw.draw.action.AbstractSelectedAction.getEditor(), org.jhotdraw.draw.DrawingView.getSelectedFigures(), org.jhotdraw.draw.action.AbstractSelectedAction.getView(), and org.jhotdraw.draw.DrawingEditor.setDefaultAttribute().
Referenced by org.jhotdraw.draw.action.PickAttributesAction.actionPerformed().
selectionChanged()
void org.jhotdraw.draw.action.PickAttributesAction.selectionChanged (FigureSelectionEvent evt)
References org.jhotdraw.draw.action.AbstractSelectedAction.getView().
setExcludedAttributes()
void org.jhotdraw.draw.action.PickAttributesAction.setExcludedAttributes (Set< AttributeKey<?>> a)
Set of attributes that is excluded when applying default attributes. By default, the TRANSFORM attribute is excluded.
The documentation for this class was generated from the following file:
jhotdraw-core/src/main/java/org/jhotdraw/draw/action/PickAttributesAction.java