jhotdraw: org.jhotdraw.draw.handle.ConnectorHandle Class Reference
org.jhotdraw.draw.handle.ConnectorHandle Class Reference
Public Member Functions
ConnectorHandle (Connector connector, ConnectionFigure prototype)
Point2D.Double getLocationOnDrawing ()
Point getLocation ()
void draw (Graphics2D g)
void trackStart (Point anchor, int modifiersEx)
void trackStep (Point anchor, Point lead, int modifiersEx)
Rectangle getDrawingArea ()
void trackEnd (Point anchor, Point lead, int modifiersEx)
boolean isCombinableWith (Handle handle)
void repaintConnectors ()
Public Member Functions inherited from org.jhotdraw.draw.handle.AbstractHandle
AbstractHandle (Figure owner)
void addHandleListener (HandleListener l)
void removeHandleListener (HandleListener l)
Figure getOwner ()
void setView (DrawingView view)
DrawingView getView ()
DrawingEditor getEditor ()
boolean contains (Point p)
void invalidate ()
void dispose ()
void areaInvalidated (FigureEvent evt)
void figureAdded (FigureEvent e)
void figureRemoved (FigureEvent e)
void figureRequestRemove (FigureEvent e)
void figureChanged (FigureEvent evt)
Cursor getCursor ()
void keyTyped (KeyEvent evt)
void keyReleased (KeyEvent evt)
void keyPressed (KeyEvent evt)
final Rectangle getBounds ()
void trackDoubleClick (Point p, int modifiersEx)
void attributeChanged (FigureEvent e)
void viewTransformChanged ()
Collection< Handle > createSecondaryHandles ()
String getToolTipText (Point p)
void setToolTipText (String newValue)
void figureHandlesChanged (FigureEvent e)
Protected Member Functions
ConnectionFigure createConnection ()
void setConnection (ConnectionFigure newConnection)
ConnectionFigure getConnection ()
Figure getTargetFigure ()
void setTargetFigure (Figure newTargetFigure)
Connector findConnectableConnector (Figure connectableFigure, Point2D.Double p)
Rectangle basicGetBounds ()
Protected Member Functions inherited from org.jhotdraw.draw.handle.AbstractHandle
int getHandlesize ()
void fireAreaInvalidated (Rectangle invalidatedArea)
void fireUndoableEditHappened (UndoableEdit edit)
void fireHandleRequestRemove (Rectangle invalidatedArea)
void fireHandleRequestSecondaryHandles ()
void drawCircle (Graphics2D g, Color fill, Color stroke)
void drawRectangle (Graphics2D g, Color fill, Color stroke)
void drawDiamond (Graphics2D g, Color fill, Color stroke)
void updateBounds ()
Protected Attributes
Collection< Connector > connectors = Collections.emptyList()
Protected Attributes inherited from org.jhotdraw.draw.handle.AbstractHandle
DrawingView view
EventListenerList listenerList = new EventListenerList()
Detailed Description
A Handle associated to a Connector which allows to create a new ConnectionFigure by dragging the handle to another connector.
Author
Werner Randelshofer.
Version
$Id$
Constructor & Destructor Documentation
ConnectorHandle()
org.jhotdraw.draw.handle.ConnectorHandle.ConnectorHandle (Connector connector, ConnectionFigure prototype)
Creates a new instance.
References org.jhotdraw.draw.connector.Connector.getOwner().
Member Function Documentation
basicGetBounds()
Rectangle org.jhotdraw.draw.handle.ConnectorHandle.basicGetBounds () protected
Reimplemented from org.jhotdraw.draw.handle.AbstractHandle.
References org.jhotdraw.draw.handle.AbstractHandle.getHandlesize(), and org.jhotdraw.draw.handle.ConnectorHandle.getLocation().
createConnection()
ConnectionFigure org.jhotdraw.draw.handle.ConnectorHandle.createConnection () protected
Creates the ConnectionFigure. By default the figure prototype is cloned.
References org.jhotdraw.draw.figure.Figure.clone().
Referenced by org.jhotdraw.draw.handle.ConnectorHandle.trackStart().
draw()
void org.jhotdraw.draw.handle.ConnectorHandle.draw (Graphics2D g)
Draws this handle.
Reimplemented from org.jhotdraw.draw.handle.AbstractHandle.
References org.jhotdraw.draw.handle.HandleAttributeKeys.CONNECTED_CONNECTOR_HANDLE_FILL_COLOR, org.jhotdraw.draw.handle.HandleAttributeKeys.CONNECTED_CONNECTOR_HANDLE_STROKE_COLOR, org.jhotdraw.draw.handle.ConnectorHandle.connectors, org.jhotdraw.draw.handle.HandleAttributeKeys.DISCONNECTED_CONNECTOR_HANDLE_FILL_COLOR, org.jhotdraw.draw.handle.HandleAttributeKeys.DISCONNECTED_CONNECTOR_HANDLE_STROKE_COLOR, org.jhotdraw.draw.handle.AbstractHandle.drawCircle(), org.jhotdraw.draw.DrawingView.drawingToView(), org.jhotdraw.draw.DrawingView.getDrawingToViewTransform(), org.jhotdraw.draw.handle.AbstractHandle.getEditor(), org.jhotdraw.draw.figure.ConnectionFigure.getEndPoint(), org.jhotdraw.draw.handle.AbstractHandle.getHandlesize(), and org.jhotdraw.draw.handle.AbstractHandle.view.
findConnectableConnector()
Connector org.jhotdraw.draw.handle.ConnectorHandle.findConnectableConnector (Figure connectableFigure, Point2D.Double p) protected
Finds a connection end figure.
References org.jhotdraw.draw.figure.ConnectionFigure.canConnect(), org.jhotdraw.draw.figure.Figure.findConnector(), org.jhotdraw.draw.handle.ConnectorHandle.getConnection(), org.jhotdraw.draw.handle.AbstractHandle.getOwner(), org.jhotdraw.draw.figure.Figure.includes(), and org.jhotdraw.draw.figure.Figure.isConnectable().
Referenced by org.jhotdraw.draw.handle.ConnectorHandle.trackEnd(), and org.jhotdraw.draw.handle.ConnectorHandle.trackStep().
getConnection()
ConnectionFigure org.jhotdraw.draw.handle.ConnectorHandle.getConnection () protected
Referenced by org.jhotdraw.draw.handle.ConnectorHandle.findConnectableConnector(), org.jhotdraw.draw.handle.ConnectorHandle.getDrawingArea(), org.jhotdraw.draw.handle.ConnectorHandle.trackEnd(), org.jhotdraw.draw.handle.ConnectorHandle.trackStart(), and org.jhotdraw.draw.handle.ConnectorHandle.trackStep().
getDrawingArea()
Rectangle org.jhotdraw.draw.handle.ConnectorHandle.getDrawingArea ()
Returns the drawing area of the handle. Note: The drawing area must be returned in the coordinate system of the DrawingView.
Reimplemented from org.jhotdraw.draw.handle.AbstractHandle.
References org.jhotdraw.draw.DrawingView.drawingToView(), org.jhotdraw.draw.handle.ConnectorHandle.getConnection(), org.jhotdraw.draw.handle.AbstractHandle.getHandlesize(), and org.jhotdraw.draw.handle.AbstractHandle.view.
Referenced by org.jhotdraw.draw.handle.ConnectorHandle.trackEnd(), and org.jhotdraw.draw.handle.ConnectorHandle.trackStep().
getLocation()
Point org.jhotdraw.draw.handle.ConnectorHandle.getLocation ()
References org.jhotdraw.draw.DrawingView.drawingToView(), org.jhotdraw.draw.connector.Connector.getAnchor(), and org.jhotdraw.draw.handle.AbstractHandle.view.
Referenced by org.jhotdraw.draw.handle.ConnectorHandle.basicGetBounds().
getLocationOnDrawing()
Point2D.Double org.jhotdraw.draw.handle.ConnectorHandle.getLocationOnDrawing ()
References org.jhotdraw.draw.connector.Connector.getAnchor().
Referenced by org.jhotdraw.draw.handle.ConnectorHandle.trackStart().
getTargetFigure()
Figure org.jhotdraw.draw.handle.ConnectorHandle.getTargetFigure () protected
isCombinableWith()
boolean org.jhotdraw.draw.handle.ConnectorHandle.isCombinableWith (Handle handle)
Returns true, if the given handle is an instance of the same class or of a subclass of this handle,.
Reimplemented from org.jhotdraw.draw.handle.AbstractHandle.
repaintConnectors()
void org.jhotdraw.draw.handle.ConnectorHandle.repaintConnectors ()
Updates the list of connectors that we draw when the user moves or drags the mouse over a figure to which can connect.
References org.jhotdraw.draw.handle.ConnectorHandle.connectors, org.jhotdraw.draw.DrawingView.drawingToView(), org.jhotdraw.draw.DrawingView.getComponent(), org.jhotdraw.draw.figure.Figure.getConnectors(), and org.jhotdraw.draw.handle.AbstractHandle.view.
Referenced by org.jhotdraw.draw.handle.ConnectorHandle.trackStep().
setConnection()
void org.jhotdraw.draw.handle.ConnectorHandle.setConnection (ConnectionFigure newConnection) protected
Referenced by org.jhotdraw.draw.handle.ConnectorHandle.trackEnd(), and org.jhotdraw.draw.handle.ConnectorHandle.trackStart().
setTargetFigure()
void org.jhotdraw.draw.handle.ConnectorHandle.setTargetFigure (Figure newTargetFigure) protected
Referenced by org.jhotdraw.draw.handle.ConnectorHandle.trackEnd().
trackEnd()
void org.jhotdraw.draw.handle.ConnectorHandle.trackEnd (Point anchor, Point lead, int modifiersEx)
Tracks the end of the interaction.
Parameters
anchor the position where the interaction started
lead the current position
Implements org.jhotdraw.draw.handle.Handle.
References org.jhotdraw.draw.Drawing.add(), org.jhotdraw.draw.DrawingView.addToSelection(), org.jhotdraw.draw.DrawingView.clearSelection(), org.jhotdraw.draw.handle.ConnectorHandle.connectors, org.jhotdraw.draw.Constrainer.constrainPoint(), org.jhotdraw.draw.handle.ConnectorHandle.findConnectableConnector(), org.jhotdraw.draw.handle.AbstractHandle.fireAreaInvalidated(), org.jhotdraw.draw.Drawing.fireUndoableEditHappened(), org.jhotdraw.draw.handle.ConnectorHandle.getConnection(), org.jhotdraw.draw.DrawingView.getConstrainer(), org.jhotdraw.draw.DrawingView.getDrawing(), org.jhotdraw.draw.handle.ConnectorHandle.getDrawingArea(), org.jhotdraw.draw.Drawing.remove(), org.jhotdraw.draw.handle.ConnectorHandle.setConnection(), org.jhotdraw.draw.figure.ConnectionFigure.setEndConnector(), org.jhotdraw.draw.figure.ConnectionFigure.setStartConnector(), org.jhotdraw.draw.handle.ConnectorHandle.setTargetFigure(), org.jhotdraw.draw.figure.ConnectionFigure.updateConnection(), org.jhotdraw.draw.handle.AbstractHandle.view, and org.jhotdraw.draw.DrawingView.viewToDrawing().
trackStart()
void org.jhotdraw.draw.handle.ConnectorHandle.trackStart (Point anchor, int modifiersEx)
Tracks the start of the interaction. The default implementation does nothing.
Parameters
anchor the position where the interaction started
Implements org.jhotdraw.draw.handle.Handle.
References org.jhotdraw.draw.Drawing.add(), org.jhotdraw.draw.handle.ConnectorHandle.createConnection(), org.jhotdraw.draw.handle.ConnectorHandle.getConnection(), org.jhotdraw.draw.DrawingView.getDrawing(), org.jhotdraw.draw.handle.ConnectorHandle.getLocationOnDrawing(), org.jhotdraw.draw.handle.ConnectorHandle.setConnection(), org.jhotdraw.draw.figure.ConnectionFigure.setEndPoint(), org.jhotdraw.draw.figure.ConnectionFigure.setStartPoint(), and org.jhotdraw.draw.handle.AbstractHandle.view.
trackStep()
void org.jhotdraw.draw.handle.ConnectorHandle.trackStep (Point anchor, Point lead, int modifiersEx)
Tracks a step of the interaction.
Parameters
anchor the position where the interaction started
lead the current position
Implements org.jhotdraw.draw.handle.Handle.
References org.jhotdraw.draw.figure.Figure.changed(), org.jhotdraw.draw.handle.ConnectorHandle.findConnectableConnector(), org.jhotdraw.draw.handle.AbstractHandle.fireAreaInvalidated(), org.jhotdraw.draw.connector.Connector.getAnchor(), org.jhotdraw.draw.handle.ConnectorHandle.getConnection(), org.jhotdraw.draw.DrawingView.getDrawing(), org.jhotdraw.draw.handle.ConnectorHandle.getDrawingArea(), org.jhotdraw.draw.handle.ConnectorHandle.repaintConnectors(), org.jhotdraw.draw.figure.ConnectionFigure.setEndPoint(), org.jhotdraw.draw.handle.AbstractHandle.view, org.jhotdraw.draw.DrawingView.viewToDrawing(), and org.jhotdraw.draw.figure.Figure.willChange().
Member Data Documentation
connectors
Collection<Connector> org.jhotdraw.draw.handle.ConnectorHandle.connectors = Collections.emptyList() protected
All connectors of the connectable Figure.
Referenced by org.jhotdraw.draw.handle.ConnectorHandle.draw(), org.jhotdraw.draw.handle.ConnectorHandle.repaintConnectors(), and org.jhotdraw.draw.handle.ConnectorHandle.trackEnd().
The documentation for this class was generated from the following file:
jhotdraw-core/src/main/java/org/jhotdraw/draw/handle/ConnectorHandle.java