jhotdraw: org.jhotdraw.draw.io.ImageInputFormat Class Reference
org.jhotdraw.draw.io.ImageInputFormat Class Reference
Public Member Functions
ImageInputFormat (ImageHolderFigure prototype)
ImageInputFormat (ImageHolderFigure prototype, String formatName, String description, String fileExtension, String mimeType)
ImageInputFormat (ImageHolderFigure prototype, String formatName, String description, String fileExtensions[], String[] mimeTypes)
javax.swing.filechooser.FileFilter getFileFilter ()
String[] getFileExtensions ()
JComponent getInputFormatAccessory ()
void read (URI uri, Drawing drawing) throws IOException
void read (URI uri, Drawing drawing, boolean replace) throws IOException
void read (File file, Drawing drawing, boolean replace) throws IOException
void read (File file, Drawing drawing) throws IOException
void read (InputStream in, Drawing drawing, boolean replace) throws IOException
ImageHolderFigure createImageHolder (InputStream in) throws IOException
boolean isDataFlavorSupported (DataFlavor flavor)
void read (Transferable t, Drawing drawing, boolean replace) throws UnsupportedFlavorException, IOException
Detailed Description
An input format for importing drawings using one of the image formats supported by javax.imageio.
This class uses the prototype design pattern. A ImageHolderFigure figure is used as a prototype for creating a figure that holds the imported image.
If the drawing is replaced using the loaded image, the size of the drawing is set to match the size of the image using the attributes
AttributeKeys.CANVAS_WIDTH
and
AttributeKeys.CANVAS_HEIGHT
.
Design Patterns
Prototype
The image input format creates new image holder figures by cloning a prototype figure object and assigning an image to it, which was read from data input. That's the reason why
Figure
extends the
Cloneable
interface.
Prototype: org.jhotdraw.draw.ImageHolderFigure; Client: ImageInputFormat.
Author
Werner Randelshor
Version
$Id$
Constructor & Destructor Documentation
ImageInputFormat() [1/3]
org.jhotdraw.draw.io.ImageInputFormat.ImageInputFormat (ImageHolderFigure prototype)
Creates a new image input format for all formats supported by
javax.imageio.ImageIO
.
ImageInputFormat() [2/3]
org.jhotdraw.draw.io.ImageInputFormat.ImageInputFormat (ImageHolderFigure prototype, String formatName, String description, String fileExtension, String mimeType)
Creates a new image input format for the specified image format.
Parameters
formatName The format name for the javax.imageio.ImageIO object.
description The format description to be used for the file filter.
fileExtension The file extension to be used for the file filter.
mimeType The mime type used for filtering data flavors from Transferable objects.
ImageInputFormat() [3/3]
org.jhotdraw.draw.io.ImageInputFormat.ImageInputFormat (ImageHolderFigure prototype, String formatName, String description, String fileExtensions[], String[] mimeTypes)
Creates a new image input format for the specified image format.
Parameters
formatName The format name for the javax.imageio.ImageIO object.
description The format description to be used for the file filter.
fileExtensions The file extensions to be used for the file filter.
mimeTypes The mime typse used for filtering data flavors from Transferable objects.
References org.jhotdraw.draw.figure.Figure.clone().
Member Function Documentation
createImageHolder()
ImageHolderFigure org.jhotdraw.draw.io.ImageInputFormat.createImageHolder (InputStream in) throws IOException
References org.jhotdraw.draw.figure.Figure.clone(), org.jhotdraw.draw.figure.ImageHolderFigure.getBufferedImage(), org.jhotdraw.draw.figure.ImageHolderFigure.loadImage(), and org.jhotdraw.draw.figure.Figure.setBounds().
Referenced by org.jhotdraw.draw.io.ImageInputFormat.read().
getFileExtensions()
String [] org.jhotdraw.draw.io.ImageInputFormat.getFileExtensions ()
getFileFilter()
javax.swing.filechooser.FileFilter org.jhotdraw.draw.io.ImageInputFormat.getFileFilter ()
Return a FileFilter that can be used to identify files which can be read with this input format. Typically, each input format has its own recognizable file naming convention.
Returns
FileFilter to be used with a javax.swing.JFileChooser
Implements org.jhotdraw.draw.io.InputFormat.
getInputFormatAccessory()
JComponent org.jhotdraw.draw.io.ImageInputFormat.getInputFormatAccessory ()
Return a JFileChooser accessory that can be used to customize the input format.
Returns
A JFileChooser accessory to be used with a javax.swing.JFileChooser Returns null, if no accessory is provided for this format.
Implements org.jhotdraw.draw.io.InputFormat.
isDataFlavorSupported()
boolean org.jhotdraw.draw.io.ImageInputFormat.isDataFlavorSupported (DataFlavor flavor)
Returns true, if this InputFormat can readFigures TransferData using the specified DataFlavor.
Parameters
flavor A DataFlavor.
Implements org.jhotdraw.draw.io.InputFormat.
read() [1/6]
void org.jhotdraw.draw.io.ImageInputFormat.read (File file, Drawing drawing) throws IOException
References org.jhotdraw.draw.io.ImageInputFormat.read().
read() [2/6]
void org.jhotdraw.draw.io.ImageInputFormat.read (File file, Drawing drawing, boolean replace) throws IOException
References org.jhotdraw.draw.figure.Figure.clone(), org.jhotdraw.draw.figure.Figure.getBounds(), org.jhotdraw.draw.figure.ImageHolderFigure.getBufferedImage(), org.jhotdraw.draw.figure.ImageHolderFigure.loadImage(), and org.jhotdraw.draw.figure.Figure.setBounds().
read() [3/6]
void org.jhotdraw.draw.io.ImageInputFormat.read (InputStream in, Drawing drawing, boolean replace) throws IOException
Reads figures from a file and adds them to the specified drawing.
Parameters
in The input stream.
drawing The drawing.
replace Set this to true, if the contents of the stream replaces the contents of the drawing (for example, when loading a drawing from a stream). Set this to false, to add the contents of the file to the drawing (for example, when the stream has been dropped into the drawing view).
Implements org.jhotdraw.draw.io.InputFormat.
References org.jhotdraw.draw.io.ImageInputFormat.createImageHolder(), and org.jhotdraw.draw.figure.Figure.getBounds().
read() [4/6]
void org.jhotdraw.draw.io.ImageInputFormat.read (Transferable t, Drawing drawing, boolean replace) throws UnsupportedFlavorException, IOException
Reads figures from the specified Transferable and adds them to the specified drawing.
Parameters
t The Transferable.
drawing The drawing.
replace Set this to true, if the contents of the transferable replaces the contents of the drawing (for example, when loading a drawing from a transferable). Set this to false, to add the contents of the transferable to the drawing (for example, when the transferable has been dropped or pasted into the drawing view).
Implements org.jhotdraw.draw.io.InputFormat.
References org.jhotdraw.draw.figure.Figure.clone(), org.jhotdraw.draw.figure.Figure.getBounds(), org.jhotdraw.draw.figure.ImageHolderFigure.getBufferedImage(), org.jhotdraw.draw.figure.Figure.setBounds(), and org.jhotdraw.draw.figure.ImageHolderFigure.setBufferedImage().
read() [5/6]
void org.jhotdraw.draw.io.ImageInputFormat.read (URI uri, Drawing drawing) throws IOException
Reads figures from an URI and replaces the children of the drawing with them.
This is a convenience method for calling read(URI,Drawing,true).
Parameters
uri The URI.
drawing The drawing.
Implements org.jhotdraw.draw.io.InputFormat.
Referenced by org.jhotdraw.draw.io.ImageInputFormat.read().
read() [6/6]
void org.jhotdraw.draw.io.ImageInputFormat.read (URI uri, Drawing drawing, boolean replace) throws IOException
Reads figures from an URI and adds them to the specified drawing.
Parameters
uri The URI.
drawing The drawing.
replace Set this to true, if the contents of the file replaces the contents of the drawing (for example, when loading a drawing from a file). Set this to false, to add the contents of the file to the drawing (for example, when the file has been dropped into the drawing view).
Implements org.jhotdraw.draw.io.InputFormat.
References org.jhotdraw.draw.io.ImageInputFormat.read().
The documentation for this class was generated from the following file:
jhotdraw-core/src/main/java/org/jhotdraw/draw/io/ImageInputFormat.java