jhotdraw: org.jhotdraw.draw.handle.RoundRectangleRadiusHandle Class Reference
org.jhotdraw.draw.handle.RoundRectangleRadiusHandle Class Reference
Public Member Functions
RoundRectangleRadiusHandle (Figure owner)
void draw (Graphics2D g)
void trackStart (Point anchor, int modifiersEx)
void trackStep (Point anchor, Point lead, int modifiersEx)
void trackEnd (Point anchor, Point lead, int modifiersEx)
void keyPressed (KeyEvent evt)
String getToolTipText (Point p)
Public Member Functions inherited from org.jhotdraw.draw.handle.AbstractHandle
AbstractHandle (Figure owner)
void addHandleListener (HandleListener l)
void removeHandleListener (HandleListener l)
Figure getOwner ()
void setView (DrawingView view)
DrawingView getView ()
DrawingEditor getEditor ()
boolean contains (Point p)
void invalidate ()
void dispose ()
void areaInvalidated (FigureEvent evt)
void figureAdded (FigureEvent e)
void figureRemoved (FigureEvent e)
void figureRequestRemove (FigureEvent e)
void figureChanged (FigureEvent evt)
Cursor getCursor ()
boolean isCombinableWith (Handle handle)
void keyTyped (KeyEvent evt)
void keyReleased (KeyEvent evt)
final Rectangle getBounds ()
Rectangle getDrawingArea ()
void trackDoubleClick (Point p, int modifiersEx)
void attributeChanged (FigureEvent e)
void viewTransformChanged ()
Collection< Handle > createSecondaryHandles ()
void setToolTipText (String newValue)
void figureHandlesChanged (FigureEvent e)
Protected Member Functions
Rectangle basicGetBounds ()
Protected Member Functions inherited from org.jhotdraw.draw.handle.AbstractHandle
int getHandlesize ()
void fireAreaInvalidated (Rectangle invalidatedArea)
void fireUndoableEditHappened (UndoableEdit edit)
void fireHandleRequestRemove (Rectangle invalidatedArea)
void fireHandleRequestSecondaryHandles ()
void drawCircle (Graphics2D g, Color fill, Color stroke)
void drawRectangle (Graphics2D g, Color fill, Color stroke)
void drawDiamond (Graphics2D g, Color fill, Color stroke)
void updateBounds ()
Additional Inherited Members
Protected Attributes inherited from org.jhotdraw.draw.handle.AbstractHandle
DrawingView view
EventListenerList listenerList = new EventListenerList()
Detailed Description
A Handle to manipulate the corner radius of a RoundRectangleFigure.
Author
Werner Randelshofer
Version
$Id$
Constructor & Destructor Documentation
RoundRectangleRadiusHandle()
org.jhotdraw.draw.handle.RoundRectangleRadiusHandle.RoundRectangleRadiusHandle (Figure owner)
Creates a new instance.
Member Function Documentation
basicGetBounds()
Rectangle org.jhotdraw.draw.handle.RoundRectangleRadiusHandle.basicGetBounds () protected
Reimplemented from org.jhotdraw.draw.handle.AbstractHandle.
References org.jhotdraw.draw.handle.AbstractHandle.getHandlesize().
draw()
void org.jhotdraw.draw.handle.RoundRectangleRadiusHandle.draw (Graphics2D g)
Draws this handle.
Reimplemented from org.jhotdraw.draw.handle.AbstractHandle.
References org.jhotdraw.draw.handle.HandleAttributeKeys.ATTRIBUTE_HANDLE_FILL_COLOR, org.jhotdraw.draw.handle.HandleAttributeKeys.ATTRIBUTE_HANDLE_FILL_COLOR_DISABLED, org.jhotdraw.draw.handle.HandleAttributeKeys.ATTRIBUTE_HANDLE_STROKE_COLOR, org.jhotdraw.draw.handle.HandleAttributeKeys.ATTRIBUTE_HANDLE_STROKE_COLOR_DISABLED, org.jhotdraw.draw.handle.AbstractHandle.drawDiamond(), and org.jhotdraw.draw.handle.AbstractHandle.getEditor().
getToolTipText()
String org.jhotdraw.draw.handle.RoundRectangleRadiusHandle.getToolTipText (Point p)
Returns a tooltip for the specified location. By default, AbstractHandle returns null.
Reimplemented from org.jhotdraw.draw.handle.AbstractHandle.
keyPressed()
void org.jhotdraw.draw.handle.RoundRectangleRadiusHandle.keyPressed (KeyEvent evt)
Reimplemented from org.jhotdraw.draw.handle.AbstractHandle.
References org.jhotdraw.draw.figure.RoundRectangleFigure.ARC_HEIGHT_PROPERTY, org.jhotdraw.draw.figure.RoundRectangleFigure.ARC_WIDTH_PROPERTY, org.jhotdraw.draw.figure.AbstractFigure.changed(), org.jhotdraw.draw.handle.AbstractHandle.fireUndoableEditHappened(), org.jhotdraw.draw.figure.RoundRectangleFigure.getArcHeight(), org.jhotdraw.draw.figure.RoundRectangleFigure.getArcWidth(), org.jhotdraw.draw.handle.AbstractHandle.getOwner(), org.jhotdraw.draw.figure.RoundRectangleFigure.setArcHeight(), org.jhotdraw.draw.figure.RoundRectangleFigure.setArcWidth(), and org.jhotdraw.draw.figure.AbstractFigure.willChange().
trackEnd()
void org.jhotdraw.draw.handle.RoundRectangleRadiusHandle.trackEnd (Point anchor, Point lead, int modifiersEx)
Tracks the end of the interaction.
Parameters
anchor the position where the interaction started
lead the current position
Implements org.jhotdraw.draw.handle.Handle.
References org.jhotdraw.draw.figure.RoundRectangleFigure.ARC_HEIGHT_PROPERTY, org.jhotdraw.draw.figure.RoundRectangleFigure.ARC_WIDTH_PROPERTY, org.jhotdraw.draw.DrawingView.drawingToView(), org.jhotdraw.draw.handle.AbstractHandle.fireUndoableEditHappened(), org.jhotdraw.draw.figure.RoundRectangleFigure.getBounds(), org.jhotdraw.draw.handle.AbstractHandle.getOwner(), org.jhotdraw.draw.handle.AbstractHandle.view, and org.jhotdraw.draw.DrawingView.viewToDrawing().
trackStart()
void org.jhotdraw.draw.handle.RoundRectangleRadiusHandle.trackStart (Point anchor, int modifiersEx)
Tracks the start of the interaction. The default implementation does nothing.
Parameters
anchor the position where the interaction started
Implements org.jhotdraw.draw.handle.Handle.
References org.jhotdraw.draw.DrawingView.drawingToView(), org.jhotdraw.draw.figure.RoundRectangleFigure.getArcHeight(), org.jhotdraw.draw.figure.RoundRectangleFigure.getArcWidth(), org.jhotdraw.draw.handle.AbstractHandle.getOwner(), and org.jhotdraw.draw.handle.AbstractHandle.view.
trackStep()
void org.jhotdraw.draw.handle.RoundRectangleRadiusHandle.trackStep (Point anchor, Point lead, int modifiersEx)
Tracks a step of the interaction.
Parameters
anchor the position where the interaction started
lead the current position
Implements org.jhotdraw.draw.handle.Handle.
References org.jhotdraw.draw.figure.AbstractFigure.changed(), org.jhotdraw.draw.DrawingView.drawingToView(), org.jhotdraw.draw.figure.RoundRectangleFigure.getBounds(), org.jhotdraw.draw.handle.AbstractHandle.getOwner(), org.jhotdraw.draw.figure.RoundRectangleFigure.setArc(), org.jhotdraw.draw.handle.AbstractHandle.view, org.jhotdraw.draw.DrawingView.viewToDrawing(), and org.jhotdraw.draw.figure.AbstractFigure.willChange().
The documentation for this class was generated from the following file:
jhotdraw-core/src/main/java/org/jhotdraw/draw/handle/RoundRectangleRadiusHandle.java