jhotdraw: org.jhotdraw.draw.connector.StickyRectangleConnector Class Reference
org.jhotdraw.draw.connector.StickyRectangleConnector Class Reference
Public Member Functions
StickyRectangleConnector ()
StickyRectangleConnector (Figure owner)
void draw (Graphics2D g)
void setAngle (float angle)
double getAngle ()
StickyRectangleConnector (Figure owner, Point2D.Double p)
void updateAnchor (Point2D.Double p)
Point2D.Double getAnchor ()
String getParameters ()
void read (DOMInput in) throws IOException
void write (DOMOutput out) throws IOException
Public Member Functions inherited from org.jhotdraw.draw.connector.ChopRectangleConnector
ChopRectangleConnector ()
ChopRectangleConnector (Figure owner)
Point2D.Double findStart (ConnectionFigure connection)
Point2D.Double findEnd (ConnectionFigure connection)
Public Member Functions inherited from org.jhotdraw.draw.connector.AbstractConnector
AbstractConnector ()
AbstractConnector (Figure owner)
void setConnectToDecorator (boolean newValue)
boolean isConnectToDecorator ()
boolean contains (Point2D.Double p)
Figure getOwner ()
Object clone ()
void updateStartLocation (Point2D.Double p)
void updateEndLocation (Point2D.Double p)
Rectangle2D.Double getBounds ()
Rectangle2D.Double getDrawingArea ()
Protected Member Functions
Point2D.Double chop (Figure target, Point2D.Double from)
Protected Member Functions inherited from org.jhotdraw.draw.connector.AbstractConnector
final Figure getConnectorTarget (Figure f)
Point2D.Double findPoint (ConnectionFigure connection)
void setOwner (Figure newValue)
Detailed Description
A StickyRectangleConnector locates connection points by choping the connection between the centers of the two figures at the display box.
The location of the connection point is computed once, when the user connects the figure. Moving the figure around will not change the location.
Author
Werner Randelshofer
Version
$Id$
Constructor & Destructor Documentation
StickyRectangleConnector() [1/3]
org.jhotdraw.draw.connector.StickyRectangleConnector.StickyRectangleConnector ()
Creates a new instance. Only used for storable.
StickyRectangleConnector() [2/3]
org.jhotdraw.draw.connector.StickyRectangleConnector.StickyRectangleConnector (Figure owner)
StickyRectangleConnector() [3/3]
org.jhotdraw.draw.connector.StickyRectangleConnector.StickyRectangleConnector (Figure owner, Point2D.Double p)
References org.jhotdraw.draw.figure.Figure.getBounds().
Member Function Documentation
chop()
Point2D.Double org.jhotdraw.draw.connector.StickyRectangleConnector.chop (Figure target, Point2D.Double from) protected
Reimplemented from org.jhotdraw.draw.connector.ChopRectangleConnector.
References org.jhotdraw.draw.figure.Figure.getBounds().
draw()
void org.jhotdraw.draw.connector.StickyRectangleConnector.draw (Graphics2D g)
Draws the connector.
Reimplemented from org.jhotdraw.draw.connector.AbstractConnector.
References org.jhotdraw.draw.connector.AbstractConnector.getBounds().
getAnchor()
Point2D.Double org.jhotdraw.draw.connector.StickyRectangleConnector.getAnchor ()
Gets the anchor of the connector. This is a point at the center or at the bounds of the figure, where the start or the end point will most likely be attached. The purpose of this method is to give the user a hint, where the connector will most likely be attached to the owner of the connector.
Reimplemented from org.jhotdraw.draw.connector.AbstractConnector.
References org.jhotdraw.draw.connector.AbstractConnector.getBounds(), and org.jhotdraw.draw.connector.AbstractConnector.getOwner().
getAngle()
double org.jhotdraw.draw.connector.StickyRectangleConnector.getAngle ()
getParameters()
String org.jhotdraw.draw.connector.StickyRectangleConnector.getParameters ()
read()
void org.jhotdraw.draw.connector.StickyRectangleConnector.read (DOMInput in) throws IOException
Reimplemented from org.jhotdraw.draw.connector.AbstractConnector.
setAngle()
void org.jhotdraw.draw.connector.StickyRectangleConnector.setAngle (float angle)
updateAnchor()
void org.jhotdraw.draw.connector.StickyRectangleConnector.updateAnchor (Point2D.Double p)
Updates the anchor of the connector. This method is called when the user manually changes the end point of the ConnectionFigure. The Connector uses this as a hint for choosing a new anchor position.
Reimplemented from org.jhotdraw.draw.connector.AbstractConnector.
References org.jhotdraw.draw.figure.Figure.getBounds(), and org.jhotdraw.draw.connector.AbstractConnector.getOwner().
write()
void org.jhotdraw.draw.connector.StickyRectangleConnector.write (DOMOutput out) throws IOException
Reimplemented from org.jhotdraw.draw.connector.AbstractConnector.
The documentation for this class was generated from the following file:
jhotdraw-core/src/main/java/org/jhotdraw/draw/connector/StickyRectangleConnector.java