jhotdraw: org.jhotdraw.draw.action.StrokeIcon Class Reference
org.jhotdraw.draw.action.StrokeIcon Class Reference
Public Member Functions
StrokeIcon (Stroke stroke)
int getIconHeight ()
int getIconWidth ()
void paintIcon (java.awt.Component c, java.awt.Graphics gr, int x, int y)
Detailed Description
StrokeIcon.
Author
Werner Randelshofer
Version
$Id$
Constructor & Destructor Documentation
StrokeIcon()
org.jhotdraw.draw.action.StrokeIcon.StrokeIcon (Stroke stroke)
Creates a new instance.
Member Function Documentation
getIconHeight()
int org.jhotdraw.draw.action.StrokeIcon.getIconHeight ()
Referenced by org.jhotdraw.draw.action.StrokeIcon.paintIcon().
getIconWidth()
int org.jhotdraw.draw.action.StrokeIcon.getIconWidth ()
Referenced by org.jhotdraw.draw.action.StrokeIcon.paintIcon().
paintIcon()
void org.jhotdraw.draw.action.StrokeIcon.paintIcon (java.awt.Component c, java.awt.Graphics gr, int x, int y)
References org.jhotdraw.draw.action.StrokeIcon.getIconHeight(), and org.jhotdraw.draw.action.StrokeIcon.getIconWidth().
The documentation for this class was generated from the following file:
jhotdraw-core/src/main/java/org/jhotdraw/draw/action/StrokeIcon.java