jhotdraw: org.jhotdraw.draw.action.SelectionColorChooserAction Class Reference
org.jhotdraw.draw.action.SelectionColorChooserAction Class Reference
Public Member Functions
SelectionColorChooserAction (DrawingEditor editor, AttributeKey< Color > key)
SelectionColorChooserAction (DrawingEditor editor, AttributeKey< Color > key, Icon icon)
SelectionColorChooserAction (DrawingEditor editor, AttributeKey< Color > key, String name)
SelectionColorChooserAction (DrawingEditor editor, final AttributeKey< Color > key, String name, Icon icon)
SelectionColorChooserAction (DrawingEditor editor, final AttributeKey< Color > key, String name, Icon icon, Map< AttributeKey<?>, Object > fixedAttributes)
Public Member Functions inherited from org.jhotdraw.draw.action.EditorColorChooserAction
EditorColorChooserAction (DrawingEditor editor, AttributeKey< Color > key)
EditorColorChooserAction (DrawingEditor editor, AttributeKey< Color > key, Icon icon)
EditorColorChooserAction (DrawingEditor editor, AttributeKey< Color > key, String name)
EditorColorChooserAction (DrawingEditor editor, final AttributeKey< Color > key, String name, Icon icon)
EditorColorChooserAction (DrawingEditor editor, final AttributeKey< Color > key, String name, Icon icon, Map< AttributeKey<?>, Object > fixedAttributes)
void actionPerformed (java.awt.event.ActionEvent e)
void selectionChanged (FigureSelectionEvent evt)
Public Member Functions inherited from org.jhotdraw.draw.action.AttributeAction
AttributeAction (DrawingEditor editor, Map< AttributeKey<?>, Object > attributes, String name, Icon icon)
void applyAttributesTo (final Map< AttributeKey<?>, Object > a, Set< Figure > figures)
Public Member Functions inherited from org.jhotdraw.draw.action.AbstractSelectedAction
AbstractSelectedAction (DrawingEditor editor)
void dispose ()
void setEditor (DrawingEditor editor)
DrawingEditor getEditor ()
void setUpdateEnabledState (boolean newValue)
boolean isUpdatEnabledState ()
Protected Member Functions
Color getInitialColor ()
Protected Member Functions inherited from org.jhotdraw.draw.action.AttributeAction
void updateEnabledState ()
Protected Member Functions inherited from org.jhotdraw.draw.action.AbstractSelectedAction
DrawingView getView ()
Drawing getDrawing ()
void fireUndoableEditHappened (UndoableEdit edit)
Additional Inherited Members
Protected Attributes inherited from org.jhotdraw.draw.action.EditorColorChooserAction
AttributeKey< Color > key
Protected Attributes inherited from org.jhotdraw.draw.action.AttributeAction
Map< AttributeKey<?>, Object > attributes
Static Protected Attributes inherited from org.jhotdraw.draw.action.EditorColorChooserAction
static JColorChooser colorChooser
Detailed Description
This is like EditorColorChooserAction, but the JColorChooser is initialized with the color of the currently selected Figures.
The behavior for choosing the initial color of the JColorChooser matches with SelectionColorIcon.
Author
Werner Randelshofer
Version
$Id$
Constructor & Destructor Documentation
SelectionColorChooserAction() [1/5]
org.jhotdraw.draw.action.SelectionColorChooserAction.SelectionColorChooserAction (DrawingEditor editor, AttributeKey< Color > key)
Creates a new instance.
References org.jhotdraw.draw.action.EditorColorChooserAction.key.
SelectionColorChooserAction() [2/5]
org.jhotdraw.draw.action.SelectionColorChooserAction.SelectionColorChooserAction (DrawingEditor editor, AttributeKey< Color > key, Icon icon)
Creates a new instance.
References org.jhotdraw.draw.action.EditorColorChooserAction.key.
SelectionColorChooserAction() [3/5]
org.jhotdraw.draw.action.SelectionColorChooserAction.SelectionColorChooserAction (DrawingEditor editor, AttributeKey< Color > key, String name)
Creates a new instance.
References org.jhotdraw.draw.action.EditorColorChooserAction.key.
SelectionColorChooserAction() [4/5]
org.jhotdraw.draw.action.SelectionColorChooserAction.SelectionColorChooserAction (DrawingEditor editor, final AttributeKey< Color > key, String name, Icon icon)
References org.jhotdraw.draw.action.EditorColorChooserAction.key.
SelectionColorChooserAction() [5/5]
org.jhotdraw.draw.action.SelectionColorChooserAction.SelectionColorChooserAction (DrawingEditor editor, final AttributeKey< Color > key, String name, Icon icon, Map< AttributeKey<?>, Object > fixedAttributes)
References org.jhotdraw.draw.action.EditorColorChooserAction.key.
Member Function Documentation
getInitialColor()
Color org.jhotdraw.draw.action.SelectionColorChooserAction.getInitialColor () protected
Reimplemented from org.jhotdraw.draw.action.EditorColorChooserAction.
References org.jhotdraw.draw.figure.Figure.get(), org.jhotdraw.draw.DrawingEditor.getActiveView(), org.jhotdraw.draw.action.AbstractSelectedAction.getEditor(), org.jhotdraw.draw.DrawingView.getSelectedFigures(), and org.jhotdraw.draw.action.EditorColorChooserAction.key.
The documentation for this class was generated from the following file:
jhotdraw-core/src/main/java/org/jhotdraw/draw/action/SelectionColorChooserAction.java