jhotdraw: org.jhotdraw.draw.action.AlignAction Class Reference
org.jhotdraw.draw.action.AlignAction Class Reference abstract
Classes
class East
class Horizontal
class North
class South
class Vertical
class West
Public Member Functions
AlignAction (DrawingEditor editor)
void updateEnabledState ()
void actionPerformed (java.awt.event.ActionEvent e)
Public Member Functions inherited from org.jhotdraw.draw.action.AbstractSelectedAction
AbstractSelectedAction (DrawingEditor editor)
void dispose ()
void setEditor (DrawingEditor editor)
DrawingEditor getEditor ()
void setUpdateEnabledState (boolean newValue)
boolean isUpdatEnabledState ()
Protected Member Functions
abstract void alignFigures (Collection< Figure > selectedFigures, Rectangle2D.Double selectionBounds)
Rectangle2D.Double getSelectionBounds ()
Protected Member Functions inherited from org.jhotdraw.draw.action.AbstractSelectedAction
DrawingView getView ()
Drawing getDrawing ()
void fireUndoableEditHappened (UndoableEdit edit)
Protected Attributes
ResourceBundleUtil labels = ResourceBundleUtil.getBundle("org.jhotdraw.draw.Labels")
Detailed Description
Aligns the selected figures.
XXX - Fire edit events
Author
Werner Randelshofer
Version
$Id$
Constructor & Destructor Documentation
AlignAction()
org.jhotdraw.draw.action.AlignAction.AlignAction (DrawingEditor editor)
Creates a new instance.
References org.jhotdraw.draw.action.AlignAction.updateEnabledState().
Member Function Documentation
actionPerformed()
void org.jhotdraw.draw.action.AlignAction.actionPerformed (java.awt.event.ActionEvent e)
References org.jhotdraw.draw.action.AlignAction.alignFigures(), org.jhotdraw.draw.action.AbstractSelectedAction.fireUndoableEditHappened(), org.jhotdraw.draw.action.AlignAction.getSelectionBounds(), org.jhotdraw.draw.action.AbstractSelectedAction.getView(), and org.jhotdraw.draw.action.AlignAction.labels.
alignFigures()
abstract void org.jhotdraw.draw.action.AlignAction.alignFigures (Collection< Figure > selectedFigures, Rectangle2D.Double selectionBounds) abstract protected
Referenced by org.jhotdraw.draw.action.AlignAction.actionPerformed().
getSelectionBounds()
Rectangle2D.Double org.jhotdraw.draw.action.AlignAction.getSelectionBounds () protected
Returns the bounds of the selected figures.
References org.jhotdraw.draw.action.AbstractSelectedAction.getView().
Referenced by org.jhotdraw.draw.action.AlignAction.actionPerformed().
updateEnabledState()
void org.jhotdraw.draw.action.AlignAction.updateEnabledState ()
Updates the enabled state of this action to reflect the enabled state of the active
DrawingView
. If no drawing view is active, this action is disabled.
Reimplemented from org.jhotdraw.draw.action.AbstractSelectedAction.
References org.jhotdraw.draw.action.AbstractSelectedAction.getView().
Referenced by org.jhotdraw.draw.action.AlignAction.AlignAction().
Member Data Documentation
labels
ResourceBundleUtil org.jhotdraw.draw.action.AlignAction.labels = ResourceBundleUtil.getBundle("org.jhotdraw.draw.Labels") protected
Referenced by org.jhotdraw.draw.action.AlignAction.actionPerformed().
The documentation for this class was generated from the following file:
jhotdraw-core/src/main/java/org/jhotdraw/draw/action/AlignAction.java