jhotdraw: org.jhotdraw.draw.figure.AbstractCompositeFigure Class Reference
org.jhotdraw.draw.figure.AbstractCompositeFigure Class Reference abstract
Classes
class EventHandler
Public Member Functions
AbstractCompositeFigure ()
Collection< Handle > createHandles (int detailLevel)
boolean add (Figure figure)
void add (int index, Figure figure)
void addAll (Collection<? extends Figure > figures)
final void addAll (int index, Collection<? extends Figure > figures)
void basicAdd (Figure figure)
void basicAddAll (int index, Collection<? extends Figure > newFigures)
void addNotify (Drawing drawing)
void removeNotify (Drawing drawing)
boolean remove (final Figure figure)
Figure removeChild (int index)
void removeAll (Collection<? extends Figure > figures)
void removeAllChildren ()
void basicRemoveAllChildren ()
void basicRemoveAll (Collection<? extends Figure > figures)
void sendToBack (Figure figure)
void bringToFront (Figure figure)
void transform (AffineTransform tx)
void setBounds (Point2D.Double anchor, Point2D.Double lead)
java.util.List< Figure > getChildrenFrontToBack ()
Map< AttributeKey<?>, Object > getAttributes ()
Object getAttributesRestoreData ()
void restoreAttributesTo (Object newData)
boolean contains (Figure f)
boolean contains (Point2D.Double p)
Figure findFigureInside (Point2D.Double p)
Figure findChild (Point2D.Double p)
int findChildIndex (Point2D.Double p)
Layouter getLayouter ()
void layout ()
void setLayouter (Layouter newLayouter)
Dimension2DDouble getPreferredSize ()
void draw (Graphics2D g)
Collection< Figure > getDecomposition ()
void read (DOMInput in) throws IOException
void write (DOMOutput out) throws IOException
void restoreTransformTo (Object geometry)
Object getTransformRestoreData ()
void basicAdd (int index, Figure figure)
Figure basicRemoveChild (int index)
java.util.List< Figure > getChildren ()
int getChildCount ()
Figure getChild (int index)
AbstractCompositeFigure clone ()
void willChange ()
void changed ()
int basicRemove (Figure child)
int indexOf (Figure child)
Rectangle2D.Double getDrawingArea ()
Rectangle2D.Double getDrawingArea (double factor)
Rectangle2D.Double getBounds ()
void removeCompositeFigureListener (CompositeFigureListener listener)
void addCompositeFigureListener (CompositeFigureListener listener)
Public Member Functions inherited from org.jhotdraw.draw.figure.AbstractFigure
AbstractFigure ()
void addFigureListener (FigureListener l)
void removeFigureListener (FigureListener l)
void fireAreaInvalidated ()
void fireFigureChanged ()
void remap (Map< Figure, Figure > oldToNew, boolean disconnectIfNotInMap)
Cursor getCursor (Point2D.Double p)
final void setBounds (Rectangle2D.Double bounds)
Connector findConnector (Point2D.Double p, ConnectionFigure prototype)
boolean includes (Figure figure)
Connector findCompatibleConnector (Connector c, boolean isStart)
Collection< Action > getActions (Point2D.Double p)
Tool getTool (Point2D.Double p)
boolean handleMouseClick (Point2D.Double p, MouseEvent evt, DrawingView view)
boolean handleDrop (Point2D.Double p, Collection< Figure > droppedFigures, DrawingView view)
Point2D.Double getEndPoint ()
Point2D.Double getStartPoint ()
boolean isConnectable ()
void setConnectable (boolean newValue)
boolean isSelectable ()
void setSelectable (boolean newValue)
boolean isRemovable ()
void setRemovable (boolean newValue)
boolean isTransformable ()
void setTransformable (boolean newValue)
boolean isVisible ()
void setVisible (boolean newValue)
void requestRemove ()
int getLayer ()
String getToolTipText (Point2D.Double p)
String toString ()
Collection< Connector > getConnectors (ConnectionFigure prototype)
Public Member Functions inherited from org.jhotdraw.draw.figure.Figure
void addPropertyChangeListener (PropertyChangeListener listener)
void removePropertyChangeListener (PropertyChangeListener listener)
Protected Member Functions
EventHandler createEventHandler ()
void validate ()
void invalidate ()
void fireFigureAdded (Figure f, int zIndex)
void fireFigureRemoved (Figure f, int zIndex)
Protected Member Functions inherited from org.jhotdraw.draw.figure.AbstractFigure
Drawing getDrawing ()
Object getLock ()
void fireAreaInvalidated (Rectangle2D.Double invalidatedArea)
void fireAreaInvalidated (FigureEvent event)
void fireFigureRequestRemove ()
void fireFigureAdded ()
void fireFigureRemoved ()
void fireFigureChanged (Rectangle2D.Double changedArea)
void fireFigureChanged (FigureEvent event)
void fireFigureHandlesChanged ()
void fireUndoableEditHappened (UndoableEdit edit)
boolean isChanging ()
int getChangingDepth ()
FontRenderContext getFontRenderContext ()
Protected Attributes
Layouter layouter
ArrayList< Figure > children = new ArrayList<>()
transient Rectangle2D.Double cachedDrawingArea
transient Rectangle2D.Double cachedBounds
EventHandler eventHandler
Protected Attributes inherited from org.jhotdraw.draw.figure.AbstractFigure
EventListenerList listenerList = new EventListenerList()
int changingDepth = 0
Additional Inherited Members
Static Public Attributes inherited from org.jhotdraw.draw.figure.Figure
static final String CONNECTABLE_PROPERTY = "connectable"
static final String REMOVABLE_PROPERTY = "removable"
static final String SELECTABLE_PROPERTY = "selectable"
static final String TRANSFORMABLE_PROPERTY = "transformable"
Static Public Attributes inherited from org.jhotdraw.draw.figure.CompositeFigure
static final AttributeKey< Insets2D.Double > LAYOUT_INSETS = new AttributeKey<Insets2D.Double>("layoutInsets", Insets2D.Double.class, new Insets2D.Double())
Detailed Description
This abstract class can be extended to implement a CompositeFigure. AbstractCompositeFigure.
Author
Werner Randelshofer
Version
$Id$
Constructor & Destructor Documentation
AbstractCompositeFigure()
org.jhotdraw.draw.figure.AbstractCompositeFigure.AbstractCompositeFigure ()
References org.jhotdraw.draw.figure.AbstractCompositeFigure.createEventHandler(), and org.jhotdraw.draw.figure.AbstractCompositeFigure.eventHandler.
Referenced by org.jhotdraw.draw.figure.AbstractCompositeFigure.clone().
Member Function Documentation
add() [1/2]
boolean org.jhotdraw.draw.figure.AbstractCompositeFigure.add (Figure child)
Adds a child to the figure.
This is a convenience method for
add(getChildCount(), child);
This method calls
figureAdded
on all registered
CompositeFigureListener
s.
Returns
true
if this CompositeFigure changed as a result of the call
Implements org.jhotdraw.draw.figure.CompositeFigure.
References org.jhotdraw.draw.figure.AbstractCompositeFigure.getChildCount().
add() [2/2]
void org.jhotdraw.draw.figure.AbstractCompositeFigure.add (int index, Figure child)
Adds a child to the figure at the specified index.
This method calls
figureAdded
on all registered
CompositeFigureListener
s.
Implements org.jhotdraw.draw.figure.CompositeFigure.
References org.jhotdraw.draw.figure.Figure.addNotify(), org.jhotdraw.draw.figure.AbstractCompositeFigure.basicAdd(), org.jhotdraw.draw.figure.AbstractFigure.fireFigureAdded(), org.jhotdraw.draw.figure.AbstractFigure.getDrawing(), and org.jhotdraw.draw.figure.AbstractCompositeFigure.invalidate().
addAll() [1/2]
void org.jhotdraw.draw.figure.AbstractCompositeFigure.addAll (Collection<? extends Figure > figures)
References org.jhotdraw.draw.figure.AbstractCompositeFigure.getChildCount().
addAll() [2/2]
final void org.jhotdraw.draw.figure.AbstractCompositeFigure.addAll (int index, Collection<? extends Figure > figures)
References org.jhotdraw.draw.figure.AbstractCompositeFigure.basicAdd(), org.jhotdraw.draw.figure.AbstractFigure.fireFigureAdded(), org.jhotdraw.draw.figure.AbstractFigure.getDrawing(), and org.jhotdraw.draw.figure.AbstractCompositeFigure.invalidate().
addCompositeFigureListener()
void org.jhotdraw.draw.figure.AbstractCompositeFigure.addCompositeFigureListener (CompositeFigureListener listener)
Adds a listener for this composite figure.
Implements org.jhotdraw.draw.figure.CompositeFigure.
References org.jhotdraw.draw.figure.AbstractFigure.listenerList.
addNotify()
void org.jhotdraw.draw.figure.AbstractCompositeFigure.addNotify (Drawing d)
Informs a figure, that it has been added to a drawing. The figure must inform all FigureListeners that it has been added.
Reimplemented from org.jhotdraw.draw.figure.AbstractFigure.
Reimplemented in org.jhotdraw.draw.GraphicalCompositeFigure.
References org.jhotdraw.draw.figure.AbstractCompositeFigure.getChildren().
basicAdd() [1/2]
void org.jhotdraw.draw.figure.AbstractCompositeFigure.basicAdd (Figure child)
Adds a child to the figure without firing events.
This method can be used to reinsert a child figure which has been temporarily removed from this CompositeFigure (for example to reorder the sequence of the children) and to efficiently build a drawing from an org.jhotdraw.draw.io.InputFormat.
This is a convenience method for calling
basicAdd(getChildCount(), child);
.
Implements org.jhotdraw.draw.figure.CompositeFigure.
References org.jhotdraw.draw.figure.AbstractCompositeFigure.getChildCount().
Referenced by org.jhotdraw.draw.figure.AbstractCompositeFigure.add(), org.jhotdraw.draw.figure.AbstractCompositeFigure.addAll(), org.jhotdraw.draw.figure.AbstractCompositeFigure.basicAddAll(), org.jhotdraw.draw.figure.AbstractCompositeFigure.bringToFront(), org.jhotdraw.draw.figure.AbstractCompositeFigure.read(), and org.jhotdraw.draw.figure.AbstractCompositeFigure.sendToBack().
basicAdd() [2/2]
void org.jhotdraw.draw.figure.AbstractCompositeFigure.basicAdd (int index, Figure child)
Adds a child to the figure at the specified index without firing events.
This method can be used to reinsert a child figure which has been temporarily removed from this CompositeFigure (for example to reorder the sequence of the children) and to efficiently build a drawing from an org.jhotdraw.draw.io.InputFormat.
Implements org.jhotdraw.draw.figure.CompositeFigure.
Reimplemented in org.jhotdraw.draw.QuadTreeDrawing, org.jhotdraw.draw.figure.QuadTreeCompositeFigure, and org.jhotdraw.draw.DefaultDrawing.
References org.jhotdraw.draw.figure.Figure.addFigureListener(), org.jhotdraw.draw.figure.AbstractCompositeFigure.children, and org.jhotdraw.draw.figure.AbstractCompositeFigure.eventHandler.
basicAddAll()
void org.jhotdraw.draw.figure.AbstractCompositeFigure.basicAddAll (int index, Collection<? extends Figure > newFigures)
References org.jhotdraw.draw.figure.AbstractCompositeFigure.basicAdd().
basicRemove()
int org.jhotdraw.draw.figure.AbstractCompositeFigure.basicRemove (Figure child)
Removes the specified child without firing events.
This method can be used to temporarily remove a child from this CompositeFigure (for example to reorder the sequence of the children).
This is a convenience method for calling
basicRemove(indexOf(child));
.
Returns the index of the removed figure. Returns -1 if the figure was not a child of this CompositeFigure.
Implements org.jhotdraw.draw.figure.CompositeFigure.
References org.jhotdraw.draw.figure.AbstractCompositeFigure.basicRemoveChild(), and org.jhotdraw.draw.figure.AbstractCompositeFigure.children.
Referenced by org.jhotdraw.draw.figure.AbstractCompositeFigure.basicRemoveAll(), org.jhotdraw.draw.figure.AbstractCompositeFigure.basicRemoveAllChildren(), org.jhotdraw.draw.figure.AbstractCompositeFigure.bringToFront(), and org.jhotdraw.draw.figure.AbstractCompositeFigure.sendToBack().
basicRemoveAll()
void org.jhotdraw.draw.figure.AbstractCompositeFigure.basicRemoveAll (Collection<? extends Figure > figures)
Removes all children.
See also
add
References org.jhotdraw.draw.figure.AbstractCompositeFigure.basicRemove().
basicRemoveAllChildren()
void org.jhotdraw.draw.figure.AbstractCompositeFigure.basicRemoveAllChildren ()
Removes all children.
See also
add
Implements org.jhotdraw.draw.figure.CompositeFigure.
References org.jhotdraw.draw.figure.AbstractCompositeFigure.basicRemove(), and org.jhotdraw.draw.figure.AbstractCompositeFigure.getChildren().
basicRemoveChild()
Figure org.jhotdraw.draw.figure.AbstractCompositeFigure.basicRemoveChild (int index)
Removes the child at the specified index without firing events.
This method can be used to temporarily remove a child from this CompositeFigure (for example to reorder the sequence of the children).
Returns the removed child figure.
Implements org.jhotdraw.draw.figure.CompositeFigure.
Reimplemented in org.jhotdraw.draw.QuadTreeDrawing, and org.jhotdraw.draw.figure.QuadTreeCompositeFigure.
References org.jhotdraw.draw.figure.AbstractCompositeFigure.children, org.jhotdraw.draw.figure.AbstractCompositeFigure.eventHandler, org.jhotdraw.draw.figure.AbstractCompositeFigure.invalidate(), and org.jhotdraw.draw.figure.Figure.removeFigureListener().
Referenced by org.jhotdraw.draw.figure.AbstractCompositeFigure.basicRemove(), org.jhotdraw.draw.figure.AbstractCompositeFigure.remove(), and org.jhotdraw.draw.figure.AbstractCompositeFigure.removeChild().
bringToFront()
void org.jhotdraw.draw.figure.AbstractCompositeFigure.bringToFront (Figure figure)
Brings a figure to the front of the drawing.
Parameters
figure that is part of the drawing
Reimplemented in org.jhotdraw.draw.QuadTreeDrawing, and org.jhotdraw.draw.figure.QuadTreeCompositeFigure.
References org.jhotdraw.draw.figure.AbstractCompositeFigure.basicAdd(), org.jhotdraw.draw.figure.AbstractCompositeFigure.basicRemove(), org.jhotdraw.draw.figure.AbstractFigure.fireAreaInvalidated(), and org.jhotdraw.draw.figure.Figure.getDrawingArea().
changed()
void org.jhotdraw.draw.figure.AbstractCompositeFigure.changed ()
Informs that a figure changed the area of its display box.
Reimplemented from org.jhotdraw.draw.figure.AbstractFigure.
References org.jhotdraw.draw.figure.AbstractCompositeFigure.children.
Referenced by org.jhotdraw.draw.figure.AbstractCompositeFigure.removeAll().
clone()
AbstractCompositeFigure org.jhotdraw.draw.figure.AbstractCompositeFigure.clone ()
Returns a clone of the figure, with clones of all aggregated figures, such as children and decorators. The cloned figure does not clone the list of FigureListeners from its original.
Reimplemented from org.jhotdraw.draw.figure.AbstractFigure.
Reimplemented in org.jhotdraw.draw.QuadTreeDrawing, org.jhotdraw.draw.GraphicalCompositeFigure, org.jhotdraw.draw.figure.AbstractAttributedCompositeFigure, and org.jhotdraw.draw.AbstractDrawing.
References org.jhotdraw.draw.figure.AbstractCompositeFigure.AbstractCompositeFigure(), org.jhotdraw.draw.figure.Figure.addFigureListener(), org.jhotdraw.draw.figure.AbstractCompositeFigure.children, org.jhotdraw.draw.figure.AbstractCompositeFigure.clone(), org.jhotdraw.draw.figure.Figure.clone(), org.jhotdraw.draw.figure.AbstractCompositeFigure.createEventHandler(), and org.jhotdraw.draw.figure.AbstractCompositeFigure.eventHandler.
Referenced by org.jhotdraw.draw.figure.AbstractCompositeFigure.clone().
contains() [1/2]
boolean org.jhotdraw.draw.figure.AbstractCompositeFigure.contains (Figure f)
Returns true if this composite figure contains the specified figure.
This is a convenience method for calling
getChildren().contains(f);
.
Implements org.jhotdraw.draw.figure.CompositeFigure.
Reimplemented in org.jhotdraw.draw.QuadTreeDrawing, and org.jhotdraw.draw.figure.QuadTreeCompositeFigure.
References org.jhotdraw.draw.figure.AbstractCompositeFigure.children.
Referenced by org.jhotdraw.draw.figure.AbstractCompositeFigure.contains(), org.jhotdraw.draw.figure.AbstractCompositeFigure.findChild(), and org.jhotdraw.draw.figure.AbstractCompositeFigure.findFigureInside().
contains() [2/2]
boolean org.jhotdraw.draw.figure.AbstractCompositeFigure.contains (Point2D.Double p)
Checks if a point is contained by the figure.
This is used for hit testing by Tool's.
Implements org.jhotdraw.draw.figure.Figure.
Reimplemented in org.jhotdraw.draw.GraphicalCompositeFigure.
References org.jhotdraw.draw.figure.AbstractCompositeFigure.contains(), org.jhotdraw.draw.figure.AbstractCompositeFigure.getChildren(), and org.jhotdraw.draw.figure.AbstractCompositeFigure.getDrawingArea().
createEventHandler()
EventHandler org.jhotdraw.draw.figure.AbstractCompositeFigure.createEventHandler () protected
Reimplemented in org.jhotdraw.draw.QuadTreeDrawing.
Referenced by org.jhotdraw.draw.figure.AbstractCompositeFigure.AbstractCompositeFigure(), and org.jhotdraw.draw.figure.AbstractCompositeFigure.clone().
createHandles()
Collection<Handle> org.jhotdraw.draw.figure.AbstractCompositeFigure.createHandles (int detailLevel)
Creates handles used to manipulate the figure.
Parameters
detailLevel The detail level of the handles. Usually this is 0 for bounding box handles and 1 for point handles. The value -1 is used by the SelectAreaTracker and the HandleTracker to highlight figures, over which the mouse pointer is hovering.
Returns
a Collection of handles
See also
Handle
Reimplemented from org.jhotdraw.draw.figure.AbstractFigure.
Reimplemented in org.jhotdraw.draw.GraphicalCompositeFigure.
References org.jhotdraw.draw.handle.TransformHandleKit.addScaleMoveTransformHandles().
draw()
void org.jhotdraw.draw.figure.AbstractCompositeFigure.draw (Graphics2D g)
Draws the figure.
Parameters
g The Graphics2D to draw to.
Implements org.jhotdraw.draw.figure.Figure.
Reimplemented in org.jhotdraw.draw.QuadTreeDrawing, org.jhotdraw.draw.GraphicalCompositeFigure, org.jhotdraw.draw.figure.QuadTreeCompositeFigure, and org.jhotdraw.draw.DefaultDrawing.
References org.jhotdraw.draw.figure.AbstractCompositeFigure.getChildren().
findChild()
Figure org.jhotdraw.draw.figure.AbstractCompositeFigure.findChild (Point2D.Double p)
References org.jhotdraw.draw.figure.AbstractCompositeFigure.contains(), org.jhotdraw.draw.figure.AbstractCompositeFigure.getBounds(), and org.jhotdraw.draw.figure.AbstractCompositeFigure.getChildrenFrontToBack().
Referenced by org.jhotdraw.draw.figure.AbstractCompositeFigure.findChildIndex().
findChildIndex()
int org.jhotdraw.draw.figure.AbstractCompositeFigure.findChildIndex (Point2D.Double p)
References org.jhotdraw.draw.figure.AbstractCompositeFigure.children, and org.jhotdraw.draw.figure.AbstractCompositeFigure.findChild().
findFigureInside()
Figure org.jhotdraw.draw.figure.AbstractCompositeFigure.findFigureInside (Point2D.Double p)
Finds the innermost figure at the specified location.
In case of a
CompositeFigure
, this method descends into its children and into its children's children until the innermost figure is found.
This functionality is implemented using the Chain of Responsibility design pattern. A figure which is not composed of other figures returns itself if the point is contained by the figure. Composed figures pass the method call down to their children.
Parameters
p A location on the drawing.
Returns
Returns the innermost figure at the location, or null if the location is not contained in a figure.
Reimplemented from org.jhotdraw.draw.figure.AbstractFigure.
Reimplemented in org.jhotdraw.draw.QuadTreeDrawing, org.jhotdraw.draw.figure.QuadTreeCompositeFigure, and org.jhotdraw.draw.DefaultDrawing.
References org.jhotdraw.draw.figure.AbstractCompositeFigure.contains(), org.jhotdraw.draw.figure.Figure.findFigureInside(), org.jhotdraw.draw.figure.AbstractCompositeFigure.getChildrenFrontToBack(), and org.jhotdraw.draw.figure.AbstractCompositeFigure.getDrawingArea().
fireFigureAdded()
void org.jhotdraw.draw.figure.AbstractCompositeFigure.fireFigureAdded (Figure f, int zIndex) protected
Notify all listenerList that have registered interest for notification on this event type.
References org.jhotdraw.draw.figure.Figure.getDrawingArea(), and org.jhotdraw.draw.figure.AbstractFigure.listenerList.
fireFigureRemoved()
void org.jhotdraw.draw.figure.AbstractCompositeFigure.fireFigureRemoved (Figure f, int zIndex) protected
Notify all listenerList that have registered interest for notification on this event type.
References org.jhotdraw.draw.figure.Figure.getDrawingArea(), and org.jhotdraw.draw.figure.AbstractFigure.listenerList.
getAttributes()
Map<AttributeKey<?>, Object> org.jhotdraw.draw.figure.AbstractCompositeFigure.getAttributes ()
Returns a view to all attributes of this figure. By convention, an unmodifiable map is returned.
Implements org.jhotdraw.draw.figure.Figure.
Reimplemented in org.jhotdraw.draw.GraphicalCompositeFigure, and org.jhotdraw.draw.figure.AbstractAttributedCompositeFigure.
getAttributesRestoreData()
Object org.jhotdraw.draw.figure.AbstractCompositeFigure.getAttributesRestoreData ()
Gets data which can be used to restore the attributes of the figure after a set has been applied to it.
Implements org.jhotdraw.draw.figure.Figure.
Reimplemented in org.jhotdraw.draw.figure.AbstractAttributedCompositeFigure.
References org.jhotdraw.draw.figure.AbstractCompositeFigure.getChildren().
getBounds()
Rectangle2D.Double org.jhotdraw.draw.figure.AbstractCompositeFigure.getBounds ()
Returns the untransformed logical bounds of the figure as a Rectangle.
The bounds are used by Handle objects for adjusting the figure and for aligning the figure on a grid.
Implements org.jhotdraw.draw.figure.Figure.
Reimplemented in org.jhotdraw.draw.GraphicalCompositeFigure.
References org.jhotdraw.draw.figure.AbstractCompositeFigure.cachedBounds, org.jhotdraw.draw.figure.AbstractCompositeFigure.children, and org.jhotdraw.draw.figure.AbstractCompositeFigure.getChildCount().
Referenced by org.jhotdraw.draw.figure.GroupFigure.chop(), org.jhotdraw.draw.figure.AbstractCompositeFigure.findChild(), org.jhotdraw.draw.figure.AbstractAttributedCompositeFigure.getFigureDrawBounds(), org.jhotdraw.draw.figure.AbstractCompositeFigure.layout(), and org.jhotdraw.draw.figure.AbstractCompositeFigure.setBounds().
getChild()
Figure org.jhotdraw.draw.figure.AbstractCompositeFigure.getChild (int index)
Returns the child figure at the specified index.
This is a convenience method for calling
getChildren().get(index);
.
Implements org.jhotdraw.draw.figure.CompositeFigure.
References org.jhotdraw.draw.figure.AbstractCompositeFigure.children.
Referenced by org.jhotdraw.draw.QuadTreeDrawing.basicRemoveChild().
getChildCount()
int org.jhotdraw.draw.figure.AbstractCompositeFigure.getChildCount ()
Returns the number of children.
This is a convenience method for calling
getChildren().size();
.
Implements org.jhotdraw.draw.figure.CompositeFigure.
References org.jhotdraw.draw.figure.AbstractCompositeFigure.children.
Referenced by org.jhotdraw.draw.figure.AbstractCompositeFigure.add(), org.jhotdraw.draw.figure.AbstractCompositeFigure.addAll(), org.jhotdraw.draw.figure.AbstractCompositeFigure.basicAdd(), org.jhotdraw.draw.figure.AbstractCompositeFigure.getBounds(), and org.jhotdraw.draw.figure.AbstractCompositeFigure.getDrawingArea().
getChildren()
java.util.List<Figure> org.jhotdraw.draw.figure.AbstractCompositeFigure.getChildren ()
Returns an unchangeable list view on the children.
Implements org.jhotdraw.draw.figure.CompositeFigure.
Reimplemented in org.jhotdraw.draw.QuadTreeDrawing, and org.jhotdraw.draw.figure.QuadTreeCompositeFigure.
References org.jhotdraw.draw.figure.AbstractCompositeFigure.children.
Referenced by org.jhotdraw.draw.figure.AbstractCompositeFigure.addNotify(), org.jhotdraw.draw.figure.AbstractCompositeFigure.basicRemoveAllChildren(), org.jhotdraw.draw.figure.AbstractCompositeFigure.contains(), org.jhotdraw.draw.DefaultDrawing.draw(), org.jhotdraw.draw.figure.AbstractCompositeFigure.draw(), org.jhotdraw.draw.figure.AbstractAttributedCompositeFigure.drawChildren(), org.jhotdraw.draw.DefaultDrawing.findFigures(), org.jhotdraw.draw.DefaultDrawing.findFiguresWithin(), org.jhotdraw.draw.figure.AbstractAttributedCompositeFigure.getAttributesRestoreData(), org.jhotdraw.draw.figure.AbstractCompositeFigure.getAttributesRestoreData(), org.jhotdraw.draw.figure.AbstractCompositeFigure.getChildrenFrontToBack(), org.jhotdraw.draw.figure.AbstractCompositeFigure.getDecomposition(), org.jhotdraw.draw.DefaultDrawing.getFiguresFrontToBack(), org.jhotdraw.draw.figure.AbstractCompositeFigure.getTransformRestoreData(), org.jhotdraw.draw.figure.AbstractCompositeFigure.layout(), org.jhotdraw.draw.figure.AbstractCompositeFigure.removeAllChildren(), org.jhotdraw.draw.figure.AbstractCompositeFigure.removeNotify(), org.jhotdraw.draw.figure.AbstractCompositeFigure.restoreAttributesTo(), org.jhotdraw.draw.figure.AbstractAttributedCompositeFigure.restoreAttributesTo(), org.jhotdraw.draw.figure.AbstractCompositeFigure.restoreTransformTo(), org.jhotdraw.draw.DefaultDrawing.sort(), org.jhotdraw.draw.figure.AbstractCompositeFigure.transform(), org.jhotdraw.draw.AbstractDrawing.write(), and org.jhotdraw.draw.figure.AbstractCompositeFigure.write().
getChildrenFrontToBack()
java.util.List<Figure> org.jhotdraw.draw.figure.AbstractCompositeFigure.getChildrenFrontToBack ()
Returns an iterator to iterate in Z-order front to back over the children.
References org.jhotdraw.draw.figure.AbstractCompositeFigure.children, and org.jhotdraw.draw.figure.AbstractCompositeFigure.getChildren().
Referenced by org.jhotdraw.draw.figure.AbstractCompositeFigure.findChild(), and org.jhotdraw.draw.figure.AbstractCompositeFigure.findFigureInside().
getDecomposition()
Collection<Figure> org.jhotdraw.draw.figure.AbstractCompositeFigure.getDecomposition ()
Returns a decompositon of a figure into its parts. A figure is considered as a part of itself.
Reimplemented from org.jhotdraw.draw.figure.AbstractFigure.
References org.jhotdraw.draw.figure.AbstractCompositeFigure.getChildren().
getDrawingArea() [1/2]
Rectangle2D.Double org.jhotdraw.draw.figure.AbstractCompositeFigure.getDrawingArea ()
Returns the drawing area of the figure as a Rectangle.
The drawing area is used to inform DrawingView about the area that is needed to draw this figure.
The drawing area needs to be large enough, to take line width, line caps and other decorations into account that exceed the bounds of the Figure.
Implements org.jhotdraw.draw.figure.Figure.
Reimplemented in org.jhotdraw.draw.GraphicalCompositeFigure.
Referenced by org.jhotdraw.draw.figure.AbstractCompositeFigure.contains(), org.jhotdraw.draw.figure.AbstractCompositeFigure.EventHandler.figureChanged(), and org.jhotdraw.draw.figure.AbstractCompositeFigure.findFigureInside().
getDrawingArea() [2/2]
Rectangle2D.Double org.jhotdraw.draw.figure.AbstractCompositeFigure.getDrawingArea (double factor)
Returns the drawing area of the figure as a Rectangle.
The drawing area is used to inform DrawingView about the area that is needed to draw this figure.
The drawing area needs to be large enough, to take line width, line caps and other decorations into account that exceed the bounds of the Figure.
Implements org.jhotdraw.draw.figure.Figure.
References org.jhotdraw.draw.figure.AbstractCompositeFigure.cachedDrawingArea, org.jhotdraw.draw.figure.AbstractCompositeFigure.children, and org.jhotdraw.draw.figure.AbstractCompositeFigure.getChildCount().
getLayouter()
Layouter org.jhotdraw.draw.figure.AbstractCompositeFigure.getLayouter ()
Get a Layouter object which encapsulated a layout algorithm for this figure. Typically, a Layouter accesses the child components of this figure and arranges their graphical presentation.
Returns
layout strategy used by this figure
Implements org.jhotdraw.draw.figure.CompositeFigure.
References org.jhotdraw.draw.figure.AbstractCompositeFigure.layouter.
Referenced by org.jhotdraw.draw.figure.AbstractCompositeFigure.layout(), and org.jhotdraw.draw.GraphicalCompositeFigure.setBounds().
getPreferredSize()
Dimension2DDouble org.jhotdraw.draw.figure.AbstractCompositeFigure.getPreferredSize ()
The preferred size is used by Layouter to determine the preferred size of a Figure. For most Figure's this is the same as the dimensions returned by getBounds.
Reimplemented from org.jhotdraw.draw.figure.AbstractFigure.
References org.jhotdraw.draw.layouter.Layouter.calculateLayout(), org.jhotdraw.draw.figure.AbstractFigure.getEndPoint(), org.jhotdraw.draw.figure.AbstractFigure.getStartPoint(), and org.jhotdraw.draw.figure.AbstractCompositeFigure.layouter.
getTransformRestoreData()
Object org.jhotdraw.draw.figure.AbstractCompositeFigure.getTransformRestoreData ()
Gets data which can be used to restore the transformation of the figure without loss of precision, after a transform has been applied to it.
See also
transform(AffineTransform)
Implements org.jhotdraw.draw.figure.Figure.
References org.jhotdraw.draw.figure.AbstractCompositeFigure.getChildren().
indexOf()
int org.jhotdraw.draw.figure.AbstractCompositeFigure.indexOf (Figure child)
Returns the index of the specified child.
This is a convenience method for calling
getChildren().indexOf(index);
.
Returns
The index of the child, or -1 if the specified figure is not a child of this CompositeFigure.
Implements org.jhotdraw.draw.figure.CompositeFigure.
Reimplemented in org.jhotdraw.draw.QuadTreeDrawing, org.jhotdraw.draw.figure.QuadTreeCompositeFigure, and org.jhotdraw.draw.DefaultDrawing.
References org.jhotdraw.draw.figure.AbstractCompositeFigure.children.
invalidate()
void org.jhotdraw.draw.figure.AbstractCompositeFigure.invalidate () protected
Invalidates cached data of the Figure. This method must execute fast, because it can be called very often.
Reimplemented from org.jhotdraw.draw.figure.AbstractFigure.
References org.jhotdraw.draw.figure.AbstractCompositeFigure.cachedBounds, and org.jhotdraw.draw.figure.AbstractCompositeFigure.cachedDrawingArea.
Referenced by org.jhotdraw.draw.figure.AbstractCompositeFigure.add(), org.jhotdraw.draw.figure.AbstractCompositeFigure.addAll(), org.jhotdraw.draw.figure.AbstractCompositeFigure.EventHandler.attributeChanged(), org.jhotdraw.draw.figure.AbstractCompositeFigure.basicRemoveChild(), org.jhotdraw.draw.figure.AbstractCompositeFigure.EventHandler.figureAdded(), org.jhotdraw.draw.figure.AbstractCompositeFigure.EventHandler.figureChanged(), org.jhotdraw.draw.QuadTreeDrawing.QuadTreeEventHandler.figureChanged(), org.jhotdraw.draw.figure.AbstractCompositeFigure.EventHandler.figureRemoved(), org.jhotdraw.draw.figure.AbstractCompositeFigure.layout(), org.jhotdraw.draw.figure.AbstractCompositeFigure.restoreTransformTo(), org.jhotdraw.draw.GraphicalCompositeFigure.setBounds(), and org.jhotdraw.draw.figure.AbstractCompositeFigure.transform().
layout()
void org.jhotdraw.draw.figure.AbstractCompositeFigure.layout ()
A layout algorithm is used to define how the child components should be laid out in relation to each other. The task for layouting the child components for presentation is delegated to a Layouter which can be plugged in at runtime.
Implements org.jhotdraw.draw.figure.CompositeFigure.
References org.jhotdraw.draw.figure.AbstractFigure.changingDepth, org.jhotdraw.draw.figure.AbstractCompositeFigure.getBounds(), org.jhotdraw.draw.figure.AbstractCompositeFigure.getChildren(), org.jhotdraw.draw.figure.AbstractCompositeFigure.getLayouter(), org.jhotdraw.draw.figure.AbstractCompositeFigure.invalidate(), org.jhotdraw.draw.figure.CompositeFigure.layout(), org.jhotdraw.draw.layouter.Layouter.layout(), and org.jhotdraw.draw.figure.AbstractCompositeFigure.setBounds().
Referenced by org.jhotdraw.draw.figure.AbstractCompositeFigure.validate().
read()
void org.jhotdraw.draw.figure.AbstractCompositeFigure.read (DOMInput in) throws IOException
Reimplemented in org.jhotdraw.draw.GraphicalCompositeFigure, org.jhotdraw.draw.figure.AbstractAttributedCompositeFigure, and org.jhotdraw.draw.AbstractDrawing.
References org.jhotdraw.draw.figure.AbstractCompositeFigure.basicAdd().
remove()
boolean org.jhotdraw.draw.figure.AbstractCompositeFigure.remove (final Figure child)
Removes the specified child. Returns true, if the Figure contained the removed child.
This is a convenience method for calling
removeChild(getChildren().indexOf(child));
This method calls
figureRemoved
on all registered
CompositeFigureListener
's.
Implements org.jhotdraw.draw.figure.CompositeFigure.
References org.jhotdraw.draw.figure.AbstractCompositeFigure.basicRemoveChild(), org.jhotdraw.draw.figure.AbstractCompositeFigure.children, org.jhotdraw.draw.figure.AbstractFigure.fireFigureRemoved(), and org.jhotdraw.draw.figure.AbstractFigure.getDrawing().
removeAll()
void org.jhotdraw.draw.figure.AbstractCompositeFigure.removeAll (Collection<? extends Figure > figures)
Removes all specified children.
See also
add
References org.jhotdraw.draw.figure.AbstractCompositeFigure.changed(), and org.jhotdraw.draw.figure.AbstractCompositeFigure.willChange().
Referenced by org.jhotdraw.draw.figure.AbstractCompositeFigure.removeAllChildren().
removeAllChildren()
void org.jhotdraw.draw.figure.AbstractCompositeFigure.removeAllChildren ()
Removes all children.
See also
add
Implements org.jhotdraw.draw.figure.CompositeFigure.
References org.jhotdraw.draw.figure.AbstractCompositeFigure.getChildren(), and org.jhotdraw.draw.figure.AbstractCompositeFigure.removeAll().
removeChild()
Figure org.jhotdraw.draw.figure.AbstractCompositeFigure.removeChild (int index)
Removes the child at the specified index. Returns the removed child figure.
Calls
figureRemoved
on all registered
CompositeFigureListener
's.
Implements org.jhotdraw.draw.figure.CompositeFigure.
References org.jhotdraw.draw.figure.AbstractCompositeFigure.basicRemoveChild(), org.jhotdraw.draw.figure.AbstractFigure.getDrawing(), and org.jhotdraw.draw.figure.Figure.removeNotify().
removeCompositeFigureListener()
void org.jhotdraw.draw.figure.AbstractCompositeFigure.removeCompositeFigureListener (CompositeFigureListener listener)
Removes a listener from this composite figure.
Implements org.jhotdraw.draw.figure.CompositeFigure.
References org.jhotdraw.draw.figure.AbstractFigure.listenerList.
removeNotify()
void org.jhotdraw.draw.figure.AbstractCompositeFigure.removeNotify (Drawing d)
Informs a figure, that it has been removed from a drawing. The figure must inform all FigureListeners that it has been removed.
Reimplemented from org.jhotdraw.draw.figure.AbstractFigure.
Reimplemented in org.jhotdraw.draw.GraphicalCompositeFigure.
References org.jhotdraw.draw.figure.AbstractCompositeFigure.getChildren().
restoreAttributesTo()
void org.jhotdraw.draw.figure.AbstractCompositeFigure.restoreAttributesTo (Object restoreData)
Restores the attributes of the figure to a previously stored state.
Implements org.jhotdraw.draw.figure.Figure.
Reimplemented in org.jhotdraw.draw.figure.AbstractAttributedCompositeFigure.
References org.jhotdraw.draw.figure.AbstractCompositeFigure.getChildren().
restoreTransformTo()
void org.jhotdraw.draw.figure.AbstractCompositeFigure.restoreTransformTo (Object restoreData)
Restores the transform of the figure to a previously stored state.
Implements org.jhotdraw.draw.figure.Figure.
References org.jhotdraw.draw.figure.AbstractCompositeFigure.getChildren(), and org.jhotdraw.draw.figure.AbstractCompositeFigure.invalidate().
sendToBack()
void org.jhotdraw.draw.figure.AbstractCompositeFigure.sendToBack (Figure figure)
Sends a figure to the back of the composite figure.
Parameters
figure that is part of this composite figure
Reimplemented in org.jhotdraw.draw.QuadTreeDrawing, and org.jhotdraw.draw.figure.QuadTreeCompositeFigure.
References org.jhotdraw.draw.figure.AbstractCompositeFigure.basicAdd(), org.jhotdraw.draw.figure.AbstractCompositeFigure.basicRemove(), org.jhotdraw.draw.figure.AbstractFigure.fireAreaInvalidated(), and org.jhotdraw.draw.figure.Figure.getDrawingArea().
setBounds()
void org.jhotdraw.draw.figure.AbstractCompositeFigure.setBounds (Point2D.Double start, Point2D.Double end)
Sets the logical and untransformed bounds of the figure.
This is used by Tool's which create a new Figure and by Tool's which connect a Figure to another Figure.
This is a basic operation which does not fire events. Use the following code sequence, if you need event firing:
figure.willChange();
figure.setBounds(...);
figure.changed();
Parameters
start the start point of the bounds
end the end point of the bounds
See also
getBounds
Reimplemented from org.jhotdraw.draw.figure.AbstractFigure.
Reimplemented in org.jhotdraw.draw.GraphicalCompositeFigure.
References org.jhotdraw.draw.figure.AbstractCompositeFigure.getBounds(), and org.jhotdraw.draw.figure.AbstractCompositeFigure.transform().
Referenced by org.jhotdraw.draw.figure.AbstractCompositeFigure.layout().
setLayouter()
void org.jhotdraw.draw.figure.AbstractCompositeFigure.setLayouter (Layouter newLayouter)
Set a Layouter object which encapsulated a layout algorithm for this figure. Typically, a Layouter accesses the child components of this figure and arranges their graphical presentation. It is a good idea to set the Layouter in the protected initialize() method so it can be recreated if a GraphicalCompositeFigure is read and restored from a StorableInput stream.
Parameters
newLayouter encapsulation of a layout algorithm.
Implements org.jhotdraw.draw.figure.CompositeFigure.
Referenced by org.jhotdraw.draw.figure.ListFigure.ListFigure().
transform()
void org.jhotdraw.draw.figure.AbstractCompositeFigure.transform (AffineTransform tx)
Transforms the figure.
Implements org.jhotdraw.draw.figure.Figure.
Reimplemented in org.jhotdraw.draw.GraphicalCompositeFigure.
References org.jhotdraw.draw.figure.AbstractCompositeFigure.getChildren(), and org.jhotdraw.draw.figure.AbstractCompositeFigure.invalidate().
Referenced by org.jhotdraw.draw.figure.AbstractCompositeFigure.setBounds().
validate()
void org.jhotdraw.draw.figure.AbstractCompositeFigure.validate () protected
Reimplemented from org.jhotdraw.draw.figure.AbstractFigure.
References org.jhotdraw.draw.figure.AbstractCompositeFigure.layout().
Referenced by org.jhotdraw.draw.figure.AbstractCompositeFigure.EventHandler.figureChanged().
willChange()
void org.jhotdraw.draw.figure.AbstractCompositeFigure.willChange ()
Informs that a figure is about to change something that affects the contents of its display box.
Reimplemented from org.jhotdraw.draw.figure.AbstractFigure.
References org.jhotdraw.draw.figure.AbstractCompositeFigure.children.
Referenced by org.jhotdraw.draw.figure.AbstractCompositeFigure.removeAll().
write()
void org.jhotdraw.draw.figure.AbstractCompositeFigure.write (DOMOutput out) throws IOException
Reimplemented in org.jhotdraw.draw.GraphicalCompositeFigure, org.jhotdraw.draw.figure.AbstractAttributedCompositeFigure, and org.jhotdraw.draw.AbstractDrawing.
References org.jhotdraw.draw.figure.AbstractCompositeFigure.getChildren().
Member Data Documentation
cachedBounds
transient Rectangle2D.Double org.jhotdraw.draw.figure.AbstractCompositeFigure.cachedBounds protected
Caches the bounds to improve the performance of method getBounds.
Referenced by org.jhotdraw.draw.figure.AbstractCompositeFigure.getBounds(), and org.jhotdraw.draw.figure.AbstractCompositeFigure.invalidate().
cachedDrawingArea
transient Rectangle2D.Double org.jhotdraw.draw.figure.AbstractCompositeFigure.cachedDrawingArea protected
Caches the drawing area to improve the performance of method getDrawingArea.
Referenced by org.jhotdraw.draw.figure.AbstractCompositeFigure.getDrawingArea(), and org.jhotdraw.draw.figure.AbstractCompositeFigure.invalidate().
children
ArrayList<Figure> org.jhotdraw.draw.figure.AbstractCompositeFigure.children = new ArrayList<>() protected
The children that this figure is composed of
See also
add
removeChild
Referenced by org.jhotdraw.draw.figure.AbstractCompositeFigure.basicAdd(), org.jhotdraw.draw.figure.QuadTreeCompositeFigure.basicAdd(), org.jhotdraw.draw.figure.AbstractCompositeFigure.basicRemove(), org.jhotdraw.draw.figure.AbstractCompositeFigure.basicRemoveChild(), org.jhotdraw.draw.figure.QuadTreeCompositeFigure.basicRemoveChild(), org.jhotdraw.draw.figure.QuadTreeCompositeFigure.bringToFront(), org.jhotdraw.draw.QuadTreeDrawing.bringToFront(), org.jhotdraw.draw.figure.AbstractCompositeFigure.changed(), org.jhotdraw.draw.figure.AbstractCompositeFigure.clone(), org.jhotdraw.draw.figure.AbstractCompositeFigure.contains(), org.jhotdraw.draw.figure.QuadTreeCompositeFigure.contains(), org.jhotdraw.draw.QuadTreeDrawing.contains(), org.jhotdraw.draw.figure.QuadTreeCompositeFigure.draw(), org.jhotdraw.draw.QuadTreeDrawing.draw(), org.jhotdraw.draw.DefaultDrawing.draw(), org.jhotdraw.draw.figure.AbstractCompositeFigure.findChildIndex(), org.jhotdraw.draw.DefaultDrawing.findFigureBehind(), org.jhotdraw.draw.QuadTreeDrawing.findFigureBehind(), org.jhotdraw.draw.figure.QuadTreeCompositeFigure.findFiguresWithin(), org.jhotdraw.draw.QuadTreeDrawing.findFiguresWithin(), org.jhotdraw.draw.figure.AbstractCompositeFigure.getBounds(), org.jhotdraw.draw.figure.AbstractCompositeFigure.getChild(), org.jhotdraw.draw.figure.AbstractCompositeFigure.getChildCount(), org.jhotdraw.draw.figure.AbstractCompositeFigure.getChildren(), org.jhotdraw.draw.figure.QuadTreeCompositeFigure.getChildren(), org.jhotdraw.draw.QuadTreeDrawing.getChildren(), org.jhotdraw.draw.figure.AbstractCompositeFigure.getChildrenFrontToBack(), org.jhotdraw.draw.figure.AbstractCompositeFigure.getDrawingArea(), org.jhotdraw.draw.figure.QuadTreeCompositeFigure.getFiguresFrontToBack(), org.jhotdraw.draw.QuadTreeDrawing.getFiguresFrontToBack(), org.jhotdraw.draw.figure.AbstractCompositeFigure.indexOf(), org.jhotdraw.draw.DefaultDrawing.indexOf(), org.jhotdraw.draw.figure.QuadTreeCompositeFigure.indexOf(), org.jhotdraw.draw.QuadTreeDrawing.indexOf(), org.jhotdraw.draw.figure.GroupFigure.isTransformable(), org.jhotdraw.draw.figure.AbstractCompositeFigure.remove(), org.jhotdraw.draw.figure.QuadTreeCompositeFigure.sendToBack(), org.jhotdraw.draw.QuadTreeDrawing.sendToBack(), org.jhotdraw.draw.figure.QuadTreeCompositeFigure.sort(), org.jhotdraw.draw.QuadTreeDrawing.sort(), and org.jhotdraw.draw.figure.AbstractCompositeFigure.willChange().
eventHandler
EventHandler org.jhotdraw.draw.figure.AbstractCompositeFigure.eventHandler protected
Handles figure changes in the children.
Referenced by org.jhotdraw.draw.figure.AbstractCompositeFigure.AbstractCompositeFigure(), org.jhotdraw.draw.figure.AbstractCompositeFigure.basicAdd(), org.jhotdraw.draw.figure.AbstractCompositeFigure.basicRemoveChild(), and org.jhotdraw.draw.figure.AbstractCompositeFigure.clone().
layouter
Layouter org.jhotdraw.draw.figure.AbstractCompositeFigure.layouter protected
A Layouter determines how the children of the CompositeFigure are laid out graphically.
Referenced by org.jhotdraw.draw.figure.AbstractCompositeFigure.getLayouter(), and org.jhotdraw.draw.figure.AbstractCompositeFigure.getPreferredSize().
The documentation for this class was generated from the following file:
jhotdraw-core/src/main/java/org/jhotdraw/draw/figure/AbstractCompositeFigure.java