jhotdraw: org.jhotdraw.draw.action.ZoomAction Class Reference
org.jhotdraw.draw.action.ZoomAction Class Reference
Public Member Functions
ZoomAction (DrawingEditor editor, double scaleFactor, AbstractButton button)
ZoomAction (DrawingView view, double scaleFactor, AbstractButton button)
void actionPerformed (java.awt.event.ActionEvent e)
Public Member Functions inherited from org.jhotdraw.draw.action.AbstractDrawingViewAction
AbstractDrawingViewAction (DrawingEditor editor)
AbstractDrawingViewAction (DrawingView view)
void dispose ()
void setUpdateEnabledState (boolean newValue)
boolean isUpdatEnabledState ()
Additional Inherited Members
Protected Member Functions inherited from org.jhotdraw.draw.action.AbstractDrawingViewAction
void setEditor (DrawingEditor newValue)
DrawingEditor getEditor ()
DrawingView getView ()
Drawing getDrawing ()
void fireUndoableEditHappened (UndoableEdit edit)
void updateEnabledState ()
void updateViewState ()
Detailed Description
ZoomAction.
Author
Werner Randelshofer
Version
$Id$
Constructor & Destructor Documentation
ZoomAction() [1/2]
org.jhotdraw.draw.action.ZoomAction.ZoomAction (DrawingEditor editor, double scaleFactor, AbstractButton button)
Creates a new instance.
References org.jhotdraw.draw.action.AbstractDrawingViewAction.setEditor().
ZoomAction() [2/2]
org.jhotdraw.draw.action.ZoomAction.ZoomAction (DrawingView view, double scaleFactor, AbstractButton button)
Creates a new instance.
Member Function Documentation
actionPerformed()
void org.jhotdraw.draw.action.ZoomAction.actionPerformed (java.awt.event.ActionEvent e)
References org.jhotdraw.draw.DrawingView.getComponent(), org.jhotdraw.draw.DrawingView.getScaleFactor(), org.jhotdraw.draw.action.AbstractDrawingViewAction.getView(), and org.jhotdraw.draw.DrawingView.setScaleFactor().
The documentation for this class was generated from the following file:
jhotdraw-core/src/main/java/org/jhotdraw/draw/action/ZoomAction.java