jhotdraw: org.jhotdraw.draw.DefaultDrawing Class Reference
org.jhotdraw.draw.DefaultDrawing Class Reference
Public Member Functions
DefaultDrawing ()
void basicAdd (int index, Figure figure)
void draw (Graphics2D g)
void draw (Graphics2D g, Collection< Figure > children)
List< Figure > sort (Collection<? extends Figure > c)
Figure findFigure (Point2D.Double p)
Figure findFigureExcept (Point2D.Double p, Figure ignore)
Figure findFigureBehind (Point2D.Double p, Figure figure)
Figure findFigureBehind (Point2D.Double p, Collection<? extends Figure > children)
Figure findFigureExcept (Point2D.Double p, Collection<? extends Figure > ignore)
List< Figure > findFigures (Rectangle2D.Double bounds)
List< Figure > findFiguresWithin (Rectangle2D.Double bounds)
Figure findFigureInside (Point2D.Double p)
List< Figure > getFiguresFrontToBack ()
int indexOf (Figure figure)
void drawCanvas (Graphics2D g)
Public Member Functions inherited from org.jhotdraw.draw.AbstractDrawing
AbstractDrawing ()
void addUndoableEditListener (UndoableEditListener l)
void removeUndoableEditListener (UndoableEditListener l)
void fireUndoableEditHappened (UndoableEdit edit)
FontRenderContext getFontRenderContext ()
void setFontRenderContext (FontRenderContext frc)
void read (DOMInput in) throws IOException
void write (DOMOutput out) throws IOException
Object getLock ()
void addInputFormat (InputFormat format)
void addOutputFormat (OutputFormat format)
void setOutputFormats (java.util.List< OutputFormat > formats)
void setInputFormats (java.util.List< InputFormat > formats)
java.util.List< InputFormat > getInputFormats ()
java.util.List< OutputFormat > getOutputFormats ()
Drawing getDrawing ()
AbstractDrawing clone ()
Public Member Functions inherited from org.jhotdraw.draw.figure.AbstractAttributedCompositeFigure
AbstractAttributedCompositeFigure ()
void setAttributeEnabled (AttributeKey<?> key, boolean b)
void setAttributes (Map< AttributeKey<?>, Object > map)
Map< AttributeKey<?>, Object > getAttributes ()
Object getAttributesRestoreData ()
void restoreAttributesTo (Object restoreData)
void drawFigure (Graphics2D g)
Stroke getStroke ()
double getStrokeMiterLimitFactor ()
Rectangle2D.Double getFigureDrawBounds ()
Public Member Functions inherited from org.jhotdraw.draw.figure.AbstractCompositeFigure
AbstractCompositeFigure ()
Collection< Handle > createHandles (int detailLevel)
boolean add (Figure figure)
void add (int index, Figure figure)
void addAll (Collection<? extends Figure > figures)
final void addAll (int index, Collection<? extends Figure > figures)
void basicAdd (Figure figure)
void basicAddAll (int index, Collection<? extends Figure > newFigures)
void addNotify (Drawing drawing)
void removeNotify (Drawing drawing)
boolean remove (final Figure figure)
Figure removeChild (int index)
void removeAll (Collection<? extends Figure > figures)
void removeAllChildren ()
void basicRemoveAllChildren ()
void basicRemoveAll (Collection<? extends Figure > figures)
void sendToBack (Figure figure)
void bringToFront (Figure figure)
void transform (AffineTransform tx)
void setBounds (Point2D.Double anchor, Point2D.Double lead)
java.util.List< Figure > getChildrenFrontToBack ()
boolean contains (Figure f)
boolean contains (Point2D.Double p)
Figure findChild (Point2D.Double p)
int findChildIndex (Point2D.Double p)
Layouter getLayouter ()
void layout ()
void setLayouter (Layouter newLayouter)
Dimension2DDouble getPreferredSize ()
Collection< Figure > getDecomposition ()
void restoreTransformTo (Object geometry)
Object getTransformRestoreData ()
Figure basicRemoveChild (int index)
java.util.List< Figure > getChildren ()
int getChildCount ()
Figure getChild (int index)
void willChange ()
void changed ()
int basicRemove (Figure child)
Rectangle2D.Double getDrawingArea ()
Rectangle2D.Double getDrawingArea (double factor)
Rectangle2D.Double getBounds ()
void removeCompositeFigureListener (CompositeFigureListener listener)
void addCompositeFigureListener (CompositeFigureListener listener)
Public Member Functions inherited from org.jhotdraw.draw.figure.AbstractFigure
AbstractFigure ()
void addFigureListener (FigureListener l)
void removeFigureListener (FigureListener l)
void fireAreaInvalidated ()
void fireFigureChanged ()
void remap (Map< Figure, Figure > oldToNew, boolean disconnectIfNotInMap)
Cursor getCursor (Point2D.Double p)
final void setBounds (Rectangle2D.Double bounds)
Connector findConnector (Point2D.Double p, ConnectionFigure prototype)
boolean includes (Figure figure)
Connector findCompatibleConnector (Connector c, boolean isStart)
Collection< Action > getActions (Point2D.Double p)
Tool getTool (Point2D.Double p)
boolean handleMouseClick (Point2D.Double p, MouseEvent evt, DrawingView view)
boolean handleDrop (Point2D.Double p, Collection< Figure > droppedFigures, DrawingView view)
Point2D.Double getEndPoint ()
Point2D.Double getStartPoint ()
boolean isConnectable ()
void setConnectable (boolean newValue)
boolean isSelectable ()
void setSelectable (boolean newValue)
boolean isRemovable ()
void setRemovable (boolean newValue)
boolean isTransformable ()
void setTransformable (boolean newValue)
boolean isVisible ()
void setVisible (boolean newValue)
void requestRemove ()
int getLayer ()
String getToolTipText (Point2D.Double p)
String toString ()
Collection< Connector > getConnectors (ConnectionFigure prototype)
Public Member Functions inherited from org.jhotdraw.draw.figure.Figure
void addPropertyChangeListener (PropertyChangeListener listener)
void removePropertyChangeListener (PropertyChangeListener listener)
Public Member Functions inherited from org.jhotdraw.draw.Drawing
boolean add (Figure figure)
void add (int index, Figure figure)
void addAll (Collection<? extends Figure > figures)
void addAll (int index, Collection<? extends Figure > figures)
boolean remove (Figure figure)
void removeAll (Collection<? extends Figure > figures)
int basicRemove (Figure figure)
void basicRemoveAll (Collection<? extends Figure > figures)
void basicAdd (Figure figure)
void basicAddAll (int index, Collection<? extends Figure > figures)
void sendToBack (Figure figure)
void bringToFront (Figure figure)
void setInputFormats (List< InputFormat > formats)
void setOutputFormats (List< OutputFormat > formats)
Protected Member Functions
void drawFill (Graphics2D g)
void drawStroke (Graphics2D g)
Protected Member Functions inherited from org.jhotdraw.draw.figure.AbstractAttributedCompositeFigure
void drawChildren (Graphics2D g)
abstract void drawFill (java.awt.Graphics2D g)
abstract void drawStroke (java.awt.Graphics2D g)
void drawText (java.awt.Graphics2D g)
void writeAttributes (DOMOutput out) throws IOException
void readAttributes (DOMInput in) throws IOException
AttributeKey<?> getAttributeKey (String name)
void applyAttributesTo (Figure that)
Protected Member Functions inherited from org.jhotdraw.draw.figure.AbstractCompositeFigure
EventHandler createEventHandler ()
void validate ()
void invalidate ()
void fireFigureAdded (Figure f, int zIndex)
void fireFigureRemoved (Figure f, int zIndex)
Protected Member Functions inherited from org.jhotdraw.draw.figure.AbstractFigure
void fireAreaInvalidated (Rectangle2D.Double invalidatedArea)
void fireAreaInvalidated (FigureEvent event)
void fireFigureRequestRemove ()
void fireFigureAdded ()
void fireFigureRemoved ()
void fireFigureChanged (Rectangle2D.Double changedArea)
void fireFigureChanged (FigureEvent event)
void fireFigureHandlesChanged ()
boolean isChanging ()
int getChangingDepth ()
Additional Inherited Members
Static Public Member Functions inherited from org.jhotdraw.draw.AbstractDrawing
static boolean isDebugMode ()
static void setDebugMode (boolean debugMode)
Static Public Attributes inherited from org.jhotdraw.draw.figure.Figure
static final String CONNECTABLE_PROPERTY = "connectable"
static final String REMOVABLE_PROPERTY = "removable"
static final String SELECTABLE_PROPERTY = "selectable"
static final String TRANSFORMABLE_PROPERTY = "transformable"
Static Public Attributes inherited from org.jhotdraw.draw.figure.CompositeFigure
static final AttributeKey< Insets2D.Double > LAYOUT_INSETS = new AttributeKey<Insets2D.Double>("layoutInsets", Insets2D.Double.class, new Insets2D.Double())
Protected Attributes inherited from org.jhotdraw.draw.figure.AbstractCompositeFigure
Layouter layouter
ArrayList< Figure > children = new ArrayList<>()
transient Rectangle2D.Double cachedDrawingArea
transient Rectangle2D.Double cachedBounds
EventHandler eventHandler
Protected Attributes inherited from org.jhotdraw.draw.figure.AbstractFigure
EventListenerList listenerList = new EventListenerList()
int changingDepth = 0
Detailed Description
A default implementation of Drawing useful for drawings which contain only a few figures.
For larger drawings, QuadTreeDrawing is recommended.
FIXME - Maybe we should rename this class to SimpleDrawing or we should get rid of this class altogether.
Author
Werner Randelshofer
Version
$Id$
Constructor & Destructor Documentation
DefaultDrawing()
org.jhotdraw.draw.DefaultDrawing.DefaultDrawing ()
Creates a new instance.
Member Function Documentation
basicAdd()
void org.jhotdraw.draw.DefaultDrawing.basicAdd (int index, Figure figure)
Reinserts a figure which was temporarily removed using basicRemove.
See also
basicRemove(Figure)
Parameters
figure that is part of the drawing and should be removed
Implements org.jhotdraw.draw.Drawing.
draw() [1/2]
void org.jhotdraw.draw.DefaultDrawing.draw (Graphics2D g)
Draws the figure.
Parameters
g The Graphics2D to draw to.
Reimplemented from org.jhotdraw.draw.figure.AbstractCompositeFigure.
References org.jhotdraw.draw.figure.AbstractCompositeFigure.getChildren(), org.jhotdraw.draw.AbstractDrawing.getLock(), and org.jhotdraw.draw.AttributeKeys.getScaleFactorFromGraphics().
draw() [2/2]
void org.jhotdraw.draw.DefaultDrawing.draw (Graphics2D g, Collection< Figure > children)
References org.jhotdraw.draw.figure.AbstractCompositeFigure.children, and org.jhotdraw.draw.AttributeKeys.getScaleFactorFromGraphics().
drawCanvas()
void org.jhotdraw.draw.DefaultDrawing.drawCanvas (Graphics2D g)
Draws on the canvas area. The canvas is the background area onto which the drawing is drawn.
By convention this method is only invoked by DrawingView.
AttributeKeys defines a number of attribute keys which can be used to determine what to draw on the canvas.
Implements org.jhotdraw.draw.Drawing.
drawFill()
void org.jhotdraw.draw.DefaultDrawing.drawFill (Graphics2D g) protected
drawStroke()
void org.jhotdraw.draw.DefaultDrawing.drawStroke (Graphics2D g) protected
findFigure()
Figure org.jhotdraw.draw.DefaultDrawing.findFigure (Point2D.Double p)
Finds a top level Figure. Use this call for hit detection that should not descend into children of composite figures.
Use findFigureInside If you need to descend into children of composite figures.
Implements org.jhotdraw.draw.Drawing.
References org.jhotdraw.draw.DefaultDrawing.getFiguresFrontToBack().
Referenced by org.jhotdraw.draw.DefaultDrawing.findFigureInside().
findFigureBehind() [1/2]
Figure org.jhotdraw.draw.DefaultDrawing.findFigureBehind (Point2D.Double p, Collection<? extends Figure > figures)
Finds a top level Figure which is behind the specified Figures.
Implements org.jhotdraw.draw.Drawing.
References org.jhotdraw.draw.figure.AbstractCompositeFigure.children, and org.jhotdraw.draw.DefaultDrawing.getFiguresFrontToBack().
findFigureBehind() [2/2]
Figure org.jhotdraw.draw.DefaultDrawing.findFigureBehind (Point2D.Double p, Figure figure)
Finds a top level Figure which is behind the specified Figure.
Implements org.jhotdraw.draw.Drawing.
References org.jhotdraw.draw.DefaultDrawing.getFiguresFrontToBack().
findFigureExcept() [1/2]
Figure org.jhotdraw.draw.DefaultDrawing.findFigureExcept (Point2D.Double p, Collection<? extends Figure > ignore)
Finds a top level Figure. Use this call for hit detection that should not descend into the figure's children.
Implements org.jhotdraw.draw.Drawing.
References org.jhotdraw.draw.DefaultDrawing.getFiguresFrontToBack().
findFigureExcept() [2/2]
Figure org.jhotdraw.draw.DefaultDrawing.findFigureExcept (Point2D.Double p, Figure ignore)
Finds a top level Figure. Use this call for hit detection that should not descend into the figure's children.
Implements org.jhotdraw.draw.Drawing.
References org.jhotdraw.draw.DefaultDrawing.getFiguresFrontToBack(), and org.jhotdraw.draw.figure.Figure.isVisible().
findFigureInside()
Figure org.jhotdraw.draw.DefaultDrawing.findFigureInside (Point2D.Double p)
Finds the innermost figure at the specified location.
In case a
CompositeFigure
is at the specified location, this method descends into its children and into its children's children until the innermost figure is found.
This functionality is implemented using the Chain of Responsibility design pattern in the
Figure
interface. Since it is often used from a drawing object as the starting point, and since
Drawing
defines other find methods as well, it is defined here again for clarity.
Parameters
p A location on the drawing.
Returns
Returns the innermost figure at the location, or null if the location is not contained in a figure.
Implements org.jhotdraw.draw.Drawing.
References org.jhotdraw.draw.DefaultDrawing.findFigure(), and org.jhotdraw.draw.figure.Figure.findFigureInside().
findFigures()
List<Figure> org.jhotdraw.draw.DefaultDrawing.findFigures (Rectangle2D.Double bounds)
Returns all figures that lie within or intersect the specified bounds. The figures are returned in Z-order from back to front.
Implements org.jhotdraw.draw.Drawing.
References org.jhotdraw.draw.figure.AbstractCompositeFigure.getChildren().
findFiguresWithin()
List<Figure> org.jhotdraw.draw.DefaultDrawing.findFiguresWithin (Rectangle2D.Double bounds)
Returns all figures that lie within the specified bounds. The figures are returned in Z-order from back to front.
Implements org.jhotdraw.draw.Drawing.
References org.jhotdraw.draw.figure.AbstractCompositeFigure.getChildren().
getFiguresFrontToBack()
List<Figure> org.jhotdraw.draw.DefaultDrawing.getFiguresFrontToBack ()
Returns an iterator to iterate in Z-order front to back over the children.
Implements org.jhotdraw.draw.Drawing.
References org.jhotdraw.draw.figure.AbstractCompositeFigure.getChildren().
Referenced by org.jhotdraw.draw.DefaultDrawing.findFigure(), org.jhotdraw.draw.DefaultDrawing.findFigureBehind(), and org.jhotdraw.draw.DefaultDrawing.findFigureExcept().
indexOf()
int org.jhotdraw.draw.DefaultDrawing.indexOf (Figure child)
Returns the index of the specified child.
This is a convenience method for calling
getChildren().indexOf(index);
.
Returns
The index of the child, or -1 if the specified figure is not a child of this CompositeFigure.
Reimplemented from org.jhotdraw.draw.figure.AbstractCompositeFigure.
References org.jhotdraw.draw.figure.AbstractCompositeFigure.children.
sort()
List<Figure> org.jhotdraw.draw.DefaultDrawing.sort (Collection<? extends Figure > figures)
Returns a copy of the provided collection which is sorted in z order from back to front.
Implements org.jhotdraw.draw.Drawing.
References org.jhotdraw.draw.figure.AbstractCompositeFigure.getChildren().
The documentation for this class was generated from the following file:
jhotdraw-core/src/main/java/org/jhotdraw/draw/DefaultDrawing.java