jhotdraw: org.jhotdraw.draw.decoration.CompositeLineDecoration Class Reference
org.jhotdraw.draw.decoration.CompositeLineDecoration Class Reference
Public Member Functions
CompositeLineDecoration ()
CompositeLineDecoration (LineDecoration decoration1, LineDecoration decoration2)
void addDecoration (LineDecoration decoration)
void draw (Graphics2D g, Figure f, Point2D.Double p1, Point2D.Double p2)
Rectangle2D.Double getDrawingArea (Figure f, Point2D.Double p1, Point2D.Double p2)
double getDecorationRadius (Figure f)
void read (DOMInput in) throws IOException
void write (DOMOutput out) throws IOException
Detailed Description
A LineDecoration which can compose multiple individual line decorations.
An composite implementation of a line decoration. It allows more than one line decoration shape to be rotated and moved to the end of the line. The shape is scaled by the stroke width.
Author
Huw Jones
Constructor & Destructor Documentation
CompositeLineDecoration() [1/2]
org.jhotdraw.draw.decoration.CompositeLineDecoration.CompositeLineDecoration ()
Constructs a composite line decoration with no decorations.
CompositeLineDecoration() [2/2]
org.jhotdraw.draw.decoration.CompositeLineDecoration.CompositeLineDecoration (LineDecoration decoration1, LineDecoration decoration2)
Constructs a composite line decoration with the two supplied decorations.
References org.jhotdraw.draw.decoration.CompositeLineDecoration.addDecoration().
Member Function Documentation
addDecoration()
void org.jhotdraw.draw.decoration.CompositeLineDecoration.addDecoration (LineDecoration decoration)
Add another line decoration into the composite line decoration. The new decoration will be appended to the existing decorations and is also the last drawn.
Referenced by org.jhotdraw.draw.decoration.CompositeLineDecoration.CompositeLineDecoration(), and org.jhotdraw.draw.decoration.CompositeLineDecoration.read().
draw()
void org.jhotdraw.draw.decoration.CompositeLineDecoration.draw (Graphics2D g, Figure f, Point2D.Double p1, Point2D.Double p2)
Draws the arrow tip in the direction specified by the given two Points.. (template method)
Implements org.jhotdraw.draw.decoration.LineDecoration.
getDecorationRadius()
double org.jhotdraw.draw.decoration.CompositeLineDecoration.getDecorationRadius (Figure f)
Returns the radius of the decorator. This is used to crop the end of the line, to prevent it from being drawn it over the decorator.
Implements org.jhotdraw.draw.decoration.LineDecoration.
getDrawingArea()
Rectangle2D.Double org.jhotdraw.draw.decoration.CompositeLineDecoration.getDrawingArea (Figure f, Point2D.Double p1, Point2D.Double p2)
Returns the drawing area of the decorator.
Implements org.jhotdraw.draw.decoration.LineDecoration.
read()
void org.jhotdraw.draw.decoration.CompositeLineDecoration.read (DOMInput in) throws IOException
References org.jhotdraw.draw.decoration.CompositeLineDecoration.addDecoration().
write()
void org.jhotdraw.draw.decoration.CompositeLineDecoration.write (DOMOutput out) throws IOException
The documentation for this class was generated from the following file:
jhotdraw-core/src/main/java/org/jhotdraw/draw/decoration/CompositeLineDecoration.java