jhotdraw: org.jhotdraw.draw.action.SelectSameAction Class Reference
org.jhotdraw.draw.action.SelectSameAction Class Reference
Public Member Functions
SelectSameAction (DrawingEditor editor)
void actionPerformed (java.awt.event.ActionEvent e)
void selectSame ()
Public Member Functions inherited from org.jhotdraw.draw.action.AbstractSelectedAction
AbstractSelectedAction (DrawingEditor editor)
void dispose ()
void setEditor (DrawingEditor editor)
DrawingEditor getEditor ()
void setUpdateEnabledState (boolean newValue)
boolean isUpdatEnabledState ()
Static Public Attributes
static final String ID = "edit.selectSame"
Additional Inherited Members
Protected Member Functions inherited from org.jhotdraw.draw.action.AbstractSelectedAction
void updateEnabledState ()
DrawingView getView ()
Drawing getDrawing ()
void fireUndoableEditHappened (UndoableEdit edit)
Detailed Description
SelectSameAction.
Author
Werner Randelshofer
Version
$Id$
Constructor & Destructor Documentation
SelectSameAction()
org.jhotdraw.draw.action.SelectSameAction.SelectSameAction (DrawingEditor editor)
Creates a new instance.
References org.jhotdraw.draw.action.SelectSameAction.ID, and org.jhotdraw.draw.action.AbstractSelectedAction.updateEnabledState().
Member Function Documentation
actionPerformed()
void org.jhotdraw.draw.action.SelectSameAction.actionPerformed (java.awt.event.ActionEvent e)
References org.jhotdraw.draw.action.SelectSameAction.selectSame().
selectSame()
void org.jhotdraw.draw.action.SelectSameAction.selectSame ()
References org.jhotdraw.draw.DrawingView.addToSelection(), org.jhotdraw.draw.action.AbstractSelectedAction.getDrawing(), and org.jhotdraw.draw.action.AbstractSelectedAction.getView().
Referenced by org.jhotdraw.draw.action.SelectSameAction.actionPerformed().
Member Data Documentation
ID
final String org.jhotdraw.draw.action.SelectSameAction.ID = "edit.selectSame" static
Referenced by org.jhotdraw.draw.action.SelectSameAction.SelectSameAction().
The documentation for this class was generated from the following file:
jhotdraw-core/src/main/java/org/jhotdraw/draw/action/SelectSameAction.java