jhotdraw: org.jhotdraw.draw.DefaultDrawingView Class Reference
org.jhotdraw.draw.DefaultDrawingView Class Reference
Public Member Functions
void repaintHandles ()
boolean isSelectionEmpty ()
DefaultDrawingView ()
Drawing getDrawing ()
String getToolTipText (MouseEvent evt)
void setEmptyDrawingMessage (String newValue)
String getEmptyDrawingMessage ()
void paintComponent (Graphics gr)
void printComponent (Graphics gr)
void setDrawing (Drawing newValue)
void paint (Graphics g)
void invalidate ()
void removeNotify ()
void addToSelection (Figure figure)
void addToSelection (Collection< Figure > figures)
void removeFromSelection (Figure figure)
void toggleSelection (Figure figure)
void setEnabled (boolean b)
void selectAll ()
void clearSelection ()
boolean isFigureSelected (Figure checkFigure)
Set< Figure > getSelectedFigures ()
int getSelectionCount ()
Handle findHandle (Point p)
Collection< Handle > getCompatibleHandles (Handle master)
Figure findFigure (Point p)
Collection< Figure > findFigures (Rectangle r)
Collection< Figure > findFiguresWithin (Rectangle r)
void addFigureSelectionListener (FigureSelectionListener fsl)
void removeFigureSelectionListener (FigureSelectionListener fsl)
Constrainer getConstrainer ()
Dimension getPreferredSize ()
void setBounds (int x, int y, int width, int height)
Point drawingToView (Point2D.Double p)
Rectangle drawingToView (Rectangle2D.Double r)
Point2D.Double viewToDrawing (Point p)
Rectangle2D.Double viewToDrawing (Rectangle r)
JComponent getComponent ()
double getScaleFactor ()
void setScaleFactor (double newValue)
void setHandleDetailLevel (int newValue)
int getHandleDetailLevel ()
AffineTransform getDrawingToViewTransform ()
void delete ()
void duplicate ()
void removeNotify (DrawingEditor editor)
void addNotify (DrawingEditor editor)
void setVisibleConstrainer (Constrainer newValue)
Constrainer getVisibleConstrainer ()
void setInvisibleConstrainer (Constrainer newValue)
Constrainer getInvisibleConstrainer ()
void setConstrainerVisible (boolean newValue)
boolean isConstrainerVisible ()
void setDrawingDoubleBuffered (boolean newValue)
boolean isDrawingDoubleBuffered ()
DrawingEditor getEditor ()
void setActiveHandle (Handle newValue)
Handle getActiveHandle ()
Public Member Functions inherited from org.jhotdraw.draw.DrawingView
void setCursor (Cursor c)
void requestFocus ()
boolean isEnabled ()
void addPropertyChangeListener (PropertyChangeListener listener)
void removePropertyChangeListener (PropertyChangeListener listener)
void addMouseListener (MouseListener l)
void removeMouseListener (MouseListener l)
void addKeyListener (KeyListener l)
void removeKeyListener (KeyListener l)
void addMouseMotionListener (MouseMotionListener l)
void removeMouseMotionListener (MouseMotionListener l)
void addMouseWheelListener (MouseWheelListener l)
void removeMouseWheelListener (MouseWheelListener l)
Static Public Attributes
static final String DRAWING_DOUBLE_BUFFERED_PROPERTY = "drawingDoubleBuffered"
Static Public Attributes inherited from org.jhotdraw.draw.DrawingView
static final String DRAWING_PROPERTY = "drawing"
static final String CURSOR_PROPERTY = "cursor"
static final String CONSTRAINER_PROPERTY = "constrainer"
static final String VISIBLE_CONSTRAINER_PROPERTY = "visibleConstrainer"
static final String INVISIBLE_CONSTRAINER_PROPERTY = "invisibleConstrainer"
static final String CONSTRAINER_VISIBLE_PROPERTY = "constrainerVisible"
static final String SCALE_FACTOR_PROPERTY = "scaleFactor"
static final String HANDLE_DETAIL_LEVEL_PROPERTY = "handleDetailLevel"
static final String ENABLED_PROPERTY = "enabled"
static final String ACTIVE_HANDLE_PROPERTY = "activeHandle"
Protected Member Functions
void drawBackground (Graphics2D g)
EventHandler createEventHandler ()
void drawDrawingVolatileBuffered (Graphics2D g)
void drawDrawingNonvolatileBuffered (Graphics2D g)
void setViewRenderingHints (Graphics2D g)
Rectangle getCanvasViewBounds ()
void drawCanvas (Graphics2D gr)
void drawConstrainer (Graphics2D g)
void drawDrawing (Graphics2D gr)
void drawHandles (java.awt.Graphics2D g)
void drawTool (Graphics2D g)
void repaintDrawingArea (Rectangle2D.Double r)
void fireSelectionChanged (Set< Figure > oldValue, Set< Figure > newValue)
void invalidateDimension ()
Rectangle2D.Double getDrawingArea ()
void fireViewTransformChanged ()
Paint getBackgroundPaint (int x, int y)
Protected Attributes
BufferedImage backgroundTile
Detailed Description
A default implementation of DrawingView suited for viewing drawings with a small number of figures.
FIXME - Implement clone Method. FIXME - Use double buffering for the drawing to improve performance.
Author
Werner Randelshofer
Version
$Id$
Constructor & Destructor Documentation
DefaultDrawingView()
org.jhotdraw.draw.DefaultDrawingView.DefaultDrawingView ()
Creates new instance.
References org.jhotdraw.draw.DefaultDrawingView.createEventHandler().
Member Function Documentation
addFigureSelectionListener()
void org.jhotdraw.draw.DefaultDrawingView.addFigureSelectionListener (FigureSelectionListener fsl)
Add a listener for selection changes in this DrawingView.
Parameters
fsl jhotdraw.framework.FigureSelectionListener
Implements org.jhotdraw.draw.DrawingView.
addNotify()
void org.jhotdraw.draw.DefaultDrawingView.addNotify (DrawingEditor editor)
Informs the view that it has been added to the specified editor. The view must draw the tool of the editor, if getActiveView() of the editor returns the view.
Implements org.jhotdraw.draw.DrawingView.
addToSelection() [1/2]
void org.jhotdraw.draw.DefaultDrawingView.addToSelection (Collection< Figure > figures)
Adds a collection of figures to the current selection.
Implements org.jhotdraw.draw.DrawingView.
References org.jhotdraw.draw.DefaultDrawingView.fireSelectionChanged(), and org.jhotdraw.draw.DefaultDrawingView.getEditor().
addToSelection() [2/2]
void org.jhotdraw.draw.DefaultDrawingView.addToSelection (Figure figure)
Adds a figure to the current selection.
Implements org.jhotdraw.draw.DrawingView.
References org.jhotdraw.draw.figure.Figure.addFigureListener(), org.jhotdraw.draw.figure.Figure.createHandles(), org.jhotdraw.draw.DefaultDrawingView.fireSelectionChanged(), and org.jhotdraw.draw.DefaultDrawingView.getEditor().
Referenced by org.jhotdraw.draw.DefaultDrawingView.delete(), org.jhotdraw.draw.DefaultDrawingView.duplicate(), and org.jhotdraw.draw.DefaultDrawingView.toggleSelection().
clearSelection()
void org.jhotdraw.draw.DefaultDrawingView.clearSelection ()
Clears the current selection.
Implements org.jhotdraw.draw.DrawingView.
References org.jhotdraw.draw.DefaultDrawingView.fireSelectionChanged(), and org.jhotdraw.draw.DefaultDrawingView.getSelectionCount().
Referenced by org.jhotdraw.draw.DefaultDrawingView.delete(), org.jhotdraw.draw.DefaultDrawingView.duplicate(), and org.jhotdraw.draw.DefaultDrawingView.setDrawing().
createEventHandler()
EventHandler org.jhotdraw.draw.DefaultDrawingView.createEventHandler () protected
Referenced by org.jhotdraw.draw.DefaultDrawingView.DefaultDrawingView().
delete()
void org.jhotdraw.draw.DefaultDrawingView.delete ()
References org.jhotdraw.draw.Drawing.add(), org.jhotdraw.draw.DefaultDrawingView.addToSelection(), org.jhotdraw.draw.DefaultDrawingView.clearSelection(), org.jhotdraw.draw.Drawing.fireUndoableEditHappened(), org.jhotdraw.draw.DefaultDrawingView.getDrawing(), org.jhotdraw.draw.DefaultDrawingView.getSelectedFigures(), org.jhotdraw.draw.figure.CompositeFigure.indexOf(), org.jhotdraw.draw.Drawing.remove(), org.jhotdraw.draw.Drawing.removeAll(), and org.jhotdraw.draw.Drawing.sort().
drawBackground()
void org.jhotdraw.draw.DefaultDrawingView.drawBackground (Graphics2D g) protected
Draws the background of the drawing view.
References org.jhotdraw.draw.DefaultDrawingView.drawingToView(), org.jhotdraw.draw.figure.Figure.get(), and org.jhotdraw.draw.DefaultDrawingView.getBackgroundPaint().
Referenced by org.jhotdraw.draw.DefaultDrawingView.paintComponent().
drawCanvas()
void org.jhotdraw.draw.DefaultDrawingView.drawCanvas (Graphics2D gr) protected
Draws the canvas. If the
AttributeKeys.CANVAS_FILL_OPACITY
is not fully opaque, the canvas area is filled with the background paint before the
AttributeKeys.CANVAS_FILL_COLOR
is drawn.
References org.jhotdraw.draw.Drawing.drawCanvas(), and org.jhotdraw.draw.Drawing.setFontRenderContext().
Referenced by org.jhotdraw.draw.DefaultDrawingView.paintComponent().
drawConstrainer()
void org.jhotdraw.draw.DefaultDrawingView.drawConstrainer (Graphics2D g) protected
References org.jhotdraw.draw.Constrainer.draw(), org.jhotdraw.draw.DefaultDrawingView.getCanvasViewBounds(), and org.jhotdraw.draw.DefaultDrawingView.getConstrainer().
Referenced by org.jhotdraw.draw.DefaultDrawingView.paintComponent().
drawDrawing()
void org.jhotdraw.draw.DefaultDrawingView.drawDrawing (Graphics2D gr) protected
References org.jhotdraw.draw.figure.Figure.draw(), org.jhotdraw.draw.figure.CompositeFigure.getChildCount(), and org.jhotdraw.draw.Drawing.setFontRenderContext().
Referenced by org.jhotdraw.draw.DefaultDrawingView.drawDrawingNonvolatileBuffered(), org.jhotdraw.draw.DefaultDrawingView.drawDrawingVolatileBuffered(), org.jhotdraw.draw.DefaultDrawingView.paintComponent(), and org.jhotdraw.draw.DefaultDrawingView.printComponent().
drawDrawingNonvolatileBuffered()
void org.jhotdraw.draw.DefaultDrawingView.drawDrawingNonvolatileBuffered (Graphics2D g) protected
Draws the drawing double buffered using a buffered image.
References org.jhotdraw.draw.DefaultDrawingView.drawDrawing(), and org.jhotdraw.draw.DefaultDrawingView.setViewRenderingHints().
Referenced by org.jhotdraw.draw.DefaultDrawingView.paintComponent().
drawDrawingVolatileBuffered()
void org.jhotdraw.draw.DefaultDrawingView.drawDrawingVolatileBuffered (Graphics2D g) protected
Draws the drawing double buffered using a volatile image.
References org.jhotdraw.draw.DefaultDrawingView.drawDrawing(), and org.jhotdraw.draw.DefaultDrawingView.setViewRenderingHints().
Referenced by org.jhotdraw.draw.DefaultDrawingView.paintComponent().
drawHandles()
void org.jhotdraw.draw.DefaultDrawingView.drawHandles (java.awt.Graphics2D g) protected
References org.jhotdraw.draw.DrawingEditor.getActiveView().
Referenced by org.jhotdraw.draw.DefaultDrawingView.paintComponent().
drawingToView() [1/2]
Point org.jhotdraw.draw.DefaultDrawingView.drawingToView (Point2D.Double p)
Converts drawing coordinates to view coordinates.
Implements org.jhotdraw.draw.DrawingView.
Referenced by org.jhotdraw.draw.DefaultDrawingView.drawBackground(), org.jhotdraw.draw.DefaultDrawingView.getCanvasViewBounds(), and org.jhotdraw.draw.DefaultDrawingView.repaintDrawingArea().
drawingToView() [2/2]
Rectangle org.jhotdraw.draw.DefaultDrawingView.drawingToView (Rectangle2D.Double p)
Converts drawing coordinates to view coordinates.
Implements org.jhotdraw.draw.DrawingView.
drawTool()
void org.jhotdraw.draw.DefaultDrawingView.drawTool (Graphics2D g) protected
References org.jhotdraw.draw.tool.Tool.draw(), org.jhotdraw.draw.DrawingEditor.getActiveView(), and org.jhotdraw.draw.DrawingEditor.getTool().
Referenced by org.jhotdraw.draw.DefaultDrawingView.paintComponent().
duplicate()
void org.jhotdraw.draw.DefaultDrawingView.duplicate ()
References org.jhotdraw.draw.Drawing.add(), org.jhotdraw.draw.Drawing.addAll(), org.jhotdraw.draw.DefaultDrawingView.addToSelection(), org.jhotdraw.draw.DefaultDrawingView.clearSelection(), org.jhotdraw.draw.figure.Figure.clone(), org.jhotdraw.draw.Drawing.fireUndoableEditHappened(), org.jhotdraw.draw.DefaultDrawingView.getDrawing(), org.jhotdraw.draw.DefaultDrawingView.getSelectedFigures(), org.jhotdraw.draw.Drawing.removeAll(), org.jhotdraw.draw.Drawing.sort(), and org.jhotdraw.draw.figure.Figure.transform().
findFigure()
Figure org.jhotdraw.draw.DefaultDrawingView.findFigure (Point p)
Finds a figure at a given coordinates.
Returns
A figure, null if no figure is found.
Implements org.jhotdraw.draw.DrawingView.
References org.jhotdraw.draw.Drawing.findFigure(), org.jhotdraw.draw.DefaultDrawingView.getDrawing(), and org.jhotdraw.draw.DefaultDrawingView.viewToDrawing().
findFigures()
Collection<Figure> org.jhotdraw.draw.DefaultDrawingView.findFigures (Rectangle r)
Returns all figures that lie within or intersect the specified bounds. The figures are returned in Z-order from back to front.
Implements org.jhotdraw.draw.DrawingView.
References org.jhotdraw.draw.Drawing.findFigures(), org.jhotdraw.draw.DefaultDrawingView.getDrawing(), and org.jhotdraw.draw.DefaultDrawingView.viewToDrawing().
findFiguresWithin()
Collection<Figure> org.jhotdraw.draw.DefaultDrawingView.findFiguresWithin (Rectangle r)
Returns all figures that lie within the specified bounds. The figures are returned in Z-order from back to front.
Implements org.jhotdraw.draw.DrawingView.
References org.jhotdraw.draw.Drawing.findFiguresWithin(), org.jhotdraw.draw.DefaultDrawingView.getDrawing(), and org.jhotdraw.draw.DefaultDrawingView.viewToDrawing().
findHandle()
Handle org.jhotdraw.draw.DefaultDrawingView.findHandle (Point p)
Finds a handle at a given coordinates.
Returns
A handle, null if no handle is found.
Implements org.jhotdraw.draw.DrawingView.
fireSelectionChanged()
void org.jhotdraw.draw.DefaultDrawingView.fireSelectionChanged (Set< Figure > oldValue, Set< Figure > newValue) protected
Notify all listenerList that have registered interest for notification on this event type. Also notify listeners who listen for EditableComponent#SELECTION_EMPTY_PROPERTY.
Referenced by org.jhotdraw.draw.DefaultDrawingView.addToSelection(), org.jhotdraw.draw.DefaultDrawingView.clearSelection(), org.jhotdraw.draw.DefaultDrawingView.removeFromSelection(), and org.jhotdraw.draw.DefaultDrawingView.selectAll().
fireViewTransformChanged()
void org.jhotdraw.draw.DefaultDrawingView.fireViewTransformChanged () protected
getActiveHandle()
Handle org.jhotdraw.draw.DefaultDrawingView.getActiveHandle ()
Gets the active handle.
Implements org.jhotdraw.draw.DrawingView.
getBackgroundPaint()
Paint org.jhotdraw.draw.DefaultDrawingView.getBackgroundPaint (int x, int y) protected
Returns a paint for drawing the background of the drawing area.
Returns
Paint.
References org.jhotdraw.draw.DefaultDrawingView.backgroundTile.
Referenced by org.jhotdraw.draw.DefaultDrawingView.drawBackground().
getCanvasViewBounds()
Rectangle org.jhotdraw.draw.DefaultDrawingView.getCanvasViewBounds () protected
Returns the bounds of the canvas on the drawing view.
Returns
The current bounds of the canvas on the drawing view.
References org.jhotdraw.draw.DefaultDrawingView.drawingToView(), org.jhotdraw.draw.figure.Figure.get(), and org.jhotdraw.draw.DefaultDrawingView.getDrawing().
Referenced by org.jhotdraw.draw.DefaultDrawingView.drawConstrainer().
getCompatibleHandles()
Collection<Handle> org.jhotdraw.draw.DefaultDrawingView.getCompatibleHandles (Handle master)
Gets compatible handles.
Returns
A collection containing the handle and all compatible handles.
Implements org.jhotdraw.draw.DrawingView.
References org.jhotdraw.draw.handle.Handle.getOwner().
getComponent()
JComponent org.jhotdraw.draw.DefaultDrawingView.getComponent ()
Returns the JComponent of the drawing view.
The drawing framework supports only two use cases, where this component may be accessed:
The component can be used to add the drawing view to a parent Swing component.
The currently active org.jhotdraw.draw.tool.Tool may add child components to the drawing view. The tool must remove these components when it becomes inactive.
Implements org.jhotdraw.draw.DrawingView.
getConstrainer()
Constrainer org.jhotdraw.draw.DefaultDrawingView.getConstrainer ()
Gets the current constrainer of this view. If isConstrainerVisible is true, this method returns getVisibleConstrainer, otherwise it returns getInvisibleConstrainer. This is a bound property.
Implements org.jhotdraw.draw.DrawingView.
Referenced by org.jhotdraw.draw.DefaultDrawingView.drawConstrainer().
getDrawing()
Drawing org.jhotdraw.draw.DefaultDrawingView.getDrawing ()
Gets the drawing. This is a bound property.
Implements org.jhotdraw.draw.DrawingView.
Referenced by org.jhotdraw.draw.DefaultDrawingView.delete(), org.jhotdraw.draw.DefaultDrawingView.duplicate(), org.jhotdraw.draw.DefaultDrawingView.findFigure(), org.jhotdraw.draw.DefaultDrawingView.findFigures(), org.jhotdraw.draw.DefaultDrawingView.findFiguresWithin(), org.jhotdraw.draw.DefaultDrawingView.getCanvasViewBounds(), and org.jhotdraw.draw.DefaultDrawingView.getPreferredSize().
getDrawingArea()
Rectangle2D.Double org.jhotdraw.draw.DefaultDrawingView.getDrawingArea () protected
References org.jhotdraw.draw.figure.Figure.getDrawingArea().
Referenced by org.jhotdraw.draw.DefaultDrawingView.getPreferredSize().
getDrawingToViewTransform()
AffineTransform org.jhotdraw.draw.DefaultDrawingView.getDrawingToViewTransform ()
Gets an transform which can be used to convert drawing coordinates to view coordinates.
Implements org.jhotdraw.draw.DrawingView.
getEditor()
DrawingEditor org.jhotdraw.draw.DefaultDrawingView.getEditor ()
Gets the drawing editor associated to the DrawingView. This is a bound property.
Implements org.jhotdraw.draw.DrawingView.
Referenced by org.jhotdraw.draw.DefaultDrawingView.addToSelection(), and org.jhotdraw.draw.DefaultDrawingView.getToolTipText().
getEmptyDrawingMessage()
String org.jhotdraw.draw.DefaultDrawingView.getEmptyDrawingMessage ()
getHandleDetailLevel()
int org.jhotdraw.draw.DefaultDrawingView.getHandleDetailLevel ()
Returns the detail level of the handles. This is a bound property.
Implements org.jhotdraw.draw.DrawingView.
getInvisibleConstrainer()
Constrainer org.jhotdraw.draw.DefaultDrawingView.getInvisibleConstrainer ()
Gets the editor's constrainer for this view, for use, when the visible constrainer is turned off. This is a bound property.
Implements org.jhotdraw.draw.DrawingView.
getPreferredSize()
Dimension org.jhotdraw.draw.DefaultDrawingView.getPreferredSize ()
References org.jhotdraw.draw.figure.Figure.get(), org.jhotdraw.draw.DefaultDrawingView.getDrawing(), and org.jhotdraw.draw.DefaultDrawingView.getDrawingArea().
getScaleFactor()
double org.jhotdraw.draw.DefaultDrawingView.getScaleFactor ()
Gets the scale factor of the drawing view. This is a bound property.
Implements org.jhotdraw.draw.DrawingView.
getSelectedFigures()
Set<Figure> org.jhotdraw.draw.DefaultDrawingView.getSelectedFigures ()
Gets the current selection as a FigureSelection. A FigureSelection can be cut, copied, pasted.
Implements org.jhotdraw.draw.DrawingView.
Referenced by org.jhotdraw.draw.DefaultDrawingView.delete(), and org.jhotdraw.draw.DefaultDrawingView.duplicate().
getSelectionCount()
int org.jhotdraw.draw.DefaultDrawingView.getSelectionCount ()
Gets the number of selected figures.
Implements org.jhotdraw.draw.DrawingView.
Referenced by org.jhotdraw.draw.DefaultDrawingView.clearSelection().
getToolTipText()
String org.jhotdraw.draw.DefaultDrawingView.getToolTipText (MouseEvent evt)
References org.jhotdraw.draw.DefaultDrawingView.getEditor(), org.jhotdraw.draw.DrawingEditor.getTool(), and org.jhotdraw.draw.tool.Tool.getToolTipText().
getVisibleConstrainer()
Constrainer org.jhotdraw.draw.DefaultDrawingView.getVisibleConstrainer ()
Gets the editor's constrainer for this view, for use, when the visible constrainer is turned on. This is a bound property.
Implements org.jhotdraw.draw.DrawingView.
invalidate()
void org.jhotdraw.draw.DefaultDrawingView.invalidate ()
References org.jhotdraw.draw.DefaultDrawingView.invalidateDimension().
invalidateDimension()
void org.jhotdraw.draw.DefaultDrawingView.invalidateDimension () protected
Referenced by org.jhotdraw.draw.DefaultDrawingView.invalidate().
isConstrainerVisible()
boolean org.jhotdraw.draw.DefaultDrawingView.isConstrainerVisible ()
Returns true, if the visible Constrainer is in use, returns false, if the invisible Constrainer is in use. This is a bound property.
Implements org.jhotdraw.draw.DrawingView.
isDrawingDoubleBuffered()
boolean org.jhotdraw.draw.DefaultDrawingView.isDrawingDoubleBuffered ()
Returns true, if the the drawing is double buffered.
isFigureSelected()
boolean org.jhotdraw.draw.DefaultDrawingView.isFigureSelected (Figure checkFigure)
Test whether a given figure is selected.
Implements org.jhotdraw.draw.DrawingView.
isSelectionEmpty()
boolean org.jhotdraw.draw.DefaultDrawingView.isSelectionEmpty ()
paint()
void org.jhotdraw.draw.DefaultDrawingView.paint (Graphics g)
paintComponent()
void org.jhotdraw.draw.DefaultDrawingView.paintComponent (Graphics gr)
Paints the drawing view. Uses rendering hints for fast painting. Paints the canvasColor, the grid, the drawing, the handles and the current tool.
References org.jhotdraw.draw.DefaultDrawingView.drawBackground(), org.jhotdraw.draw.DefaultDrawingView.drawCanvas(), org.jhotdraw.draw.DefaultDrawingView.drawConstrainer(), org.jhotdraw.draw.DefaultDrawingView.drawDrawing(), org.jhotdraw.draw.DefaultDrawingView.drawDrawingNonvolatileBuffered(), org.jhotdraw.draw.DefaultDrawingView.drawDrawingVolatileBuffered(), org.jhotdraw.draw.DefaultDrawingView.drawHandles(), org.jhotdraw.draw.DefaultDrawingView.drawTool(), and org.jhotdraw.draw.DefaultDrawingView.setViewRenderingHints().
printComponent()
void org.jhotdraw.draw.DefaultDrawingView.printComponent (Graphics gr)
Prints the drawing view. Uses high quality rendering hints for printing. Only prints the drawing. Doesn't print the canvasColor, the grid, the handles and the tool.
References org.jhotdraw.draw.DefaultDrawingView.drawDrawing().
removeFigureSelectionListener()
void org.jhotdraw.draw.DefaultDrawingView.removeFigureSelectionListener (FigureSelectionListener fsl)
Remove a listener for selection changes in this DrawingView.
Parameters
fsl jhotdraw.framework.FigureSelectionListener
Implements org.jhotdraw.draw.DrawingView.
removeFromSelection()
void org.jhotdraw.draw.DefaultDrawingView.removeFromSelection (Figure figure)
Removes a figure from the selection.
Implements org.jhotdraw.draw.DrawingView.
References org.jhotdraw.draw.DefaultDrawingView.fireSelectionChanged(), and org.jhotdraw.draw.figure.Figure.removeFigureListener().
Referenced by org.jhotdraw.draw.DefaultDrawingView.toggleSelection().
removeNotify() [1/2]
void org.jhotdraw.draw.DefaultDrawingView.removeNotify ()
removeNotify() [2/2]
void org.jhotdraw.draw.DefaultDrawingView.removeNotify (DrawingEditor editor)
Informs the view that it has been removed from the specified editor. The view must not draw the tool from the editor anymore.
Implements org.jhotdraw.draw.DrawingView.
repaintDrawingArea()
void org.jhotdraw.draw.DefaultDrawingView.repaintDrawingArea (Rectangle2D.Double r) protected
References org.jhotdraw.draw.DefaultDrawingView.drawingToView().
repaintHandles()
void org.jhotdraw.draw.DefaultDrawingView.repaintHandles ()
Repaints the handles of the view.
Implements org.jhotdraw.draw.DrawingView.
selectAll()
void org.jhotdraw.draw.DefaultDrawingView.selectAll ()
Selects all selectable figures.
Implements org.jhotdraw.draw.DrawingView.
References org.jhotdraw.draw.DefaultDrawingView.fireSelectionChanged(), and org.jhotdraw.draw.figure.CompositeFigure.getChildren().
setActiveHandle()
void org.jhotdraw.draw.DefaultDrawingView.setActiveHandle (Handle newValue)
Sets the active handle.
Implements org.jhotdraw.draw.DrawingView.
References org.jhotdraw.draw.DrawingView.ACTIVE_HANDLE_PROPERTY, and org.jhotdraw.draw.handle.Handle.getDrawingArea().
setBounds()
void org.jhotdraw.draw.DefaultDrawingView.setBounds (int x, int y, int width, int height)
Side effect: Changes view Translation.
setConstrainerVisible()
void org.jhotdraw.draw.DefaultDrawingView.setConstrainerVisible (boolean newValue)
Changes between a visible Constrainer and an invisible Constrainer. This is a bound property.
Implements org.jhotdraw.draw.DrawingView.
References org.jhotdraw.draw.DrawingView.CONSTRAINER_VISIBLE_PROPERTY.
setDrawing()
void org.jhotdraw.draw.DefaultDrawingView.setDrawing (Drawing d)
Sets and installs another drawing in the view. This is a bound property.
Implements org.jhotdraw.draw.DrawingView.
References org.jhotdraw.draw.figure.CompositeFigure.addCompositeFigureListener(), org.jhotdraw.draw.figure.Figure.addFigureListener(), org.jhotdraw.draw.DefaultDrawingView.clearSelection(), org.jhotdraw.draw.DrawingView.DRAWING_PROPERTY, org.jhotdraw.draw.figure.CompositeFigure.removeCompositeFigureListener(), and org.jhotdraw.draw.figure.Figure.removeFigureListener().
setDrawingDoubleBuffered()
void org.jhotdraw.draw.DefaultDrawingView.setDrawingDoubleBuffered (boolean newValue)
Sets whether the drawing is double buffered.
The default value is true.
This is a bound property.
If the drawing view is used for editing, you should leave this to true. If the drawing view is used for viewing only, you should set this to false.
References org.jhotdraw.draw.DefaultDrawingView.DRAWING_DOUBLE_BUFFERED_PROPERTY.
setEmptyDrawingMessage()
void org.jhotdraw.draw.DefaultDrawingView.setEmptyDrawingMessage (String newValue)
setEnabled()
void org.jhotdraw.draw.DefaultDrawingView.setEnabled (boolean newValue)
Sets the enabled state of the drawing view. This is a bound property.
Implements org.jhotdraw.draw.DrawingView.
References org.jhotdraw.draw.DrawingView.setCursor().
setHandleDetailLevel()
void org.jhotdraw.draw.DefaultDrawingView.setHandleDetailLevel (int newValue)
The detail level of the handles. This is a bound property.
Implements org.jhotdraw.draw.DrawingView.
setInvisibleConstrainer()
void org.jhotdraw.draw.DefaultDrawingView.setInvisibleConstrainer (Constrainer constrainer)
Sets the editor's constrainer for this view, for use, when the visible constrainer is turned off. This is a bound property.
Implements org.jhotdraw.draw.DrawingView.
References org.jhotdraw.draw.DrawingView.INVISIBLE_CONSTRAINER_PROPERTY.
setScaleFactor()
void org.jhotdraw.draw.DefaultDrawingView.setScaleFactor (double newValue)
Sets the scale factor of the drawing view. This is a bound property.
Implements org.jhotdraw.draw.DrawingView.
setViewRenderingHints()
void org.jhotdraw.draw.DefaultDrawingView.setViewRenderingHints (Graphics2D g) protected
Referenced by org.jhotdraw.draw.DefaultDrawingView.drawDrawingNonvolatileBuffered(), org.jhotdraw.draw.DefaultDrawingView.drawDrawingVolatileBuffered(), and org.jhotdraw.draw.DefaultDrawingView.paintComponent().
setVisibleConstrainer()
void org.jhotdraw.draw.DefaultDrawingView.setVisibleConstrainer (Constrainer constrainer)
Sets the editor's constrainer for this view, for use, when the visible constrainer is turned on. This is a bound property.
Implements org.jhotdraw.draw.DrawingView.
References org.jhotdraw.draw.DrawingView.VISIBLE_CONSTRAINER_PROPERTY.
toggleSelection()
void org.jhotdraw.draw.DefaultDrawingView.toggleSelection (Figure figure)
If a figure isn't selected it is added to the selection. Otherwise it is removed from the selection.
Implements org.jhotdraw.draw.DrawingView.
References org.jhotdraw.draw.DefaultDrawingView.addToSelection(), and org.jhotdraw.draw.DefaultDrawingView.removeFromSelection().
viewToDrawing() [1/2]
Point2D.Double org.jhotdraw.draw.DefaultDrawingView.viewToDrawing (Point p)
Converts view coordinates to drawing coordinates.
Implements org.jhotdraw.draw.DrawingView.
Referenced by org.jhotdraw.draw.DefaultDrawingView.findFigure(), org.jhotdraw.draw.DefaultDrawingView.findFigures(), and org.jhotdraw.draw.DefaultDrawingView.findFiguresWithin().
viewToDrawing() [2/2]
Rectangle2D.Double org.jhotdraw.draw.DefaultDrawingView.viewToDrawing (Rectangle p)
Converts view coordinates to drawing coordinates.
Implements org.jhotdraw.draw.DrawingView.
Member Data Documentation
backgroundTile
BufferedImage org.jhotdraw.draw.DefaultDrawingView.backgroundTile protected
Referenced by org.jhotdraw.draw.DefaultDrawingView.getBackgroundPaint().
DRAWING_DOUBLE_BUFFERED_PROPERTY
final String org.jhotdraw.draw.DefaultDrawingView.DRAWING_DOUBLE_BUFFERED_PROPERTY = "drawingDoubleBuffered" static
Referenced by org.jhotdraw.draw.DefaultDrawingView.setDrawingDoubleBuffered().
The documentation for this class was generated from the following file:
jhotdraw-core/src/main/java/org/jhotdraw/draw/DefaultDrawingView.java