jhotdraw: org.jhotdraw.draw.action.ZoomEditorAction Class Reference
org.jhotdraw.draw.action.ZoomEditorAction Class Reference
Public Member Functions
ZoomEditorAction (DrawingEditor editor, double scaleFactor, AbstractButton button)
ZoomEditorAction (DrawingEditor editor, double scaleFactor, AbstractButton button, boolean updateAllViews)
void actionPerformed (java.awt.event.ActionEvent e)
Public Member Functions inherited from org.jhotdraw.draw.action.AbstractDrawingEditorAction
AbstractDrawingEditorAction (DrawingEditor editor)
void setEditor (DrawingEditor newValue)
DrawingEditor getEditor ()
void setUpdateEnabledState (boolean newValue)
boolean isUpdatEnabledState ()
Static Public Attributes
static final String ID = "zoomEditor"
Additional Inherited Members
Protected Member Functions inherited from org.jhotdraw.draw.action.AbstractDrawingEditorAction
void updateEnabledState ()
DrawingView getView ()
Drawing getDrawing ()
void fireUndoableEditHappened (UndoableEdit edit)
Protected Attributes inherited from org.jhotdraw.draw.action.AbstractDrawingEditorAction
DrawingEditor editor
Detailed Description
Zooms either the current view or all views of a DrawingEditor.
Author
Werner Randelshofer
Version
$Id$
Constructor & Destructor Documentation
ZoomEditorAction() [1/2]
org.jhotdraw.draw.action.ZoomEditorAction.ZoomEditorAction (DrawingEditor editor, double scaleFactor, AbstractButton button)
Creates a new instance.
References org.jhotdraw.draw.action.AbstractDrawingEditorAction.editor.
ZoomEditorAction() [2/2]
org.jhotdraw.draw.action.ZoomEditorAction.ZoomEditorAction (DrawingEditor editor, double scaleFactor, AbstractButton button, boolean updateAllViews)
Creates a new instance.
References org.jhotdraw.draw.action.AbstractDrawingEditorAction.editor.
Member Function Documentation
actionPerformed()
void org.jhotdraw.draw.action.ZoomEditorAction.actionPerformed (java.awt.event.ActionEvent e)
References org.jhotdraw.draw.action.AbstractDrawingEditorAction.getEditor(), org.jhotdraw.draw.action.AbstractDrawingEditorAction.getView(), and org.jhotdraw.draw.DrawingView.setScaleFactor().
Member Data Documentation
ID
final String org.jhotdraw.draw.action.ZoomEditorAction.ID = "zoomEditor" static
The documentation for this class was generated from the following file:
jhotdraw-core/src/main/java/org/jhotdraw/draw/action/ZoomEditorAction.java