jhotdraw: org.jhotdraw.draw.action.AttributeAction Class Reference
org.jhotdraw.draw.action.AttributeAction Class Reference
Public Member Functions
AttributeAction (DrawingEditor editor, Map< AttributeKey<?>, Object > attributes, String name, Icon icon)
void actionPerformed (java.awt.event.ActionEvent evt)
void applyAttributesTo (final Map< AttributeKey<?>, Object > a, Set< Figure > figures)
Public Member Functions inherited from org.jhotdraw.draw.action.AbstractSelectedAction
AbstractSelectedAction (DrawingEditor editor)
void dispose ()
void setEditor (DrawingEditor editor)
DrawingEditor getEditor ()
void setUpdateEnabledState (boolean newValue)
boolean isUpdatEnabledState ()
Protected Member Functions
void updateEnabledState ()
Protected Member Functions inherited from org.jhotdraw.draw.action.AbstractSelectedAction
DrawingView getView ()
Drawing getDrawing ()
void fireUndoableEditHappened (UndoableEdit edit)
Protected Attributes
Map< AttributeKey<?>, Object > attributes
Detailed Description
AttributeAction
applies attribute values on the selected figures of the current
DrawingView
of a
DrawingEditor
.
Author
Werner Randelshofer
Version
$Id$
Constructor & Destructor Documentation
AttributeAction()
org.jhotdraw.draw.action.AttributeAction.AttributeAction (DrawingEditor editor, Map< AttributeKey<?>, Object > attributes, String name, Icon icon)
References org.jhotdraw.draw.action.AttributeAction.attributes, and org.jhotdraw.draw.action.AttributeAction.updateEnabledState().
Member Function Documentation
actionPerformed()
void org.jhotdraw.draw.action.AttributeAction.actionPerformed (java.awt.event.ActionEvent evt)
Reimplemented in org.jhotdraw.draw.action.EditorColorChooserAction, and org.jhotdraw.draw.action.DrawingColorChooserAction.
References org.jhotdraw.draw.action.AttributeAction.applyAttributesTo(), org.jhotdraw.draw.action.AttributeAction.attributes, and org.jhotdraw.draw.action.AbstractSelectedAction.getView().
applyAttributesTo()
void org.jhotdraw.draw.action.AttributeAction.applyAttributesTo (final Map< AttributeKey<?>, Object > a, Set< Figure > figures)
Applies the specified attributes to the currently selected figures of the drawing.
Parameters
a The attributes.
figures The figures to which the attributes are applied.
References org.jhotdraw.draw.Drawing.fireUndoableEditHappened(), org.jhotdraw.draw.action.AbstractSelectedAction.getDrawing(), org.jhotdraw.draw.action.AbstractSelectedAction.getEditor(), and org.jhotdraw.draw.DrawingEditor.setDefaultAttribute().
Referenced by org.jhotdraw.draw.action.DrawingColorChooserAction.actionPerformed(), org.jhotdraw.draw.action.EditorColorChooserAction.actionPerformed(), and org.jhotdraw.draw.action.AttributeAction.actionPerformed().
updateEnabledState()
void org.jhotdraw.draw.action.AttributeAction.updateEnabledState () protected
Updates the enabled state of this action to reflect the enabled state of the active
DrawingView
. If no drawing view is active, this action is disabled.
Reimplemented from org.jhotdraw.draw.action.AbstractSelectedAction.
Reimplemented in org.jhotdraw.draw.action.DrawingColorChooserAction.
References org.jhotdraw.draw.action.AbstractSelectedAction.getEditor().
Referenced by org.jhotdraw.draw.action.AttributeAction.AttributeAction(), and org.jhotdraw.draw.action.EditorColorChooserAction.EditorColorChooserAction().
Member Data Documentation
attributes
Map<AttributeKey<?>, Object> org.jhotdraw.draw.action.AttributeAction.attributes protected
Referenced by org.jhotdraw.draw.action.DrawingColorChooserAction.actionPerformed(), org.jhotdraw.draw.action.EditorColorChooserAction.actionPerformed(), org.jhotdraw.draw.action.AttributeAction.actionPerformed(), and org.jhotdraw.draw.action.AttributeAction.AttributeAction().
The documentation for this class was generated from the following file:
jhotdraw-core/src/main/java/org/jhotdraw/draw/action/AttributeAction.java