jhotdraw: org.jhotdraw.draw.action.SendToBackAction Class Reference
org.jhotdraw.draw.action.SendToBackAction Class Reference
Public Member Functions
SendToBackAction (DrawingEditor editor)
void actionPerformed (java.awt.event.ActionEvent e)
Public Member Functions inherited from org.jhotdraw.draw.action.AbstractSelectedAction
AbstractSelectedAction (DrawingEditor editor)
void dispose ()
void setEditor (DrawingEditor editor)
DrawingEditor getEditor ()
void setUpdateEnabledState (boolean newValue)
boolean isUpdatEnabledState ()
Static Public Member Functions
static void sendToBack (DrawingView view, Collection< Figure > figures)
Static Public Attributes
static final String ID = "edit.sendToBack"
Additional Inherited Members
Protected Member Functions inherited from org.jhotdraw.draw.action.AbstractSelectedAction
void updateEnabledState ()
DrawingView getView ()
Drawing getDrawing ()
void fireUndoableEditHappened (UndoableEdit edit)
Detailed Description
SendToBackAction.
Author
Werner Randelshofer
Version
$Id$
Constructor & Destructor Documentation
SendToBackAction()
org.jhotdraw.draw.action.SendToBackAction.SendToBackAction (DrawingEditor editor)
Creates a new instance.
References org.jhotdraw.draw.action.SendToBackAction.ID, and org.jhotdraw.draw.action.AbstractSelectedAction.updateEnabledState().
Member Function Documentation
actionPerformed()
void org.jhotdraw.draw.action.SendToBackAction.actionPerformed (java.awt.event.ActionEvent e)
References org.jhotdraw.draw.action.BringToFrontAction.bringToFront(), org.jhotdraw.draw.action.AbstractSelectedAction.fireUndoableEditHappened(), org.jhotdraw.draw.DrawingView.getSelectedFigures(), org.jhotdraw.draw.action.AbstractSelectedAction.getView(), org.jhotdraw.draw.action.SendToBackAction.ID, and org.jhotdraw.draw.action.SendToBackAction.sendToBack().
sendToBack()
static void org.jhotdraw.draw.action.SendToBackAction.sendToBack (DrawingView view, Collection< Figure > figures) static
References org.jhotdraw.draw.DrawingView.getDrawing(), and org.jhotdraw.draw.Drawing.sendToBack().
Referenced by org.jhotdraw.draw.action.BringToFrontAction.actionPerformed(), and org.jhotdraw.draw.action.SendToBackAction.actionPerformed().
Member Data Documentation
ID
final String org.jhotdraw.draw.action.SendToBackAction.ID = "edit.sendToBack" static
Referenced by org.jhotdraw.draw.action.SendToBackAction.actionPerformed(), and org.jhotdraw.draw.action.SendToBackAction.SendToBackAction().
The documentation for this class was generated from the following file:
jhotdraw-core/src/main/java/org/jhotdraw/draw/action/SendToBackAction.java