jhotdraw: org.jhotdraw.draw.decoration.AbstractLineDecoration Class Reference
org.jhotdraw.draw.decoration.AbstractLineDecoration Class Reference abstract
Public Member Functions
AbstractLineDecoration (boolean isFilled, boolean isStroked, boolean isSolid)
void draw (Graphics2D g, Figure f, Point2D.Double p1, Point2D.Double p2)
Rectangle2D.Double getDrawingArea (Figure f, Point2D.Double p1, Point2D.Double p2)
double getDecorationRadius (Figure f)
Protected Member Functions
boolean isFilled ()
boolean isStroked ()
boolean isSolid ()
void setFilled (boolean b)
void setStroked (boolean b)
void setSolid (boolean b)
abstract Path2D.Double getDecoratorPath (Figure f)
abstract double getDecoratorPathRadius (Figure f)
Detailed Description
This abstract class can be extended to implement a LineDecoration.
Author
Werner Randelshofer
Version
$Id$
Constructor & Destructor Documentation
AbstractLineDecoration()
org.jhotdraw.draw.decoration.AbstractLineDecoration.AbstractLineDecoration (boolean isFilled, boolean isStroked, boolean isSolid)
Constructs an arrow tip with the given angle and radius.
Member Function Documentation
draw()
void org.jhotdraw.draw.decoration.AbstractLineDecoration.draw (Graphics2D g, Figure f, Point2D.Double p1, Point2D.Double p2)
Draws the arrow tip in the direction specified by the given two Points. (template method)
Implements org.jhotdraw.draw.decoration.LineDecoration.
References org.jhotdraw.draw.figure.Figure.get(), org.jhotdraw.draw.AttributeKeys.getScaleFactorFromGraphics(), and org.jhotdraw.draw.AttributeKeys.getStroke().
getDecorationRadius()
double org.jhotdraw.draw.decoration.AbstractLineDecoration.getDecorationRadius (Figure f)
Returns the radius of the decorator. This is used to crop the end of the line, to prevent it from being drawn over the decorator.
Implements org.jhotdraw.draw.decoration.LineDecoration.
References org.jhotdraw.draw.figure.Figure.get(), and org.jhotdraw.draw.decoration.AbstractLineDecoration.getDecoratorPathRadius().
getDecoratorPath()
abstract Path2D.Double org.jhotdraw.draw.decoration.AbstractLineDecoration.getDecoratorPath (Figure f) abstract protected
Hook method to calculate the path of the decorator.
Reimplemented in org.jhotdraw.draw.decoration.PerpendicularBar, and org.jhotdraw.draw.decoration.ArrowTip.
getDecoratorPathRadius()
abstract double org.jhotdraw.draw.decoration.AbstractLineDecoration.getDecoratorPathRadius (Figure f) abstract protected
Hook method to calculate the radius of the decorator path.
Reimplemented in org.jhotdraw.draw.decoration.PerpendicularBar, and org.jhotdraw.draw.decoration.ArrowTip.
Referenced by org.jhotdraw.draw.decoration.AbstractLineDecoration.getDecorationRadius().
getDrawingArea()
Rectangle2D.Double org.jhotdraw.draw.decoration.AbstractLineDecoration.getDrawingArea (Figure f, Point2D.Double p1, Point2D.Double p2)
Returns the drawing area of the decorator.
Implements org.jhotdraw.draw.decoration.LineDecoration.
References org.jhotdraw.draw.figure.Figure.get().
isFilled()
boolean org.jhotdraw.draw.decoration.AbstractLineDecoration.isFilled () protected
Referenced by org.jhotdraw.draw.decoration.ArrowTip.write().
isSolid()
boolean org.jhotdraw.draw.decoration.AbstractLineDecoration.isSolid () protected
Referenced by org.jhotdraw.draw.decoration.ArrowTip.write().
isStroked()
boolean org.jhotdraw.draw.decoration.AbstractLineDecoration.isStroked () protected
Referenced by org.jhotdraw.draw.decoration.ArrowTip.getDecoratorPath(), org.jhotdraw.draw.decoration.ArrowTip.getDecoratorPathRadius(), and org.jhotdraw.draw.decoration.ArrowTip.write().
setFilled()
void org.jhotdraw.draw.decoration.AbstractLineDecoration.setFilled (boolean b) protected
Referenced by org.jhotdraw.draw.decoration.ArrowTip.read().
setSolid()
void org.jhotdraw.draw.decoration.AbstractLineDecoration.setSolid (boolean b) protected
Referenced by org.jhotdraw.draw.decoration.ArrowTip.read().
setStroked()
void org.jhotdraw.draw.decoration.AbstractLineDecoration.setStroked (boolean b) protected
Referenced by org.jhotdraw.draw.decoration.ArrowTip.read().
The documentation for this class was generated from the following file:
jhotdraw-core/src/main/java/org/jhotdraw/draw/decoration/AbstractLineDecoration.java