jhotdraw: org.jhotdraw.draw.event.SelectionComponentDisplayer Class Reference
org.jhotdraw.draw.event.SelectionComponentDisplayer Class Reference
Public Member Functions
SelectionComponentDisplayer (DrawingEditor editor, JComponent component)
void propertyChange (PropertyChangeEvent evt)
void selectionChanged (FigureSelectionEvent evt)
void updateVisibility ()
void dispose ()
void setMinSelectionCount (int newValue)
void setVisibleIfCreationTool (boolean newValue)
Protected Member Functions
JComponent getComponent ()
Protected Attributes
DrawingView view
DrawingEditor editor
WeakReference< JComponent > weakRef
int minSelectionCount = 1
boolean isVisibleIfCreationTool = true
Detailed Description
Calls setVisible(true/false) on components, which show attributes of the drawing editor and of its views based on the current selection.
Holds a
WeakReference
on the component. Automatically disposes itself if the component no longer exists.
Author
Werner Randelshofer
Version
$Id$
Constructor & Destructor Documentation
SelectionComponentDisplayer()
org.jhotdraw.draw.event.SelectionComponentDisplayer.SelectionComponentDisplayer (DrawingEditor editor, JComponent component)
References org.jhotdraw.draw.DrawingView.addFigureSelectionListener(), org.jhotdraw.draw.DrawingEditor.addPropertyChangeListener(), org.jhotdraw.draw.DrawingView.addPropertyChangeListener(), org.jhotdraw.draw.event.SelectionComponentDisplayer.editor, org.jhotdraw.draw.DrawingEditor.getActiveView(), org.jhotdraw.draw.event.SelectionComponentDisplayer.updateVisibility(), and org.jhotdraw.draw.event.SelectionComponentDisplayer.view.
Member Function Documentation
dispose()
void org.jhotdraw.draw.event.SelectionComponentDisplayer.dispose ()
References org.jhotdraw.draw.event.SelectionComponentDisplayer.editor, org.jhotdraw.draw.DrawingView.removeFigureSelectionListener(), org.jhotdraw.draw.DrawingEditor.removePropertyChangeListener(), org.jhotdraw.draw.DrawingView.removePropertyChangeListener(), and org.jhotdraw.draw.event.SelectionComponentDisplayer.view.
Referenced by org.jhotdraw.draw.event.SelectionComponentDisplayer.updateVisibility().
getComponent()
JComponent org.jhotdraw.draw.event.SelectionComponentDisplayer.getComponent () protected
References org.jhotdraw.draw.event.SelectionComponentDisplayer.weakRef.
propertyChange()
void org.jhotdraw.draw.event.SelectionComponentDisplayer.propertyChange (PropertyChangeEvent evt)
References org.jhotdraw.draw.DrawingEditor.ACTIVE_VIEW_PROPERTY, org.jhotdraw.draw.DrawingView.addFigureSelectionListener(), org.jhotdraw.draw.DrawingView.addPropertyChangeListener(), org.jhotdraw.draw.DrawingView.removeFigureSelectionListener(), org.jhotdraw.draw.DrawingView.removePropertyChangeListener(), org.jhotdraw.draw.DrawingEditor.TOOL_PROPERTY, org.jhotdraw.draw.event.SelectionComponentDisplayer.updateVisibility(), and org.jhotdraw.draw.event.SelectionComponentDisplayer.view.
selectionChanged()
void org.jhotdraw.draw.event.SelectionComponentDisplayer.selectionChanged (FigureSelectionEvent evt)
Implements org.jhotdraw.draw.event.FigureSelectionListener.
References org.jhotdraw.draw.event.SelectionComponentDisplayer.updateVisibility().
setMinSelectionCount()
void org.jhotdraw.draw.event.SelectionComponentDisplayer.setMinSelectionCount (int newValue)
References org.jhotdraw.draw.event.SelectionComponentDisplayer.minSelectionCount, and org.jhotdraw.draw.event.SelectionComponentDisplayer.updateVisibility().
setVisibleIfCreationTool()
void org.jhotdraw.draw.event.SelectionComponentDisplayer.setVisibleIfCreationTool (boolean newValue)
References org.jhotdraw.draw.event.SelectionComponentDisplayer.isVisibleIfCreationTool.
updateVisibility()
void org.jhotdraw.draw.event.SelectionComponentDisplayer.updateVisibility ()
References org.jhotdraw.draw.event.SelectionComponentDisplayer.dispose(), org.jhotdraw.draw.event.SelectionComponentDisplayer.editor, org.jhotdraw.draw.DrawingEditor.getActiveView(), org.jhotdraw.draw.DrawingView.getSelectionCount(), org.jhotdraw.draw.DrawingEditor.getTool(), org.jhotdraw.draw.event.SelectionComponentDisplayer.isVisibleIfCreationTool, org.jhotdraw.draw.event.SelectionComponentDisplayer.minSelectionCount, and org.jhotdraw.draw.event.SelectionComponentDisplayer.weakRef.
Referenced by org.jhotdraw.draw.event.SelectionComponentDisplayer.propertyChange(), org.jhotdraw.draw.event.SelectionComponentDisplayer.selectionChanged(), org.jhotdraw.draw.event.SelectionComponentDisplayer.SelectionComponentDisplayer(), and org.jhotdraw.draw.event.SelectionComponentDisplayer.setMinSelectionCount().
Member Data Documentation
editor
DrawingEditor org.jhotdraw.draw.event.SelectionComponentDisplayer.editor protected
Referenced by org.jhotdraw.draw.event.SelectionComponentDisplayer.dispose(), org.jhotdraw.draw.event.SelectionComponentDisplayer.SelectionComponentDisplayer(), and org.jhotdraw.draw.event.SelectionComponentDisplayer.updateVisibility().
isVisibleIfCreationTool
boolean org.jhotdraw.draw.event.SelectionComponentDisplayer.isVisibleIfCreationTool = true protected
Referenced by org.jhotdraw.draw.event.SelectionComponentDisplayer.setVisibleIfCreationTool(), and org.jhotdraw.draw.event.SelectionComponentDisplayer.updateVisibility().
minSelectionCount
int org.jhotdraw.draw.event.SelectionComponentDisplayer.minSelectionCount = 1 protected
Referenced by org.jhotdraw.draw.event.SelectionComponentDisplayer.setMinSelectionCount(), and org.jhotdraw.draw.event.SelectionComponentDisplayer.updateVisibility().
view
DrawingView org.jhotdraw.draw.event.SelectionComponentDisplayer.view protected
Referenced by org.jhotdraw.draw.event.SelectionComponentDisplayer.dispose(), org.jhotdraw.draw.event.SelectionComponentDisplayer.propertyChange(), and org.jhotdraw.draw.event.SelectionComponentDisplayer.SelectionComponentDisplayer().
weakRef
WeakReference<JComponent> org.jhotdraw.draw.event.SelectionComponentDisplayer.weakRef protected
Referenced by org.jhotdraw.draw.event.SelectionComponentDisplayer.getComponent(), and org.jhotdraw.draw.event.SelectionComponentDisplayer.updateVisibility().
The documentation for this class was generated from the following file:
jhotdraw-core/src/main/java/org/jhotdraw/draw/event/SelectionComponentDisplayer.java