jhotdraw: org.jhotdraw.draw.layouter.LocatorLayouter Class Reference
org.jhotdraw.draw.layouter.LocatorLayouter Class Reference
Public Member Functions
LocatorLayouter ()
Rectangle2D.Double calculateLayout (CompositeFigure compositeFigure, Point2D.Double anchor, Point2D.Double lead)
Rectangle2D.Double layout (CompositeFigure compositeFigure, Point2D.Double anchor, Point2D.Double lead)
Static Public Attributes
static final AttributeKey< Locator > LAYOUT_LOCATOR = new AttributeKey<Locator>("layoutLocator", Locator.class, null)
Detailed Description
A layouter which lays out all children of a CompositeFigure according to their LayoutLocator property..
Author
Werner Randelshofer
Version
$Id$
Constructor & Destructor Documentation
LocatorLayouter()
org.jhotdraw.draw.layouter.LocatorLayouter.LocatorLayouter ()
Creates a new instance.
Member Function Documentation
calculateLayout()
Rectangle2D.Double org.jhotdraw.draw.layouter.LocatorLayouter.calculateLayout (CompositeFigure compositeFigure, Point2D.Double anchor, Point2D.Double lead)
Calculate the layout for the figure and all its subelements. The layout is not actually performed but just its dimensions are calculated.
Parameters
anchor start point for the layout
lead minimum lead point for the layout
Implements org.jhotdraw.draw.layouter.Layouter.
References org.jhotdraw.draw.figure.CompositeFigure.getChildren(), and org.jhotdraw.draw.locator.Locator.locate().
layout()
Rectangle2D.Double org.jhotdraw.draw.layouter.LocatorLayouter.layout (CompositeFigure compositeFigure, Point2D.Double anchor, Point2D.Double lead)
Method which lays out a figure. It is called by the figure if a layout task is to be performed. Implementing classes specify a certain layout algorithm in this method.
Parameters
anchor start point for the layout
lead minimum lead point for the layout
Implements org.jhotdraw.draw.layouter.Layouter.
References org.jhotdraw.draw.figure.CompositeFigure.getChildren(), and org.jhotdraw.draw.locator.Locator.locate().
Member Data Documentation
LAYOUT_LOCATOR
final AttributeKey<Locator> org.jhotdraw.draw.layouter.LocatorLayouter.LAYOUT_LOCATOR = new AttributeKey<Locator>("layoutLocator", Locator.class, null) static
LayoutLocator property used by the children to specify their location relative to the compositeFigure.
The documentation for this class was generated from the following file:
jhotdraw-core/src/main/java/org/jhotdraw/draw/layouter/LocatorLayouter.java