jhotdraw: org.jhotdraw.draw.connector.AbstractConnector Class Reference
org.jhotdraw.draw.connector.AbstractConnector Class Reference
Public Member Functions
AbstractConnector ()
AbstractConnector (Figure owner)
void setConnectToDecorator (boolean newValue)
boolean isConnectToDecorator ()
boolean contains (Point2D.Double p)
Point2D.Double findStart (ConnectionFigure connection)
Point2D.Double findEnd (ConnectionFigure connection)
Figure getOwner ()
Object clone ()
void updateStartLocation (Point2D.Double p)
void updateEndLocation (Point2D.Double p)
Point2D.Double getAnchor ()
void updateAnchor (Point2D.Double p)
Rectangle2D.Double getBounds ()
void read (DOMInput in) throws IOException
void write (DOMOutput out) throws IOException
Rectangle2D.Double getDrawingArea ()
void draw (Graphics2D g)
Protected Member Functions
final Figure getConnectorTarget (Figure f)
Point2D.Double findPoint (ConnectionFigure connection)
void setOwner (Figure newValue)
Detailed Description
This abstract class can be extended to implement a Connector.
See also
Connector
Author
Werner Randelshofer
Version
$Id$
Constructor & Destructor Documentation
AbstractConnector() [1/2]
org.jhotdraw.draw.connector.AbstractConnector.AbstractConnector ()
Constructs a connector that has no owner. It is only used internally to resurrect a connectors from a StorableOutput. It should never be called directly.
Referenced by org.jhotdraw.draw.connector.AbstractConnector.clone().
AbstractConnector() [2/2]
org.jhotdraw.draw.connector.AbstractConnector.AbstractConnector (Figure owner)
Constructs a connector with the given owner figure.
Member Function Documentation
clone()
Object org.jhotdraw.draw.connector.AbstractConnector.clone ()
Returns a clone of the Connection.
Implements org.jhotdraw.draw.connector.Connector.
References org.jhotdraw.draw.connector.AbstractConnector.AbstractConnector(), and org.jhotdraw.draw.connector.AbstractConnector.clone().
Referenced by org.jhotdraw.draw.connector.AbstractConnector.clone().
contains()
boolean org.jhotdraw.draw.connector.AbstractConnector.contains (Point2D.Double p)
Tests if a point is contained in the connector. This implementation tests if the point is contained by the figure object, which owns this connector.
Implements org.jhotdraw.draw.connector.Connector.
Reimplemented in org.jhotdraw.draw.connector.LocatorConnector.
References org.jhotdraw.draw.figure.Figure.contains(), and org.jhotdraw.draw.connector.AbstractConnector.getOwner().
draw()
void org.jhotdraw.draw.connector.AbstractConnector.draw (Graphics2D g)
Draws the connector.
Implements org.jhotdraw.draw.connector.Connector.
Reimplemented in org.jhotdraw.draw.connector.StickyRectangleConnector.
References org.jhotdraw.draw.connector.AbstractConnector.getAnchor().
findEnd()
Point2D.Double org.jhotdraw.draw.connector.AbstractConnector.findEnd (ConnectionFigure connection)
Finds the end point for the connection.
Implements org.jhotdraw.draw.connector.Connector.
Reimplemented in org.jhotdraw.draw.connector.ChopRectangleConnector.
References org.jhotdraw.draw.connector.AbstractConnector.findPoint().
findPoint()
Point2D.Double org.jhotdraw.draw.connector.AbstractConnector.findPoint (ConnectionFigure connection) protected
Gets the connection point. Override when the connector does not need to distinguish between the start and end point of a connection.
References org.jhotdraw.draw.connector.AbstractConnector.getBounds().
Referenced by org.jhotdraw.draw.connector.AbstractConnector.findEnd(), and org.jhotdraw.draw.connector.AbstractConnector.findStart().
findStart()
Point2D.Double org.jhotdraw.draw.connector.AbstractConnector.findStart (ConnectionFigure connection)
Finds the start point for the connection.
Implements org.jhotdraw.draw.connector.Connector.
Reimplemented in org.jhotdraw.draw.connector.ChopRectangleConnector.
References org.jhotdraw.draw.connector.AbstractConnector.findPoint().
getAnchor()
Point2D.Double org.jhotdraw.draw.connector.AbstractConnector.getAnchor ()
Gets the anchor of the connector. This is a point at the center or at the bounds of the figure, where the start or the end point will most likely be attached. The purpose of this method is to give the user a hint, where the connector will most likely be attached to the owner of the connector.
Implements org.jhotdraw.draw.connector.Connector.
Reimplemented in org.jhotdraw.draw.connector.StickyRectangleConnector.
References org.jhotdraw.draw.connector.AbstractConnector.getBounds().
Referenced by org.jhotdraw.draw.connector.AbstractConnector.draw(), and org.jhotdraw.draw.connector.AbstractConnector.getDrawingArea().
getBounds()
Rectangle2D.Double org.jhotdraw.draw.connector.AbstractConnector.getBounds ()
Gets the bounds of the connector. This usually are the bounds of the Figure which owns the Connector. The bounds can differ from the Figure bounds, if the Connector connects to a specific region of the Figure.
Implements org.jhotdraw.draw.connector.Connector.
Reimplemented in org.jhotdraw.draw.connector.LocatorConnector.
References org.jhotdraw.draw.figure.Figure.getBounds(), and org.jhotdraw.draw.connector.AbstractConnector.getOwner().
Referenced by org.jhotdraw.draw.connector.StickyRectangleConnector.draw(), org.jhotdraw.draw.connector.AbstractConnector.findPoint(), org.jhotdraw.draw.connector.AbstractConnector.getAnchor(), and org.jhotdraw.draw.connector.StickyRectangleConnector.getAnchor().
getConnectorTarget()
final Figure org.jhotdraw.draw.connector.AbstractConnector.getConnectorTarget (Figure f) protected
Referenced by org.jhotdraw.draw.connector.ChopBezierConnector.chop(), org.jhotdraw.draw.connector.ChopDiamondConnector.chop(), org.jhotdraw.draw.connector.ChopEllipseConnector.chop(), org.jhotdraw.draw.connector.ChopRectangleConnector.chop(), org.jhotdraw.draw.connector.ChopRoundRectangleConnector.chop(), org.jhotdraw.draw.connector.ChopTriangleConnector.chop(), org.jhotdraw.draw.connector.ChopRectangleConnector.findEnd(), and org.jhotdraw.draw.connector.ChopRectangleConnector.findStart().
getDrawingArea()
Rectangle2D.Double org.jhotdraw.draw.connector.AbstractConnector.getDrawingArea ()
Gets the drawing area of the connector.
Implements org.jhotdraw.draw.connector.Connector.
References org.jhotdraw.draw.connector.AbstractConnector.getAnchor().
getOwner()
Figure org.jhotdraw.draw.connector.AbstractConnector.getOwner ()
Gets the connector's owner.
Implements org.jhotdraw.draw.connector.Connector.
Referenced by org.jhotdraw.draw.connector.AbstractConnector.contains(), org.jhotdraw.draw.connector.StickyRectangleConnector.getAnchor(), org.jhotdraw.draw.connector.AbstractConnector.getBounds(), org.jhotdraw.draw.connector.LocatorConnector.getBounds(), org.jhotdraw.draw.connector.LocatorConnector.locate(), org.jhotdraw.draw.connector.StickyRectangleConnector.updateAnchor(), and org.jhotdraw.draw.connector.AbstractConnector.write().
isConnectToDecorator()
boolean org.jhotdraw.draw.connector.AbstractConnector.isConnectToDecorator ()
read()
void org.jhotdraw.draw.connector.AbstractConnector.read (DOMInput in) throws IOException
Reimplemented in org.jhotdraw.draw.connector.StickyRectangleConnector, and org.jhotdraw.draw.connector.LocatorConnector.
setConnectToDecorator()
void org.jhotdraw.draw.connector.AbstractConnector.setConnectToDecorator (boolean newValue)
setOwner()
void org.jhotdraw.draw.connector.AbstractConnector.setOwner (Figure newValue) protected
Sets the connector's owner.
updateAnchor()
void org.jhotdraw.draw.connector.AbstractConnector.updateAnchor (Point2D.Double p)
Updates the anchor of the connector. This method is called when the user manually changes the end point of the ConnectionFigure. The Connector uses this as a hint for choosing a new anchor position.
Implements org.jhotdraw.draw.connector.Connector.
Reimplemented in org.jhotdraw.draw.connector.StickyRectangleConnector.
updateEndLocation()
void org.jhotdraw.draw.connector.AbstractConnector.updateEndLocation (Point2D.Double p)
This is called, when the end location of the connection has been moved by the user. The user has this probably done, to adjust the layout. The connector may use this as a hint to improve the results for the next call to findStart.
updateStartLocation()
void org.jhotdraw.draw.connector.AbstractConnector.updateStartLocation (Point2D.Double p)
This is called, when the start location of the connection has been moved by the user. The user has this probably done, to adjust the layout. The connector may use this as a hint to improve the results for the next call to findEnd.
write()
void org.jhotdraw.draw.connector.AbstractConnector.write (DOMOutput out) throws IOException
Reimplemented in org.jhotdraw.draw.connector.StickyRectangleConnector, and org.jhotdraw.draw.connector.LocatorConnector.
References org.jhotdraw.draw.connector.AbstractConnector.getOwner().
The documentation for this class was generated from the following file:
jhotdraw-core/src/main/java/org/jhotdraw/draw/connector/AbstractConnector.java