jhotdraw: org.jhotdraw.draw.handle.AbstractHandle Class Reference
org.jhotdraw.draw.handle.AbstractHandle Class Reference abstract
Public Member Functions
AbstractHandle (Figure owner)
void addHandleListener (HandleListener l)
void removeHandleListener (HandleListener l)
Figure getOwner ()
void setView (DrawingView view)
DrawingView getView ()
DrawingEditor getEditor ()
void draw (Graphics2D g)
boolean contains (Point p)
void invalidate ()
void dispose ()
void areaInvalidated (FigureEvent evt)
void figureAdded (FigureEvent e)
void figureRemoved (FigureEvent e)
void figureRequestRemove (FigureEvent e)
void figureChanged (FigureEvent evt)
Cursor getCursor ()
boolean isCombinableWith (Handle handle)
void keyTyped (KeyEvent evt)
void keyReleased (KeyEvent evt)
void keyPressed (KeyEvent evt)
final Rectangle getBounds ()
Rectangle getDrawingArea ()
void trackDoubleClick (Point p, int modifiersEx)
void attributeChanged (FigureEvent e)
void viewTransformChanged ()
Collection< Handle > createSecondaryHandles ()
String getToolTipText (Point p)
void setToolTipText (String newValue)
void figureHandlesChanged (FigureEvent e)
Public Member Functions inherited from org.jhotdraw.draw.handle.Handle
void trackStart (Point anchor, int modifiersEx)
void trackStep (Point anchor, Point lead, int modifiersEx)
void trackEnd (Point anchor, Point lead, int modifiersEx)
Protected Member Functions
int getHandlesize ()
void fireAreaInvalidated (Rectangle invalidatedArea)
void fireUndoableEditHappened (UndoableEdit edit)
void fireHandleRequestRemove (Rectangle invalidatedArea)
void fireHandleRequestSecondaryHandles ()
void drawCircle (Graphics2D g, Color fill, Color stroke)
void drawRectangle (Graphics2D g, Color fill, Color stroke)
void drawDiamond (Graphics2D g, Color fill, Color stroke)
abstract Rectangle basicGetBounds ()
void updateBounds ()
Protected Attributes
DrawingView view
EventListenerList listenerList = new EventListenerList()
Detailed Description
This abstract class can be extended to implement a Handle.
Author
Werner Randelshofer
Version
$Id$
Constructor & Destructor Documentation
AbstractHandle()
org.jhotdraw.draw.handle.AbstractHandle.AbstractHandle (Figure owner)
Creates a new instance.
References org.jhotdraw.draw.figure.Figure.addFigureListener().
Member Function Documentation
addHandleListener()
void org.jhotdraw.draw.handle.AbstractHandle.addHandleListener (HandleListener l)
Adds a listener for this handle.
Implements org.jhotdraw.draw.handle.Handle.
References org.jhotdraw.draw.handle.AbstractHandle.listenerList.
areaInvalidated()
void org.jhotdraw.draw.handle.AbstractHandle.areaInvalidated (FigureEvent evt)
Sent when a region used by the figure needs to be repainted. The implementation of this method assumes that the handle is located on the bounds of the figure or inside the figure. If the handle is located elsewhere this method must be reimpleted by the subclass.
Implements org.jhotdraw.draw.event.FigureListener.
References org.jhotdraw.draw.handle.AbstractHandle.updateBounds().
attributeChanged()
void org.jhotdraw.draw.handle.AbstractHandle.attributeChanged (FigureEvent e)
Sent when an attribute of the figure has changed.
Implements org.jhotdraw.draw.event.FigureListener.
basicGetBounds()
abstract Rectangle org.jhotdraw.draw.handle.AbstractHandle.basicGetBounds () abstract protected
Reimplemented in org.jhotdraw.draw.handle.TextOverflowHandle, org.jhotdraw.draw.handle.RoundRectangleRadiusHandle, org.jhotdraw.draw.handle.OrientationHandle, org.jhotdraw.draw.handle.LocatorHandle, org.jhotdraw.draw.handle.FontSizeHandle, org.jhotdraw.draw.handle.ConnectorHandle, org.jhotdraw.draw.handle.BoundsOutlineHandle, org.jhotdraw.draw.handle.BezierScaleHandle, org.jhotdraw.draw.handle.BezierOutlineHandle, org.jhotdraw.draw.handle.BezierNodeHandle, org.jhotdraw.draw.handle.BezierControlPointHandle, org.jhotdraw.draw.handle.AbstractRotateHandle, and org.jhotdraw.draw.handle.AbstractConnectionHandle.
Referenced by org.jhotdraw.draw.handle.AbstractHandle.getBounds(), and org.jhotdraw.draw.handle.AbstractHandle.updateBounds().
contains()
boolean org.jhotdraw.draw.handle.AbstractHandle.contains (Point p)
Tests if a point is contained in the handle.
Implements org.jhotdraw.draw.handle.Handle.
Reimplemented in org.jhotdraw.draw.handle.TextOverflowHandle, org.jhotdraw.draw.handle.BoundsOutlineHandle, and org.jhotdraw.draw.handle.BezierOutlineHandle.
References org.jhotdraw.draw.handle.AbstractHandle.getBounds().
createSecondaryHandles()
Collection<Handle> org.jhotdraw.draw.handle.AbstractHandle.createSecondaryHandles ()
Creates secondary handles.
Implements org.jhotdraw.draw.handle.Handle.
Reimplemented in org.jhotdraw.draw.handle.BezierNodeHandle, and org.jhotdraw.draw.handle.AbstractConnectionHandle.
dispose()
void org.jhotdraw.draw.handle.AbstractHandle.dispose ()
Disposes the resources acquired by the handler.
Implements org.jhotdraw.draw.handle.Handle.
Reimplemented in org.jhotdraw.draw.handle.BezierNodeHandle, and org.jhotdraw.draw.handle.BezierControlPointHandle.
References org.jhotdraw.draw.figure.Figure.removeFigureListener().
draw()
void org.jhotdraw.draw.handle.AbstractHandle.draw (Graphics2D g)
Draws this handle.
Implements org.jhotdraw.draw.handle.Handle.
Reimplemented in org.jhotdraw.draw.handle.TextOverflowHandle, org.jhotdraw.draw.handle.RoundRectangleRadiusHandle, org.jhotdraw.draw.handle.OrientationHandle, org.jhotdraw.draw.handle.NullHandle, org.jhotdraw.draw.handle.MoveHandle, org.jhotdraw.draw.handle.FontSizeHandle, org.jhotdraw.draw.handle.ConnectorHandle, org.jhotdraw.draw.handle.CloseHandle, org.jhotdraw.draw.handle.BoundsOutlineHandle, org.jhotdraw.draw.handle.BezierScaleHandle, org.jhotdraw.draw.handle.BezierOutlineHandle, org.jhotdraw.draw.handle.BezierNodeHandle, org.jhotdraw.draw.handle.BezierControlPointHandle, org.jhotdraw.draw.handle.AbstractRotateHandle, and org.jhotdraw.draw.handle.AbstractConnectionHandle.
References org.jhotdraw.draw.handle.AbstractHandle.drawCircle(), org.jhotdraw.draw.handle.AbstractHandle.getEditor(), org.jhotdraw.draw.handle.HandleAttributeKeys.HANDLE_FILL_COLOR, and org.jhotdraw.draw.handle.HandleAttributeKeys.HANDLE_STROKE_COLOR.
drawCircle()
void org.jhotdraw.draw.handle.AbstractHandle.drawCircle (Graphics2D g, Color fill, Color stroke) protected
References org.jhotdraw.draw.handle.AbstractHandle.getBounds(), and org.jhotdraw.draw.handle.AbstractHandle.getView().
Referenced by org.jhotdraw.draw.handle.AbstractConnectionHandle.draw(), org.jhotdraw.draw.handle.AbstractHandle.draw(), org.jhotdraw.draw.handle.AbstractRotateHandle.draw(), org.jhotdraw.draw.handle.BezierControlPointHandle.draw(), org.jhotdraw.draw.handle.BezierNodeHandle.draw(), org.jhotdraw.draw.handle.BezierScaleHandle.draw(), and org.jhotdraw.draw.handle.ConnectorHandle.draw().
drawDiamond()
void org.jhotdraw.draw.handle.AbstractHandle.drawDiamond (Graphics2D g, Color fill, Color stroke) protected
References org.jhotdraw.draw.handle.AbstractHandle.getBounds(), and org.jhotdraw.draw.handle.AbstractHandle.getView().
Referenced by org.jhotdraw.draw.handle.BezierNodeHandle.draw(), org.jhotdraw.draw.handle.FontSizeHandle.draw(), org.jhotdraw.draw.handle.OrientationHandle.draw(), and org.jhotdraw.draw.handle.RoundRectangleRadiusHandle.draw().
drawRectangle()
void org.jhotdraw.draw.handle.AbstractHandle.drawRectangle (Graphics2D g, Color fill, Color stroke) protected
References org.jhotdraw.draw.handle.AbstractHandle.getBounds(), and org.jhotdraw.draw.handle.AbstractHandle.getView().
Referenced by org.jhotdraw.draw.handle.BezierNodeHandle.draw(), org.jhotdraw.draw.handle.CloseHandle.draw(), org.jhotdraw.draw.handle.MoveHandle.draw(), org.jhotdraw.draw.handle.NullHandle.draw(), and org.jhotdraw.draw.handle.TextOverflowHandle.draw().
figureAdded()
void org.jhotdraw.draw.handle.AbstractHandle.figureAdded (FigureEvent e)
Sent when a figure was added.
Implements org.jhotdraw.draw.event.FigureListener.
figureChanged()
void org.jhotdraw.draw.handle.AbstractHandle.figureChanged (FigureEvent evt)
Sent when the bounds or shape of a figure has changed.
Implements org.jhotdraw.draw.event.FigureListener.
References org.jhotdraw.draw.handle.AbstractHandle.updateBounds().
figureHandlesChanged()
void org.jhotdraw.draw.handle.AbstractHandle.figureHandlesChanged (FigureEvent e)
Sent when handles of a Figure have been added, removed or replaced.
DrawingViews listen to this event to repopulate the Handles.
A Figure should not fire this event, if just the state or the location of Handle has changed.
Implements org.jhotdraw.draw.event.FigureListener.
figureRemoved()
void org.jhotdraw.draw.handle.AbstractHandle.figureRemoved (FigureEvent e)
Sent when a figure was removed.
Implements org.jhotdraw.draw.event.FigureListener.
figureRequestRemove()
void org.jhotdraw.draw.handle.AbstractHandle.figureRequestRemove (FigureEvent e)
Sent when a figure requests to be removed.
Implements org.jhotdraw.draw.event.FigureListener.
fireAreaInvalidated()
void org.jhotdraw.draw.handle.AbstractHandle.fireAreaInvalidated (Rectangle invalidatedArea) protected
Notify all listenerList that have registered interest for notification on this event type.
References org.jhotdraw.draw.handle.AbstractHandle.listenerList.
Referenced by org.jhotdraw.draw.handle.AbstractRotateHandle.trackEnd(), org.jhotdraw.draw.handle.CloseHandle.trackEnd(), org.jhotdraw.draw.handle.ConnectorHandle.trackEnd(), org.jhotdraw.draw.handle.CloseHandle.trackStart(), org.jhotdraw.draw.handle.CloseHandle.trackStep(), org.jhotdraw.draw.handle.ConnectorHandle.trackStep(), and org.jhotdraw.draw.handle.AbstractHandle.updateBounds().
fireHandleRequestRemove()
void org.jhotdraw.draw.handle.AbstractHandle.fireHandleRequestRemove (Rectangle invalidatedArea) protected
Notify all listenerList that have registered interest for notification on this event type.
References org.jhotdraw.draw.handle.AbstractHandle.listenerList.
Referenced by org.jhotdraw.draw.handle.BezierNodeHandle.keyPressed(), and org.jhotdraw.draw.handle.BezierNodeHandle.trackDoubleClick().
fireHandleRequestSecondaryHandles()
void org.jhotdraw.draw.handle.AbstractHandle.fireHandleRequestSecondaryHandles () protected
Notify all listenerList that have registered interest for notification on this event type.
References org.jhotdraw.draw.handle.AbstractHandle.listenerList.
Referenced by org.jhotdraw.draw.handle.AbstractConnectionHandle.trackEnd(), org.jhotdraw.draw.handle.BezierControlPointHandle.trackEnd(), org.jhotdraw.draw.handle.BezierNodeHandle.trackEnd(), org.jhotdraw.draw.handle.AbstractConnectionHandle.trackStart(), and org.jhotdraw.draw.handle.BezierNodeHandle.trackStart().
fireUndoableEditHappened()
void org.jhotdraw.draw.handle.AbstractHandle.fireUndoableEditHappened (UndoableEdit edit) protected
Notify all listenerList that have registered interest for notification on this event type.
References org.jhotdraw.draw.Drawing.fireUndoableEditHappened(), org.jhotdraw.draw.DrawingView.getDrawing(), and org.jhotdraw.draw.handle.AbstractHandle.view.
Referenced by org.jhotdraw.draw.handle.AbstractRotateHandle.keyPressed(), org.jhotdraw.draw.handle.BezierNodeHandle.keyPressed(), org.jhotdraw.draw.handle.FontSizeHandle.keyPressed(), org.jhotdraw.draw.handle.MoveHandle.keyPressed(), org.jhotdraw.draw.handle.RoundRectangleRadiusHandle.keyPressed(), org.jhotdraw.draw.handle.BezierNodeHandle.trackDoubleClick(), org.jhotdraw.draw.handle.FontSizeHandle.trackEnd(), org.jhotdraw.draw.handle.MoveHandle.trackEnd(), org.jhotdraw.draw.handle.OrientationHandle.trackEnd(), and org.jhotdraw.draw.handle.RoundRectangleRadiusHandle.trackEnd().
getBounds()
final Rectangle org.jhotdraw.draw.handle.AbstractHandle.getBounds ()
Returns the bounding box of the handle. Note: The bounding box must be returned in the coordinate system of the DrawingView.
Implements org.jhotdraw.draw.handle.Handle.
References org.jhotdraw.draw.handle.AbstractHandle.basicGetBounds().
Referenced by org.jhotdraw.draw.handle.AbstractHandle.contains(), org.jhotdraw.draw.handle.CloseHandle.draw(), org.jhotdraw.draw.handle.AbstractHandle.drawCircle(), org.jhotdraw.draw.handle.AbstractHandle.drawDiamond(), org.jhotdraw.draw.handle.AbstractHandle.drawRectangle(), org.jhotdraw.draw.handle.AbstractHandle.getDrawingArea(), and org.jhotdraw.draw.handle.OrientationHandle.trackStart().
getCursor()
Cursor org.jhotdraw.draw.handle.AbstractHandle.getCursor ()
Returns a cursor for the handle.
Implements org.jhotdraw.draw.handle.Handle.
Reimplemented in org.jhotdraw.draw.handle.NullHandle, org.jhotdraw.draw.handle.MoveHandle, org.jhotdraw.draw.handle.FontSizeHandle, and org.jhotdraw.draw.handle.CloseHandle.
getDrawingArea()
Rectangle org.jhotdraw.draw.handle.AbstractHandle.getDrawingArea ()
Returns the drawing area of the handle. Note: The drawing area must be returned in the coordinate system of the DrawingView.
Implements org.jhotdraw.draw.handle.Handle.
Reimplemented in org.jhotdraw.draw.handle.ConnectorHandle.
References org.jhotdraw.draw.handle.AbstractHandle.getBounds().
Referenced by org.jhotdraw.draw.handle.BezierOutlineHandle.basicGetBounds(), org.jhotdraw.draw.handle.BezierNodeHandle.keyPressed(), org.jhotdraw.draw.handle.BezierNodeHandle.trackDoubleClick(), org.jhotdraw.draw.handle.AbstractRotateHandle.trackEnd(), org.jhotdraw.draw.handle.CloseHandle.trackEnd(), org.jhotdraw.draw.handle.CloseHandle.trackStart(), org.jhotdraw.draw.handle.CloseHandle.trackStep(), and org.jhotdraw.draw.handle.AbstractHandle.updateBounds().
getEditor()
DrawingEditor org.jhotdraw.draw.handle.AbstractHandle.getEditor ()
References org.jhotdraw.draw.DrawingView.getEditor(), and org.jhotdraw.draw.handle.AbstractHandle.view.
Referenced by org.jhotdraw.draw.handle.AbstractConnectionHandle.draw(), org.jhotdraw.draw.handle.AbstractHandle.draw(), org.jhotdraw.draw.handle.AbstractRotateHandle.draw(), org.jhotdraw.draw.handle.BezierControlPointHandle.draw(), org.jhotdraw.draw.handle.BezierNodeHandle.draw(), org.jhotdraw.draw.handle.BezierOutlineHandle.draw(), org.jhotdraw.draw.handle.BezierScaleHandle.draw(), org.jhotdraw.draw.handle.BoundsOutlineHandle.draw(), org.jhotdraw.draw.handle.ConnectorHandle.draw(), org.jhotdraw.draw.handle.FontSizeHandle.draw(), org.jhotdraw.draw.handle.MoveHandle.draw(), org.jhotdraw.draw.handle.NullHandle.draw(), org.jhotdraw.draw.handle.OrientationHandle.draw(), org.jhotdraw.draw.handle.RoundRectangleRadiusHandle.draw(), org.jhotdraw.draw.handle.TextOverflowHandle.draw(), and org.jhotdraw.draw.handle.AbstractHandle.getHandlesize().
getHandlesize()
int org.jhotdraw.draw.handle.AbstractHandle.getHandlesize () protected
Reimplemented in org.jhotdraw.draw.handle.CloseHandle.
References org.jhotdraw.draw.handle.AbstractHandle.getEditor(), org.jhotdraw.draw.DrawingEditor.getHandleAttribute(), and org.jhotdraw.draw.handle.HandleAttributeKeys.HANDLE_SIZE.
Referenced by org.jhotdraw.draw.handle.AbstractConnectionHandle.basicGetBounds(), org.jhotdraw.draw.handle.AbstractRotateHandle.basicGetBounds(), org.jhotdraw.draw.handle.BezierControlPointHandle.basicGetBounds(), org.jhotdraw.draw.handle.BezierNodeHandle.basicGetBounds(), org.jhotdraw.draw.handle.BezierScaleHandle.basicGetBounds(), org.jhotdraw.draw.handle.ConnectorHandle.basicGetBounds(), org.jhotdraw.draw.handle.FontSizeHandle.basicGetBounds(), org.jhotdraw.draw.handle.LocatorHandle.basicGetBounds(), org.jhotdraw.draw.handle.OrientationHandle.basicGetBounds(), org.jhotdraw.draw.handle.RoundRectangleRadiusHandle.basicGetBounds(), org.jhotdraw.draw.handle.TextOverflowHandle.basicGetBounds(), org.jhotdraw.draw.handle.ConnectorHandle.draw(), org.jhotdraw.draw.handle.ConnectorHandle.getDrawingArea(), and org.jhotdraw.draw.handle.RotateHandle.getOrigin().
getOwner()
Figure org.jhotdraw.draw.handle.AbstractHandle.getOwner ()
Returns the owner of this handle.
Implements org.jhotdraw.draw.handle.Handle.
Reimplemented in org.jhotdraw.draw.handle.TextOverflowHandle, org.jhotdraw.draw.handle.BezierOutlineHandle, org.jhotdraw.draw.handle.BezierNodeHandle, org.jhotdraw.draw.handle.BezierControlPointHandle, and org.jhotdraw.draw.handle.AbstractConnectionHandle.
Referenced by org.jhotdraw.draw.handle.BoundsOutlineHandle.basicGetBounds(), org.jhotdraw.draw.handle.BoundsOutlineHandle.draw(), org.jhotdraw.draw.handle.MoveHandle.draw(), org.jhotdraw.draw.handle.ConnectorHandle.findConnectableConnector(), org.jhotdraw.draw.handle.MoveHandle.getCursor(), org.jhotdraw.draw.handle.LocatorHandle.getLocation(), org.jhotdraw.draw.handle.LocatorHandle.getLocationOnDrawing(), org.jhotdraw.draw.handle.AbstractRotateHandle.getTransformedBounds(), org.jhotdraw.draw.handle.AbstractRotateHandle.keyPressed(), org.jhotdraw.draw.handle.FontSizeHandle.keyPressed(), org.jhotdraw.draw.handle.MoveHandle.keyPressed(), org.jhotdraw.draw.handle.RoundRectangleRadiusHandle.keyPressed(), org.jhotdraw.draw.handle.AbstractRotateHandle.trackEnd(), org.jhotdraw.draw.handle.BezierScaleHandle.trackEnd(), org.jhotdraw.draw.handle.CloseHandle.trackEnd(), org.jhotdraw.draw.handle.FontSizeHandle.trackEnd(), org.jhotdraw.draw.handle.MoveHandle.trackEnd(), org.jhotdraw.draw.handle.OrientationHandle.trackEnd(), org.jhotdraw.draw.handle.RoundRectangleRadiusHandle.trackEnd(), org.jhotdraw.draw.handle.AbstractRotateHandle.trackStart(), org.jhotdraw.draw.handle.FontSizeHandle.trackStart(), org.jhotdraw.draw.handle.OrientationHandle.trackStart(), org.jhotdraw.draw.handle.RoundRectangleRadiusHandle.trackStart(), org.jhotdraw.draw.handle.AbstractRotateHandle.trackStep(), org.jhotdraw.draw.handle.BezierScaleHandle.trackStep(), org.jhotdraw.draw.handle.FontSizeHandle.trackStep(), org.jhotdraw.draw.handle.MoveHandle.trackStep(), org.jhotdraw.draw.handle.OrientationHandle.trackStep(), and org.jhotdraw.draw.handle.RoundRectangleRadiusHandle.trackStep().
getToolTipText()
String org.jhotdraw.draw.handle.AbstractHandle.getToolTipText (Point p)
Returns a tooltip for the specified location. By default, AbstractHandle returns null.
Implements org.jhotdraw.draw.handle.Handle.
Reimplemented in org.jhotdraw.draw.handle.TextOverflowHandle, org.jhotdraw.draw.handle.RoundRectangleRadiusHandle, org.jhotdraw.draw.handle.FontSizeHandle, org.jhotdraw.draw.handle.BezierNodeHandle, org.jhotdraw.draw.handle.BezierControlPointHandle, org.jhotdraw.draw.handle.AbstractRotateHandle, and org.jhotdraw.draw.handle.AbstractConnectionHandle.
getView()
DrawingView org.jhotdraw.draw.handle.AbstractHandle.getView ()
References org.jhotdraw.draw.handle.AbstractHandle.view.
Referenced by org.jhotdraw.draw.handle.AbstractHandle.drawCircle(), org.jhotdraw.draw.handle.AbstractHandle.drawDiamond(), and org.jhotdraw.draw.handle.AbstractHandle.drawRectangle().
invalidate()
void org.jhotdraw.draw.handle.AbstractHandle.invalidate ()
Invalidates the handle. This method informs its listeners that its current display box is invalid and should be refreshed.
Implements org.jhotdraw.draw.handle.Handle.
Referenced by org.jhotdraw.draw.handle.AbstractRotateHandle.trackEnd(), and org.jhotdraw.draw.handle.AbstractHandle.viewTransformChanged().
isCombinableWith()
boolean org.jhotdraw.draw.handle.AbstractHandle.isCombinableWith (Handle handle)
Returns true, if the given handle is an instance of the same class or of a subclass of this handle,.
Implements org.jhotdraw.draw.handle.Handle.
Reimplemented in org.jhotdraw.draw.handle.ConnectorHandle, org.jhotdraw.draw.handle.AbstractConnectionHandle, org.jhotdraw.draw.handle.OrientationHandle, org.jhotdraw.draw.handle.BezierScaleHandle, org.jhotdraw.draw.handle.BezierNodeHandle, org.jhotdraw.draw.handle.BezierControlPointHandle, and org.jhotdraw.draw.handle.AbstractRotateHandle.
keyPressed()
void org.jhotdraw.draw.handle.AbstractHandle.keyPressed (KeyEvent evt)
Reimplemented in org.jhotdraw.draw.handle.RoundRectangleRadiusHandle, org.jhotdraw.draw.handle.MoveHandle, org.jhotdraw.draw.handle.FontSizeHandle, org.jhotdraw.draw.handle.BezierNodeHandle, org.jhotdraw.draw.handle.BezierControlPointHandle, and org.jhotdraw.draw.handle.AbstractRotateHandle.
keyReleased()
void org.jhotdraw.draw.handle.AbstractHandle.keyReleased (KeyEvent evt)
keyTyped()
void org.jhotdraw.draw.handle.AbstractHandle.keyTyped (KeyEvent evt)
removeHandleListener()
void org.jhotdraw.draw.handle.AbstractHandle.removeHandleListener (HandleListener l)
Removes a listener for this handle.
Implements org.jhotdraw.draw.handle.Handle.
References org.jhotdraw.draw.handle.AbstractHandle.listenerList.
setToolTipText()
void org.jhotdraw.draw.handle.AbstractHandle.setToolTipText (String newValue)
Changes the default tool tip text returned by AbstractHandle.
setView()
void org.jhotdraw.draw.handle.AbstractHandle.setView (DrawingView view)
Sets the view of the handle.
Implements org.jhotdraw.draw.handle.Handle.
References org.jhotdraw.draw.handle.AbstractHandle.view.
trackDoubleClick()
void org.jhotdraw.draw.handle.AbstractHandle.trackDoubleClick (Point p, int modifiersEx)
Tracks a double click.
Implements org.jhotdraw.draw.handle.Handle.
Reimplemented in org.jhotdraw.draw.handle.BezierNodeHandle.
updateBounds()
void org.jhotdraw.draw.handle.AbstractHandle.updateBounds () protected
References org.jhotdraw.draw.handle.AbstractHandle.basicGetBounds(), org.jhotdraw.draw.handle.AbstractHandle.fireAreaInvalidated(), and org.jhotdraw.draw.handle.AbstractHandle.getDrawingArea().
Referenced by org.jhotdraw.draw.handle.AbstractHandle.areaInvalidated(), org.jhotdraw.draw.handle.AbstractHandle.figureChanged(), and org.jhotdraw.draw.handle.OrientationHandle.trackStep().
viewTransformChanged()
void org.jhotdraw.draw.handle.AbstractHandle.viewTransformChanged ()
This method is invoked by the drawing view, when its transform has changed. This means, that DrawingView.viewToDrawing and DrawingView.drawingToView will return different values than they did before.
Implements org.jhotdraw.draw.handle.Handle.
References org.jhotdraw.draw.handle.AbstractHandle.invalidate().
Member Data Documentation
listenerList
EventListenerList org.jhotdraw.draw.handle.AbstractHandle.listenerList = new EventListenerList() protected
Referenced by org.jhotdraw.draw.handle.AbstractHandle.addHandleListener(), org.jhotdraw.draw.handle.AbstractHandle.fireAreaInvalidated(), org.jhotdraw.draw.handle.AbstractHandle.fireHandleRequestRemove(), org.jhotdraw.draw.handle.AbstractHandle.fireHandleRequestSecondaryHandles(), and org.jhotdraw.draw.handle.AbstractHandle.removeHandleListener().
view
DrawingView org.jhotdraw.draw.handle.AbstractHandle.view protected
Referenced by org.jhotdraw.draw.handle.AbstractConnectionHandle.basicGetBounds(), org.jhotdraw.draw.handle.BezierOutlineHandle.basicGetBounds(), org.jhotdraw.draw.handle.BoundsOutlineHandle.basicGetBounds(), org.jhotdraw.draw.handle.OrientationHandle.basicGetBounds(), org.jhotdraw.draw.handle.TextOverflowHandle.basicGetBounds(), org.jhotdraw.draw.handle.AbstractConnectionHandle.draw(), org.jhotdraw.draw.handle.BezierControlPointHandle.draw(), org.jhotdraw.draw.handle.BezierOutlineHandle.draw(), org.jhotdraw.draw.handle.BoundsOutlineHandle.draw(), org.jhotdraw.draw.handle.ConnectorHandle.draw(), org.jhotdraw.draw.handle.AbstractHandle.fireUndoableEditHappened(), org.jhotdraw.draw.handle.ConnectorHandle.getDrawingArea(), org.jhotdraw.draw.handle.AbstractHandle.getEditor(), org.jhotdraw.draw.handle.AbstractRotateHandle.getLocation(), org.jhotdraw.draw.handle.BezierControlPointHandle.getLocation(), org.jhotdraw.draw.handle.BezierNodeHandle.getLocation(), org.jhotdraw.draw.handle.BezierScaleHandle.getLocation(), org.jhotdraw.draw.handle.ConnectorHandle.getLocation(), org.jhotdraw.draw.handle.LocatorHandle.getLocation(), org.jhotdraw.draw.handle.RotateHandle.getOrigin(), org.jhotdraw.draw.handle.AbstractHandle.getView(), org.jhotdraw.draw.handle.BezierControlPointHandle.keyPressed(), org.jhotdraw.draw.handle.BezierNodeHandle.keyPressed(), org.jhotdraw.draw.handle.AbstractConnectionHandle.repaintConnectors(), org.jhotdraw.draw.handle.ConnectorHandle.repaintConnectors(), org.jhotdraw.draw.handle.AbstractHandle.setView(), org.jhotdraw.draw.handle.BezierNodeHandle.trackDoubleClick(), org.jhotdraw.draw.handle.AbstractConnectionHandle.trackEnd(), org.jhotdraw.draw.handle.AbstractRotateHandle.trackEnd(), org.jhotdraw.draw.handle.BezierControlPointHandle.trackEnd(), org.jhotdraw.draw.handle.BezierNodeHandle.trackEnd(), org.jhotdraw.draw.handle.BezierScaleHandle.trackEnd(), org.jhotdraw.draw.handle.ConnectorHandle.trackEnd(), org.jhotdraw.draw.handle.RoundRectangleRadiusHandle.trackEnd(), org.jhotdraw.draw.handle.AbstractRotateHandle.trackStart(), org.jhotdraw.draw.handle.BezierControlPointHandle.trackStart(), org.jhotdraw.draw.handle.BezierNodeHandle.trackStart(), org.jhotdraw.draw.handle.BezierScaleHandle.trackStart(), org.jhotdraw.draw.handle.ConnectorHandle.trackStart(), org.jhotdraw.draw.handle.MoveHandle.trackStart(), org.jhotdraw.draw.handle.OrientationHandle.trackStart(), org.jhotdraw.draw.handle.RoundRectangleRadiusHandle.trackStart(), org.jhotdraw.draw.handle.AbstractConnectionHandle.trackStep(), org.jhotdraw.draw.handle.AbstractRotateHandle.trackStep(), org.jhotdraw.draw.handle.BezierControlPointHandle.trackStep(), org.jhotdraw.draw.handle.BezierNodeHandle.trackStep(), org.jhotdraw.draw.handle.BezierScaleHandle.trackStep(), org.jhotdraw.draw.handle.ConnectorHandle.trackStep(), org.jhotdraw.draw.handle.FontSizeHandle.trackStep(), org.jhotdraw.draw.handle.MoveHandle.trackStep(), and org.jhotdraw.draw.handle.RoundRectangleRadiusHandle.trackStep().
The documentation for this class was generated from the following file:
jhotdraw-core/src/main/java/org/jhotdraw/draw/handle/AbstractHandle.java