jhotdraw: org.jhotdraw.draw.figure.AbstractFigureNGTest Class Reference
org.jhotdraw.draw.figure.AbstractFigureNGTest Class Reference
Classes
class AbstractFigureImpl
Public Member Functions
AbstractFigureNGTest ()
void setUpMethod () throws Exception
void tearDownMethod () throws Exception
void testChangedWithoutWillChange ()
void testWillChangeChangedEvents ()
Static Public Member Functions
static void setUpClass () throws Exception
static void tearDownClass () throws Exception
Detailed Description
Author
tw
Constructor & Destructor Documentation
AbstractFigureNGTest()
org.jhotdraw.draw.figure.AbstractFigureNGTest.AbstractFigureNGTest ()
Member Function Documentation
setUpClass()
static void org.jhotdraw.draw.figure.AbstractFigureNGTest.setUpClass () throws Exception static
setUpMethod()
void org.jhotdraw.draw.figure.AbstractFigureNGTest.setUpMethod () throws Exception
tearDownClass()
static void org.jhotdraw.draw.figure.AbstractFigureNGTest.tearDownClass () throws Exception static
tearDownMethod()
void org.jhotdraw.draw.figure.AbstractFigureNGTest.tearDownMethod () throws Exception
testChangedWithoutWillChange()
void org.jhotdraw.draw.figure.AbstractFigureNGTest.testChangedWithoutWillChange ()
References org.jhotdraw.draw.figure.AbstractFigure.changed().
testWillChangeChangedEvents()
void org.jhotdraw.draw.figure.AbstractFigureNGTest.testWillChangeChangedEvents ()
References org.jhotdraw.draw.figure.AbstractFigure.changed(), org.jhotdraw.draw.figure.AbstractFigure.getChangingDepth(), and org.jhotdraw.draw.figure.AbstractFigure.willChange().
The documentation for this class was generated from the following file:
jhotdraw-core/src/test/java/org/jhotdraw/draw/figure/AbstractFigureNGTest.java