jhotdraw: org.jhotdraw.draw.handle.ConnectionStartHandle Class Reference
org.jhotdraw.draw.handle.ConnectionStartHandle Class Reference
Public Member Functions
ConnectionStartHandle (ConnectionFigure owner)
Public Member Functions inherited from org.jhotdraw.draw.handle.AbstractConnectionHandle
ConnectionFigure getOwner ()
boolean isCombinableWith (Handle handle)
void trackStart (Point anchor, int modifiersEx)
void trackStep (Point anchor, Point lead, int modifiersEx)
void trackEnd (Point anchor, Point lead, int modifiersEx)
void draw (Graphics2D g)
final Collection< Handle > createSecondaryHandles ()
String getToolTipText (Point p)
void repaintConnectors ()
Public Member Functions inherited from org.jhotdraw.draw.handle.AbstractHandle
AbstractHandle (Figure owner)
void addHandleListener (HandleListener l)
void removeHandleListener (HandleListener l)
void setView (DrawingView view)
DrawingView getView ()
DrawingEditor getEditor ()
boolean contains (Point p)
void invalidate ()
void dispose ()
void areaInvalidated (FigureEvent evt)
void figureAdded (FigureEvent e)
void figureRemoved (FigureEvent e)
void figureRequestRemove (FigureEvent e)
void figureChanged (FigureEvent evt)
Cursor getCursor ()
void keyTyped (KeyEvent evt)
void keyReleased (KeyEvent evt)
void keyPressed (KeyEvent evt)
final Rectangle getBounds ()
Rectangle getDrawingArea ()
void trackDoubleClick (Point p, int modifiersEx)
void attributeChanged (FigureEvent e)
void viewTransformChanged ()
void setToolTipText (String newValue)
void figureHandlesChanged (FigureEvent e)
Protected Member Functions
void connect (Connector c)
void disconnect ()
Connector getTarget ()
void setLocation (Point2D.Double p)
Point2D.Double getLocation ()
boolean canConnect (Connector existingEnd, Connector targetEnd)
int getBezierNodeIndex ()
Protected Member Functions inherited from org.jhotdraw.draw.handle.AbstractConnectionHandle
AbstractConnectionHandle (ConnectionFigure owner)
Connector getSource ()
Connector findConnector (Point2D.Double p, Figure f, ConnectionFigure prototype)
void setPotentialTarget (Connector newTarget)
Rectangle basicGetBounds ()
BezierFigure getBezierFigure ()
BezierPath.Node getBezierNode ()
Protected Member Functions inherited from org.jhotdraw.draw.handle.AbstractHandle
int getHandlesize ()
void fireAreaInvalidated (Rectangle invalidatedArea)
void fireUndoableEditHappened (UndoableEdit edit)
void fireHandleRequestRemove (Rectangle invalidatedArea)
void fireHandleRequestSecondaryHandles ()
void drawCircle (Graphics2D g, Color fill, Color stroke)
void drawRectangle (Graphics2D g, Color fill, Color stroke)
void drawDiamond (Graphics2D g, Color fill, Color stroke)
void updateBounds ()
Additional Inherited Members
Protected Attributes inherited from org.jhotdraw.draw.handle.AbstractConnectionHandle
Collection< Connector > connectors = Collections.emptyList()
Protected Attributes inherited from org.jhotdraw.draw.handle.AbstractHandle
DrawingView view
EventListenerList listenerList = new EventListenerList()
Detailed Description
A Handle which allows to connect the start of a ConnectionFigure to another figure.
Author
Werner Randelshofer
Version
Id
ConnectionStartHandle.java -1
Constructor & Destructor Documentation
ConnectionStartHandle()
org.jhotdraw.draw.handle.ConnectionStartHandle.ConnectionStartHandle (ConnectionFigure owner)
Constructs the connection handle for the given start figure.
Member Function Documentation
canConnect()
boolean org.jhotdraw.draw.handle.ConnectionStartHandle.canConnect (Connector existingEnd, Connector targetEnd) protected
Reimplemented from org.jhotdraw.draw.handle.AbstractConnectionHandle.
References org.jhotdraw.draw.figure.ConnectionFigure.canConnect(), and org.jhotdraw.draw.handle.AbstractConnectionHandle.getOwner().
connect()
void org.jhotdraw.draw.handle.ConnectionStartHandle.connect (Connector c) protected
Sets the start of the connection.
Reimplemented from org.jhotdraw.draw.handle.AbstractConnectionHandle.
References org.jhotdraw.draw.handle.AbstractConnectionHandle.getOwner(), and org.jhotdraw.draw.figure.ConnectionFigure.setStartConnector().
disconnect()
void org.jhotdraw.draw.handle.ConnectionStartHandle.disconnect () protected
Disconnects the start figure.
Reimplemented from org.jhotdraw.draw.handle.AbstractConnectionHandle.
References org.jhotdraw.draw.handle.AbstractConnectionHandle.getOwner(), and org.jhotdraw.draw.figure.ConnectionFigure.setStartConnector().
getBezierNodeIndex()
int org.jhotdraw.draw.handle.ConnectionStartHandle.getBezierNodeIndex () protected
Reimplemented from org.jhotdraw.draw.handle.AbstractConnectionHandle.
getLocation()
Point2D.Double org.jhotdraw.draw.handle.ConnectionStartHandle.getLocation () protected
Returns the start point of the connection.
Reimplemented from org.jhotdraw.draw.handle.AbstractConnectionHandle.
References org.jhotdraw.draw.handle.AbstractConnectionHandle.getOwner(), and org.jhotdraw.draw.figure.ConnectionFigure.getStartPoint().
getTarget()
Connector org.jhotdraw.draw.handle.ConnectionStartHandle.getTarget () protected
Returns the connector of the change.
Reimplemented from org.jhotdraw.draw.handle.AbstractConnectionHandle.
References org.jhotdraw.draw.handle.AbstractConnectionHandle.getOwner(), and org.jhotdraw.draw.figure.ConnectionFigure.getStartConnector().
setLocation()
void org.jhotdraw.draw.handle.ConnectionStartHandle.setLocation (Point2D.Double p) protected
Sets the start point of the connection.
Reimplemented from org.jhotdraw.draw.handle.AbstractConnectionHandle.
References org.jhotdraw.draw.figure.Figure.changed(), org.jhotdraw.draw.handle.AbstractConnectionHandle.getOwner(), org.jhotdraw.draw.figure.ConnectionFigure.setStartPoint(), and org.jhotdraw.draw.figure.Figure.willChange().
The documentation for this class was generated from the following file:
jhotdraw-core/src/main/java/org/jhotdraw/draw/handle/ConnectionStartHandle.java