jhotdraw: org.jhotdraw.draw.figure.TextAreaFigure Class Reference
org.jhotdraw.draw.figure.TextAreaFigure Class Reference
Public Member Functions
TextAreaFigure ()
TextAreaFigure (String text)
void setBounds (Point2D.Double anchor, Point2D.Double lead)
void transform (AffineTransform tx)
boolean figureContains (Point2D.Double p)
Rectangle2D.Double getBounds ()
void restoreTransformTo (Object geometry)
Object getTransformRestoreData ()
String getText ()
Insets2D.Double getInsets ()
double getBaseline ()
int getTabSize ()
void setText (String newText)
int getTextColumns ()
Font getFont ()
Color getTextColor ()
Color getFillColor ()
void setFontSize (float size)
float getFontSize ()
boolean isEditable ()
void setEditable (boolean b)
Tool getTool (Point2D.Double p)
TextHolderFigure getLabelFor ()
TextAreaFigure clone ()
Collection< Handle > createHandles (int detailLevel)
void read (DOMInput in) throws IOException
void write (DOMOutput out) throws IOException
void invalidate ()
boolean isTextOverflow ()
Dimension2DDouble getPreferredTextSize (double maxWidth)
Public Member Functions inherited from org.jhotdraw.draw.figure.AbstractAttributedDecoratedFigure
final void draw (Graphics2D g)
final Rectangle2D.Double getDrawingArea ()
void setDecorator (Figure newValue)
Figure getDecorator ()
final boolean contains (Point2D.Double p)
Public Member Functions inherited from org.jhotdraw.draw.figure.AbstractAttributedFigure
AbstractAttributedFigure ()
void setAttributeEnabled (AttributeKey<?> key, boolean b)
boolean isAttributeEnabled (AttributeKey<?> key)
void setAttributes (Map< AttributeKey<?>, Object > map)
Map< AttributeKey<?>, Object > getAttributes ()
Object getAttributesRestoreData ()
void restoreAttributesTo (Object restoreData)
double getStrokeMiterLimitFactor ()
Rectangle2D.Double getDrawingArea (double factor)
boolean hasAttribute (AttributeKey<?> key)
Public Member Functions inherited from org.jhotdraw.draw.figure.AbstractFigure
AbstractFigure ()
void addFigureListener (FigureListener l)
void removeFigureListener (FigureListener l)
void addNotify (Drawing d)
void removeNotify (Drawing d)
void fireAreaInvalidated ()
void fireFigureChanged ()
void remap (Map< Figure, Figure > oldToNew, boolean disconnectIfNotInMap)
Cursor getCursor (Point2D.Double p)
final void setBounds (Rectangle2D.Double bounds)
void willChange ()
void changed ()
Connector findConnector (Point2D.Double p, ConnectionFigure prototype)
boolean includes (Figure figure)
Figure findFigureInside (Point2D.Double p)
Connector findCompatibleConnector (Connector c, boolean isStart)
Collection< Action > getActions (Point2D.Double p)
boolean handleMouseClick (Point2D.Double p, MouseEvent evt, DrawingView view)
boolean handleDrop (Point2D.Double p, Collection< Figure > droppedFigures, DrawingView view)
Point2D.Double getEndPoint ()
Point2D.Double getStartPoint ()
Dimension2DDouble getPreferredSize ()
boolean isConnectable ()
void setConnectable (boolean newValue)
boolean isSelectable ()
void setSelectable (boolean newValue)
boolean isRemovable ()
void setRemovable (boolean newValue)
boolean isTransformable ()
void setTransformable (boolean newValue)
boolean isVisible ()
void setVisible (boolean newValue)
Collection< Figure > getDecomposition ()
void requestRemove ()
int getLayer ()
String getToolTipText (Point2D.Double p)
String toString ()
Collection< Connector > getConnectors (ConnectionFigure prototype)
Public Member Functions inherited from org.jhotdraw.draw.figure.Figure
void addPropertyChangeListener (PropertyChangeListener listener)
void removePropertyChangeListener (PropertyChangeListener listener)
Protected Member Functions
void drawText (Graphics2D g)
void drawFill (Graphics2D g)
void drawStroke (Graphics2D g)
void readBounds (DOMInput in) throws IOException
void writeBounds (DOMOutput out) throws IOException
Protected Member Functions inherited from org.jhotdraw.draw.figure.AbstractAttributedDecoratedFigure
void drawFigure (Graphics2D g)
void drawDecorator (Graphics2D g)
Rectangle2D.Double getFigureDrawingArea ()
void updateDecoratorBounds ()
void writeDecorator (DOMOutput out) throws IOException
void readDecorator (DOMInput in) throws IOException
Protected Member Functions inherited from org.jhotdraw.draw.figure.AbstractAttributedFigure
abstract void drawFill (java.awt.Graphics2D g)
abstract void drawStroke (java.awt.Graphics2D g)
void drawText (java.awt.Graphics2D g)
void writeAttributes (DOMOutput out) throws IOException
void readAttributes (DOMInput in) throws IOException
AttributeKey<?> getAttributeKey (String name)
void applyAttributesTo (Figure that)
Protected Member Functions inherited from org.jhotdraw.draw.figure.AbstractFigure
Drawing getDrawing ()
Object getLock ()
void fireAreaInvalidated (Rectangle2D.Double invalidatedArea)
void fireAreaInvalidated (FigureEvent event)
void fireFigureRequestRemove ()
void fireFigureAdded ()
void fireFigureRemoved ()
void fireFigureChanged (Rectangle2D.Double changedArea)
void fireFigureChanged (FigureEvent event)
void fireFigureHandlesChanged ()
void fireUndoableEditHappened (UndoableEdit edit)
boolean isChanging ()
int getChangingDepth ()
void validate ()
FontRenderContext getFontRenderContext ()
Protected Attributes
Rectangle2D.Double bounds = new Rectangle2D.Double()
boolean editable = true
Protected Attributes inherited from org.jhotdraw.draw.figure.AbstractFigure
EventListenerList listenerList = new EventListenerList()
int changingDepth = 0
Additional Inherited Members
Static Public Attributes inherited from org.jhotdraw.draw.figure.Figure
static final String CONNECTABLE_PROPERTY = "connectable"
static final String REMOVABLE_PROPERTY = "removable"
static final String SELECTABLE_PROPERTY = "selectable"
static final String TRANSFORMABLE_PROPERTY = "transformable"
Detailed Description
A
TextHolderFigure
which holds multiple lines of text in a rectangular area.
It automatically rearranges the text to fit its allocated display area, breaking the lines at word boundaries whenever possible.
The text can contain either LF or CRLF sequences to separate paragraphs, as well as tab characters for table like formatting and alignment.
Currently the tabs are distributed at regular intervals as determined by the TabSize property. Tabs align correctly with either fixed or variable fonts.
If, when resizing, the vertical size of the display box is not enough to display all the text, TextAreaFigure displays a dashed red line at the bottom of the figure to indicate there is hidden text.
TextAreFigure uses all standard attributes for the area Rectangle2D.Double, ie: FillColor, PenColor for the border, FontSize, FontStyle, and FontName, as well as four additional attributes LeftMargin, RightMargin, TopMargin, and TabSize.
A DrawingEditor should provide the TextAreaCreationTool to create a TextAreaFigure.
FIXME - TextAreaFigure should not draw a rectangle on its own but rather rely on a decorator. We probably need a DecoratorConnector for this and we need a way to specify the inner bounds of the decorator. We also need a way to center the text of the TextAreaFigure verticaly and horizontaly.
Author
Eduardo Francos - InContext (original version), Werner Randelshofer (this derived version)
Version
$Id$
Constructor & Destructor Documentation
TextAreaFigure() [1/2]
org.jhotdraw.draw.figure.TextAreaFigure.TextAreaFigure ()
Creates a new instance.
Referenced by org.jhotdraw.draw.figure.TextAreaFigure.clone().
TextAreaFigure() [2/2]
org.jhotdraw.draw.figure.TextAreaFigure.TextAreaFigure (String text)
References org.jhotdraw.draw.figure.TextAreaFigure.setText().
Member Function Documentation
clone()
TextAreaFigure org.jhotdraw.draw.figure.TextAreaFigure.clone ()
Returns a clone of the figure, with clones of all aggregated figures, such as children and decorators. The cloned figure does not clone the list of FigureListeners from its original.
Reimplemented from org.jhotdraw.draw.figure.AbstractAttributedDecoratedFigure.
References org.jhotdraw.draw.figure.TextAreaFigure.bounds, org.jhotdraw.draw.figure.TextAreaFigure.clone(), and org.jhotdraw.draw.figure.TextAreaFigure.TextAreaFigure().
Referenced by org.jhotdraw.draw.figure.TextAreaFigure.clone().
createHandles()
Collection<Handle> org.jhotdraw.draw.figure.TextAreaFigure.createHandles (int detailLevel)
Creates handles used to manipulate the figure.
Parameters
detailLevel The detail level of the handles. Usually this is 0 for bounding box handles and 1 for point handles. The value -1 is used by the SelectAreaTracker and the HandleTracker to highlight figures, over which the mouse pointer is hovering.
Returns
a Collection of handles
See also
Handle
Implements org.jhotdraw.draw.figure.Figure.
drawFill()
void org.jhotdraw.draw.figure.TextAreaFigure.drawFill (Graphics2D g) protected
References org.jhotdraw.draw.figure.TextAreaFigure.bounds.
drawStroke()
void org.jhotdraw.draw.figure.TextAreaFigure.drawStroke (Graphics2D g) protected
References org.jhotdraw.draw.figure.TextAreaFigure.bounds.
drawText()
void org.jhotdraw.draw.figure.TextAreaFigure.drawText (Graphics2D g) protected
References org.jhotdraw.draw.figure.TextAreaFigure.bounds, org.jhotdraw.draw.figure.TextAreaFigure.getFont(), org.jhotdraw.draw.figure.AbstractFigure.getFontRenderContext(), org.jhotdraw.draw.figure.TextAreaFigure.getInsets(), org.jhotdraw.draw.figure.TextAreaFigure.getTabSize(), org.jhotdraw.draw.figure.TextAreaFigure.getText(), and org.jhotdraw.draw.figure.TextAreaFigure.isEditable().
figureContains()
boolean org.jhotdraw.draw.figure.TextAreaFigure.figureContains (Point2D.Double p)
Reimplemented from org.jhotdraw.draw.figure.AbstractAttributedDecoratedFigure.
References org.jhotdraw.draw.figure.TextAreaFigure.bounds.
getBaseline()
double org.jhotdraw.draw.figure.TextAreaFigure.getBaseline ()
Gets the baseline of the first line of text, relative to the upper left corner of the figure bounds.
Implements org.jhotdraw.draw.figure.TextHolderFigure.
References org.jhotdraw.draw.figure.TextAreaFigure.getFont(), org.jhotdraw.draw.figure.AbstractFigure.getFontRenderContext(), org.jhotdraw.draw.figure.TextAreaFigure.getInsets(), and org.jhotdraw.draw.figure.TextAreaFigure.getText().
getBounds()
Rectangle2D.Double org.jhotdraw.draw.figure.TextAreaFigure.getBounds ()
Returns the untransformed logical bounds of the figure as a Rectangle.
The bounds are used by Handle objects for adjusting the figure and for aligning the figure on a grid.
Implements org.jhotdraw.draw.figure.Figure.
References org.jhotdraw.draw.figure.TextAreaFigure.bounds.
Referenced by org.jhotdraw.draw.figure.TextAreaFigure.isTextOverflow().
getFillColor()
Color org.jhotdraw.draw.figure.TextAreaFigure.getFillColor ()
Returns the fill color to be used by a text editor for editing this Figure.
Implements org.jhotdraw.draw.figure.TextHolderFigure.
getFont()
Font org.jhotdraw.draw.figure.TextAreaFigure.getFont ()
Returns the font to be used by a text editor for editing this Figure.
Implements org.jhotdraw.draw.figure.TextHolderFigure.
References org.jhotdraw.draw.AttributeKeys.getFont().
Referenced by org.jhotdraw.draw.figure.TextAreaFigure.drawText(), org.jhotdraw.draw.figure.TextAreaFigure.getBaseline(), and org.jhotdraw.draw.figure.TextAreaFigure.getPreferredTextSize().
getFontSize()
float org.jhotdraw.draw.figure.TextAreaFigure.getFontSize ()
Gets the font size of the text held by the TextHolderFigure.
Implements org.jhotdraw.draw.figure.TextHolderFigure.
getInsets()
Insets2D.Double org.jhotdraw.draw.figure.TextAreaFigure.getInsets ()
Returns the insets used to draw text.
Implements org.jhotdraw.draw.figure.TextHolderFigure.
Referenced by org.jhotdraw.draw.figure.TextAreaFigure.drawText(), org.jhotdraw.draw.figure.TextAreaFigure.getBaseline(), and org.jhotdraw.draw.figure.TextAreaFigure.isTextOverflow().
getLabelFor()
TextHolderFigure org.jhotdraw.draw.figure.TextAreaFigure.getLabelFor ()
Sometimes we want to use a TextHolderFigure as a label for another TextHolderFigure. Returns the TextHolderFigure that should be really used.
Implements org.jhotdraw.draw.figure.TextHolderFigure.
getPreferredTextSize()
Dimension2DDouble org.jhotdraw.draw.figure.TextAreaFigure.getPreferredTextSize (double maxWidth)
Returns the preferred text size of the TextAreaFigure.
If you want to use this method to determine the bounds of the TextAreaFigure, you need to add the insets of the TextAreaFigure to the size.
Parameters
maxWidth the maximal width to use. Specify Double.MAX_VALUE if you want the width to be unlimited.
Returns
width and height needed to lay out the text.
References org.jhotdraw.draw.figure.TextAreaFigure.getFont(), org.jhotdraw.draw.figure.AbstractFigure.getFontRenderContext(), org.jhotdraw.draw.figure.TextAreaFigure.getTabSize(), and org.jhotdraw.draw.figure.TextAreaFigure.getText().
Referenced by org.jhotdraw.draw.figure.TextAreaFigure.isTextOverflow().
getTabSize()
int org.jhotdraw.draw.figure.TextAreaFigure.getTabSize ()
Gets the number of characters used to expand tabs.
Implements org.jhotdraw.draw.figure.TextHolderFigure.
Referenced by org.jhotdraw.draw.figure.TextAreaFigure.drawText(), and org.jhotdraw.draw.figure.TextAreaFigure.getPreferredTextSize().
getText()
String org.jhotdraw.draw.figure.TextAreaFigure.getText ()
Gets the text shown by the text figure.
Implements org.jhotdraw.draw.figure.TextHolderFigure.
Referenced by org.jhotdraw.draw.figure.TextAreaFigure.drawText(), org.jhotdraw.draw.figure.TextAreaFigure.getBaseline(), org.jhotdraw.draw.figure.TextAreaFigure.getPreferredTextSize(), and org.jhotdraw.draw.figure.TextAreaFigure.getTextColumns().
getTextColor()
Color org.jhotdraw.draw.figure.TextAreaFigure.getTextColor ()
Returns the text color to be used by a text editor for editing this Figure.
Implements org.jhotdraw.draw.figure.TextHolderFigure.
getTextColumns()
int org.jhotdraw.draw.figure.TextAreaFigure.getTextColumns ()
Gets the number of columns to be overlaid when the figure is edited.
Implements org.jhotdraw.draw.figure.TextHolderFigure.
References org.jhotdraw.draw.figure.TextAreaFigure.getText().
getTool()
Tool org.jhotdraw.draw.figure.TextAreaFigure.getTool (Point2D.Double p)
Returns a specialized tool for the given coordinate.
Returns null, if no specialized tool is available.
Implements org.jhotdraw.draw.figure.Figure.
References org.jhotdraw.draw.figure.AbstractAttributedDecoratedFigure.contains(), and org.jhotdraw.draw.figure.TextAreaFigure.isEditable().
getTransformRestoreData()
Object org.jhotdraw.draw.figure.TextAreaFigure.getTransformRestoreData ()
Gets data which can be used to restore the transformation of the figure without loss of precision, after a transform has been applied to it.
See also
transform(AffineTransform)
Implements org.jhotdraw.draw.figure.Figure.
References org.jhotdraw.draw.figure.TextAreaFigure.bounds.
invalidate()
void org.jhotdraw.draw.figure.TextAreaFigure.invalidate ()
Invalidates cached data of the Figure. This method must execute fast, because it can be called very often.
Reimplemented from org.jhotdraw.draw.figure.AbstractFigure.
isEditable()
boolean org.jhotdraw.draw.figure.TextAreaFigure.isEditable ()
Returns true if the text of the TextHolderFigure can be edited.
Implements org.jhotdraw.draw.figure.TextHolderFigure.
References org.jhotdraw.draw.figure.TextAreaFigure.editable.
Referenced by org.jhotdraw.draw.figure.TextAreaFigure.drawText(), and org.jhotdraw.draw.figure.TextAreaFigure.getTool().
isTextOverflow()
boolean org.jhotdraw.draw.figure.TextAreaFigure.isTextOverflow ()
Returns true, if the text does not fit into the bounds of the Figure.
Implements org.jhotdraw.draw.figure.TextHolderFigure.
References org.jhotdraw.draw.figure.TextAreaFigure.getBounds(), org.jhotdraw.draw.figure.TextAreaFigure.getInsets(), and org.jhotdraw.draw.figure.TextAreaFigure.getPreferredTextSize().
read()
void org.jhotdraw.draw.figure.TextAreaFigure.read (DOMInput in) throws IOException
Reimplemented from org.jhotdraw.draw.figure.AbstractAttributedDecoratedFigure.
References org.jhotdraw.draw.figure.AbstractAttributedFigure.readAttributes(), and org.jhotdraw.draw.figure.TextAreaFigure.readBounds().
readBounds()
void org.jhotdraw.draw.figure.TextAreaFigure.readBounds (DOMInput in) throws IOException protected
References org.jhotdraw.draw.figure.TextAreaFigure.bounds.
Referenced by org.jhotdraw.draw.figure.TextAreaFigure.read().
restoreTransformTo()
void org.jhotdraw.draw.figure.TextAreaFigure.restoreTransformTo (Object restoreData)
Restores the transform of the figure to a previously stored state.
Implements org.jhotdraw.draw.figure.Figure.
References org.jhotdraw.draw.figure.TextAreaFigure.bounds.
setBounds()
void org.jhotdraw.draw.figure.TextAreaFigure.setBounds (Point2D.Double start, Point2D.Double end)
Sets the logical and untransformed bounds of the figure.
This is used by Tool's which create a new Figure and by Tool's which connect a Figure to another Figure.
This is a basic operation which does not fire events. Use the following code sequence, if you need event firing:
figure.willChange();
figure.setBounds(...);
figure.changed();
Parameters
start the start point of the bounds
end the end point of the bounds
See also
getBounds
Implements org.jhotdraw.draw.figure.Figure.
References org.jhotdraw.draw.figure.TextAreaFigure.bounds.
Referenced by org.jhotdraw.draw.figure.TextAreaFigure.transform().
setEditable()
void org.jhotdraw.draw.figure.TextAreaFigure.setEditable (boolean b)
setFontSize()
void org.jhotdraw.draw.figure.TextAreaFigure.setFontSize (float size)
Sets the font size of the text held by the TextHolderFigure.
Implements org.jhotdraw.draw.figure.TextHolderFigure.
setText()
void org.jhotdraw.draw.figure.TextAreaFigure.setText (String newText)
Sets the text shown by the text figure.
Implements org.jhotdraw.draw.figure.TextHolderFigure.
Referenced by org.jhotdraw.draw.figure.TextAreaFigure.TextAreaFigure().
transform()
void org.jhotdraw.draw.figure.TextAreaFigure.transform (AffineTransform tx)
Transforms the shape of the Figure. Transformations using double precision arithmethics are inherently lossy operations. Therefore it is recommended to use getTransformRestoreData() restoreTransformTo() to provide lossless undo/redo functionality.
This is a basic operation which does not fire events. Use the following code sequence, if you need event firing:
figure.willChange();
figure.transform(...);
figure.changed();
Parameters
tx The transformation.
See also
getTransformRestoreData
restoreTransformTo
Implements org.jhotdraw.draw.figure.Figure.
References org.jhotdraw.draw.figure.Figure.getEndPoint(), org.jhotdraw.draw.figure.Figure.getStartPoint(), and org.jhotdraw.draw.figure.TextAreaFigure.setBounds().
write()
void org.jhotdraw.draw.figure.TextAreaFigure.write (DOMOutput out) throws IOException
Reimplemented from org.jhotdraw.draw.figure.AbstractAttributedDecoratedFigure.
References org.jhotdraw.draw.figure.AbstractAttributedFigure.writeAttributes(), and org.jhotdraw.draw.figure.TextAreaFigure.writeBounds().
writeBounds()
void org.jhotdraw.draw.figure.TextAreaFigure.writeBounds (DOMOutput out) throws IOException protected
References org.jhotdraw.draw.figure.TextAreaFigure.bounds.
Referenced by org.jhotdraw.draw.figure.TextAreaFigure.write().
Member Data Documentation
bounds
Rectangle2D.Double org.jhotdraw.draw.figure.TextAreaFigure.bounds = new Rectangle2D.Double() protected
Referenced by org.jhotdraw.draw.figure.TextAreaFigure.clone(), org.jhotdraw.draw.figure.TextAreaFigure.drawFill(), org.jhotdraw.draw.figure.TextAreaFigure.drawStroke(), org.jhotdraw.draw.figure.TextAreaFigure.drawText(), org.jhotdraw.draw.figure.TextAreaFigure.figureContains(), org.jhotdraw.draw.figure.TextAreaFigure.getBounds(), org.jhotdraw.draw.figure.TextAreaFigure.getTransformRestoreData(), org.jhotdraw.draw.figure.TextAreaFigure.readBounds(), org.jhotdraw.draw.figure.TextAreaFigure.restoreTransformTo(), org.jhotdraw.draw.figure.TextAreaFigure.setBounds(), and org.jhotdraw.draw.figure.TextAreaFigure.writeBounds().
editable
boolean org.jhotdraw.draw.figure.TextAreaFigure.editable = true protected
Referenced by org.jhotdraw.draw.figure.TextAreaFigure.isEditable().
The documentation for this class was generated from the following file:
jhotdraw-core/src/main/java/org/jhotdraw/draw/figure/TextAreaFigure.java