jhotdraw: org.jhotdraw.draw.event.DrawingComponentRepainter Class Reference
org.jhotdraw.draw.event.DrawingComponentRepainter Class Reference
Public Member Functions
DrawingComponentRepainter (DrawingEditor editor, JComponent component)
void attributeChanged (FigureEvent evt)
void propertyChange (PropertyChangeEvent evt)
void dispose ()
Public Member Functions inherited from org.jhotdraw.draw.event.FigureAdapter
void areaInvalidated (FigureEvent e)
void figureAdded (FigureEvent e)
void figureChanged (FigureEvent e)
void figureRemoved (FigureEvent e)
void figureRequestRemove (FigureEvent e)
void figureHandlesChanged (FigureEvent e)
Detailed Description
Calls repaint on components, which show attributes of a drawing object on the current view of the editor.
Author
Werner Randelshofer
Version
$Id$
Constructor & Destructor Documentation
DrawingComponentRepainter()
org.jhotdraw.draw.event.DrawingComponentRepainter.DrawingComponentRepainter (DrawingEditor editor, JComponent component)
References org.jhotdraw.draw.figure.Figure.addFigureListener(), org.jhotdraw.draw.DrawingEditor.addPropertyChangeListener(), org.jhotdraw.draw.DrawingView.addPropertyChangeListener(), org.jhotdraw.draw.DrawingEditor.getActiveView(), and org.jhotdraw.draw.DrawingView.getDrawing().
Member Function Documentation
attributeChanged()
void org.jhotdraw.draw.event.DrawingComponentRepainter.attributeChanged (FigureEvent e)
Sent when an attribute of the figure has changed.
Reimplemented from org.jhotdraw.draw.event.FigureAdapter.
dispose()
void org.jhotdraw.draw.event.DrawingComponentRepainter.dispose ()
References org.jhotdraw.draw.DrawingEditor.getActiveView(), org.jhotdraw.draw.DrawingView.getDrawing(), org.jhotdraw.draw.figure.Figure.removeFigureListener(), org.jhotdraw.draw.DrawingEditor.removePropertyChangeListener(), and org.jhotdraw.draw.DrawingView.removePropertyChangeListener().
propertyChange()
void org.jhotdraw.draw.event.DrawingComponentRepainter.propertyChange (PropertyChangeEvent evt)
References org.jhotdraw.draw.DrawingEditor.ACTIVE_VIEW_PROPERTY, org.jhotdraw.draw.figure.Figure.addFigureListener(), org.jhotdraw.draw.DrawingView.addPropertyChangeListener(), org.jhotdraw.draw.DrawingView.DRAWING_PROPERTY, org.jhotdraw.draw.DrawingView.getDrawing(), org.jhotdraw.draw.figure.Figure.removeFigureListener(), and org.jhotdraw.draw.DrawingView.removePropertyChangeListener().
The documentation for this class was generated from the following file:
jhotdraw-core/src/main/java/org/jhotdraw/draw/event/DrawingComponentRepainter.java