jhotdraw: org.jhotdraw.draw.text.FloatingTextField Class Reference
org.jhotdraw.draw.text.FloatingTextField Class Reference
Public Member Functions
FloatingTextField ()
void requestFocus ()
void createOverlay (DrawingView view, TextHolderFigure figure)
Insets getInsets ()
void addActionListener (ActionListener listener)
void removeActionListener (ActionListener listener)
String getText ()
Dimension getPreferredSize (int cols)
void endOverlay ()
Protected Member Functions
void updateWidget ()
Detailed Description
A floating text field that is used to edit a TextHolderFigure.
FloatingTextField
requires a two step initialization: In a first step the overlay is created and in a second step it can be positioned.
Design Patterns
Framework
The text creation and editing tools and the
TextHolderFigure
interface define together the contracts of a smaller framework inside of the JHotDraw framework for structured drawing editors.
Contract: TextHolderFigure, org.jhotdraw.draw.tool.TextCreationTool, org.jhotdraw.draw.tool.TextAreaCreationTool, org.jhotdraw.draw.tool.TextEditingTool, org.jhotdraw.draw.tool.TextAreaEditingTool, FloatingTextField, FloatingTextArea.
Author
Werner Randelshofer
Version
Id
FloatingTextField.java -1
Constructor & Destructor Documentation
FloatingTextField()
org.jhotdraw.draw.text.FloatingTextField.FloatingTextField ()
Member Function Documentation
addActionListener()
void org.jhotdraw.draw.text.FloatingTextField.addActionListener (ActionListener listener)
Adds an action listener
Referenced by org.jhotdraw.draw.tool.TextCreationTool.beginEdit(), and org.jhotdraw.draw.tool.TextEditingTool.beginEdit().
createOverlay()
void org.jhotdraw.draw.text.FloatingTextField.createOverlay (DrawingView view, TextHolderFigure figure)
Creates the overlay for the given Container using a specific font.
References org.jhotdraw.draw.figure.Figure.addFigureListener(), org.jhotdraw.draw.DrawingView.getComponent(), org.jhotdraw.draw.figure.TextHolderFigure.getText(), org.jhotdraw.draw.figure.TextHolderFigure.getTextColumns(), and org.jhotdraw.draw.text.FloatingTextField.updateWidget().
Referenced by org.jhotdraw.draw.tool.TextCreationTool.beginEdit(), and org.jhotdraw.draw.tool.TextEditingTool.beginEdit().
endOverlay()
void org.jhotdraw.draw.text.FloatingTextField.endOverlay ()
Removes the overlay.
References org.jhotdraw.draw.DrawingView.getComponent(), and org.jhotdraw.draw.figure.Figure.removeFigureListener().
Referenced by org.jhotdraw.draw.tool.TextCreationTool.endEdit(), and org.jhotdraw.draw.tool.TextEditingTool.endEdit().
getInsets()
Insets org.jhotdraw.draw.text.FloatingTextField.getInsets ()
getPreferredSize()
Dimension org.jhotdraw.draw.text.FloatingTextField.getPreferredSize (int cols)
Gets the preferred size of the overlay.
getText()
String org.jhotdraw.draw.text.FloatingTextField.getText ()
Gets the text contents of the overlay.
Referenced by org.jhotdraw.draw.tool.TextCreationTool.endEdit(), and org.jhotdraw.draw.tool.TextEditingTool.endEdit().
removeActionListener()
void org.jhotdraw.draw.text.FloatingTextField.removeActionListener (ActionListener listener)
Remove an action listener
requestFocus()
void org.jhotdraw.draw.text.FloatingTextField.requestFocus ()
Referenced by org.jhotdraw.draw.tool.TextCreationTool.beginEdit(), and org.jhotdraw.draw.tool.TextEditingTool.beginEdit().
updateWidget()
void org.jhotdraw.draw.text.FloatingTextField.updateWidget () protected
References org.jhotdraw.draw.DrawingView.drawingToView(), org.jhotdraw.draw.figure.Figure.get(), org.jhotdraw.draw.figure.TextHolderFigure.getBaseline(), org.jhotdraw.draw.figure.Figure.getBounds(), org.jhotdraw.draw.figure.TextHolderFigure.getFillColor(), org.jhotdraw.draw.figure.TextHolderFigure.getFont(), org.jhotdraw.draw.figure.TextHolderFigure.getFontSize(), org.jhotdraw.draw.DrawingView.getScaleFactor(), and org.jhotdraw.draw.figure.TextHolderFigure.getTextColor().
Referenced by org.jhotdraw.draw.text.FloatingTextField.createOverlay().
The documentation for this class was generated from the following file:
jhotdraw-core/src/main/java/org/jhotdraw/draw/text/FloatingTextField.java