jhotdraw: org.jhotdraw.draw.handle.BezierNodeHandle Class Reference
org.jhotdraw.draw.handle.BezierNodeHandle Class Reference
Public Member Functions
BezierNodeHandle (BezierFigure owner, int index)
BezierNodeHandle (BezierFigure owner, int index, Figure transformOwner)
void dispose ()
void draw (Graphics2D g)
BezierFigure getOwner ()
void trackStart (Point anchor, int modifiersEx)
void trackStep (Point anchor, Point lead, int modifiersEx)
void trackEnd (Point anchor, Point lead, int modifiersEx)
boolean isCombinableWith (Handle h)
void trackDoubleClick (Point p, int modifiersEx)
Collection< Handle > createSecondaryHandles ()
String getToolTipText (Point p)
void keyPressed (KeyEvent evt)
Public Member Functions inherited from org.jhotdraw.draw.handle.AbstractHandle
AbstractHandle (Figure owner)
void addHandleListener (HandleListener l)
void removeHandleListener (HandleListener l)
void setView (DrawingView view)
DrawingView getView ()
DrawingEditor getEditor ()
boolean contains (Point p)
void invalidate ()
void areaInvalidated (FigureEvent evt)
void figureAdded (FigureEvent e)
void figureRemoved (FigureEvent e)
void figureRequestRemove (FigureEvent e)
void figureChanged (FigureEvent evt)
Cursor getCursor ()
void keyTyped (KeyEvent evt)
void keyReleased (KeyEvent evt)
final Rectangle getBounds ()
Rectangle getDrawingArea ()
void attributeChanged (FigureEvent e)
void viewTransformChanged ()
void setToolTipText (String newValue)
void figureHandlesChanged (FigureEvent e)
Protected Member Functions
Point getLocation ()
BezierPath.Node getBezierNode ()
Rectangle basicGetBounds ()
Figure getTransformOwner ()
Protected Member Functions inherited from org.jhotdraw.draw.handle.AbstractHandle
int getHandlesize ()
void fireAreaInvalidated (Rectangle invalidatedArea)
void fireUndoableEditHappened (UndoableEdit edit)
void fireHandleRequestRemove (Rectangle invalidatedArea)
void fireHandleRequestSecondaryHandles ()
void drawCircle (Graphics2D g, Color fill, Color stroke)
void drawRectangle (Graphics2D g, Color fill, Color stroke)
void drawDiamond (Graphics2D g, Color fill, Color stroke)
void updateBounds ()
Protected Attributes
int index
Protected Attributes inherited from org.jhotdraw.draw.handle.AbstractHandle
DrawingView view
EventListenerList listenerList = new EventListenerList()
Detailed Description
A Handle which allows to interactively change a node of a bezier path.
Author
Werner Randelshofer
Version
$Id$
Constructor & Destructor Documentation
BezierNodeHandle() [1/2]
org.jhotdraw.draw.handle.BezierNodeHandle.BezierNodeHandle (BezierFigure owner, int index)
Creates a new instance.
References org.jhotdraw.draw.handle.BezierNodeHandle.index.
BezierNodeHandle() [2/2]
org.jhotdraw.draw.handle.BezierNodeHandle.BezierNodeHandle (BezierFigure owner, int index, Figure transformOwner)
References org.jhotdraw.draw.figure.Figure.addFigureListener(), and org.jhotdraw.draw.handle.BezierNodeHandle.index.
Member Function Documentation
basicGetBounds()
Rectangle org.jhotdraw.draw.handle.BezierNodeHandle.basicGetBounds () protected
Reimplemented from org.jhotdraw.draw.handle.AbstractHandle.
References org.jhotdraw.draw.handle.AbstractHandle.getHandlesize(), and org.jhotdraw.draw.handle.BezierNodeHandle.getLocation().
createSecondaryHandles()
Collection<Handle> org.jhotdraw.draw.handle.BezierNodeHandle.createSecondaryHandles ()
Creates secondary handles.
Reimplemented from org.jhotdraw.draw.handle.AbstractHandle.
References org.jhotdraw.draw.figure.BezierFigure.getNode(), org.jhotdraw.draw.figure.BezierFigure.getNodeCount(), org.jhotdraw.draw.handle.BezierNodeHandle.getOwner(), org.jhotdraw.draw.handle.BezierNodeHandle.getTransformOwner(), org.jhotdraw.draw.handle.BezierNodeHandle.index, and org.jhotdraw.draw.figure.BezierFigure.isClosed().
dispose()
void org.jhotdraw.draw.handle.BezierNodeHandle.dispose ()
Disposes the resources acquired by the handler.
Reimplemented from org.jhotdraw.draw.handle.AbstractHandle.
References org.jhotdraw.draw.figure.Figure.removeFigureListener().
draw()
void org.jhotdraw.draw.handle.BezierNodeHandle.draw (Graphics2D g)
Draws this handle.
Reimplemented from org.jhotdraw.draw.handle.AbstractHandle.
References org.jhotdraw.draw.handle.HandleAttributeKeys.BEZIER_NODE_HANDLE_FILL_COLOR, org.jhotdraw.draw.handle.HandleAttributeKeys.BEZIER_NODE_HANDLE_FILL_COLOR_DISABLED, org.jhotdraw.draw.handle.HandleAttributeKeys.BEZIER_NODE_HANDLE_STROKE_COLOR, org.jhotdraw.draw.handle.HandleAttributeKeys.BEZIER_NODE_HANDLE_STROKE_COLOR_DISABLED, org.jhotdraw.draw.handle.AbstractHandle.drawCircle(), org.jhotdraw.draw.handle.AbstractHandle.drawDiamond(), org.jhotdraw.draw.handle.AbstractHandle.drawRectangle(), org.jhotdraw.draw.handle.AbstractHandle.getEditor(), org.jhotdraw.draw.DrawingEditor.getHandleAttribute(), org.jhotdraw.draw.figure.BezierFigure.getNode(), org.jhotdraw.draw.figure.BezierFigure.getNodeCount(), org.jhotdraw.draw.handle.BezierNodeHandle.getOwner(), org.jhotdraw.draw.handle.BezierNodeHandle.index, and org.jhotdraw.draw.figure.BezierFigure.isClosed().
getBezierNode()
BezierPath.Node org.jhotdraw.draw.handle.BezierNodeHandle.getBezierNode () protected
References org.jhotdraw.draw.figure.BezierFigure.getNode(), org.jhotdraw.draw.figure.BezierFigure.getNodeCount(), org.jhotdraw.draw.handle.BezierNodeHandle.getOwner(), and org.jhotdraw.draw.handle.BezierNodeHandle.index.
Referenced by org.jhotdraw.draw.handle.BezierNodeHandle.getToolTipText().
getLocation()
Point org.jhotdraw.draw.handle.BezierNodeHandle.getLocation () protected
References org.jhotdraw.draw.DrawingView.drawingToView(), org.jhotdraw.draw.figure.Figure.get(), org.jhotdraw.draw.handle.BezierNodeHandle.getOwner(), org.jhotdraw.draw.figure.BezierFigure.getPoint(), org.jhotdraw.draw.handle.BezierNodeHandle.getTransformOwner(), org.jhotdraw.draw.handle.BezierNodeHandle.index, and org.jhotdraw.draw.handle.AbstractHandle.view.
Referenced by org.jhotdraw.draw.handle.BezierNodeHandle.basicGetBounds().
getOwner()
BezierFigure org.jhotdraw.draw.handle.BezierNodeHandle.getOwner ()
Returns the owner of this handle.
Reimplemented from org.jhotdraw.draw.handle.AbstractHandle.
Referenced by org.jhotdraw.draw.handle.BezierNodeHandle.createSecondaryHandles(), org.jhotdraw.draw.handle.BezierNodeHandle.draw(), org.jhotdraw.draw.handle.BezierNodeHandle.getBezierNode(), org.jhotdraw.draw.handle.BezierNodeHandle.getLocation(), org.jhotdraw.draw.handle.BezierNodeHandle.keyPressed(), org.jhotdraw.draw.handle.BezierNodeHandle.trackDoubleClick(), org.jhotdraw.draw.handle.BezierNodeHandle.trackEnd(), org.jhotdraw.draw.handle.BezierNodeHandle.trackStart(), and org.jhotdraw.draw.handle.BezierNodeHandle.trackStep().
getToolTipText()
String org.jhotdraw.draw.handle.BezierNodeHandle.getToolTipText (Point p)
Returns a tooltip for the specified location. By default, AbstractHandle returns null.
Reimplemented from org.jhotdraw.draw.handle.AbstractHandle.
References org.jhotdraw.draw.handle.BezierNodeHandle.getBezierNode().
getTransformOwner()
Figure org.jhotdraw.draw.handle.BezierNodeHandle.getTransformOwner () protected
Referenced by org.jhotdraw.draw.handle.BezierNodeHandle.createSecondaryHandles(), org.jhotdraw.draw.handle.BezierNodeHandle.getLocation(), and org.jhotdraw.draw.handle.BezierNodeHandle.trackStep().
isCombinableWith()
boolean org.jhotdraw.draw.handle.BezierNodeHandle.isCombinableWith (Handle handle)
Returns true, if the given handle is an instance of the same class or of a subclass of this handle,.
Reimplemented from org.jhotdraw.draw.handle.AbstractHandle.
keyPressed()
void org.jhotdraw.draw.handle.BezierNodeHandle.keyPressed (KeyEvent evt)
Reimplemented from org.jhotdraw.draw.handle.AbstractHandle.
References org.jhotdraw.draw.figure.BezierFigure.addNode(), org.jhotdraw.draw.DrawingView.addToSelection(), org.jhotdraw.draw.figure.AbstractFigure.changed(), org.jhotdraw.draw.handle.AbstractHandle.fireHandleRequestRemove(), org.jhotdraw.draw.Drawing.fireUndoableEditHappened(), org.jhotdraw.draw.handle.AbstractHandle.fireUndoableEditHappened(), org.jhotdraw.draw.DrawingView.getDrawing(), org.jhotdraw.draw.handle.AbstractHandle.getDrawingArea(), org.jhotdraw.draw.figure.BezierFigure.getNode(), org.jhotdraw.draw.handle.BezierNodeHandle.getOwner(), org.jhotdraw.draw.handle.BezierNodeHandle.index, org.jhotdraw.draw.DrawingView.removeFromSelection(), org.jhotdraw.draw.figure.BezierFigure.removeNode(), org.jhotdraw.draw.figure.BezierFigure.setPoint(), org.jhotdraw.draw.handle.AbstractHandle.view, and org.jhotdraw.draw.figure.AbstractFigure.willChange().
trackDoubleClick()
void org.jhotdraw.draw.handle.BezierNodeHandle.trackDoubleClick (Point p, int modifiersEx)
Tracks a double click.
Reimplemented from org.jhotdraw.draw.handle.AbstractHandle.
References org.jhotdraw.draw.figure.BezierFigure.addNode(), org.jhotdraw.draw.DrawingView.addToSelection(), org.jhotdraw.draw.figure.AbstractFigure.changed(), org.jhotdraw.draw.handle.AbstractHandle.fireHandleRequestRemove(), org.jhotdraw.draw.handle.AbstractHandle.fireUndoableEditHappened(), org.jhotdraw.draw.handle.AbstractHandle.getDrawingArea(), org.jhotdraw.draw.figure.BezierFigure.getNodeCount(), org.jhotdraw.draw.handle.BezierNodeHandle.getOwner(), org.jhotdraw.draw.handle.BezierNodeHandle.index, org.jhotdraw.draw.DrawingView.removeFromSelection(), org.jhotdraw.draw.figure.BezierFigure.removeNode(), org.jhotdraw.draw.handle.AbstractHandle.view, and org.jhotdraw.draw.figure.AbstractFigure.willChange().
trackEnd()
void org.jhotdraw.draw.handle.BezierNodeHandle.trackEnd (Point anchor, Point lead, int modifiersEx)
Tracks the end of the interaction.
Parameters
anchor the position where the interaction started
lead the current position
Implements org.jhotdraw.draw.handle.Handle.
References org.jhotdraw.draw.figure.AbstractFigure.changed(), org.jhotdraw.draw.handle.AbstractHandle.fireHandleRequestSecondaryHandles(), org.jhotdraw.draw.Drawing.fireUndoableEditHappened(), org.jhotdraw.draw.DrawingView.getDrawing(), org.jhotdraw.draw.figure.BezierFigure.getNode(), org.jhotdraw.draw.figure.BezierFigure.getNodeCount(), org.jhotdraw.draw.handle.BezierNodeHandle.getOwner(), org.jhotdraw.draw.handle.BezierNodeHandle.index, org.jhotdraw.draw.figure.BezierFigure.isClosed(), org.jhotdraw.draw.event.BezierNodeEdit.redo(), org.jhotdraw.draw.figure.BezierFigure.setNode(), org.jhotdraw.draw.handle.AbstractHandle.view, and org.jhotdraw.draw.figure.AbstractFigure.willChange().
trackStart()
void org.jhotdraw.draw.handle.BezierNodeHandle.trackStart (Point anchor, int modifiersEx)
Tracks the start of the interaction. The default implementation does nothing.
Parameters
anchor the position where the interaction started
Implements org.jhotdraw.draw.handle.Handle.
References org.jhotdraw.draw.handle.AbstractHandle.fireHandleRequestSecondaryHandles(), org.jhotdraw.draw.Drawing.fireUndoableEditHappened(), org.jhotdraw.draw.DrawingView.getDrawing(), org.jhotdraw.draw.figure.BezierFigure.getNode(), org.jhotdraw.draw.handle.BezierNodeHandle.getOwner(), org.jhotdraw.draw.handle.BezierNodeHandle.index, and org.jhotdraw.draw.handle.AbstractHandle.view.
trackStep()
void org.jhotdraw.draw.handle.BezierNodeHandle.trackStep (Point anchor, Point lead, int modifiersEx)
Tracks a step of the interaction.
Parameters
anchor the position where the interaction started
lead the current position
Implements org.jhotdraw.draw.handle.Handle.
References org.jhotdraw.draw.figure.AbstractFigure.changed(), org.jhotdraw.draw.Constrainer.constrainPoint(), org.jhotdraw.draw.figure.Figure.get(), org.jhotdraw.draw.DrawingView.getConstrainer(), org.jhotdraw.draw.figure.BezierFigure.getNode(), org.jhotdraw.draw.handle.BezierNodeHandle.getOwner(), org.jhotdraw.draw.handle.BezierNodeHandle.getTransformOwner(), org.jhotdraw.draw.handle.BezierNodeHandle.index, org.jhotdraw.draw.figure.BezierFigure.setNode(), org.jhotdraw.draw.handle.AbstractHandle.view, org.jhotdraw.draw.DrawingView.viewToDrawing(), and org.jhotdraw.draw.figure.AbstractFigure.willChange().
Member Data Documentation
index
int org.jhotdraw.draw.handle.BezierNodeHandle.index protected
Referenced by org.jhotdraw.draw.handle.BezierNodeHandle.BezierNodeHandle(), org.jhotdraw.draw.handle.BezierNodeHandle.createSecondaryHandles(), org.jhotdraw.draw.handle.BezierNodeHandle.draw(), org.jhotdraw.draw.handle.BezierNodeHandle.getBezierNode(), org.jhotdraw.draw.handle.BezierNodeHandle.getLocation(), org.jhotdraw.draw.handle.BezierNodeHandle.keyPressed(), org.jhotdraw.draw.handle.BezierNodeHandle.trackDoubleClick(), org.jhotdraw.draw.handle.BezierNodeHandle.trackEnd(), org.jhotdraw.draw.handle.BezierNodeHandle.trackStart(), and org.jhotdraw.draw.handle.BezierNodeHandle.trackStep().
The documentation for this class was generated from the following file:
jhotdraw-core/src/main/java/org/jhotdraw/draw/handle/BezierNodeHandle.java