jhotdraw: org.jhotdraw.draw.tool.DelegationSelectionTool Class Reference
org.jhotdraw.draw.tool.DelegationSelectionTool Class Reference
Public Member Functions
DelegationSelectionTool ()
DelegationSelectionTool (Collection< Action > drawingActions, Collection< Action > selectionActions)
void setDrawingActions (Collection< Action > drawingActions)
void setFigureActions (Collection< Action > selectionActions)
void mousePressed (final MouseEvent evt)
void mouseReleased (MouseEvent evt)
void mouseDragged (MouseEvent evt)
void mouseClicked (MouseEvent evt)
String getToolTipText (DrawingView view, MouseEvent evt)
Public Member Functions inherited from org.jhotdraw.draw.tool.SelectionTool
SelectionTool ()
void setSelectBehindEnabled (boolean newValue)
boolean isSelectBehindEnabled ()
void activate (DrawingEditor editor)
void deactivate (DrawingEditor editor)
void keyPressed (KeyEvent e)
void keyReleased (KeyEvent evt)
void keyTyped (KeyEvent evt)
void mouseEntered (MouseEvent evt)
void mouseExited (MouseEvent evt)
void mouseMoved (MouseEvent evt)
void draw (Graphics2D g)
void setHandleTracker (HandleTracker newValue)
void setSelectAreaTracker (SelectAreaTracker newValue)
void setDragTracker (DragTracker newValue)
boolean supportsHandleInteraction ()
Public Member Functions inherited from org.jhotdraw.draw.tool.AbstractTool
AbstractTool ()
void addUndoableEditListener (UndoableEditListener l)
void removeUndoableEditListener (UndoableEditListener l)
boolean isActive ()
void setInputMap (InputMap newValue)
InputMap getInputMap ()
void setActionMap (ActionMap newValue)
ActionMap getActionMap ()
void editDelete ()
void editCut ()
void editCopy ()
void editDuplicate ()
void editPaste ()
void addToolListener (ToolListener l)
void removeToolListener (ToolListener l)
void updateCursor (DrawingView view, Point p)
Protected Member Functions
void handlePopupMenu (MouseEvent evt)
void showPopupMenu (Figure figure, Point p, Component c)
void handleDoubleClick (MouseEvent evt)
void handleMultiClick (MouseEvent evt)
Protected Member Functions inherited from org.jhotdraw.draw.tool.SelectionTool
void setTracker (Tool newTracker)
HandleTracker getHandleTracker (Handle handle)
DragTracker getDragTracker (Figure f)
SelectAreaTracker getSelectAreaTracker ()
Protected Member Functions inherited from org.jhotdraw.draw.tool.AbstractTool
DrawingView getView ()
DrawingEditor getEditor ()
Drawing getDrawing ()
Point2D.Double viewToDrawing (Point p)
Point2D.Double constrainPoint (Point p, Figure... figure)
Point2D.Double constrainPoint (Point2D.Double p, Figure... figure)
InputMap createInputMap ()
ActionMap createActionMap ()
void fireToolStarted (DrawingView view)
void fireToolDone ()
void fireAreaInvalidated (Rectangle2D.Double r)
void fireAreaInvalidated (Rectangle invalidatedArea)
void maybeFireBoundsInvalidated (Rectangle invalidatedArea)
void fireBoundsInvalidated (Rectangle invalidatedArea)
Additional Inherited Members
Static Public Attributes inherited from org.jhotdraw.draw.tool.SelectionTool
static final String SELECT_BEHIND_ENABLED_PROPERTY = "selectBehindEnabled"
Protected Attributes inherited from org.jhotdraw.draw.tool.AbstractTool
boolean isWorking
DrawingEditor editor
Point anchor = new Point()
EventListenerList listenerList = new EventListenerList()
Detailed Description
A SelectionTool, which recognizes double clicks and popup menu triggers. If a double click or popup trigger is encountered a hook method is called, which handles the event. This methods can be overriden in subclasse to provide customized behaviour.
By default, this Tool delegates mouse events to a specific Tool if the figure which has been double clicked, provides a specialized tool.
Author
Werner Randelshofer
Version
$Id$
Constructor & Destructor Documentation
DelegationSelectionTool() [1/2]
org.jhotdraw.draw.tool.DelegationSelectionTool.DelegationSelectionTool ()
Creates a new instance.
DelegationSelectionTool() [2/2]
org.jhotdraw.draw.tool.DelegationSelectionTool.DelegationSelectionTool (Collection< Action > drawingActions, Collection< Action > selectionActions)
Creates a new instance.
Member Function Documentation
getToolTipText()
String org.jhotdraw.draw.tool.DelegationSelectionTool.getToolTipText (DrawingView view, MouseEvent evt)
Returns the tooltip text for a mouse event on a drawing view.
Parameters
view A drawing view.
evt A mouse event.
Returns
A tooltip text or null.
Reimplemented from org.jhotdraw.draw.tool.AbstractTool.
References org.jhotdraw.draw.DrawingView.findFigure(), org.jhotdraw.draw.DrawingView.findHandle(), org.jhotdraw.draw.handle.Handle.getToolTipText(), org.jhotdraw.draw.figure.Figure.getToolTipText(), and org.jhotdraw.draw.tool.AbstractTool.viewToDrawing().
handleDoubleClick()
void org.jhotdraw.draw.tool.DelegationSelectionTool.handleDoubleClick (MouseEvent evt) protected
Hook method which can be overriden by subclasses to provide specialised behaviour in the event of a double click.
References org.jhotdraw.draw.DrawingView.addToSelection(), org.jhotdraw.draw.DrawingView.clearSelection(), org.jhotdraw.draw.DrawingView.findFigure(), org.jhotdraw.draw.Drawing.findFigureInside(), org.jhotdraw.draw.DrawingView.findHandle(), org.jhotdraw.draw.tool.AbstractTool.getDrawing(), org.jhotdraw.draw.DrawingView.getHandleDetailLevel(), org.jhotdraw.draw.DrawingView.getSelectedFigures(), org.jhotdraw.draw.figure.Figure.getTool(), org.jhotdraw.draw.tool.AbstractTool.getView(), org.jhotdraw.draw.figure.Figure.handleMouseClick(), org.jhotdraw.draw.figure.Figure.isSelectable(), org.jhotdraw.draw.tool.SelectionTool.isSelectBehindEnabled(), org.jhotdraw.draw.DrawingView.setHandleDetailLevel(), org.jhotdraw.draw.tool.SelectionTool.setTracker(), org.jhotdraw.draw.handle.Handle.trackDoubleClick(), and org.jhotdraw.draw.tool.AbstractTool.viewToDrawing().
Referenced by org.jhotdraw.draw.tool.DelegationSelectionTool.mouseClicked().
handleMultiClick()
void org.jhotdraw.draw.tool.DelegationSelectionTool.handleMultiClick (MouseEvent evt) protected
Hook method which can be overriden by subclasses to provide specialised behaviour in the event of a multi-click.
References org.jhotdraw.draw.DrawingView.findHandle(), org.jhotdraw.draw.DrawingView.getHandleDetailLevel(), org.jhotdraw.draw.tool.AbstractTool.getView(), and org.jhotdraw.draw.DrawingView.setHandleDetailLevel().
Referenced by org.jhotdraw.draw.tool.DelegationSelectionTool.mouseClicked().
handlePopupMenu()
void org.jhotdraw.draw.tool.DelegationSelectionTool.handlePopupMenu (MouseEvent evt) protected
Hook method which can be overriden by subclasses to provide specialised behaviour in the event of a popup trigger.
References org.jhotdraw.draw.DrawingView.findFigure(), org.jhotdraw.draw.tool.AbstractTool.getView(), and org.jhotdraw.draw.tool.DelegationSelectionTool.showPopupMenu().
Referenced by org.jhotdraw.draw.tool.DelegationSelectionTool.mousePressed(), and org.jhotdraw.draw.tool.DelegationSelectionTool.mouseReleased().
mouseClicked()
void org.jhotdraw.draw.tool.DelegationSelectionTool.mouseClicked (MouseEvent evt)
Reimplemented from org.jhotdraw.draw.tool.SelectionTool.
References org.jhotdraw.draw.tool.DelegationSelectionTool.handleDoubleClick(), and org.jhotdraw.draw.tool.DelegationSelectionTool.handleMultiClick().
mouseDragged()
void org.jhotdraw.draw.tool.DelegationSelectionTool.mouseDragged (MouseEvent evt)
Reimplemented from org.jhotdraw.draw.tool.SelectionTool.
mousePressed()
void org.jhotdraw.draw.tool.DelegationSelectionTool.mousePressed (final MouseEvent evt)
MouseListener method for mousePressed events. If the popup trigger has been activated, then the appropriate hook method is called.
Reimplemented from org.jhotdraw.draw.tool.SelectionTool.
References org.jhotdraw.draw.tool.AbstractTool.getView(), org.jhotdraw.draw.tool.DelegationSelectionTool.handlePopupMenu(), and org.jhotdraw.draw.DrawingView.requestFocus().
mouseReleased()
void org.jhotdraw.draw.tool.DelegationSelectionTool.mouseReleased (MouseEvent evt)
MouseListener method for mouseReleased events. If the popup trigger has been activated, then the appropriate hook method is called.
Reimplemented from org.jhotdraw.draw.tool.SelectionTool.
References org.jhotdraw.draw.tool.DelegationSelectionTool.handlePopupMenu().
setDrawingActions()
void org.jhotdraw.draw.tool.DelegationSelectionTool.setDrawingActions (Collection< Action > drawingActions)
setFigureActions()
void org.jhotdraw.draw.tool.DelegationSelectionTool.setFigureActions (Collection< Action > selectionActions)
showPopupMenu()
void org.jhotdraw.draw.tool.DelegationSelectionTool.showPopupMenu (Figure figure, Point p, Component c) protected
References org.jhotdraw.draw.figure.Figure.getActions(), and org.jhotdraw.draw.tool.AbstractTool.viewToDrawing().
Referenced by org.jhotdraw.draw.tool.DelegationSelectionTool.handlePopupMenu().
The documentation for this class was generated from the following file:
jhotdraw-core/src/main/java/org/jhotdraw/draw/tool/DelegationSelectionTool.java