jhotdraw: org.jhotdraw.draw.AbstractDrawing Class Reference
org.jhotdraw.draw.AbstractDrawing Class Reference abstract
Public Member Functions
AbstractDrawing ()
void addUndoableEditListener (UndoableEditListener l)
void removeUndoableEditListener (UndoableEditListener l)
void fireUndoableEditHappened (UndoableEdit edit)
FontRenderContext getFontRenderContext ()
void setFontRenderContext (FontRenderContext frc)
void read (DOMInput in) throws IOException
void write (DOMOutput out) throws IOException
Object getLock ()
void addInputFormat (InputFormat format)
void addOutputFormat (OutputFormat format)
void setOutputFormats (java.util.List< OutputFormat > formats)
void setInputFormats (java.util.List< InputFormat > formats)
java.util.List< InputFormat > getInputFormats ()
java.util.List< OutputFormat > getOutputFormats ()
Drawing getDrawing ()
AbstractDrawing clone ()
Public Member Functions inherited from org.jhotdraw.draw.figure.AbstractAttributedCompositeFigure
AbstractAttributedCompositeFigure ()
void setAttributeEnabled (AttributeKey<?> key, boolean b)
void setAttributes (Map< AttributeKey<?>, Object > map)
Map< AttributeKey<?>, Object > getAttributes ()
Object getAttributesRestoreData ()
void restoreAttributesTo (Object restoreData)
void drawFigure (Graphics2D g)
Stroke getStroke ()
double getStrokeMiterLimitFactor ()
Rectangle2D.Double getFigureDrawBounds ()
Public Member Functions inherited from org.jhotdraw.draw.figure.AbstractCompositeFigure
AbstractCompositeFigure ()
Collection< Handle > createHandles (int detailLevel)
boolean add (Figure figure)
void add (int index, Figure figure)
void addAll (Collection<? extends Figure > figures)
final void addAll (int index, Collection<? extends Figure > figures)
void basicAdd (Figure figure)
void basicAddAll (int index, Collection<? extends Figure > newFigures)
void addNotify (Drawing drawing)
void removeNotify (Drawing drawing)
boolean remove (final Figure figure)
Figure removeChild (int index)
void removeAll (Collection<? extends Figure > figures)
void removeAllChildren ()
void basicRemoveAllChildren ()
void basicRemoveAll (Collection<? extends Figure > figures)
void sendToBack (Figure figure)
void bringToFront (Figure figure)
void transform (AffineTransform tx)
void setBounds (Point2D.Double anchor, Point2D.Double lead)
java.util.List< Figure > getChildrenFrontToBack ()
boolean contains (Figure f)
boolean contains (Point2D.Double p)
Figure findFigureInside (Point2D.Double p)
Figure findChild (Point2D.Double p)
int findChildIndex (Point2D.Double p)
Layouter getLayouter ()
void layout ()
void setLayouter (Layouter newLayouter)
Dimension2DDouble getPreferredSize ()
void draw (Graphics2D g)
Collection< Figure > getDecomposition ()
void restoreTransformTo (Object geometry)
Object getTransformRestoreData ()
void basicAdd (int index, Figure figure)
Figure basicRemoveChild (int index)
java.util.List< Figure > getChildren ()
int getChildCount ()
Figure getChild (int index)
void willChange ()
void changed ()
int basicRemove (Figure child)
int indexOf (Figure child)
Rectangle2D.Double getDrawingArea ()
Rectangle2D.Double getDrawingArea (double factor)
Rectangle2D.Double getBounds ()
void removeCompositeFigureListener (CompositeFigureListener listener)
void addCompositeFigureListener (CompositeFigureListener listener)
Public Member Functions inherited from org.jhotdraw.draw.figure.AbstractFigure
AbstractFigure ()
void addFigureListener (FigureListener l)
void removeFigureListener (FigureListener l)
void fireAreaInvalidated ()
void fireFigureChanged ()
void remap (Map< Figure, Figure > oldToNew, boolean disconnectIfNotInMap)
Cursor getCursor (Point2D.Double p)
final void setBounds (Rectangle2D.Double bounds)
Connector findConnector (Point2D.Double p, ConnectionFigure prototype)
boolean includes (Figure figure)
Connector findCompatibleConnector (Connector c, boolean isStart)
Collection< Action > getActions (Point2D.Double p)
Tool getTool (Point2D.Double p)
boolean handleMouseClick (Point2D.Double p, MouseEvent evt, DrawingView view)
boolean handleDrop (Point2D.Double p, Collection< Figure > droppedFigures, DrawingView view)
Point2D.Double getEndPoint ()
Point2D.Double getStartPoint ()
boolean isConnectable ()
void setConnectable (boolean newValue)
boolean isSelectable ()
void setSelectable (boolean newValue)
boolean isRemovable ()
void setRemovable (boolean newValue)
boolean isTransformable ()
void setTransformable (boolean newValue)
boolean isVisible ()
void setVisible (boolean newValue)
void requestRemove ()
int getLayer ()
String getToolTipText (Point2D.Double p)
String toString ()
Collection< Connector > getConnectors (ConnectionFigure prototype)
Public Member Functions inherited from org.jhotdraw.draw.figure.Figure
void addPropertyChangeListener (PropertyChangeListener listener)
void removePropertyChangeListener (PropertyChangeListener listener)
Public Member Functions inherited from org.jhotdraw.draw.Drawing
void drawCanvas (Graphics2D g)
boolean add (Figure figure)
void add (int index, Figure figure)
void addAll (Collection<? extends Figure > figures)
void addAll (int index, Collection<? extends Figure > figures)
boolean remove (Figure figure)
void removeAll (Collection<? extends Figure > figures)
int basicRemove (Figure figure)
void basicRemoveAll (Collection<? extends Figure > figures)
void basicAdd (Figure figure)
void basicAdd (int index, Figure figure)
void basicAddAll (int index, Collection<? extends Figure > figures)
List< Figure > findFigures (Rectangle2D.Double bounds)
List< Figure > findFiguresWithin (Rectangle2D.Double bounds)
Figure findFigure (Point2D.Double p)
Figure findFigureExcept (Point2D.Double p, Figure ignore)
Figure findFigureExcept (Point2D.Double p, Collection<? extends Figure > ignore)
Figure findFigureBehind (Point2D.Double p, Figure figure)
Figure findFigureBehind (Point2D.Double p, Collection<? extends Figure > figures)
List< Figure > getFiguresFrontToBack ()
Figure findFigureInside (Point2D.Double p)
void sendToBack (Figure figure)
void bringToFront (Figure figure)
List< Figure > sort (Collection<? extends Figure > figures)
void setInputFormats (List< InputFormat > formats)
void setOutputFormats (List< OutputFormat > formats)
Static Public Member Functions
static boolean isDebugMode ()
static void setDebugMode (boolean debugMode)
Additional Inherited Members
Static Public Attributes inherited from org.jhotdraw.draw.figure.Figure
static final String CONNECTABLE_PROPERTY = "connectable"
static final String REMOVABLE_PROPERTY = "removable"
static final String SELECTABLE_PROPERTY = "selectable"
static final String TRANSFORMABLE_PROPERTY = "transformable"
Static Public Attributes inherited from org.jhotdraw.draw.figure.CompositeFigure
static final AttributeKey< Insets2D.Double > LAYOUT_INSETS = new AttributeKey<Insets2D.Double>("layoutInsets", Insets2D.Double.class, new Insets2D.Double())
Protected Member Functions inherited from org.jhotdraw.draw.figure.AbstractAttributedCompositeFigure
void drawChildren (Graphics2D g)
abstract void drawFill (java.awt.Graphics2D g)
abstract void drawStroke (java.awt.Graphics2D g)
void drawText (java.awt.Graphics2D g)
void writeAttributes (DOMOutput out) throws IOException
void readAttributes (DOMInput in) throws IOException
AttributeKey<?> getAttributeKey (String name)
void applyAttributesTo (Figure that)
Protected Member Functions inherited from org.jhotdraw.draw.figure.AbstractCompositeFigure
EventHandler createEventHandler ()
void validate ()
void invalidate ()
void fireFigureAdded (Figure f, int zIndex)
void fireFigureRemoved (Figure f, int zIndex)
Protected Member Functions inherited from org.jhotdraw.draw.figure.AbstractFigure
void fireAreaInvalidated (Rectangle2D.Double invalidatedArea)
void fireAreaInvalidated (FigureEvent event)
void fireFigureRequestRemove ()
void fireFigureAdded ()
void fireFigureRemoved ()
void fireFigureChanged (Rectangle2D.Double changedArea)
void fireFigureChanged (FigureEvent event)
void fireFigureHandlesChanged ()
boolean isChanging ()
int getChangingDepth ()
Protected Attributes inherited from org.jhotdraw.draw.figure.AbstractCompositeFigure
Layouter layouter
ArrayList< Figure > children = new ArrayList<>()
transient Rectangle2D.Double cachedDrawingArea
transient Rectangle2D.Double cachedBounds
EventHandler eventHandler
Protected Attributes inherited from org.jhotdraw.draw.figure.AbstractFigure
EventListenerList listenerList = new EventListenerList()
int changingDepth = 0
Detailed Description
This abstract class can be extended to implement a Drawing.
Author
Werner Randelshofer
Version
$Id$
Constructor & Destructor Documentation
AbstractDrawing()
org.jhotdraw.draw.AbstractDrawing.AbstractDrawing ()
Creates a new instance.
Referenced by org.jhotdraw.draw.AbstractDrawing.clone().
Member Function Documentation
addInputFormat()
void org.jhotdraw.draw.AbstractDrawing.addInputFormat (InputFormat format)
Adds an input format to the drawing.
Implements org.jhotdraw.draw.Drawing.
addOutputFormat()
void org.jhotdraw.draw.AbstractDrawing.addOutputFormat (OutputFormat format)
Adds an output format to the drawing.
Implements org.jhotdraw.draw.Drawing.
addUndoableEditListener()
void org.jhotdraw.draw.AbstractDrawing.addUndoableEditListener (UndoableEditListener l)
Adds a listener for undooable edit events.
Implements org.jhotdraw.draw.Drawing.
References org.jhotdraw.draw.figure.AbstractFigure.listenerList.
clone()
AbstractDrawing org.jhotdraw.draw.AbstractDrawing.clone ()
Returns a clone of the figure, with clones of all aggregated figures, such as children and decorators. The cloned figure does not clone the list of FigureListeners from its original.
Reimplemented from org.jhotdraw.draw.figure.AbstractAttributedCompositeFigure.
Reimplemented in org.jhotdraw.draw.QuadTreeDrawing.
References org.jhotdraw.draw.AbstractDrawing.AbstractDrawing(), and org.jhotdraw.draw.AbstractDrawing.clone().
Referenced by org.jhotdraw.draw.AbstractDrawing.clone().
fireUndoableEditHappened()
void org.jhotdraw.draw.AbstractDrawing.fireUndoableEditHappened (UndoableEdit edit)
Notify all listenerList that have registered interest for notification on this event type.
Implements org.jhotdraw.draw.Drawing.
References org.jhotdraw.draw.figure.AbstractFigure.listenerList.
getDrawing()
Drawing org.jhotdraw.draw.AbstractDrawing.getDrawing ()
Reimplemented from org.jhotdraw.draw.figure.AbstractFigure.
getFontRenderContext()
FontRenderContext org.jhotdraw.draw.AbstractDrawing.getFontRenderContext ()
Returns the font render context used to do text leyout and text drawing.
Implements org.jhotdraw.draw.Drawing.
getInputFormats()
java.util.List<InputFormat> org.jhotdraw.draw.AbstractDrawing.getInputFormats ()
Gets input formats for the Drawing in order of preferred formats.
Implements org.jhotdraw.draw.Drawing.
getLock()
Object org.jhotdraw.draw.AbstractDrawing.getLock ()
The drawing view synchronizes on the lock when drawing a drawing.
Implements org.jhotdraw.draw.Drawing.
Referenced by org.jhotdraw.draw.DefaultDrawing.draw().
getOutputFormats()
java.util.List<OutputFormat> org.jhotdraw.draw.AbstractDrawing.getOutputFormats ()
Gets output formats for the Drawing in order of preferred formats.
Implements org.jhotdraw.draw.Drawing.
isDebugMode()
static boolean org.jhotdraw.draw.AbstractDrawing.isDebugMode () static
Referenced by org.jhotdraw.draw.QuadTreeDrawing.draw().
read()
void org.jhotdraw.draw.AbstractDrawing.read (DOMInput in) throws IOException
Reimplemented from org.jhotdraw.draw.figure.AbstractAttributedCompositeFigure.
References org.jhotdraw.draw.Drawing.add().
removeUndoableEditListener()
void org.jhotdraw.draw.AbstractDrawing.removeUndoableEditListener (UndoableEditListener l)
Removes a listener for undoable edit events.
Implements org.jhotdraw.draw.Drawing.
References org.jhotdraw.draw.figure.AbstractFigure.listenerList.
setDebugMode()
static void org.jhotdraw.draw.AbstractDrawing.setDebugMode (boolean debugMode) static
setFontRenderContext()
void org.jhotdraw.draw.AbstractDrawing.setFontRenderContext (FontRenderContext frc)
Sets the font render context used to do text leyout and text drawing.
Implements org.jhotdraw.draw.Drawing.
setInputFormats()
void org.jhotdraw.draw.AbstractDrawing.setInputFormats (java.util.List< InputFormat > formats)
setOutputFormats()
void org.jhotdraw.draw.AbstractDrawing.setOutputFormats (java.util.List< OutputFormat > formats)
write()
void org.jhotdraw.draw.AbstractDrawing.write (DOMOutput out) throws IOException
Reimplemented from org.jhotdraw.draw.figure.AbstractAttributedCompositeFigure.
References org.jhotdraw.draw.figure.AbstractCompositeFigure.getChildren().
The documentation for this class was generated from the following file:
jhotdraw-core/src/main/java/org/jhotdraw/draw/AbstractDrawing.java