jhotdraw: org.jhotdraw.draw.connector.Connector Interface Reference
org.jhotdraw.draw.connector.Connector Interface Reference
Public Member Functions
Point2D.Double findStart (ConnectionFigure connection)
Point2D.Double findEnd (ConnectionFigure connection)
Figure getOwner ()
Point2D.Double getAnchor ()
Rectangle2D.Double getBounds ()
void updateAnchor (Point2D.Double p)
boolean contains (Point2D.Double p)
Object clone ()
Rectangle2D.Double getDrawingArea ()
void draw (Graphics2D g)
Detailed Description
A connector knows how to locate the start point or the end point of a ConnectionFigure on a connected figure.
A connector is created and owned by a Figure.
A connector knows its owning figure. A connector has bounds which describe the area of the figure it is responsible for. A connector can be drawn, so that users can see the bounds of the connector.
Design Patterns
Framework
Two figures can be connected using a connection figure. The location of the start or end point of the connection is handled by a connector object at each connected figure.
Contract: org.jhotdraw.draw.Figure, ConnectionFigure, Connector, org.jhotdraw.draw.tool.ConnectionTool.
Strategy
The location of the start and end points of a connection figure are determined by
Connector
s which are owned by the connected figures.
Context: Figure, ConnectionFigure; Strategy: Connector.
Author
Werner Randelshofer
Version
$Id$
Member Function Documentation
clone()
Object org.jhotdraw.draw.connector.Connector.clone ()
Returns a clone of the Connection.
Implemented in org.jhotdraw.draw.connector.AbstractConnector.
Referenced by org.jhotdraw.draw.figure.LineConnectionFigure.clone().
contains()
boolean org.jhotdraw.draw.connector.Connector.contains (Point2D.Double p)
Tests if a point is contained in the connector.
Implemented in org.jhotdraw.draw.connector.LocatorConnector, and org.jhotdraw.draw.connector.AbstractConnector.
draw()
void org.jhotdraw.draw.connector.Connector.draw (Graphics2D g)
Draws the connector.
Implemented in org.jhotdraw.draw.connector.StickyRectangleConnector, and org.jhotdraw.draw.connector.AbstractConnector.
findEnd()
Point2D.Double org.jhotdraw.draw.connector.Connector.findEnd (ConnectionFigure connection)
Finds the end point for the connection.
Implemented in org.jhotdraw.draw.connector.ChopRectangleConnector, and org.jhotdraw.draw.connector.AbstractConnector.
Referenced by org.jhotdraw.draw.liner.CurvedLiner.lineout(), org.jhotdraw.draw.liner.ElbowLiner.lineout(), org.jhotdraw.draw.liner.SlantedLiner.lineout(), and org.jhotdraw.draw.figure.LineConnectionFigure.updateConnection().
findStart()
Point2D.Double org.jhotdraw.draw.connector.Connector.findStart (ConnectionFigure connection)
Finds the start point for the connection.
Implemented in org.jhotdraw.draw.connector.ChopRectangleConnector, and org.jhotdraw.draw.connector.AbstractConnector.
Referenced by org.jhotdraw.draw.liner.CurvedLiner.lineout(), org.jhotdraw.draw.liner.ElbowLiner.lineout(), org.jhotdraw.draw.liner.SlantedLiner.lineout(), and org.jhotdraw.draw.figure.LineConnectionFigure.updateConnection().
getAnchor()
Point2D.Double org.jhotdraw.draw.connector.Connector.getAnchor ()
Gets the anchor of the connector. This is a point at the center or at the bounds of the figure, where the start or the end point will most likely be attached. The purpose of this method is to give the user a hint, where the connector will most likely be attached to the owner of the connector.
Implemented in org.jhotdraw.draw.connector.StickyRectangleConnector, and org.jhotdraw.draw.connector.AbstractConnector.
Referenced by org.jhotdraw.draw.handle.ConnectorHandle.getLocation(), org.jhotdraw.draw.handle.ConnectorHandle.getLocationOnDrawing(), org.jhotdraw.draw.tool.ConnectionTool.mouseDragged(), org.jhotdraw.draw.tool.ConnectionTool.mousePressed(), org.jhotdraw.draw.tool.ConnectionTool.mouseReleased(), org.jhotdraw.draw.handle.AbstractConnectionHandle.trackStep(), and org.jhotdraw.draw.handle.ConnectorHandle.trackStep().
getBounds()
Rectangle2D.Double org.jhotdraw.draw.connector.Connector.getBounds ()
Gets the bounds of the connector. This usually are the bounds of the Figure which owns the Connector. The bounds can differ from the Figure bounds, if the Connector connects to a specific region of the Figure.
Implemented in org.jhotdraw.draw.connector.LocatorConnector, and org.jhotdraw.draw.connector.AbstractConnector.
Referenced by org.jhotdraw.draw.liner.CurvedLiner.lineout(), org.jhotdraw.draw.liner.ElbowLiner.lineout(), and org.jhotdraw.draw.liner.SlantedLiner.lineout().
getDrawingArea()
Rectangle2D.Double org.jhotdraw.draw.connector.Connector.getDrawingArea ()
Gets the drawing area of the connector.
Implemented in org.jhotdraw.draw.connector.AbstractConnector.
getOwner()
Figure org.jhotdraw.draw.connector.Connector.getOwner ()
Gets the connector's owner.
Implemented in org.jhotdraw.draw.connector.AbstractConnector.
Referenced by org.jhotdraw.draw.figure.LineConnectionFigure.canConnect(), org.jhotdraw.draw.handle.ConnectorHandle.ConnectorHandle(), org.jhotdraw.draw.connector.ChopRectangleConnector.findEnd(), org.jhotdraw.draw.connector.ChopRectangleConnector.findStart(), org.jhotdraw.draw.figure.LineConnectionFigure.getEndFigure(), and org.jhotdraw.draw.figure.LineConnectionFigure.getStartFigure().
updateAnchor()
void org.jhotdraw.draw.connector.Connector.updateAnchor (Point2D.Double p)
Updates the anchor of the connector. This method is called when the user manually changes the end point of the ConnectionFigure. The Connector uses this as a hint for choosing a new anchor position.
Implemented in org.jhotdraw.draw.connector.StickyRectangleConnector, and org.jhotdraw.draw.connector.AbstractConnector.
The documentation for this interface was generated from the following file:
jhotdraw-core/src/main/java/org/jhotdraw/draw/connector/Connector.java