jhotdraw: org.jhotdraw.draw.tool.Tool Interface Reference
org.jhotdraw.draw.tool.Tool Interface Reference
Public Member Functions
void activate (DrawingEditor editor)
void deactivate (DrawingEditor editor)
void addToolListener (ToolListener l)
void removeToolListener (ToolListener l)
void draw (Graphics2D g)
void editDelete ()
void editCut ()
void editCopy ()
void editDuplicate ()
void editPaste ()
String getToolTipText (DrawingView view, MouseEvent evt)
boolean supportsHandleInteraction ()
Detailed Description
A tool defines an editing mode of a DrawingEditor.
Tools are used for user interaction. Unlike figures, a tool works with the user interface coordinates of a DrawingView. The user interface coordinates are expressed in integer pixels.
When a tool is set on a drawing editor using
setTool
, the drawing editor registers the tool as a listener for mouse and keyboard events on all drawing views. The tool processes these events and perform edit operations on the figures of the drawing, on the drawing itself or even on the drawing view.
Tools inform listeners when they are done with an interaction by calling the ToolListener's
toolDone()
method.
In a typical application, tools are created once and reused.
A tool forwards UndoableEdit events to the Drawing object onto which it is performing changes.
If a tool does not handle a specific keyboard event, it looks up the
InputMap
of the drawing editor and then invokes the corresponding action in the
ActionMap
of the drawing editor. A tool can have an InputMap and ActionMap of its own which take precedence over the ones provided by the drawing editor.
Design Patterns
Framework
The following interfaces define the contracts of a framework for structured drawing editors:
Contract: Drawing, Figure, DrawingView, DrawingEditor, org.jhotdraw.draw.handle.Handle and Tool.
Mediator
DrawingEditor
acts as a mediator for coordinating drawing tools and drawing views:
Mediator: DrawingEditor; Colleagues: DrawingView, Tool.
Mediator
DrawingEditor
acts as a mediator for coordinating keyboard input from
Tool
s and Swing action objects:
Mediator: DrawingEditor; Colleagues: Tool, javax.swing.Action.
Observer
State changes of tools can be observed by other objects. Specifically
DrawingEditor
observes area invalidations of tools and repaints its active drawing view accordingly.
Subject: Tool; Observer: ToolListener; Event: org.jhotdraw.draw.event.ToolEvent; Concrete Observer: DrawingEditor.
Author
Werner Randelshofer
Version
$Id$
Member Function Documentation
activate()
void org.jhotdraw.draw.tool.Tool.activate (DrawingEditor editor)
Activates the tool for the given editor. This method is called whenever the user switches to this tool.
Implemented in org.jhotdraw.draw.tool.SelectionTool, org.jhotdraw.draw.tool.ImageTool, org.jhotdraw.draw.tool.DefaultSelectAreaTracker, org.jhotdraw.draw.tool.DefaultHandleTracker, org.jhotdraw.draw.tool.CreationTool, org.jhotdraw.draw.tool.ConnectionTool, org.jhotdraw.draw.tool.BezierTool, and org.jhotdraw.draw.tool.AbstractTool.
Referenced by org.jhotdraw.draw.tool.SelectionTool.activate(), org.jhotdraw.draw.DefaultDrawingEditor.setTool(), and org.jhotdraw.draw.tool.SelectionTool.setTracker().
addToolListener()
void org.jhotdraw.draw.tool.Tool.addToolListener (ToolListener l)
Adds a listener for this tool.
Implemented in org.jhotdraw.draw.tool.AbstractTool.
Referenced by org.jhotdraw.draw.tool.SelectionTool.SelectionTool(), org.jhotdraw.draw.DefaultDrawingEditor.setTool(), and org.jhotdraw.draw.tool.SelectionTool.setTracker().
deactivate()
void org.jhotdraw.draw.tool.Tool.deactivate (DrawingEditor editor)
Deactivates the tool. This method is called whenever the user switches to another tool.
Implemented in org.jhotdraw.draw.tool.TextEditingTool, org.jhotdraw.draw.tool.TextCreationTool, org.jhotdraw.draw.tool.TextAreaEditingTool, org.jhotdraw.draw.tool.TextAreaCreationTool, org.jhotdraw.draw.tool.SelectionTool, org.jhotdraw.draw.tool.DefaultSelectAreaTracker, org.jhotdraw.draw.tool.DefaultHandleTracker, org.jhotdraw.draw.tool.CreationTool, org.jhotdraw.draw.tool.ConnectionTool, org.jhotdraw.draw.tool.BezierTool, and org.jhotdraw.draw.tool.AbstractTool.
Referenced by org.jhotdraw.draw.tool.SelectionTool.deactivate(), org.jhotdraw.draw.DefaultDrawingEditor.setTool(), and org.jhotdraw.draw.tool.SelectionTool.setTracker().
draw()
void org.jhotdraw.draw.tool.Tool.draw (Graphics2D g)
Draws the tool.
Implemented in org.jhotdraw.draw.tool.TextAreaEditingTool, org.jhotdraw.draw.tool.TextAreaCreationTool, org.jhotdraw.draw.tool.SelectionTool, org.jhotdraw.draw.tool.DefaultSelectAreaTracker, org.jhotdraw.draw.tool.DefaultHandleTracker, org.jhotdraw.draw.tool.ConnectionTool, org.jhotdraw.draw.tool.BezierTool, and org.jhotdraw.draw.tool.AbstractTool.
Referenced by org.jhotdraw.draw.tool.SelectionTool.draw(), org.jhotdraw.draw.AbstractDrawingView.drawTool(), and org.jhotdraw.draw.DefaultDrawingView.drawTool().
editCopy()
void org.jhotdraw.draw.tool.Tool.editCopy ()
Copies the selection into the clipboard. Depending on the tool, this could be selected figures, selected points or selected text.
Implemented in org.jhotdraw.draw.tool.AbstractTool.
editCut()
void org.jhotdraw.draw.tool.Tool.editCut ()
Cuts the selection into the clipboard. Depending on the tool, this could be selected figures, selected points or selected text.
Implemented in org.jhotdraw.draw.tool.AbstractTool.
editDelete()
void org.jhotdraw.draw.tool.Tool.editDelete ()
Deletes the selection. Depending on the tool, this could be selected figures, selected points or selected text.
Implemented in org.jhotdraw.draw.tool.AbstractTool.
editDuplicate()
void org.jhotdraw.draw.tool.Tool.editDuplicate ()
Duplicates the selection. Depending on the tool, this could be selected figures, selected points or selected text.
Implemented in org.jhotdraw.draw.tool.AbstractTool.
editPaste()
void org.jhotdraw.draw.tool.Tool.editPaste ()
Pastes the contents of the clipboard. Depending on the tool, this could be selected figures, selected points or selected text.
Implemented in org.jhotdraw.draw.tool.AbstractTool.
getToolTipText()
String org.jhotdraw.draw.tool.Tool.getToolTipText (DrawingView view, MouseEvent evt)
Returns the tooltip text for a mouse event on a drawing view.
Parameters
view A drawing view.
evt A mouse event.
Returns
A tooltip text or null.
Implemented in org.jhotdraw.draw.tool.DelegationSelectionTool, and org.jhotdraw.draw.tool.AbstractTool.
Referenced by org.jhotdraw.draw.AbstractDrawingView.getToolTipText(), and org.jhotdraw.draw.DefaultDrawingView.getToolTipText().
removeToolListener()
void org.jhotdraw.draw.tool.Tool.removeToolListener (ToolListener l)
Removes a listener for this tool.
Implemented in org.jhotdraw.draw.tool.AbstractTool.
Referenced by org.jhotdraw.draw.DefaultDrawingEditor.setTool(), and org.jhotdraw.draw.tool.SelectionTool.setTracker().
supportsHandleInteraction()
boolean org.jhotdraw.draw.tool.Tool.supportsHandleInteraction ()
Returns true, if this tool lets the user interact with handles.
Handles may draw differently, if interaction is not possible.
Returns
True, if this tool supports interaction with the handles.
Implemented in org.jhotdraw.draw.tool.SelectionTool, and org.jhotdraw.draw.tool.AbstractTool.
The documentation for this interface was generated from the following file:
jhotdraw-core/src/main/java/org/jhotdraw/draw/tool/Tool.java