jhotdraw: org.jhotdraw.draw.DrawingView Interface Reference
org.jhotdraw.draw.DrawingView Interface Reference
Public Member Functions
Drawing getDrawing ()
void setDrawing (Drawing d)
void setCursor (Cursor c)
boolean isFigureSelected (Figure checkFigure)
void addToSelection (Figure figure)
void addToSelection (Collection< Figure > figures)
void removeFromSelection (Figure figure)
void toggleSelection (Figure figure)
void clearSelection ()
void selectAll ()
Set< Figure > getSelectedFigures ()
int getSelectionCount ()
Handle findHandle (Point p)
Collection< Handle > getCompatibleHandles (Handle handle)
void setActiveHandle (Handle newValue)
Handle getActiveHandle ()
Figure findFigure (Point p)
Collection< Figure > findFigures (Rectangle r)
Collection< Figure > findFiguresWithin (Rectangle r)
void addNotify (DrawingEditor editor)
void removeNotify (DrawingEditor editor)
DrawingEditor getEditor ()
void addFigureSelectionListener (FigureSelectionListener fsl)
void removeFigureSelectionListener (FigureSelectionListener fsl)
void requestFocus ()
Point drawingToView (Point2D.Double p)
Point2D.Double viewToDrawing (Point p)
Rectangle drawingToView (Rectangle2D.Double p)
Rectangle2D.Double viewToDrawing (Rectangle p)
Constrainer getConstrainer ()
void setVisibleConstrainer (Constrainer constrainer)
Constrainer getVisibleConstrainer ()
void setInvisibleConstrainer (Constrainer constrainer)
Constrainer getInvisibleConstrainer ()
void setConstrainerVisible (boolean newValue)
boolean isConstrainerVisible ()
JComponent getComponent ()
AffineTransform getDrawingToViewTransform ()
double getScaleFactor ()
void setScaleFactor (double newValue)
void setHandleDetailLevel (int newValue)
int getHandleDetailLevel ()
void setEnabled (boolean newValue)
boolean isEnabled ()
void repaintHandles ()
void addPropertyChangeListener (PropertyChangeListener listener)
void removePropertyChangeListener (PropertyChangeListener listener)
void addMouseListener (MouseListener l)
void removeMouseListener (MouseListener l)
void addKeyListener (KeyListener l)
void removeKeyListener (KeyListener l)
void addMouseMotionListener (MouseMotionListener l)
void removeMouseMotionListener (MouseMotionListener l)
void addMouseWheelListener (MouseWheelListener l)
void removeMouseWheelListener (MouseWheelListener l)
Static Public Attributes
static final String DRAWING_PROPERTY = "drawing"
static final String CURSOR_PROPERTY = "cursor"
static final String CONSTRAINER_PROPERTY = "constrainer"
static final String VISIBLE_CONSTRAINER_PROPERTY = "visibleConstrainer"
static final String INVISIBLE_CONSTRAINER_PROPERTY = "invisibleConstrainer"
static final String CONSTRAINER_VISIBLE_PROPERTY = "constrainerVisible"
static final String SCALE_FACTOR_PROPERTY = "scaleFactor"
static final String HANDLE_DETAIL_LEVEL_PROPERTY = "handleDetailLevel"
static final String ENABLED_PROPERTY = "enabled"
static final String ACTIVE_HANDLE_PROPERTY = "activeHandle"
Detailed Description
A drawing view paints a Drawing on a
JComponent
.
A drawing view can hold only one drawing at a time, but a drawing can be in multiple drawing views at the same time.
DrawingView
can paint the drawing with a scale factor. It supports conversion between view coordinates and drawing coordinates.
DrawingView
maintains a selection of the Figures contained in the drawing. When a figure is selected, the drawing view request Handles from the figure and draws them on top of the drawing.
To support editing, a drawing view needs to be added to a DrawingEditor. The current org.jhotdraw.draw.tool.Tool of the drawing editor receives mouse and key events from all drawing views of the drawing editor. When added to an editor, the drawing view paints the current org.jhotdraw.draw.tool.Tool on top of the drawing. The selected figures and handles can be the targets of the current tool of the drawing editor.
Editing operations can be constrained, for example by a grid. The constraints are defined by a Constrainer object. Handles and tools should take the constrainer of the drawing view into account when editing a figure.
The painting process of
DrawingView
view involves the following steps:
Paint the background of the drawing view.
Invoke Drawing#drawCanvas.
Invoke Constrainer#draw if a constrainer is set.
Invoke Drawing#draw.
Invoke org.jhotdraw.draw.handle.Handle#draw on the handles of selected figures.
Invoke org.jhotdraw.draw.tool.Tool#draw if the drawing view is the active view of the
DrawingEditor
.
Design Patterns
Framework
The following interfaces define the contracts of a framework for structured drawing editors:
Contract: Drawing, Figure, DrawingView, DrawingEditor, org.jhotdraw.draw.handle.Handle and org.jhotdraw.draw.tool.Tool.
Chain of responsibility
Mouse and keyboard events of the user occur on the drawing view, and are preprocessed by the
DragTracker
of a
SelectionTool
. In turn
org.jhotdraw.draw.selectiontool.DragTracker
invokes "track" methods on a
Handle
which in turn changes an aspect of a figure.
Client: org.jhotdraw.draw.tool.SelectionTool; Handler: org.jhotdraw.draw.tool.DragTracker, org.jhotdraw.draw.handle.Handle.
Mediator
DrawingEditor
acts as a mediator for coordinating drawing tools and drawing views:
Mediator: DrawingEditor; Colleagues: DrawingView, org.jhotdraw.draw.tool.Tool.
Model-View-Controller
The following classes implement together the Model-View-Controller design pattern:
Model: Drawing; View: DrawingView; Controller: DrawingEditor.
Observer
Selection changes of
DrawingView
are observed by user interface components which act on selected figures.
Subject: org.jhotdraw.draw.DrawingView; Observer: org.jhotdraw.draw.event.FigureSelectionListener; Event: org.jhotdraw.draw.event.FigureSelectionEvent.
Observer
State changes of figures can be observed by other objects. Specifically
CompositeFigure
observes area invalidations and remove requests of its child figures.
DrawingView
also observes area invalidations of its drawing object. Subject: Figure; Observer: org.jhotdraw.draw.event.FigureListener; Event: org.jhotdraw.draw.event.FigureEvent; Concrete Observer: CompositeFigure, DrawingView.
Observer
State changes of handles can be observed by other objects. Specifically
DrawingView
observes area invalidations and remove requests of handles.
Subject: Handle; Observer: org.jhotdraw.draw.event.HandleListener; Event: org.jhotdraw.draw.event.HandleEvent; Concrete Observer: DrawingView.
Strategy
Editing can be constrained by a constrainer which is associated to a drawing view.
Context: DrawingView; Strategy: Constrainer.
Author
Werner Randelshofer
Version
$Id$
Member Function Documentation
addFigureSelectionListener()
void org.jhotdraw.draw.DrawingView.addFigureSelectionListener (FigureSelectionListener fsl)
Add a listener for selection changes in this DrawingView.
Parameters
fsl jhotdraw.framework.FigureSelectionListener
Implemented in org.jhotdraw.draw.DefaultDrawingView, and org.jhotdraw.draw.AbstractDrawingView.
Referenced by org.jhotdraw.draw.event.SelectionComponentDisplayer.propertyChange(), org.jhotdraw.draw.event.SelectionComponentRepainter.propertyChange(), org.jhotdraw.draw.event.SelectionComponentDisplayer.SelectionComponentDisplayer(), org.jhotdraw.draw.event.SelectionComponentRepainter.SelectionComponentRepainter(), and org.jhotdraw.draw.event.AbstractAttributeEditorHandler< T >.updateActiveView().
addKeyListener()
void org.jhotdraw.draw.DrawingView.addKeyListener (KeyListener l)
Adds a key listener to the drawing view.
Parameters
l the listener.
Implemented in org.jhotdraw.draw.DelegatorDrawingView.
Referenced by org.jhotdraw.draw.DefaultDrawingEditor.add().
addMouseListener()
void org.jhotdraw.draw.DrawingView.addMouseListener (MouseListener l)
Adds a mouse listener to the drawing view.
Parameters
l the listener.
Implemented in org.jhotdraw.draw.DelegatorDrawingView.
Referenced by org.jhotdraw.draw.DefaultDrawingEditor.add().
addMouseMotionListener()
void org.jhotdraw.draw.DrawingView.addMouseMotionListener (MouseMotionListener l)
Adds a mouse motion listener to the drawing view.
Parameters
l the listener.
Implemented in org.jhotdraw.draw.DelegatorDrawingView.
Referenced by org.jhotdraw.draw.DefaultDrawingEditor.add().
addMouseWheelListener()
void org.jhotdraw.draw.DrawingView.addMouseWheelListener (MouseWheelListener l)
Implemented in org.jhotdraw.draw.DelegatorDrawingView.
addNotify()
void org.jhotdraw.draw.DrawingView.addNotify (DrawingEditor editor)
Informs the view that it has been added to the specified editor. The view must draw the tool of the editor, if getActiveView() of the editor returns the view.
Implemented in org.jhotdraw.draw.DefaultDrawingView, and org.jhotdraw.draw.AbstractDrawingView.
Referenced by org.jhotdraw.draw.DefaultDrawingEditor.add().
addPropertyChangeListener()
void org.jhotdraw.draw.DrawingView.addPropertyChangeListener (PropertyChangeListener listener)
Adds a property change listener to the drawing view.
Parameters
listener
Implemented in org.jhotdraw.draw.AbstractDrawingView.
Referenced by org.jhotdraw.draw.event.DrawingComponentRepainter.DrawingComponentRepainter(), org.jhotdraw.draw.event.DrawingComponentRepainter.propertyChange(), org.jhotdraw.draw.event.SelectionComponentDisplayer.propertyChange(), org.jhotdraw.draw.event.SelectionComponentRepainter.propertyChange(), org.jhotdraw.draw.event.SelectionComponentDisplayer.SelectionComponentDisplayer(), org.jhotdraw.draw.event.SelectionComponentRepainter.SelectionComponentRepainter(), and org.jhotdraw.draw.event.AbstractAttributeEditorHandler< T >.updateActiveView().
addToSelection() [1/2]
void org.jhotdraw.draw.DrawingView.addToSelection (Collection< Figure > figures)
Adds a collection of figures to the current selection.
Implemented in org.jhotdraw.draw.DefaultDrawingView, and org.jhotdraw.draw.AbstractDrawingView.
addToSelection() [2/2]
void org.jhotdraw.draw.DrawingView.addToSelection (Figure figure)
Adds a figure to the current selection.
Implemented in org.jhotdraw.draw.DefaultDrawingView, and org.jhotdraw.draw.AbstractDrawingView.
Referenced by org.jhotdraw.draw.tool.CreationTool.creationFinished(), org.jhotdraw.draw.tool.TextAreaCreationTool.creationFinished(), org.jhotdraw.draw.DefaultDrawingViewTransferHandler.exportDone(), org.jhotdraw.draw.tool.BezierTool.finishCreation(), org.jhotdraw.draw.tool.BezierTool.fireUndoEvent(), org.jhotdraw.draw.action.GroupAction.groupFigures(), org.jhotdraw.draw.tool.DelegationSelectionTool.handleDoubleClick(), org.jhotdraw.draw.DefaultDrawingViewTransferHandler.importData(), org.jhotdraw.draw.handle.BezierNodeHandle.keyPressed(), org.jhotdraw.draw.tool.DnDTracker.mouseDragged(), org.jhotdraw.draw.tool.TextCreationTool.mousePressed(), org.jhotdraw.draw.tool.DefaultDragTracker.mousePressed(), org.jhotdraw.draw.tool.DnDTracker.mousePressed(), org.jhotdraw.draw.action.SelectSameAction.selectSame(), org.jhotdraw.draw.handle.BezierNodeHandle.trackDoubleClick(), org.jhotdraw.draw.handle.ConnectorHandle.trackEnd(), and org.jhotdraw.draw.action.GroupAction.ungroupFigures().
clearSelection()
void org.jhotdraw.draw.DrawingView.clearSelection ()
Clears the current selection.
Implemented in org.jhotdraw.draw.DefaultDrawingView, and org.jhotdraw.draw.AbstractDrawingView.
Referenced by org.jhotdraw.draw.tool.TextAreaCreationTool.creationFinished(), org.jhotdraw.draw.DefaultDrawingViewTransferHandler.exportDone(), org.jhotdraw.draw.tool.BezierTool.fireUndoEvent(), org.jhotdraw.draw.action.GroupAction.groupFigures(), org.jhotdraw.draw.tool.DelegationSelectionTool.handleDoubleClick(), org.jhotdraw.draw.DefaultDrawingViewTransferHandler.importData(), org.jhotdraw.draw.tool.DnDTracker.mouseDragged(), org.jhotdraw.draw.tool.TextCreationTool.mousePressed(), org.jhotdraw.draw.tool.BezierTool.mousePressed(), org.jhotdraw.draw.tool.ConnectionTool.mousePressed(), org.jhotdraw.draw.tool.CreationTool.mousePressed(), org.jhotdraw.draw.tool.DefaultDragTracker.mousePressed(), org.jhotdraw.draw.tool.DnDTracker.mousePressed(), org.jhotdraw.draw.tool.SelectionTool.mousePressed(), org.jhotdraw.draw.handle.ConnectorHandle.trackEnd(), and org.jhotdraw.draw.action.GroupAction.ungroupFigures().
drawingToView() [1/2]
Point org.jhotdraw.draw.DrawingView.drawingToView (Point2D.Double p)
Converts drawing coordinates to view coordinates.
Implemented in org.jhotdraw.draw.DefaultDrawingView, and org.jhotdraw.draw.AbstractDrawingView.
Referenced by org.jhotdraw.draw.handle.AbstractConnectionHandle.basicGetBounds(), org.jhotdraw.draw.handle.BezierOutlineHandle.basicGetBounds(), org.jhotdraw.draw.handle.OrientationHandle.basicGetBounds(), org.jhotdraw.draw.handle.TextOverflowHandle.basicGetBounds(), org.jhotdraw.draw.handle.BezierControlPointHandle.draw(), org.jhotdraw.draw.handle.ConnectorHandle.draw(), org.jhotdraw.draw.tool.BezierTool.draw(), org.jhotdraw.draw.tool.ConnectionTool.draw(), org.jhotdraw.draw.DefaultDrawingViewTransferHandler.exportAsDrag(), org.jhotdraw.draw.tool.AbstractTool.fireAreaInvalidated(), org.jhotdraw.draw.handle.ConnectorHandle.getDrawingArea(), org.jhotdraw.draw.handle.AbstractRotateHandle.getLocation(), org.jhotdraw.draw.handle.BezierControlPointHandle.getLocation(), org.jhotdraw.draw.handle.BezierNodeHandle.getLocation(), org.jhotdraw.draw.handle.BezierScaleHandle.getLocation(), org.jhotdraw.draw.handle.ConnectorHandle.getLocation(), org.jhotdraw.draw.handle.LocatorHandle.getLocation(), org.jhotdraw.draw.tool.BezierTool.mouseMoved(), org.jhotdraw.draw.handle.AbstractConnectionHandle.repaintConnectors(), org.jhotdraw.draw.handle.ConnectorHandle.repaintConnectors(), org.jhotdraw.draw.text.FloatingTextArea.setBounds(), org.jhotdraw.draw.handle.RoundRectangleRadiusHandle.trackEnd(), org.jhotdraw.draw.handle.OrientationHandle.trackStart(), org.jhotdraw.draw.handle.RoundRectangleRadiusHandle.trackStart(), org.jhotdraw.draw.handle.RoundRectangleRadiusHandle.trackStep(), and org.jhotdraw.draw.text.FloatingTextField.updateWidget().
drawingToView() [2/2]
Rectangle org.jhotdraw.draw.DrawingView.drawingToView (Rectangle2D.Double p)
Converts drawing coordinates to view coordinates.
Implemented in org.jhotdraw.draw.DefaultDrawingView, and org.jhotdraw.draw.AbstractDrawingView.
findFigure()
Figure org.jhotdraw.draw.DrawingView.findFigure (Point p)
Finds a figure at the given point.
Returns
A figure, null if no figure is found.
Implemented in org.jhotdraw.draw.DefaultDrawingView, and org.jhotdraw.draw.AbstractDrawingView.
Referenced by org.jhotdraw.draw.DefaultDrawingViewTransferHandler.exportAsDrag(), org.jhotdraw.draw.tool.DelegationSelectionTool.getToolTipText(), org.jhotdraw.draw.tool.DelegationSelectionTool.handleDoubleClick(), org.jhotdraw.draw.tool.DelegationSelectionTool.handlePopupMenu(), org.jhotdraw.draw.tool.DnDTracker.mouseDragged(), org.jhotdraw.draw.tool.DefaultHandleTracker.mouseMoved(), org.jhotdraw.draw.tool.DefaultSelectAreaTracker.mouseMoved(), org.jhotdraw.draw.tool.SelectionTool.mousePressed(), and org.jhotdraw.draw.tool.AbstractTool.updateCursor().
findFigures()
Collection<Figure> org.jhotdraw.draw.DrawingView.findFigures (Rectangle r)
Returns all figures that lie within or intersect the specified bounds. The figures are returned in Z-order from back to front.
Implemented in org.jhotdraw.draw.DefaultDrawingView, and org.jhotdraw.draw.AbstractDrawingView.
findFiguresWithin()
Collection<Figure> org.jhotdraw.draw.DrawingView.findFiguresWithin (Rectangle r)
Returns all figures that lie within the specified bounds. The figures are returned in Z-order from back to front.
Implemented in org.jhotdraw.draw.DefaultDrawingView, and org.jhotdraw.draw.AbstractDrawingView.
findHandle()
Handle org.jhotdraw.draw.DrawingView.findHandle (Point p)
Finds a handle at the given coordinates.
Returns
A handle, null if no handle is found.
Implemented in org.jhotdraw.draw.DefaultDrawingView, and org.jhotdraw.draw.AbstractDrawingView.
Referenced by org.jhotdraw.draw.tool.DelegationSelectionTool.getToolTipText(), org.jhotdraw.draw.tool.DelegationSelectionTool.handleDoubleClick(), org.jhotdraw.draw.tool.DelegationSelectionTool.handleMultiClick(), org.jhotdraw.draw.tool.SelectionTool.mousePressed(), and org.jhotdraw.draw.tool.AbstractTool.updateCursor().
getActiveHandle()
Handle org.jhotdraw.draw.DrawingView.getActiveHandle ()
Gets the active handle.
Implemented in org.jhotdraw.draw.DefaultDrawingView, and org.jhotdraw.draw.AbstractDrawingView.
getCompatibleHandles()
Collection<Handle> org.jhotdraw.draw.DrawingView.getCompatibleHandles (Handle handle)
Gets compatible handles.
Returns
A collection containing the handle and all compatible handles.
Implemented in org.jhotdraw.draw.DefaultDrawingView, and org.jhotdraw.draw.AbstractDrawingView.
getComponent()
JComponent org.jhotdraw.draw.DrawingView.getComponent ()
Returns the JComponent of the drawing view.
The drawing framework supports only two use cases, where this component may be accessed:
The component can be used to add the drawing view to a parent Swing component.
The currently active org.jhotdraw.draw.tool.Tool may add child components to the drawing view. The tool must remove these components when it becomes inactive.
Implemented in org.jhotdraw.draw.DelegatorDrawingView, and org.jhotdraw.draw.DefaultDrawingView.
Referenced by org.jhotdraw.draw.action.ZoomAction.actionPerformed(), org.jhotdraw.draw.tool.ImageTool.activate(), org.jhotdraw.draw.DefaultDrawingEditor.add(), org.jhotdraw.draw.text.FloatingTextArea.createOverlay(), org.jhotdraw.draw.text.FloatingTextField.createOverlay(), org.jhotdraw.draw.text.FloatingTextArea.endOverlay(), org.jhotdraw.draw.text.FloatingTextField.endOverlay(), org.jhotdraw.draw.tool.ConnectionTool.mouseDragged(), org.jhotdraw.draw.tool.DnDTracker.mouseDragged(), org.jhotdraw.draw.tool.BezierTool.mouseMoved(), org.jhotdraw.draw.handle.AbstractConnectionHandle.repaintConnectors(), org.jhotdraw.draw.handle.ConnectorHandle.repaintConnectors(), and org.jhotdraw.draw.tool.ConnectionTool.repaintConnectors().
getConstrainer()
Constrainer org.jhotdraw.draw.DrawingView.getConstrainer ()
Gets the current constrainer of this view. If isConstrainerVisible is true, this method returns getVisibleConstrainer, otherwise it returns getInvisibleConstrainer. This is a bound property.
Implemented in org.jhotdraw.draw.DefaultDrawingView, and org.jhotdraw.draw.AbstractDrawingView.
Referenced by org.jhotdraw.draw.action.MoveConstrainedAction.actionPerformed(), org.jhotdraw.draw.tool.AbstractTool.constrainPoint(), org.jhotdraw.draw.tool.ConnectionTool.mouseDragged(), org.jhotdraw.draw.tool.DefaultDragTracker.mouseDragged(), org.jhotdraw.draw.tool.BezierTool.mousePressed(), org.jhotdraw.draw.handle.AbstractConnectionHandle.trackEnd(), org.jhotdraw.draw.handle.ConnectorHandle.trackEnd(), org.jhotdraw.draw.handle.MoveHandle.trackStart(), org.jhotdraw.draw.handle.AbstractConnectionHandle.trackStep(), org.jhotdraw.draw.handle.AbstractRotateHandle.trackStep(), org.jhotdraw.draw.handle.BezierControlPointHandle.trackStep(), org.jhotdraw.draw.handle.BezierNodeHandle.trackStep(), and org.jhotdraw.draw.handle.MoveHandle.trackStep().
getDrawing()
Drawing org.jhotdraw.draw.DrawingView.getDrawing ()
Gets the drawing. This is a bound property.
Implemented in org.jhotdraw.draw.DefaultDrawingView, and org.jhotdraw.draw.AbstractDrawingView.
Referenced by org.jhotdraw.draw.action.AttributeToggler< T >.actionPerformed(), org.jhotdraw.draw.action.DrawingAttributeAction.actionPerformed(), org.jhotdraw.draw.action.ApplyAttributesAction.applyAttributes(), org.jhotdraw.draw.action.DrawingColorChooserHandler.applySelectedColorToFigures(), org.jhotdraw.draw.action.BringToFrontAction.bringToFront(), org.jhotdraw.draw.DefaultDrawingViewTransferHandler.canImport(), org.jhotdraw.draw.DefaultDrawingViewTransferHandler.createTransferable(), org.jhotdraw.draw.event.DrawingComponentRepainter.dispose(), org.jhotdraw.draw.event.SelectionComponentRepainter.dispose(), org.jhotdraw.draw.event.DrawingComponentRepainter.DrawingComponentRepainter(), org.jhotdraw.draw.tool.AbstractTool.editDelete(), org.jhotdraw.draw.DefaultDrawingViewTransferHandler.exportDone(), org.jhotdraw.draw.handle.AbstractHandle.fireUndoableEditHappened(), org.jhotdraw.draw.tool.BezierTool.fireUndoEvent(), org.jhotdraw.draw.action.AbstractDrawingEditorAction.getDrawing(), org.jhotdraw.draw.action.AbstractDrawingViewAction.getDrawing(), org.jhotdraw.draw.action.AbstractSelectedAction.getDrawing(), org.jhotdraw.draw.tool.AbstractTool.getDrawing(), org.jhotdraw.draw.event.DrawingAttributeEditorHandler< T >.getEditedFigures(), org.jhotdraw.draw.action.DrawingColorChooserAction.getInitialColor(), org.jhotdraw.draw.DefaultDrawingViewTransferHandler.getSourceActions(), org.jhotdraw.draw.action.GroupAction.groupFigures(), org.jhotdraw.draw.DefaultDrawingViewTransferHandler.importData(), org.jhotdraw.draw.handle.BezierControlPointHandle.keyPressed(), org.jhotdraw.draw.handle.BezierNodeHandle.keyPressed(), org.jhotdraw.draw.tool.DefaultHandleTracker.mouseMoved(), org.jhotdraw.draw.tool.DefaultSelectAreaTracker.mouseMoved(), org.jhotdraw.draw.tool.SelectionTool.mousePressed(), org.jhotdraw.draw.action.DrawingColorIcon.paintIcon(), org.jhotdraw.draw.event.DrawingComponentRepainter.propertyChange(), org.jhotdraw.draw.event.SelectionComponentRepainter.propertyChange(), org.jhotdraw.draw.event.SelectionComponentRepainter.SelectionComponentRepainter(), org.jhotdraw.draw.action.SendToBackAction.sendToBack(), org.jhotdraw.draw.handle.AbstractConnectionHandle.trackEnd(), org.jhotdraw.draw.handle.AbstractRotateHandle.trackEnd(), org.jhotdraw.draw.handle.BezierControlPointHandle.trackEnd(), org.jhotdraw.draw.handle.BezierNodeHandle.trackEnd(), org.jhotdraw.draw.handle.BezierScaleHandle.trackEnd(), org.jhotdraw.draw.handle.ConnectorHandle.trackEnd(), org.jhotdraw.draw.handle.BezierControlPointHandle.trackStart(), org.jhotdraw.draw.handle.BezierNodeHandle.trackStart(), org.jhotdraw.draw.handle.ConnectorHandle.trackStart(), org.jhotdraw.draw.handle.AbstractConnectionHandle.trackStep(), org.jhotdraw.draw.handle.ConnectorHandle.trackStep(), org.jhotdraw.draw.action.GroupAction.ungroupFigures(), org.jhotdraw.draw.tool.AbstractTool.updateCursor(), org.jhotdraw.draw.action.DrawingColorChooserHandler.updateEnabledState(), and org.jhotdraw.draw.event.AbstractAttributeEditorHandler< T >.updateFigures().
getDrawingToViewTransform()
AffineTransform org.jhotdraw.draw.DrawingView.getDrawingToViewTransform ()
Gets an transform which can be used to convert drawing coordinates to view coordinates.
Implemented in org.jhotdraw.draw.DelegatorDrawingView, org.jhotdraw.draw.DefaultDrawingView, and org.jhotdraw.draw.AbstractDrawingView.
Referenced by org.jhotdraw.draw.handle.BoundsOutlineHandle.basicGetBounds(), org.jhotdraw.draw.handle.AbstractConnectionHandle.draw(), org.jhotdraw.draw.handle.BezierOutlineHandle.draw(), org.jhotdraw.draw.handle.BoundsOutlineHandle.draw(), org.jhotdraw.draw.handle.ConnectorHandle.draw(), org.jhotdraw.draw.tool.ConnectionTool.draw(), and org.jhotdraw.draw.GridConstrainer.draw().
getEditor()
DrawingEditor org.jhotdraw.draw.DrawingView.getEditor ()
Gets the drawing editor associated to the DrawingView. This is a bound property.
Implemented in org.jhotdraw.draw.DefaultDrawingView, and org.jhotdraw.draw.AbstractDrawingView.
Referenced by org.jhotdraw.draw.handle.AbstractHandle.getEditor(), and org.jhotdraw.draw.DefaultDrawingViewTransferHandler.importData().
getHandleDetailLevel()
int org.jhotdraw.draw.DrawingView.getHandleDetailLevel ()
Returns the detail level of the handles. This is a bound property.
Implemented in org.jhotdraw.draw.DefaultDrawingView, and org.jhotdraw.draw.AbstractDrawingView.
Referenced by org.jhotdraw.draw.tool.DelegationSelectionTool.handleDoubleClick(), org.jhotdraw.draw.figure.BezierFigure.handleMouseClick(), org.jhotdraw.draw.figure.LineFigure.handleMouseClick(), org.jhotdraw.draw.tool.DelegationSelectionTool.handleMultiClick(), and org.jhotdraw.draw.action.IncreaseHandleDetailLevelAction.increaseHandleDetaiLevel().
getInvisibleConstrainer()
Constrainer org.jhotdraw.draw.DrawingView.getInvisibleConstrainer ()
Gets the editor's constrainer for this view, for use, when the visible constrainer is turned off. This is a bound property.
Implemented in org.jhotdraw.draw.DefaultDrawingView, and org.jhotdraw.draw.AbstractDrawingView.
getScaleFactor()
double org.jhotdraw.draw.DrawingView.getScaleFactor ()
Gets the scale factor of the drawing view. This is a bound property.
Implemented in org.jhotdraw.draw.DelegatorDrawingView, and org.jhotdraw.draw.DefaultDrawingView.
Referenced by org.jhotdraw.draw.action.ZoomAction.actionPerformed(), org.jhotdraw.draw.DefaultDrawingViewTransferHandler.createTransferable(), org.jhotdraw.draw.GridConstrainer.draw(), org.jhotdraw.draw.handle.RotateHandle.getOrigin(), org.jhotdraw.draw.figure.BezierFigure.handleMouseClick(), org.jhotdraw.draw.figure.LineConnectionFigure.handleMouseClick(), org.jhotdraw.draw.figure.LineFigure.handleMouseClick(), org.jhotdraw.draw.text.FloatingTextArea.updateWidget(), and org.jhotdraw.draw.text.FloatingTextField.updateWidget().
getSelectedFigures()
Set<Figure> org.jhotdraw.draw.DrawingView.getSelectedFigures ()
Gets the selected figures. Returns an empty set, if no figures are selected.
Implemented in org.jhotdraw.draw.DefaultDrawingView, and org.jhotdraw.draw.AbstractDrawingView.
Referenced by org.jhotdraw.draw.action.AttributeToggler< T >.actionPerformed(), org.jhotdraw.draw.action.BringToFrontAction.actionPerformed(), org.jhotdraw.draw.action.GroupAction.actionPerformed(), org.jhotdraw.draw.action.SendToBackAction.actionPerformed(), org.jhotdraw.draw.action.ApplyAttributesAction.applyAttributes(), org.jhotdraw.draw.action.GroupAction.canUngroup(), org.jhotdraw.draw.DefaultDrawingViewTransferHandler.createTransferable(), org.jhotdraw.draw.DefaultDrawingViewTransferHandler.exportAsDrag(), org.jhotdraw.draw.event.FigureAttributeEditorHandler< T >.getEditedFigures(), org.jhotdraw.draw.action.SelectionColorChooserAction.getInitialColor(), org.jhotdraw.draw.tool.DelegationSelectionTool.handleDoubleClick(), org.jhotdraw.draw.tool.DnDTracker.mouseDragged(), org.jhotdraw.draw.tool.DefaultHandleTracker.mouseMoved(), org.jhotdraw.draw.tool.DefaultSelectAreaTracker.mouseMoved(), org.jhotdraw.draw.tool.DefaultDragTracker.mousePressed(), org.jhotdraw.draw.tool.DnDTracker.mousePressed(), org.jhotdraw.draw.tool.SelectionTool.mousePressed(), org.jhotdraw.draw.action.SelectionColorIcon.paintIcon(), and org.jhotdraw.draw.action.PickAttributesAction.pickAttributes().
getSelectionCount()
int org.jhotdraw.draw.DrawingView.getSelectionCount ()
Gets the number of selected figures.
Implemented in org.jhotdraw.draw.DefaultDrawingView, and org.jhotdraw.draw.AbstractDrawingView.
Referenced by org.jhotdraw.draw.action.GroupAction.canGroup(), org.jhotdraw.draw.action.GroupAction.canUngroup(), org.jhotdraw.draw.DefaultDrawingViewTransferHandler.getSourceActions(), and org.jhotdraw.draw.event.SelectionComponentDisplayer.updateVisibility().
getVisibleConstrainer()
Constrainer org.jhotdraw.draw.DrawingView.getVisibleConstrainer ()
Gets the editor's constrainer for this view, for use, when the visible constrainer is turned on. This is a bound property.
Implemented in org.jhotdraw.draw.DefaultDrawingView, and org.jhotdraw.draw.AbstractDrawingView.
isConstrainerVisible()
boolean org.jhotdraw.draw.DrawingView.isConstrainerVisible ()
Returns true, if the visible Constrainer is in use, returns false, if the invisible Constrainer is in use. This is a bound property.
Implemented in org.jhotdraw.draw.DefaultDrawingView, and org.jhotdraw.draw.AbstractDrawingView.
Referenced by org.jhotdraw.draw.action.ToggleGridAction.actionPerformed(), and org.jhotdraw.draw.action.ToggleGridAction.updateViewState().
isEnabled()
boolean org.jhotdraw.draw.DrawingView.isEnabled ()
Gets the enabled state of the drawing view. This is a bound property.
Implemented in org.jhotdraw.draw.DelegatorDrawingView.
Referenced by org.jhotdraw.draw.tool.AbstractTool.updateCursor(), org.jhotdraw.draw.tool.CreationTool.updateCursor(), org.jhotdraw.draw.tool.TextCreationTool.updateCursor(), and org.jhotdraw.draw.tool.TextEditingTool.updateCursor().
isFigureSelected()
boolean org.jhotdraw.draw.DrawingView.isFigureSelected (Figure checkFigure)
Test whether a given figure is selected.
Implemented in org.jhotdraw.draw.DefaultDrawingView, and org.jhotdraw.draw.AbstractDrawingView.
Referenced by org.jhotdraw.draw.tool.DefaultDragTracker.mousePressed(), and org.jhotdraw.draw.tool.DnDTracker.mousePressed().
removeFigureSelectionListener()
void org.jhotdraw.draw.DrawingView.removeFigureSelectionListener (FigureSelectionListener fsl)
Remove a listener for selection changes in this DrawingView.
Parameters
fsl jhotdraw.framework.FigureSelectionListener
Implemented in org.jhotdraw.draw.DefaultDrawingView, and org.jhotdraw.draw.AbstractDrawingView.
Referenced by org.jhotdraw.draw.event.SelectionComponentDisplayer.dispose(), org.jhotdraw.draw.event.SelectionComponentRepainter.dispose(), org.jhotdraw.draw.event.SelectionComponentDisplayer.propertyChange(), org.jhotdraw.draw.event.SelectionComponentRepainter.propertyChange(), and org.jhotdraw.draw.event.AbstractAttributeEditorHandler< T >.updateActiveView().
removeFromSelection()
void org.jhotdraw.draw.DrawingView.removeFromSelection (Figure figure)
Removes a figure from the selection.
Implemented in org.jhotdraw.draw.DefaultDrawingView, and org.jhotdraw.draw.AbstractDrawingView.
Referenced by org.jhotdraw.draw.handle.BezierNodeHandle.keyPressed(), and org.jhotdraw.draw.handle.BezierNodeHandle.trackDoubleClick().
removeKeyListener()
void org.jhotdraw.draw.DrawingView.removeKeyListener (KeyListener l)
Removes a key listener to the drawing view.
Parameters
l the listener.
Implemented in org.jhotdraw.draw.DelegatorDrawingView.
removeMouseListener()
void org.jhotdraw.draw.DrawingView.removeMouseListener (MouseListener l)
Removes a mouse listener to the drawing view.
Parameters
l the listener.
Implemented in org.jhotdraw.draw.DelegatorDrawingView.
removeMouseMotionListener()
void org.jhotdraw.draw.DrawingView.removeMouseMotionListener (MouseMotionListener l)
Removes a mouse motion listener to the drawing view.
Parameters
l the listener.
Implemented in org.jhotdraw.draw.DelegatorDrawingView.
removeMouseWheelListener()
void org.jhotdraw.draw.DrawingView.removeMouseWheelListener (MouseWheelListener l)
Implemented in org.jhotdraw.draw.DelegatorDrawingView.
removeNotify()
void org.jhotdraw.draw.DrawingView.removeNotify (DrawingEditor editor)
Informs the view that it has been removed from the specified editor. The view must not draw the tool from the editor anymore.
Implemented in org.jhotdraw.draw.DefaultDrawingView, and org.jhotdraw.draw.AbstractDrawingView.
removePropertyChangeListener()
void org.jhotdraw.draw.DrawingView.removePropertyChangeListener (PropertyChangeListener listener)
Removes a property change listener to the drawing view.
Parameters
listener
Implemented in org.jhotdraw.draw.AbstractDrawingView.
Referenced by org.jhotdraw.draw.event.DrawingComponentRepainter.dispose(), org.jhotdraw.draw.event.SelectionComponentDisplayer.dispose(), org.jhotdraw.draw.event.SelectionComponentRepainter.dispose(), org.jhotdraw.draw.event.DrawingComponentRepainter.propertyChange(), org.jhotdraw.draw.event.SelectionComponentDisplayer.propertyChange(), org.jhotdraw.draw.event.SelectionComponentRepainter.propertyChange(), and org.jhotdraw.draw.event.AbstractAttributeEditorHandler< T >.updateActiveView().
repaintHandles()
void org.jhotdraw.draw.DrawingView.repaintHandles ()
Repaints the handles of the view.
Implemented in org.jhotdraw.draw.DefaultDrawingView, and org.jhotdraw.draw.AbstractDrawingView.
requestFocus()
void org.jhotdraw.draw.DrawingView.requestFocus ()
This is a convenience method for invoking
getComponent().requestFocus()
.
Implemented in org.jhotdraw.draw.DelegatorDrawingView.
Referenced by org.jhotdraw.draw.tool.DelegationSelectionTool.mousePressed(), and org.jhotdraw.draw.tool.AbstractTool.mousePressed().
selectAll()
void org.jhotdraw.draw.DrawingView.selectAll ()
Selects all figures.
Implemented in org.jhotdraw.draw.DefaultDrawingView, and org.jhotdraw.draw.AbstractDrawingView.
setActiveHandle()
void org.jhotdraw.draw.DrawingView.setActiveHandle (Handle newValue)
Sets the active handle.
Implemented in org.jhotdraw.draw.DefaultDrawingView, and org.jhotdraw.draw.AbstractDrawingView.
Referenced by org.jhotdraw.draw.tool.DefaultHandleTracker.activate(), and org.jhotdraw.draw.tool.DefaultHandleTracker.deactivate().
setConstrainerVisible()
void org.jhotdraw.draw.DrawingView.setConstrainerVisible (boolean newValue)
Changes between a visible Constrainer and an invisible Constrainer. This is a bound property.
Implemented in org.jhotdraw.draw.DefaultDrawingView, and org.jhotdraw.draw.AbstractDrawingView.
Referenced by org.jhotdraw.draw.action.ToggleGridAction.actionPerformed().
setCursor()
void org.jhotdraw.draw.DrawingView.setCursor (Cursor c)
Sets the cursor of the DrawingView. This is a bound property.
Implemented in org.jhotdraw.draw.DelegatorDrawingView.
Referenced by org.jhotdraw.draw.tool.BezierTool.activate(), org.jhotdraw.draw.tool.CreationTool.activate(), org.jhotdraw.draw.tool.DefaultHandleTracker.activate(), org.jhotdraw.draw.tool.BezierTool.deactivate(), org.jhotdraw.draw.tool.CreationTool.deactivate(), org.jhotdraw.draw.tool.DefaultHandleTracker.deactivate(), org.jhotdraw.draw.DefaultDrawingView.setEnabled(), org.jhotdraw.draw.tool.AbstractTool.updateCursor(), org.jhotdraw.draw.tool.CreationTool.updateCursor(), org.jhotdraw.draw.tool.TextCreationTool.updateCursor(), and org.jhotdraw.draw.tool.TextEditingTool.updateCursor().
setDrawing()
void org.jhotdraw.draw.DrawingView.setDrawing (Drawing d)
Sets and installs another drawing in the view. This is a bound property.
Implemented in org.jhotdraw.draw.DefaultDrawingView, and org.jhotdraw.draw.AbstractDrawingView.
setEnabled()
void org.jhotdraw.draw.DrawingView.setEnabled (boolean newValue)
Sets the enabled state of the drawing view. This is a bound property.
Implemented in org.jhotdraw.draw.DelegatorDrawingView, and org.jhotdraw.draw.DefaultDrawingView.
setHandleDetailLevel()
void org.jhotdraw.draw.DrawingView.setHandleDetailLevel (int newValue)
The detail level of the handles. This is a bound property.
Implemented in org.jhotdraw.draw.DefaultDrawingView, and org.jhotdraw.draw.AbstractDrawingView.
Referenced by org.jhotdraw.draw.tool.DelegationSelectionTool.handleDoubleClick(), org.jhotdraw.draw.tool.DelegationSelectionTool.handleMultiClick(), org.jhotdraw.draw.action.IncreaseHandleDetailLevelAction.increaseHandleDetaiLevel(), org.jhotdraw.draw.tool.DefaultDragTracker.mousePressed(), org.jhotdraw.draw.tool.DnDTracker.mousePressed(), and org.jhotdraw.draw.tool.SelectionTool.mousePressed().
setInvisibleConstrainer()
void org.jhotdraw.draw.DrawingView.setInvisibleConstrainer (Constrainer constrainer)
Sets the editor's constrainer for this view, for use, when the visible constrainer is turned off. This is a bound property.
Implemented in org.jhotdraw.draw.DefaultDrawingView, and org.jhotdraw.draw.AbstractDrawingView.
setScaleFactor()
void org.jhotdraw.draw.DrawingView.setScaleFactor (double newValue)
Sets the scale factor of the drawing view. This is a bound property.
Implemented in org.jhotdraw.draw.DelegatorDrawingView, and org.jhotdraw.draw.DefaultDrawingView.
Referenced by org.jhotdraw.draw.action.ZoomAction.actionPerformed(), and org.jhotdraw.draw.action.ZoomEditorAction.actionPerformed().
setVisibleConstrainer()
void org.jhotdraw.draw.DrawingView.setVisibleConstrainer (Constrainer constrainer)
Sets the editor's constrainer for this view, for use, when the visible constrainer is turned on. This is a bound property.
Implemented in org.jhotdraw.draw.DefaultDrawingView, and org.jhotdraw.draw.AbstractDrawingView.
toggleSelection()
void org.jhotdraw.draw.DrawingView.toggleSelection (Figure figure)
If a figure isn't selected it is added to the selection. Otherwise it is removed from the selection.
Implemented in org.jhotdraw.draw.DefaultDrawingView, and org.jhotdraw.draw.AbstractDrawingView.
Referenced by org.jhotdraw.draw.tool.DefaultDragTracker.mousePressed(), and org.jhotdraw.draw.tool.DnDTracker.mousePressed().
viewToDrawing() [1/2]
Point2D.Double org.jhotdraw.draw.DrawingView.viewToDrawing (Point p)
Converts view coordinates to drawing coordinates.
Implemented in org.jhotdraw.draw.DefaultDrawingView, and org.jhotdraw.draw.AbstractDrawingView.
Referenced by org.jhotdraw.draw.GridConstrainer.draw(), org.jhotdraw.draw.tool.DefaultDragTracker.mouseDragged(), org.jhotdraw.draw.tool.DefaultHandleTracker.mouseMoved(), org.jhotdraw.draw.tool.DefaultSelectAreaTracker.mouseMoved(), org.jhotdraw.draw.tool.BezierTool.mousePressed(), org.jhotdraw.draw.tool.DefaultDragTracker.mousePressed(), org.jhotdraw.draw.tool.DnDTracker.mousePressed(), org.jhotdraw.draw.tool.SelectionTool.mousePressed(), org.jhotdraw.draw.tool.DefaultDragTracker.mouseReleased(), org.jhotdraw.draw.DefaultDrawingViewTransferHandler.moveToDropPoint(), org.jhotdraw.draw.handle.AbstractConnectionHandle.trackEnd(), org.jhotdraw.draw.handle.ConnectorHandle.trackEnd(), org.jhotdraw.draw.handle.RoundRectangleRadiusHandle.trackEnd(), org.jhotdraw.draw.handle.AbstractRotateHandle.trackStart(), org.jhotdraw.draw.handle.BezierScaleHandle.trackStart(), org.jhotdraw.draw.handle.MoveHandle.trackStart(), org.jhotdraw.draw.handle.AbstractConnectionHandle.trackStep(), org.jhotdraw.draw.handle.AbstractRotateHandle.trackStep(), org.jhotdraw.draw.handle.BezierControlPointHandle.trackStep(), org.jhotdraw.draw.handle.BezierNodeHandle.trackStep(), org.jhotdraw.draw.handle.BezierScaleHandle.trackStep(), org.jhotdraw.draw.handle.ConnectorHandle.trackStep(), org.jhotdraw.draw.handle.FontSizeHandle.trackStep(), org.jhotdraw.draw.handle.MoveHandle.trackStep(), org.jhotdraw.draw.handle.RoundRectangleRadiusHandle.trackStep(), and org.jhotdraw.draw.tool.AbstractTool.updateCursor().
viewToDrawing() [2/2]
Rectangle2D.Double org.jhotdraw.draw.DrawingView.viewToDrawing (Rectangle p)
Converts view coordinates to drawing coordinates.
Implemented in org.jhotdraw.draw.DefaultDrawingView, and org.jhotdraw.draw.AbstractDrawingView.
Member Data Documentation
ACTIVE_HANDLE_PROPERTY
final String org.jhotdraw.draw.DrawingView.ACTIVE_HANDLE_PROPERTY = "activeHandle" static
This constant is used to identify the activeHandle property of the DrawingView.
Referenced by org.jhotdraw.draw.AbstractDrawingView.setActiveHandle(), and org.jhotdraw.draw.DefaultDrawingView.setActiveHandle().
CONSTRAINER_PROPERTY
final String org.jhotdraw.draw.DrawingView.CONSTRAINER_PROPERTY = "constrainer" static
This constant is used to identify the constrainer property of the DrawingView.
CONSTRAINER_VISIBLE_PROPERTY
final String org.jhotdraw.draw.DrawingView.CONSTRAINER_VISIBLE_PROPERTY = "constrainerVisible" static
This constant is used to identify the constrainer visible property of the DrawingView.
Referenced by org.jhotdraw.draw.AbstractDrawingView.setConstrainerVisible(), and org.jhotdraw.draw.DefaultDrawingView.setConstrainerVisible().
CURSOR_PROPERTY
final String org.jhotdraw.draw.DrawingView.CURSOR_PROPERTY = "cursor" static
This constant is used to identify the cursor property of the DrawingView.
DRAWING_PROPERTY
final String org.jhotdraw.draw.DrawingView.DRAWING_PROPERTY = "drawing" static
This constant is used to identify the drawing property of the DrawingView.
Referenced by org.jhotdraw.draw.event.AbstractAttributeEditorHandler< T >.EventHandler.propertyChange(), org.jhotdraw.draw.event.DrawingComponentRepainter.propertyChange(), org.jhotdraw.draw.event.SelectionComponentRepainter.propertyChange(), org.jhotdraw.draw.AbstractDrawingView.setDrawing(), and org.jhotdraw.draw.DefaultDrawingView.setDrawing().
ENABLED_PROPERTY
final String org.jhotdraw.draw.DrawingView.ENABLED_PROPERTY = "enabled" static
This constant is used to identify the enabled property of the DrawingView.
HANDLE_DETAIL_LEVEL_PROPERTY
final String org.jhotdraw.draw.DrawingView.HANDLE_DETAIL_LEVEL_PROPERTY = "handleDetailLevel" static
This constant is used to identify the handle detail level property of the DrawingView.
INVISIBLE_CONSTRAINER_PROPERTY
final String org.jhotdraw.draw.DrawingView.INVISIBLE_CONSTRAINER_PROPERTY = "invisibleConstrainer" static
This constant is used to identify the invisible constrainer property of the DrawingView.
Referenced by org.jhotdraw.draw.AbstractDrawingView.setInvisibleConstrainer(), and org.jhotdraw.draw.DefaultDrawingView.setInvisibleConstrainer().
SCALE_FACTOR_PROPERTY
final String org.jhotdraw.draw.DrawingView.SCALE_FACTOR_PROPERTY = "scaleFactor" static
This constant is used to identify the scale factor property of the DrawingView.
VISIBLE_CONSTRAINER_PROPERTY
final String org.jhotdraw.draw.DrawingView.VISIBLE_CONSTRAINER_PROPERTY = "visibleConstrainer" static
This constant is used to identify the visible constrainer property of the DrawingView.
Referenced by org.jhotdraw.draw.AbstractDrawingView.setVisibleConstrainer(), and org.jhotdraw.draw.DefaultDrawingView.setVisibleConstrainer().
The documentation for this interface was generated from the following file:
jhotdraw-core/src/main/java/org/jhotdraw/draw/DrawingView.java