jhotdraw: org.jhotdraw.draw.layouter.Layouter Interface Reference
org.jhotdraw.draw.layouter.Layouter Interface Reference
Public Member Functions
Rectangle2D.Double calculateLayout (CompositeFigure compositeFigure, Point2D.Double anchor, Point2D.Double lead)
Rectangle2D.Double layout (CompositeFigure compositeFigure, Point2D.Double anchor, Point2D.Double lead)
Detailed Description
A Layouter encapsulates a strategy for laying out the child figures of a CompositeFigure.
Design Patterns
Strategy
Composite figures can be laid out using different layout algorithms which are implemented by layouters.
Context: CompositeFigure; Strategy: Layouter.
Author
Werner Randelshofer
Version
$Id$
Member Function Documentation
calculateLayout()
Rectangle2D.Double org.jhotdraw.draw.layouter.Layouter.calculateLayout (CompositeFigure compositeFigure, Point2D.Double anchor, Point2D.Double lead)
Calculate the layout for the figure and all its subelements. The layout is not actually performed but just its dimensions are calculated.
Parameters
anchor start point for the layout
lead minimum lead point for the layout
Implemented in org.jhotdraw.draw.layouter.VerticalLayouter, org.jhotdraw.draw.layouter.LocatorLayouter, and org.jhotdraw.draw.layouter.HorizontalLayouter.
Referenced by org.jhotdraw.draw.figure.AbstractCompositeFigure.getPreferredSize().
layout()
Rectangle2D.Double org.jhotdraw.draw.layouter.Layouter.layout (CompositeFigure compositeFigure, Point2D.Double anchor, Point2D.Double lead)
Method which lays out a figure. It is called by the figure if a layout task is to be performed. Implementing classes specify a certain layout algorithm in this method.
Parameters
anchor start point for the layout
lead minimum lead point for the layout
Implemented in org.jhotdraw.draw.layouter.VerticalLayouter, org.jhotdraw.draw.layouter.LocatorLayouter, and org.jhotdraw.draw.layouter.HorizontalLayouter.
Referenced by org.jhotdraw.draw.figure.AbstractCompositeFigure.layout(), org.jhotdraw.draw.figure.LabeledLineConnectionFigure.layout(), and org.jhotdraw.draw.GraphicalCompositeFigure.setBounds().
The documentation for this interface was generated from the following file:
jhotdraw-core/src/main/java/org/jhotdraw/draw/layouter/Layouter.java