jhotdraw: org.jhotdraw.draw.Drawing Interface Reference
org.jhotdraw.draw.Drawing Interface Reference
Public Member Functions
void drawCanvas (Graphics2D g)
boolean add (Figure figure)
void add (int index, Figure figure)
void addAll (Collection<? extends Figure > figures)
void addAll (int index, Collection<? extends Figure > figures)
boolean remove (Figure figure)
void removeAll (Collection<? extends Figure > figures)
int basicRemove (Figure figure)
void basicRemoveAll (Collection<? extends Figure > figures)
void basicAdd (Figure figure)
void basicAdd (int index, Figure figure)
void basicAddAll (int index, Collection<? extends Figure > figures)
List< Figure > findFigures (Rectangle2D.Double bounds)
List< Figure > findFiguresWithin (Rectangle2D.Double bounds)
Figure findFigure (Point2D.Double p)
Figure findFigureExcept (Point2D.Double p, Figure ignore)
Figure findFigureExcept (Point2D.Double p, Collection<? extends Figure > ignore)
Figure findFigureBehind (Point2D.Double p, Figure figure)
Figure findFigureBehind (Point2D.Double p, Collection<? extends Figure > figures)
List< Figure > getFiguresFrontToBack ()
Figure findFigureInside (Point2D.Double p)
void sendToBack (Figure figure)
void bringToFront (Figure figure)
List< Figure > sort (Collection<? extends Figure > figures)
void addUndoableEditListener (UndoableEditListener l)
void removeUndoableEditListener (UndoableEditListener l)
void fireUndoableEditHappened (UndoableEdit edit)
FontRenderContext getFontRenderContext ()
void setFontRenderContext (FontRenderContext frc)
Object getLock ()
void addInputFormat (InputFormat format)
void addOutputFormat (OutputFormat format)
void setInputFormats (List< InputFormat > formats)
List< InputFormat > getInputFormats ()
void setOutputFormats (List< OutputFormat > formats)
List< OutputFormat > getOutputFormats ()
Public Member Functions inherited from org.jhotdraw.draw.figure.CompositeFigure
Figure removeChild (int index)
void removeAllChildren ()
Figure basicRemoveChild (int index)
void basicRemoveAllChildren ()
java.util.List< Figure > getChildren ()
int getChildCount ()
Figure getChild (int index)
int indexOf (Figure child)
boolean contains (Figure f)
Layouter getLayouter ()
void layout ()
void setLayouter (Layouter newValue)
void addCompositeFigureListener (CompositeFigureListener listener)
void removeCompositeFigureListener (CompositeFigureListener listener)
Public Member Functions inherited from org.jhotdraw.draw.figure.Figure
void draw (Graphics2D g)
int getLayer ()
boolean isVisible ()
void setBounds (Point2D.Double start, Point2D.Double end)
Point2D.Double getStartPoint ()
Point2D.Double getEndPoint ()
Rectangle2D.Double getBounds ()
Rectangle2D.Double getDrawingArea ()
Rectangle2D.Double getDrawingArea (double factor)
Dimension2DDouble getPreferredSize ()
boolean contains (Point2D.Double p)
Object getTransformRestoreData ()
void restoreTransformTo (Object restoreData)
void transform (AffineTransform tx)
public< T > void set (AttributeKey< T > key, T value)
public< T > T get (AttributeKey< T > key)
Map< AttributeKey<?>, Object > getAttributes ()
Object getAttributesRestoreData ()
void restoreAttributesTo (Object restoreData)
boolean isSelectable ()
boolean isRemovable ()
boolean isTransformable ()
Collection< Handle > createHandles (int detailLevel)
Cursor getCursor (Point2D.Double p)
Collection< Action > getActions (Point2D.Double p)
Tool getTool (Point2D.Double p)
String getToolTipText (Point2D.Double p)
boolean isConnectable ()
Connector findConnector (Point2D.Double p, ConnectionFigure prototype)
Connector findCompatibleConnector (Connector c, boolean isStartConnector)
Collection< Connector > getConnectors (ConnectionFigure prototype)
boolean includes (Figure figure)
Collection< Figure > getDecomposition ()
Figure clone ()
void remap (Map< Figure, Figure > oldToNew, boolean disconnectIfNotInMap)
void addNotify (Drawing d)
void removeNotify (Drawing d)
void willChange ()
void changed ()
void requestRemove ()
boolean handleDrop (Point2D.Double p, Collection< Figure > droppedFigures, DrawingView view)
boolean handleMouseClick (Point2D.Double p, MouseEvent evt, DrawingView view)
void addFigureListener (FigureListener l)
void removeFigureListener (FigureListener l)
void addPropertyChangeListener (PropertyChangeListener listener)
void removePropertyChangeListener (PropertyChangeListener listener)
Additional Inherited Members
Static Public Attributes inherited from org.jhotdraw.draw.figure.CompositeFigure
static final AttributeKey< Insets2D.Double > LAYOUT_INSETS = new AttributeKey<Insets2D.Double>("layoutInsets", Insets2D.Double.class, new Insets2D.Double())
Static Public Attributes inherited from org.jhotdraw.draw.figure.Figure
static final String CONNECTABLE_PROPERTY = "connectable"
static final String REMOVABLE_PROPERTY = "removable"
static final String SELECTABLE_PROPERTY = "selectable"
static final String TRANSFORMABLE_PROPERTY = "transformable"
Detailed Description
A drawing is a container for Figures. A drawing can hold multiple figures, but a figure can only be in one drawing at a time. A drawing can be in one or multiple DrawingViews.
Drawing
is essentially a CompositeFigure with a number of additional functionality:
A drawing notifies a figure and its
CompositeFigureListener
's when the figure is added or removed from it. Like with
CompositeFigure
basic add and remove methods are supplied for use cases where this is not desired - for example when figures need to be temporarily removed in order to group or ungroup them.
A drawing can find contained figures given a point or a rectangular region. Specialized implementations of the
Drawing
interface can use optimized strategies and data structures to find figures faster.
The drawing object is used by
Figure
,
Tool
and
Handle
as a mediator for undoable edit events. This way, undoable edit listeners only need to register on the drawing object in order to receive all undoable edit events related to changes made in the drawing.
Drawing can hold a number of org.jhotdraw.draw.io.InputFormats and org.jhotdraw.draw.io.OutputFormats, allowing to read and write a drawing from/to a stream, a file or the clipboard.
Note that there are some restrictions too. Here are some things that a drawing is not allowed to do:
A drawing may not access
DrawingView
,
DrawingEditor
or
Tool
. The drawing framework is built on the assumption that a drawing can be rendered at any time without the need for the creation of views and editing tools.
Design Patterns
Framework
The following interfaces define the contracts of a framework for structured drawing editors:
Contract: Drawing, Figure, DrawingView, DrawingEditor, org.jhotdraw.draw.handle.Handle and org.jhotdraw.draw.tool.Tool.
Model-View-Controller
The following classes implement together the Model-View-Controller design pattern:
Model: Drawing; View: DrawingView; Controller: DrawingEditor.
Strategy
org.jhotdraw.draw.io.OutputFormat
encapsulates a strategy for writing drawings to output streams.
Strategy: org.jhotdraw.draw.io.OutputFormat; Context: Drawing.
Strategy
org.jhotdraw.draw.io.InputFormat
encapsulates a strategy for reading drawings from input streams.
Strategy: org.jhotdraw.draw.io.InputFormat; Context: Drawing.
Author
Werner Randelshofer
Version
$Id$
Member Function Documentation
add() [1/2]
boolean org.jhotdraw.draw.Drawing.add (Figure figure)
Adds a figure to the drawing. The drawing sends an
addNotify
message to the figure after it has been added.
See also
Figure::addNotify
Parameters
figure to be added to the drawing
Implements org.jhotdraw.draw.figure.CompositeFigure.
Referenced by org.jhotdraw.draw.action.DrawingAttributeAction.actionPerformed(), org.jhotdraw.draw.io.SerializationInputOutputFormat.createTransferable(), org.jhotdraw.draw.AbstractDrawingView.delete(), org.jhotdraw.draw.DefaultDrawingView.delete(), org.jhotdraw.draw.AbstractDrawingView.duplicate(), org.jhotdraw.draw.DefaultDrawingView.duplicate(), org.jhotdraw.draw.DefaultDrawingViewTransferHandler.exportDone(), org.jhotdraw.draw.tool.BezierTool.fireUndoEvent(), org.jhotdraw.draw.action.GroupAction.groupFigures(), org.jhotdraw.draw.tool.BezierTool.mousePressed(), org.jhotdraw.draw.tool.ConnectionTool.mousePressed(), org.jhotdraw.draw.tool.CreationTool.mousePressed(), org.jhotdraw.draw.tool.ConnectionTool.mouseReleased(), org.jhotdraw.draw.tool.CreationTool.mouseReleased(), org.jhotdraw.draw.AbstractDrawing.read(), org.jhotdraw.draw.handle.ConnectorHandle.trackEnd(), and org.jhotdraw.draw.handle.ConnectorHandle.trackStart().
add() [2/2]
void org.jhotdraw.draw.Drawing.add (int index, Figure figure)
Adds a figure to the drawing. The drawing sends an
addNotify
message to the figure after it has been added.
See also
Figure::addNotify
Parameters
index The z-index of the figure.
figure to be added to the drawing
Implements org.jhotdraw.draw.figure.CompositeFigure.
addAll() [1/2]
void org.jhotdraw.draw.Drawing.addAll (Collection<? extends Figure > figures)
Adds a collection of figures to the drawing. The drawing sends an
addNotify
message to each figure after it has been added.
See also
Figure::addNotify
Parameters
figures to be added to the drawing
Referenced by org.jhotdraw.draw.AbstractDrawingView.duplicate(), org.jhotdraw.draw.DefaultDrawingView.duplicate(), and org.jhotdraw.draw.DefaultDrawingViewTransferHandler.importData().
addAll() [2/2]
void org.jhotdraw.draw.Drawing.addAll (int index, Collection<? extends Figure > figures)
Adds a collection of figures to the drawing. The drawing sends an
addNotify
message to each figure after it has been added.
See also
Figure::addNotify
Parameters
index The z-index of the figure.
figures to be added to the drawing
addInputFormat()
void org.jhotdraw.draw.Drawing.addInputFormat (InputFormat format)
Adds an input format to the drawing.
Implemented in org.jhotdraw.draw.AbstractDrawing.
addOutputFormat()
void org.jhotdraw.draw.Drawing.addOutputFormat (OutputFormat format)
Adds an output format to the drawing.
Implemented in org.jhotdraw.draw.AbstractDrawing.
addUndoableEditListener()
void org.jhotdraw.draw.Drawing.addUndoableEditListener (UndoableEditListener l)
Adds a listener for undooable edit events.
Implemented in org.jhotdraw.draw.AbstractDrawing.
basicAdd() [1/2]
void org.jhotdraw.draw.Drawing.basicAdd (Figure figure)
Reinserts a figure which was temporarily removed using basicRemove.
This is a convenience method for calling
basicAdd(size(), figure)
.
Parameters
figure that is part of the drawing and should be removed
See also
basicRemove(Figure)
Implements org.jhotdraw.draw.figure.CompositeFigure.
basicAdd() [2/2]
void org.jhotdraw.draw.Drawing.basicAdd (int index, Figure figure)
Reinserts a figure which was temporarily removed using basicRemove.
See also
basicRemove(Figure)
Parameters
figure that is part of the drawing and should be removed
Implements org.jhotdraw.draw.figure.CompositeFigure.
Implemented in org.jhotdraw.draw.QuadTreeDrawing, and org.jhotdraw.draw.DefaultDrawing.
basicAddAll()
void org.jhotdraw.draw.Drawing.basicAddAll (int index, Collection<? extends Figure > figures)
Reinserts the specified figures which were temporarily removed from the drawing.
Parameters
index The insertion index.
figures A collection of figures which are part of the drawing and should be reinserted.
See also
#basicRemoveAll(Collection)
Referenced by org.jhotdraw.draw.action.GroupAction.ungroupFigures().
basicRemove()
int org.jhotdraw.draw.Drawing.basicRemove (Figure figure)
Removes a figure temporarily from the drawing.
See also
basicAdd(Figure)
Parameters
figure that is part of the drawing and should be removed
Implements org.jhotdraw.draw.figure.CompositeFigure.
basicRemoveAll()
void org.jhotdraw.draw.Drawing.basicRemoveAll (Collection<? extends Figure > figures)
Removes the specified figures temporarily from the drawing.
See also
#basicAddAll(int, Collection)
Parameters
figures A collection of figures which are part of the drawing and should be removed
Referenced by org.jhotdraw.draw.action.GroupAction.groupFigures().
bringToFront()
void org.jhotdraw.draw.Drawing.bringToFront (Figure figure)
Brings a figure to the front.
Parameters
figure that is part of the drawing
Implemented in org.jhotdraw.draw.QuadTreeDrawing.
Referenced by org.jhotdraw.draw.action.BringToFrontAction.bringToFront().
drawCanvas()
void org.jhotdraw.draw.Drawing.drawCanvas (Graphics2D g)
Draws on the canvas area. The canvas is the background area onto which the drawing is drawn.
By convention this method is only invoked by DrawingView.
AttributeKeys defines a number of attribute keys which can be used to determine what to draw on the canvas.
Implemented in org.jhotdraw.draw.QuadTreeDrawing, and org.jhotdraw.draw.DefaultDrawing.
Referenced by org.jhotdraw.draw.AbstractDrawingView.drawCanvas(), and org.jhotdraw.draw.DefaultDrawingView.drawCanvas().
findFigure()
Figure org.jhotdraw.draw.Drawing.findFigure (Point2D.Double p)
Finds a top level Figure. Use this call for hit detection that should not descend into children of composite figures.
Use findFigureInside If you need to descend into children of composite figures.
Implemented in org.jhotdraw.draw.QuadTreeDrawing, and org.jhotdraw.draw.DefaultDrawing.
Referenced by org.jhotdraw.draw.AbstractDrawingView.findFigure(), org.jhotdraw.draw.DefaultDrawingView.findFigure(), and org.jhotdraw.draw.tool.ConnectionTool.mousePressed().
findFigureBehind() [1/2]
Figure org.jhotdraw.draw.Drawing.findFigureBehind (Point2D.Double p, Collection<? extends Figure > figures)
Finds a top level Figure which is behind the specified Figures.
Implemented in org.jhotdraw.draw.QuadTreeDrawing, and org.jhotdraw.draw.DefaultDrawing.
findFigureBehind() [2/2]
Figure org.jhotdraw.draw.Drawing.findFigureBehind (Point2D.Double p, Figure figure)
Finds a top level Figure which is behind the specified Figure.
Implemented in org.jhotdraw.draw.QuadTreeDrawing, and org.jhotdraw.draw.DefaultDrawing.
Referenced by org.jhotdraw.draw.tool.DefaultHandleTracker.mouseMoved(), org.jhotdraw.draw.tool.DefaultSelectAreaTracker.mouseMoved(), org.jhotdraw.draw.tool.SelectionTool.mousePressed(), and org.jhotdraw.draw.tool.AbstractTool.updateCursor().
findFigureExcept() [1/2]
Figure org.jhotdraw.draw.Drawing.findFigureExcept (Point2D.Double p, Collection<? extends Figure > ignore)
Finds a top level Figure. Use this call for hit detection that should not descend into the figure's children.
Implemented in org.jhotdraw.draw.QuadTreeDrawing, and org.jhotdraw.draw.DefaultDrawing.
findFigureExcept() [2/2]
Figure org.jhotdraw.draw.Drawing.findFigureExcept (Point2D.Double p, Figure ignore)
Finds a top level Figure. Use this call for hit detection that should not descend into the figure's children.
Implemented in org.jhotdraw.draw.QuadTreeDrawing, and org.jhotdraw.draw.DefaultDrawing.
Referenced by org.jhotdraw.draw.tool.ConnectionTool.mouseDragged(), org.jhotdraw.draw.tool.DefaultDragTracker.mouseReleased(), and org.jhotdraw.draw.tool.ConnectionTool.repaintConnectors().
findFigureInside()
Figure org.jhotdraw.draw.Drawing.findFigureInside (Point2D.Double p)
Finds the innermost figure at the specified location.
In case a
CompositeFigure
is at the specified location, this method descends into its children and into its children's children until the innermost figure is found.
This functionality is implemented using the Chain of Responsibility design pattern in the
Figure
interface. Since it is often used from a drawing object as the starting point, and since
Drawing
defines other find methods as well, it is defined here again for clarity.
Parameters
p A location on the drawing.
Returns
Returns the innermost figure at the location, or null if the location is not contained in a figure.
Implements org.jhotdraw.draw.figure.Figure.
Implemented in org.jhotdraw.draw.QuadTreeDrawing, and org.jhotdraw.draw.DefaultDrawing.
Referenced by org.jhotdraw.draw.tool.DelegationSelectionTool.handleDoubleClick().
findFigures()
List<Figure> org.jhotdraw.draw.Drawing.findFigures (Rectangle2D.Double bounds)
Returns all figures that lie within or intersect the specified bounds. The figures are returned in Z-order from back to front.
Implemented in org.jhotdraw.draw.QuadTreeDrawing, and org.jhotdraw.draw.DefaultDrawing.
Referenced by org.jhotdraw.draw.AbstractDrawingView.findFigures(), and org.jhotdraw.draw.DefaultDrawingView.findFigures().
findFiguresWithin()
List<Figure> org.jhotdraw.draw.Drawing.findFiguresWithin (Rectangle2D.Double bounds)
Returns all figures that lie within the specified bounds. The figures are returned in Z-order from back to front.
Implemented in org.jhotdraw.draw.QuadTreeDrawing, and org.jhotdraw.draw.DefaultDrawing.
Referenced by org.jhotdraw.draw.AbstractDrawingView.findFiguresWithin(), and org.jhotdraw.draw.DefaultDrawingView.findFiguresWithin().
fireUndoableEditHappened()
void org.jhotdraw.draw.Drawing.fireUndoableEditHappened (UndoableEdit edit)
Notify all listenerList that have registered interest for notification on this event type.
Implemented in org.jhotdraw.draw.AbstractDrawing.
Referenced by org.jhotdraw.draw.action.AttributeToggler< T >.actionPerformed(), org.jhotdraw.draw.action.ApplyAttributesAction.applyAttributes(), org.jhotdraw.draw.action.AttributeAction.applyAttributesTo(), org.jhotdraw.draw.AbstractDrawingView.delete(), org.jhotdraw.draw.DefaultDrawingView.delete(), org.jhotdraw.draw.AbstractDrawingView.duplicate(), org.jhotdraw.draw.DefaultDrawingView.duplicate(), org.jhotdraw.draw.tool.TextAreaCreationTool.endEdit(), org.jhotdraw.draw.tool.TextAreaEditingTool.endEdit(), org.jhotdraw.draw.tool.TextCreationTool.endEdit(), org.jhotdraw.draw.tool.TextEditingTool.endEdit(), org.jhotdraw.draw.DefaultDrawingViewTransferHandler.exportDone(), org.jhotdraw.draw.action.AbstractDrawingEditorAction.fireUndoableEditHappened(), org.jhotdraw.draw.action.AbstractDrawingViewAction.fireUndoableEditHappened(), org.jhotdraw.draw.action.AbstractSelectedAction.fireUndoableEditHappened(), org.jhotdraw.draw.figure.AbstractFigure.fireUndoableEditHappened(), org.jhotdraw.draw.handle.AbstractHandle.fireUndoableEditHappened(), org.jhotdraw.draw.tool.BezierTool.fireUndoEvent(), org.jhotdraw.draw.DefaultDrawingViewTransferHandler.importData(), org.jhotdraw.draw.handle.BezierControlPointHandle.keyPressed(), org.jhotdraw.draw.handle.BezierNodeHandle.keyPressed(), org.jhotdraw.draw.tool.ConnectionTool.mouseReleased(), org.jhotdraw.draw.tool.CreationTool.mouseReleased(), org.jhotdraw.draw.tool.DefaultDragTracker.mouseReleased(), org.jhotdraw.draw.handle.AbstractRotateHandle.trackEnd(), org.jhotdraw.draw.handle.BezierControlPointHandle.trackEnd(), org.jhotdraw.draw.handle.BezierNodeHandle.trackEnd(), org.jhotdraw.draw.handle.BezierScaleHandle.trackEnd(), org.jhotdraw.draw.handle.ConnectorHandle.trackEnd(), org.jhotdraw.draw.handle.BezierControlPointHandle.trackStart(), org.jhotdraw.draw.handle.BezierNodeHandle.trackStart(), and org.jhotdraw.draw.event.AbstractAttributeEditorHandler< T >.updateFigures().
getFiguresFrontToBack()
List<Figure> org.jhotdraw.draw.Drawing.getFiguresFrontToBack ()
Returns a list of the figures in Z-Order from front to back.
Implemented in org.jhotdraw.draw.QuadTreeDrawing, and org.jhotdraw.draw.DefaultDrawing.
getFontRenderContext()
FontRenderContext org.jhotdraw.draw.Drawing.getFontRenderContext ()
Returns the font render context used to do text leyout and text drawing.
Implemented in org.jhotdraw.draw.AbstractDrawing.
getInputFormats()
List<InputFormat> org.jhotdraw.draw.Drawing.getInputFormats ()
Gets input formats for the Drawing in order of preferred formats.
Implemented in org.jhotdraw.draw.AbstractDrawing.
Referenced by org.jhotdraw.draw.DefaultDrawingViewTransferHandler.canImport(), and org.jhotdraw.draw.DefaultDrawingViewTransferHandler.importData().
getLock()
Object org.jhotdraw.draw.Drawing.getLock ()
Returns the lock object on which all threads acting on Figures in this drawing synchronize to prevent race conditions.
Implemented in org.jhotdraw.draw.AbstractDrawing.
Referenced by org.jhotdraw.draw.figure.AbstractFigure.getLock().
getOutputFormats()
List<OutputFormat> org.jhotdraw.draw.Drawing.getOutputFormats ()
Gets output formats for the Drawing in order of preferred formats.
Implemented in org.jhotdraw.draw.AbstractDrawing.
Referenced by org.jhotdraw.draw.DefaultDrawingViewTransferHandler.createTransferable(), and org.jhotdraw.draw.DefaultDrawingViewTransferHandler.getSourceActions().
remove()
boolean org.jhotdraw.draw.Drawing.remove (Figure figure)
Removes a figure from the drawing. The drawing sends a
removeNotify
message to the figure before it is removed.
See also
Figure::removeNotify
Parameters
figure that is part of the drawing and should be removed
Implements org.jhotdraw.draw.figure.CompositeFigure.
Referenced by org.jhotdraw.draw.tool.ImageTool.activate(), org.jhotdraw.draw.tool.ConnectionTool.deactivate(), org.jhotdraw.draw.AbstractDrawingView.delete(), org.jhotdraw.draw.DefaultDrawingView.delete(), org.jhotdraw.draw.tool.TextAreaCreationTool.endEdit(), org.jhotdraw.draw.tool.TextCreationTool.endEdit(), org.jhotdraw.draw.DefaultDrawingViewTransferHandler.exportDone(), org.jhotdraw.draw.tool.BezierTool.fireUndoEvent(), org.jhotdraw.draw.tool.ConnectionTool.mouseReleased(), org.jhotdraw.draw.tool.CreationTool.mouseReleased(), org.jhotdraw.draw.handle.ConnectorHandle.trackEnd(), and org.jhotdraw.draw.action.GroupAction.ungroupFigures().
removeAll()
void org.jhotdraw.draw.Drawing.removeAll (Collection<? extends Figure > figures)
Removes the specified figures from the drawing. The drawing sends a
removeNotify
message to each figure before it is removed.
See also
Figure::removeNotify
Parameters
figures A collection of figures which are part of the drawing and should be removed
Referenced by org.jhotdraw.draw.AbstractDrawingView.delete(), org.jhotdraw.draw.DefaultDrawingView.delete(), org.jhotdraw.draw.AbstractDrawingView.duplicate(), org.jhotdraw.draw.DefaultDrawingView.duplicate(), org.jhotdraw.draw.tool.AbstractTool.editDelete(), org.jhotdraw.draw.DefaultDrawingViewTransferHandler.exportDone(), and org.jhotdraw.draw.DefaultDrawingViewTransferHandler.importData().
removeUndoableEditListener()
void org.jhotdraw.draw.Drawing.removeUndoableEditListener (UndoableEditListener l)
Removes a listener for undoable edit events.
Implemented in org.jhotdraw.draw.AbstractDrawing.
sendToBack()
void org.jhotdraw.draw.Drawing.sendToBack (Figure figure)
Sends a figure to the back of the drawing.
Parameters
figure that is part of the drawing
Implemented in org.jhotdraw.draw.QuadTreeDrawing.
Referenced by org.jhotdraw.draw.action.SendToBackAction.sendToBack().
setFontRenderContext()
void org.jhotdraw.draw.Drawing.setFontRenderContext (FontRenderContext frc)
Sets the font render context used to do text leyout and text drawing.
Implemented in org.jhotdraw.draw.AbstractDrawing.
Referenced by org.jhotdraw.draw.AbstractDrawingView.drawCanvas(), org.jhotdraw.draw.DefaultDrawingView.drawCanvas(), org.jhotdraw.draw.AbstractDrawingView.drawDrawing(), and org.jhotdraw.draw.DefaultDrawingView.drawDrawing().
setInputFormats()
void org.jhotdraw.draw.Drawing.setInputFormats (List< InputFormat > formats)
Sets input formats for the Drawing in order of preferred formats.
The input formats are used for loading the Drawing from a file and for pasting Figures from the clipboard into the Drawing.
setOutputFormats()
void org.jhotdraw.draw.Drawing.setOutputFormats (List< OutputFormat > formats)
Sets output formats for the Drawing in order of preferred formats.
The output formats are used for saving the Drawing into a file and for cutting and copying Figures from the Drawing into the clipboard.
sort()
List<Figure> org.jhotdraw.draw.Drawing.sort (Collection<? extends Figure > figures)
Returns a copy of the provided collection which is sorted in z order from back to front.
Implemented in org.jhotdraw.draw.QuadTreeDrawing, and org.jhotdraw.draw.DefaultDrawing.
Referenced by org.jhotdraw.draw.action.BringToFrontAction.bringToFront(), org.jhotdraw.draw.DefaultDrawingViewTransferHandler.createTransferable(), org.jhotdraw.draw.AbstractDrawingView.delete(), org.jhotdraw.draw.DefaultDrawingView.delete(), org.jhotdraw.draw.AbstractDrawingView.duplicate(), org.jhotdraw.draw.DefaultDrawingView.duplicate(), and org.jhotdraw.draw.action.GroupAction.groupFigures().
The documentation for this interface was generated from the following file:
jhotdraw-core/src/main/java/org/jhotdraw/draw/Drawing.java