jhotdraw: org.jhotdraw.draw.DrawingEditor Interface Reference
org.jhotdraw.draw.DrawingEditor Interface Reference
Public Member Functions
void add (DrawingView view)
void remove (DrawingView view)
Collection< DrawingView > getDrawingViews ()
DrawingView getActiveView ()
void setActiveView (DrawingView newValue)
void setTool (Tool t)
Tool getTool ()
void setCursor (Cursor c)
DrawingView findView (Container c)
public< T > void setDefaultAttribute (AttributeKey< T > key, T value)
public< T > T getDefaultAttribute (AttributeKey< T > key)
void applyDefaultAttributesTo (Figure f)
Map< AttributeKey<?>, Object > getDefaultAttributes ()
public< T > void setHandleAttribute (AttributeKey< T > key, T value)
public< T > T getHandleAttribute (AttributeKey< T > key)
void setInputMap (InputMap newValue)
InputMap getInputMap ()
void setActionMap (ActionMap newValue)
ActionMap getActionMap ()
void setEnabled (boolean newValue)
boolean isEnabled ()
void addPropertyChangeListener (PropertyChangeListener listener)
void removePropertyChangeListener (PropertyChangeListener listener)
Static Public Attributes
static final String ACTIVE_VIEW_PROPERTY = "activeView"
static final String TOOL_PROPERTY = "tool"
static final String INPUT_MAP_PROPERTY = "inputMap"
static final String ACTION_MAP_PROPERTY = "actionMap"
static final String DEFAULT_ATTRIBUTE_PROPERTY_PREFIX = "defaultAttribute."
Detailed Description
A drawing editor coordinates drawing tools and drawing views.
Usage of drawing editor in conjunction with the JHotDraw application framework:
For org.jhotdraw.app.Applications which provide a single document interface (SDI) there is typically one drawing editor instance per org.jhotdraw.app.View. So that each view can have its own toolbars and drawing palettes.
For applications with a Windows-style multiple document interface (MDI) there is typically one drawing editor instance per parent window. All views within a parent window share the toolbars and drawing palettes provided be the parent window.
For applications with a Mac OS X-style application document interface (OSX) there is typically a single drawing editor instance for the application. All views within the application share a single set of toolbars and drawing palettes.
Design Patterns
Framework
The following interfaces define the contracts of a framework for structured drawing editors:
Contract: Drawing, Figure, DrawingView, DrawingEditor, org.jhotdraw.draw.handle.Handle and org.jhotdraw.draw.tool.Tool.
Mediator
DrawingEditor
acts as a mediator for coordinating drawing tools and drawing views:
Mediator: DrawingEditor; Colleagues: DrawingView, org.jhotdraw.draw.tool.Tool.
Mediator
DrawingEditor
acts as a mediator for coordinating keyboard input from
Tool
s and Swing action objects:
Mediator: DrawingEditor; Colleagues: org.jhotdraw.draw.tool.Tool, javax.swing.Action.
Model-View-Controller
The following classes implement together the Model-View-Controller design pattern:
Model: Drawing; View: DrawingView; Controller: DrawingEditor.
Observer
State changes of tools can be observed by other objects. Specifically
DrawingEditor
observes area invalidations of tools and repaints its active drawing view accordingly.
Subject: Tool; Observer: org.jhotdraw.draw.event.ToolListener; Event: org.jhotdraw.draw.event.ToolEvent; Concrete Observer: DrawingEditor.
Proxy
To remove the need for null-handling,
AbstractTool
makes use of a proxy for
DrawingEditor
.
Subject: DrawingEditor; Proxy: DrawingEditorProxy; Client: org.jhotdraw.draw.tool.AbstractTool.
Author
Werner Randelshofer
Version
$Id$
Member Function Documentation
add()
void org.jhotdraw.draw.DrawingEditor.add (DrawingView view)
Gets the editor's current drawing. / Drawing getDrawing(); /** Sets the editor's current drawing. / void setDrawing(Drawing drawing); Adds a drawing view to the editor. The editor invokes addNotify on the view, and it registers its tool as an event listener on the view.
Implemented in org.jhotdraw.draw.DrawingEditorProxy, and org.jhotdraw.draw.DefaultDrawingEditor.
Referenced by org.jhotdraw.draw.DrawingEditorProxy.add().
addPropertyChangeListener()
void org.jhotdraw.draw.DrawingEditor.addPropertyChangeListener (PropertyChangeListener listener)
Adds a
PropertyChangeListener
.
Parameters
listener
Referenced by org.jhotdraw.draw.action.DefaultAttributeAction.DefaultAttributeAction(), org.jhotdraw.draw.event.DrawingComponentRepainter.DrawingComponentRepainter(), org.jhotdraw.draw.event.SelectionComponentDisplayer.SelectionComponentDisplayer(), org.jhotdraw.draw.event.SelectionComponentRepainter.SelectionComponentRepainter(), org.jhotdraw.draw.event.AbstractAttributeEditorHandler< T >.setEditor(), and org.jhotdraw.draw.DrawingEditorProxy.setTarget().
applyDefaultAttributesTo()
void org.jhotdraw.draw.DrawingEditor.applyDefaultAttributesTo (Figure f)
Applies the default attributes to the specified figure.
Implemented in org.jhotdraw.draw.DrawingEditorProxy, and org.jhotdraw.draw.DefaultDrawingEditor.
Referenced by org.jhotdraw.draw.DrawingEditorProxy.applyDefaultAttributesTo(), org.jhotdraw.draw.tool.BezierTool.createFigure(), org.jhotdraw.draw.tool.ConnectionTool.createFigure(), and org.jhotdraw.draw.tool.CreationTool.createFigure().
findView()
DrawingView org.jhotdraw.draw.DrawingEditor.findView (Container c)
Finds a drawing view. This is used by Tool to identify the view of which it has received an event.
Implemented in org.jhotdraw.draw.DrawingEditorProxy, and org.jhotdraw.draw.DefaultDrawingEditor.
Referenced by org.jhotdraw.draw.DrawingEditorProxy.findView(), org.jhotdraw.draw.tool.AbstractTool.keyPressed(), org.jhotdraw.draw.tool.DefaultDragTracker.mouseDragged(), org.jhotdraw.draw.tool.DefaultHandleTracker.mouseExited(), org.jhotdraw.draw.tool.DefaultSelectAreaTracker.mouseExited(), org.jhotdraw.draw.tool.DefaultDragTracker.mouseMoved(), org.jhotdraw.draw.tool.DefaultHandleTracker.mouseMoved(), org.jhotdraw.draw.tool.DefaultSelectAreaTracker.mouseMoved(), org.jhotdraw.draw.tool.DnDTracker.mouseMoved(), org.jhotdraw.draw.tool.AbstractTool.mousePressed(), org.jhotdraw.draw.tool.DefaultDragTracker.mouseReleased(), and org.jhotdraw.draw.tool.DnDTracker.mouseReleased().
getActionMap()
ActionMap org.jhotdraw.draw.DrawingEditor.getActionMap ()
Gets the action map used by the tool of this drawing editor as a fall back for performing actions.
Tool
s use the action map of the drawing editor to determine what to do when an action needs to be invoked from the InputMap of the drawing editor.
This is a bound property.
Implemented in org.jhotdraw.draw.DrawingEditorProxy, and org.jhotdraw.draw.DefaultDrawingEditor.
Referenced by org.jhotdraw.draw.DrawingEditorProxy.getActionMap(), and org.jhotdraw.draw.tool.AbstractTool.keyPressed().
getActiveView()
DrawingView org.jhotdraw.draw.DrawingEditor.getActiveView ()
Gets the editor's active drawing view. This can be null, if the editor has no views.
Implemented in org.jhotdraw.draw.DrawingEditorProxy, and org.jhotdraw.draw.DefaultDrawingEditor.
Referenced by org.jhotdraw.draw.event.DrawingComponentRepainter.dispose(), org.jhotdraw.draw.event.SelectionComponentRepainter.dispose(), org.jhotdraw.draw.AbstractDrawingView.drawHandles(), org.jhotdraw.draw.DefaultDrawingView.drawHandles(), org.jhotdraw.draw.event.DrawingComponentRepainter.DrawingComponentRepainter(), org.jhotdraw.draw.AbstractDrawingView.drawTool(), org.jhotdraw.draw.DefaultDrawingView.drawTool(), org.jhotdraw.draw.DrawingEditorProxy.getActiveView(), org.jhotdraw.draw.event.AbstractAttributeEditorHandler< T >.getActiveView(), org.jhotdraw.draw.DrawingEditorProxy.getFocusedView(), org.jhotdraw.draw.action.DrawingColorChooserAction.getInitialColor(), org.jhotdraw.draw.action.SelectionColorChooserAction.getInitialColor(), org.jhotdraw.draw.action.AbstractDrawingEditorAction.getView(), org.jhotdraw.draw.action.AbstractDrawingViewAction.getView(), org.jhotdraw.draw.action.AbstractSelectedAction.getView(), org.jhotdraw.draw.action.AttributeToggler< T >.getView(), org.jhotdraw.draw.tool.AbstractTool.getView(), org.jhotdraw.draw.tool.DefaultHandleTracker.mouseMoved(), org.jhotdraw.draw.tool.DefaultSelectAreaTracker.mouseMoved(), org.jhotdraw.draw.action.DrawingColorIcon.paintIcon(), org.jhotdraw.draw.action.SelectionColorIcon.paintIcon(), org.jhotdraw.draw.event.SelectionComponentDisplayer.SelectionComponentDisplayer(), org.jhotdraw.draw.event.SelectionComponentRepainter.SelectionComponentRepainter(), org.jhotdraw.draw.event.AbstractAttributeEditorHandler< T >.updateActiveView(), and org.jhotdraw.draw.event.SelectionComponentDisplayer.updateVisibility().
getDefaultAttribute()
public<T> T org.jhotdraw.draw.DrawingEditor.getDefaultAttribute (AttributeKey< T > key)
Gets a default attribute from the editor. The default attribute will be used by creation tools, to create a new figure.
Referenced by org.jhotdraw.draw.action.DefaultAttributeAction.changeAttribute(), org.jhotdraw.draw.action.EditorColorChooserAction.getInitialColor(), org.jhotdraw.draw.action.EditorColorIcon.paintIcon(), and org.jhotdraw.draw.event.AbstractAttributeEditorHandler< T >.updateAttributeEditor().
getDefaultAttributes()
Map<AttributeKey<?>, Object> org.jhotdraw.draw.DrawingEditor.getDefaultAttributes ()
Returns an immutable Map with the default attributes of this editor.
Implemented in org.jhotdraw.draw.DrawingEditorProxy, and org.jhotdraw.draw.DefaultDrawingEditor.
Referenced by org.jhotdraw.draw.action.ApplyAttributesAction.applyAttributes(), org.jhotdraw.draw.DrawingEditorProxy.getDefaultAttributes(), and org.jhotdraw.draw.action.SelectionColorIcon.paintIcon().
getDrawingViews()
Collection<DrawingView> org.jhotdraw.draw.DrawingEditor.getDrawingViews ()
Gets all drawing views associated with this editor.
Implemented in org.jhotdraw.draw.DrawingEditorProxy, and org.jhotdraw.draw.DefaultDrawingEditor.
Referenced by org.jhotdraw.draw.tool.AbstractTool.activate(), and org.jhotdraw.draw.DrawingEditorProxy.getDrawingViews().
getHandleAttribute()
public<T> T org.jhotdraw.draw.DrawingEditor.getHandleAttribute (AttributeKey< T > key)
Gets a handle attribute from the editor. The default attribute will be used by creation tools, to create a new figure.
Parameters
key AttributeKey.
Returns
If the handle attribute has been set, returns the previously set value. If the handle attribute has not been set, returns key.getDefaultValue().
Referenced by org.jhotdraw.draw.handle.BezierControlPointHandle.draw(), org.jhotdraw.draw.handle.BezierNodeHandle.draw(), org.jhotdraw.draw.handle.BezierOutlineHandle.draw(), org.jhotdraw.draw.handle.BoundsOutlineHandle.draw(), and org.jhotdraw.draw.handle.AbstractHandle.getHandlesize().
getInputMap()
InputMap org.jhotdraw.draw.DrawingEditor.getInputMap ()
Sets the input map used by the tool of this drawing editor as a fall back for handling keyboard events.
Tool
s use the input map of the drawing editor to determine what to do when a key was pressed that the tool can not handle.
This is a bound property.
Implemented in org.jhotdraw.draw.DrawingEditorProxy, and org.jhotdraw.draw.DefaultDrawingEditor.
Referenced by org.jhotdraw.draw.DrawingEditorProxy.getInputMap(), and org.jhotdraw.draw.tool.AbstractTool.keyPressed().
getTool()
Tool org.jhotdraw.draw.DrawingEditor.getTool ()
Gets the current tool.
This is a bound property.
Implemented in org.jhotdraw.draw.DrawingEditorProxy, and org.jhotdraw.draw.DefaultDrawingEditor.
Referenced by org.jhotdraw.draw.AbstractDrawingView.drawTool(), org.jhotdraw.draw.DefaultDrawingView.drawTool(), org.jhotdraw.draw.DrawingEditorProxy.getTool(), org.jhotdraw.draw.AbstractDrawingView.getToolTipText(), org.jhotdraw.draw.DefaultDrawingView.getToolTipText(), and org.jhotdraw.draw.event.SelectionComponentDisplayer.updateVisibility().
isEnabled()
boolean org.jhotdraw.draw.DrawingEditor.isEnabled ()
Gets the enabled state of the drawing editor.
Implemented in org.jhotdraw.draw.DrawingEditorProxy, and org.jhotdraw.draw.DefaultDrawingEditor.
Referenced by org.jhotdraw.draw.DrawingEditorProxy.isEnabled(), and org.jhotdraw.draw.action.AbstractDrawingEditorAction.updateEnabledState().
remove()
void org.jhotdraw.draw.DrawingEditor.remove (DrawingView view)
Removes a drawing view from the editor. The editor invokes removeNotify on the view, and it unregisters its tool on the view.
Implemented in org.jhotdraw.draw.DrawingEditorProxy, and org.jhotdraw.draw.DefaultDrawingEditor.
Referenced by org.jhotdraw.draw.DrawingEditorProxy.remove().
removePropertyChangeListener()
void org.jhotdraw.draw.DrawingEditor.removePropertyChangeListener (PropertyChangeListener listener)
Removes a
PropertyChangeListener
.
Parameters
listener
Referenced by org.jhotdraw.draw.event.DrawingComponentRepainter.dispose(), org.jhotdraw.draw.event.SelectionComponentDisplayer.dispose(), org.jhotdraw.draw.event.SelectionComponentRepainter.dispose(), org.jhotdraw.draw.event.AbstractAttributeEditorHandler< T >.setEditor(), and org.jhotdraw.draw.DrawingEditorProxy.setTarget().
setActionMap()
void org.jhotdraw.draw.DrawingEditor.setActionMap (ActionMap newValue)
Sets the action map used by the tool of this drawing editor as a fall back for performing actions.
This is a bound property.
Implemented in org.jhotdraw.draw.DrawingEditorProxy, and org.jhotdraw.draw.DefaultDrawingEditor.
Referenced by org.jhotdraw.draw.DrawingEditorProxy.setActionMap().
setActiveView()
void org.jhotdraw.draw.DrawingEditor.setActiveView (DrawingView newValue)
Sets the editor's active drawing view. This can be set to null, if the editor has no views.
Implemented in org.jhotdraw.draw.DrawingEditorProxy, and org.jhotdraw.draw.DefaultDrawingEditor.
Referenced by org.jhotdraw.draw.tool.AbstractTool.keyPressed(), and org.jhotdraw.draw.DrawingEditorProxy.setActiveView().
setCursor()
void org.jhotdraw.draw.DrawingEditor.setCursor (Cursor c)
Sets the cursor on the view(s) of the drawing editor.
Implemented in org.jhotdraw.draw.DrawingEditorProxy, and org.jhotdraw.draw.DefaultDrawingEditor.
Referenced by org.jhotdraw.draw.DrawingEditorProxy.setCursor().
setDefaultAttribute()
public<T> void org.jhotdraw.draw.DrawingEditor.setDefaultAttribute (AttributeKey< T > key, T value)
Sets a default attribute of the editor. The default attribute will be used by creation tools, to create a new figure.
Fires a property change event with the name of the attribute key, and the prefix
"defaultAttribute."
.
Referenced by org.jhotdraw.draw.action.AttributeAction.applyAttributesTo(), org.jhotdraw.draw.action.DrawingColorChooserHandler.applySelectedColorToFigures(), org.jhotdraw.draw.action.SelectionColorChooserHandler.applySelectedColorToFigures(), org.jhotdraw.draw.action.PickAttributesAction.pickAttributes(), and org.jhotdraw.draw.event.AbstractAttributeEditorHandler< T >.updateFigures().
setEnabled()
void org.jhotdraw.draw.DrawingEditor.setEnabled (boolean newValue)
Sets the enabled state of the drawing editor. This is a bound property.
Implemented in org.jhotdraw.draw.DrawingEditorProxy, and org.jhotdraw.draw.DefaultDrawingEditor.
Referenced by org.jhotdraw.draw.DefaultDrawingViewTransferHandler.importData(), and org.jhotdraw.draw.DrawingEditorProxy.setEnabled().
setHandleAttribute()
public<T> void org.jhotdraw.draw.DrawingEditor.setHandleAttribute (AttributeKey< T > key, T value)
Sets a handle attribute of the editor. The default attribute will be used by creation tools, to create a new figure.
Parameters
key AttributeKey.
value Attribute value.
setInputMap()
void org.jhotdraw.draw.DrawingEditor.setInputMap (InputMap newValue)
Sets the input map used by the tool of this drawing editor as a fall back for handling keyboard events.
This is a bound property.
Implemented in org.jhotdraw.draw.DrawingEditorProxy, and org.jhotdraw.draw.DefaultDrawingEditor.
Referenced by org.jhotdraw.draw.DrawingEditorProxy.setInputMap().
setTool()
void org.jhotdraw.draw.DrawingEditor.setTool (Tool t)
Calls deactivate on the previously active tool of this drawing editor. Calls activate on the provided tool. Forwards all mouse, mouse moation and keyboard events that occur on the DrawingView to the provided tool.
This is a bound property.
Implemented in org.jhotdraw.draw.DrawingEditorProxy, and org.jhotdraw.draw.DefaultDrawingEditor.
Referenced by org.jhotdraw.draw.DrawingEditorProxy.setTool().
Member Data Documentation
ACTION_MAP_PROPERTY
final String org.jhotdraw.draw.DrawingEditor.ACTION_MAP_PROPERTY = "actionMap" static
The property name for the action map property.
Referenced by org.jhotdraw.draw.DefaultDrawingEditor.setActionMap().
ACTIVE_VIEW_PROPERTY
final String org.jhotdraw.draw.DrawingEditor.ACTIVE_VIEW_PROPERTY = "activeView" static
The property name for the active view property.
Referenced by org.jhotdraw.draw.event.AbstractAttributeEditorHandler< T >.EventHandler.propertyChange(), org.jhotdraw.draw.event.DrawingComponentRepainter.propertyChange(), org.jhotdraw.draw.event.SelectionComponentDisplayer.propertyChange(), org.jhotdraw.draw.event.SelectionComponentRepainter.propertyChange(), and org.jhotdraw.draw.DefaultDrawingEditor.setActiveView().
DEFAULT_ATTRIBUTE_PROPERTY_PREFIX
final String org.jhotdraw.draw.DrawingEditor.DEFAULT_ATTRIBUTE_PROPERTY_PREFIX = "defaultAttribute." static
The prefix for default attribute property changes.
Referenced by org.jhotdraw.draw.event.AbstractAttributeEditorHandler< T >.EventHandler.propertyChange().
INPUT_MAP_PROPERTY
final String org.jhotdraw.draw.DrawingEditor.INPUT_MAP_PROPERTY = "inputMap" static
The property name for the input map property.
Referenced by org.jhotdraw.draw.DefaultDrawingEditor.setInputMap().
TOOL_PROPERTY
final String org.jhotdraw.draw.DrawingEditor.TOOL_PROPERTY = "tool" static
The property name for the active tool property.
Referenced by org.jhotdraw.draw.event.SelectionComponentDisplayer.propertyChange(), and org.jhotdraw.draw.DefaultDrawingEditor.setTool().
The documentation for this interface was generated from the following file:
jhotdraw-core/src/main/java/org/jhotdraw/draw/DrawingEditor.java