jhotdraw: org.jhotdraw.draw.figure.Figure Interface Reference
org.jhotdraw.draw.figure.Figure Interface Reference
Public Member Functions
void draw (Graphics2D g)
int getLayer ()
boolean isVisible ()
void setBounds (Point2D.Double start, Point2D.Double end)
Point2D.Double getStartPoint ()
Point2D.Double getEndPoint ()
Rectangle2D.Double getBounds ()
Rectangle2D.Double getDrawingArea ()
Rectangle2D.Double getDrawingArea (double factor)
Dimension2DDouble getPreferredSize ()
boolean contains (Point2D.Double p)
Object getTransformRestoreData ()
void restoreTransformTo (Object restoreData)
void transform (AffineTransform tx)
public< T > void set (AttributeKey< T > key, T value)
public< T > T get (AttributeKey< T > key)
Map< AttributeKey<?>, Object > getAttributes ()
Object getAttributesRestoreData ()
void restoreAttributesTo (Object restoreData)
boolean isSelectable ()
boolean isRemovable ()
boolean isTransformable ()
Collection< Handle > createHandles (int detailLevel)
Cursor getCursor (Point2D.Double p)
Collection< Action > getActions (Point2D.Double p)
Tool getTool (Point2D.Double p)
String getToolTipText (Point2D.Double p)
boolean isConnectable ()
Connector findConnector (Point2D.Double p, ConnectionFigure prototype)
Connector findCompatibleConnector (Connector c, boolean isStartConnector)
Collection< Connector > getConnectors (ConnectionFigure prototype)
boolean includes (Figure figure)
Figure findFigureInside (Point2D.Double p)
Collection< Figure > getDecomposition ()
Figure clone ()
void remap (Map< Figure, Figure > oldToNew, boolean disconnectIfNotInMap)
void addNotify (Drawing d)
void removeNotify (Drawing d)
void willChange ()
void changed ()
void requestRemove ()
boolean handleDrop (Point2D.Double p, Collection< Figure > droppedFigures, DrawingView view)
boolean handleMouseClick (Point2D.Double p, MouseEvent evt, DrawingView view)
void addFigureListener (FigureListener l)
void removeFigureListener (FigureListener l)
void addPropertyChangeListener (PropertyChangeListener listener)
void removePropertyChangeListener (PropertyChangeListener listener)
Static Public Attributes
static final String CONNECTABLE_PROPERTY = "connectable"
static final String REMOVABLE_PROPERTY = "removable"
static final String SELECTABLE_PROPERTY = "selectable"
static final String TRANSFORMABLE_PROPERTY = "transformable"
Detailed Description
A figure is a graphical element of a Drawing. A figure can be only in one drawing at a time.
Figure
provides the following functionality:
Figure
knows its bounds and it can draw itself.
Figures can have an open ended set of attributes. An attribute is identified by an AttributeKey.
A figure can have org.jhotdraw.draw.connector.Connectors that define how to locate a connection point on the figure.
A figure can create a set of Handles which can interactively manipulate aspects of the figure.
A figure can return a set of actions associated with a specific point on the figure.
A figure can be composed of other figures. If this is the case, the object implementing the
Figure
interface usually also implements the CompositeFigure interface.
A figure can create a clone of itself.
Note that there are some restrictions too. Here are some things that a figure is not allowed to do:
A figure may not access
DrawingView
,
DrawingEditor
or
Tool
. The drawing framework is built on the assumption that a drawing can be rendered at any time without the need for the creation of views and editing tools.
Design Patterns
Framework
The following interfaces define the contracts of a framework for structured drawing editors:
Contract: Drawing, Figure, DrawingView, DrawingEditor, org.jhotdraw.draw.handle.Handle and org.jhotdraw.draw.tool.Tool.
Composite
Composite figures can be composed of other figures.
Component: Figure; Composite: CompositeFigure.
Framework
Two figures can be connected using a connection figure. The location of the start or end point of the connection is handled by a connector object at each connected figure.
Contract: org.jhotdraw.draw.figure.Figure, ConnectionFigure, org.jhotdraw.draw.connector.Connector, org.jhotdraw.draw.tool.ConnectionTool.
Decorator
Decorated figures can be adorned with another figure.
Component: DecoratedFigure; Decorator: Figure.
Observer
State changes of figures can be observed by other objects. Specifically
CompositeFigure
observes area invalidations of its child figures. And
DrawingView
observers area invalidations of its drawing object.
Subject: Figure; Observer: org.jhotdraw.draw.event.FigureListener; Event: org.jhotdraw.draw.event.FigureEvent; Concrete Observer: CompositeFigure, DrawingView.
Prototype
The creation tool creates new figures by cloning a prototype figure object. That's the reason why
Figure
extends the
Cloneable
interface.
Prototype: Figure; Client: org.jhotdraw.draw.tool.CreationTool.
Strategy
The location of the start and end points of a connection figure are determined by
Connector
s which are owned by the connected figures.
Context: Figure, ConnectionFigure; Strategy: org.jhotdraw.draw.connector.Connector.
Strategy
Locator
encapsulates a strategy for locating a point on a
Figure
.
Strategy: org.jhotdraw.draw.locator.Locator; Context: Figure.
Author
Werner Randelshofer
Version
$Id$
Member Function Documentation
addFigureListener()
void org.jhotdraw.draw.figure.Figure.addFigureListener (FigureListener l)
Adds a listener for FigureEvent's.
Implemented in org.jhotdraw.draw.figure.AbstractFigure.
Referenced by org.jhotdraw.draw.handle.AbstractHandle.AbstractHandle(), org.jhotdraw.draw.AbstractDrawingView.addToSelection(), org.jhotdraw.draw.DefaultDrawingView.addToSelection(), org.jhotdraw.draw.figure.AbstractCompositeFigure.basicAdd(), org.jhotdraw.draw.figure.LabeledLineConnectionFigure.basicAdd(), org.jhotdraw.draw.figure.QuadTreeCompositeFigure.basicAdd(), org.jhotdraw.draw.handle.BezierControlPointHandle.BezierControlPointHandle(), org.jhotdraw.draw.handle.BezierNodeHandle.BezierNodeHandle(), org.jhotdraw.draw.figure.AbstractCompositeFigure.clone(), org.jhotdraw.draw.figure.LabeledLineConnectionFigure.clone(), org.jhotdraw.draw.figure.LineConnectionFigure.clone(), org.jhotdraw.draw.GraphicalCompositeFigure.clone(), org.jhotdraw.draw.text.FloatingTextArea.createOverlay(), org.jhotdraw.draw.text.FloatingTextField.createOverlay(), org.jhotdraw.draw.event.DrawingComponentRepainter.DrawingComponentRepainter(), org.jhotdraw.draw.event.DrawingComponentRepainter.propertyChange(), org.jhotdraw.draw.event.SelectionComponentRepainter.propertyChange(), org.jhotdraw.draw.figure.LabelFigure.remap(), org.jhotdraw.draw.event.SelectionComponentRepainter.SelectionComponentRepainter(), org.jhotdraw.draw.AbstractDrawingView.setDrawing(), org.jhotdraw.draw.DefaultDrawingView.setDrawing(), org.jhotdraw.draw.figure.LineConnectionFigure.setEndConnector(), org.jhotdraw.draw.figure.LabelFigure.setLabelFor(), org.jhotdraw.draw.GraphicalCompositeFigure.setPresentationFigure(), and org.jhotdraw.draw.figure.LineConnectionFigure.setStartConnector().
addNotify()
void org.jhotdraw.draw.figure.Figure.addNotify (Drawing d)
Informs a figure, that it has been added to a drawing. The figure must inform all FigureListeners that it has been added.
Implemented in org.jhotdraw.draw.GraphicalCompositeFigure, org.jhotdraw.draw.figure.LineConnectionFigure, org.jhotdraw.draw.figure.LabeledLineConnectionFigure, org.jhotdraw.draw.figure.AbstractCompositeFigure, and org.jhotdraw.draw.figure.AbstractFigure.
Referenced by org.jhotdraw.draw.figure.LabeledLineConnectionFigure.add(), org.jhotdraw.draw.figure.AbstractCompositeFigure.add(), org.jhotdraw.draw.GraphicalCompositeFigure.addNotify(), and org.jhotdraw.draw.GraphicalCompositeFigure.setPresentationFigure().
addPropertyChangeListener()
void org.jhotdraw.draw.figure.Figure.addPropertyChangeListener (PropertyChangeListener listener)
Adds a
PropertyChangeListener
which can optionally be wrapped into a
WeakPropertyChangeListener
.
Parameters
listener
changed()
void org.jhotdraw.draw.figure.Figure.changed ()
Informs that a Figure changed its visual representation and needs to be redrawn.
This fires a FigureListener.figureChanged event for the current display bounds of the figure.
Note: willChange and changed are typically used as pairs before and after invoking one or multiple basic-methods on the Figure.
See also
willChange
Implemented in org.jhotdraw.draw.figure.AbstractFigure, and org.jhotdraw.draw.figure.AbstractCompositeFigure.
Referenced by org.jhotdraw.draw.action.DrawingAttributeAction.actionPerformed(), org.jhotdraw.draw.action.DrawingColorChooserHandler.applySelectedColorToFigures(), org.jhotdraw.draw.tool.TextAreaCreationTool.endEdit(), org.jhotdraw.draw.tool.TextAreaEditingTool.endEdit(), org.jhotdraw.draw.tool.TextCreationTool.endEdit(), org.jhotdraw.draw.tool.TextEditingTool.endEdit(), org.jhotdraw.draw.action.GroupAction.groupFigures(), org.jhotdraw.draw.handle.AbstractRotateHandle.keyPressed(), org.jhotdraw.draw.handle.FontSizeHandle.keyPressed(), org.jhotdraw.draw.handle.MoveHandle.keyPressed(), org.jhotdraw.draw.tool.ConnectionTool.mouseDragged(), org.jhotdraw.draw.tool.CreationTool.mouseDragged(), org.jhotdraw.draw.tool.ConnectionTool.mouseReleased(), org.jhotdraw.draw.tool.CreationTool.mouseReleased(), org.jhotdraw.draw.io.TextInputFormat.read(), org.jhotdraw.draw.event.AttributeChangeEdit< T >.redo(), org.jhotdraw.draw.event.CompositeFigureEdit.redo(), org.jhotdraw.draw.event.TransformRestoreEdit.redo(), org.jhotdraw.draw.figure.LabeledLineConnectionFigure.remove(), org.jhotdraw.draw.figure.LabeledLineConnectionFigure.removeAllChildren(), org.jhotdraw.draw.figure.LabeledLineConnectionFigure.removeChild(), org.jhotdraw.draw.figure.ImageFigure.setBufferedImage(), org.jhotdraw.draw.figure.ImageFigure.setImage(), org.jhotdraw.draw.figure.ImageFigure.setImageData(), org.jhotdraw.draw.handle.ConnectionEndHandle.setLocation(), org.jhotdraw.draw.handle.ConnectionStartHandle.setLocation(), org.jhotdraw.draw.AttributeKey< WindingRule >.setUndoable(), org.jhotdraw.draw.handle.AbstractConnectionHandle.trackEnd(), org.jhotdraw.draw.handle.FontSizeHandle.trackEnd(), org.jhotdraw.draw.handle.AbstractConnectionHandle.trackStep(), org.jhotdraw.draw.handle.AbstractRotateHandle.trackStep(), org.jhotdraw.draw.handle.BezierScaleHandle.trackStep(), org.jhotdraw.draw.handle.ConnectorHandle.trackStep(), org.jhotdraw.draw.handle.FontSizeHandle.trackStep(), org.jhotdraw.draw.handle.MoveHandle.trackStep(), org.jhotdraw.draw.handle.OrientationHandle.trackStep(), org.jhotdraw.draw.event.AttributeChangeEdit< T >.undo(), org.jhotdraw.draw.event.CompositeFigureEdit.undo(), org.jhotdraw.draw.event.TransformRestoreEdit.undo(), and org.jhotdraw.draw.figure.LineConnectionFigure.updateConnection().
clone()
Figure org.jhotdraw.draw.figure.Figure.clone ()
Returns a clone of the figure, with clones of all aggregated figures, such as children and decorators. The cloned figure does not clone the list of FigureListeners from its original.
Implemented in org.jhotdraw.draw.QuadTreeDrawing, org.jhotdraw.draw.GraphicalCompositeFigure, org.jhotdraw.draw.figure.TriangleFigure, org.jhotdraw.draw.figure.TextFigure, org.jhotdraw.draw.figure.TextAreaFigure, org.jhotdraw.draw.figure.RoundRectangleFigure, org.jhotdraw.draw.figure.RectangleFigure, org.jhotdraw.draw.figure.LineConnectionFigure, org.jhotdraw.draw.figure.LabeledLineConnectionFigure, org.jhotdraw.draw.figure.ImageFigure, org.jhotdraw.draw.figure.EllipseFigure, org.jhotdraw.draw.figure.DiamondFigure, org.jhotdraw.draw.figure.BezierFigure, org.jhotdraw.draw.figure.AbstractFigure, org.jhotdraw.draw.figure.AbstractCompositeFigure, org.jhotdraw.draw.figure.AbstractAttributedFigure, org.jhotdraw.draw.figure.AbstractAttributedDecoratedFigure, org.jhotdraw.draw.figure.AbstractAttributedCompositeFigure, and org.jhotdraw.draw.AbstractDrawing.
Referenced by org.jhotdraw.draw.action.GroupAction.actionPerformed(), org.jhotdraw.draw.tool.ImageTool.activate(), org.jhotdraw.draw.figure.AbstractAttributedDecoratedFigure.clone(), org.jhotdraw.draw.figure.AbstractCompositeFigure.clone(), org.jhotdraw.draw.figure.LabeledLineConnectionFigure.clone(), org.jhotdraw.draw.GraphicalCompositeFigure.clone(), org.jhotdraw.draw.handle.ConnectorHandle.createConnection(), org.jhotdraw.draw.tool.ConnectionTool.createFigure(), org.jhotdraw.draw.tool.CreationTool.createFigure(), org.jhotdraw.draw.io.ImageInputFormat.createImageHolder(), org.jhotdraw.draw.io.TextInputFormat.createTextHolderFigures(), org.jhotdraw.draw.io.SerializationInputOutputFormat.createTransferable(), org.jhotdraw.draw.AbstractDrawingView.duplicate(), org.jhotdraw.draw.DefaultDrawingView.duplicate(), org.jhotdraw.draw.io.ImageInputFormat.ImageInputFormat(), org.jhotdraw.draw.io.ImageInputFormat.read(), and org.jhotdraw.draw.io.TextInputFormat.read().
contains()
boolean org.jhotdraw.draw.figure.Figure.contains (Point2D.Double p)
Checks if a point is contained by the figure.
This is used for hit testing by Tool's.
Implemented in org.jhotdraw.draw.figure.AbstractFigureNGTest.AbstractFigureImpl, org.jhotdraw.draw.GraphicalCompositeFigure, org.jhotdraw.draw.figure.TriangleFigure, org.jhotdraw.draw.figure.RoundRectangleFigure, org.jhotdraw.draw.figure.RectangleFigure, org.jhotdraw.draw.figure.LabeledLineConnectionFigure, org.jhotdraw.draw.figure.EllipseFigure, org.jhotdraw.draw.figure.DiamondFigure, org.jhotdraw.draw.figure.BezierFigure, org.jhotdraw.draw.figure.AbstractCompositeFigure, and org.jhotdraw.draw.figure.AbstractAttributedDecoratedFigure.
Referenced by org.jhotdraw.draw.connector.AbstractConnector.contains(), org.jhotdraw.draw.figure.AbstractAttributedDecoratedFigure.contains(), org.jhotdraw.draw.GraphicalCompositeFigure.contains(), org.jhotdraw.draw.figure.QuadTreeCompositeFigure.findFigure(), org.jhotdraw.draw.QuadTreeDrawing.findFigure(), org.jhotdraw.draw.figure.QuadTreeCompositeFigure.findFigureExcept(), org.jhotdraw.draw.QuadTreeDrawing.findFigureExcept(), org.jhotdraw.draw.figure.AbstractFigure.findFigureInside(), and org.jhotdraw.draw.figure.AbstractFigure.getCursor().
createHandles()
Collection<Handle> org.jhotdraw.draw.figure.Figure.createHandles (int detailLevel)
Creates handles used to manipulate the figure.
Parameters
detailLevel The detail level of the handles. Usually this is 0 for bounding box handles and 1 for point handles. The value -1 is used by the SelectAreaTracker and the HandleTracker to highlight figures, over which the mouse pointer is hovering.
Returns
a Collection of handles
See also
Handle
Implemented in org.jhotdraw.draw.GraphicalCompositeFigure, org.jhotdraw.draw.figure.TriangleFigure, org.jhotdraw.draw.figure.TextFigure, org.jhotdraw.draw.figure.TextAreaFigure, org.jhotdraw.draw.figure.RoundRectangleFigure, org.jhotdraw.draw.figure.LineFigure, org.jhotdraw.draw.figure.LineConnectionFigure, org.jhotdraw.draw.figure.BezierFigure, org.jhotdraw.draw.figure.AbstractFigure, and org.jhotdraw.draw.figure.AbstractCompositeFigure.
Referenced by org.jhotdraw.draw.AbstractDrawingView.addToSelection(), org.jhotdraw.draw.DefaultDrawingView.addToSelection(), org.jhotdraw.draw.tool.DefaultHandleTracker.updateHoverHandles(), and org.jhotdraw.draw.tool.DefaultSelectAreaTracker.updateHoverHandles().
draw()
void org.jhotdraw.draw.figure.Figure.draw (Graphics2D g)
Draws the figure.
Parameters
g The Graphics2D to draw to.
Implemented in org.jhotdraw.draw.figure.AbstractFigureNGTest.AbstractFigureImpl, org.jhotdraw.draw.QuadTreeDrawing, org.jhotdraw.draw.GraphicalCompositeFigure, org.jhotdraw.draw.figure.QuadTreeCompositeFigure, org.jhotdraw.draw.figure.LabeledLineConnectionFigure, org.jhotdraw.draw.figure.AbstractCompositeFigure, org.jhotdraw.draw.figure.AbstractAttributedFigure, org.jhotdraw.draw.figure.AbstractAttributedDecoratedFigure, and org.jhotdraw.draw.DefaultDrawing.
Referenced by org.jhotdraw.draw.tool.ConnectionTool.draw(), org.jhotdraw.draw.figure.AbstractAttributedDecoratedFigure.drawDecorator(), org.jhotdraw.draw.AbstractDrawingView.drawDrawing(), org.jhotdraw.draw.DefaultDrawingView.drawDrawing(), org.jhotdraw.draw.GraphicalCompositeFigure.drawPresentationFigure(), and org.jhotdraw.draw.print.DrawingPageable.printPage().
findCompatibleConnector()
Connector org.jhotdraw.draw.figure.Figure.findCompatibleConnector (Connector c, boolean isStartConnector)
Gets a compatible connector. If the provided connector is part of this figure, return the connector. If the provided connector is part of another figure, return a connector with the same semantics for this figure. Returns null, if no compatible connector is available.
Implemented in org.jhotdraw.draw.figure.TriangleFigure, org.jhotdraw.draw.figure.RoundRectangleFigure, org.jhotdraw.draw.figure.ImageFigure, org.jhotdraw.draw.figure.EllipseFigure, org.jhotdraw.draw.figure.DiamondFigure, org.jhotdraw.draw.figure.BezierFigure, and org.jhotdraw.draw.figure.AbstractFigure.
Referenced by org.jhotdraw.draw.figure.LineConnectionFigure.remap().
findConnector()
Connector org.jhotdraw.draw.figure.Figure.findConnector (Point2D.Double p, ConnectionFigure prototype)
Gets a connector for this figure at the given location. A figure can have different connectors at different locations.
Parameters
p the location of the connector.
prototype The prototype used to create a connection or null if unknown. This allows for specific connectors for different connection figures.
Implemented in org.jhotdraw.draw.figure.TriangleFigure, org.jhotdraw.draw.figure.RoundRectangleFigure, org.jhotdraw.draw.figure.ImageFigure, org.jhotdraw.draw.figure.EllipseFigure, org.jhotdraw.draw.figure.DiamondFigure, org.jhotdraw.draw.figure.BezierFigure, and org.jhotdraw.draw.figure.AbstractFigure.
Referenced by org.jhotdraw.draw.handle.ConnectorHandle.findConnectableConnector(), org.jhotdraw.draw.handle.AbstractConnectionHandle.findConnector(), org.jhotdraw.draw.tool.ConnectionTool.mouseDragged(), and org.jhotdraw.draw.tool.ConnectionTool.mousePressed().
findFigureInside()
Figure org.jhotdraw.draw.figure.Figure.findFigureInside (Point2D.Double p)
Finds the innermost figure at the specified location.
In case of a
CompositeFigure
, this method descends into its children and into its children's children until the innermost figure is found.
This functionality is implemented using the Chain of Responsibility design pattern. A figure which is not composed of other figures returns itself if the point is contained by the figure. Composed figures pass the method call down to their children.
Parameters
p A location on the drawing.
Returns
Returns the innermost figure at the location, or null if the location is not contained in a figure.
Implemented in org.jhotdraw.draw.QuadTreeDrawing, org.jhotdraw.draw.figure.QuadTreeCompositeFigure, org.jhotdraw.draw.figure.LabeledLineConnectionFigure, org.jhotdraw.draw.figure.AbstractFigure, org.jhotdraw.draw.figure.AbstractCompositeFigure, org.jhotdraw.draw.Drawing, and org.jhotdraw.draw.DefaultDrawing.
Referenced by org.jhotdraw.draw.DefaultDrawing.findFigureInside(), org.jhotdraw.draw.figure.AbstractCompositeFigure.findFigureInside(), org.jhotdraw.draw.figure.LabeledLineConnectionFigure.findFigureInside(), org.jhotdraw.draw.figure.QuadTreeCompositeFigure.findFigureInside(), and org.jhotdraw.draw.QuadTreeDrawing.findFigureInside().
get()
public<T> T org.jhotdraw.draw.figure.Figure.get (AttributeKey< T > key)
Gets an attribute from the Figure.
See also
AttributeKey::get
Returns
Returns the attribute value. If the Figure does not have an attribute with the specified key, returns key.getDefaultValue().
Referenced by org.jhotdraw.draw.action.AttributeToggler< T >.actionPerformed(), org.jhotdraw.draw.handle.BoundsOutlineHandle.basicGetBounds(), org.jhotdraw.draw.handle.TextOverflowHandle.basicGetBounds(), org.jhotdraw.draw.layouter.HorizontalLayouter.calculateLayout(), org.jhotdraw.draw.layouter.VerticalLayouter.calculateLayout(), org.jhotdraw.draw.connector.ChopDiamondConnector.chop(), org.jhotdraw.draw.connector.ChopEllipseConnector.chop(), org.jhotdraw.draw.connector.ChopRectangleConnector.chop(), org.jhotdraw.draw.connector.ChopRoundRectangleConnector.chop(), org.jhotdraw.draw.handle.BezierControlPointHandle.draw(), org.jhotdraw.draw.handle.BoundsOutlineHandle.draw(), org.jhotdraw.draw.decoration.AbstractLineDecoration.draw(), org.jhotdraw.draw.AbstractDrawingView.drawBackground(), org.jhotdraw.draw.DefaultDrawingView.drawBackground(), org.jhotdraw.draw.AbstractDrawingView.getCanvasViewBounds(), org.jhotdraw.draw.DefaultDrawingView.getCanvasViewBounds(), org.jhotdraw.draw.figure.LabeledLineConnectionFigure.getChild(), org.jhotdraw.draw.decoration.AbstractLineDecoration.getDecorationRadius(), org.jhotdraw.draw.decoration.AbstractLineDecoration.getDrawingArea(), org.jhotdraw.draw.AttributeKeys.getFont(), org.jhotdraw.draw.AttributeKeys.getFontStyle(), org.jhotdraw.draw.AttributeKeys.getGlobalValueFactor(), org.jhotdraw.draw.AttributeKeys.getHitStroke(), org.jhotdraw.draw.action.DrawingColorChooserAction.getInitialColor(), org.jhotdraw.draw.action.SelectionColorChooserAction.getInitialColor(), org.jhotdraw.draw.layouter.AbstractLayouter.getInsets(), org.jhotdraw.draw.handle.BezierControlPointHandle.getLocation(), org.jhotdraw.draw.handle.BezierNodeHandle.getLocation(), org.jhotdraw.draw.AttributeKeys.getPerpendicularDrawGrowth(), org.jhotdraw.draw.AttributeKeys.getPerpendicularFillGrowth(), org.jhotdraw.draw.AttributeKeys.getPerpendicularHitGrowth(), org.jhotdraw.draw.DefaultDrawingView.getPreferredSize(), org.jhotdraw.draw.AttributeKeys.getStroke(), org.jhotdraw.draw.AttributeKeys.getStrokeTotalMiterLimit(), org.jhotdraw.draw.AttributeKeys.getStrokeTotalWidth(), org.jhotdraw.draw.handle.AbstractRotateHandle.getTransformedBounds(), org.jhotdraw.draw.layouter.HorizontalLayouter.layout(), org.jhotdraw.draw.layouter.VerticalLayouter.layout(), org.jhotdraw.draw.locator.FontSizeLocator.locate(), org.jhotdraw.draw.locator.RelativeLocator.locate(), org.jhotdraw.draw.tool.AbstractTool.maybeFireBoundsInvalidated(), org.jhotdraw.draw.action.DrawingColorIcon.paintIcon(), org.jhotdraw.draw.figure.LabelFigure.remap(), org.jhotdraw.draw.figure.LineConnectionFigure.remap(), org.jhotdraw.draw.io.ImageOutputFormat.toImage(), org.jhotdraw.draw.handle.OrientationHandle.trackStart(), org.jhotdraw.draw.handle.BezierControlPointHandle.trackStep(), org.jhotdraw.draw.handle.BezierNodeHandle.trackStep(), org.jhotdraw.draw.handle.FontSizeHandle.trackStep(), org.jhotdraw.draw.action.DrawingColorChooserHandler.updateEnabledState(), org.jhotdraw.draw.text.FloatingTextField.updateWidget(), org.jhotdraw.draw.figure.AbstractAttributedCompositeFigure.writeAttributes(), org.jhotdraw.draw.figure.AbstractAttributedFigure.writeAttributes(), and org.jhotdraw.draw.GraphicalCompositeFigure.writeAttributes().
getActions()
Collection<Action> org.jhotdraw.draw.figure.Figure.getActions (Point2D.Double p)
Returns a collection of Action's for the specified location on the figure.
The collection may contain null entries. These entries are used interpreted as separators in the popup menu.
Actions can use the property Figure.ACTION_SUBMENU to specify a submenu.
Implemented in org.jhotdraw.draw.figure.ImageFigure, and org.jhotdraw.draw.figure.AbstractFigure.
Referenced by org.jhotdraw.draw.tool.DelegationSelectionTool.showPopupMenu().
getAttributes()
Map<AttributeKey<?>, Object> org.jhotdraw.draw.figure.Figure.getAttributes ()
Returns a view to all attributes of this figure. By convention, an unmodifiable map is returned.
Implemented in org.jhotdraw.draw.figure.AbstractFigureNGTest.AbstractFigureImpl, org.jhotdraw.draw.GraphicalCompositeFigure, org.jhotdraw.draw.figure.AbstractCompositeFigure, org.jhotdraw.draw.figure.AbstractAttributedFigure, and org.jhotdraw.draw.figure.AbstractAttributedCompositeFigure.
Referenced by org.jhotdraw.draw.action.PickAttributesAction.pickAttributes(), and org.jhotdraw.draw.io.SerializationInputOutputFormat.read().
getAttributesRestoreData()
Object org.jhotdraw.draw.figure.Figure.getAttributesRestoreData ()
Gets data which can be used to restore the attributes of the figure after a set has been applied to it.
Implemented in org.jhotdraw.draw.figure.AbstractFigureNGTest.AbstractFigureImpl, org.jhotdraw.draw.figure.AbstractCompositeFigure, org.jhotdraw.draw.figure.AbstractAttributedFigure, and org.jhotdraw.draw.figure.AbstractAttributedCompositeFigure.
Referenced by org.jhotdraw.draw.action.DrawingAttributeAction.actionPerformed(), org.jhotdraw.draw.action.DrawingColorChooserHandler.applySelectedColorToFigures(), org.jhotdraw.draw.handle.FontSizeHandle.keyPressed(), org.jhotdraw.draw.AttributeKey< WindingRule >.setUndoable(), and org.jhotdraw.draw.handle.FontSizeHandle.trackStart().
getBounds()
Rectangle2D.Double org.jhotdraw.draw.figure.Figure.getBounds ()
Returns the untransformed logical bounds of the figure as a Rectangle.
The bounds are used by Handle objects for adjusting the figure and for aligning the figure on a grid.
Implemented in org.jhotdraw.draw.figure.AbstractFigureNGTest.AbstractFigureImpl, org.jhotdraw.draw.GraphicalCompositeFigure, org.jhotdraw.draw.figure.TriangleFigure, org.jhotdraw.draw.figure.TextFigure, org.jhotdraw.draw.figure.TextAreaFigure, org.jhotdraw.draw.figure.RoundRectangleFigure, org.jhotdraw.draw.figure.RectangleFigure, org.jhotdraw.draw.figure.ImageFigure, org.jhotdraw.draw.figure.EllipseFigure, org.jhotdraw.draw.figure.DiamondFigure, org.jhotdraw.draw.figure.BezierFigure, and org.jhotdraw.draw.figure.AbstractCompositeFigure.
Referenced by org.jhotdraw.draw.handle.BoundsOutlineHandle.basicGetBounds(), org.jhotdraw.draw.handle.TextOverflowHandle.basicGetBounds(), org.jhotdraw.draw.connector.ChopDiamondConnector.chop(), org.jhotdraw.draw.connector.ChopEllipseConnector.chop(), org.jhotdraw.draw.connector.ChopRectangleConnector.chop(), org.jhotdraw.draw.connector.StickyRectangleConnector.chop(), org.jhotdraw.draw.handle.BoundsOutlineHandle.draw(), org.jhotdraw.draw.tool.TextAreaCreationTool.draw(), org.jhotdraw.draw.connector.ChopRectangleConnector.findEnd(), org.jhotdraw.draw.connector.ChopRectangleConnector.findStart(), org.jhotdraw.draw.figure.AbstractFigure.fireFigureAdded(), org.jhotdraw.draw.figure.AbstractFigure.fireFigureRemoved(), org.jhotdraw.draw.figure.AbstractFigure.fireFigureRequestRemove(), org.jhotdraw.draw.connector.AbstractConnector.getBounds(), org.jhotdraw.draw.GraphicalCompositeFigure.getBounds(), org.jhotdraw.draw.figure.AbstractAttributedFigure.getDrawingArea(), org.jhotdraw.draw.figure.AbstractFigure.getEndPoint(), org.jhotdraw.draw.figure.AbstractFigure.getPreferredSize(), org.jhotdraw.draw.figure.AbstractFigure.getStartPoint(), org.jhotdraw.draw.handle.AbstractRotateHandle.getTransformedBounds(), org.jhotdraw.draw.figure.LabeledLineConnectionFigure.layout(), org.jhotdraw.draw.locator.RelativeDecoratorLocator.locate(), org.jhotdraw.draw.locator.RelativeLocator.locate(), org.jhotdraw.draw.tool.CreationTool.mouseReleased(), org.jhotdraw.draw.io.ImageInputFormat.read(), org.jhotdraw.draw.connector.StickyRectangleConnector.StickyRectangleConnector(), org.jhotdraw.draw.connector.StickyRectangleConnector.updateAnchor(), org.jhotdraw.draw.text.FloatingTextField.updateWidget(), and org.jhotdraw.draw.figure.AbstractAttributedFigure.write().
getConnectors()
Collection<Connector> org.jhotdraw.draw.figure.Figure.getConnectors (ConnectionFigure prototype)
Returns all connectors of this Figure for the specified prototype of a ConnectionFigure.
This is used by connection tools and connection handles to visualize the connectors when the user is about to create a ConnectionFigure to this Figure.
Parameters
prototype The prototype used to create a connection or null if unknown. This allows for specific connectors for different connection figures.
Implemented in org.jhotdraw.draw.figure.AbstractFigure.
Referenced by org.jhotdraw.draw.tool.ConnectionTool.draw(), org.jhotdraw.draw.handle.AbstractConnectionHandle.repaintConnectors(), org.jhotdraw.draw.handle.ConnectorHandle.repaintConnectors(), and org.jhotdraw.draw.tool.ConnectionTool.repaintConnectors().
getCursor()
Cursor org.jhotdraw.draw.figure.Figure.getCursor (Point2D.Double p)
Returns a cursor for the specified location.
Implemented in org.jhotdraw.draw.figure.AbstractFigure.
Referenced by org.jhotdraw.draw.tool.AbstractTool.updateCursor().
getDecomposition()
Collection<Figure> org.jhotdraw.draw.figure.Figure.getDecomposition ()
Returns a decompositon of a figure into its parts. A figure is considered as a part of itself.
Implemented in org.jhotdraw.draw.figure.AbstractFigure, and org.jhotdraw.draw.figure.AbstractCompositeFigure.
getDrawingArea() [1/2]
Rectangle2D.Double org.jhotdraw.draw.figure.Figure.getDrawingArea ()
Returns the drawing area of the figure as a Rectangle.
The drawing area is used to inform DrawingView about the area that is needed to draw this figure.
The drawing area needs to be large enough, to take line width, line caps and other decorations into account that exceed the bounds of the Figure.
Implemented in org.jhotdraw.draw.figure.AbstractFigureNGTest.AbstractFigureImpl, org.jhotdraw.draw.GraphicalCompositeFigure, org.jhotdraw.draw.figure.TriangleFigure, org.jhotdraw.draw.figure.RoundRectangleFigure, org.jhotdraw.draw.figure.RectangleFigure, org.jhotdraw.draw.figure.LabeledLineConnectionFigure, org.jhotdraw.draw.figure.EllipseFigure, org.jhotdraw.draw.figure.DiamondFigure, org.jhotdraw.draw.figure.AbstractCompositeFigure, org.jhotdraw.draw.figure.AbstractAttributedFigure, and org.jhotdraw.draw.figure.AbstractAttributedDecoratedFigure.
Referenced by org.jhotdraw.draw.figure.QuadTreeCompositeFigure.basicAdd(), org.jhotdraw.draw.QuadTreeDrawing.basicAdd(), org.jhotdraw.draw.figure.AbstractCompositeFigure.bringToFront(), org.jhotdraw.draw.figure.QuadTreeCompositeFigure.bringToFront(), org.jhotdraw.draw.QuadTreeDrawing.bringToFront(), org.jhotdraw.draw.figure.AbstractFigure.changed(), org.jhotdraw.draw.DefaultDrawingViewTransferHandler.exportAsDrag(), org.jhotdraw.draw.figure.QuadTreeCompositeFigure.FigureHandler.figureChanged(), org.jhotdraw.draw.QuadTreeDrawing.QuadTreeEventHandler.figureChanged(), org.jhotdraw.draw.figure.AbstractFigure.fireAreaInvalidated(), org.jhotdraw.draw.figure.AbstractCompositeFigure.fireFigureAdded(), org.jhotdraw.draw.figure.LabeledLineConnectionFigure.fireFigureAdded(), org.jhotdraw.draw.figure.AbstractFigure.fireFigureChanged(), org.jhotdraw.draw.figure.AbstractFigure.fireFigureHandlesChanged(), org.jhotdraw.draw.figure.AbstractCompositeFigure.fireFigureRemoved(), org.jhotdraw.draw.figure.LabeledLineConnectionFigure.fireFigureRemoved(), org.jhotdraw.draw.AbstractDrawingView.getDrawingArea(), org.jhotdraw.draw.DefaultDrawingView.getDrawingArea(), org.jhotdraw.draw.figure.AbstractAttributedDecoratedFigure.getDrawingArea(), org.jhotdraw.draw.tool.ConnectionTool.repaintConnectors(), org.jhotdraw.draw.figure.AbstractCompositeFigure.sendToBack(), org.jhotdraw.draw.figure.QuadTreeCompositeFigure.sendToBack(), org.jhotdraw.draw.QuadTreeDrawing.sendToBack(), org.jhotdraw.draw.tool.DefaultHandleTracker.updateHoverHandles(), and org.jhotdraw.draw.tool.DefaultSelectAreaTracker.updateHoverHandles().
getDrawingArea() [2/2]
Rectangle2D.Double org.jhotdraw.draw.figure.Figure.getDrawingArea (double factor)
Returns the drawing area of the figure as a Rectangle.
The drawing area is used to inform DrawingView about the area that is needed to draw this figure.
The drawing area needs to be large enough, to take line width, line caps and other decorations into account that exceed the bounds of the Figure.
Implemented in org.jhotdraw.draw.figure.AbstractFigureNGTest.AbstractFigureImpl, org.jhotdraw.draw.figure.BezierFigure, org.jhotdraw.draw.figure.AbstractCompositeFigure, and org.jhotdraw.draw.figure.AbstractAttributedFigure.
getEndPoint()
Point2D.Double org.jhotdraw.draw.figure.Figure.getEndPoint ()
Returns the untransformed logical end point of the bounds.
See also
setBounds
Implemented in org.jhotdraw.draw.figure.ConnectionFigure, org.jhotdraw.draw.figure.BezierFigure, and org.jhotdraw.draw.figure.AbstractFigure.
Referenced by org.jhotdraw.draw.figure.ImageFigure.transform(), and org.jhotdraw.draw.figure.TextAreaFigure.transform().
getLayer()
int org.jhotdraw.draw.figure.Figure.getLayer ()
Gets the layer number of the figure. The layer is used to determine the z-ordering of a figure inside of a drawing. Figures with a higher layer number are drawn after figures with a lower number. The z-order of figures within the same layer is determined by the sequence the figures were added to a drawing. Figures added later to a drawn after figures which have been added before. If a figure changes its layer, it must fire a FigureListener.figureChanged event to its figure listeners.
Implemented in org.jhotdraw.draw.figure.AbstractFigure.
Referenced by org.jhotdraw.draw.FigureLayerComparator.compare().
getPreferredSize()
Dimension2DDouble org.jhotdraw.draw.figure.Figure.getPreferredSize ()
The preferred size is used by Layouter to determine the preferred size of a Figure. For most Figure's this is the same as the dimensions returned by getBounds.
Implemented in org.jhotdraw.draw.figure.TextFigure, org.jhotdraw.draw.figure.AbstractFigure, and org.jhotdraw.draw.figure.AbstractCompositeFigure.
Referenced by org.jhotdraw.draw.io.TextInputFormat.createTextHolderFigures(), org.jhotdraw.draw.locator.BezierLabelLocator.getRelativeLabelPoint(), and org.jhotdraw.draw.io.TextInputFormat.read().
getStartPoint()
Point2D.Double org.jhotdraw.draw.figure.Figure.getStartPoint ()
Returns the untransformed logical start point of the bounds.
See also
setBounds
Implemented in org.jhotdraw.draw.figure.ConnectionFigure, org.jhotdraw.draw.figure.BezierFigure, and org.jhotdraw.draw.figure.AbstractFigure.
Referenced by org.jhotdraw.draw.locator.FontSizeLocator.locate(), org.jhotdraw.draw.figure.ImageFigure.transform(), and org.jhotdraw.draw.figure.TextAreaFigure.transform().
getTool()
Tool org.jhotdraw.draw.figure.Figure.getTool (Point2D.Double p)
Returns a specialized tool for the specified location.
Returns null, if no specialized tool is available.
Implemented in org.jhotdraw.draw.figure.TextFigure, org.jhotdraw.draw.figure.TextAreaFigure, org.jhotdraw.draw.figure.LabelFigure, and org.jhotdraw.draw.figure.AbstractFigure.
Referenced by org.jhotdraw.draw.tool.DelegationSelectionTool.handleDoubleClick().
getToolTipText()
String org.jhotdraw.draw.figure.Figure.getToolTipText (Point2D.Double p)
Returns a tooltip for the specified location on the figure.
Implemented in org.jhotdraw.draw.figure.AbstractFigure.
Referenced by org.jhotdraw.draw.tool.DelegationSelectionTool.getToolTipText().
getTransformRestoreData()
Object org.jhotdraw.draw.figure.Figure.getTransformRestoreData ()
Gets data which can be used to restore the transformation of the figure without loss of precision, after a transform has been applied to it.
See also
transform(AffineTransform)
Implemented in org.jhotdraw.draw.figure.AbstractFigureNGTest.AbstractFigureImpl, org.jhotdraw.draw.figure.TriangleFigure, org.jhotdraw.draw.figure.TextFigure, org.jhotdraw.draw.figure.TextAreaFigure, org.jhotdraw.draw.figure.RoundRectangleFigure, org.jhotdraw.draw.figure.RectangleFigure, org.jhotdraw.draw.figure.ImageFigure, org.jhotdraw.draw.figure.EllipseFigure, org.jhotdraw.draw.figure.DiamondFigure, org.jhotdraw.draw.figure.BezierFigure, and org.jhotdraw.draw.figure.AbstractCompositeFigure.
Referenced by org.jhotdraw.draw.handle.AbstractRotateHandle.trackStart().
handleDrop()
boolean org.jhotdraw.draw.figure.Figure.handleDrop (Point2D.Double p, Collection< Figure > droppedFigures, DrawingView view)
Handles a drop.
Parameters
p The location of the mouse event.
droppedFigures The dropped figures.
view The drawing view which is the source of the mouse event.
Returns
Returns true, if the figures should snap back to the location they were dragged from.
Implemented in org.jhotdraw.draw.figure.AbstractFigure.
Referenced by org.jhotdraw.draw.tool.DefaultDragTracker.mouseReleased().
handleMouseClick()
boolean org.jhotdraw.draw.figure.Figure.handleMouseClick (Point2D.Double p, MouseEvent evt, DrawingView view)
Handles a mouse click.
Parameters
p The location of the mouse event.
evt The mouse event.
view The drawing view which is the source of the mouse event.
Returns
Returns true, if the event was consumed.
Implemented in org.jhotdraw.draw.figure.LineFigure, org.jhotdraw.draw.figure.LineConnectionFigure, org.jhotdraw.draw.figure.BezierFigure, and org.jhotdraw.draw.figure.AbstractFigure.
Referenced by org.jhotdraw.draw.tool.DelegationSelectionTool.handleDoubleClick().
includes()
boolean org.jhotdraw.draw.figure.Figure.includes (Figure figure)
Checks whether the given figure is contained in this figure. A figure includes itself.
Implemented in org.jhotdraw.draw.figure.AbstractFigure.
Referenced by org.jhotdraw.draw.handle.ConnectorHandle.findConnectableConnector().
isConnectable()
boolean org.jhotdraw.draw.figure.Figure.isConnectable ()
Returns true if this Figure can be connected to a ConnectionFigure.
Implemented in org.jhotdraw.draw.figure.AbstractFigure.
Referenced by org.jhotdraw.draw.figure.LineConnectionFigure.canConnect(), org.jhotdraw.draw.handle.ConnectorHandle.findConnectableConnector(), and org.jhotdraw.draw.tool.ConnectionTool.repaintConnectors().
isRemovable()
boolean org.jhotdraw.draw.figure.Figure.isRemovable ()
Returns true, if the user may remove this figure. If this operation returns false, Tool's should not remove this figure on behalf of the user.
Please note, that even if this method returns false, the Figure may be removed from the Drawing for other reasons. For example, if the Figure is used to display a warning message, the Figure can be removed from the Drawing, when the warning message is no longer relevant.
Implemented in org.jhotdraw.draw.figure.AbstractFigure.
isSelectable()
boolean org.jhotdraw.draw.figure.Figure.isSelectable ()
Returns true, if the user may select this figure. If this operation returns false, Tool's should not select this figure on behalf of the user.
Please note, that even if this method returns false, the Figure may become part of a selection for other reasons. For example, if the Figure is part of a GroupFigure, then the Figure is indirectly part of the selection, when the user selects the GroupFigure.
Implemented in org.jhotdraw.draw.figure.AbstractFigure.
Referenced by org.jhotdraw.draw.tool.CreationTool.creationFinished(), org.jhotdraw.draw.tool.DelegationSelectionTool.handleDoubleClick(), org.jhotdraw.draw.tool.DefaultHandleTracker.mouseMoved(), org.jhotdraw.draw.tool.DefaultSelectAreaTracker.mouseMoved(), org.jhotdraw.draw.tool.SelectionTool.mousePressed(), org.jhotdraw.draw.tool.AbstractTool.updateCursor(), org.jhotdraw.draw.tool.DefaultHandleTracker.updateHoverHandles(), and org.jhotdraw.draw.tool.DefaultSelectAreaTracker.updateHoverHandles().
isTransformable()
boolean org.jhotdraw.draw.figure.Figure.isTransformable ()
Returns true, if the user may transform this figure. If this operation returns false, Tool's should not transform this figure on behalf of the user.
Please note, that even if this method returns false, the Figure may be transformed for other reasons. For example, if the Figure takes part in an animation.
See also
transform
Implemented in org.jhotdraw.draw.figure.GroupFigure, and org.jhotdraw.draw.figure.AbstractFigure.
Referenced by org.jhotdraw.draw.handle.ResizeHandleKit.addCornerResizeHandles(), org.jhotdraw.draw.handle.TransformHandleKit.addCornerTransformHandles(), org.jhotdraw.draw.handle.ResizeHandleKit.addEdgeResizeHandles(), org.jhotdraw.draw.handle.TransformHandleKit.addEdgeTransformHandles(), org.jhotdraw.draw.handle.ResizeHandleKit.addResizeHandles(), org.jhotdraw.draw.handle.TransformHandleKit.addScaleMoveTransformHandles(), org.jhotdraw.draw.handle.TransformHandleKit.addTransformHandles(), org.jhotdraw.draw.handle.AbstractRotateHandle.keyPressed(), org.jhotdraw.draw.handle.MoveHandle.keyPressed(), and org.jhotdraw.draw.handle.MoveHandle.trackStep().
isVisible()
boolean org.jhotdraw.draw.figure.Figure.isVisible ()
A Figure is only drawn by a CompositeFigure, if it is visible. Layouter's should ignore invisible figures too.
Implemented in org.jhotdraw.draw.figure.AbstractFigure.
Referenced by org.jhotdraw.draw.DefaultDrawing.findFigureExcept().
remap()
void org.jhotdraw.draw.figure.Figure.remap (Map< Figure, Figure > oldToNew, boolean disconnectIfNotInMap)
After cloning a collection of figures, the ConnectionFigures contained in this collection still connect to the original figures instead of to the clones. Using This operation and providing a map, which maps from the original collection of figures to the new collection, connections can be remapped to the new figures.
Implemented in org.jhotdraw.draw.figure.LineConnectionFigure, org.jhotdraw.draw.figure.LabelFigure, org.jhotdraw.draw.figure.LabeledLineConnectionFigure, and org.jhotdraw.draw.figure.AbstractFigure.
Referenced by org.jhotdraw.draw.GraphicalCompositeFigure.remap().
removeFigureListener()
void org.jhotdraw.draw.figure.Figure.removeFigureListener (FigureListener l)
Removes a listener for FigureEvent's.
Implemented in org.jhotdraw.draw.figure.AbstractFigure.
Referenced by org.jhotdraw.draw.figure.AbstractCompositeFigure.basicRemoveChild(), org.jhotdraw.draw.figure.LabeledLineConnectionFigure.basicRemoveChild(), org.jhotdraw.draw.figure.QuadTreeCompositeFigure.basicRemoveChild(), org.jhotdraw.draw.event.DrawingComponentRepainter.dispose(), org.jhotdraw.draw.event.SelectionComponentRepainter.dispose(), org.jhotdraw.draw.handle.AbstractHandle.dispose(), org.jhotdraw.draw.handle.BezierControlPointHandle.dispose(), org.jhotdraw.draw.handle.BezierNodeHandle.dispose(), org.jhotdraw.draw.text.FloatingTextArea.endOverlay(), org.jhotdraw.draw.text.FloatingTextField.endOverlay(), org.jhotdraw.draw.figure.LabelFigure.figureRemoved(), org.jhotdraw.draw.event.DrawingComponentRepainter.propertyChange(), org.jhotdraw.draw.event.SelectionComponentRepainter.propertyChange(), org.jhotdraw.draw.figure.LabelFigure.remap(), org.jhotdraw.draw.AbstractDrawingView.removeFromSelection(), org.jhotdraw.draw.DefaultDrawingView.removeFromSelection(), org.jhotdraw.draw.AbstractDrawingView.setDrawing(), org.jhotdraw.draw.DefaultDrawingView.setDrawing(), org.jhotdraw.draw.figure.LineConnectionFigure.setEndConnector(), org.jhotdraw.draw.figure.LabelFigure.setLabelFor(), org.jhotdraw.draw.GraphicalCompositeFigure.setPresentationFigure(), and org.jhotdraw.draw.figure.LineConnectionFigure.setStartConnector().
removeNotify()
void org.jhotdraw.draw.figure.Figure.removeNotify (Drawing d)
Informs a figure, that it has been removed from a drawing. The figure must inform all FigureListeners that it has been removed.
Implemented in org.jhotdraw.draw.GraphicalCompositeFigure, org.jhotdraw.draw.figure.LineConnectionFigure, org.jhotdraw.draw.figure.LabeledLineConnectionFigure, org.jhotdraw.draw.figure.AbstractCompositeFigure, and org.jhotdraw.draw.figure.AbstractFigure.
Referenced by org.jhotdraw.draw.figure.LabeledLineConnectionFigure.removeAllChildren(), org.jhotdraw.draw.figure.AbstractCompositeFigure.removeChild(), org.jhotdraw.draw.figure.LabeledLineConnectionFigure.removeChild(), org.jhotdraw.draw.GraphicalCompositeFigure.removeNotify(), and org.jhotdraw.draw.GraphicalCompositeFigure.setPresentationFigure().
removePropertyChangeListener()
void org.jhotdraw.draw.figure.Figure.removePropertyChangeListener (PropertyChangeListener listener)
Removes a
PropertyChangeListener
. If the listener was added wrapped into a
WeakPropertyChangeListener
, the
WeakPropertyChangeListener
is removed.
Parameters
listener
requestRemove()
void org.jhotdraw.draw.figure.Figure.requestRemove ()
Fires a FigureListener.figureRequestRemove event.
Implemented in org.jhotdraw.draw.figure.AbstractFigure.
Referenced by org.jhotdraw.draw.handle.CloseHandle.trackEnd().
restoreAttributesTo()
void org.jhotdraw.draw.figure.Figure.restoreAttributesTo (Object restoreData)
Restores the attributes of the figure to a previously stored state.
Implemented in org.jhotdraw.draw.figure.AbstractFigureNGTest.AbstractFigureImpl, org.jhotdraw.draw.figure.AbstractAttributedFigure, org.jhotdraw.draw.figure.AbstractAttributedCompositeFigure, and org.jhotdraw.draw.figure.AbstractCompositeFigure.
Referenced by org.jhotdraw.draw.action.DrawingAttributeAction.actionPerformed(), org.jhotdraw.draw.action.DrawingColorChooserHandler.applySelectedColorToFigures(), org.jhotdraw.draw.handle.FontSizeHandle.keyPressed(), org.jhotdraw.draw.AttributeKey< WindingRule >.setUndoable(), and org.jhotdraw.draw.handle.FontSizeHandle.trackEnd().
restoreTransformTo()
void org.jhotdraw.draw.figure.Figure.restoreTransformTo (Object restoreData)
Restores the transform of the figure to a previously stored state.
Implemented in org.jhotdraw.draw.figure.AbstractFigureNGTest.AbstractFigureImpl, org.jhotdraw.draw.figure.TriangleFigure, org.jhotdraw.draw.figure.TextFigure, org.jhotdraw.draw.figure.TextAreaFigure, org.jhotdraw.draw.figure.RoundRectangleFigure, org.jhotdraw.draw.figure.RectangleFigure, org.jhotdraw.draw.figure.ImageFigure, org.jhotdraw.draw.figure.EllipseFigure, org.jhotdraw.draw.figure.DiamondFigure, org.jhotdraw.draw.figure.BezierFigure, and org.jhotdraw.draw.figure.AbstractCompositeFigure.
Referenced by org.jhotdraw.draw.event.TransformRestoreEdit.redo(), org.jhotdraw.draw.handle.AbstractRotateHandle.trackStep(), org.jhotdraw.draw.handle.BezierScaleHandle.trackStep(), and org.jhotdraw.draw.event.TransformRestoreEdit.undo().
set()
public<T> void org.jhotdraw.draw.figure.Figure.set (AttributeKey< T > key, T value)
Sets an attribute on the figure and calls
attributeChanged
on all registered
FigureListener
s if the attribute value has changed.
For efficiency reasons, the drawing is not automatically repainted. If you want the drawing to be repainted when the attribute is changed, you can either use
key.set(figure, value);
or
figure.willChange();
figure.set(...);
figure.changed();
See also
AttributeKey::set
Referenced by org.jhotdraw.draw.action.DrawingAttributeAction.actionPerformed(), org.jhotdraw.draw.DefaultDrawingEditor.applyDefaultAttributesTo(), org.jhotdraw.draw.action.DrawingColorChooserHandler.applySelectedColorToFigures(), org.jhotdraw.draw.tool.ConnectionTool.createFigure(), org.jhotdraw.draw.tool.CreationTool.createFigure(), org.jhotdraw.draw.io.SerializationInputOutputFormat.read(), org.jhotdraw.draw.event.AttributeChangeEdit< T >.redo(), org.jhotdraw.draw.AttributeKey< WindingRule >.setClone(), org.jhotdraw.draw.AttributeKey< WindingRule >.setUndoable(), org.jhotdraw.draw.handle.OrientationHandle.trackStep(), and org.jhotdraw.draw.event.AttributeChangeEdit< T >.undo().
setBounds()
void org.jhotdraw.draw.figure.Figure.setBounds (Point2D.Double start, Point2D.Double end)
Sets the logical and untransformed bounds of the figure.
This is used by Tool's which create a new Figure and by Tool's which connect a Figure to another Figure.
This is a basic operation which does not fire events. Use the following code sequence, if you need event firing:
figure.willChange();
figure.setBounds(...);
figure.changed();
Parameters
start the start point of the bounds
end the end point of the bounds
See also
getBounds
Implemented in org.jhotdraw.draw.GraphicalCompositeFigure, org.jhotdraw.draw.figure.TriangleFigure, org.jhotdraw.draw.figure.TextFigure, org.jhotdraw.draw.figure.TextAreaFigure, org.jhotdraw.draw.figure.RoundRectangleFigure, org.jhotdraw.draw.figure.RectangleFigure, org.jhotdraw.draw.figure.ImageFigure, org.jhotdraw.draw.figure.EllipseFigure, org.jhotdraw.draw.figure.DiamondFigure, org.jhotdraw.draw.figure.BezierFigure, org.jhotdraw.draw.figure.AbstractFigure, and org.jhotdraw.draw.figure.AbstractCompositeFigure.
Referenced by org.jhotdraw.draw.GraphicalCompositeFigure.basicSetPresentationFigureBounds(), org.jhotdraw.draw.io.ImageInputFormat.createImageHolder(), org.jhotdraw.draw.io.TextInputFormat.createTextHolderFigures(), org.jhotdraw.draw.tool.CreationTool.mouseDragged(), org.jhotdraw.draw.tool.CreationTool.mousePressed(), org.jhotdraw.draw.tool.CreationTool.mouseReleased(), org.jhotdraw.draw.io.ImageInputFormat.read(), org.jhotdraw.draw.io.TextInputFormat.read(), org.jhotdraw.draw.figure.AbstractAttributedDecoratedFigure.setDecorator(), and org.jhotdraw.draw.figure.AbstractAttributedDecoratedFigure.updateDecoratorBounds().
transform()
void org.jhotdraw.draw.figure.Figure.transform (AffineTransform tx)
Transforms the shape of the Figure. Transformations using double precision arithmethics are inherently lossy operations. Therefore it is recommended to use getTransformRestoreData() restoreTransformTo() to provide lossless undo/redo functionality.
This is a basic operation which does not fire events. Use the following code sequence, if you need event firing:
figure.willChange();
figure.transform(...);
figure.changed();
Parameters
tx The transformation.
See also
getTransformRestoreData
restoreTransformTo
Implemented in org.jhotdraw.draw.figure.AbstractFigureNGTest.AbstractFigureImpl, org.jhotdraw.draw.GraphicalCompositeFigure, org.jhotdraw.draw.figure.TriangleFigure, org.jhotdraw.draw.figure.TextFigure, org.jhotdraw.draw.figure.TextAreaFigure, org.jhotdraw.draw.figure.RoundRectangleFigure, org.jhotdraw.draw.figure.RectangleFigure, org.jhotdraw.draw.figure.LineConnectionFigure, org.jhotdraw.draw.figure.LabeledLineConnectionFigure, org.jhotdraw.draw.figure.ImageFigure, org.jhotdraw.draw.figure.EllipseFigure, org.jhotdraw.draw.figure.DiamondFigure, org.jhotdraw.draw.figure.BezierFigure, and org.jhotdraw.draw.figure.AbstractCompositeFigure.
Referenced by org.jhotdraw.draw.AbstractDrawingView.duplicate(), org.jhotdraw.draw.DefaultDrawingView.duplicate(), org.jhotdraw.draw.handle.AbstractRotateHandle.keyPressed(), org.jhotdraw.draw.handle.MoveHandle.keyPressed(), org.jhotdraw.draw.handle.AbstractRotateHandle.trackStep(), org.jhotdraw.draw.handle.BezierScaleHandle.trackStep(), org.jhotdraw.draw.handle.MoveHandle.trackStep(), and org.jhotdraw.draw.GraphicalCompositeFigure.transform().
willChange()
void org.jhotdraw.draw.figure.Figure.willChange ()
Informs that the figure is about to change its visual representation (for example, its shape, or its color).
Note: willChange and changed are typically used as pairs before and after invoking one or multiple basic-methods on the Figure.
See also
changed
Implemented in org.jhotdraw.draw.figure.AbstractFigure, and org.jhotdraw.draw.figure.AbstractCompositeFigure.
Referenced by org.jhotdraw.draw.action.DrawingAttributeAction.actionPerformed(), org.jhotdraw.draw.action.DrawingColorChooserHandler.applySelectedColorToFigures(), org.jhotdraw.draw.tool.TextAreaCreationTool.endEdit(), org.jhotdraw.draw.tool.TextAreaEditingTool.endEdit(), org.jhotdraw.draw.tool.TextCreationTool.endEdit(), org.jhotdraw.draw.tool.TextEditingTool.endEdit(), org.jhotdraw.draw.action.GroupAction.groupFigures(), org.jhotdraw.draw.handle.AbstractRotateHandle.keyPressed(), org.jhotdraw.draw.handle.FontSizeHandle.keyPressed(), org.jhotdraw.draw.handle.MoveHandle.keyPressed(), org.jhotdraw.draw.tool.ConnectionTool.mouseDragged(), org.jhotdraw.draw.tool.CreationTool.mouseDragged(), org.jhotdraw.draw.tool.ConnectionTool.mouseReleased(), org.jhotdraw.draw.tool.CreationTool.mouseReleased(), org.jhotdraw.draw.io.TextInputFormat.read(), org.jhotdraw.draw.event.AttributeChangeEdit< T >.redo(), org.jhotdraw.draw.event.CompositeFigureEdit.redo(), org.jhotdraw.draw.event.TransformRestoreEdit.redo(), org.jhotdraw.draw.figure.LabeledLineConnectionFigure.remove(), org.jhotdraw.draw.figure.LabeledLineConnectionFigure.removeAllChildren(), org.jhotdraw.draw.figure.LabeledLineConnectionFigure.removeChild(), org.jhotdraw.draw.figure.ImageFigure.setBufferedImage(), org.jhotdraw.draw.figure.ImageFigure.setImage(), org.jhotdraw.draw.figure.ImageFigure.setImageData(), org.jhotdraw.draw.handle.ConnectionEndHandle.setLocation(), org.jhotdraw.draw.handle.ConnectionStartHandle.setLocation(), org.jhotdraw.draw.AttributeKey< WindingRule >.setUndoable(), org.jhotdraw.draw.handle.AbstractConnectionHandle.trackEnd(), org.jhotdraw.draw.handle.FontSizeHandle.trackEnd(), org.jhotdraw.draw.handle.AbstractConnectionHandle.trackStep(), org.jhotdraw.draw.handle.AbstractRotateHandle.trackStep(), org.jhotdraw.draw.handle.BezierScaleHandle.trackStep(), org.jhotdraw.draw.handle.ConnectorHandle.trackStep(), org.jhotdraw.draw.handle.FontSizeHandle.trackStep(), org.jhotdraw.draw.handle.MoveHandle.trackStep(), org.jhotdraw.draw.handle.OrientationHandle.trackStep(), org.jhotdraw.draw.event.AttributeChangeEdit< T >.undo(), org.jhotdraw.draw.event.CompositeFigureEdit.undo(), org.jhotdraw.draw.event.TransformRestoreEdit.undo(), and org.jhotdraw.draw.figure.LineConnectionFigure.updateConnection().
Member Data Documentation
CONNECTABLE_PROPERTY
final String org.jhotdraw.draw.figure.Figure.CONNECTABLE_PROPERTY = "connectable" static
The name of the "connectable" property.
Referenced by org.jhotdraw.draw.figure.AbstractFigure.setConnectable().
REMOVABLE_PROPERTY
final String org.jhotdraw.draw.figure.Figure.REMOVABLE_PROPERTY = "removable" static
The name of the "removable" property.
Referenced by org.jhotdraw.draw.figure.AbstractFigure.setRemovable().
SELECTABLE_PROPERTY
final String org.jhotdraw.draw.figure.Figure.SELECTABLE_PROPERTY = "selectable" static
The name of the "selectable" property.
Referenced by org.jhotdraw.draw.figure.AbstractFigure.setSelectable().
TRANSFORMABLE_PROPERTY
final String org.jhotdraw.draw.figure.Figure.TRANSFORMABLE_PROPERTY = "transformable" static
The name of the "transformable" property.
Referenced by org.jhotdraw.draw.figure.AbstractFigure.setTransformable().
The documentation for this interface was generated from the following file:
jhotdraw-core/src/main/java/org/jhotdraw/draw/figure/Figure.java