jhotdraw: org.jhotdraw.draw.locator.Locator Interface Reference
org.jhotdraw.draw.locator.Locator Interface Reference
Public Member Functions
Point2D.Double locate (Figure owner)
Point2D.Double locate (Figure owner, Figure dependent)
Detailed Description
A locator encapsulates a strategy for locating a point on a Figure.
Design Patterns
Strategy
Locator
encapsulates a strategy for locating a point on a
Figure
.
Strategy: Locator; Context: Figure.
Author
Werner Randelshofer
Version
$Id$
Member Function Documentation
locate() [1/2]
Point2D.Double org.jhotdraw.draw.locator.Locator.locate (Figure owner)
Locates a position on the provided figure.
Returns
a point on the figure.
Implemented in org.jhotdraw.draw.locator.RelativeLocator, org.jhotdraw.draw.locator.RelativeDecoratorLocator, org.jhotdraw.draw.locator.FontSizeLocator, org.jhotdraw.draw.locator.BezierPointLocator, and org.jhotdraw.draw.locator.BezierLabelLocator.
Referenced by org.jhotdraw.draw.layouter.LocatorLayouter.calculateLayout(), org.jhotdraw.draw.connector.LocatorConnector.getBounds(), org.jhotdraw.draw.handle.LocatorHandle.getLocation(), org.jhotdraw.draw.handle.LocatorHandle.getLocationOnDrawing(), org.jhotdraw.draw.layouter.LocatorLayouter.layout(), and org.jhotdraw.draw.connector.LocatorConnector.locate().
locate() [2/2]
Point2D.Double org.jhotdraw.draw.locator.Locator.locate (Figure owner, Figure dependent)
Locates a position on the provided figure relative to the dependent figure.
Returns
a point on the figure.
Implemented in org.jhotdraw.draw.locator.BezierLabelLocator, org.jhotdraw.draw.locator.FontSizeLocator, and org.jhotdraw.draw.locator.AbstractLocator.
The documentation for this interface was generated from the following file:
jhotdraw-core/src/main/java/org/jhotdraw/draw/locator/Locator.java