jhotdraw: org.jhotdraw.draw.liner.Liner Interface Reference
org.jhotdraw.draw.liner.Liner Interface Reference
Public Member Functions
void lineout (ConnectionFigure figure)
Collection< Handle > createHandles (BezierPath path)
Liner clone ()
Detailed Description
A liner encapsulates a strategy for laying out the bezier path of a ConnectionFigure.
Design Patterns
Strategy
The control points of the bezier path of a connection figure can be laid out using different layout algorithms which are implemented by liners.
Context: ConnectionFigure; Strategy: Liner.
Author
Werner Randelshofer
Version
$Id$
Member Function Documentation
clone()
Liner org.jhotdraw.draw.liner.Liner.clone ()
Implemented in org.jhotdraw.draw.liner.SlantedLiner, org.jhotdraw.draw.liner.ElbowLiner, and org.jhotdraw.draw.liner.CurvedLiner.
Referenced by org.jhotdraw.draw.figure.LineConnectionFigure.clone(), org.jhotdraw.draw.liner.CurvedLiner.clone(), org.jhotdraw.draw.liner.ElbowLiner.clone(), and org.jhotdraw.draw.liner.SlantedLiner.clone().
createHandles()
Collection<Handle> org.jhotdraw.draw.liner.Liner.createHandles (BezierPath path)
Creates Handle's for the Liner. The ConnectionFigure can provide these handles to the user, in order to let her control the lineout.
Parameters
path The path for which to create handles.
Implemented in org.jhotdraw.draw.liner.SlantedLiner, org.jhotdraw.draw.liner.ElbowLiner, and org.jhotdraw.draw.liner.CurvedLiner.
lineout()
void org.jhotdraw.draw.liner.Liner.lineout (ConnectionFigure figure)
Layouts the Path. This may alter the number and type of points in the Path.
Parameters
figure The ConnectionFigure to be lined out.
Implemented in org.jhotdraw.draw.liner.SlantedLiner, org.jhotdraw.draw.liner.ElbowLiner, and org.jhotdraw.draw.liner.CurvedLiner.
Referenced by org.jhotdraw.draw.figure.LineConnectionFigure.lineout().
The documentation for this interface was generated from the following file:
jhotdraw-core/src/main/java/org/jhotdraw/draw/liner/Liner.java