jhotdraw: org.jhotdraw.draw.Constrainer Interface Reference
org.jhotdraw.draw.Constrainer Interface Reference
Public Member Functions
Point2D.Double constrainPoint (Point2D.Double p, Figure... figures)
Point2D.Double translatePoint (Point2D.Double p, TranslationDirection dir, Figure... figures)
Rectangle2D.Double constrainRectangle (Rectangle2D.Double r, Figure... figures)
Rectangle2D.Double translateRectangle (Rectangle2D.Double r, TranslationDirection dir, Figure... figures)
double constrainAngle (double angle, Figure... figures)
double rotateAngle (double angle, RotationDirection dir, Figure... figures)
void draw (Graphics2D g, DrawingView view)
void addChangeListener (ChangeListener listener)
void removeChangeListener (ChangeListener listener)
Detailed Description
A constrainer constrains editing operations performed by org.jhotdraw.draw.tool.Tools and org.jhotdraw.draw.handle.Handles on a DrawingView.
Constrainer
objects are associated to
DrawingView
's.
Constrainers can draw themselves onto the drawing view to visualize the constraints that they impose. Typically by drawing a grid of some kind.
Design Patterns
Strategy
Editing can be constrained by a constrainer which is associated to a drawing view.
Context: DrawingView; Strategy: Constrainer.
Author
Werner Randelshofer
Version
$Id$
Member Function Documentation
addChangeListener()
void org.jhotdraw.draw.Constrainer.addChangeListener (ChangeListener listener)
Adds a change listener.
Implemented in org.jhotdraw.draw.AbstractConstrainer.
constrainAngle()
double org.jhotdraw.draw.Constrainer.constrainAngle (double angle, Figure... figures)
Constrains the given angle (in radians). This method changes the angle which is passed as a parameter.
Parameters
angle The angle (in radians).
Returns
The closest constrained angle (in radians).
Implemented in org.jhotdraw.draw.GridConstrainer.
Referenced by org.jhotdraw.draw.handle.AbstractRotateHandle.trackStep().
constrainPoint()
Point2D.Double org.jhotdraw.draw.Constrainer.constrainPoint (Point2D.Double p, Figure... figures)
Constrains the placement of a point towards the closest constraint in any direction.
This method changes the point which is passed as a parameter.
Parameters
p A point on the drawing.
Returns
Returns the constrained point.
Implemented in org.jhotdraw.draw.GridConstrainer.
Referenced by org.jhotdraw.draw.tool.AbstractTool.constrainPoint(), org.jhotdraw.draw.tool.ConnectionTool.mouseDragged(), org.jhotdraw.draw.tool.BezierTool.mousePressed(), org.jhotdraw.draw.handle.AbstractConnectionHandle.trackEnd(), org.jhotdraw.draw.handle.ConnectorHandle.trackEnd(), org.jhotdraw.draw.handle.MoveHandle.trackStart(), org.jhotdraw.draw.handle.AbstractConnectionHandle.trackStep(), org.jhotdraw.draw.handle.BezierControlPointHandle.trackStep(), org.jhotdraw.draw.handle.BezierNodeHandle.trackStep(), and org.jhotdraw.draw.handle.MoveHandle.trackStep().
constrainRectangle()
Rectangle2D.Double org.jhotdraw.draw.Constrainer.constrainRectangle (Rectangle2D.Double r, Figure... figures)
Constrains the placement of a rectangle towards the closest constrainment in any direction.
This method changes the location of the rectangle which is passed as a parameter. This method does not change the size of the rectangle.
Parameters
r A rectangle on the drawing.
Returns
Returns the constrained rectangle.
Implemented in org.jhotdraw.draw.GridConstrainer.
Referenced by org.jhotdraw.draw.tool.DefaultDragTracker.mouseDragged().
draw()
void org.jhotdraw.draw.Constrainer.draw (Graphics2D g, DrawingView view)
Draws the constrainer grid for the specified drawing view.
Implemented in org.jhotdraw.draw.GridConstrainer.
Referenced by org.jhotdraw.draw.AbstractDrawingView.drawConstrainer(), and org.jhotdraw.draw.DefaultDrawingView.drawConstrainer().
removeChangeListener()
void org.jhotdraw.draw.Constrainer.removeChangeListener (ChangeListener listener)
Removes a change listener.
Implemented in org.jhotdraw.draw.AbstractConstrainer.
rotateAngle()
double org.jhotdraw.draw.Constrainer.rotateAngle (double angle, RotationDirection dir, Figure... figures)
Moves the given angle (in radians) to the closest constrained orientation in the specified direction.
Parameters
angle The angle (in radians).
Returns
The closest constrained angle (in radians) in the specified direction.
Implemented in org.jhotdraw.draw.GridConstrainer.
translatePoint()
Point2D.Double org.jhotdraw.draw.Constrainer.translatePoint (Point2D.Double p, TranslationDirection dir, Figure... figures)
Moves a point to the closest constrained location in the specified direction.
This method changes the point which is passed as a parameter.
Parameters
p A point on the drawing.
dir A direction.
Returns
Returns the constrained point.
Implemented in org.jhotdraw.draw.GridConstrainer.
translateRectangle()
Rectangle2D.Double org.jhotdraw.draw.Constrainer.translateRectangle (Rectangle2D.Double r, TranslationDirection dir, Figure... figures)
Moves a rectangle to the closest constrained location in the specified direction.
This method changes the location of the rectangle which is passed as a parameter. This method only performs a translation - it does not change the size of the rectangle.
Parameters
r A rectangle on the drawing.
dir A direction.
Returns
Returns the constrained rectangle.
Implemented in org.jhotdraw.draw.GridConstrainer.
Referenced by org.jhotdraw.draw.action.MoveConstrainedAction.actionPerformed().
The documentation for this interface was generated from the following file:
jhotdraw-core/src/main/java/org/jhotdraw/draw/Constrainer.java