jhotdraw: org.jhotdraw.draw.figure.ConnectionFigure Interface Reference
org.jhotdraw.draw.figure.ConnectionFigure Interface Reference
Public Member Functions
void setStartConnector (Connector start)
Connector getStartConnector ()
void setEndConnector (Connector end)
Connector getEndConnector ()
void updateConnection ()
boolean canConnect (Connector start, Connector end)
boolean canConnect (Connector start)
void setStartPoint (Point2D.Double p)
void setEndPoint (Point2D.Double p)
void setPoint (int index, Point2D.Double p)
int getNodeCount ()
Point2D.Double getPoint (int index)
BezierPath.Node getNode (int index)
void setNode (int index, BezierPath.Node node)
Point2D.Double getStartPoint ()
Point2D.Double getEndPoint ()
Figure getStartFigure ()
Figure getEndFigure ()
Liner getLiner ()
void setLiner (Liner newValue)
void lineout ()
Public Member Functions inherited from org.jhotdraw.draw.figure.Figure
void draw (Graphics2D g)
int getLayer ()
boolean isVisible ()
void setBounds (Point2D.Double start, Point2D.Double end)
Rectangle2D.Double getBounds ()
Rectangle2D.Double getDrawingArea ()
Rectangle2D.Double getDrawingArea (double factor)
Dimension2DDouble getPreferredSize ()
boolean contains (Point2D.Double p)
Object getTransformRestoreData ()
void restoreTransformTo (Object restoreData)
void transform (AffineTransform tx)
public< T > void set (AttributeKey< T > key, T value)
public< T > T get (AttributeKey< T > key)
Map< AttributeKey<?>, Object > getAttributes ()
Object getAttributesRestoreData ()
void restoreAttributesTo (Object restoreData)
boolean isSelectable ()
boolean isRemovable ()
boolean isTransformable ()
Collection< Handle > createHandles (int detailLevel)
Cursor getCursor (Point2D.Double p)
Collection< Action > getActions (Point2D.Double p)
Tool getTool (Point2D.Double p)
String getToolTipText (Point2D.Double p)
boolean isConnectable ()
Connector findConnector (Point2D.Double p, ConnectionFigure prototype)
Connector findCompatibleConnector (Connector c, boolean isStartConnector)
Collection< Connector > getConnectors (ConnectionFigure prototype)
boolean includes (Figure figure)
Figure findFigureInside (Point2D.Double p)
Collection< Figure > getDecomposition ()
Figure clone ()
void remap (Map< Figure, Figure > oldToNew, boolean disconnectIfNotInMap)
void addNotify (Drawing d)
void removeNotify (Drawing d)
void willChange ()
void changed ()
void requestRemove ()
boolean handleDrop (Point2D.Double p, Collection< Figure > droppedFigures, DrawingView view)
boolean handleMouseClick (Point2D.Double p, MouseEvent evt, DrawingView view)
void addFigureListener (FigureListener l)
void removeFigureListener (FigureListener l)
void addPropertyChangeListener (PropertyChangeListener listener)
void removePropertyChangeListener (PropertyChangeListener listener)
Additional Inherited Members
Static Public Attributes inherited from org.jhotdraw.draw.figure.Figure
static final String CONNECTABLE_PROPERTY = "connectable"
static final String REMOVABLE_PROPERTY = "removable"
static final String SELECTABLE_PROPERTY = "selectable"
static final String TRANSFORMABLE_PROPERTY = "transformable"
Detailed Description
A connection figure connects two figures with a org.jhotdraw.geom.BezierPath.
The location of the start and end points of the bezier path is defined by Connector objects, which are supplied by the connected figures.
If a connected figure is removed, the connection figure needs to be removed as well. To achieve this,
ConnectionFigure
listens to
figureRemoved
events sent by the two figures that it connects, and then fires a
requestRemove
event to get removed as well.
The bezier path of the connection figure can be laid out using a Liner.
Design Patterns
Framework
Two figures can be connected using a connection figure. The location of the start or end point of the connection is handled by a connector object at each connected figure.
Contract: org.jhotdraw.draw.figure.Figure, org.jhotdraw.draw.figure.ConnectionFigure, org.jhotdraw.draw.connector.Connector, org.jhotdraw.draw.tool.ConnectionTool.
Strategy
The control points of the bezier path of a connection figure can be laid out using different layout algorithms which are implemented by a liner object.
Context: ConnectionFigure; Strategy: Liner.
Strategy
The location of the start and end points of a connection figure are determined by
Connector
s which are owned by the connected figures.
Context: Figure, ConnectionFigure; Strategy: Connector.
Author
Werner Randelshofer
Version
$Id$
Member Function Documentation
canConnect() [1/2]
boolean org.jhotdraw.draw.figure.ConnectionFigure.canConnect (Connector start)
Checks if this
ConnectionFigure
can be connect to the specified
Connector
. This is used to provide an early feedback to the user, when he/she creates a new connection.
Implemented in org.jhotdraw.draw.figure.LineConnectionFigure.
canConnect() [2/2]
boolean org.jhotdraw.draw.figure.ConnectionFigure.canConnect (Connector start, Connector end)
Returns true, if this ConnectionFigure can connect the specified
Connector
s. Implement this method to constrain the allowed connections between figures.
Implemented in org.jhotdraw.draw.figure.LineConnectionFigure.
Referenced by org.jhotdraw.draw.tool.ConnectionTool.canConnect(), org.jhotdraw.draw.handle.ConnectionEndHandle.canConnect(), org.jhotdraw.draw.handle.ConnectionStartHandle.canConnect(), org.jhotdraw.draw.handle.ConnectorHandle.findConnectableConnector(), and org.jhotdraw.draw.tool.ConnectionTool.mouseReleased().
getEndConnector()
Connector org.jhotdraw.draw.figure.ConnectionFigure.getEndConnector ()
Gets the end Connector. Returns null, if there is no end connection.
Implemented in org.jhotdraw.draw.figure.LineConnectionFigure.
Referenced by org.jhotdraw.draw.connector.ChopRectangleConnector.findEnd(), org.jhotdraw.draw.connector.ChopRectangleConnector.findStart(), org.jhotdraw.draw.handle.AbstractConnectionHandle.getSource(), org.jhotdraw.draw.handle.ConnectionEndHandle.getTarget(), org.jhotdraw.draw.liner.CurvedLiner.lineout(), org.jhotdraw.draw.liner.ElbowLiner.lineout(), and org.jhotdraw.draw.liner.SlantedLiner.lineout().
getEndFigure()
Figure org.jhotdraw.draw.figure.ConnectionFigure.getEndFigure ()
Gets the end figure of the connection. This is a convenience method for doing getEndConnector().getOwner() and handling null cases.
Implemented in org.jhotdraw.draw.figure.LineConnectionFigure.
Referenced by org.jhotdraw.draw.connector.ChopRectangleConnector.findEnd(), org.jhotdraw.draw.liner.CurvedLiner.lineout(), org.jhotdraw.draw.liner.ElbowLiner.lineout(), and org.jhotdraw.draw.liner.SlantedLiner.lineout().
getEndPoint()
Point2D.Double org.jhotdraw.draw.figure.ConnectionFigure.getEndPoint ()
Gets the end point.
Implements org.jhotdraw.draw.figure.Figure.
Referenced by org.jhotdraw.draw.handle.ConnectorHandle.draw(), org.jhotdraw.draw.tool.ConnectionTool.draw(), org.jhotdraw.draw.connector.ChopRectangleConnector.findStart(), org.jhotdraw.draw.handle.ConnectionEndHandle.getLocation(), and org.jhotdraw.draw.tool.ConnectionTool.mouseDragged().
getLiner()
Liner org.jhotdraw.draw.figure.ConnectionFigure.getLiner ()
Get a Liner object which encapsulated a lineout algorithm for this figure. Typically, a Liner accesses the child components of this figure and arranges their graphical presentation.
Returns
lineout strategy used by this figure
Implemented in org.jhotdraw.draw.figure.LineConnectionFigure.
Referenced by org.jhotdraw.draw.connector.ChopRectangleConnector.findEnd(), org.jhotdraw.draw.connector.ChopRectangleConnector.findStart(), org.jhotdraw.draw.handle.AbstractConnectionHandle.getToolTipText(), and org.jhotdraw.draw.handle.AbstractConnectionHandle.trackStart().
getNode()
BezierPath.Node org.jhotdraw.draw.figure.ConnectionFigure.getNode (int index)
Returns the specified node.
Referenced by org.jhotdraw.draw.handle.AbstractConnectionHandle.trackEnd().
getNodeCount()
int org.jhotdraw.draw.figure.ConnectionFigure.getNodeCount ()
Gets the node count.
Referenced by org.jhotdraw.draw.figure.LineConnectionFigure.createHandles(), org.jhotdraw.draw.connector.ChopRectangleConnector.findEnd(), org.jhotdraw.draw.connector.ChopRectangleConnector.findStart(), and org.jhotdraw.draw.handle.AbstractConnectionHandle.trackEnd().
getPoint()
Point2D.Double org.jhotdraw.draw.figure.ConnectionFigure.getPoint (int index)
Returns the specified point.
Referenced by org.jhotdraw.draw.connector.ChopRectangleConnector.findEnd(), and org.jhotdraw.draw.connector.ChopRectangleConnector.findStart().
getStartConnector()
Connector org.jhotdraw.draw.figure.ConnectionFigure.getStartConnector ()
Gets the start
Connector
. Returns null, if there is no start connection.
Implemented in org.jhotdraw.draw.figure.LineConnectionFigure.
Referenced by org.jhotdraw.draw.connector.ChopRectangleConnector.findEnd(), org.jhotdraw.draw.connector.ChopRectangleConnector.findStart(), org.jhotdraw.draw.handle.AbstractConnectionHandle.getSource(), org.jhotdraw.draw.handle.ConnectionStartHandle.getTarget(), org.jhotdraw.draw.liner.CurvedLiner.lineout(), org.jhotdraw.draw.liner.ElbowLiner.lineout(), and org.jhotdraw.draw.liner.SlantedLiner.lineout().
getStartFigure()
Figure org.jhotdraw.draw.figure.ConnectionFigure.getStartFigure ()
Gets the start figure of the connection. This is a convenience method for doing getStartConnector().getOwner() and handling null cases.
Implemented in org.jhotdraw.draw.figure.LineConnectionFigure.
Referenced by org.jhotdraw.draw.connector.ChopRectangleConnector.findEnd(), org.jhotdraw.draw.liner.CurvedLiner.lineout(), org.jhotdraw.draw.liner.ElbowLiner.lineout(), and org.jhotdraw.draw.liner.SlantedLiner.lineout().
getStartPoint()
Point2D.Double org.jhotdraw.draw.figure.ConnectionFigure.getStartPoint ()
Gets the start point.
Implements org.jhotdraw.draw.figure.Figure.
Referenced by org.jhotdraw.draw.tool.ConnectionTool.draw(), org.jhotdraw.draw.connector.ChopRectangleConnector.findEnd(), and org.jhotdraw.draw.handle.ConnectionStartHandle.getLocation().
lineout()
void org.jhotdraw.draw.figure.ConnectionFigure.lineout ()
A "lineout" algorithm is used to define how the child components should be laid out in relation to each other. The task for layouting the child components for presentation is delegated to a Liner which can be plugged in at runtime.
Implemented in org.jhotdraw.draw.figure.LineConnectionFigure.
setEndConnector()
void org.jhotdraw.draw.figure.ConnectionFigure.setEndConnector (Connector end)
Sets the end Connector of the connection. Set this to null to disconnect the end connection.
Parameters
end the end Connector of the connection
Implemented in org.jhotdraw.draw.figure.LineConnectionFigure.
Referenced by org.jhotdraw.draw.handle.ConnectionEndHandle.connect(), org.jhotdraw.draw.handle.ConnectionEndHandle.disconnect(), org.jhotdraw.draw.tool.ConnectionTool.mouseReleased(), and org.jhotdraw.draw.handle.ConnectorHandle.trackEnd().
setEndPoint()
void org.jhotdraw.draw.figure.ConnectionFigure.setEndPoint (Point2D.Double p)
Sets the end point.
Implemented in org.jhotdraw.draw.figure.LineConnectionFigure.
Referenced by org.jhotdraw.draw.tool.ConnectionTool.mouseDragged(), org.jhotdraw.draw.tool.ConnectionTool.mousePressed(), org.jhotdraw.draw.handle.ConnectionEndHandle.setLocation(), org.jhotdraw.draw.handle.ConnectorHandle.trackStart(), and org.jhotdraw.draw.handle.ConnectorHandle.trackStep().
setLiner()
void org.jhotdraw.draw.figure.ConnectionFigure.setLiner (Liner newValue)
Set a Liner object which encapsulated a lineout algorithm for this figure. Typically, a Liner accesses the child components of this figure and arranges their graphical presentation.
Parameters
newValue encapsulation of a lineout algorithm.
Implemented in org.jhotdraw.draw.figure.LineConnectionFigure.
Referenced by org.jhotdraw.draw.handle.AbstractConnectionHandle.trackEnd(), and org.jhotdraw.draw.handle.AbstractConnectionHandle.trackStart().
setNode()
void org.jhotdraw.draw.figure.ConnectionFigure.setNode (int index, BezierPath.Node node)
Sets the specified node.
Implemented in org.jhotdraw.draw.figure.LineConnectionFigure.
Referenced by org.jhotdraw.draw.handle.AbstractConnectionHandle.trackEnd().
setPoint()
void org.jhotdraw.draw.figure.ConnectionFigure.setPoint (int index, Point2D.Double p)
Sets the specified point.
Implemented in org.jhotdraw.draw.figure.LineConnectionFigure.
setStartConnector()
void org.jhotdraw.draw.figure.ConnectionFigure.setStartConnector (Connector start)
Sets the start
Connector
of the connection. Set this to null to disconnect the start connection.
Parameters
start the start Connector of the connection
Implemented in org.jhotdraw.draw.figure.LineConnectionFigure.
Referenced by org.jhotdraw.draw.handle.ConnectionStartHandle.connect(), org.jhotdraw.draw.handle.ConnectionStartHandle.disconnect(), org.jhotdraw.draw.tool.ConnectionTool.mouseReleased(), and org.jhotdraw.draw.handle.ConnectorHandle.trackEnd().
setStartPoint()
void org.jhotdraw.draw.figure.ConnectionFigure.setStartPoint (Point2D.Double p)
Sets the start point.
Implemented in org.jhotdraw.draw.figure.LineConnectionFigure.
Referenced by org.jhotdraw.draw.tool.ConnectionTool.mousePressed(), org.jhotdraw.draw.handle.ConnectionStartHandle.setLocation(), and org.jhotdraw.draw.handle.ConnectorHandle.trackStart().
updateConnection()
void org.jhotdraw.draw.figure.ConnectionFigure.updateConnection ()
Updates the start and end point of the figure and fires figureChanged events.
Implemented in org.jhotdraw.draw.figure.LineConnectionFigure, and org.jhotdraw.draw.figure.LabeledLineConnectionFigure.
Referenced by org.jhotdraw.draw.tool.ConnectionTool.mouseReleased(), org.jhotdraw.draw.handle.AbstractConnectionHandle.trackEnd(), and org.jhotdraw.draw.handle.ConnectorHandle.trackEnd().
The documentation for this interface was generated from the following file:
jhotdraw-core/src/main/java/org/jhotdraw/draw/figure/ConnectionFigure.java