jhotdraw: org.jhotdraw.draw.handle.Handle Interface Reference
org.jhotdraw.draw.handle.Handle Interface Reference
Public Member Functions
Figure getOwner ()
void setView (DrawingView view)
void addHandleListener (HandleListener l)
void removeHandleListener (HandleListener l)
Rectangle getBounds ()
Rectangle getDrawingArea ()
boolean contains (Point p)
void draw (Graphics2D g)
void invalidate ()
void dispose ()
Cursor getCursor ()
boolean isCombinableWith (Handle handle)
void trackStart (Point anchor, int modifiersEx)
void trackStep (Point anchor, Point lead, int modifiersEx)
void trackEnd (Point anchor, Point lead, int modifiersEx)
void trackDoubleClick (Point p, int modifiersEx)
void viewTransformChanged ()
Collection< Handle > createSecondaryHandles ()
String getToolTipText (Point p)
Detailed Description
A handle is used to change one aspect of a Figure by direct manipulation.
A handle is owned by a figure and associated to a DrawingView.
Handle
knows its owning figure and its associated drawing view.
Handles are drawn using the view coordinates of the associated DrawingView.
Handle
uses methods of the drawing view to translate the view coordinates into drawing coordinates, which is the coordinate system used by the owning figure.
Mouse and keyboard events of the user occur on a drawing view, and are preprocessed by the org.jhotdraw.draw.tool.DragTracker of a org.jhotdraw.draw.tool.SelectionTool.
DragTracker
invokes "track" methods on the handle, such as
trackStart
,
trackStep
and
trackEnd
.
Handle forwards
UndoableEdit
events to the drawing object onto which it is performing changes.
Design Patterns
Framework
The following interfaces define the contracts of a framework for structured drawing editors:
Contract: Drawing, Figure, DrawingView, DrawingEditor, Handle and org.jhotdraw.draw.tool.Tool.
Observer
State changes of handles can be observed by other objects. Specifically
DrawingView
observes area invalidations and remove requests of handles.
Subject: Handle; Observer: org.jhotdraw.draw.event.HandleListener; Event: org.jhotdraw.draw.event.HandleEvent; Concrete Observer: org.jhotdraw.draw.DrawingView.
Chain of responsibility
Mouse and keyboard events of the user occur on the drawing view, and are preprocessed by the
DragTracker
of a
SelectionTool
. In turn
DragTracker
invokes "track" methods on a
Handle
which in turn changes an aspect of a figure.
Client: org.jhotdraw.draw.tool.SelectionTool; Handler: org.jhotdraw.draw.tool.DragTracker, Handle.
Author
Werner Randelshofer
Version
$Id$
Member Function Documentation
addHandleListener()
void org.jhotdraw.draw.handle.Handle.addHandleListener (HandleListener l)
Adds a listener for this handle.
Implemented in org.jhotdraw.draw.handle.AbstractHandle.
Referenced by org.jhotdraw.draw.tool.DefaultHandleTracker.activate().
contains()
boolean org.jhotdraw.draw.handle.Handle.contains (Point p)
Tests if a point is contained in the handle.
Implemented in org.jhotdraw.draw.handle.TextOverflowHandle, org.jhotdraw.draw.handle.BoundsOutlineHandle, org.jhotdraw.draw.handle.BezierOutlineHandle, and org.jhotdraw.draw.handle.AbstractHandle.
createSecondaryHandles()
Collection<Handle> org.jhotdraw.draw.handle.Handle.createSecondaryHandles ()
Creates secondary handles.
Implemented in org.jhotdraw.draw.handle.BezierNodeHandle, org.jhotdraw.draw.handle.AbstractHandle, and org.jhotdraw.draw.handle.AbstractConnectionHandle.
dispose()
void org.jhotdraw.draw.handle.Handle.dispose ()
Disposes the resources acquired by the handler.
Implemented in org.jhotdraw.draw.handle.BezierNodeHandle, org.jhotdraw.draw.handle.BezierControlPointHandle, and org.jhotdraw.draw.handle.AbstractHandle.
draw()
void org.jhotdraw.draw.handle.Handle.draw (Graphics2D g)
Draws this handle. Note: The handle is drawn with the coordinate system of the DrawingView.
Implemented in org.jhotdraw.draw.handle.TextOverflowHandle, org.jhotdraw.draw.handle.RoundRectangleRadiusHandle, org.jhotdraw.draw.handle.OrientationHandle, org.jhotdraw.draw.handle.NullHandle, org.jhotdraw.draw.handle.MoveHandle, org.jhotdraw.draw.handle.FontSizeHandle, org.jhotdraw.draw.handle.ConnectorHandle, org.jhotdraw.draw.handle.CloseHandle, org.jhotdraw.draw.handle.BoundsOutlineHandle, org.jhotdraw.draw.handle.BezierScaleHandle, org.jhotdraw.draw.handle.BezierOutlineHandle, org.jhotdraw.draw.handle.BezierNodeHandle, org.jhotdraw.draw.handle.BezierControlPointHandle, org.jhotdraw.draw.handle.AbstractRotateHandle, org.jhotdraw.draw.handle.AbstractHandle, and org.jhotdraw.draw.handle.AbstractConnectionHandle.
getBounds()
Rectangle org.jhotdraw.draw.handle.Handle.getBounds ()
Returns the bounding box of the handle. Note: The bounding box must be returned in the coordinate system of the DrawingView.
Implemented in org.jhotdraw.draw.handle.AbstractHandle.
getCursor()
Cursor org.jhotdraw.draw.handle.Handle.getCursor ()
Returns a cursor for the handle.
Implemented in org.jhotdraw.draw.handle.NullHandle, org.jhotdraw.draw.handle.MoveHandle, org.jhotdraw.draw.handle.FontSizeHandle, org.jhotdraw.draw.handle.CloseHandle, and org.jhotdraw.draw.handle.AbstractHandle.
Referenced by org.jhotdraw.draw.tool.DefaultHandleTracker.activate(), and org.jhotdraw.draw.tool.AbstractTool.updateCursor().
getDrawingArea()
Rectangle org.jhotdraw.draw.handle.Handle.getDrawingArea ()
Returns the drawing area of the handle. Note: The drawing area must be returned in the coordinate system of the DrawingView.
Implemented in org.jhotdraw.draw.handle.ConnectorHandle, and org.jhotdraw.draw.handle.AbstractHandle.
Referenced by org.jhotdraw.draw.AbstractDrawingView.setActiveHandle(), and org.jhotdraw.draw.DefaultDrawingView.setActiveHandle().
getOwner()
Figure org.jhotdraw.draw.handle.Handle.getOwner ()
Returns the owner of this handle.
Implemented in org.jhotdraw.draw.handle.TextOverflowHandle, org.jhotdraw.draw.handle.BezierOutlineHandle, org.jhotdraw.draw.handle.BezierNodeHandle, org.jhotdraw.draw.handle.BezierControlPointHandle, org.jhotdraw.draw.handle.AbstractHandle, and org.jhotdraw.draw.handle.AbstractConnectionHandle.
Referenced by org.jhotdraw.draw.AbstractDrawingView.getCompatibleHandles(), and org.jhotdraw.draw.DefaultDrawingView.getCompatibleHandles().
getToolTipText()
String org.jhotdraw.draw.handle.Handle.getToolTipText (Point p)
Returns a tooltip for the specified location.
Implemented in org.jhotdraw.draw.handle.TextOverflowHandle, org.jhotdraw.draw.handle.RoundRectangleRadiusHandle, org.jhotdraw.draw.handle.FontSizeHandle, org.jhotdraw.draw.handle.BezierNodeHandle, org.jhotdraw.draw.handle.BezierControlPointHandle, org.jhotdraw.draw.handle.AbstractRotateHandle, org.jhotdraw.draw.handle.AbstractHandle, and org.jhotdraw.draw.handle.AbstractConnectionHandle.
Referenced by org.jhotdraw.draw.tool.DelegationSelectionTool.getToolTipText().
invalidate()
void org.jhotdraw.draw.handle.Handle.invalidate ()
Invalidates the handle. This method informs its listeners that its current display box is invalid and should be refreshed.
Implemented in org.jhotdraw.draw.handle.AbstractHandle.
isCombinableWith()
boolean org.jhotdraw.draw.handle.Handle.isCombinableWith (Handle handle)
Returns true, if this handle is combinable with the specified handle. This method is used to determine, if multiple handles need to be tracked, when more than one figure is selected.
Implemented in org.jhotdraw.draw.handle.ConnectorHandle, org.jhotdraw.draw.handle.AbstractHandle, org.jhotdraw.draw.handle.AbstractConnectionHandle, org.jhotdraw.draw.handle.OrientationHandle, org.jhotdraw.draw.handle.BezierScaleHandle, org.jhotdraw.draw.handle.BezierNodeHandle, org.jhotdraw.draw.handle.BezierControlPointHandle, and org.jhotdraw.draw.handle.AbstractRotateHandle.
removeHandleListener()
void org.jhotdraw.draw.handle.Handle.removeHandleListener (HandleListener l)
Removes a listener for this handle.
Implemented in org.jhotdraw.draw.handle.AbstractHandle.
Referenced by org.jhotdraw.draw.tool.DefaultHandleTracker.deactivate().
setView()
void org.jhotdraw.draw.handle.Handle.setView (DrawingView view)
Sets the view of the handle.
Implemented in org.jhotdraw.draw.handle.AbstractHandle.
trackDoubleClick()
void org.jhotdraw.draw.handle.Handle.trackDoubleClick (Point p, int modifiersEx)
Tracks a double click.
Implemented in org.jhotdraw.draw.handle.BezierNodeHandle, and org.jhotdraw.draw.handle.AbstractHandle.
Referenced by org.jhotdraw.draw.tool.DelegationSelectionTool.handleDoubleClick().
trackEnd()
void org.jhotdraw.draw.handle.Handle.trackEnd (Point anchor, Point lead, int modifiersEx)
Tracks the end of the interaction.
Parameters
anchor the position where the interaction started
lead the current position
Implemented in org.jhotdraw.draw.handle.TextOverflowHandle, org.jhotdraw.draw.handle.RoundRectangleRadiusHandle, org.jhotdraw.draw.handle.OrientationHandle, org.jhotdraw.draw.handle.NullHandle, org.jhotdraw.draw.handle.MoveHandle, org.jhotdraw.draw.handle.FontSizeHandle, org.jhotdraw.draw.handle.ConnectorHandle, org.jhotdraw.draw.handle.CloseHandle, org.jhotdraw.draw.handle.BoundsOutlineHandle, org.jhotdraw.draw.handle.BezierScaleHandle, org.jhotdraw.draw.handle.BezierOutlineHandle, org.jhotdraw.draw.handle.BezierNodeHandle, org.jhotdraw.draw.handle.BezierControlPointHandle, org.jhotdraw.draw.handle.AbstractRotateHandle, and org.jhotdraw.draw.handle.AbstractConnectionHandle.
trackStart()
void org.jhotdraw.draw.handle.Handle.trackStart (Point anchor, int modifiersEx)
Tracks the start of the interaction. The default implementation does nothing.
Parameters
anchor the position where the interaction started
Implemented in org.jhotdraw.draw.handle.TextOverflowHandle, org.jhotdraw.draw.handle.RoundRectangleRadiusHandle, org.jhotdraw.draw.handle.OrientationHandle, org.jhotdraw.draw.handle.NullHandle, org.jhotdraw.draw.handle.MoveHandle, org.jhotdraw.draw.handle.FontSizeHandle, org.jhotdraw.draw.handle.ConnectorHandle, org.jhotdraw.draw.handle.CloseHandle, org.jhotdraw.draw.handle.BoundsOutlineHandle, org.jhotdraw.draw.handle.BezierScaleHandle, org.jhotdraw.draw.handle.BezierOutlineHandle, org.jhotdraw.draw.handle.BezierNodeHandle, org.jhotdraw.draw.handle.BezierControlPointHandle, org.jhotdraw.draw.handle.AbstractRotateHandle, and org.jhotdraw.draw.handle.AbstractConnectionHandle.
trackStep()
void org.jhotdraw.draw.handle.Handle.trackStep (Point anchor, Point lead, int modifiersEx)
Tracks a step of the interaction.
Parameters
anchor the position where the interaction started
lead the current position
Implemented in org.jhotdraw.draw.handle.TextOverflowHandle, org.jhotdraw.draw.handle.RoundRectangleRadiusHandle, org.jhotdraw.draw.handle.OrientationHandle, org.jhotdraw.draw.handle.NullHandle, org.jhotdraw.draw.handle.MoveHandle, org.jhotdraw.draw.handle.FontSizeHandle, org.jhotdraw.draw.handle.ConnectorHandle, org.jhotdraw.draw.handle.CloseHandle, org.jhotdraw.draw.handle.BoundsOutlineHandle, org.jhotdraw.draw.handle.BezierScaleHandle, org.jhotdraw.draw.handle.BezierOutlineHandle, org.jhotdraw.draw.handle.BezierNodeHandle, org.jhotdraw.draw.handle.BezierControlPointHandle, org.jhotdraw.draw.handle.AbstractRotateHandle, and org.jhotdraw.draw.handle.AbstractConnectionHandle.
viewTransformChanged()
void org.jhotdraw.draw.handle.Handle.viewTransformChanged ()
This method is invoked by the drawing view, when its transform has changed. This means, that DrawingView.viewToDrawing and DrawingView.drawingToView will return different values than they did before.
Implemented in org.jhotdraw.draw.handle.AbstractHandle.
The documentation for this interface was generated from the following file:
jhotdraw-core/src/main/java/org/jhotdraw/draw/handle/Handle.java