jhotdraw: org.jhotdraw.draw.figure.CompositeFigure Interface Reference
org.jhotdraw.draw.figure.CompositeFigure Interface Reference
Public Member Functions
boolean add (Figure child)
void add (int index, Figure child)
void basicAdd (Figure child)
void basicAdd (int index, Figure child)
boolean remove (Figure child)
Figure removeChild (int index)
void removeAllChildren ()
int basicRemove (Figure child)
Figure basicRemoveChild (int index)
void basicRemoveAllChildren ()
java.util.List< Figure > getChildren ()
int getChildCount ()
Figure getChild (int index)
int indexOf (Figure child)
boolean contains (Figure f)
Layouter getLayouter ()
void layout ()
void setLayouter (Layouter newValue)
void addCompositeFigureListener (CompositeFigureListener listener)
void removeCompositeFigureListener (CompositeFigureListener listener)
Public Member Functions inherited from org.jhotdraw.draw.figure.Figure
void draw (Graphics2D g)
int getLayer ()
boolean isVisible ()
void setBounds (Point2D.Double start, Point2D.Double end)
Point2D.Double getStartPoint ()
Point2D.Double getEndPoint ()
Rectangle2D.Double getBounds ()
Rectangle2D.Double getDrawingArea ()
Rectangle2D.Double getDrawingArea (double factor)
Dimension2DDouble getPreferredSize ()
boolean contains (Point2D.Double p)
Object getTransformRestoreData ()
void restoreTransformTo (Object restoreData)
void transform (AffineTransform tx)
public< T > void set (AttributeKey< T > key, T value)
public< T > T get (AttributeKey< T > key)
Map< AttributeKey<?>, Object > getAttributes ()
Object getAttributesRestoreData ()
void restoreAttributesTo (Object restoreData)
boolean isSelectable ()
boolean isRemovable ()
boolean isTransformable ()
Collection< Handle > createHandles (int detailLevel)
Cursor getCursor (Point2D.Double p)
Collection< Action > getActions (Point2D.Double p)
Tool getTool (Point2D.Double p)
String getToolTipText (Point2D.Double p)
boolean isConnectable ()
Connector findConnector (Point2D.Double p, ConnectionFigure prototype)
Connector findCompatibleConnector (Connector c, boolean isStartConnector)
Collection< Connector > getConnectors (ConnectionFigure prototype)
boolean includes (Figure figure)
Figure findFigureInside (Point2D.Double p)
Collection< Figure > getDecomposition ()
Figure clone ()
void remap (Map< Figure, Figure > oldToNew, boolean disconnectIfNotInMap)
void addNotify (Drawing d)
void removeNotify (Drawing d)
void willChange ()
void changed ()
void requestRemove ()
boolean handleDrop (Point2D.Double p, Collection< Figure > droppedFigures, DrawingView view)
boolean handleMouseClick (Point2D.Double p, MouseEvent evt, DrawingView view)
void addFigureListener (FigureListener l)
void removeFigureListener (FigureListener l)
void addPropertyChangeListener (PropertyChangeListener listener)
void removePropertyChangeListener (PropertyChangeListener listener)
Static Public Attributes
static final AttributeKey< Insets2D.Double > LAYOUT_INSETS = new AttributeKey<Insets2D.Double>("layoutInsets", Insets2D.Double.class, new Insets2D.Double())
Static Public Attributes inherited from org.jhotdraw.draw.figure.Figure
static final String CONNECTABLE_PROPERTY = "connectable"
static final String REMOVABLE_PROPERTY = "removable"
static final String SELECTABLE_PROPERTY = "selectable"
static final String TRANSFORMABLE_PROPERTY = "transformable"
Detailed Description
A composite figure is composed of several child Figures.
A composite figure can be laid out using a Layouter.
CompositeFigure
listens to
requestRemove
events sent by its child figures, and then removes the child figure which sent the event.
Design Patterns
Composite
Composite figures can be composed of other figures.
Component: Figure; Composite: CompositeFigure.
Observer
State changes of figures can be observed by other objects. Specifically
CompositeFigure
observes area invalidations and remove requests of its child figures. DrawingView also observes area invalidations of its drawing object.
Subject: Figure; Observer: org.jhotdraw.draw.event.FigureListener; Event: org.jhotdraw.draw.event.FigureEvent; Concrete Observer: CompositeFigure, DrawingView.
Observer
Changes in the composition of a composite figure can be observed.
Subject: CompositeFigure; Observer: org.jhotdraw.draw.event.CompositeFigureListener; Event: org.jhotdraw.draw.event.CompositeFigureEvent.
Strategy
Composite figures can be laid out using different layout algorithms which are implemented by layouters.
Context: CompositeFigure; Strategy: Layouter.
Author
Werner Randelshofer
Version
$Id$
Member Function Documentation
add() [1/2]
boolean org.jhotdraw.draw.figure.CompositeFigure.add (Figure child)
Adds a child to the figure.
This is a convenience method for
add(getChildCount(), child);
This method calls
figureAdded
on all registered
CompositeFigureListener
s.
Returns
true
if this CompositeFigure changed as a result of the call
Implemented in org.jhotdraw.draw.figure.LabeledLineConnectionFigure, org.jhotdraw.draw.figure.AbstractCompositeFigure, and org.jhotdraw.draw.Drawing.
add() [2/2]
void org.jhotdraw.draw.figure.CompositeFigure.add (int index, Figure child)
Adds a child to the figure at the specified index.
This method calls
figureAdded
on all registered
CompositeFigureListener
s.
Implemented in org.jhotdraw.draw.figure.LabeledLineConnectionFigure, org.jhotdraw.draw.figure.AbstractCompositeFigure, and org.jhotdraw.draw.Drawing.
addCompositeFigureListener()
void org.jhotdraw.draw.figure.CompositeFigure.addCompositeFigureListener (CompositeFigureListener listener)
Adds a listener for this composite figure.
Implemented in org.jhotdraw.draw.figure.LabeledLineConnectionFigure, and org.jhotdraw.draw.figure.AbstractCompositeFigure.
Referenced by org.jhotdraw.draw.DefaultDrawingViewTransferHandler.exportDone(), org.jhotdraw.draw.AbstractDrawingView.setDrawing(), and org.jhotdraw.draw.DefaultDrawingView.setDrawing().
basicAdd() [1/2]
void org.jhotdraw.draw.figure.CompositeFigure.basicAdd (Figure child)
Adds a child to the figure without firing events.
This method can be used to reinsert a child figure which has been temporarily removed from this CompositeFigure (for example to reorder the sequence of the children) and to efficiently build a drawing from an org.jhotdraw.draw.io.InputFormat.
This is a convenience method for calling
basicAdd(getChildCount(), child);
.
Implemented in org.jhotdraw.draw.figure.LabeledLineConnectionFigure, org.jhotdraw.draw.figure.AbstractCompositeFigure, and org.jhotdraw.draw.Drawing.
Referenced by org.jhotdraw.draw.action.GroupAction.groupFigures().
basicAdd() [2/2]
void org.jhotdraw.draw.figure.CompositeFigure.basicAdd (int index, Figure child)
Adds a child to the figure at the specified index without firing events.
This method can be used to reinsert a child figure which has been temporarily removed from this CompositeFigure (for example to reorder the sequence of the children) and to efficiently build a drawing from an org.jhotdraw.draw.io.InputFormat.
Implemented in org.jhotdraw.draw.QuadTreeDrawing, org.jhotdraw.draw.figure.QuadTreeCompositeFigure, org.jhotdraw.draw.figure.LabeledLineConnectionFigure, org.jhotdraw.draw.figure.AbstractCompositeFigure, org.jhotdraw.draw.Drawing, and org.jhotdraw.draw.DefaultDrawing.
basicRemove()
int org.jhotdraw.draw.figure.CompositeFigure.basicRemove (Figure child)
Removes the specified child without firing events.
This method can be used to temporarily remove a child from this CompositeFigure (for example to reorder the sequence of the children).
This is a convenience method for calling
basicRemove(indexOf(child));
.
Returns the index of the removed figure. Returns -1 if the figure was not a child of this CompositeFigure.
Implemented in org.jhotdraw.draw.figure.LabeledLineConnectionFigure, org.jhotdraw.draw.Drawing, and org.jhotdraw.draw.figure.AbstractCompositeFigure.
basicRemoveAllChildren()
void org.jhotdraw.draw.figure.CompositeFigure.basicRemoveAllChildren ()
Removes all children from the composite figure without firing events.
This method can be used to temporarily remove a child from this CompositeFigure (for example to reorder the sequence of the children).
This is a convenience method for
while(getChildCount() > 0) basicRemoveChild(0);
Implemented in org.jhotdraw.draw.figure.LabeledLineConnectionFigure, and org.jhotdraw.draw.figure.AbstractCompositeFigure.
Referenced by org.jhotdraw.draw.action.GroupAction.ungroupFigures().
basicRemoveChild()
Figure org.jhotdraw.draw.figure.CompositeFigure.basicRemoveChild (int index)
Removes the child at the specified index without firing events.
This method can be used to temporarily remove a child from this CompositeFigure (for example to reorder the sequence of the children).
Returns the removed child figure.
Implemented in org.jhotdraw.draw.QuadTreeDrawing, org.jhotdraw.draw.figure.QuadTreeCompositeFigure, org.jhotdraw.draw.figure.LabeledLineConnectionFigure, and org.jhotdraw.draw.figure.AbstractCompositeFigure.
contains()
boolean org.jhotdraw.draw.figure.CompositeFigure.contains (Figure f)
Returns true if this composite figure contains the specified figure.
This is a convenience method for calling
getChildren().contains(f);
.
Implemented in org.jhotdraw.draw.QuadTreeDrawing, org.jhotdraw.draw.figure.QuadTreeCompositeFigure, org.jhotdraw.draw.figure.LabeledLineConnectionFigure, and org.jhotdraw.draw.figure.AbstractCompositeFigure.
getChild()
Figure org.jhotdraw.draw.figure.CompositeFigure.getChild (int index)
Returns the child figure at the specified index.
This is a convenience method for calling
getChildren().get(index);
.
Implemented in org.jhotdraw.draw.figure.LabeledLineConnectionFigure, and org.jhotdraw.draw.figure.AbstractCompositeFigure.
getChildCount()
int org.jhotdraw.draw.figure.CompositeFigure.getChildCount ()
Returns the number of children.
This is a convenience method for calling
getChildren().size();
.
Implemented in org.jhotdraw.draw.figure.LabeledLineConnectionFigure, and org.jhotdraw.draw.figure.AbstractCompositeFigure.
Referenced by org.jhotdraw.draw.AbstractDrawingView.drawDrawing(), org.jhotdraw.draw.DefaultDrawingView.drawDrawing(), org.jhotdraw.draw.print.DrawingPageable.printPage(), and org.jhotdraw.draw.io.ImageOutputFormat.toImage().
getChildren()
java.util.List<Figure> org.jhotdraw.draw.figure.CompositeFigure.getChildren ()
Returns an unchangeable list view on the children.
Implemented in org.jhotdraw.draw.QuadTreeDrawing, org.jhotdraw.draw.figure.QuadTreeCompositeFigure, org.jhotdraw.draw.figure.LabeledLineConnectionFigure, and org.jhotdraw.draw.figure.AbstractCompositeFigure.
Referenced by org.jhotdraw.draw.layouter.HorizontalLayouter.calculateLayout(), org.jhotdraw.draw.layouter.LocatorLayouter.calculateLayout(), org.jhotdraw.draw.layouter.VerticalLayouter.calculateLayout(), org.jhotdraw.draw.DefaultDrawingViewTransferHandler.importData(), org.jhotdraw.draw.layouter.HorizontalLayouter.layout(), org.jhotdraw.draw.layouter.LocatorLayouter.layout(), org.jhotdraw.draw.layouter.VerticalLayouter.layout(), org.jhotdraw.draw.print.DrawingPageable.printPage(), org.jhotdraw.draw.io.SerializationInputOutputFormat.read(), org.jhotdraw.draw.AbstractDrawingView.selectAll(), org.jhotdraw.draw.DefaultDrawingView.selectAll(), and org.jhotdraw.draw.action.GroupAction.ungroupFigures().
getLayouter()
Layouter org.jhotdraw.draw.figure.CompositeFigure.getLayouter ()
Get a Layouter object which encapsulated a layout algorithm for this figure. Typically, a Layouter accesses the child components of this figure and arranges their graphical presentation.
Returns
layout strategy used by this figure
Implemented in org.jhotdraw.draw.figure.LabeledLineConnectionFigure, and org.jhotdraw.draw.figure.AbstractCompositeFigure.
indexOf()
int org.jhotdraw.draw.figure.CompositeFigure.indexOf (Figure child)
Returns the index of the specified child.
This is a convenience method for calling
getChildren().indexOf(index);
.
Returns
The index of the child, or -1 if the specified figure is not a child of this CompositeFigure.
Implemented in org.jhotdraw.draw.QuadTreeDrawing, org.jhotdraw.draw.figure.QuadTreeCompositeFigure, org.jhotdraw.draw.DefaultDrawing, org.jhotdraw.draw.figure.LabeledLineConnectionFigure, and org.jhotdraw.draw.figure.AbstractCompositeFigure.
Referenced by org.jhotdraw.draw.AbstractDrawingView.delete(), org.jhotdraw.draw.DefaultDrawingView.delete(), org.jhotdraw.draw.action.GroupAction.groupFigures(), and org.jhotdraw.draw.action.GroupAction.ungroupFigures().
layout()
void org.jhotdraw.draw.figure.CompositeFigure.layout ()
A layout algorithm is used to define how the child components should be laid out in relation to each other.
This method first calls layout() on all child figures which implement the CompositeFigure interface. Then the children are laid out.
The task for laying out the child figures is delegated to a Layouter which can be plugged in at runtime.
Implemented in org.jhotdraw.draw.figure.LabeledLineConnectionFigure, and org.jhotdraw.draw.figure.AbstractCompositeFigure.
Referenced by org.jhotdraw.draw.figure.AbstractCompositeFigure.layout().
remove()
boolean org.jhotdraw.draw.figure.CompositeFigure.remove (Figure child)
Removes the specified child. Returns true, if the Figure contained the removed child.
This is a convenience method for calling
removeChild(getChildren().indexOf(child));
This method calls
figureRemoved
on all registered
CompositeFigureListener
's.
Implemented in org.jhotdraw.draw.figure.LabeledLineConnectionFigure, org.jhotdraw.draw.figure.AbstractCompositeFigure, and org.jhotdraw.draw.Drawing.
removeAllChildren()
void org.jhotdraw.draw.figure.CompositeFigure.removeAllChildren ()
Removes all children from the composite figure.
This is a convenience method for
while(getChildCount() > 0) removeChild(0);
Implemented in org.jhotdraw.draw.figure.LabeledLineConnectionFigure, and org.jhotdraw.draw.figure.AbstractCompositeFigure.
removeChild()
Figure org.jhotdraw.draw.figure.CompositeFigure.removeChild (int index)
Removes the child at the specified index. Returns the removed child figure.
Calls
figureRemoved
on all registered
CompositeFigureListener
's.
Implemented in org.jhotdraw.draw.figure.LabeledLineConnectionFigure, and org.jhotdraw.draw.figure.AbstractCompositeFigure.
removeCompositeFigureListener()
void org.jhotdraw.draw.figure.CompositeFigure.removeCompositeFigureListener (CompositeFigureListener listener)
Removes a listener from this composite figure.
Implemented in org.jhotdraw.draw.figure.LabeledLineConnectionFigure, and org.jhotdraw.draw.figure.AbstractCompositeFigure.
Referenced by org.jhotdraw.draw.DefaultDrawingViewTransferHandler.exportDone(), org.jhotdraw.draw.AbstractDrawingView.setDrawing(), and org.jhotdraw.draw.DefaultDrawingView.setDrawing().
setLayouter()
void org.jhotdraw.draw.figure.CompositeFigure.setLayouter (Layouter newValue)
Set a Layouter object which encapsulated a layout algorithm for this figure. Typically, a Layouter accesses the child components of this figure and arranges their graphical presentation. It is a good idea to put the Layouter in the protected initialize() method so it can be recreated if a GraphicalCompositeFigure is read and restored from a StorableInput stream.
Parameters
newValue encapsulation of a layout algorithm.
Implemented in org.jhotdraw.draw.figure.LabeledLineConnectionFigure, and org.jhotdraw.draw.figure.AbstractCompositeFigure.
Member Data Documentation
LAYOUT_INSETS
final AttributeKey<Insets2D.Double> org.jhotdraw.draw.figure.CompositeFigure.LAYOUT_INSETS = new AttributeKey<Insets2D.Double>("layoutInsets", Insets2D.Double.class, new Insets2D.Double()) static
The value of this attribute is a Insets2D.Double object.
Referenced by org.jhotdraw.draw.layouter.AbstractLayouter.getInsets(), and org.jhotdraw.draw.figure.ListFigure.ListFigure().
The documentation for this interface was generated from the following file:
jhotdraw-core/src/main/java/org/jhotdraw/draw/figure/CompositeFigure.java